export const DE = {
    Translator: "Übersetzer",
    TranslatorName: "v1rul3nt, Quiipy, Xerex, Wehraboo",
    Language: "Sprache",
    ThisLanguage: "Deutsch",
    OK: "OK",
    SteelMill: "Stahlwerk",
    StainlessSteelPlant: "Edelstahl-Fabrik",
    CircuitFoundry: "Schaltkreis-Fabrik",
    IntegratedCircuit: "integrierte Schaltung",
    OilWell: "Ölplattform",
    Wood: "Holz",
    LoggingCamp: "Forstbetrieb",
    LumberMill: "Sägewerk",
    Lumber: "Nutzholz",
    Paper: "Papier",
    PaperMill: "Papier-Fabrik",
    Book: "Buch",
    BookPublisher: "Buchverlag",
    OilRefinery: "Öl-Raffinerie",
    Sell: "Verkaufen",
    Upgrade: "Verbessern",
    Build: "Bauen",
    Buildings: "Gebäude",
    Iron: "Eisen",
    FuelType: "Wählen Sie einen Kraftstoff",
    FuelCost: "Kraftstoffkosten",
    FuelEconomy: "Kraftstoffverbrauch",
    FuelInStorage: "%{fuel} im Lager",
    Plastic: "Kunststoff",
    Petrol: "Benzin",
    Buy: "Kaufen",
    NoLiquidity: "Zahlungsunfähig",
    NoLiquidityTurnOffAutoSell:
        "Es gibt nicht genügend Nachfrage für %{res}, der automatische Verkauf wurde abgestellt.",
    Multiplier: "Multiplikator",
    MultiplierDesc: "Alle 10, erhältst du +1 Multiplikator",
    SellBuilding: "Gebäude verkaufen",
    PowerGrid: "Stromversorgung",
    SortBy: "sortieren nach",
    SortByPrice: "Wert",
    SortByAmount: "Menge",
    NotEnoughResources: "Unzureichende Ressourcen für diese Aktion",
    Transportation: "Transport",
    Cash: "Geld",
    Aluminum: "Aluminium",
    ResearchPoint: "Forschungspunkte",
    Unlock: "freischalten",
    BuildingUnlocked: "%{building} wurde freigeschalten",
    Science: "Wissenschaftspunkte",
    ScienceFromPowerDesc: "Stormerzeuger produzieren eine kleine Menege Wissenschaftspunkte, solange sie aktiv sind",
    Culture: "Kultur",
    School: "Schule",
    University: "Universität",
    Polytechnic: "Fachhochschule",
    Colosseum: "Kolosseum",
    WindTurbine: "Windkraftanlage",
    Engine: "Motor",
    EngineFactory: "Motoren-Fabrik",
    CameraFactory: "Kamera-Fabrik",
    Camera: "Kamera",
    Gun: "Waffe",
    GunFactory: "Waffen-Fabrik",
    Aircraft: "Flugzeug",
    AircraftFactory: "Flugzeug-Fabrik",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Zeppelin-Fabrik",
    Tank: "Panzer",
    TankFactory: "Panzerwerk",
    CoalPowerPlant: "Kohlekraftwerk",
    PetrolPowerPlant: "Ölkraftwerk",
    Copper: "Kupfer",
    Gas: "Erdgas",
    GasPump: "Erdgasförderwerk",
    GasPowerPlant: "Gaskraftwerk",
    Missile: "Fernlenkgeschoss",
    MissileFactory: "Fernlenkgeschoss-Fabrik",
    Rocket: "Rakete",
    RocketFactory: "Raketen-Fabrik",
    BuildingPermit: "Baugenehmigung",
    BuildingPermitDesc:
        "Du hast die Baugenehmigung für %{amount} Gebäude, davon hast du bereits %{amountBuilt} gebaut und %{amountLeft} sind noch übrig",
    BuildingLocked: "Das Gebäude ist noch nicht verfügbar, du musst es zuerst im Forschungslabor freischalten",
    MaxBuilders: "Max Baumeister",
    MaxBuildersDesc: "Anzahl der Gebäude die du gleichzeitig bauen kannst",
    Silicon: "Silizium",
    AluminumMine: "Aluminium-Mine",
    CopperMine: "Kupfer-Mine",
    SiliconMine: "Silizium-Mine",
    IronMine: "Eisen-Mine",
    CoalMine: "Kohle-Mine",
    Headquarter: "Hauptquartier",
    ResearchLab: "Forschungslabor",
    TradeCenter: "Handelszentrum",
    Resources: "Ressourcen",
    NotEnoughCash: "Nicht genug Geld für diese Aktion",
    NotEnoughSwissMoney: "Nicht genug Schweizer Franken für diese Aktion",
    BuildingNotEnoughFuel: "💡 Nicht genug %{fuel}",
    AutoSell: "Auto verkaufen",
    Change: "ändern",
    StatisticsBureau: "Statistik-Agentur",
    LogisticsDepartment: "Logistik-Institut",
    From: "Von",
    Top20FuelCost: "Top 20 Kraftstoffverbraucher",
    To: "Zu",
    TransportTime: "Transportdauer",
    Warehouse: "Lagerhaus",
    TradeWarehouse: "Handelslager",
    Coal: "Kohle",
    Video: "Video",
    ClothingFactory: "Kleidungs-Fabrik",
    Clothes: "Kleidung",
    Fashion: "Mode",
    FashionFactory: "Modedesigner",
    VideoFarm: "Video-Fabrik",
    SantaFactory: "Santa-Fabrik",
    Santa: "Santa",
    Car: "Auto",
    CarFactory: "Auto-Fabrik",
    Ship: "Schiff",
    SolarPanel: "Solarmodul",
    SolarPanelDesc: "💡 Solarmodule arbeiten nur 5 von 10 Sekunden - alle Kreisläufe sind verbunden",
    WindTurbineDesc:
        "💡 Windkraftanlagen arbeiten nur 8 von 10 Sekunden - Die Stromkreisläufe sind nicht miteinander verbunden",
    Movie: "Film",
    MovieStudio: "Filmstudio",
    Sitcom: "Sitcom",
    TVStudio: "TV-Studio",
    PC: "PC",
    GameStudio: "Game-Studio",
    Game: "Game",
    ComputerFactory: "Computerfabrik",
    Shipyard: "Werft",
    PowerUsage: "Energieverbrauch",
    PowerSupply: "Energieerzeugung",
    Level: "Stufe",
    Power: "Energie",
    CentralBank: "Zentralbank",
    ResourceInput: "Eingang",
    ResourceOutput: "Ausgang",
    ResourceStorage: "Lager",
    ResourceChange: "Wechsel",
    ResourceInOutDesc:
        "💡 Klicke oben auf die Out-In-Nummern, um die entsprechenden Ausgangs- und Eingangsgebäude zu markieren",
    MarketUpdateIn: "Marktpreisupdate in %{time}",
    Semiconductor: "Halbleiter",
    SemiconductorFactory: "Halbleiter-Fabrik",
    Steel: "Stahl",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin-Farm",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin-Farm",
    Guitar: "Gitarre",
    GuitarFactory: "Gitarren-Fabrik",
    Drum: "Schlagzeug",
    DrumFactory: "Schlagzeug-Fabrik",
    RecordingStudio: "Tonstudio",
    OperaHouse: "Opernhaus",
    CoalGasificationPlant: "Kohle-Vergasungsanlage",
    GasProcessingPlant: "Gas-Veredelungsanlage",
    Music: "Musik",
    Glass: "Glas",
    PhoneFactory: "Smartphone-Fabrik",
    Phone: "Smartphone",
    GlassFactory: "Glasmanufaktur",
    Oil: "Öl",
    Chromium: "Chrom",
    ChromiumMine: "Chrom-Mine",
    Uranium: "Uran",
    EnrichedUranium: "angereichertes Uran",
    NuclearPowerPlant: "Kernkraftwerk",
    UraniumEnrichmentPlant: "Uran-Anreicherungsanlage",
    UraniumMine: "Uran-Mine",
    Titanium: "Titan",
    TitaniumMine: "Titan-Mine",
    TitaniumAlloyPlant: "Titan-Manufaktur",
    ChromiumAlloyPlant: "Chrom-Manufaktur",
    Input: "Eintrag",
    PanelPosition: "Panel Position",
    PanelPositionDesc:
        "Anzeige des Seitenpanels links, rechts oder automatisch (entsprechend des aktuell ausgewählten Feldes)",
    Output: "Produktion",
    OutputCapacity: "produzierte Materialien",
    ResourceDeposit: "Ressourcen Absatz",
    AdjacentBonus: "Angrenzungsbonus",
    AdjacentBonusDesc:
        "Du erhältst %{bonus}% zusätzliche Kapazität für jedes angrenzende und arbeitende Gebäude der selben Art",
    ConsiderIncreaseProduction: "💡 Versuche %{resource} Produktionserhöhrung",
    AlwaysTransportInput: "Vorratsmodus",
    AlwaysTransportInputDesc: "Transportiere benötigte Ware immer, auch wenn es mehr ist als benötigt",
    ProductionCycleLength: "Produktionszyklus",
    ProductionCycleLengthDesc:
        "Dauer eines Produktionszyklus in Sekunden. Eine Verlängerung des Zyklus erhöht entsprechend die benötigen und hergestellten Waren",
    MaxInputDistance: "Max. Importentfernung",
    MaxInputDistanceDesc:
        "Die maximale Distanz des Gebäudes woher Rohstoffe bezogen werden, gemessen in Zellenanzahlen",
    AutoSellCapacity: "automatische Verkaufsmenge",
    AutoSellCapacityDesc: "Maximale Anzahl an Ressourcen die automatisch verkauft werden können pro Sekunde/Ressource",
    CurrentAutoSellCapacityMultiplier: "Aktueller Multiplikator: x%{n}",
    AutoSellConcurrency: "automatische Verkaufsanzahl",
    AutoSellConcurrencyDesc: "Maximale Anzahl der Ressourcen die gleichzeit automatisch verkauft werden können",
    MaxAutoSellConcurrencyReached:
        "Du hast die maximale automatische Verkaufsanzahl erreicht, schalte eine andere ab um diese zu aktivieren",
    WallStreet: "Wall Street",
    MarketCap: "Marktkapitalisierung",
    MarketCapDesc: "Gesamtkapital (i.e. Marktwert) deiner Organisation",
    BuildingValuation: "Gebäudewert",
    BuildingValuationDesc: "Gesamtwert deiner Gebäude, inklusive Baugenehmigungen und Aufwertungen",
    ResourcesValuation: "Ressourcenwert",
    ResourcesValuationDesc: "Gesamtwert der Ressourcen im Inventar",
    Battery: "Batterie",
    BatteryFactory: "Batterie-Fabrik",
    RatingBuy: "Kaufen",
    RatingSell: "Verkaufen",
    SwissShop: "Schweizer Bank",
    RatingHold: "Durchschnittlich",
    RatingOutperform: "Überdurchschnittlich",
    RatingUnderperform: "Unterdurchschnittlich",
    StockRating: "Unternehmensbewertung",
    JetEngine: "Düsentriebwerk",
    Helicopter: "Helikopter",
    Lithium: "Lithium",
    LithiumMine: "Lithium-Mine",
    LiionBatteryFactory: "Lithium-Ionen-Batterie-Fabrik",
    HelicopterFactory: "Helikopter-Fabrik",
    Satellite: "Satellit",
    ToyFactory: "Spielzeug-Fabrik",
    Toy: "Spielzeug",
    SpaceStation: "Weltraumstation",
    SpaceStationFactory: "Weltraumstations-Fabrik",
    OperatingSystem: "Betriebssystem",
    OperatingSystemCompany: "Betriebssystem-Hersteller",
    LinuxDistribution: "Linux Vertrieb",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Konsole",
    ConsoleFactory: "Konsolen-Fabrik",
    Train: "Zug",
    TrainFactory: "Zug-Fabrik",
    ShoeFactory: "Schuh-Fabrik",
    Shoes: "Schuhe",
    ArtilleryFactory: "Artillerie-Fabrik",
    Artillery: "Artillerie",
    SubmarineFactory: "U-Boot-Fabrik",
    Submarine: "U-Boot",
    Spaceship: "Raumschiff",
    RobotFactory: "Roboter-Fabrik",
    Robot: "Roboter",
    SpaceshipFactory: "Raumschiff-Fabrik",
    SatelliteFactory: "Satelliten-Fabrik",
    JetEngineFactory: "Düsentriebwerks-Fabrik",
    StockRatingDesc:
        "Die Aktienwertung beruht auf Wall Street-Auswertungen, wirkt sich auf deine Marktobergrenze aus und aktualisiert sich zusammen mit dem Handel",
    OfflineEarning: "Offline-Einkommen",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline-Erwerbszeit",
    OfflineEarningTimeDesc: "Du erhältst Offline-Einkommen bis zu diesem Schwellenwert",
    BuyPermit: "Kauferlaubis",
    Settings: "Einstellungen",
    Sound: "Sound-Effekt",
    SoundDesc: "Aktivieren Sie Soundeffekte wie Klick- oder Fehlersound",
    MusicDesc: "Musik einschalten: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Symbole",
    MisplacedBuilding: "⛔ Das %{building} wird nicht auf die richtige Ressource gelegt",
    HighlightBuildings: "Gebäude hervorheben",
    HighlightTurnedOff: "... sind abgeschaltet",
    HighlightStockpileModeOn: "...die den Lagermodus aktiviert haben",
    HighlightProductionCycleNotDefault: "...diese haben Produktionszyklus > 1",
    HighlightMaxInputDistanceNotDefault: "...haben die maximale Eingangsentfernung < ∞",
    HighlightNotMakingProfit: "...machen keinen Gewinn",
    NBuildingsAreHighlighted: "%{n} Gebäude sind hervorgehoben",
    TurnOffProduction: "Stilllegen",
    TurnOffProductionDesc:
        "Schalten Sie die Produktion des Gebäudes aus. Das Gebäude wird keine Ressourcen mehr transportieren und keinen Strom verbrauchen",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "unbegrenzt",
    Transport: "transport",
    TileModifier: "Zellen-Modifikator",
    ShowAllModifiers: "Alle Modifikatoren anzeigen",
    HideAllModifiers: "Alle Modifikatoren ausblenden",
    NumberOfBuildings: "Anzahl der Gebäude, die Sie haben",
    ShowContent: "Inhalt zeigen",
    HideContent: "Inhalt ausblenden",
    BuyExpansionPack: "Kaufen für %{price}",
    Cities: "Städte",
    InputStrategy: "Eingangsstrategie",
    InputStrategyClose: "Näher",
    InputStrategyCloseDesc: "Bevorzugen Sie das nächstgelegene Lager mit genügend Ressourcen",
    InputStrategyFar: "Weiter",
    InputStrategyFarDesc: "Bevorzugen Sie das am weitesten entfernte Lager mit genügend Ressourcen",
    InputStrategyAmount: "Menge",
    InputStrategyAmountDesc:
        "Bevorzugen Sie das Lager mit der größten Menge an Ressourcen, unabhängig von der Entfernung",
    FuelCostSave: "Kraftstoffkosten sparen",
    FuelCostSaveDescV2:
        "Lagerhäuser lagern einen bestimmten Prozentsatz an Treibstoff für den Transport von Ressourcen ein. Im Vergleich zu anderen Gebäuden: Je höher die Stufe, desto mehr lagern sie ein",
    SoftwareCompany: "Software-Unternehmen",
    Software: "Software",
    ScreenFactory: "Bildschirm-Fabrik",
    Screen: "Bildschirm",
    JoinDiscord: "Besuchen Sie unseren Discord-Server, um die neuesten Updates, Tipps und Diskussionen zu erhalten",
    ClaimOfflineEarning: "Offline-Einnahmen abholen",
    OfflineTime: "Offline-Zeit",
    Minutes: "%{time}min",
    MaxUpgrade: "Maximale Stufe",
    MaxUpgradeDesc: "Sie haben die maximale Stufe erreicht",
    ClaimAmount: "Geld +%{amount}",
    EffectiveTime: "Effektive Zeit",
    EffectiveTimeDesc: "Ihre effektive Offline-Verdienstzeit ist begrenzt %{time}min.",
    BuildSearchPlaceholder: "Geben Sie Gebäude oder Ressource für die Suche ein",
    MineOverlayWarning: "%{building} wird vom Zellenmodifikator nicht beeinflusst",
    WholesaleCenter: "Großhandelszentrum",
    OrderFrom: "Bestellung von %{name}",
    ExpireIn: "läuft aus in",
    Reward: "Belohnung",
    PerSecond: "%{time}/s",
    PolicyPoint: "Richtlinienpunkte",
    PolicyPointDesc: "💡 Je mehr Richtlinien aktiv sind, desto höher sind die Kosten für jede Richtlinie",
    NextOrderIn: "Nächste Bestellung in",
    FillOrder: "Auftrag erfüllen",
    RejectOrder: "Ablehnen",
    WholesaleCenterLocked:
        "Du brauchst mindestens %{required} verschiedene Ressourcen zum Freischalten des Großhandelszentrums. Du hast nur %{current} der benötigten Ressourcen",
    OrderFilled: "Die Bestellung von %{from} wurde erfolgreich ausgeliefert!",
    PolicyCenter: "Bundestag",
    NewOrder: "Eine neue Bestellung von %{from} ist angekommen, nachzusehen im  Großhandelszentrum",
    Policies: "Richtlinien",
    PolicyNotEnoughTime: "Sie haben nicht genügend Richtlinien-Punkte für diese Richtlinie",
    WholesaleCenterOrderFasterDesc:
        "Das Großhandelszentrum erhält Bestellungen 2x schneller und die Bestellgröße ist 2x größer",
    PolicyOilWellPowerx2: "Verdopple Ölquelle",
    PolicyOilWellPowerx2Desc: "Ölquellen produzieren 2x Öl und 2x verbrauchen Strom",
    HalfTransportSpeed: "Verlangsamen, um zu sparen",
    HalfTransportSpeedDesc:
        "Die Transportgeschwindigkeit wird um 25% verlangsamt und die Kraftstoffkosten um 25% gesenkt.",
    RefineryMoreOil: "Mehr Kraftstoff Mehr Probleme",
    RefineryMoreOilDesc: "Ölraffinerien produzieren 50% mehr Benzin und 50% weniger Kunststoff",
    RefineryMorePlastic: "Mehr Plastic Mehr Probleme",
    RefineryMorePlasticDesc: "Ölraffinerien produzieren 50% weniger Benzin und 50% mehr Kunststoff",
    FreeOilTransportDesc: "Der Öltransport kostet keinen Kraftstoff, aber Ölquellen verbrauchen 2x Strom",
    SuperSteelMill: "Herzen aus Eisen",
    SuperSteelMillDesc: "Stahlwerke verbrauchen 50% weniger Kohle, aber 25% mehr Eisen und Strom",
    AlSemiconductor: "Al Schaltkreis",
    AlSemiconductorDesc: "Schaltungsgießereien verwenden Aluminium anstelle von Kupfer",
    CostSaver: "Kostenersparnis",
    CostSaverDesc: "Wenn der Eintrag eines Gebäudes mehr kostet als der Austrag, stellen Sie die Produktion ein",
    CostSaverBuildingDesc:
        "Die Kostensparrichtlinie ist aktiv. Die Produktion wird basierend auf ihrer Rentabilität automatisch ein- und ausgeschaltet",
    CostSaverBuildingWarning:
        "Die Kosteneinsparungsrichtlinie ist aktiv. Sie können die Produktion nicht manuell ändern",
    GlassUseCoal: "Schwarzes Glas",
    GlassUseCoalDesc: "Glasfabriken verbrauchen 50% mehr Kohle und 50% weniger Silizium",
    AdjacentBonusOnlyOutput: "Angrenzender Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Der Angrenzendungsbonus erfordert nicht mehr Eintrag, verbraucht aber mehr Strom und ist nur zu 50% effektiv",
    IronMine2xOutput: "Schwermetall",
    IronMine2xOutputDesc: "Eisenminen produzieren 2x Eisen, aber der Eisentransport kostet 2x Kraftstoff",
    SolarPanelAlwaysWork: "Die Sonne geht nie unter",
    SolarPanelAlwaysWorkDesc: "Solarzellen arbeiten 100% der Zeit, produzieren aber 60% weniger Strom",
    SteelScience: "Wissen durch Stahl",
    SteelScienceDesc: "Stahlwerke verbrauchen 2x Ressourcen und produzieren zusätzlich Wissenschaftspunkte",
    ShoppingSpree: "Einkaufsbummel",
    ShoppingSpreeDesc:
        "Wenn die Produktion einer Ressource nicht ausreicht, kaufen Sie den Mangelbetrag automatisch am Marktplatz (wenn die Ressource automatisch weiterverkauft wird, wird Sie ignoriert).",
    ShoppingSpreeTradeCenterDesc:
        "💡 Wenn die Einkaufsbummel Richtlinie aktiviert ist, kauft der Marktplatz automatisch Ressourcen, die knapp sind",
    ExtraPolicyPoints: "Politischer Lobbyist",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromlegierungsanlagen verwenden kein Lithium, sondern 2x Eisen",
    DoubleTileModifier: "Die Kraft der Natur",
    TileModifierOutputOnly: "Zellenmodifikator Plus",
    GasPlantPetrol: "Gasliquidator",
    GasPlantPetrolDesc: "Gaskraftwerke verwenden zusätzliches Gas zur Herstellung von Benzin",
    CoalPlantFuel: "Kohle Liquidator",
    CoalPlantFuelDesc: "Kohlekraftwerke verwenden zusätzliche Kohle zur Herstellung von Kraftstoff",
    Welcome: "Willkommen",
    SeeTutorialAgain: "Tutorial wiederholen",
    HelpTranslateTheGame: "Hilf das Spiel zu übersetzen",
    NextTutorial: "weiter",
    Tutorial1:
        "Industry Idle ist ein <em> Ressourcenmanagement </em> -Spiel, in dem Sie Fabriken bauen🏭, Waren produzieren📦 und Geld verdienen💸.<br><br>Lassen Sie uns einige grundlegende Konzepte durchgehen, um Ihnen den Einstieg zu erleichtern - es dauert nicht lange verspreche ich.",
    Tutorial2:
        "Alle Gebäude benötigen Strom⚡, du hast ein <em>Windrad</em> welches Strom erzeugt. Du kannst deine aktuelle Netzversorgung auf der linken Seite der oberen Leiste sehen.<br><br> Möglicherweise haben Sie bemerkt, dass Windkraftanlagen nur <em>80%</em> der Zeit arbeiten. Du kannst auch andere Kraftwerkstypen bauen, die dauerhaft Strom erzeugen.",
    Tutorial3:
        "Sie haben viele <em> Ressourcenablagerungen </em> auf der Karte. Um Ressourcen zu gewinnen, müssen Sie Minen <em> auf </em> der entsprechenden Lagerstätte errichten. <br> <br> Zum Beispiel haben Sie eine <em> Ölquelle🛢️ </em>, die <em extrahiert > Öl </em> aus einem Ölvorkommen. <br><br>  Ressourcenvorkommen sind unbegrenzt - Sie müssen sich keine Sorgen machen, dass sie aufgebraucht sind. Abgesehen von Minen können andere Gebäude auf jeder leeren Fliese gebaut werden.",
    Tutorial5:
        "Um Geld zu verdienen, müssen Sie Ihre Ressourcen über das Handelszentrum verkaufen. Aktivieren Sie dazu einfach <em> Automatischen Verkauf </em> für diese Ressource. <br><br>  Sie können Ressourcen auch auf dem Marktplatz kaufen. Denken Sie daran, <em> wenn Sie eine Ressource kaufen, erhöhen Sie den Preis </em> und wenn Sie eine Ressource verkaufen, senken Sie den Preis. <br> <br> Der Markt ist <em> unbeständig </ em > und der Preis 📈 ändert sich regelmäßig.",
    Tutorial6:
        "Um neue Gebäude zu bauen, müssen Sie diese zuerst im <em> Forschungslabor🧪 </em> freischalten. Das Forschungslabor wandelt auch Wissenschaft in Forschungspunkte um. <br> <br> Ihre Windkraftanlage (und andere Kraftwerke) produziert beim Betrieb eine kleine Menge Wissenschaft. Und Sie können eine Schule und andere spezielle Gebäude bauen, um die Wissenschaft später anzukurbeln. <br> <br> Jetzt haben Sie alle Grundlagen gelernt und beginnen, Ihre Wirtschaft aufzubauen! Hier sind einige <em> Geldmittel💸 </em> und <em> Benzin </em>, um Ihnen eine Starthilfe zu geben.",
    WelcomePlay: "Spielen",
    WelcomePlayMuted: "Spiel (🔇Musik)",
    Chat: "Chat",
    RestoreFromBackup: "Sicherung wiederherstellen",
    RestoreFromBackupFail:
        "Wiederherstellung aus der Steam Cloud fehlgeschalgen: sind Sie sicher das dort eine Sicherung existiert?",
    RestoreFromBackupTitle: "Bist du sicher?",
    RestoreFromBackupDesc:
        "Normalerweise müssen Sie keine Wiederherstellung aus der Cloud-Sicherung durchführen, es sei denn, Ihre lokale Speicherung geht verloren. Cloud-Backups sind etwas älter als Ihre lokale Sicherung",
    ChangeName: "Ändern",
    SaveName: "Speichern",
    NameValidationRule: "Ihr Name sollte nur Buchstaben und Zahlen enthalten und zwischen 5 und 15 Zeichen liegen",
    NameValidationRuleProfanity: "Ihr Name sollte keine Obszönitäten enthalten",
    ChatMessageRateLimit: "Sie können nur alle 10 Sekunden eine neue Chat-Nachricht senden",
    NameSaved: "Ihr Name wurde erfolgreich geändert",
    NoMessages: "Keine neue Nachrichten",
    Leaderboard: "Bestenliste",
    Name: "Name",
    Tips1: "Aktienbewertungen haben 5 Kriterien: Kaufen, Überperformance, Halten, Underperformance und Verkaufen",
    Tips2: "Gebäude stellen den Transport von Ressourcen ein, wenn bereits genug für die Produktion vorhanden ist, es sei denn, Sie aktivieren den Stapelmodus",
    Tips3: "Die Kraftstoffkosten für den Ressourcentransport werden durch die Entfernung und die Menge der Ressourcen bestimmt",
    Tips4: "Gebäude transportieren eine Ressource nur, wenn die auf der Karte gefundene Menge die Eingabekapazität überschreitet",
    Tips5: "Gebäude transportieren eine Ressource nur vom Großhandelszentrum, wenn der automatische Verkauf für diese Ressource deaktiviert ist",
    Tips6: "Sie können die Kraftstoffkosten für eine Ressource im entsprechenden Abschnitt zur Eingabekapazität anzeigen",
    Tips7: "Wenn Sie eine Ressource kaufen, erhöhen Sie den Preis. Wenn Sie eine Ressource verkaufen, senken Sie den Preis",
    Tips8: "Sie können das Diagramm für die Menge jeder Ressource und ihre zeitliche Änderung im Statistikbüro anzeigen",
    Tips9: "Die für ein Gebäude benötigten Forschungspunkte werden durch den Marktpreis seiner Inputressourcen bestimmt",
    Tips10: "Unterschiedliche Ressourcen werden auf dem Markt unterschiedlich bewertet - seien Sie immer auf Marktvschwankungen vorbereitet",
    Tips11: "Es ist eine gute Idee, immer Ihre Strom- und Kraftstoffversorgung zu überprüfen, bevor Sie Ihre Produktion erweitern",
    FPS30: "Energiesparmodus",
    OfflineModeDesc:
        "Es kann keine Verbindung zum Server hergestellt werden: Es werden keine Offline-Einnahmen generiert. Bitte überprüfe deine Internetverbindung",
    OptOut: "Abmelden",
    OptIn: "Zurücksetzen und aktivieren",
    LeaderboardOptOut: "Leaderboard-Deaktivierung",
    LeaderboardOptIn: "Bestenliste zurücksetzen und aktivieren",
    LeaderboardOptInDesc:
        "Ihre Daten müssen zurückgesetzt werden, bevor Sie die Bestenliste wieder aktivieren können. Sind Sie sicher?",
    RewardAdsFailed: "Das Belohnungsvideo wurde nicht abgeschlossen",
    OfflineEarningDoubleSuccess: "Sie haben Ihr Offline-Einkommen verdoppelt",
    FPS30Desc:
        "Wenn Sie den Energiesparmodus aktivieren, wird das Spiel mit 30 FPS anstelle von 60 FPS ausgeführt. Dadurch hält Ihr Akku länger",
    HighlightAll: '"%{type}"markieren',
    HighlightInput: "🔍 %{type} Verbraucher hervorheben",
    HighlightOutput: "🔍 %{type} Erzeuger hervorheben",
    RunOutIn: "Leer in %{time}",
    SwissBank: "Schweizer Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Wenn Sie in einer neuen Stadt beginnen, erhalten Sie %{money} 💵",
    RestorePurchases: "Einkäufe wiederherstellen",
    RestorePurchasesSuccess: "Ihre Einkäufe wurden wiederhergestellt",
    RestorePurchasesFailed: "Ihre Einkäufe wurden nicht wiederhergestellt",
    ExpansionPacks: "Erweiterungspakete",
    ExpansionPack1: "Erweiterungspaket 1",
    RequireExpansionPack1: "Erweiterungspaket 1",
    RequireExpansionPack1Desc: "Dies ist nur für das Erweiterungspaket 1 verfügbar",
    RequireAnyExpansionPack: "Erweiterungspakete exklusiv",
    RequireAnyExpansionPackDesc: "Für diese Funktion müssen Sie mindestens eines der Erweiterungspakete besitzen",
    HideRewardAd: "Belohnungsanzeigen ausblenden",
    HideRewardAdDesc:
        "Alle In-Game-Anzeigen sind optionale Belohnungsanzeigen. Dadurch werden alle Belohnungsanzeigen vor dem Spiel ausgeblendet.",
    HideDiscordBanner: "Discord Banner ausblenden",
    HideDiscordBannerDesc: "Ausblenden des Discord und Storefront-Banner im Hauptquartier",
    HideChat: "Chat-Nachrichten ausblenden",
    PurchaseFailed: "Der Kauf wurde nicht abgeschlossen",
    PurchaseSteamContinue: "Bitte beenden Sie Ihren Kauf bei Steam",
    PurchaseSuccess: "Der Kauf ist abgeschlossen, danke für Ihre Unterstützung",
    PrestigeCurrency: "Schweizer Franken 💵",
    RestartDesc:
        "💡 Willst du nur neu starten? Sie können oben auf Start in einer neuen Stadt tippen und Ihre aktuelle Stadt auswählen",
    PrestigeGoBack: "bleiben",
    ProductionMultiplier: "Produktionsmultiplikator",
    ProductionMultiplierDesc:
        "Steigerung der Produktionskapazität aller Gebäude (einschließlich Minen, Fabriken, Kraftwerke, Wissenschafts- und Kulturgebäude)",
    FuelCostDiscount: "Kraftstoffkostenrabatt",
    FuelCostDiscountDesc: "Gibt einen Rabatt auf die Kraftstoffkosten beim Transport von Ressourcen",
    AutoSellCapacityMultiplier: "Multiplikator für die automatische Verkaufskapazität",
    AutoSellCapacityMultiplierDesc:
        "Ein Multiplikator, der unabhängig von der aktuellen Kapazität auf Ihre automatische Verkaufskapazität angewendet wird",
    BuildingPermitCostDivider: "Kostenteiler für Baugenehmigungen",
    BuildingPermitCostDividerDesc: "Teilen Sie die Baugenehmigungskosten durch diesen Teiler",
    ExtraAdjacentBonus: "Zusätzlicher Benachbarungsbonus",
    ExtraAdjacentBonusDesc: "Zusätzliche Bonuskapazität für jedes benachbarte Arbeitsgebäude des gleichen Typs",
    PrestigeAlertTitle: "Bist du sicher?",
    PrestigeAlertContent:
        "Ihr Unternehmen wird aufgelöst. Sie werden %{amount} Schweizer Franken bekommen und eine neue Firma in %{city} gründen",
    PrestigeCurrencyDesc:
        "Dies ist das Geld auf Ihrem geheimen Schweizer Bankkonto. Sie können es mitnehmen, wenn Sie in einer neuen Stadt anfangen",
    Prestige: "Einzahlen",
    Cancel: "Abbrechen",
    SaveFileCorrupted: "Sicherung beschädigt",
    LoadGameError: "Spiel konnte nicht geladen werden",
    LoadGameErrorMessage: "Fehlermeldung: %{message}",
    LoadGameErrorDesc:
        "Bitte überprüfe deine Internetverbindung. Wenn das Problem weiterhin besteht, wenden Sie sich an den Support",
    ExpansionPackIncompatible:
        "Sie importieren einen Speicher mit Erweiterungspaketen, aber Ihr Spiel verfügt nicht über die erforderlichen Erweiterungspakete",
    CashIn: "Einzahlen",
    CurrentCity: "Aktuelle Stadt",
    CashInDesc:
        "Sie erhalten diesen Betrag auf Ihr Schweizer Bankkonto, wenn Sie in einer neuen Stadt beginnen. Er basiert auf dem Marktwert Ihres Unternehmens und muss %{amount} erreichen, bevor Sie Schweizer Franken verdienen können",
    CitySize: "Kartengröße",
    GridType: "Zellentyp",
    StartInThisCity: "Starte in %{city}",
    CityBonus: "Stadtbonus",
    ResourceTilePercentage: "Ressourcenkacheln",
    MapSquareGrid: "quadratisch",
    MapHexGrid: "hexagon",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li> Zeppelinfabriken sind freigeschaltet </li> <li> Halbleiterfabriken haben 2x Produktivität </li> <li> Werften haben 2x Kapazität </li> <li> Autofabriken haben 2x Kapazität </li> <li> Li-Ionen-Akkufabriken sind freigeschaltet </li> ",
    Toulouse: "Toulouse",
    Rome: "Rom",
    RomeBonus:
        "<li> Kolosseen sind freigeschaltet </li> <li> Kolosseen haben 2x Produktivität </li> <li> Beginnen Sie mit dem Policy Center der Stufe 5 </li> <li> Opernhäuser haben 2x Kapazität </li> <li> Aufnahmestudios produzieren auch Kultur </li> ",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li> Starte mit Forschungslabor Level 5 </li> <li> Fachhochschulen sind frei </li> <li> Fachhochschulen haben 2x Kapazität </li> <li> Schulen haben 2x Kapazität </li> <li> Universität haben 2x Produktivität </li> ",
    HideNotProducing: "Ressourcen ausblenden, die nicht produziert werden",
    SortByStorage: "Lager",
    SortByName: "Name",
    PlayerTrade: "Spielerhandel",
    AddTradeFail: "Fehler beim Hinzufügen Ihres Handels",
    AddTradeExceedMaximumTrade:
        "Sie können maximal %{number} aktive Handel haben, bitte fordern Sie zuerst einen ein, oder brechen einen ab.",
    AddTradeSuccess: "Ihr Handel wurde erfolgreich hinzugefügt",
    ClaimTradeFail: "Wenn Sie diesen Handel nicht beanspruchen konnten, versuchen Sie es später erneut",
    CancelTradeSuccess: "Ihr Handel wurde erfolgreich abgebrochen",
    CancelTradeFail: "Dieser Handel konnte nicht abgebrochen werden. Bitte versuchen Sie es später erneut",
    AcceptTradeFail: "Dieser Handel wurde nicht akzeptiert. Bitte versuchen Sie es später erneut",
    PlayerTradeBanner: "Handel Ressourcen mit anderen Spielern",
    PlayerTradeResource: "Ressource",
    PlayerTradeAmount: "Menge",
    PlayerTradePrice: "Preis $",
    PlayerTradeValue: "Wert $",
    PlayerTradeWaiting: "Warte...",
    AddTrade: "Handel hinzufügen",
    AcceptTrade: "akzeptieren",
    CancelTrade: "abbrechen",
    ClaimTrade: "erhalte",
    FailedToImportSave: "Fehler beim Importieren der Sicherung",
    CancelActiveTradeFirst: "Sie haben aktive Spieler-Handel, bitte stornieren / beanspruchen Sie diese zuerst",
    PlayerTradeQuotaExceed: "Dieser Handel hat Ihre Menge überschritten",
    PlayerTradeValidRange: "Entfernung: %{min} ~ %{max}",
    PlayerTradeQuota: "Menge übrig: %{value}",
    PlayerTradeUnavailable:
        "Sie brauchen mindestens eine Ressource in Produktion oder im Lager um mit anderen Spielern zu handeln",
    PlayerTradeToClaim: "Sie haben %{num} neue Handel zum abholen im Spielerhandel",
    PowerBank: "Stromspeicher",
    PowerBankBuildDesc: "Speichern Sie überschüssigen Strom und sorgen Sie für Stromversorgung bei Engpässen",
    WarehouseBuildDesc: "Transportieren und lagern Sie alle Ressourcen mit geringeren Kraftstoffkosten",
    PowerBankChargeSpeed: "Ladegeschwindigkeit",
    PowerBankPowerLeft: "Strom übrig",
    PowerBankMoreCapacity: "Batteriesparmodus",
    PowerBankMoreCapacityDesc: "Stromspeicher laden mit 50% Geschwindigkeit auf, haben aber 50% mehr Kapazität",
    PowerBankNotWorking: "⛔ Stromspeicher arbeiten nur neben einem Kraftwerk",
    ColorTheme: "Spielfarbthema",
    ColorThemeDesc: "Farbthema für Spielesymbole, Hervorhebung, Gitter und Hintergrund. ERFORDERT EINEN NEUSTART",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Siliziumminem produzieren 2x Silizium, aber benötigen 50% mehr Strom und die Transportkosten für Silizium sind 50% höher.",
    CoalMine2xOutput: "Industrielle Revolution",
    CoalMine2xOutputDesc:
        "Kohleminen produzieren 2x soviel Kohle, aber benötigen 50% mehr Strom und die Transportkosten für Kohle sind um 50% erhöht.",
    AlMine2xOutput: "Aluminumschmelze",
    AlMine2xOutputDesc: "Aluminumminem produzieren 2x soviel Aluminium und verbrauchen 2x soviel Strom.",
    LoggingCamp2xOutput: "Abholzung",
    LoggingCamp2xOutputDesc: "Forstbetriebe produzieren 2x soviel Holz und die Transportkosten werden verdoppelt.",
    PowerBankLeft: "Energiespeicher",
    ColorThemeEditor: "Farbschemen Editor",
    ColorThemeEditorDesc: "Du kannst im aktuellen Schema Farben überschreiben. Du hast aktuell %{num} überschrieben.",
    ColorThemeEditorSave: "Speichern",
    ColorThemeEditorReset: "Zurücksetzen",
    ColorThemeEditorResetAll: "Alle zurücksetzen",
    NewMessageMentions: "Eine neue Nachricht erwähnt Sie: %{message}",
    HideChatMentions: "Chat-Erwähnungen ausblenden",
    HideChatMentionsDesc:
        "Blenden Sie die Audio- und Toastbenachrichtigung aus, wenn eine Chat-Nachricht mich erwähnt,",
    AcceptTradeFailRateLimit: "Sie können nur einen Trade alle %{time} Sekunden akzeptieren",
    DowngradeBuilding: "Herabstufen",
    WarehouseAddInput: "Route hinzufügen",
    WarehouseTapToSelect: "Tippen Sie zur Auswahl auf die Karte...",
    WarehouseFindOnMap: "🔍 auf der Karte finden",
    WarehouseRemoveRoute: "entfernen",
    WarehouseAddRouteFail: "Route konnte nicht hinzugefügt werden: Die ausgewählte Kachel ist keine gültige Quelle",
    LevelN: "Level %{level}",
    Surplus: "Überschuss",
    Production: "Produktion",
    Consumption: "Verbrauch",
    WarehouseInputCapacityDescV2: "Gesamtkapazität des Eingangsstransports, gleichmäßig auf alle Strecken verteilt",
    PlayerCountryFlag: "Spielerflagge",
    PlayerCountryChooseFlag: "In alphabetischer Reihenfolge des Länderkürzels",
    WindTurbineAlwaysWork: "Der Wind wird stärker",
    WindTurbineAlwaysWorkDesc: "Windkraftanlagen arbeiten 100% der Zeit, produzieren aber 30% weniger Strom",
    BookPublisherScience: "Wissenschaftsliteratur",
    BookPublisherScienceDesc: "Buchverlage produzieren Wissenschaft statt Kultur",
    BatteryFuelEconomy: "Wiederaufladbare Batterie",
    BatteryFuelEconomyDesc:
        "Der Kraftstoffverbrauch der Batterie verbessert sich um 100% (daher 50% Kraftstoffkosten).",
    ShowTheoreticalInputOutputCapacity: "Zeigen Sie die theoretische Eingangs- / Ausgabekapazität an",
    SpecialTransportCost: "Ressourcen mit besonderen Transportkosten",
    FreeTransportCost: "Ressourcen mit kostenlosen Transportkosten",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Ressourcen erscheinen in der Regel in Clustern.</li> <li>Das Lagerhaus bietet 50% mehr Kraftstoffeinsparung.</li> <li>Einzigartiges Gebäude: Manga-Verlag</li> <li>Einzigartiges Gebäude: Anime-Studio</ li ><li>Halbleiterchipfabriken haben 2x Produktivität</li> <li>Li-Ionen-Batteriefabriken haben 2x Kapazität</li> <li>Batteriefabriken sind entsperrt</li> <li>Batteriefabriken haben 2x Kapazität</ li > <li>Der Kraftstoffverbrauch der Batterie erhöht sich um 100%.</li> <li>Batteriefabriken benötigen keine Kohle.</li> <li>Beginnen Sie mit 100K-Batterien</li>",
    HideChatDescV2:
        "Chat-Nachricht in der unteren Symbolleiste ausblenden. Durch das Anzeigen von Chat-Nachrichten stimmen Sie den ",
    HideChatDescV2ToS: "Nutzungsbedingungen zu",
    IntegratedCircuitFab: "Fabrik für integrierte Schaltkreise",
    MangaPublisher: "Mangaverlag",
    Manga: "Manga",
    AnimeStudio: "Animestudio",
    Anime: "Anime",
    PlayerTradeAction: "Aktion",
    PlayerTradeBuy: "Kaufen",
    PlayerTradeSell: "Verkaufen",
    PlayerTradeBid: "Bieten",
    PlayerTradeAsk: "Anfragen",
    ClaimTradeSuccessV2: "Ihr Handel wurde erfolgreich angenommen: %{cashOrResource}",
    AcceptTradeSuccessV2: "Dieser Handel wurde von dir abgeschlossen: %{cashOrResource}",
    ResourceExplorer: "Ressourcen-Explorer",
    ResourceExplorerDesc: "Ermöglicht das Extrahieren von Ressourcen aus einer leeren Kartenkachel",
    ResourceExplorerDescLong:
        "💡 Ressourcen-Entdecker haben keinen Benachbarungsbonus. Der Stromverbrauch ist je nach Ressource unterschiedlich",
    ResourceExplorerSelectResource: "Erkunden",
    ProductionSettings: "Produktionseinstellungen",
    PlayerTradePartialFillTitle: "Wählen Sie Füllprozentsatz",
    PlayerTradeAmountNotValidV2: "Der minimal zulässige Handelsbetrag beträgt 1",
    PlayerTradeOptOut: "Sie haben sich von der Rangliste abgemeldet und können nicht mit anderen Spielern handeln",
    FirstTimeReadGuide:
        "💡 Benötigen Sie ein bisschen Hilfe beim Spielen? Tippen Sie hier, um den Anfängerleitfaden zu lesen!",
    ReadSteamGuideV2: "Spielanleitungen",
    ReadSteamGuideV2Desc:
        "Sie können von der Community erstellte Anleitungen auf Steam lesen - und Sie können auch Ihre eigenen erstellen",
    ChatMessageTooLong: "Ihre Chat-Nachricht hat die maximal zulässigen Zeichen überschritten",
    ChatPlaceholderV2: "Geben Sie Ihre Nachricht ein: max %{length} Buchstaben",
    ProfitBreakdownOutput: "%{res} Erzeugung",
    ProfitBreakdownInput: "%{res} Verbrauch",
    ProfitBreakdownFuel: "Kraftstoffkosten",
    BuildingProfit: "Gewinn",
    RestoreBackup: "Wiederherstellen",
    SteamLogin: "Melden Sie sich via Steam an",
    SteamLoginDialogDesc:
        "Für Ihre lokale Speicherung ist das Erweiterungspaket aktiviert. Sie müssen sich über Steam anmelden, um fortzufahren. Oder Sie können Ihre lokale Speicherung löschen und von vorne beginnen",
    SteamLoginDesc:
        "Wenn Sie Erweiterungspakete bei Steam besitzen, können Sie nach der Anmeldung mit Erweiterungspaketen im Web spielen",
    SteamLoginYes: "Einloggen",
    SteamLoginNo: "Löschen & von vorne beginnen",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Internationaler Exporthandel",
    FreeTransportToTradeCenterDesc:
        "Der Transport zum Handelszentrum kostet keinen Kraftstoff, aber der Transport vom Handelszentrum kostet 50% mehr Kraftstoff",
    TaiChi10xCulture: "Perle des Orients",
    PlayerTradeYouHave: "Auf Lager: %{amount}",
    PlayerTradeFillValue: "Wert",
    FiberFactory: "Glasfaserfabrik",
    Fiber: "Glasfaser",
    Achievements: "Errungenschaften",
    AchievementsDesc: "Du hast %{number} von %{total} Errungenschaften erreicht",
    AchievementsReward: "Belohnung: Schweizer Franken +%{swiss}",
    AchievementsRewardToast: "Sie haben die Belohnung beansprucht:  Schweizer Franken +%{swiss}",
    AchievementsClaim: "Einsammeln",
    AchievementsToast: "Du hast %{name} erreicht, fordern Sie Ihre Belohnung im Hauptquartier an",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Verdiene 100 Schweizer Franken in Stockholm in einem einzigen Druchlauf",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Verdiene 500 Schweizer Franken in Stockholm in einem einzigen Druchlauf",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Verdiene 1000 Schweizer Franken in Stockholm in einem einzigen Druchlauf",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Verdiene 100 Schweizer Franken in Oslo in einem einzigen Druchlauf",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Verdiene 500 Schweizer Franken in Oslo in einem einzigen Druchlauf",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Verdiene 1000 Schweizer Franken in Oslo in einem einzigen Druchlauf",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Verdiene 100 Schweizer Franken in Rotterdam in einem einzigen Druchlauf",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Verdiene 500 Schweizer Franken in Rotterdam in einem einzigen Druchlauf",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Verdiene 1000 Schweizer Franken in Rotterdam in einem einzigen Druchlauf",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Verdiene 100 Schweizer Franken in Detroit in einem einzigen Druchlauf",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Verdiene 500 Schweizer Franken in Detroit in einem einzigen Druchlauf",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Verdiene 1000 Schweizer Franken in Detroit in einem einzigen Druchlauf",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Verdiene 100 Schweizer Franken in Boston in einem einzigen Druchlauf",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Verdiene 500 Schweizer Franken in Boston in einem einzigen Druchlauf",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Verdiene 1000 Schweizer Franken in Boston in einem einzigen Druchlauf",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Verdiene 100 Schweizer Franken in Rom in einem einzigen Druchlauf",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Verdiene 500 Schweizer Franken in Rom in einem einzigen Druchlauf",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Verdiene 1000 Schweizer Franken in Rom in einem einzigen Druchlauf",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Verdiene 100 Schweizer Franken in Hamburg in einem einzigen Druchlauf",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Verdiene 500 Schweizer Franken in Hamburg in einem einzigen Druchlauf",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Verdiene 1000 Schweizer Franken in Hamburg in einem einzigen Druchlauf",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Verdiene 100 Schweizer Franken in Toulouse in einem einzigen Druchlauf",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Verdiene 500 Schweizer Franken in Toulouse in einem einzigen Druchlauf",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Verdiene 1000 Schweizer Franken in Toulouse in einem einzigen Druchlauf",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Verdiene 100 Schweizer Franken in Hong Kong in einem einzigen Druchlauf",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Verdiene 500 Schweizer Franken in Hong Kong in einem einzigen Druchlauf",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Verdiene 1000 Schweizer Franken in Hong Kong in einem einzigen Druchlauf",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Verdiene 100 Schweizer Franken in St. Petersburg in einem einzigen Druchlauf",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Verdiene 500 Schweizer Franken in St. Petersburg in einem einzigen Druchlauf",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Verdiene 1000 Schweizer Franken in St. Petersburg in einem einzigen Druchlauf",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Verdiene 100 Schweizer Franken in Osaka in einem einzigen Druchlauf",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Verdiene 500 Schweizer Franken in Osaka in einem einzigen Druchlauf",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Verdiene 1000 Schweizer Franken in Osaka in einem einzigen Druchlauf",
    SteamAutoCloudBackup: "Steam Cloud Auto Sicherung",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup fehlgeschlagen: %{error}",
    SteamManualBackup: "Steam Cloud Sync erzwingen",
    UILoading: "Laden...",
    UserAuthenticated: "Sie sind authentifiziert",
    BuildingResourceBreakdown: "Aufschlüsselung des Leerlaufbetrags",
    SortByDeficit: "Defizit",
    SortByRunOut: "Läuft aus",
    SocialNetworkInc: "Social Network Inc.",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Datenbankunternehmen",
    Database: "Datenbank",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Flugzeugträgerfabrik",
    AircraftCarrier: "Flugzeugträger",
    MapExclusive: "Karten exklusiv",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Autofabriken verwenden Batterien anstelle von Benzin und benötigen nur 50% der Menge",
    HongKongBonusV2:
        "<li>Einzigartiger Marktpreisalgorithmus - Preise und Aktienbewertung folgen der Normalverteilung (Glockenkurve)</li><li>Marktaktualisierungen und Zurücksetzen von Handelsquoten sind doppelt so häufig (jede Stunde)</li><li>Forschung kann über gehandelte Ressourcen freigeschaltet werden</li><li>Einzigartiges Gebäude: Kung-Fu Dojo</li><li>Einzigartiges Gebäude: Tai-Chi Dojo</li><li>Erhöhung der maximal zulässigen Anzahl aktiver Spieler-Trades um 50%</li><li>Beginnen Sie mit 1 weiteren Auto-Sell-Parallelität</li><li>Einzigartige Richtlinie: Internationaler Exporthandel</li><li>Einzigartige Richtlinie: Perle des Orients</li><li>Das Großhandelszentrum benötigt zum Freischalten nur 4 Ressourcen</li><li>Beginnen Sie mit 100 Millionen Bargeld</li>",
    TaiChi10xCultureDescV2:
        "Kostenloser Transport von Kung-Fu und Tai-Chi. Filmstudios haben eine doppelte Kapazität, verbrauchen aber 50% mehr Strom",
    SettingsFullScreen: "Vollbild",
    SettingsFullScreenDesc: "Führen Sie das Spiel im Vollbildmodus aus. Nur für die Steam-Version verfügbar",
    LeaderboardByAllPrestigeCurrency: "Summe verdienter Schweizer Franken",
    LeaderboardByCash: "Aktuelles Bargeld",
    LeaderboardTotalValuation: "Gesamtwert",
    LeaderboardDescV2: "Sehen Sie, wo die Top-Spieler sind",
    LastUpdatedAt: "Zuletzt aktualisiert um",
    DetroitBonusV3:
        "<li>Motorenfabriken sind entsperrt</li><li>Motorenfabriken haben 2x Produktivität</li><li>Autofabriken haben 2x Kapazität</li><li>Autofabriken verwenden Gas anstelle von Benzin</li><li>Kostenloser Autotransport</li><li>Nikola Tesla Richtlinie ist kostenlos</li><li>Zugfabriken haben 2x Kapazität</li>",
    SaveAndExit: "Spiel speichern und beenden",
    SaveAndExitDesc:
        "Spiel speichern und beenden. Dies ist nur in der Steam-Version verfügbar und entspricht der Schaltfläche zum Schließen in der Fensterleiste",
    AutoSellResourceWarningShortLabel: "💡Auto Verkauf",
    AutoSellResourceWarningDesc:
        "Sie verkaufen diese Ressource automatisch. Der im Handelszentrum verfügbare Betrag kann hier nicht verwendet werden",
    PlayerTradeLocalPrice: "Lokaler Preis: %{price}",
    ChatForceScroll: "Scrollen erzwingen",
    ChatForceScrollDesc:
        "Wenn das Scrollen erzwingen aktiviert ist, wird der Chat immer dann gescrollt, wenn eine neue Nachricht eingeht. Andernfalls wird nur gescrollt, wenn Sie sich bereits unten befinden",
    ResourceExplorer2: "Ressourcen-Finder 2.0",
    ConstructionCancel: "Bau abbrechen",
    PolicyBlueprint: "Blaupause",
    PolicyBlueprintDesc:
        "Der Bau eines Gebäudes beginnt nicht automatisch - er muss manuell gestartet werden (KOSTENLOSE RICHTLINIE)",
    HighlightUnderConstruction: "... wurde noch nicht gebaut",
    HighlightUnderLevel10: "...sind unter Level 10",
    HighlightUnderLevel20: "...sind unter Level 20",
    HighlightUnderLevel30: "...sind unter Level 30",
    Logout: "Sie sind abgemeldet",
    ConstructionStatusQueueingV2: "Anstehend",
    ConstructionStatusPausedV2: "pausiert",
    ConstructionStatusBuildingV2: "Gebäude",
    ConstructionStatusUnpaidV2: "Unbezahlt",
    ConstructionStatus: "Baustatus",
    ConstructionStart: "Start",
    CostFree: "kostenlos",
    PlaceBlueprint: "Platzieren einer Gebäude Blaupause ist kostenlos",
    PlayerTradePriceNotValidV2: "Der Handelspreis muss zwischen %{min} und %{max} liegen",
    MarketNews: "Marktneuigkeiten",
    MarketNewsApplyToYou: "Nur für dich",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 hervorheben",
    MarketNewsFilterInput: "Alle %{res} Verbraucher",
    MarketNewsFilterOutput: "Alle %{res} Erzeuger",
    MarketNewsFilterBoth: "Alle %{res} Verbraucher und Erzeuger",
    MarketNewsIncrease: " erhöht um %{percent}",
    MarketNewsDecrease: " verringert um %{percent}",
    MarketNewsBuilding: "Dieses Gebäude wird betroffen von %{num} Neuigkeiten",
    StockholmBonusV2:
        "<li>Einzigartiges Gebäude: Musikproduzent</li><li>Forstbetriebe haben 2x Absatz</li><li>Papierfabriken sind entsperrt</li><li>Schaltungsgießereien haben 2x Produktivität</li><li>Die Politik der Wissenschaft Richtlinie ist kostenlos</li>",
    FreeOilTransportV2: "Elektronischer Öltransport",
    Tutorial4P1:
        "Der Transport von Ressourcen kostet Kraftstoff. Es gibt verschiedene Kraftstoffarten, momentan verwenden Sie <em>petrol⛽</em> als Kraftstoff. Sie haben eine <em>Ölraffinerie</em> welche das Öl auf der Ölquelle verbraucht und Benzin herstellt.<br><br>Die kleinen bewegenden <em>Punkte</em> stellen den Transport der Ressourcen dar. Sie sollten Ihre Gebäudestandorte optimieren, um die Distanz zu minimieren.<br><br><em>Aufwerten</em> deiner Gebäude erhöht deren Produktion, aber erhöht ebenfalls deren Stromverbrauch sowie die benötigten Ressourcen.",
    Tutorial4P2:
        "Sie können Ihren Kraftstofftyp im <em>Logistik Institut🚦</em> ändern. Auf dieser Karte können Sie auch <em>Erdgas</em> als Kraftstoff verwenden.<br><br>Das Logistik Institut zeigt auch Ihre Transportwege an, auf denen der meiste Kraftstoff verbraucht wird - Sie sollten es im Auge behalten.<br><br>Denken Sie daran, <em> sicherzustellen, dass Ihre Kraftstoffproduktion über dem Verbrauch liegt </em>, da sonst Ihre Produktion stoppt wenn der Kraftstoff ausgeht.<br><br>Machen Sie sich in diesem Fall keine Sorgen, Sie können notfalls Kraftstoff im Handelszentrum oder bei anderen Spielern kaufen",
    Tutorial5P2:
        "<em>Die Statistik Agentur📊</em> bietet einen guten Überblick deiner Produktion. Sie können eine detaillierte Aufschlüsselung Ihrer Ressourcenein- und -ausgabe sehen.<br><br>Es gibt auch viele nützliche Diagramme📈 - Sie sollten sich auf diese beziehen, wenn Sie Ihre Produktion ausbalancieren.<br></br>Dein <em>Geld💰, Stromüberschuss⚡ und Kraftstoffüberschuss⛽</em> -zahlen werden auch in der oberen linken Ecke angezeigt. Wenn eine davon rot wird, sollten Sie untersuchen, was los ist.",
    MusicProducer: "Musikproduzent",
    PlasticFiber: "Kunststofffaser",
    PlasticFiberDesc: "Glasfaserfabriken verwenden 50% mehr Kunststoff, aber 50% weniger Glas",
    NewsEffectx2: "Pressekonferenz",
    NewsEffectx2Desc: "Der Effekt von Marktnachrichten verdoppelt sich sowohl positiv als auch negativ",
    SellRefundPercentage: "Rückerstattung verkaufen / herabstufen",
    SellRefundPercentageDesc:
        "Wenn Sie ein Gebäude verkaufen oder herabstufen, ist dies der Prozentsatz an Bargeld und Ressourcen, den Sie erstattet bekommen",
    SellBuildingDescV2:
        "Durch den Verkauf eines Gebäudes erhalten Sie %{percent} Ihrer Investition zurück und %{percent} der Ressourcen werden zum Handelszentrum transportiert",
    BuilderMoveSpeed: "Bauherren Bewegungsgeschwindigkeit",
    BuilderMoveSpeedDesc: "Die Geschwindigkeit, mit der sich Bauherren bewegen, um Gebäude zu bauen",
    EBookInc: "eBook Inc.",
    ResourceBooster: "Ressourcen-Verstärker",
    BuildWarningTitle: "Gebäude funktioniert möglicherweise nicht",
    BuildWarningTitleDesc: "%{reason}. Sind Sie sicher, dass Sie auf dieser Zelle bauen wollen?",
    BuildWarningBuildAnyway: "Trotzdem bauen",
    ResourceBoosterNotWorking: "⛔ Ressourcen-Verstärker funktionieren nur in der Nähe von Lagerstätten",
    ResourceBoosterBuildings: "Gebäude werden verstärkt",
    BuildingResourceConversion: "%{resource} Umwandlung",
    AllTimeSwissMoneyEarned: "Gesamstmenge Schweizer Franken: %{number}",
    BuildingUpgradeCostDivider: "Kostenteiler für Gebäude-Upgrades",
    AchievementSoftwareGiant: "Software Gigant",
    AchievementSoftwareGiantDesc:
        "Erstellen Sie auf derselben Karte ein Softwareunternehmen der Stufe 10, ein Betriebssystemunternehmen der Stufe 10, ein Datenbankunternehmen der Stufe 10 und einen Webbrowser der Stufe 10",
    AchievementSpaceRace: "Weltraumrennen",
    AchievementSpaceRaceDesc:
        "Baue auf derselben Karte eine Raketenfabrik der Stufe 10, eine Satellitenfabrik der Stufe 10, eine Raumschifffabrik der Stufe 10 und eine Raumstationsfabrik der Stufe 10",
    AchievementToTheMoon: "Zum Mond",
    AchievementToTheMoonDesc:
        "Baue eine Bitcoin-Farm der Stufe 40 und eine Dogecoin-Farm der Stufe 40. Besitze 1B Bitcoin und 1B Dogecoin",
    ItsAllGreen: "Alles ist grün",
    ItsAllGreenDesc: "Haben Sie 50 Produktionslinien und überhaupt kein Produktionsdefizit",
    DeepInRed: "Tiefrot",
    DeepInRedDesc: "Haben Sie 50 Produktionslinien mit Produktionsdefizit",
    UseScientificNotation: "Verwenden Sie wissenschaftliche Zahlen",
    UseScientificNotationDesc:
        "Verwenden Sie die wissenschaftliche Zahlen (e Nummernsystem) für Zahlen größer als 999,9T",
    LogoutDescV2:
        "Sie haben sich auf einem anderen Gerät angemeldet, dieses Gerät ist abgemeldet. Sie können sich wieder anmelden, aber das andere Gerät wird abgemeldet ",
    LogBackIn: "Anmelden",
    ServerDisconnected:
        "Sie sind vom Server getrennt, überprüfen Sie bitte Ihre Internetverbindung und starten Sie das Spiel neu",
    BuildingUpgradeCostDividerDescV2: "Teilen Sie die Kosten für die Gebäudeerweiterung durch diesen Teiler",
    ResourceBoosterDesc: "Steigern Sie die Leistung benachbarter Minen",
    BlockUserChatTitle: "Blockiere %{user}",
    BlockUserChatAction: "Blockieren",
    BlockUserChatDesc:
        "Der Block wird während dieser Spielsitzung wirksam sein und Sie können dies nicht rückgängig machen, es sei denn, Sie starten das Spiel neu",
    ChangeNameCooldown: "Sie können Ihren Namen nur ein mal alle %{hour} ändern",
    AtomicBombFactory: "Atombombenfabrik",
    AtomicBomb: "Atombombe",
    DynamiteFactory: "Sprengstofffabrik",
    Dynamite: "Sprengstoff",
    NuclearMissileFactory: "Atomraketenfabrik",
    NuclearMissile: "Atomrakete",
    LiquidPropellantFactory: "Fabrik für flüssigen Treibstoff",
    GasPropellantFactory: "Gas-Treibstofffabrik",
    Propellant: "Treibstoff",
    ProjectV2: "Projekt V-2",
    ICBMFactory: "Interkontinentalraketenfabrik",
    ICBM: "Interkontinentalraketen",
    RadarFactory: "Radarfabrik",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Kommando",
    SpaceForce: "Space Force",
    SpaceColony: "Weltraumkolonie",
    SpaceColonyInc: "Weltraumkolonieagentur",
    ProjectVostok: "Projekt Wostok",
    AdjacentBonusSquare: "Angrenzendes Bonusfeld",
    AdjacentBonusSquareDesc:
        "Der angrenzende Bonus ist 50% effektiver, aber die Zellenmodifikatoren skalieren von -15% bis + 15%.",
    ResourceBoosterSquare: "Ressourcen-Verstärker Quadrat",
    ResourceBoosterSquareDesc:
        "Ressourcen-Verstärker sorgen für 25% mehr Boost, aber ihr Wissenschaftspunkte- und Stromverbrauch steigt um 25%",
    SteelMillx2: "Stahlofenmodernisierung",
    SteelMillx2Desc:
        "Stahlwerke und Edelstahlwerke haben eine doppelte Kapazität, verbrauchen jedoch die doppelte Menge Strom",
    FuelDynamite: "Kraftstoff Dynamit",
    FuelDynamiteDesc: "Dynamitfabriken verwenden Ihren aktuellen Kraftstoff anstelle von Öl",
    StPetersburgBonusV2:
        "<li>Uranminen haben 2x Produktion</li><li>Urananreicherungsanlagen haben doppelte Kapazität</li><li>Der Urantransport kostet 50% weniger Kraftstoff</li><li>Kostenloser Waffentransport</li><li>Das Projekt Wostok hat eine Kapazität von 2x</li>",
    ToulouseBonusV2:
        "<li>Titanminen haben 2x Prdouktion</li><li>Urananreicherungsanlagen haben eine doppelte Produktivität</li><li>Triebwerksfabriken haben eine Kapazität von 2x</li><li>Flugzeugfabriken haben 2x Produktivität</li><li>Raketenfabriken haben eine Kapazität von 2x</li>",
    BuildingPermitsNeededDesc: "Dieses Gebäude funktioniert nicht, weil Sie nicht genügend Baugenehmigungen haben",
    BuildingPermitsNeeded: "Baugenehmigungen erforderlich",
    BuyMissingPermits: "Fehlende Baugenehmigungen kaufen",
    GPUIsBusy: "Ihre GPU ist ausgelastet",
    GPUIsBusyDesc:
        "Ihr Betriebssystem hat die Grafik des Spiels angehalten, da die GPU mit anderen Aufgaben beschäftigt ist. Sie können das Spiel neu laden, um fortzufahren. Wenn es nicht funktioniert, starte das Spiel neu",
    SaveAndReloadGame: "Spiel speichern und neu laden",
    ResearchLabCultureInput: "Die Renaissance",
    ResearchLabCultureInputDesc: "Das Forschungslabor hat die doppelte Kapazität, verbraucht aber zusätzlich Kultur",
    GasPumpx2Output: "Hochdruck-Gaspumpe",
    GasPumpx2OutputDesc: "Erdgaspumpen haben 2x Leistung, verbrauchen aber 2x Strom",
    LeaderboardValuationPerHour: "Gesamtwert pro Stunde",
    LeaderboardValuationPerHourPerSwiss: "Gesamtwert pro Stunde pro Schweizer Franken",
    LeaderboardValuationPerHourNewPlayers: "Gesamtwert pro Stunde (< 1000 Schweizer Franken)",
    LeaderboardValuationPerBuilding: "Gebäudebewert pro Gebäude",
    BuildingCustomColor: "Gebäudefarbe",
    BuildingCustomColorReset: "Zurücksetzen",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Für alle 4 verschiedenen Gebäudetypen erhalten Sie 1 kostenlose Baugenehmigung</li><li>Einigartige Richtlinie: Produktionsdiversifizierung</li><li>Einzigartiges Gebäude: Ahornsirupfabrik</li><li>Kostenloser Ahornsiruptransport</li><li>Einzigartiger Kraftstoff: Ahornsirup</li><li>2x Spieler-Handelsquote beim Handel mit Uran und angereichertem Uran</li><li>Einigartige kostenlose Richtlinie: Sirup Kunststoff</li><li>Spielzeugfabriken haben doppelte Produktivität</li><li>Spielstudios haben 2x Kapazität</li>",
    MapExtraPermitDesc: "Du erhältst %{number} kostenlose Baugenehmigungen durch den einzigartigen Bonus der Karte",
    OsloBonusV3:
        "<li>Ölraffinerien sind freigeschaltet</li><li>Ölraffinerien haben 2x Kapazität</li><li>Die Transportrichlinie Elektronisches Öl ist kostenlos</li><li>Gasaufbereitungsanlagen haben 2x Kapazität</li><li>1x kostenlose Windturbine der Stufe 4</li><li>1x kostenlose Ölquelle der Stufe 8</li><li>1x kostenlose Stufe 2 Ölraffinerie</li><li>1x kostenlose Stufe 2 Gaspumpe</li>",
    ResourceBoosterPercentageV2: "💡 Dieser Betrag beinhaltet %{percent} Boost von benachbarten Ressourcenverstärkern",
    MapleSyrup: "Ahornsirup",
    MapleSyrupFactory: "Ahornsirupfabrik",
    SyrupPlastic: "Sirup Kunststoff",
    SyrupPlasticDesc: "Alle Gebäude, die Kunststoff verwenden, verwenden stattdessen Ahornsirup",
    ResourceBoosterSupplyChain: "Lieferkettenbonus",
    ResourceBoosterSupplyChainDesc:
        "Ressourcen-Booster verbrauchen 2x Strom und Wissenschaftspunkte, aber für jede arbeitende Mine erhöht ein Ressourcen-Booster die Kapazität benachbarter Fabriken, die die Produktion der Mine verbrauchen (die Fabrik sollte nur Lagerbestaände verbrauchen).",
    ProductionDiversification: "Produktionsdiversifizierung",
    ProductionDiversificationDesc: "Jeder Gebäudetyp gibt allen Gebäuden 1% zusätzliche Kapazität",
    ExtraPolicyPointsDescV2:
        "Das Policy Center verfügt über die doppelte Konvertierungskapazität von Richtlinienpunkten",
    PowerRequired: "Strom benötigt",
    AchievementVancouver100: "Saftverkäufer",
    AchievementVancouver100Desc: "Verdiene 100 Schweizer Franken in Vancouver in einem Durchgang",
    AchievementVancouver500: "Sirup Vertiebler",
    AchievementVancouver500Desc: "Verdiene 500 Schweizer Franken in Vancouver in einem Durchgang",
    AchievementVancouver1000: "Canuck-Eroberer",
    AchievementVancouver1000Desc: "Verdiene 1000 Schweizer Franken in Vancouver in einem Durchgang",
    BarbariansAtTheGate: "Barbaren am Tor",
    BarbariansAtTheGateDesc: "Nutze zwischen den Marktaktualisierungen eine Handelsquote von 1T zwischen Spielern",
    DiversifiedProductions: "Diversifizierte Produktionen",
    DiversifiedProductionsDesc: "Baue 100 verschiedene Gebäudetypen auf einer einzigen Karte",
    RealEstateTycoon: "Immobilien-Tycoon",
    RealEstateTycoonDesc: "Habe 400 Gebäude auf einer einzigen Karte",
    ResourceExplorer2DescV2:
        "Ressourcen-Explorer produzieren 2x Ertrag, verbrauchen aber 2x Strom. Ressourcen-Explorer können durch Ressourcen-Booster verstärkt werden, wenn die Lieferketten-Richtlinie aktiv ist und der Booster eine benachbarte Mine mit der gleichen Ressource hat",
    NoTileModifier: "Die Erde ist Flach",
    NoTileModifierDesc:
        "Alle Zellenmodifikatoren werden 0. Diese Richtlinie wird die Richtlinien (Kraft der Natur) und (Zellenmodifikator Plus) deaktivieren.",
    DoubleTileModifierDescV2:
        "Alle Zellenmodifikatoren x2 - positive als auch negative. Die Richtlinie wird (Die Erde ist Rund - Richtlinie) deaktivieren.",
    TileModifierOutputOnlyDescV2:
        "Zellenmodifikatoren beeinflussen nur die Produktuion, anstelle der Produktion und des Verbrauchs, sind aber nur zu 50% effektiv. Die Richtlinie wird (Die Erde ist Rund - Richtlinie) deaktivieren.",
    QuickLinks: "Direktlinks",
    GetHelp: "HILFE",
    GetHelpBeginnerGuides: "Anfänger Hilfen",
    GetHelpSteamGuides: "Andere Hilfen auf Steam",
    GetHelpInGameChat: "Frage im Spielchat",
    GetHelpDiscord: "Trete unserem Discord Server bei!",
    GetHelpWiki: "Community Wiki",
    SelectATile: "Wähle eine Zelle",
    PledgeAmount: "Beitrag %{amount}",
    PledgeValue: "Wert $%{amount}",
    TotalPledgedValue: "Gesamt Beitragswert",
    TotalPledgedValueDesc:
        "Dein erster Beitrag zählt für das Crowdfunding-Ziel. Nachfolgende Beiträge erhöhen den Gesamt Beitragswert, zählen aber nicht zum Ziel",
    ReturnOnPledge: "Gewinn bei Erfolg",
    CrowdfundingEndIn: "Endet in %{time}",
    ClaimCrowdfundingReward: "Belohnung einfordern %{amount}",
    PledgeSuccessful: "Du hast %{amount} zum Crowdfunding beigetragen",
    CrowdfundingClaimSuccessful: "Du hast %{amount} Geld abgeholt",
    CrowdfundingAlreadyPledged: "Sie haben bereits beigesteuert",
    CrowdfundingAlreadyPledgedDesc:
        "Du kannst mehr Ressourcen beisteuern, was deinem Gesamtwert (und die potenzielle Rendite) erhöht, aber nicht auf das Crowdfunding-Ziel angerechnet wird",
    WholesaleCenterProducingOnly: "Großhandelspartner",
    WholesaleCenterProducingOnlyDesc:
        "Großhandelszentrum-Bestellungen enthalten nur Ressourcen, deren Fabriken Sie gebaut haben (Sie müssen auch die Anzahl der erforderlichen Ressourcen produzieren, um das Großhandelszentrum freizuschalten).",
    SoftwareCompiler: "Software Compiler",
    SearchEngine: "Suchmaschine",
    SearchEngineCompany: "Suchmaschinenfirma",
    Navy: "Marine",
    NavyCommand: "Marineführung",
    Battleship: "Schlachtschiff",
    BattleshipFactory: "Schlachtschifffabrik",
    ResourceMovementHide: "Immer ausblenden",
    ResourceMovementShow: "Immer anzeigen",
    ResourceMovementViewport: "Punktedarstellung",
    ResourceMovementHighlight: "Bei Hervorhebung",
    ResourceMovementLine: "Linien",
    ResourceMovement: "Ressourcenbewegung",
    ResourceMovementDesc:
        "Sie können auswählen, wann die Ressourcenbewegung (Punkte) angezeigt werden soll. Das Ausblenden kann die Leistung verbessern",
    CrowdfundingCashInWarning:
        "Du hast ausstehende Crowdfunding-Beiträge – wenn du in einer neuen Stadt beginnst, verfallen sie",
    ResourceBoosterBannerDescV2:
        "💡 Du hast aktuell %{number} Ressource-Booster - der wissenschaftliche Input jedes einzelnen wird auf die Anzahl der Ressourcen-Booster skaliert, die Sie derzeit haben",
    CrowdfundingId: "Crowdfunding %{id}",
    PatchNotes: "Patch Notizen",
    PatchNotesDesc: "Lese was neu im Update ist",
    PanelPositionLeft: "Links (Docked)",
    PanelPositionLeftFloat: "Links (Float)",
    PanelPositionRight: "Rechts (Docked)",
    PanelPositionRightFloat: "Rechts (Float)",
    PanelPositionAuto: "Automatisch",
    TimePlayed: "Gespielte Zeit",
    ValuationPerHour: "Wert pro Stunde",
    HighPowerPriority: "Hohe Leistungspriorität",
    HighPowerPriorityDesc: "Wenn du das einschaltest, zieht das Gebäude Strom von anderen Gebäuden",
    IndustryZone: "Industrie Zone",
    IndustryZoneDesc:
        "Kombinieren Sie angrenzende Gebäude, die eine Lieferkette bilden und sparen Sie Baugenehmigungen",
    IndustryZoneMaxBuildingLevel: "Maximale Gebäudestufe",
    IndustryZoneNotWorkingDesc:
        "Alle angrenzenden Gebäude sollten eine Lieferkette bilden und sind nicht Teil anderer Industriezonen",
    PlayerTradeAutoClaim: "Beanspruche erfüllte Handel automatisch",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "Cloud Streaming",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "Super Computer Labor",
    SuperComputer: "Super Computer",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "SkyNet",
    RobocarFactory: "Robocar Fabrik",
    Robocar: "Robocar",
    WarehouseBuildingPermitSave: "Lagerhausbaugenehmigung",
    WarehouseBuildingPermitSaveDesc: "Alle zwei Lagerhäuser bieten eine kostenlose Baugenehmigung",
    PolicySearchPlaceholder: "Geben Sie den Namen der zu durchsuchenden Richtlinie ein",
    SwissUpgrade: "Schweizer Upgrade",
    SwissUpgradeDesc: "Schweizer Upgrades sind permanent und werden in die neue Stadt übertragen",
    SwissBoost: "Schweizer Boost",
    SwissBoostDesc:
        "Schweizer Boost wirkt nur auf die jetzige Stadt - und muss nach dem Start einer neuen Stadt wieder aktiviert werden",
    ProductionMultipliers: "Produktions-Multiplikator",
    MultiplierMapUniqueBonus: "Einzigartiger Karten-Bonus",
    MultiplierSwissUpgrade: "Schweizer Upgrade (Permanent)",
    MultiplierSwissBoost: "Schweizer Boost (Aktuelle Stadt)",
    SwissBoostCostDivider: "Schweizer Boost Kostenteiler",
    SwissBoostCostDividerDesc:
        "Teile die Schweizer Boost Kosten durch diesen Wert - funktioniert nur für Multiplikator/Teiler-Verbesserungen",
    AirForceCommand: "Luftwaffenführung",
    AirForce: "Luftwaffe",
    StealthFighterFactory: "Tarnkappenbomberfabrik",
    StealthFighter: "Tarnkappenbomber",
    ArmyCommand: "Heeresführung",
    Army: "Heer",
    GreenPeacekeeper: "Green Peacekeeper",
    GreenPeacekeeperDesc:
        "Stelle Herr, Marine, Lufwaffe oder Space Force nur mit erneuerbaren Energien her (Wind/Solar)",
    DotComTycoon: "DotCom Tycoon",
    DotComTycoonDesc:
        "Baue einen Stufe 10 Scial Network Inc, Stufe 10 Suchmaschinenfirma, Stufe 10 Skynet Inc und Stufe 10 Musify Inc auf derselben Karte",
    ConstructionNotResearched: "Nicht erforscht",
    OfflineEarningDescV2:
        "Offline-Einkommen basiert auf deiner derzeitigen Forschung, Produktion und automatischem Verkauf",
    HighSpeedWarehouse: "Hochgeschwindigkeits-Warenhaus",
    HighSpeedWarehouseDesc:
        "Warenhäuser haben doppelte Kapazität und 50% schnelleren Warentransport, baut verbrauchen doppelt so viel Strom",
    IndustryZoneMultiplierDesc: "Industrie-Zonen-Bonus",
    IndustryZoneMultiplierSwissBoost: "Industrie-Zonen-Kapazitäts-Booster",
    EarningPerMinuteV2: "Offline-Erwerbsrate",
    OfflineResearchPoint: "Offline-Forschungspunkte",
    WholesaleCenterOrderFasterV2: "Größerer scneller Großhandel",
    OfflineResearchSwissBoost: "Offline-Forschung",
    OfflineResearchSwissBoostDesc:
        "Forschungspunkte werden auch offline generiert (Basierend auf der Forschungslabor-Stufe, Wissenschaft im Warenhaus und Offline-Erwerbszeit)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Einzigartiges Gebäude: Chipfabrik</li><li>Einzigartiges Gebäude: FaceApp Inc</li><li>Einzigartiges Gebäude: Bitcoin Miner</li><li>Alle Gebäude, die Silikon verbrauchen, haben maximalen Zellen-Modifikator</li><li>Solarmodule produzieren doppelt so viel Strom</li><li>Silizium-Mine produzieren doppelt so viel</li>",
    RotterdamBonusV2:
        "<li>Stahlwerke haben 2x Kapazität</li><li>Edelstahlanlagen haben 2x Kapazität</li><li>Kostenloser Eisentransport</li><li>Stahltransport kostet 50 % weniger Kraftstoff</li><li>Beginnen Sie mit 2x Auto-Verkauf-Menge</li><li>Die Richtlinie (Die Erde ist flach) ist kostenlos</li>",
    ChipManufacturer: "Chipfabrik",
    SnapTokInc: "SnapTok Inc",
    FaceAppInc: "FaceApp Inc",
    BitcoinMiner: "Bitcoin Miner",
    GalvanicBatteryFactory: "Galvanische-Batterie-Fabrik",
    BaseProductionMultiplier: "Basisproduktion",
    ShowBreakdown: "Zeige Unterteilung",
    HideBreakdown: "Verstecke Unterteilung",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Jede Stufe einer Lieferkettede in der Industrie Zone gibt seinen Kapazitäts Boost allen anderen Gebäude in der Zone",
    IndustryZoneBuildingPermitDesc:
        "Wenn eine Industrie Zone N Stufe and Produktion hat, dann gibt es N-2 Baugehnehmigungen umsonst",
    CrowdfundingBackersReturn: "Investoren: %{backers}, Derzeitiger Gewinn: %{return}",
    CrowdfundingBackersNeeded: "%{backers} mehr Investoren",
    CrowdfundingReturnBonus: "+%{return} Gewinn",
    ReturnOnPledgeDescV2:
        "Dein Gewinn ergibt sich aus deinem gesamten Beitrag multipliziert mit den Gewinnraten aller Ressourcen.  Je mehr in eine Ressource investieren, desto höher wird der Gewinn sein.",
    PlayerTradeQuotaDescV2:
        "💡 Quota ist die Menge an Ressourcen, die du handeln kannst. Der Geldwert gleicht %{percent} deiner Marktkapitalisierung und wird beim Marktpreisupdate zurückgesetzt. Je mehr dein Handelswert von dem des Handelszentrums abweicht, desto mehr Quota benötigst du",
    AchievementSanJose100: "Venture Hobbyist",
    AchievementSanJose100Desc: "Verdiene 100 Schweizer Franken in San Jose in einem Durchgang",
    AchievementSanJose500: "Venture Enthusiast",
    AchievementSanJose500Desc: "Verdiene 500 Schweizer Franken in San Jose in einem Durchgang",
    AchievementSanJose1000: "Venture Capitalist",
    AchievementSanJose1000Desc: "Verdiene 1000 Schweizer Franken in San Jose in einem Durchgang",
    AchievementCrowdfundingTycoon: "Crowdfunding Tycoon",
    AchievementCrowdfundingTycoonDesc: "Trage Ressourcen im Wert von 1Qa zu einem einzigen Crowdfunding-Ziel bei",
    AchievementCashIsKing: "Cash Is King",
    AchievementCashIsKingDesc: "Habe 1Qa Geld auf der Hand in einem Durchgang",
    AchievementPowerTycoon: "Power Tycoon",
    AchievementPowerTycoonDesc: "Erzeuge 1 Gigawatt Strom in einem Durchgang",
    PlayerTradeFilteringNResources: "Filtert %{n} Ressourcen",
    PlayerTradeFilterResources: "Filtere Ressourcen",
    PlayerTradeFilterClear: "Lösche Filter",
    ResourceExplorerAll: "Erforsche alle Ressourcen",
    ResourceExplorerAllDesc:
        "Ressourcen-Explorer können alle Ressourcen produzieren, auch die, die nicht auf der Karte vorkommen (schaltet NICHT die relevanten Technologien frei)",
    ShowResourceInTopBar: "Zeige in der oberen Leiste",
    LeaderboardOptOutDescV2:
        "Du wirst nicht mehr auf dem Bestenliste angezeigt. Spielerhandel wird ausgeschaltet. BEMERKE: Wenn du wieder auf der Bestenliste erscheinen willst muss dein Spiel zurückgesetzt werden",
    PolicyPointNoCopperDesc:
        "💡 Diese Karte hat keine Kupfervorkommen, du kannst Al Schaltkreis aktivieren um weitere Technologien freizuschalten",
    Pumpkin: "Kürbis",
    PumpkinBattery: "Kürbis-Batterie",
    PumpkinBatteryDesc: "Alle Gebäude, die Batterien verbrauchen, nutzen stattdessen Kürbisse (Kostenlose Richtlinie)",
    PumpkinSteel: "Kürbis-Stahl",
    PumpkinSteelDesc: "Alle Gebäude, die Stahl verbrauchen, nutzen stattdessen Kürbisse (Kostenlose Richtlinie)",
    RequireExpansionPack2: "Erweiterung 2",
    ExpansionPack2: "Erweiterung 2",
    RequireExpansionPack2Desc: "Das ist nur für Erweiterung 2 verfügbar",
    Reindeer: "Rentier",
    ReindeerSilicon: "Rentier-Silizium",
    ReindeerSiliconDesc: "Alle Gebäude, die Silizium verbrauchen, nutzen stattdessen Rentiere (Kostenlose Richtlinie)",
    ReindeerAluminum: "Rentier-Aluminium",
    ReindeerAluminumDesc:
        "Alle Gebäude, die Aluminium verbrauchen, nutzen stattdessen Rentiere (Kostenlose Richtlinie)",
    SantaClauseIsComing: "Der Weihnachtsmann kommt :^)",
    SantaClauseIsComingDesc:
        "Santa factories consume reindeer and toy and produce santa, science and culture. Santa factories have max tile modifier. Toy factories produce reindeer in addition to toy (FREE POLICY)",
    MetaRebranding: "Meta Rebranding",
    MetaRebrandingDesc:
        "Social Network Inc wird zu Meta Inc umbenannt und verbraucht stattdessen Internet, Game, Super Computer, Bitcoin und Dogecoin.",
    MetaInc: "Meta Inc",
    ImportSave: "Importiere Speicherstand",
    ClearMyTrades: "Lösche deine Handel",
    SaveVersionTooNew:
        "Dein Speicherstand ist von %{saveVersion}, dein Spiel ist auf %{gameVersion}. Aktualisiere zuerst dein Spiel",
    LeaderboardByFlag: "Bewertung nach Spielerflagge",
    LeaderboardByMap: "Bewertung nach Karte",
    LeaderboardByFlagPlayerFlag: "Flagge",
    LeaderboardByFlagPayerCount: "Spielerzahl",
    LeaderboardByFlagPayerValuationPerHour: "V/H",
    LeaderboardByFlagPayerSwissMoney: "Schweizer Franken",
    PlayerTradePriceFilter: "Preisfilter",
    PlayerTradeFilterBetterThanMarket: "Besser als der Markt",
    PlayerTradeFilterAll: "Alles",
    PlayerTradeFilterBestPrice: "Bester Preis",
    CrowdfundingTotalPledgdeValueTooLarge:
        "Dein Beitrag fürs Crowdfunding darf deine derzeitigen Marktkapitalisierung nicht überschreiten",
    BuildingSourceAuto: "Automatische Quelle",
    BuildingSourceManual: "🔍 Manuelle Quelle",
    BuildingSourceReset: "Zurücksetzen",
    BuildingSourceSelecting: "Klicke auf die Karte...",
    BuildingSourceSetOverride: "Überschreiben",
    BuildingSourceFallback: "Manuelle Quellen",
    BuildingSourceFallbackDesc:
        "Wie sollte das Gebäude den Eingang transportieren, wenn die manuelle Quelle nicht genug hat? Überspringen - nicht transportieren; Restposten - transportiere, was übrig ist; Neu - nutze automatische Quellen um eine neue Quelle zu finden",
    BuildingSourceFallbackSkip: "Überspringen",
    BuildingSourceFallbackDrain: "Restposten",
    BuildingSourceFallbackAuto: "Neu",
    BuildingSourceFallbackMarker: "(Zurückgreifen)",
    BuildingSourceFallbackMarkerDesc: "Der manuellen Quelle fehlt es an Ressourcen, auf anderes wird zurückgegriffen",
    BuildingSourceInvalid: "Deine ausgewählte Quelle ist invalide, wähle ein gültige Zelle aus.",
    RandomIsland: "Zufällige Insel",
    RandomIslandBonus:
        "<li>Die Karte ist jedes mal anders wenn du neu beginnst</li><li>Kartengröße, Zellentyp, Ressourcenvorkommen und einzigartige Boni werden alle zufällig ausgewählt</li><li>Für Kartenneustarts gibt es eine 5 Minuten Wartezeit</li>",
    RandomIslandBonusDesc:
        "Der einzigartige Bonus auf der zufälligen Insel verändert sich jedes mal, wenn du auf der Karte neu startest.",
    RandomIslandBonusCapacity: "%{building} hat %{multiplier}x Kapazität",
    RandomIslandBonusProductivity: "%{building} hat %{multiplier}x Produktivität",
    RandomIslandBonusResources: "Resourcenvorkommen auf dieser Karte: %{deposits}",
    ValuationPerActiveMinute: "Bewertung per aktiver Minute",
    Perth: "Perth",
    GV: "Geothermiequelle",
    GeothermalPowerPlant: "Hochenthalpie-Lagerstätten",
    AdjacentExplorer: "Angrenzender Explorer",
    AdjacentExplorerDesc:
        "Ressourcen-Explorer haben doppelte Produktion, wenn es an die Ressource, die es produziert, angrenzt. (Kostenlose Richtlinie)",
    FactoryMining: "Industrialisierte Mine",
    FactoryMiningDesc:
        "Eine Fabrik kann Vorkommen direkt auf der Zelle abbauen, wenn es diese Ressource auch verbraucht (Kostenlose Richtlinie)",
    FactoryMiningBanner: "Dieses Gebäude baut %{resource} direkt von dieser Zelle ab",
    WarehouseSourceWeight: "Gewicht: %{weight}",
    YAxisStartsFromZero: "Y-Achse startet bei 0",
    YAxisStartsFromZeroDesc: "Die Y-Achse jeder Grafik fängt immer bei 0 an, anstatt automatisch angepasst zu werden",
    OwnDLC: "Besitzt %{number}x Erweiterung(en)",
    GeneralServerSuccessMessage: "Deine ANfrage wurde erfolgreich ausgeführt",
    GeneralServerErrorMessage: "Serverfehlermeldung: %{error}",
    WarehouseInputRoutes: "Eingaberouten",
    WarehouseOutputRoutes: "Ausgaberouten",
    InputCapacity: "benötigte Materialien",
    MultipleSources: "Mehrere Quellen",
    MultipleSourcesDesc: "Das Gebäude bezieht Ressourcen von mehreren Quellen während eines Kreifslaufes",
    Water: "Wasser",
    KansasCity: "Kansas City",
    Dam: "Staudamm",
    DamDesc: "Staudamm flutet verwandelt angrenzende Zellen zu Wasser",
    Farmland: "Acker",
    FarmlandDesc: "Baue Pflanzen auf Wasserzellen an",
    Storage: "Lagerung",
    Rice: "Reis",
    Corn: "Mais",
    Wheat: "Weizen",
    Soybean: "Sojabohne",
    Sugarcane: "Zuckerrohr",
    Vegetable: "Gemüse",
    FarmlandProduce: "Ernte",
    FarmlandOfflineFarming: "Offline-Landwirtschaft",
    FarmlandOfflineFarmingDesc:
        "Äcker auf natürlichen Wasserquellen produzieren auch offline. Beeinflusst durch Schweizer Upgrades und Offline-Erwerbszeit",
    FarmlandProductionDesc: "💡 Äcker arbeiten nur 5 von 10 Sekunden - alle Kreisläufe sind verbunden",
    WaterPump: "Wasserpumpe",
    Greenhouse: "Gewächshaus",
    GreenhouseDesc: "Baue eine Pflanze deiner Wahl an",
    WaterEntityLevelTooHighDesc:
        "Das Gebäudelevel ist höher als das des anliegenden Staudamm. Verbessere seinen Staudamm.",
    AirLiquidizer: "Luftverflüssiger",
    CapacitorFactory: "Kondensatorfabrik",
    Capacitor: "Kondensator",
    OfflineProduction: "Offline-Produktion",
    OfflineProductionDesc: "Wenn dieses Gebäude mit Kondensatoren versorgt wird produziert es auch offline.",
    Moderator: "Moderator",
    FlourMill: "Getreidemühle",
    Flour: "Mehl",
    FlourMillAdjustMix: "Verändere Mehlmischung",
    RiceFlour: "100% Glutenfrei",
    RiceFlourDesc: "Getreidemühlen verbrauchen Reis statt Weizen.",
    Bread: "Brot",
    Bakery: "Bäkerei",
    Fodder: "Futter",
    FodderFactory: "Futterfabrik",
    SugarRefinery: "Zuckerraffenerie",
    RefinedSugar: "raffinierter Zucker",
    ShowSupplyChain: "Lieferkette",
    ShowSupplyChainDesc: "Wenn du ein Gebäude hervorhebst, zeige die gesamte Lieferkette.",
    Cake: "Kuchen",
    ChooseARecipe: "Wähle ein Rezept",
    ChickenFarm: "Geflügelzuchtbetrieb",
    Chicken: "Huhn",
    Egg: "Ei",
    CowFarm: "Rindzuchtbetrieb",
    Beef: "Rindfleisch",
    Milk: "Milch",
    DairyFactory: "Molkerei",
    Cheese: "Käse",
    Cookie: "Keks",
    Butter: "Butter",
    UnlockAtLevel: "Freigeschaltet ab Stufe %{level}",
    FastFoodChain: "Fast Food Chain",
    Burger: "Burger",
    Sandwich: "Sandwich",
    StandbyMode: "Ruhemodus",
    StandbyModeDesc:
        "Das Spiel wird weiter im Hintergrund laufen, aber keine Grafiken mehr rendern. Grafikkarte und CPU werden entlastet",
    StandbyModeOn: "Ruhemodus an",
    StandbyModeOnDesc: "Das Spiel läuft im Hintergrund. Drücke eine beliebige Taste um den Ruhemodus zu verlassen",
    PigFarm: "Schweinezuchtbetrieb",
    Pork: "Schweinefleisch",
    SausageFactory: "Metzgerei",
    Sausage: "Wurst",
    Hotdog: "Hotdog",
    BatchOperationDesc: "Das wird auf %{number} Gebäude angewandt. Ausführen?",
    BatchOperationResult: "Der Batchbefehl wurde erfolgreich für %{success} Gebäude ausgeführt",
    StreamingMakeMeDiscoverable: "Mach mich entdeckbar",
    StreamingMakeMeDiscoverableDesc:
        "Erlaube es anderen Spielern deinem Spiel zuzuschauen. Die Verbindung basiert auf P2P und ist wird nur das Gameplay gestreamt. Es wird weder auf Mikrofon nocht Kamer zugegriffen",
    StreamAutoApprove: "Öffentlicher Stream",
    StreamAutoApproveDesc: "Erlaubt es Spielern deinem Stream anzuschauen ohne individuelle Anfragen anzunehmen.",
    StreamingWatch: "schauen",
    StreamingStop: "Stop",
    StreamingPlayerDisconnected: "%{player} hat deinen Stream verlassen",
    StreamingPlayerRejected: "%{player} hat deine Streamanfrage abgelehnt",
    StreamingPlayerRequested:
        "%{player} hat angefragt deinem Stream zuzuschauen, gehe zum Hauptquartier um anzunehmen oder abzulehnen",
    StreamingSettings: "Streameinstellungen",
    StreamingAvailableStreams: "Verfügbare Streams",
    StreamingAudience: "Zuschauer",
    StreamingStopStream: "Nicht mehr für diesen Zuschauer streamen",
    StreamingAcceptStream: "Annehmen",
    StreamingRejectStream: "Ablehnen",
    StreamingStopStreamDesc: "Nicht mehr für diesen Zuschauer streamen",
    StreamingConnectionFailed:
        "Verbindung konnte nicht aufgebaut werden - dein Netzwerk unterstützt wahrscheinlich keine P2P-Verbindungen",
    Pizza: "Pizza",
    StreamingStartRecord: "Starte Aufnahme",
    StreamingRecordCamera: "Nehme einen Director´s Cut auf",
    StreamingRecordCameraDesc:
        "Nehmen einen 10s Director´s Cut auf - die Kamera geht auf maximalen Zoom und schwenkt langsam raus",
    StreamingStopRecord: "Stoppe Aufnahme",
    StreamingRecordingReady: "Aufnahme ist bereit",
    StreamingRecordingReadyDesc: "Du kannst deine Aufnahme speichern und mit einem kompatiblen Videospieler abspielen.",
    StreamingRecordingSave: "Speichern als",
    Lantern: "Laterne",
    LunarNewYear22: "Jahr des Tigers",
    LunarNewYear22Desc:
        "Alle Gebäude, die Papier verbrauchen, nutzen stattdessen Lanternen und haben doppelte Kapazität. Papier-Fabriken und Papierakademien produzieren stattdessen Kultur.",
    PaperAcademy: "Papierakademie",
    FriedRice: "gebratener Reis",
    Highlight: "🔍 Hervorheben",
    BatchMode: "Batchmodus",
    BatchModeAll: "Alle",
    BatchModeAdjacent: "angrenzend",
    BatchModeCluster: "Haufen",
    BatchUpgradeToLevelX: "Zur Stufe %{level}",
    ApplyToBatch: "Auf %{batch} anwenden",
    BatteryRecycler: "Batterie-Recykler",
    BatteryShell: "Batteriegehäuse",
    StartInANewCity: "Starte in einer neuen Stadt",
    StartInANewCityFinePrint: "(Oder starte deine derzeitge Stadt neu)",
    BatteryFuelDesc:
        "💡 Nachdem Batterien als Kraftstoff verwendet wurden werden diese zu Batteriegehäusen. Du kannst Batterie-Recykle bauen oder sie wieder aufladen",
    FriedChicken: "Gebratenes Hühnchen",
    Coffee: "Kaffee",
    Cocoa: "Kakao",
    CornSyrup: "Sirup",
    CornSyrupDesc: "Zuckerraffenerien produzieren Zucker mit Mais anstatt Zuckerrohr",
    Crop: "Ernte",
    FishPond: "Fish Pond",
    Fish: "Fisch",
    LoadGameErrorRetry: "Wiederholen",
    LoadGameErrorHardReset: "Hard Reset",
    FontSizeScaling: "Schriftgröße",
    FontSizeScalingDesc:
        "Verändert die Schriftgröße. Die Benutzeroberfläche könnte komisch aussehen. Benötigt Neustart.",
    FrozenVegetable: "Gefrohrenes Gemüse",
    MilkPowder: "Milchpulver",
    CannedFish: "Dosenfisch",
    CocoaPowder: "Kakaopulver",
    FrozenChicken: "Gefrohrenes Hühnchen",
    FrozenPork: "Gefrohrenes Schweinefleisch",
    CannedBeef: "Büchsenrindfleisch",
    FoodProcessingPlant: "Lebensmittelverarbeitungs-Betrieb",
    KansasCityBonus:
        "<li>Äcker und Gewächshäuser haben doppelte Produktion</li><li>Kostenloser Maistransport</li><li>Für jede Stufe boosten Staudämme angrenzende Äcker um 5%</li><li>Alle zwei Äcker bieten eine kostenlose Baugenehmigung</li><li>Die Sonne geht nie unter Richtlinie lässt Äcker 100% der Zeit arbeiten (auch Offline)</li><li>Doppelte Handelsquota beim Handeln von Mais</li><li>Lebensmittelverarbeitungs-Betrieb sind freigeschaltet</li>",
    KansasCityHydroDamBoost: "Kansas City einzigartiger Bonus: Dieser Staudamm gibt angrenzenden Äckern %{boost} Boost",
    PerthGeothermalPowerPlantBoost:
        "Perth einzigartiger Bonus: this geothermal power plant provides %{boost} boost to adjacent buildings that produce steel",
    PerthBonus:
        "<li>Building spinners rotate clockwise, which is opposite to other cities</li><li>Unique deposit: Geothermal vent</li><li>Unique building: Geothermal Power Plant</li><li>Unique policies: Adjacent Explorer (FREE), Factory Mining (FREE)</li>",
    Biofuel: "Biotreibstoff",
    RioDeJaneiro: "Rio de Janeiro",
    RioDeJaneiroBonus:
        "<li>Unique fuel: Biofuel</li><li>Pig, cow and chicken farms produces extra biofuel</li><li>Unique building: Biofuel Power Plant</li><li>Unique building: Cristo Redentor</li><li>Resource boosters can boost pig, cow and chicken farms</li><li>Logging camps produce 2x wood</li><li>Lumber mills have 2x capacity</li><li>Frozen chicken, frozen pork and canned beef have 2x trading quota</li>",
    BiofuelPowerPlant: "Biotreibstoff-Kraftwerk",
    CristoRedentor: "Cristo Redentor",
    CristoRedentorBanner:
        "Cristo Redentor gibt jedem Gebäude mit gleicher oder niedrigerer Stufe Angrenzungsbonus. Der Kulturverbrauch wächst exponential je mehr du baust",
    CristoRedentorDesc: "Verbraucht Kultur und verbessert jegliche angrenzenden Gebäude",
    Istanbul: "Istanbul",
    Wormhole: "Wurmloch",
    WavesSurvived: "überlebte Wellen",
    NumberOfWormholes: "Anzahl der Wurmlöcher auf der Karte",
    NextWave: "Nächste Welle",
    NextWaveUnitHP: "Einheiten-Lebenspunkte",
    NextWaveTotalCount: "totale Einheiten",
    NextWaveTotalCountDesc: "Gesamtanzahl an Einheiten, die aus jedem Wurmloch kommen",
    NextWaveSpeed: "Bewegungsgeschwindigkeit",
    NextWaveSpawnDelay: "Spawn-Frequenz",
    NextWaveSpawnDelayValue: "Alle %{number}s",
    NextWaveBonusMultiplier: "Bonus Multiplikator",
    NextWaveBonusMultiplierValue: "%{number}x",
    NextWaveTotalDamageNeeded: "benötigter Gesamtschaden",
    NextWaveTotalReward: "Gesamtbelohnung",
    StartWave: "Startwelle",
    WaveSpawned: "Erschienen",
    WaveEliminated: "Besiegt",
    WaveFailed: "Verloren",
    WaveRetry: "Wiederholen",
    WaveForfeit: "Aufgeben",
    Damage: "Schaden",
    DefenseCommandConvert: "Umwandeln",
    DefenseModule: "Verteidigungsmodul",
    DefenseModuleAddOne: "Füge ein Verteidigungsmodul hinzu",
    DefenseModuleRange: "Reichweite",
    DefenseModuleDamage: "Schaden",
    DefenseModuleBulletSpeed: "Projektilgeschwindigkeit",
    DefenseModuleAttackSpeed: "Angriffsgeschwindigkeit",
    DefenseModuleUpgrade: "Verbesserung",
    DefenseModuleMaxUpgrade: "Maximale Verbesserung",
    DefenseModuleCriticalDamageChance: "kritische Trefferwahrscheinlichkeit",
    DefenseModuleCriticalDamageChanceShort: "Crit Dmg %",
    DefenseModuleCriticalDamageMultiplier: "Kritischer-Schaden-Multiplikator",
    DefenseModuleCriticalDamageMultiplierShort: "Crit Dmg x",
    DefenseModuleBaseModule: "Basismodul",
    DefenseCommand: "Oberkommando der Verteidigung",
    DefenseCommandDesc: "Verursache Schaden mit Waffen und verteidige deine Basis gegen Eindringlinge",
    PathBlocked:
        "Du kannst keine Gebäude auf dieser Zelle bauen, da dadurch alle möglichen Wege von den Wurmlöchern zum Hauptquartier blockiert werden",
    WaveInProgressBuildRemoveDisabled:
        "Du kannst keine Gebäude auf dem Weg bauen und keine Gebäude während der Invasionswelle verkaufen",
    ExportSaveForTransfer: "Übertrage deinen Speicherstand",
    ExportSaveForTransferDesc:
        "Wähle diese Option wenn du deinen Speicherstand auf ein anderes Gerät übertragen willst. Dein Handelsrecht wird auf diesen Spielstand transferiert - du kannst wieder handeln, nachdem du den Speicherstand importierst. Auf deinem derzeitigen Gerät kannst du erst wieder nach einer Wartezeit handeln.",
    ExportSaveForBackup: "Backup für deinen Speicherstand",
    ExportSaveForBackupDesc:
        "Wähle diese Option, wenn du ein Backup deines Fortschrittes machen will. Dein derzeitiges Gerät behält das Handelsrecht - Das Backup zu importieren stellt das Handelsrecht erst nach einer Wartezeit wieder her",
    CheckRightToTrade: "Prüfe Handelsrecht",
    RightToTradeValid: "Handelsrecht",
    RightToTradeInvalid: "Kein Handelsrecht",
    RightToTradeInvalidDesc:
        "Dein Handelsrecht wurde auf einen anderen Speicherstand übertragen - Du musst den Speicherstand importieren, um dein Handelsrecht wiederherzustellen. Du kannst deine Handelsrecht auch ohne Speicherstand wiederherstellen, aber du kannst erst nach einem Cooldown wieder handeln und dein exportierter Speicherstand verliert sein Handelsrecht.",
    ForceRestoreRightToTrade: "Erzwinge Wiederherstellung (%{cooldown}-hour cooldown)",
    ImportSaveRestoreFail: "Verbindungsfehler, prüfe deine Internetverbindung",
    DefenseCommandConvertDesc: "Verwandle Ressourcen zu Schaden auf Basis der Handelszentrums-Preise.",
    MousewheelSensitivity: "Mausrad-Zoom-Sensitivität",
    MousewheelSensitivityDesc: "Passe die Sensitivität für das Mausrad an, wenn du rein- und rauszoomst.",
    PlayerTradeFilterWhatIHave: "Filter What I Have",
    PathTemporarilyBlocked:
        "You cannot build on this tile as there's a wave in progress. Check again after the wave is finished",
    MobilePriceChangeTitle: "Complementary Expansion Pack 2",
    MobilePriceChangeDesc:
        "Price for Expansion Pack 1 on %{platform} has been changed from $4.99 to $2.99. As you are our early supporter and have purchased the expansion with the original price, we would like to offer you a complimentary Expansion Pack 2 ($2.99) when it is released. This should be automatic - but if it doesn't work, you can click Restore Purchases or contact support",
    MoveBuilding: "Move Building",
    MoveBuildingInvalidTarget: "Failed to move the building - target tile is not valid",
    MoveBuildingMoving: "Select An Empty Tile...",
    WaveAutoNext: "Auto Start",
    WaveAutoNextDesc: "After successfully defending a wave, automatically claim the reward and start the next one",
    IstanbulBonus:
        "<li>Tower defense mode - convert your weapons to damage, defend against invaders and get cash rewards for further expansion</li><li>Army commands have 2x capacity</li><li>Tank factories have 2x capacity</li><li>Gun factories have 2x capacity</li><li>Missile factories have 2x capacity</li><li>Dynamite factories have 2x productivity</li>",
    PlayerTradeCancelTitle: "Cancel This Trade?",
    PlayerTradeCancelDesc: "Cancelling this trade will return your quota and part of your resource",
    PlayerTradeCancelYes: "Cancel Trade",
    PlayerTradeCancelNo: "Don't Cancel",
    SteamAutoCloudBackupDescV3:
        "Your latest progress is saved to Steam Cloud. The game also backs up every 10 minutes - you can force a backup at any time. Loading a backup will lose the right to trade and require a force restoration (subject to cooldown)",
    BuyFromTradeCenter: "Buy from Trade Center",
    BuyFromTradeCenterBestBid: "Best bid price from player trades",
    BuyFromTradeCenterBestAsk: "Best ask price from player trades",
    BuyFromTradeCenterAveragePrice: "Average %{price}",
};
