export const DE = {
    OK: "OK",
    SteelMill: "Stahlwerk",
    StainlessSteelPlant: "Edelstahlfabrik",
    CircuitFoundry: "Schaltkreis Fabrik",
    IntegratedCircuit: "integrierter Schaltkreis",
    OilWell: "Ölplattform",
    Wood: "Holz",
    LoggingCamp: "Forstbetrieb",
    LumberMill: "Sägewerk",
    Lumber: "Nutzholz",
    Paper: "Papier",
    PaperMill: "Papierfabrik",
    Book: "Buch",
    BookPublisher: "Buchverlag",
    OilRefinery: "Öl Raffinerie",
    Sell: "Verkaufen",
    Upgrade: "Upgrade",
    Build: "Bauen",
    Inspect: "untersuchen",
    Buildings: "Gebäude",
    Iron: "Eisen",
    Actions: "Aktionen",
    fuelType: "Treibstoffart",
    fuelCost: "Treibstoffkosten",
    fuelConsumption: "%{fuel} Verbrauch",
    fuelEconomy: "Treibstoffbilanz",
    fuelProduction: "%{fuel} Produktion",
    fuelInStorage: "%{fuel} Im Lager",
    Plastic: "Kunststoff",
    fuelSurplus: "%{fuel} Überschuss",
    Petrol: "Benzin",
    Buy: "Kaufen",
    NoLiquidity: "Zahlungsunfähig",
    NoLiquidityTurnOffAutoSell:
        "Es gibt nicht genügend Nachfrage für %{res}, der automatische Verkauf wurde abgestellt.",
    Multiplier: "Multiplikator",
    MultiplierDesc: "Alle 10, erhältst du +1 Multiplikator",
    SellBuilding: "Gebäude verkaufen",
    PowerGrid: "Stromversorgung",
    TradeAmount: "Handelsmenge",
    SortBy: "sortieren nach",
    SortByPrice: "Wert",
    SortByAmount: "Menge",
    NotEnoughResourcesForTrade: "Unzureichende Ressourcen im Handelszentrum um den Handel durchzuführen.",
    NotEnoughResources: "Unzureichende Ressourcen für diese Aktion",
    Transportation: "Transport",
    Cash: "Geld",
    Aluminum: "Aluminium",
    ResearchPoint: "Forschungspunkte",
    Unlock: "freischalten",
    BuildingUnlocked: "%{building} wurde freigeschalten",
    Science: "Wissenschaftspunkte",
    ScienceFromPowerDesc: "Stormerzeuger produzieren eine kleine Menege Wissenschaftspunkte, falls sie Strom erzeugen",
    Culture: "Kultur",
    School: "Schule",
    University: "Universität",
    Polytechnic: "Fachhochschule",
    Colosseum: "Kolosseum",
    WindTurbine: "Windkraftanlage",
    Engine: "Motor",
    EngineFactory: "Motorenfabrik",
    CameraFactory: "Kamerafabrik",
    Camera: "Kamera",
    Gun: "Waffe",
    GunFactory: "Waffenfabrik",
    Aircraft: "Flugzeug",
    AircraftFactory: "Flugzeugfabrik",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Zeppelinfabrik",
    Tank: "Panzer",
    TankFactory: "Panzerwerk",
    MinimumTradingAmount: "Du kannst nicht mit weniger, als der Mindestmenge Handeln",
    CoalPowerPlant: "Kohlekraftwerk",
    PetrolPowerPlant: "Ölkraftwerk",
    Copper: "Kupfer",
    Gas: "Erdgas",
    GasPump: "Erdgasförderung",
    GasPowerPlant: "Gaskraftwerk",
    Missile: "Fernlenkgeschoss",
    MissileFactory: "Fernlenkgeschossfabrik",
    Rocket: "Rakete",
    RocketFactory: "Raketenfabrik",
    BuildingPermit: "Baugenehmigung",
    BuildingPermitDesc:
        "Du hast die Baugenehmigung für %{amount} Gebäude, du hast bereits  %{amountBuilt} gebaut und hast %{amountLeft} übrig",
    BuildingLocked: "Das Gebäude ist noch nicht verfügbar, du musst es zuerst im Forschungslabor freischalten",
    BuildQueue: "Bau Warteschlange",
    BuildQueueDesc: "Anzahl der Gebäude in der Warteschleife",
    MaxBuilders: "Max Baumeister",
    MaxBuildersDesc: "Anzahl der Gebäude die du gleichzeitig bauen kannst",
    Silicon: "Silizium",
    AluminumMine: "Aluminiummine",
    CopperMine: "Kupfermine",
    SiliconMine: "Siliziummine",
    IronMine: "Eisenmine",
    CoalMine: "Kohlemine",
    Headquarter: "Hauptquartier",
    ResearchLab: "Forschungslabor",
    TradeCenter: "Handelszentrum",
    Resources: "Ressoursen",
    NotEnoughPower: "💡 Nicht genug Energie, erwäge die Erhöhung der Energieproduktion",
    NotEnoughfuel: "Nicht genug %{fuel} für diese Aktion",
    NotEnoughCash: "Nicht genug Geld für diese Aktion",
    NotEnoughSwissMoney: "Nicht genug Schweizer Franken für diese Aktion",
    BuildingNotEnoughfuel: "💡 Nicht genug %{fuel}",
    AutoSell: "Auto verkaufen",
    SellAll: "verkaufe ALLES",
    Change: "ändern",
    StatisticsBureau: "Statistik Agentur",
    LogisticsDepartment: "Logistik Insitut",
    From: "Von",
    Top20fuelCost: "Top 20 Kraftstoff Verbraucher",
    To: "Zu",
    TransportTime: "Transportdauer",
    TopN: "Top %{n}",
    Warehouse: "Lagerhaus",
    TradeWarehouse: "Handelslager",
    Coal: "Kohle",
    Video: "Video",
    ClothingFactory: "Kleidungsfabrik",
    Clothes: "Kleidung",
    Fashion: "Mode",
    FashionFactory: "Modedesigner",
    VideoFarm: "Videofabrik",
    SantaFactory: "Santafabrik",
    Santa: "Santa",
    Car: "Auto",
    CarFactory: "Autofabrik",
    Ship: "Schiff",
    SolarPanel: "Solarmodul",
    SolarPanelDesc: "💡 Solarmodule arbeiten nur 5 von 10 Sekunden - alle Kreisläufe sind verbunden",
    WindDesc: "💡 Windkraftanlagen arbeiten nur 8 von 10 Sekunden - Kreisläufe sind nicht verbunden",
    Movie: "Film",
    MovieStudio: "Filmstudio",
    Sitcom: "Sitcom",
    TVStudio: "TV Studio",
    PC: "PC",
    GameStudio: "Game Studio",
    Game: "Game",
    ComputerFactory: "Computerfabrik",
    Shipyard: "Werft",
    PowerUsage: "Energieverbrauch",
    PowerSupply: "Energieerzeugung",
    PowerSurplus: "Energieüberschuss",
    Level: "Stufe",
    Power: "Energie",
    CentralBank: "Zentralbank",
    ResourceInput: "Eingang",
    ResourceOutput: "Ausgang",
    ResourceStorage: "Lager",
    ResourceChange: "Wechsel",
    ResourceInOutDesc: "💡 Klicke auf Aus-Ein Tap on Out-In Zahl unterhalb um die Entsprechenden Gebäude zu markieren",
    ResourceChart: "Ressourcentabelle",
    MarketUpdateIn: "Marktpreisupdate in %{time}",
    Income: "Einkommen",
    Semiconductor: "Halbleiterchip",
    SemiconductorFactory: "Halbleiterchipfabrik",
    SemiconductorFab: "Schaltkreisgießerei",
    Steel: "Stahl",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Farm",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Farm",
    Guitar: "Gitarre",
    GuitarFactory: "Gitarrenfabrik",
    Drum: "Schlagzeug",
    DrumFactory: "Schlagzeugfabrik",
    RecordingStudio: "Tonstudio",
    OperaHouse: "Opernhaus",
    CoalGasificationPlant: "Kohlevergasungsanlage",
    GasProcessingPlant: "Gasveredelungsanlage",
    Music: "Musik",
    Glass: "Glas",
    PhoneFactory: "Handyfabrik",
    Phone: "Handy",
    GlassFactory: "Glasmanufaktur",
    Oil: "Öl",
    Chromium: "Chrom",
    ChromiumMine: "Chrommine",
    Uranium: "Uran",
    EnrichedUranium: "angereichertes Uran",
    NuclearPowerPlant: "Kernkraftwerk",
    UraniumEnrichmentPlant: "Urananreicherungsanlage",
    UraniumMine: "Uranmine",
    Titanium: "Titan",
    TitaniumMine: "Titanmine",
    TitaniumAlloyPlant: "Titanmanufaktur",
    ChromiumAlloyPlant: "Chrommanufaktur",
    Input: "Eintrag",
    PanelPosition: "Paneel Position",
    PanelPositionDesc:
        "Anzeige des Seitenpaneels links, rechts oder automatisch (entsprechend des aktuell ausgewählten Feldes)",
    InputCapacity: "benötigte Materialien",
    InputCapacityPerCycle: "benötigte Materialien / Zyklus",
    Output: "Produktion",
    OutputCapacity: "produzierte Materialien",
    OutputCapacityPerCycle: "produzierte Materialien / Zyklus",
    ResourceDeposit: "Ressourcen Absatz",
    RecommendedBuilding: "💡 Dieses Feld hat %{resource} Austrag",
    AdjacentBonus: "Angrenzungsbonus",
    AdjacentBonusDesc:
        "Du erhältst %{bonus}% zusätzliche Kapazität für jedes angrenzende arbeitende Gebäude der selben Art",
    ConsiderIncreaseProduction: "💡 Versuche %{resource} Produktionserhöhrung",
    AlwaysTransportInput: "Vorratsmodus",
    AlwaysTransportInputTradeCenter: "Immer exportieren",
    AlwaysTransportInputTradeCenterDesc:
        "Transportiere Ressourcen immer zum Marktplatz, auch wenn der automatische Verkauf für die Ressource nicht aktiviert ist",
    AlwaysTransportInputDesc: "Transportiere benötigte Ware immer, auch wenn es mehr ist als benötigt",
    ProductionCycleLength: "Produktionszyklus",
    ProductionCycleLengthDesc:
        "Dauer eines Produktionszyklus in Sekunden. Eine Verlängerung des Zyklus erhöht entsprechend die benötigen und hergestellten Waren",
    MaxInputDistance: "Max. Importentfernung",
    MaxInputDistanceDesc:
        "Die maximale Distanz des Gebäudes woher Rohstoffe bezogen werden, gemessen in Zellenanzahlen",
    AutoSellCapacity: "automatsiche Verkaufsmenge",
    AutoSellCapacityDesc: "Maximale Anzahl an Ressourcen die automatisch verkauf werden können pro Sekunde/Ressource",
    CurrentAutoSellCapacityMultiplier: "Aktueller Multiplikator: x%{n}",
    AutoSellConcurrency: "automatische Verkaufsanzahl",
    AutoSellConcurrencyDesc: "Maximale Anzahl der Ressourcen die gleichzeit automatisch verkauft werden können",
    MaxAutoSellConcurrencyReached:
        "Du hast die maximale automatische Verkaufsanzahl erreicht, schalte eine andere ab um diese zu aktivieren",
    CannotSellBuilding: "Du kannst diese Gebäude zurzeit nicht verkaufen",
    WallStreet: "Wall Street",
    MarketCap: "Marktkapitalisierung",
    MarketCapDesc: "Gesamtkapital (i.e. Marktwert) deiner Organisation",
    BuildingValuation: "Gebäudewert",
    BuildingValuationDesc: "Gesamtwert deiner Gebäude, inklusive Baugenehmigungen und Aufwertungen",
    ResourcesValuation: "Ressourcenwert",
    ResourcesValuationDesc: "Gesamtwert der Ressourcen im Inventar",
    Battery: "Batterie",
    BatteryFactory: "Batteriefabrik",
    RatingBuy: "Kaufen",
    RatingSell: "Verkaufen",
    SwissShop: "Schweizer Bank",
    RatingHold: "Durchschnittlich",
    RatingOutperform: "Überdurchschnittlich",
    RatingUnderperform: "Unterdurchschnittlich",
    StockRating: "Unternehmensbewertung",
    JetEngine: "Düsentriebwerk",
    Helicopter: "Helikopter",
    Lithium: "Lithium",
    LithiumMine: "Lithiummine",
    LiionBatteryFactory: "Li-ion Batteriefabrik",
    HelicopterFactory: "Helikopterfabrik",
    Satellite: "Satellit",
    ToyFactory: "Spielzeugfabrik",
    Toy: "Spielzeug",
    SpaceStation: "Weltraumstation",
    SpaceStationFactory: "Weltraumstationsfabrik",
    OperatingSystem: "Betriebssystem",
    OperatingSystemCompany: "Betriebssystemhersteller",
    LinuxDistribution: "Linux Vertrieb",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Konsole",
    ConsoleFactory: "Konsolenfabrik",
    Train: "Zug",
    TrainFactory: "Zugfabrik",
    ShoeFactory: "Schuhfabrik",
    Shoes: "Schuhe",
    ArtilleryFactory: "Artilleriefabrik",
    Artillery: "Artillerie",
    SubmarineFactory: "U-Boot Fabrik",
    Submarine: "U-Boot",
    Spaceship: "Raumschiff",
    RobotFactory: "Roboterfabik",
    Robot: "Roboter",
    SpaceshipFactory: "Raumschifffabrik",
    SatelliteFactory: "Satellitenfabrik",
    JetEngineFactory: "Düsentriebwerksfabrik",
    StockRatingDesc:
        "Die Aktienwertung beruht auf Wall Street Auswertungen, wirkt sich auf deine Marktobergrenze aus und aktualisiert sich zusammen mit dem Handel",
    InterestRate: "Übernacht Anteil",
    InterestRateDesc: "Diesen Anteil erwirtschaftest du auf dem Markt während du Offline bist",
    OfflineEarning: "Offline Einkommen",
    OfflineEarningDesc: "Offline Einkommen ist abhängig von der Marktobergrenze und der Zinsrate",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline Erwerbszeit",
    OfflineEarningTimeDesc: "Du erhältst Offline Einkommen bis zu diesem Schwellenwert",
    BuyPermit: "Kauferlaubis",
    NotEnoughBuildingPermit: "Nicht genug Baugenehmigungen. Bitte kaufen Sie mehr, um neue Gebäude zu bauen",
    MovingAverage: "Gleitender Durchschnitt",
    MovingAverageDesc: "Zeigen Sie den gleitenden Durchschnitt der Ressourcenänderung anstelle der Echtzeitänderung an",
    AllowZoom: "Zoomen",
    AllowZoomDesc:
        "Aktivieren Sie die Zoomunterstützung. Verwenden Sie Ihr Mausrad zum Zoomen. Aktueller Zoom ist %{zoom}",
    AllowZoomMobileDesc:
        "Aktivieren Sie die Zoomunterstützung. Sie können zum Zoomen kneifen. Aktueller Zoom ist %{zoom}",
    Settings: "Einstellungen",
    SellBuildingDesc:
        "Durch den Verkauf eines Gebäudes erhalten Sie 50% Ihrer Investition zurück und 50% der Ressourcen werden zum Handelszentrum transportiert",
    SellBuildingFullRefundDesc:
        "Die Gebäuderückgewinnungsrichtlinie ist aktiv. Wenn Sie ein Gebäude verkaufen, erhalten Sie die volle Rückerstattung bis in %{time}",
    Sound: "Sound-Effekt",
    SoundDesc: "Aktivieren Sie Soundeffekte wie Klick- oder Fehlersound",
    AutoHighlight: "Automatische Markierung",
    AutoHighlightDesc: "Markieren Sie automatisch Gebäude desselben Typs, wenn Sie ein Gebäude auswählen",
    MusicDesc: "Musik einschalten: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Symbole",
    MisplacedBuilding: "⛔ Das %{building} wird nicht auf die richtige Ressource gelegt",
    UnderConstruction: "%{building} befindet sich im Bau",
    Left: "Links",
    Right: "Rechts",
    Auto: "Auto",
    HighlightBuildings: "Gebäude hervorheben",
    HighlightTurnedOff: "... sind abgeschaltet",
    HighlightStockpileModeOn: "...die den Lagermodus aktiviert haben",
    HighlightProductionCycleNotDefault: "...diese haben Produktionszyklus > 1",
    HighlightMaxInputDistanceNotDefault: "...haben die maximale Eingangsentfernung < ∞",
    HighlightNotMakingProfit: "...machen keinen Gewinn",
    NBuildingsAreHighlighted: "%{n} Gebäude sind hervorgehoben",
    OnlyToWarehouse: "Nur für Lager",
    OnlyToWarehouseDesc: "Nur Lager können Ressourcen von diesem Gebäude transportieren",
    TurnOffProduction: "Stilllegen",
    TurnOffProductionDesc:
        "Schalten Sie die Produktion des Gebäudes aus. Das Gebäude wird keine Ressourcen mehr transportieren und keinen Strom verbrauchen",
    ApplyToAll: "Auf alle anwenden %{building}",
    fuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "unbegrenzt",
    Transport: "transport",
    TileModifier: "Zellen-Modifikator",
    ShowAllModifiers: "Alle Modifikatoren anzeigen",
    HideAllModifiers: "Alle Modifikatoren ausblenden",
    NumberOfBuildings: "Anzahl der Gebäude, die Sie haben",
    ShowContent: "Inhalt zeigen",
    HideContent: "Inhalt ausblenden",
    BuyExpansionPack: "Kaufen für %{price}",
    Cities: "Städte",
    WarehouseInputCapacityDesc: "Menge an Ressourcen, die das Lager pro Sekunde und Ressource aufnehmen kann.",
    InputStrategy: "Eingangsstrategie",
    InputStrategyClose: "Näher",
    InputStrategyCloseDesc: "Bevorzugen Sie das nächstgelegene Lager mit genügend Ressourcen",
    InputStrategyFar: "Weiter",
    InputStrategyFarDesc: "Bevorzugen Sie das am weitesten entfernte Lager mit genügend Ressourcen",
    InputStrategyAmount: "Menge",
    InputStrategyAmountDesc:
        "Bevorzugen Sie das Lager mit der größten Menge an Ressourcen, unabhängig von der Entfernung",
    fuelCostSave: "Treibstoffeinsparung",
    fuelCostSaveDesc:
        "Lagerhäuser sparen im Vergleich zu anderen Gebäuden einen bestimmten Prozentsatz an Treibstoff für den Transport von Ressourcen nach innen. Je höher das Niveau, desto mehr wird gespart",
    SoftwareCompany: "Softwareunternehmen",
    Software: "Software",
    ScreenFactory: "Bildschirmfabrik",
    Screen: "Bildschirm",
    JoinDiscord: "Besuchen Sie unseren Discord-Server, um die neuesten Updates, Tipps und Diskussionen zu erhalten",
    ClaimOfflineEarning: "Offline-Einnahmen abholen",
    OfflineTime: "Offline Zeit",
    Minutes: "%{time}min",
    MaxUpgrade: "Maximales Upgrade",
    MaxUpgradeDesc: "Sie haben das maximale Upgrade erreicht",
    ClaimAmount: "Geld +%{amount}",
    EarningPerMinute: "Verdienstquote",
    EffectiveTime: "Effektive Zeit",
    EffectiveTimeDesc: "Ihre effektive Offline-Verdienstzeit ist begrenzt %{time}min.",
    BuildSearchPlaceholder: "Geben Sie Gebäude oder Ressource für die Suche ein",
    MineOverlayWarning: "%{building} wird vom Zellenmodifikator nicht beeinflusst",
    WholesaleCenter: "Großhandelszentrum",
    OrderFrom: "Bestellung von %{name}",
    ExpireIn: "läuft aus in",
    ProfitMargin: "Gewinnspanne",
    NotMakingProfitWarning: "💡 Die Produktion ist nicht rentabel, überlegen Sie, ob Sie es herunterfahren möchten",
    TurnOnAllProductions: "Produktion An",
    TurnOnAllProductionsDesc:
        "Produktionen aller Gebäude einschalten, kann nicht verwendet werden, wenn die Kostensparrichtlinie aktiv ist",
    OperationSuccessful: "Der Vorgang wurde erfolgreich abgeschlossen",
    TurnOn: "Einschalten",
    Reward: "Belohnung",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/Zyklus",
    PolicyPoint: "Richtlinienpunkte",
    PolicyPointPerMinute: "Herstellungsrate",
    PolicyPointPerMinuteDesc: "Sie erhalten jede Minute im Spiel Richtlinienpunkte",
    YourWilLGaimPolicyPoints: "Du erhältst %{amount} Richtlinienpunkte in %{time}s",
    PolicyPointDesc: "💡 Je mehr Richtlinien aktiv sind, desto höher sind die Kosten für jede Richtlinie",
    NextOrderIn: "Nächste Bestellung in",
    FillOrder: "Auftrag erfüllen",
    RejectOrder: "Ablehnen",
    YouHave: "Du besitzt %{amount}",
    WholesaleCenterLocked:
        "Du brauchst mindestens %{required} verschiedene Ressourcen zum Freischalten des Großhandelszentrums. Du hast nur %{current} der benötigten Ressourcen",
    OrderFilled: "Die Bestellung von %{from} wurde erfolgreich ausgeliefert!",
    PolicyCenter: "Bundestag",
    NewOrder: "Eine neue Bestellung von %{from} ist angekommen, nachzusehen im  Großhandelszentrum",
    Policies: "Richtlinien",
    PolicyNotEnoughTime: "Sie haben nicht genügend Richtlinienpunkte für diese Richtlinie",
    TimeLeft: "%{time} übrig",
    WholesaleCenterOrderFaster: "Weltausstellung",
    WholesaleCenterOrderFasterDesc:
        "Das Großhandelszentrum erhält Bestellungen 2x schneller und die Bestellgröße ist 2x größer",
    PolicyOilWellPowerx2: "Verdopple Ölquelle",
    PolicyOilWellPowerx2Desc: "Ölquellen produzieren 2x Öl und 2x verbrauchen Strom",
    HalfTransportSpeed: "Verlangsamen, um zu sparen",
    HalfTransportSpeedDesc:
        "Die Transportgeschwindigkeit wird um 25% verlangsamt und die Kraftstoffkosten um 25% gesenkt.",
    RefineryMoreOil: "Mehr Treibstoff Mehr Probleme",
    RefineryMoreOilDesc: "Ölraffinerien produzieren 50% mehr Benzin und 50% weniger Kunststoff",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Gebäude bevorzugen den Transport aus nahen Quellen, anstatt in jedem Zyklus nach der besten Quelle zu suchen (KOSTENLOSE RICHTLINIE)",
    RefineryMorePlastic: "Mehr Plastic Mehr Probleme",
    RefineryMorePlasticDesc: "Ölraffinerien produzieren 50% weniger Benzin und 50% mehr Kunststoff",
    FreeOilTransport: "Kostenloser Öltransport",
    FreeOilTransportDesc: "Der Öltransport kostet keinen Kraftstoff, aber Ölquellen verbrauchen 2x Strom",
    SuperSteelMill: "Herzen aus Eisen",
    SuperSteelMillDesc: "Stahlwerke verbrauchen 50% weniger Kohle, aber 25% mehr Eisen und Strom",
    AlSemiconductor: "Al Schaltkreis",
    AlSemiconductorDesc: "Schaltungsgießereien verwenden Aluminium anstelle von Kupfer",
    CostSaver: "Kostenersparnis",
    CostSaverDesc: "Wenn der Eintrag eines Gebäudes mehr kostet als der Austrag, stellen Sie die Produktion ein",
    CostSaverBuildingDesc:
        "Die Kostensparrichtlinie ist aktiv. Die Produktion wird basierend auf ihrer Rentabilität automatisch ein- und ausgeschaltet",
    CostSaverBuildingWarning:
        "Die Kosteneinsparungsrichtlinie ist aktiv. Sie können die Produktion nicht manuell ändern",
    GlassUseCoal: "Schwarzes Glas",
    GlassUseCoalDesc: "Glasfabriken verbrauchen 50% mehr Kohle und 50% weniger Silizium",
    AdjacentBonusOnlyOutput: "Angrenzender Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Der Angrenzendungsbonus erfordert nicht mehr Eintrag, verbraucht aber mehr Strom und ist nur zu 50% effektiv",
    IronMine2xOutput: "Schwermetall",
    IronMine2xOutputDesc: "Eisenminen produzieren 2x Eisen, aber der Eisentransport kostet 2x Treibstoff",
    SolarPanelAlwaysWork: "Die Sonne geht nie unter",
    SolarPanelAlwaysWorkDesc: "Solarzellen arbeiten 100% der Zeit, produzieren aber 60% weniger Strom",
    SteelScience: "Wissen durch Stahl",
    SteelScienceDesc: "Stahlwerke verbrauchen 2x Ressourcen und produzieren zusätzlich Wissenschaftspunkte",
    ShowWarehouse: "Lager freischalten",
    ShowWarehouseDesc:
        "Ein Lagerhaus ist ein spezielles Gebäude, das nur Ressourcen transportiert und lagert und Kraftstoff spart (KOSTENLOSE RICHTLINIEN).",
    WholesaleCenterProducingOnly: "Großhandelspartner",
    WholesaleCenterProducingOnlyDesc:
        "Großhandelszentrum-Bestellungen enthalten nur Ressourcen, die derzeit produziert werden (Sie müssen auch die Anzahl der erforderlichen Ressourcen produzieren, um das Großhandelszentrum freizuschalten).",
    ShoppingSpree: "Einkaufsbummel",
    ShoppingSpreeDesc:
        "Wenn die Ausgabekapazität einer Ressource nicht ausreicht, kaufen Sie den Mangelbetrag automatisch am Marktplatz (wenn die Ressource automatisch weiterverkauft wird, wird er ignoriert).",
    ShoppingSpreeTradeCenterDesc:
        "💡 Wenn die Einkaufsbummel-Richtlinie aktiviert ist, kauft der Marktplatz automatisch Ressourcen, die knapp sind",
    ExtraPolicyPoints: "Politischer Lobbyist",
    ExtraPolicyPointsDesc: "Erhöhen Sie die Produktionskapazität für Richtlinienpunkte um 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromlegierungsanlagen verwenden kein Lithium, sondern 2x Eisen",
    DoubleTileModifier: "Die Kraft der Natur",
    DoubleTileModifierDesc: "Der Effekt des Modifikators aller Zellen x2 - sowohl positiv als auch negativ",
    TileModifierOutputOnly: "Zellenmodifikator Plus",
    TileModifierOutputOnlyDesc:
        "Zellenmodifikatoren wirken sich nur auf die Ausgabe anstatt auf den Eintrag und Ausgabe aus, sind jedoch nur zu 50% wirksam",
    GasPlantPetrol: "Gasliquidator",
    GasPlantPetrolDesc: "Gaskraftwerke verwenden zusätzliches Gas zur Herstellung von Treibstoff",
    BuildingRecycle: "Gebäuderecycling",
    BuildingRecycleDesc:
        "Erhalten Sie die volle Rückerstattung, wenn Sie ein Gebäude innerhalb von 1 Minute nach dem Bau verkaufen",
    CoalPlantfuel: "Kohle Liquidator",
    CoalPlantfuelDesc: "Kohlekraftwerke verwenden zusätzliche Kohle zur Herstellung von Treibstoff",
    Welcome: "Willkommen",
    SeeTutorialAgain: "Tutorial wiederholen",
    ReadSteamGuide: "Offizieller Guide auf Steam",
    HelpTranslateTheGame: "Hilf das Spiel zu übersetzen",
    SkipTutorial: "Tutorial überspringen",
    NextTutorial: "weiter",
    Tutorial1:
        "Industry Idle ist ein <em> Ressourcenmanagement </ em> -Spiel, in dem Sie Fabriken bauen🏭, Waren produzieren📦 und Geld verdienen💸.<br><br>Lassen Sie uns einige grundlegende Konzepte durchgehen, um Ihnen den Einstieg zu erleichtern - es dauert nicht lange verspreche ich.",
    Tutorial2:
        "Alle Gebäude benötigen Strom⚡, du hast ein <em>Windrad</em> welches Strom erzeugt. Du kannst deine aktuelle Netzversorgung auf der linken Seite der oberen Leiste sehen.<br><br> Möglicherweise haben Sie bemerkt, dass Windkraftanlagen nur <em>80%</em> der Zeit arbeiten. Du kannst auch andere Kraftwerkstypen bauen, die dauerhaft Strom erzeugen.",
    Tutorial3:
        "Sie haben viele <em> Ressourcenablagerungen </ em> auf der Karte. Um Ressourcen zu gewinnen, müssen Sie Minen <em> auf </ em> der entsprechenden Lagerstätte errichten. <br> <br> Zum Beispiel haben Sie eine <em> Ölquelle🛢️ </ em>, die <em extrahiert > Öl </ em> aus einem Ölvorkommen. <br> </ br> Ressourcenvorkommen sind unbegrenzt - Sie müssen sich keine Sorgen machen, dass sie aufgebraucht sind. Abgesehen von Minen können andere Gebäude auf jeder leeren Fliese gebaut werden.",
    Tutorial4:
        "Der Transport von Ressourcen kostet Kraftstoff. Auf dieser Karte können Sie <em> Benzin⛽ </ em> als Kraftstoff verwenden. Sie haben eine <em> Ölraffinerie </ em>, die Öl aus der Ölquelle transportiert und Benzin produziert. <br> <br> Die winzigen beweglichen <em> Punkte </ em> repräsentieren die Echtzeitbewegung von Ressourcen. Sie sollten Ihre Gebäudestandorte optimieren, um die Entfernung zu minimieren. <br> <br> <em> Durch die Verbesserung </ em> Ihrer Gebäude wird die Leistung erhöht, aber auch der Stromverbrauch und der erforderliche Kraftstoff. <br> <br > Sie können Ihre Kraftstoffart im Transportzentrum ändern🚦. Denken Sie daran, sicherzustellen, dass Ihre Kraftstoffproduktion über dem Verbrauch liegt. Andernfalls wird Ihre Produktion gestoppt, wenn Ihnen der Kraftstoff ausgeht.",
    Tutorial5:
        "Um Geld zu verdienen, müssen Sie Ihre Ressourcen über das Handelszentrum verkaufen. Aktivieren Sie dazu einfach <em> Automatischen Verkauf </ em> für diese Ressource. <br> </ br> Sie können Ressourcen auch auf dem Marktplatz kaufen. Denken Sie daran, <em> wenn Sie eine Ressource kaufen, erhöhen Sie den Preis </ em> und wenn Sie eine Ressource verkaufen, senken Sie den Preis. <br> <br> Der Markt ist <em> unbeständig </ em > und der Preis 📈 ändert sich regelmäßig.",
    Tutorial6:
        "Um neue Gebäude zu bauen, müssen Sie diese zuerst im <em> Forschungslabor🧪 </ em> freischalten. Das Forschungslabor wandelt auch Wissenschaft in Forschungspunkte um. <br> <br> Ihre Windkraftanlage (und andere Kraftwerke) produziert beim Betrieb eine kleine Menge Wissenschaft. Und Sie können eine Schule und andere spezielle Gebäude bauen, um die Wissenschaft später anzukurbeln. <br> <br> Jetzt haben Sie alle Grundlagen gelernt und beginnen, Ihre Wirtschaft aufzubauen! Hier sind einige <em> Geld💸 </ em> und <em> Benzin </ em>, um Ihnen einen Starthilfe zu geben.",
    WelcomePlay: "Spielen",
    WelcomePlayMuted: "Spiel (🔇Musik)",
    Changelog: "Neuerungen",
    ChangelogGotIt: "Verstanden",
    Chat: "Chat",
    Send: "Senden",
    Import: "Import",
    Export: "Export",
    SteamCloudBackup: "Steam Cloud Sicherung",
    LastBackupAt: "Letze Sicherung",
    RestoreFromBackup: "Sicherung wiederherstellen",
    RestoreFromBackupFail:
        "Wiederherstellung aus der Steam Cloud fehlgeschalgen: sind Sie sicher das dort seine Sicherung existiert?",
    RestoreFromBackupTitle: "Bist du sicher?",
    RestoreFromBackupDesc:
        "Normalerweise müssen Sie keine Wiederherstellung aus der Cloud-Sicherung durchführen, es sei denn, Ihre lokale Speicherung geht verloren. Cloud-Backups sind etwas älter als Ihre lokale Sicherung",
    ChatMessages: "Chat Nachrichten",
    ChatPlaceholder: "Geben Sie Ihre Nachricht ein: maximal 100 Zeichen",
    ChangeName: "Ändern",
    SaveName: "Speichern",
    NameValidationRule: "Ihr Name sollte nur Buchstaben und Zahlen enthalten und zwischen 5 und 15 Zeichen liegen",
    NameValidationRuleProfanity: "Ihr Name sollte keine Obszönitäten enthalten",
    ChatMessageRateLimit: "Sie können nur alle 10 Sekunden eine neue Chat-Nachricht senden",
    NameSaved: "Ihr Name wurde erfolgreich geändert",
    NoMessages: "Keine neue Nachrichten",
    Leaderboard: "Bestenliste",
    LeaderboardDesc: "Die Rangliste sind die gesamten Schweizer Franken die Sie jemals verdient haben",
    Name: "Name",
    Rank: "Rang",
    Tips1: "Aktienbewertungen haben 5 Kriterien: Kaufen, Überperformance, Halten, Underperformance und Verkaufen",
    Tips2:
        "Gebäude stellen den Transport von Ressourcen ein, wenn bereits genug für die Produktion vorhanden ist, es sei denn, Sie aktivieren den Stapelmodus",
    Tips3:
        "Die Kraftstoffkosten für den Ressourcentransport werden durch die Entfernung und die Menge der Ressourcen bestimmt",
    Tips4:
        "Gebäude transportieren eine Ressource nur, wenn die auf der Karte gefundene Menge die Eingabekapazität überschreitet",
    Tips5:
        "Gebäude transportieren eine Ressource nur vom Großhandelszentrum, wenn der automatische Verkauf für diese Ressource deaktiviert ist",
    Tips6:
        "Sie können die Kraftstoffkosten für eine Ressource im entsprechenden Abschnitt zur Eingabekapazität anzeigen",
    Tips7:
        "Wenn Sie eine Ressource kaufen, erhöhen Sie den Preis. Wenn Sie eine Ressource verkaufen, senken Sie den Preis",
    Tips8:
        "Sie können das Diagramm für die Menge jeder Ressource und ihre zeitliche Änderung im Statistikbüro anzeigen",
    Tips9:
        "Die für ein Gebäude benötigten Forschungspunkte werden durch den Marktpreis seiner Inputressourcen bestimmt",
    Tips10:
        "Unterschiedliche Ressourcen werden auf dem Markt unterschiedlich bewertet - seien Sie immer auf Marktvschwankungen vorbereitet",
    Tips11:
        "Es ist eine gute Idee, immer Ihre Strom- und Kraftstoffversorgung zu überprüfen, bevor Sie Ihre Produktion erweitern",
    FPS30: "Energiesparmodus",
    OfflineModeDesc:
        "Es kann keine Verbindung zum Server hergestellt werden: Es werden keine Offline-Einnahmen generiert. Bitte überprüfe deine Internetverbindung",
    OptOut: "Optischer Ausgang",
    OptIn: "Zurücksetzen und aktivieren",
    LeaderboardOptOut: "Leaderboard-Deaktivierung",
    LeaderboardOptOutDesc:
        "Dadurch wird keine Ranglisten-Punktzahl mehr gesendet. BITTE BEACHTEN SIE: Wenn Sie die Bestenliste später aktivieren möchten, müssen Ihre Daten zurückgesetzt werden",
    LeaderboardOptIn: "Bestenliste zurücksetzen und aktivieren",
    LeaderboardOptInDesc:
        "Ihre Daten müssen zurückgesetzt werden, beFvor Sie die Bestenliste wieder aktivieren können. Sind Sie sicher?",
    RewardAdsFailed: "Das Belohnungsvideo wurde nicht abgeschlossen",
    RewardAdsNotAvailable: "Belohnungsvideo ist nicht verfügbar (derzeit wird nur iOS / Android unterstützt)",
    OfflineEarningDoubleSuccess: "Sie haben Ihr Offline-Einkommen verdoppelt",
    FPS30Desc:
        "Wenn Sie den Energiesparmodus aktivieren, wird das Spiel mit 30 FPS anstelle von 60 FPS ausgeführt. Dadurch hält Ihr Akku länger",
    HighlightAll: '"%{type}"markieren',
    HighlightInput: "🔍 %{type} Verbraucher hervorheben",
    HighlightOutput: "🔍 %{type} Erzeuger hervorheben",
    TotalInput: "Gesamteingabekapazität",
    TotalOutput: "Gesamtausgabekapazität",
    RunOutIn: "Leer in %{time}",
    fuelRunOutWarning:
        "💡 Ihr Kraftstoffverbrauch übersteigt die Produktion. Wenn der Kraftstoff ausgeht, wird Ihr Transport angehalten",
    InAmount: "Ein: %{number}",
    OutAmount: "Aus: %{number}",
    SwissBank: "Schweizer Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Wenn Sie in einer neuen Stadt beginnen, erhalten Sie %{money} 💵",
    RestorePurchases: "Einkäufe wiederherstellen",
    RestorePurchasesSuccess: "Ihre Einkäufe wurden wiederhergestellt",
    RestorePurchasesFailed: "Ihre Einkäufe wurden nicht wiederhergestellt",
    ExpansionPacks: "Erweiterungspakete",
    ExpansionPack1: "Erweiterungspaket 1",
    ExpansionPack1Owned: "Erweiterungspaket 1",
    RequireExpansionPack1: "Erweiterungspaket 1",
    RequireExpansionPack1Desc: "Dies ist nur für das Erweiterungspaket 1 verfügbar",
    RequireAnyExpansionPack: "Erweiterungspakete exklusiv",
    RequireAnyExpansionPackDesc: "Für diese Funktion müssen Sie mindestens eines der Erweiterungspakete besitzen",
    HideRewardAd: "Belohnungsanzeigen ausblenden",
    HideRewardAdDesc:
        "Alle In-Game-Anzeigen sind optionale Belohnungsanzeigen. Dadurch werden alle Belohnungsanzeigen vor dem Spiel ausgeblendet.",
    HideDiscordBanner: "Discord Banner ausblenden",
    HideDiscordBannerDesc: "Ausblenden des Discord und Storefront-Banner im Hauptquartier",
    HideChat: "Chat-Nachrichten ausblenden",
    HideChatDesc: "Chat-Nachricht in der unteren Symbolleiste ausblenden",
    SortedByDeficit: "Sortiert nach Defizit",
    PurchaseFailed: "Der Kauf wurde nicht abgeschlossen",
    PurchaseSteamContinue: "Bitte beenden Sie Ihren Kauf bei Steam",
    PurchaseSuccess: "Der Kauf ist abgeschlossen, danke für Ihre Unterstützung",
    PrestigeCurrency: "Schweizer Franken 💵",
    RestartDesc:
        "💡 Willst du nur neu starten? Sie können oben auf Start in einer neuen Stadt tippen und Ihre aktuelle Stadt auswählen",
    PrestigeGoBack: "bleiben",
    PermanentUpgradeDesc: "Dieses Upgrade bleibt bestehen, wenn Sie in einer neuen Stadt starten",
    ProductionMultiplier: "Produktionsmultiplikator",
    ProductionMultiplierDesc:
        "Steigerung der Produktionskapazität aller Gebäude (einschließlich Minen, Fabriken, Kraftwerke, Wissenschafts- und Kulturgebäude)",
    fuelCostDiscount: "Kraftstoffkostenrabatt",
    fuelCostDiscountDesc: "Gibt einen Rabatt auf die Kraftstoffkosten beim Transport von Ressourcen",
    AutoSellCapacityMultiplier: "Multiplikator für die automatische Verkaufskapazität",
    AutoSellCapacityMultiplierDesc:
        "Ein Multiplikator, der unabhängig von der aktuellen Kapazität auf Ihre automatische Verkaufskapazität angewendet wird",
    BuildingPermitCostDivider: "Kostenteiler für Baugenehmigungen",
    BuildingPermitCostDividerDesc: "Teilen Sie die Baugenehmigungskosten durch diesen Teiler",
    ExtraAdjacentBonus: "Zusätzlicher Benachbarungsbonus",
    ExtraAdjacentBonusDesc: "Zusätzliche Bonuskapazität für jedes benachbarte Arbeitsgebäude des gleichen Typs",
    OfflineEarningMultiplier: "Offline-Verdienstmultiplikator",
    OfflineEarningMultiplierDesc: "Ein Multiplikator, der für Offline-Einnahmen gilt",
    PrestigeAlertTitle: "Bist du sicher?",
    PrestigeAlertContent:
        "Ihr Unternehmen wird aufgelöst. Sie werden %{amount} Schweizer Franken bekommen und eine neue Firma in %{city} gründen",
    PrestigeCurrencyDesc:
        "Dies ist das Geld auf Ihrem geheimen Schweizer Bankkonto. Sie können es mitnehmen, wenn Sie in einer neuen Stadt anfangen",
    Prestige: "Einzahlen",
    Cancel: "Stornieren",
    SaveFileCorrupted: "Sicherung beschädigt",
    CheatDetected:
        "Ihre alte Sicherung hat die Serverüberprüfung nicht bestanden und kann nicht gelesen werden. Sie beginnen mit einer neuen Sicherung",
    LoadGameError: "Spiel konnte nicht geladen werden",
    LoadGameErrorMessage: "Fehlermeldung: %{message}",
    LoadGameErrorDesc:
        "Bitte überprüfe deine Internetverbindung. Wenn das Problem weiterhin besteht, wenden Sie sich an den Support",
    ExpansionPackIncompatible:
        "Sie importieren einen Speicher mit Erweiterungspaketen, aber Ihr Spiel verfügt nicht über die erforderlichen Erweiterungspakete",
    SaveFileMigrated: "Eine neue Ära: Beta ist da",
    SaveFileMigratedDesc:
        "Vielen Dank für das Testen der Alphaphase. Ihre alte Karte ist nicht kompatibel, aber wir haben Ihre Daten migriert und geben Ihnen einen Bonus",
    ClaimSwissMoney: "Erhalte %{amount} Schweizer Franken 💵",
    SaveFileMigratedFinePrint:
        "Ihre Marktwert wird in Schweizer Franken umgerechnet und Ihre nicht ausgegebenen Schweizer Franken werden angerechnet. Sie erhalten 50% Schweizer Bonusfranken für Spieltests in Alpha. Die maximalen Schweizer Franken, die angerechnet werden können, sind auf 200 begrenzt",
    CashIn: "Einzahlen",
    CurrentCity: "Aktuelle Stadt",
    CashInDesc:
        "Sie erhalten diesen Betrag auf Ihr Schweizer Bankkonto, wenn Sie in einer neuen Stadt beginnen. Er basiert auf dem Marktwert Ihres Unternehmens und muss %{amount} erreichen, bevor Sie Schweizer Franken verdienen können",
    MoveToNewMap: "Starte in einer neuen Stadt",
    CityName: "Stadt",
    CitySize: "Kartengröße",
    GridType: "Zellentyp",
    StartInThisCity: "Starte in %{city}",
    CityBonus: "Stadtbonus",
    ResourceTilePercentage: "Ressourcenkacheln",
    MapSquareGrid: "quadratisch",
    MapHexGrid: "hexagon",
    Stockholm: "Stockholm",
    StockholmBonus:
        "<li> kostenlose Windkraftanlage der Stufe 4 x1 </ li> <li> kostenlose Ölquelle der Stufe 4 x1 </ li> <li> kostenlose Ölraffinerie der Stufe 2 x1 </ li> <li> Papierfabriken sind freigeschaltet </ li > <li> Sägewerke haben 2x Ausgabe </ li> ",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li> Stahlwerke haben 2x Kapazität </ li> <li> Edelstahlwerke haben 2x Kapazität </ li> <li> Kostenloser Eisentransport </ li> <li> Stahltransport kostet 50% weniger Kraftstoff </ li> <li> Beginnen Sie mit 2x automatischer Verkaufskapazität </ li> <li> Keine Kachelmodifikatoren </ li> ",
    Oslo: "Oslo",
    OsloBonus:
        "<li> Ölraffinerien haben 2x Kapazität </ li> <li> Gasaufbereitungsanlagen haben 2x Kapazität </ li> <li> Benzinkraftwerke haben 2x Kapazität </ li> <li> Stahlwerke verwenden Erdgas anstelle von Kohle </ li> <li> Kostenloser Öltransport </ li> ",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li> Uranminen haben 2x Leistung </ li> <li> Urananreicherungsanlagen haben 2x Kapazität </ li> <li> Urantransport kostet 50% weniger Treibstoff </ li> <li> Kostenloser Waffentransport </ li> <li> Raketenfabriken verwenden angereichertes Uran anstelle von Titan und Uran </ li> ",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li> Zeppelinfabriken sind freigeschaltet </ li> <li> Halbleiterfabriken haben 2x Produktivität </ li> <li> Werften haben 2x Kapazität </ li> <li> Autofabriken haben 2x Kapazität </ li> <li> Li-Ionen-Akkufabriken sind freigeschaltet </ li> ",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li> Titanminen haben 2x Produktion </ li> <li> Urananreicherungsanlagen haben 2x Produktivität </ li> <li> Düsentriebwerksfabriken haben 2x Kapazität </ li> <li> Flugzeugfabriken haben 2x Produktivität </ li > <li> Raketenfabriken verwenden Uran anstelle von angereichertem Uran </ li> ",
    Rome: "Rom",
    RomeBonus:
        "<li> Kolosseen sind freigeschaltet </ li> <li> Kolosseen haben 2x Produktivität </ li> <li> Beginnen Sie mit dem Policy Center der Stufe 5 </ li> <li> Opernhäuser haben 2x Kapazität </ li> <li> Aufnahmestudios produzieren auch Kultur </ li> ",
    Detroit: "Detroit",
    DetroitBonus:
        "<li> Motorenfabriken sind entsperrt </ li> <li> Motorfabriken haben 2x Produktivität </ li> <li> Autofabriken haben 2x Kapazität </ li> <li> Autofabriken benötigen keine Batterien </ li> <li> Zugfabriken haben 2x Kapazität </ li> ",
    Boston: "Boston",
    BostonBonus:
        "<li> Starte mit Forschungslabor Level 5 </ li> <li> Fachhochschulen sind frei </ li> <li> Fachhochschulen haben 2x Kapazität </ li> <li> Schulen haben 2x Kapazität </ li> <li> Universität haben 2x Produktivität </ li> ",
    FuelType: "Wählen Sie einen Kraftstoff",
    FuelCost: "Kraftstoffkosten",
    FuelConsumption: "%{fuel} Verbrauch",
    FuelEconomy: "Kraftstoffverbrauch",
    FuelProduction: "%{fuel} Produktion",
    FuelInStorage: "%{fuel} im Lager",
    FuelSurplus: "%{fuel} Überschuss",
    NotEnoughFuel: "Nicht genug %{fuel} für diese Operation",
    BuildingNotEnoughFuel: "💡 Nicht genug %{fuel}",
    Top20FuelCost: "Top 20 Treibstoffverbraucher",
    FuelCostNumber: "%{cost} %{fuel}",
    FuelCostSave: "Treibstoffkosten sparen",
    FuelCostSaveDesc:
        "Lagerhäuser sparen im Vergleich zu anderen Gebäuden einen bestimmten Prozentsatz an Treibstoff für den Transport von Ressourcen. Je höher das Level, desto mehr wird gespart",
    CoalPlantFuel: "Kohle Liquidator",
    CoalPlantFuelDesc: "Kohlekraftwerke verwenden zusätzliche Kohle zur Herstellung von Treibstoff",
    FuelRunOutWarning:
        "💡 Ihr Kraftstoffverbrauch übersteigt die Produktion. Wenn der Kraftstoff ausgeht, wird Ihr Transport angehalten",
    FuelCostDiscount: "Treibstoffkostenrabatt",
    FuelCostDiscountDesc: "Gibt einen Rabatt auf die Treibstoffkosten beim Transport von Ressourcen",
    Translator: "Übersetzer",
    TranslatorName: "v1rul3nt, Quiipy",
    Language: "Language",
    ThisLanguage: "Deutsch",
    HideNotProducing: "Ressourcen ausblenden, die nicht produziert werden",
    SortByStorage: "Lager",
    SortByProduction: "Produktion",
    SortByName: "Name",
    BuildingInProgressCannotPrestige:
        "Es laufen noch Bauarbeiten, Sie können nicht in einer neuen Stadt beginnen, bis sie fertig sind",
    PlayerTrade: "Spielerhandel",
    AddTradeFail: "Fehler beim Hinzufügen Ihres Handels",
    AddTradeExceedMaximumTrade:
        "Sie können maximal %{number} aktive Handel haben, bitte fordern Sie zuerst einen ein, oder brechen einen ab.",
    AddTradeSuccess: "Ihr Handel wurde erfolgreich hinzugefügt",
    LoadTradeFail: "Spieler-Handel konnten nicht geladen werden. Bitte versuchen Sie es später erneut",
    ClaimTradeFail: "Wenn Sie diesen Handel nicht beanspruchen konnten, versuchen Sie es später erneut",
    ClaimTradeSuccess: "Ihr Handel wurde angenommen: $%{cash} wurde Ihrem Konto hinzugefügt",
    CancelTradeSuccess: "Ihr Handel wurde erfolgreich abgebrochen",
    CancelTradeFail: "Dieser Handel konnte nicht abgebrochen werden. Bitte versuchen Sie es später erneut",
    AcceptTradeSuccess: "Dieser Handel wurde von Ihnen akzeptiert: %{resource} wurde Ihrem Handelszentrum hinzugefügt",
    AcceptTradeFail: "Dieser Handel wurde nicht akzeptiert. Bitte versuchen Sie es später erneut",
    PlayerTradeBanner: "Handel Ressourcen mit anderen Spielern",
    PlayerTradeResource: "Ressource",
    PlayerTradeAmount: "Menge",
    PlayerTradePrice: "Preis $",
    PlayerTradeValue: "Wert $",
    PlayerTradeWaiting: "Warte...",
    UseTradeCenterPrice: "Verwenden Sie den Handelszentrum-Preis",
    AddTrade: "Handel hinzufügen",
    ActiveTrades: "Aktive Handel",
    AcceptTrade: "akzeptieren",
    CancelTrade: "abbrechen",
    RefundTrade: "erstatten",
    RefundTradeSuccess: "Dieser Handel wurde zurückerstattet: %{resource} wurde an Ihr Handelszentrum zurückerstattet",
    RefundTradeFail: "Dieser Handel konnte nicht zurückerstattet werden. Bitte versuchen Sie es später erneut",
    ClaimTrade: "erhalte",
    RefreshTrade: "Aktualisierung",
    PasteYourSave: "Bitte fügen Sie Ihre gespeicherten Daten ein",
    FailedToImportSave: "Fehler beim Importieren der Sicherung",
    FailedToImportSaveDesc: "Ihre Sicherungsdatei ist nicht kompatibel oder beschädigt: %{error}",
    SaveCopiedToClipboard: "Ihre gespeicherten Daten wurden in Ihre Zwischenablage kopiert",
    CancelActiveTradeFirst: "Sie haben aktive Spieler-Handel, bitte stornieren / beanspruchen Sie diese zuerst",
    FailedToCheckActiveTrade: "Fehler beim überprüfen aktiver Spieler-Handel. Bitte versuchen Sie es später erneut",
    PlayerTradePriceNotValid:
        "Verkaufspreis muss zwischen %{min} und %{max} liegen(2 x Preis der letzten Marktaktualisierung)",
    PlayerTradeQuotaExceed: "Dieser Handel hat Ihre Menge überschritten",
    PlayerTradeAmountNotValid: "Die Handelsmenge muss größer als 0 sein",
    PlayerTradeValidRange: "Entfernung: %{min} ~ %{max}",
    PlayerTradeFilterPrice: "unter dem Marktpreis",
    PlayerTradeFilterCanAfford: "bezahlbar",
    PlayerTradeQuota: "Menge übrig: %{value}",
    WindTurbineDesc:
        "💡 Windkraftanlagen arbeiten nur 8 von 10 Sekunden - Die Stromkreisläufe sind nicht miteinander verbunden",
    PlayerTradeUnavailable:
        "Sie brauchen mindestens eine Ressource in Produktion oder im Lager um mit anderen Spielern zu handeln",
    PlayerTradeToClaim: "Sie haben %{num} neue Handel zum abholen im Spielerhandel",
    PowerBank: "Stromspeicher",
    PowerBankBuildDesc: "Speichern Sie überschüssigen Strom und sorgen Sie für Stromversorgung bei Engpässen",
    PowerBankChargeSpeed: "Ladegeschwindigkeit",
    PowerBankPowerLeft: "Strom übrig",
    PowerBankMoreCapacity: "Batteriesparmodus",
    PowerBankMoreCapacityDesc: "Stromspeicher laden mit 50% Geschwindigkeit auf, haben aber 50% mehr Kapazität",
    PowerBankNotWorking: "⛔ Stromspeicher arbeiten nur neben einem Kraftwerk",
    ExcludeBuildingsShutdown: "Schließen Sie stillgelegte Gebäude aus",
    ColorTheme: "Spielfarbthema",
    ColorThemeDesc: "Farbthema für Spielesymbole, Hervorhebung, Gitter und Hintergrund. ERFORDERT EINEN NEUSTART",
    WarehouseBuildDesc: "Transportieren und lagern Sie alle Ressourcen mit geringeren Kraftstoffkosten",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Siliziumminem produzieren 2x Silizuium, aber benötigen 50% mehr Strom und die Transportkosten für Silizium sind 50% höher.",
    CoalMine2xOutput: "Industrielle Revolution",
    CoalMine2xOutputDesc:
        "Kohleminen produzieren 2x soviel Kohle, aber benötigen 50% mehr Strom und die Transportkosten für Kohle sind um 50% erhöht.",
    AlMine2xOutput: "Aluminumschmelze",
    AlMine2xOutputDesc: "Aluminumminem produzieren 2x soviel Aluminium und verbrauchen 2x soviel Strom.",
    LoggingCamp2xOutput: "Abholzung",
    LoggingCamp2xOutputDesc: "Forstbetriebe produzieren 2x soviel Holz und die Transportkosten werden verdoppelt.",
    HideResourceMovement: "Ressourcembewegungen ausblenden",
    HideResourceMovementDesc:
        "Die Ressourcenbewegungen werden standartmäßig ausgeblendet (die kleinen Punkte) und nur angezeigt wenn ein Gebäude angewählt ist.",
    PowerBankLeft: "Energiespeicher",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Cancel This Trade?",
    CancelTradeConfirmDialogDesc:
        "Cancelling this trade will refund %{percent} of the resource to the Trade Center warehouse",
    CancelTradeConfirmDialogYes: "Yes",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Add Route",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Find on Map",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consumption",
};
