export const DE = {
    Translator: "Übersetzer",
    TranslatorName: "v1rul3nt, Quiipy",
    Language: "Sprache",
    ThisLanguage: "Deutsch",
    OK: "OK",
    SteelMill: "Stahlwerk",
    StainlessSteelPlant: "Edelstahlfabrik",
    CircuitFoundry: "Schaltkreis Fabrik",
    IntegratedCircuit: "integrierte Schaltung",
    OilWell: "Ölplattform",
    Wood: "Holz",
    LoggingCamp: "Forstbetrieb",
    LumberMill: "Sägewerk",
    Lumber: "Nutzholz",
    Paper: "Papier",
    PaperMill: "Papierfabrik",
    Book: "Buch",
    BookPublisher: "Buchverlag",
    OilRefinery: "Öl Raffinerie",
    Sell: "Verkaufen",
    Upgrade: "Upgrade",
    Build: "Bauen",
    Inspect: "untersuchen",
    Buildings: "Gebäude",
    Iron: "Eisen",
    Actions: "Aktionen",
    FuelType: "Wählen Sie einen Kraftstoff",
    FuelCost: "Kraftstoffkosten",
    FuelConsumption: "%{fuel} Verbrauch",
    FuelEconomy: "Kraftstoffverbrauch",
    FuelProduction: "%{fuel} Produktion",
    FuelInStorage: "%{fuel} im Lager",
    Plastic: "Kunststoff",
    FuelSurplus: "%{fuel} Überschuss",
    Petrol: "Benzin",
    Buy: "Kaufen",
    NoLiquidity: "Zahlungsunfähig",
    NoLiquidityTurnOffAutoSell:
        "Es gibt nicht genügend Nachfrage für %{res}, der automatische Verkauf wurde abgestellt.",
    Multiplier: "Multiplikator",
    MultiplierDesc: "Alle 10, erhältst du +1 Multiplikator",
    SellBuilding: "Gebäude verkaufen",
    PowerGrid: "Stromversorgung",
    TradeAmount: "Handelsmenge",
    SortBy: "sortieren nach",
    SortByPrice: "Wert",
    SortByAmount: "Menge",
    NotEnoughResourcesForTrade: "Unzureichende Ressourcen im Handelszentrum um den Handel durchzuführen.",
    NotEnoughResources: "Unzureichende Ressourcen für diese Aktion",
    Transportation: "Transport",
    Cash: "Geld",
    Aluminum: "Aluminium",
    ResearchPoint: "Forschungspunkte",
    Unlock: "freischalten",
    BuildingUnlocked: "%{building} wurde freigeschalten",
    Science: "Wissenschaftspunkte",
    ScienceFromPowerDesc: "Stormerzeuger produzieren eine kleine Menege Wissenschaftspunkte, falls sie Strom erzeugen",
    Culture: "Kultur",
    School: "Schule",
    University: "Universität",
    Polytechnic: "Fachhochschule",
    Colosseum: "Kolosseum",
    WindTurbine: "Windkraftanlage",
    Engine: "Motor",
    EngineFactory: "Motorenfabrik",
    CameraFactory: "Kamerafabrik",
    Camera: "Kamera",
    Gun: "Waffe",
    GunFactory: "Waffenfabrik",
    Aircraft: "Flugzeug",
    AircraftFactory: "Flugzeugfabrik",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Zeppelinfabrik",
    Tank: "Panzer",
    TankFactory: "Panzerwerk",
    CoalPowerPlant: "Kohlekraftwerk",
    PetrolPowerPlant: "Ölkraftwerk",
    Copper: "Kupfer",
    Gas: "Erdgas",
    GasPump: "Erdgasförderung",
    GasPowerPlant: "Gaskraftwerk",
    Missile: "Fernlenkgeschoss",
    MissileFactory: "Fernlenkgeschossfabrik",
    Rocket: "Rakete",
    RocketFactory: "Raketenfabrik",
    BuildingPermit: "Baugenehmigung",
    BuildingPermitDesc:
        "Du hast die Baugenehmigung für %{amount} Gebäude, du hast bereits  %{amountBuilt} gebaut und hast %{amountLeft} übrig",
    BuildingLocked: "Das Gebäude ist noch nicht verfügbar, du musst es zuerst im Forschungslabor freischalten",
    BuildQueue: "Bau Warteschlange",
    BuildQueueDesc: "Anzahl der Gebäude in der Warteschleife",
    MaxBuilders: "Max Baumeister",
    MaxBuildersDesc: "Anzahl der Gebäude die du gleichzeitig bauen kannst",
    Silicon: "Silizium",
    AluminumMine: "Aluminiummine",
    CopperMine: "Kupfermine",
    SiliconMine: "Siliziummine",
    IronMine: "Eisenmine",
    CoalMine: "Kohlemine",
    Headquarter: "Hauptquartier",
    ResearchLab: "Forschungslabor",
    TradeCenter: "Handelszentrum",
    Resources: "Ressoursen",
    NotEnoughPower: "💡 Nicht genug Energie, erwäge die Erhöhung der Energieproduktion",
    NotEnoughFuel: "Nicht genug %{fuel} für diese Operation",
    NotEnoughCash: "Nicht genug Geld für diese Aktion",
    NotEnoughSwissMoney: "Nicht genug Schweizer Franken für diese Aktion",
    BuildingNotEnoughFuel: "💡 Nicht genug %{fuel}",
    AutoSell: "Auto verkaufen",
    SellAll: "verkaufe ALLES",
    Change: "ändern",
    StatisticsBureau: "Statistik Agentur",
    LogisticsDepartment: "Logistik Institut",
    From: "Von",
    Top20FuelCost: "Top 20 Kraftstoffverbraucher",
    To: "Zu",
    TransportTime: "Transportdauer",
    TopN: "Top %{n}",
    Warehouse: "Lagerhaus",
    TradeWarehouse: "Handelslager",
    Coal: "Kohle",
    Video: "Video",
    ClothingFactory: "Kleidungsfabrik",
    Clothes: "Kleidung",
    Fashion: "Mode",
    FashionFactory: "Modedesigner",
    VideoFarm: "Videofabrik",
    SantaFactory: "Santafabrik",
    Santa: "Santa",
    Car: "Auto",
    CarFactory: "Autofabrik",
    Ship: "Schiff",
    SolarPanel: "Solarmodul",
    SolarPanelDesc: "💡 Solarmodule arbeiten nur 5 von 10 Sekunden - alle Kreisläufe sind verbunden",
    WindTurbineDesc:
        "💡 Windkraftanlagen arbeiten nur 8 von 10 Sekunden - Die Stromkreisläufe sind nicht miteinander verbunden",
    Movie: "Film",
    MovieStudio: "Filmstudio",
    Sitcom: "Sitcom",
    TVStudio: "TV Studio",
    PC: "PC",
    GameStudio: "Game Studio",
    Game: "Game",
    ComputerFactory: "Computerfabrik",
    Shipyard: "Werft",
    PowerUsage: "Energieverbrauch",
    PowerSupply: "Energieerzeugung",
    PowerSurplus: "Energieüberschuss",
    Level: "Stufe",
    Power: "Energie",
    CentralBank: "Zentralbank",
    ResourceInput: "Eingang",
    ResourceOutput: "Ausgang",
    ResourceStorage: "Lager",
    ResourceChange: "Wechsel",
    ResourceInOutDesc: "💡 Klicke auf Aus-Ein Tap on Out-In Zahl unterhalb um die Entsprechenden Gebäude zu markieren",
    ResourceChart: "Ressourcentabelle",
    MarketUpdateIn: "Marktpreisupdate in %{time}",
    Income: "Einkommen",
    Semiconductor: "Halbleiter",
    SemiconductorFactory: "Halbleiterfabrik",
    Steel: "Stahl",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Farm",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Farm",
    Guitar: "Gitarre",
    GuitarFactory: "Gitarrenfabrik",
    Drum: "Schlagzeug",
    DrumFactory: "Schlagzeugfabrik",
    RecordingStudio: "Tonstudio",
    OperaHouse: "Opernhaus",
    CoalGasificationPlant: "Kohlevergasungsanlage",
    GasProcessingPlant: "Gasveredelungsanlage",
    Music: "Musik",
    Glass: "Glas",
    PhoneFactory: "Handyfabrik",
    Phone: "Handy",
    GlassFactory: "Glasmanufaktur",
    Oil: "Öl",
    Chromium: "Chrom",
    ChromiumMine: "Chrommine",
    Uranium: "Uran",
    EnrichedUranium: "angereichertes Uran",
    NuclearPowerPlant: "Kernkraftwerk",
    UraniumEnrichmentPlant: "Urananreicherungsanlage",
    UraniumMine: "Uranmine",
    Titanium: "Titan",
    TitaniumMine: "Titanmine",
    TitaniumAlloyPlant: "Titanmanufaktur",
    ChromiumAlloyPlant: "Chrommanufaktur",
    Input: "Eintrag",
    PanelPosition: "Paneel Position",
    PanelPositionDesc:
        "Anzeige des Seitenpaneels links, rechts oder automatisch (entsprechend des aktuell ausgewählten Feldes)",
    InputCapacity: "benötigte Materialien",
    InputCapacityPerCycle: "benötigte Materialien / Zyklus",
    Output: "Produktion",
    OutputCapacity: "produzierte Materialien",
    OutputCapacityPerCycle: "produzierte Materialien / Zyklus",
    ResourceDeposit: "Ressourcen Absatz",
    RecommendedBuilding: "💡 Dieses Feld hat %{resource} Austrag",
    AdjacentBonus: "Angrenzungsbonus",
    AdjacentBonusDesc:
        "Du erhältst %{bonus}% zusätzliche Kapazität für jedes angrenzende arbeitende Gebäude der selben Art",
    ConsiderIncreaseProduction: "💡 Versuche %{resource} Produktionserhöhrung",
    AlwaysTransportInput: "Vorratsmodus",
    AlwaysTransportInputTradeCenter: "Immer exportieren",
    AlwaysTransportInputTradeCenterDesc:
        "Transportiere Ressourcen immer zum Marktplatz, auch wenn der automatische Verkauf für die Ressource nicht aktiviert ist",
    AlwaysTransportInputDesc: "Transportiere benötigte Ware immer, auch wenn es mehr ist als benötigt",
    ProductionCycleLength: "Produktionszyklus",
    ProductionCycleLengthDesc:
        "Dauer eines Produktionszyklus in Sekunden. Eine Verlängerung des Zyklus erhöht entsprechend die benötigen und hergestellten Waren",
    MaxInputDistance: "Max. Importentfernung",
    MaxInputDistanceDesc:
        "Die maximale Distanz des Gebäudes woher Rohstoffe bezogen werden, gemessen in Zellenanzahlen",
    AutoSellCapacity: "automatsiche Verkaufsmenge",
    AutoSellCapacityDesc: "Maximale Anzahl an Ressourcen die automatisch verkauf werden können pro Sekunde/Ressource",
    CurrentAutoSellCapacityMultiplier: "Aktueller Multiplikator: x%{n}",
    AutoSellConcurrency: "automatische Verkaufsanzahl",
    AutoSellConcurrencyDesc: "Maximale Anzahl der Ressourcen die gleichzeit automatisch verkauft werden können",
    MaxAutoSellConcurrencyReached:
        "Du hast die maximale automatische Verkaufsanzahl erreicht, schalte eine andere ab um diese zu aktivieren",
    CannotSellBuilding: "Du kannst diese Gebäude zurzeit nicht verkaufen",
    WallStreet: "Wall Street",
    MarketCap: "Marktkapitalisierung",
    MarketCapDesc: "Gesamtkapital (i.e. Marktwert) deiner Organisation",
    BuildingValuation: "Gebäudewert",
    BuildingValuationDesc: "Gesamtwert deiner Gebäude, inklusive Baugenehmigungen und Aufwertungen",
    ResourcesValuation: "Ressourcenwert",
    ResourcesValuationDesc: "Gesamtwert der Ressourcen im Inventar",
    Battery: "Batterie",
    BatteryFactory: "Batteriefabrik",
    RatingBuy: "Kaufen",
    RatingSell: "Verkaufen",
    SwissShop: "Schweizer Bank",
    RatingHold: "Durchschnittlich",
    RatingOutperform: "Überdurchschnittlich",
    RatingUnderperform: "Unterdurchschnittlich",
    StockRating: "Unternehmensbewertung",
    JetEngine: "Düsentriebwerk",
    Helicopter: "Helikopter",
    Lithium: "Lithium",
    LithiumMine: "Lithiummine",
    LiionBatteryFactory: "Li-ion Batteriefabrik",
    HelicopterFactory: "Helikopterfabrik",
    Satellite: "Satellit",
    ToyFactory: "Spielzeugfabrik",
    Toy: "Spielzeug",
    SpaceStation: "Weltraumstation",
    SpaceStationFactory: "Weltraumstationsfabrik",
    OperatingSystem: "Betriebssystem",
    OperatingSystemCompany: "Betriebssystemhersteller",
    LinuxDistribution: "Linux Vertrieb",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Konsole",
    ConsoleFactory: "Konsolenfabrik",
    Train: "Zug",
    TrainFactory: "Zugfabrik",
    ShoeFactory: "Schuhfabrik",
    Shoes: "Schuhe",
    ArtilleryFactory: "Artilleriefabrik",
    Artillery: "Artillerie",
    SubmarineFactory: "U-Boot Fabrik",
    Submarine: "U-Boot",
    Spaceship: "Raumschiff",
    RobotFactory: "Roboterfabik",
    Robot: "Roboter",
    SpaceshipFactory: "Raumschifffabrik",
    SatelliteFactory: "Satellitenfabrik",
    JetEngineFactory: "Düsentriebwerksfabrik",
    StockRatingDesc:
        "Die Aktienwertung beruht auf Wall Street Auswertungen, wirkt sich auf deine Marktobergrenze aus und aktualisiert sich zusammen mit dem Handel",
    InterestRate: "Übernacht Anteil",
    InterestRateDesc: "Diesen Anteil erwirtschaftest du auf dem Markt während du Offline bist",
    OfflineEarning: "Offline Einkommen",
    OfflineEarningDesc: "Offline Einkommen ist abhängig von der Marktobergrenze und der Zinsrate",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline Erwerbszeit",
    OfflineEarningTimeDesc: "Du erhältst Offline Einkommen bis zu diesem Schwellenwert",
    BuyPermit: "Kauferlaubis",
    NotEnoughBuildingPermit: "Nicht genug Baugenehmigungen. Bitte kaufen Sie mehr, um neue Gebäude zu bauen",
    MovingAverage: "Gleitender Durchschnitt",
    MovingAverageDesc: "Zeigen Sie den gleitenden Durchschnitt der Ressourcenänderung anstelle der Echtzeitänderung an",
    AllowZoom: "Zoomen",
    AllowZoomDesc:
        "Aktivieren Sie die Zoomunterstützung. Verwenden Sie Ihr Mausrad zum Zoomen. Aktueller Zoom ist %{zoom}",
    AllowZoomMobileDesc:
        "Aktivieren Sie die Zoomunterstützung. Sie können zum Zoomen kneifen. Aktueller Zoom ist %{zoom}",
    Settings: "Einstellungen",
    Sound: "Sound-Effekt",
    SoundDesc: "Aktivieren Sie Soundeffekte wie Klick- oder Fehlersound",
    AutoHighlight: "Automatische Markierung",
    AutoHighlightDesc: "Markieren Sie automatisch Gebäude desselben Typs, wenn Sie ein Gebäude auswählen",
    MusicDesc: "Musik einschalten: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Symbole",
    MisplacedBuilding: "⛔ Das %{building} wird nicht auf die richtige Ressource gelegt",
    Left: "Links",
    Right: "Rechts",
    Auto: "Auto",
    HighlightBuildings: "Gebäude hervorheben",
    HighlightTurnedOff: "... sind abgeschaltet",
    HighlightStockpileModeOn: "...die den Lagermodus aktiviert haben",
    HighlightProductionCycleNotDefault: "...diese haben Produktionszyklus > 1",
    HighlightMaxInputDistanceNotDefault: "...haben die maximale Eingangsentfernung < ∞",
    HighlightNotMakingProfit: "...machen keinen Gewinn",
    NBuildingsAreHighlighted: "%{n} Gebäude sind hervorgehoben",
    OnlyToWarehouse: "Nur für Lager",
    OnlyToWarehouseDesc: "Nur Lager können Ressourcen von diesem Gebäude transportieren",
    TurnOffProduction: "Stilllegen",
    TurnOffProductionDesc:
        "Schalten Sie die Produktion des Gebäudes aus. Das Gebäude wird keine Ressourcen mehr transportieren und keinen Strom verbrauchen",
    ApplyToAll: "Auf alle anwenden %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "unbegrenzt",
    Transport: "transport",
    TileModifier: "Zellen-Modifikator",
    ShowAllModifiers: "Alle Modifikatoren anzeigen",
    HideAllModifiers: "Alle Modifikatoren ausblenden",
    NumberOfBuildings: "Anzahl der Gebäude, die Sie haben",
    ShowContent: "Inhalt zeigen",
    HideContent: "Inhalt ausblenden",
    BuyExpansionPack: "Kaufen für %{price}",
    Cities: "Städte",
    InputStrategy: "Eingangsstrategie",
    InputStrategyClose: "Näher",
    InputStrategyCloseDesc: "Bevorzugen Sie das nächstgelegene Lager mit genügend Ressourcen",
    InputStrategyFar: "Weiter",
    InputStrategyFarDesc: "Bevorzugen Sie das am weitesten entfernte Lager mit genügend Ressourcen",
    InputStrategyAmount: "Menge",
    InputStrategyAmountDesc:
        "Bevorzugen Sie das Lager mit der größten Menge an Ressourcen, unabhängig von der Entfernung",
    FuelCostSave: "Kraftstoffkosten sparen",
    FuelCostSaveDesc:
        "Lagerhäuser sparen im Vergleich zu anderen Gebäuden einen bestimmten Prozentsatz an Kraftstoff für den Transport von Ressourcen. Je höher das Level, desto mehr wird gespart",
    SoftwareCompany: "Softwareunternehmen",
    Software: "Software",
    ScreenFactory: "Bildschirmfabrik",
    Screen: "Bildschirm",
    JoinDiscord: "Besuchen Sie unseren Discord-Server, um die neuesten Updates, Tipps und Diskussionen zu erhalten",
    ClaimOfflineEarning: "Offline-Einnahmen abholen",
    OfflineTime: "Offline Zeit",
    Minutes: "%{time}min",
    MaxUpgrade: "Maximales Upgrade",
    MaxUpgradeDesc: "Sie haben das maximale Upgrade erreicht",
    ClaimAmount: "Geld +%{amount}",
    EarningPerMinute: "Verdienstquote",
    EffectiveTime: "Effektive Zeit",
    EffectiveTimeDesc: "Ihre effektive Offline-Verdienstzeit ist begrenzt %{time}min.",
    BuildSearchPlaceholder: "Geben Sie Gebäude oder Ressource für die Suche ein",
    MineOverlayWarning: "%{building} wird vom Zellenmodifikator nicht beeinflusst",
    WholesaleCenter: "Großhandelszentrum",
    OrderFrom: "Bestellung von %{name}",
    ExpireIn: "läuft aus in",
    TurnOnAllProductions: "Produktion An",
    TurnOnAllProductionsDesc:
        "Produktionen aller Gebäude einschalten, kann nicht verwendet werden, wenn die Kostensparrichtlinie aktiv ist",
    OperationSuccessful: "Der Vorgang wurde erfolgreich abgeschlossen",
    TurnOn: "Einschalten",
    Reward: "Belohnung",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/Zyklus",
    PolicyPoint: "Richtlinienpunkte",
    PolicyPointPerMinute: "Herstellungsrate",
    PolicyPointPerMinuteDesc: "Sie erhalten jede Minute im Spiel Richtlinienpunkte",
    YourWilLGaimPolicyPoints: "Du erhältst %{amount} Richtlinienpunkte in %{time}s",
    PolicyPointDesc: "💡 Je mehr Richtlinien aktiv sind, desto höher sind die Kosten für jede Richtlinie",
    NextOrderIn: "Nächste Bestellung in",
    FillOrder: "Auftrag erfüllen",
    RejectOrder: "Ablehnen",
    WholesaleCenterLocked:
        "Du brauchst mindestens %{required} verschiedene Ressourcen zum Freischalten des Großhandelszentrums. Du hast nur %{current} der benötigten Ressourcen",
    OrderFilled: "Die Bestellung von %{from} wurde erfolgreich ausgeliefert!",
    PolicyCenter: "Bundestag",
    NewOrder: "Eine neue Bestellung von %{from} ist angekommen, nachzusehen im  Großhandelszentrum",
    Policies: "Richtlinien",
    PolicyNotEnoughTime: "Sie haben nicht genügend Richtlinienpunkte für diese Richtlinie",
    TimeLeft: "%{time} übrig",
    WholesaleCenterOrderFaster: "Weltausstellung",
    WholesaleCenterOrderFasterDesc:
        "Das Großhandelszentrum erhält Bestellungen 2x schneller und die Bestellgröße ist 2x größer",
    PolicyOilWellPowerx2: "Verdopple Ölquelle",
    PolicyOilWellPowerx2Desc: "Ölquellen produzieren 2x Öl und 2x verbrauchen Strom",
    HalfTransportSpeed: "Verlangsamen, um zu sparen",
    HalfTransportSpeedDesc:
        "Die Transportgeschwindigkeit wird um 25% verlangsamt und die Kraftstoffkosten um 25% gesenkt.",
    RefineryMoreOil: "Mehr Kraftstoff Mehr Probleme",
    RefineryMoreOilDesc: "Ölraffinerien produzieren 50% mehr Benzin und 50% weniger Kunststoff",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Gebäude bevorzugen den Transport aus der vorherigen Quelle(n), anstatt in jedem Zyklus nach der besten Quelle zu suchen (KOSTENLOSE RICHTLINIE)",
    RefineryMorePlastic: "Mehr Plastic Mehr Probleme",
    RefineryMorePlasticDesc: "Ölraffinerien produzieren 50% weniger Benzin und 50% mehr Kunststoff",
    FreeOilTransportDesc: "Der Öltransport kostet keinen Kraftstoff, aber Ölquellen verbrauchen 2x Strom",
    SuperSteelMill: "Herzen aus Eisen",
    SuperSteelMillDesc: "Stahlwerke verbrauchen 50% weniger Kohle, aber 25% mehr Eisen und Strom",
    AlSemiconductor: "Al Schaltkreis",
    AlSemiconductorDesc: "Schaltungsgießereien verwenden Aluminium anstelle von Kupfer",
    CostSaver: "Kostenersparnis",
    CostSaverDesc: "Wenn der Eintrag eines Gebäudes mehr kostet als der Austrag, stellen Sie die Produktion ein",
    CostSaverBuildingDesc:
        "Die Kostensparrichtlinie ist aktiv. Die Produktion wird basierend auf ihrer Rentabilität automatisch ein- und ausgeschaltet",
    CostSaverBuildingWarning:
        "Die Kosteneinsparungsrichtlinie ist aktiv. Sie können die Produktion nicht manuell ändern",
    GlassUseCoal: "Schwarzes Glas",
    GlassUseCoalDesc: "Glasfabriken verbrauchen 50% mehr Kohle und 50% weniger Silizium",
    AdjacentBonusOnlyOutput: "Angrenzender Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Der Angrenzendungsbonus erfordert nicht mehr Eintrag, verbraucht aber mehr Strom und ist nur zu 50% effektiv",
    IronMine2xOutput: "Schwermetall",
    IronMine2xOutputDesc: "Eisenminen produzieren 2x Eisen, aber der Eisentransport kostet 2x Kraftstoff",
    SolarPanelAlwaysWork: "Die Sonne geht nie unter",
    SolarPanelAlwaysWorkDesc: "Solarzellen arbeiten 100% der Zeit, produzieren aber 60% weniger Strom",
    SteelScience: "Wissen durch Stahl",
    SteelScienceDesc: "Stahlwerke verbrauchen 2x Ressourcen und produzieren zusätzlich Wissenschaftspunkte",
    WholesaleCenterProducingOnly: "Großhandelspartner",
    WholesaleCenterProducingOnlyDesc:
        "Großhandelszentrum-Bestellungen enthalten nur Ressourcen, deren Fabriken Sie gebaut haben (Sie müssen auch die Anzahl der erforderlichen Ressourcen produzieren, um das Großhandelszentrum freizuschalten).",
    ShoppingSpree: "Einkaufsbummel",
    ShoppingSpreeDesc:
        "Wenn die Prdouktion einer Ressource nicht ausreicht, kaufen Sie den Mangelbetrag automatisch am Marktplatz (wenn die Ressource automatisch weiterverkauft wird, wird Sie ignoriert).",
    ShoppingSpreeTradeCenterDesc:
        "💡 Wenn die Einkaufsbummel Richtlinie aktiviert ist, kauft der Marktplatz automatisch Ressourcen, die knapp sind",
    ExtraPolicyPoints: "Politischer Lobbyist",
    ExtraPolicyPointsDesc: "Erhöhen Sie die Produktionsmenge für Richtlinienpunkte um 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromlegierungsanlagen verwenden kein Lithium, sondern 2x Eisen",
    DoubleTileModifier: "Die Kraft der Natur",
    DoubleTileModifierDesc: "Der Effekt des Modifikators aller Zellen x2 - sowohl positiv als auch negativ",
    TileModifierOutputOnly: "Zellenmodifikator Plus",
    TileModifierOutputOnlyDesc:
        "Zellenmodifikatoren wirken sich nur auf die Produktion anstatt die benötigten Ressourcen und Produktion aus, sind jedoch nur zu 50% wirksam",
    GasPlantPetrol: "Gasliquidator",
    GasPlantPetrolDesc: "Gaskraftwerke verwenden zusätzliches Gas zur Herstellung von Benzin",
    BuildingRecycle: "Gebäuderecycling",
    BuildingRecycleDesc:
        "Erhalten Sie die volle Rückerstattung, wenn Sie ein Gebäude innerhalb von 1 Minute nach dem Bau verkaufen",
    CoalPlantFuel: "Kohle Liquidator",
    CoalPlantFuelDesc: "Kohlekraftwerke verwenden zusätzliche Kohle zur Herstellung von Kraftstoff",
    Welcome: "Willkommen",
    SeeTutorialAgain: "Tutorial wiederholen",
    HelpTranslateTheGame: "Hilf das Spiel zu übersetzen",
    SkipTutorial: "Tutorial überspringen",
    NextTutorial: "weiter",
    Tutorial1:
        "Industry Idle ist ein <em> Ressourcenmanagement </em> -Spiel, in dem Sie Fabriken bauen🏭, Waren produzieren📦 und Geld verdienen💸.<br><br>Lassen Sie uns einige grundlegende Konzepte durchgehen, um Ihnen den Einstieg zu erleichtern - es dauert nicht lange verspreche ich.",
    Tutorial2:
        "Alle Gebäude benötigen Strom⚡, du hast ein <em>Windrad</em> welches Strom erzeugt. Du kannst deine aktuelle Netzversorgung auf der linken Seite der oberen Leiste sehen.<br><br> Möglicherweise haben Sie bemerkt, dass Windkraftanlagen nur <em>80%</em> der Zeit arbeiten. Du kannst auch andere Kraftwerkstypen bauen, die dauerhaft Strom erzeugen.",
    Tutorial3:
        "Sie haben viele <em> Ressourcenablagerungen </em> auf der Karte. Um Ressourcen zu gewinnen, müssen Sie Minen <em> auf </em> der entsprechenden Lagerstätte errichten. <br> <br> Zum Beispiel haben Sie eine <em> Ölquelle🛢️ </em>, die <em extrahiert > Öl </em> aus einem Ölvorkommen. <br><br>  Ressourcenvorkommen sind unbegrenzt - Sie müssen sich keine Sorgen machen, dass sie aufgebraucht sind. Abgesehen von Minen können andere Gebäude auf jeder leeren Fliese gebaut werden.",
    Tutorial5:
        "Um Geld zu verdienen, müssen Sie Ihre Ressourcen über das Handelszentrum verkaufen. Aktivieren Sie dazu einfach <em> Automatischen Verkauf </em> für diese Ressource. <br><br>  Sie können Ressourcen auch auf dem Marktplatz kaufen. Denken Sie daran, <em> wenn Sie eine Ressource kaufen, erhöhen Sie den Preis </em> und wenn Sie eine Ressource verkaufen, senken Sie den Preis. <br> <br> Der Markt ist <em> unbeständig </ em > und der Preis 📈 ändert sich regelmäßig.",
    Tutorial6:
        "Um neue Gebäude zu bauen, müssen Sie diese zuerst im <em> Forschungslabor🧪 </em> freischalten. Das Forschungslabor wandelt auch Wissenschaft in Forschungspunkte um. <br> <br> Ihre Windkraftanlage (und andere Kraftwerke) produziert beim Betrieb eine kleine Menge Wissenschaft. Und Sie können eine Schule und andere spezielle Gebäude bauen, um die Wissenschaft später anzukurbeln. <br> <br> Jetzt haben Sie alle Grundlagen gelernt und beginnen, Ihre Wirtschaft aufzubauen! Hier sind einige <em> Geld💸 </em> und <em> Benzin </em>, um Ihnen einen Starthilfe zu geben.",
    WelcomePlay: "Spielen",
    WelcomePlayMuted: "Spiel (🔇Musik)",
    Changelog: "Neuerungen",
    ChangelogGotIt: "Verstanden",
    Chat: "Chat",
    Send: "Senden",
    Import: "Import",
    Export: "Export",
    LastBackupAt: "Letze Sicherung",
    RestoreFromBackup: "Sicherung wiederherstellen",
    RestoreFromBackupFail:
        "Wiederherstellung aus der Steam Cloud fehlgeschalgen: sind Sie sicher das dort seine Sicherung existiert?",
    RestoreFromBackupTitle: "Bist du sicher?",
    RestoreFromBackupDesc:
        "Normalerweise müssen Sie keine Wiederherstellung aus der Cloud-Sicherung durchführen, es sei denn, Ihre lokale Speicherung geht verloren. Cloud-Backups sind etwas älter als Ihre lokale Sicherung",
    ChatMessages: "Chat Nachrichten",
    ChangeName: "Ändern",
    SaveName: "Speichern",
    NameValidationRule: "Ihr Name sollte nur Buchstaben und Zahlen enthalten und zwischen 5 und 15 Zeichen liegen",
    NameValidationRuleProfanity: "Ihr Name sollte keine Obszönitäten enthalten",
    ChatMessageRateLimit: "Sie können nur alle 10 Sekunden eine neue Chat-Nachricht senden",
    NameSaved: "Ihr Name wurde erfolgreich geändert",
    NoMessages: "Keine neue Nachrichten",
    Leaderboard: "Bestenliste",
    Name: "Name",
    Rank: "Rang",
    Tips1: "Aktienbewertungen haben 5 Kriterien: Kaufen, Überperformance, Halten, Underperformance und Verkaufen",
    Tips2: "Gebäude stellen den Transport von Ressourcen ein, wenn bereits genug für die Produktion vorhanden ist, es sei denn, Sie aktivieren den Stapelmodus",
    Tips3: "Die Kraftstoffkosten für den Ressourcentransport werden durch die Entfernung und die Menge der Ressourcen bestimmt",
    Tips4: "Gebäude transportieren eine Ressource nur, wenn die auf der Karte gefundene Menge die Eingabekapazität überschreitet",
    Tips5: "Gebäude transportieren eine Ressource nur vom Großhandelszentrum, wenn der automatische Verkauf für diese Ressource deaktiviert ist",
    Tips6: "Sie können die Kraftstoffkosten für eine Ressource im entsprechenden Abschnitt zur Eingabekapazität anzeigen",
    Tips7: "Wenn Sie eine Ressource kaufen, erhöhen Sie den Preis. Wenn Sie eine Ressource verkaufen, senken Sie den Preis",
    Tips8: "Sie können das Diagramm für die Menge jeder Ressource und ihre zeitliche Änderung im Statistikbüro anzeigen",
    Tips9: "Die für ein Gebäude benötigten Forschungspunkte werden durch den Marktpreis seiner Inputressourcen bestimmt",
    Tips10: "Unterschiedliche Ressourcen werden auf dem Markt unterschiedlich bewertet - seien Sie immer auf Marktvschwankungen vorbereitet",
    Tips11: "Es ist eine gute Idee, immer Ihre Strom- und Kraftstoffversorgung zu überprüfen, bevor Sie Ihre Produktion erweitern",
    FPS30: "Energiesparmodus",
    OfflineModeDesc:
        "Es kann keine Verbindung zum Server hergestellt werden: Es werden keine Offline-Einnahmen generiert. Bitte überprüfe deine Internetverbindung",
    OptOut: "Optischer Ausgang",
    OptIn: "Zurücksetzen und aktivieren",
    LeaderboardOptOut: "Leaderboard-Deaktivierung",
    LeaderboardOptOutDesc:
        "Dadurch wird keine Ranglisten-Punktzahl mehr gesendet. BITTE BEACHTEN SIE: Wenn Sie die Bestenliste später aktivieren möchten, müssen Ihre Daten zurückgesetzt werden",
    LeaderboardOptIn: "Bestenliste zurücksetzen und aktivieren",
    LeaderboardOptInDesc:
        "Ihre Daten müssen zurückgesetzt werden, beFvor Sie die Bestenliste wieder aktivieren können. Sind Sie sicher?",
    RewardAdsFailed: "Das Belohnungsvideo wurde nicht abgeschlossen",
    RewardAdsNotAvailable: "Belohnungsvideo ist nicht verfügbar (derzeit wird nur iOS / Android unterstützt)",
    OfflineEarningDoubleSuccess: "Sie haben Ihr Offline-Einkommen verdoppelt",
    FPS30Desc:
        "Wenn Sie den Energiesparmodus aktivieren, wird das Spiel mit 30 FPS anstelle von 60 FPS ausgeführt. Dadurch hält Ihr Akku länger",
    HighlightAll: '"%{type}"markieren',
    HighlightInput: "🔍 %{type} Verbraucher hervorheben",
    HighlightOutput: "🔍 %{type} Erzeuger hervorheben",
    TotalInput: "Gesamteingabekapazität",
    TotalOutput: "Gesamtausgabekapazität",
    RunOutIn: "Leer in %{time}",
    FuelRunOutWarning:
        "💡 Ihr Kraftstoffverbrauch übersteigt die Produktion. Wenn der Kraftstoff ausgeht, wird Ihr Transport angehalten",
    InAmount: "Ein: %{number}",
    OutAmount: "Aus: %{number}",
    SwissBank: "Schweizer Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Wenn Sie in einer neuen Stadt beginnen, erhalten Sie %{money} 💵",
    RestorePurchases: "Einkäufe wiederherstellen",
    RestorePurchasesSuccess: "Ihre Einkäufe wurden wiederhergestellt",
    RestorePurchasesFailed: "Ihre Einkäufe wurden nicht wiederhergestellt",
    ExpansionPacks: "Erweiterungspakete",
    ExpansionPack1: "Erweiterungspaket 1",
    ExpansionPack1Owned: "Erweiterungspaket 1",
    RequireExpansionPack1: "Erweiterungspaket 1",
    RequireExpansionPack1Desc: "Dies ist nur für das Erweiterungspaket 1 verfügbar",
    RequireAnyExpansionPack: "Erweiterungspakete exklusiv",
    RequireAnyExpansionPackDesc: "Für diese Funktion müssen Sie mindestens eines der Erweiterungspakete besitzen",
    HideRewardAd: "Belohnungsanzeigen ausblenden",
    HideRewardAdDesc:
        "Alle In-Game-Anzeigen sind optionale Belohnungsanzeigen. Dadurch werden alle Belohnungsanzeigen vor dem Spiel ausgeblendet.",
    HideDiscordBanner: "Discord Banner ausblenden",
    HideDiscordBannerDesc: "Ausblenden des Discord und Storefront-Banner im Hauptquartier",
    HideChat: "Chat-Nachrichten ausblenden",
    SortedByDeficit: "Sortiert nach Defizit",
    PurchaseFailed: "Der Kauf wurde nicht abgeschlossen",
    PurchaseSteamContinue: "Bitte beenden Sie Ihren Kauf bei Steam",
    PurchaseSuccess: "Der Kauf ist abgeschlossen, danke für Ihre Unterstützung",
    PrestigeCurrency: "Schweizer Franken 💵",
    RestartDesc:
        "💡 Willst du nur neu starten? Sie können oben auf Start in einer neuen Stadt tippen und Ihre aktuelle Stadt auswählen",
    PrestigeGoBack: "bleiben",
    PermanentUpgradeDesc: "Dieses Upgrade bleibt bestehen, wenn Sie in einer neuen Stadt starten",
    ProductionMultiplier: "Produktionsmultiplikator",
    ProductionMultiplierDesc:
        "Steigerung der Produktionskapazität aller Gebäude (einschließlich Minen, Fabriken, Kraftwerke, Wissenschafts- und Kulturgebäude)",
    FuelCostDiscount: "Kraftstoffkostenrabatt",
    FuelCostDiscountDesc: "Gibt einen Rabatt auf die Kraftstoffkosten beim Transport von Ressourcen",
    AutoSellCapacityMultiplier: "Multiplikator für die automatische Verkaufskapazität",
    AutoSellCapacityMultiplierDesc:
        "Ein Multiplikator, der unabhängig von der aktuellen Kapazität auf Ihre automatische Verkaufskapazität angewendet wird",
    BuildingPermitCostDivider: "Kostenteiler für Baugenehmigungen",
    BuildingPermitCostDividerDesc: "Teilen Sie die Baugenehmigungskosten durch diesen Teiler",
    ExtraAdjacentBonus: "Zusätzlicher Benachbarungsbonus",
    ExtraAdjacentBonusDesc: "Zusätzliche Bonuskapazität für jedes benachbarte Arbeitsgebäude des gleichen Typs",
    OfflineEarningMultiplier: "Offline-Verdienstmultiplikator",
    OfflineEarningMultiplierDesc: "Ein Multiplikator, der für Offline-Einnahmen gilt",
    PrestigeAlertTitle: "Bist du sicher?",
    PrestigeAlertContent:
        "Ihr Unternehmen wird aufgelöst. Sie werden %{amount} Schweizer Franken bekommen und eine neue Firma in %{city} gründen",
    PrestigeCurrencyDesc:
        "Dies ist das Geld auf Ihrem geheimen Schweizer Bankkonto. Sie können es mitnehmen, wenn Sie in einer neuen Stadt anfangen",
    Prestige: "Einzahlen",
    Cancel: "Stornieren",
    SaveFileCorrupted: "Sicherung beschädigt",
    CheatDetected:
        "Ihre alte Sicherung hat die Serverüberprüfung nicht bestanden und kann nicht gelesen werden. Sie beginnen mit einer neuen Sicherung",
    LoadGameError: "Spiel konnte nicht geladen werden",
    LoadGameErrorMessage: "Fehlermeldung: %{message}",
    LoadGameErrorDesc:
        "Bitte überprüfe deine Internetverbindung. Wenn das Problem weiterhin besteht, wenden Sie sich an den Support",
    ExpansionPackIncompatible:
        "Sie importieren einen Speicher mit Erweiterungspaketen, aber Ihr Spiel verfügt nicht über die erforderlichen Erweiterungspakete",
    SaveFileMigrated: "Eine neue Ära: Beta ist da",
    SaveFileMigratedDesc:
        "Vielen Dank für das Testen der Alphaphase. Ihre alte Karte ist nicht kompatibel, aber wir haben Ihre Daten migriert und geben Ihnen einen Bonus",
    ClaimSwissMoney: "Erhalte %{amount} Schweizer Franken 💵",
    SaveFileMigratedFinePrint:
        "Ihre Marktwert wird in Schweizer Franken umgerechnet und Ihre nicht ausgegebenen Schweizer Franken werden angerechnet. Sie erhalten 50% Schweizer Bonusfranken für Spieltests in Alpha. Die maximalen Schweizer Franken, die angerechnet werden können, sind auf 200 begrenzt",
    CashIn: "Einzahlen",
    CurrentCity: "Aktuelle Stadt",
    CashInDesc:
        "Sie erhalten diesen Betrag auf Ihr Schweizer Bankkonto, wenn Sie in einer neuen Stadt beginnen. Er basiert auf dem Marktwert Ihres Unternehmens und muss %{amount} erreichen, bevor Sie Schweizer Franken verdienen können",
    MoveToNewMap: "Starte in einer neuen Stadt",
    CityName: "Stadt",
    CitySize: "Kartengröße",
    GridType: "Zellentyp",
    StartInThisCity: "Starte in %{city}",
    CityBonus: "Stadtbonus",
    ResourceTilePercentage: "Ressourcenkacheln",
    MapSquareGrid: "quadratisch",
    MapHexGrid: "hexagon",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li> Stahlwerke haben 2x Kapazität </li> <li> Edelstahlwerke haben 2x Kapazität </li> <li> Kostenloser Eisentransport </li> <li> Stahltransport kostet 50% weniger Kraftstoff </li> <li> Beginnen Sie mit 2x automatischer Verkaufskapazität </li> <li> Keine Kachelmodifikatoren </li> ",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li> Zeppelinfabriken sind freigeschaltet </li> <li> Halbleiterfabriken haben 2x Produktivität </li> <li> Werften haben 2x Kapazität </li> <li> Autofabriken haben 2x Kapazität </li> <li> Li-Ionen-Akkufabriken sind freigeschaltet </li> ",
    Toulouse: "Toulouse",
    Rome: "Rom",
    RomeBonus:
        "<li> Kolosseen sind freigeschaltet </li> <li> Kolosseen haben 2x Produktivität </li> <li> Beginnen Sie mit dem Policy Center der Stufe 5 </li> <li> Opernhäuser haben 2x Kapazität </li> <li> Aufnahmestudios produzieren auch Kultur </li> ",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li> Starte mit Forschungslabor Level 5 </li> <li> Fachhochschulen sind frei </li> <li> Fachhochschulen haben 2x Kapazität </li> <li> Schulen haben 2x Kapazität </li> <li> Universität haben 2x Produktivität </li> ",
    HideNotProducing: "Ressourcen ausblenden, die nicht produziert werden",
    SortByStorage: "Lager",
    SortByProduction: "Produktion",
    SortByName: "Name",
    PlayerTrade: "Spielerhandel",
    AddTradeFail: "Fehler beim Hinzufügen Ihres Handels",
    AddTradeExceedMaximumTrade:
        "Sie können maximal %{number} aktive Handel haben, bitte fordern Sie zuerst einen ein, oder brechen einen ab.",
    AddTradeSuccess: "Ihr Handel wurde erfolgreich hinzugefügt",
    LoadTradeFail: "Spieler-Handel konnten nicht geladen werden. Bitte versuchen Sie es später erneut",
    ClaimTradeFail: "Wenn Sie diesen Handel nicht beanspruchen konnten, versuchen Sie es später erneut",
    CancelTradeSuccess: "Ihr Handel wurde erfolgreich abgebrochen",
    CancelTradeFail: "Dieser Handel konnte nicht abgebrochen werden. Bitte versuchen Sie es später erneut",
    AcceptTradeFail: "Dieser Handel wurde nicht akzeptiert. Bitte versuchen Sie es später erneut",
    PlayerTradeBanner: "Handel Ressourcen mit anderen Spielern",
    PlayerTradeResource: "Ressource",
    PlayerTradeAmount: "Menge",
    PlayerTradePrice: "Preis $",
    PlayerTradeValue: "Wert $",
    PlayerTradeWaiting: "Warte...",
    UseTradeCenterPrice: "Verwenden Sie den Handelszentrum-Preis",
    AddTrade: "Handel hinzufügen",
    ActiveTrades: "Aktive Handel",
    AcceptTrade: "akzeptieren",
    CancelTrade: "abbrechen",
    RefundTrade: "erstatten",
    RefundTradeSuccess: "Dieser Handel wurde zurückerstattet: %{resource} wurde an Ihr Handelszentrum zurückerstattet",
    RefundTradeFail: "Dieser Handel konnte nicht zurückerstattet werden. Bitte versuchen Sie es später erneut",
    ClaimTrade: "erhalte",
    RefreshTrade: "Aktualisierung",
    PasteYourSave: "Bitte fügen Sie Ihre gespeicherten Daten ein",
    FailedToImportSave: "Fehler beim Importieren der Sicherung",
    FailedToImportSaveDesc: "Ihre Sicherungsdatei ist nicht kompatibel oder beschädigt: %{error}",
    SaveCopiedToClipboard: "Ihre gespeicherten Daten wurden in Ihre Zwischenablage kopiert",
    CancelActiveTradeFirst: "Sie haben aktive Spieler-Handel, bitte stornieren / beanspruchen Sie diese zuerst",
    FailedToCheckActiveTrade: "Fehler beim überprüfen aktiver Spieler-Handel. Bitte versuchen Sie es später erneut",
    PlayerTradeQuotaExceed: "Dieser Handel hat Ihre Menge überschritten",
    PlayerTradeValidRange: "Entfernung: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "bezahlbar",
    PlayerTradeQuota: "Menge übrig: %{value}",
    PlayerTradeUnavailable:
        "Sie brauchen mindestens eine Ressource in Produktion oder im Lager um mit anderen Spielern zu handeln",
    PlayerTradeToClaim: "Sie haben %{num} neue Handel zum abholen im Spielerhandel",
    PowerBank: "Stromspeicher",
    PowerBankBuildDesc: "Speichern Sie überschüssigen Strom und sorgen Sie für Stromversorgung bei Engpässen",
    WarehouseBuildDesc: "Transportieren und lagern Sie alle Ressourcen mit geringeren Kraftstoffkosten",
    PowerBankChargeSpeed: "Ladegeschwindigkeit",
    PowerBankPowerLeft: "Strom übrig",
    PowerBankMoreCapacity: "Batteriesparmodus",
    PowerBankMoreCapacityDesc: "Stromspeicher laden mit 50% Geschwindigkeit auf, haben aber 50% mehr Kapazität",
    PowerBankNotWorking: "⛔ Stromspeicher arbeiten nur neben einem Kraftwerk",
    ExcludeBuildingsShutdown: "Schließen Sie stillgelegte Gebäude aus",
    ColorTheme: "Spielfarbthema",
    ColorThemeDesc: "Farbthema für Spielesymbole, Hervorhebung, Gitter und Hintergrund. ERFORDERT EINEN NEUSTART",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Siliziumminem produzieren 2x Silizuium, aber benötigen 50% mehr Strom und die Transportkosten für Silizium sind 50% höher.",
    CoalMine2xOutput: "Industrielle Revolution",
    CoalMine2xOutputDesc:
        "Kohleminen produzieren 2x soviel Kohle, aber benötigen 50% mehr Strom und die Transportkosten für Kohle sind um 50% erhöht.",
    AlMine2xOutput: "Aluminumschmelze",
    AlMine2xOutputDesc: "Aluminumminem produzieren 2x soviel Aluminium und verbrauchen 2x soviel Strom.",
    LoggingCamp2xOutput: "Abholzung",
    LoggingCamp2xOutputDesc: "Forstbetriebe produzieren 2x soviel Holz und die Transportkosten werden verdoppelt.",
    HideResourceMovement: "Ressourcembewegungen ausblenden",
    HideResourceMovementDesc:
        "Die Ressourcenbewegungen werden standartmäßig ausgeblendet (die kleinen Punkte) und nur angezeigt wenn ein Gebäude angewählt ist.",
    PowerBankLeft: "Energiespeicher",
    ColorThemeEditor: "Farbschemen Editor",
    ColorThemeEditorDesc: "Du kannst im aktuellen Schema Farben überschreiben. Du hast aktuell %{num} überschrieben.",
    ColorThemeEditorSave: "Speichern",
    ColorThemeEditorReset: "Zurücksetzten",
    ColorThemeEditorResetAll: "Alle zurücksetzten",
    NewMessageMentions: "Eine neue Nachricht erwähnt Sie: %{message}",
    HideChatMentions: "Chat-Erwähnungen ausblenden",
    HideChatMentionsDesc:
        "Blenden Sie die Audio- und Toastbenachrichtigung aus, wenn eine Chat-Nachricht mich erwähnt,",
    PendingConstructionCannotReload: "Sie haben gerade einen Bauvorgang, das Spiel kann nicht neu geladen werden",
    AcceptTradeFailRateLimit: "Sie können nur einen Trade alle %{time} Sekunden akzeptieren",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Handel abbrechen?",
    CancelTradeConfirmDialogYes: "Ja",
    CancelTradeConfirmDialogNo: "Nein",
    WarehouseInputRoutes: "Eingaberouten",
    WarehouseAddInput: "Route hinzufügen",
    WarehouseTapToSelect: "Tippen Sie zur Auswahl auf die Karte...",
    WarehouseFindOnMap: "🔍 auf der Karte finden",
    WarehouseRemoveRoute: "entfernen",
    WarehouseAddRouteFail: "Route konnte nicht hinzugefügt werden: Die ausgewählte Kachel ist keine gültige Quelle",
    LevelN: "Level %{level}",
    Surplus: "Überschuss",
    Production: "Produktion",
    Consumption: "Verbrauch",
    WarehouseInputCapacityDescV2: "Gesamtkapazität des Eingangsstransports, gleichmäßig auf alle Strecken verteilt",
    WarehouseInputCapacityPerRoute: "Pro Route: ",
    PlayerCountryFlag: "Spielerflagge",
    PlayerCountryChooseFlag: "In alphabetischer Reihenfolge des Länderkürzels",
    WindTurbineAlwaysWork: "Der Wind wird stärker",
    WindTurbineAlwaysWorkDesc: "Windkraftanlagen arbeiten 100% der Zeit, produzieren aber 30% weniger Strom",
    BookPublisherScience: "Wissenschaftsliteratur",
    BookPublisherScienceDesc: "Buchverlage produzieren Wissenschaft statt Kultur",
    WarehouseOutwardFuelSave: "Gratisversand",
    WarehouseOutwardFuelSaveDesc: "Lager bieten den gleichen Kraftstoffverbrauch, auch beim Transport nach außen",
    ImportSaveVersionTooNew:
        "Sie importerien eine Sicherung aus %{saveVersion} aber die Spielversion ist %{gameVersion}. Bitte aktualisiere zuerst dein Spiel",
    BatteryFuelEconomy: "Wiederaufladbare Batterie",
    BatteryFuelEconomyDesc:
        "Der Kraftstoffverbrauch der Batterie verbessert sich um 100% (daher 50% Kraftstoffkosten).",
    ShowTheoreticalInputOutputCapacity: "Zeigen Sie die theoretische Eingangs- / Ausgabekapazität an",
    SpecialTransportCost: "Ressourcen mit besonderen Transportkosten",
    FreeTransportCost: "Ressourcen mit kostenlosen Transportkosten",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Ressourcen erscheinen in der Regel in Clustern.</li> <li>Das Lagerhaus bietet 50% mehr Kraftstoffeinsparung.</li> <li>Einzigartiges Gebäude: Manga-Verlag</li> <li>Einzigartiges Gebäude: Anime-Studio</ li ><li>Halbleiterchipfabriken haben 2x Produktivität</li> <li>Li-Ionen-Batteriefabriken haben 2x Kapazität</li> <li>Batteriefabriken sind entsperrt</li> <li>Batteriefabriken haben 2x Kapazität</ li > <li>Der Kraftstoffverbrauch der Batterie erhöht sich um 100%.</li> <li>Batteriefabriken benötigen keine Kohle.</li> <li>Beginnen Sie mit 100K-Batterien</li>",
    HideChatDescV2:
        "Chat-Nachricht in der unteren Symbolleiste ausblenden. Durch das Anzeigen von Chat-Nachrichten stimmen Sie den ",
    HideChatDescV2ToS: "Nutzungsbedingungen zu",
    IntegratedCircuitFab: "Integrierte Schaltkreisgießerei",
    MangaPublisher: "Mangaverlag",
    Manga: "Manga",
    AnimeStudio: "Animestudio",
    Anime: "Anime",
    PlayerTradeAction: "Aktion",
    PlayerTradeBuy: "Kaufen",
    PlayerTradeSell: "Verkaufen",
    PlayerTradeBid: "Verkaufen",
    PlayerTradeAsk: "Kaufen",
    CancelTradeConfirmDialogDescV2:
        "Wenn Sie diesen Handel stornieren, werden %{Prozent} der Ressource / des Geldes zurückerstattet. Die Ressourcen werden an das Handelszentrum-Lager zurückerstattet",
    ClaimTradeSuccessV2: "Ihr Handel wurde erfolgreich angenommen: %{cashOrResource}",
    AcceptTradeSuccessV2: "Dieser Handel wurde von dir abgeschlossen: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Besser als der Marktpreis",
    ResourceExplorer: "Ressourcen-Explorer",
    ResourceExplorerDesc: "Ermöglicht das Extrahieren von Ressourcen aus einer leeren Kartenkachel",
    ResourceExplorerDescLong:
        "💡 Ressourcen-Entdecker haben keinen Benachbarungsbonus. Der Stromverbrauch ist je nach Ressource unterschiedlich",
    ResourceExplorerSelectResource: "Erkunden",
    ProductionSettings: "Produktionseinstellungen",
    PlayerTradeQuotaDesc:
        "💡 Die Handelsquote der Spieler beträgt %{percent} Ihres Marktkapitals. Sie wird zurückgesetzt, wenn der Markt aktualisiert wird",
    PlayerTradePartialFillTitle: "Wählen Sie Füllprozentsatz",
    PlayerTradeAmountNotValidV2: "Der minimal zulässige Handelsbetrag beträgt 1",
    PlayerTradeOptOut: "Sie haben sich von der Rangliste abgemeldet und können nicht mit anderen Spielern handeln",
    FirstTimeReadGuide:
        "💡 Benötigen Sie ein bisschen Hilfe beim Spielen? Tippen Sie hier, um den Anfängerleitfaden zu lesen!",
    ReadSteamGuideV2: "Spielanleitungen",
    ReadSteamGuideV2Desc:
        "Sie können von der Community erstellte Anleitungen auf Steam lesen - und Sie können auch Ihre eigenen erstellen",
    ChatMessageTooLong: "Ihre Chat-Nachricht hat die maximal zulässigen Zeichen überschritten",
    ChatPlaceholderV2: "Geben Sie Ihre Nachricht ein: max %{length} Buchstaben",
    ShowProfitBreakdown: "Gewinnaufschlüsselung anzeigen",
    HideProfitBreakdown: "Gewinnaufschlüsselung ausblenden",
    ProfitBreakdownOutput: "%{res} Erzeugung",
    ProfitBreakdownInput: "%{res} Verbrauch",
    ProfitBreakdownFuel: "Kraftstoffkosten",
    BuildingProfit: "Gewinn",
    RestoreBackup: "Wiederherstellen",
    SteamLogin: "Melden Sie sich via Steam an",
    SteamLoginDialogDesc:
        "Für Ihre lokale Speicherung ist das Erweiterungspaket aktiviert. Sie müssen sich über Steam anmelden, um fortzufahren. Oder Sie können Ihre lokale Speicherung löschen und von vorne beginnen",
    SteamLoginDesc:
        "Wenn Sie Erweiterungspakete bei Steam besitzen, können Sie nach der Anmeldung mit Erweiterungspaketen im Web spielen",
    SteamLoginYes: "Einloggen",
    SteamLoginNo: "Löschen & von vorne beginnen",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Internationaler Exporthandel",
    FreeTransportToTradeCenterDesc:
        "Der Transport zum Handelszentrum kostet keinen Kraftstoff, aber der Transport vom Handelszentrum kostet 50% mehr Kraftstoff",
    TaiChi10xCulture: "Perle des Orients",
    PlayerTradeYouHave: "Auf Lager: %{amount}",
    PlayerTradeFillValue: "Wert",
    FiberFactory: "Glasfaserfabrik",
    Fiber: "Glasfaser",
    Achievements: "Errungenschaften",
    AchievementsDesc: "Du hast %{number} von %{total} Errungenschaften erreicht",
    AchievementsReward: "Belohnung: Schweizer Franken +%{swiss}",
    AchievementsRewardToast: "Sie haben die Belohnung beansprucht:  Schweizer Franken +%{swiss}",
    AchievementsClaim: "Einsammeln",
    AchievementsToast: "Du hast %{name} erreicht, fordern Sie Ihre Belohnung im Hauptquartier an",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Sicherung",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup fehlgeschlagen: %{error}",
    SteamManualBackup: "Steam Cloud Sync erzwingen",
    UILoading: "Laden...",
    UserAuthenticated: "Sie sind authentifiziert",
    BuildingResourceBreakdown: "Aufschlüsselung des Leerlaufbetrags",
    SortByDeficit: "Defizit",
    SortByRunOut: "Läuft aus",
    SocialNetworkInc: "Social Network Inc.",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Datenbankunternehmen",
    Database: "Datenbank",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Flugzeugträgerfabrik",
    AircraftCarrier: "Flugzeugträger",
    MapExclusive: "Karten exklusiv",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Autofabriken verwenden Batterien anstelle von Benzin und benötigen nur 50% der Menge",
    HongKongBonusV2:
        "<li>Einzigartiger Marktpreisalgorithmus - Preise und Aktienbewertung folgen der Normalverteilung (Glockenkurve)</li><li>Marktaktualisierungen und Zurücksetzen von Handelsquoten sind doppelt so häufig (jede Stunde)</li><li>Forschung kann über gehandelte Ressourcen freigeschaltet werden</li><li>Einzigartiges Gebäude: Kung-Fu Dojo</li><li>Einzigartiges Gebäude: Tai-Chi Dojo</li><li>Erhöhung der maximal zulässigen Anzahl aktiver Spieler-Trades um 50%</li><li>Beginnen Sie mit 1 weiteren Auto-Sell-Parallelität</li><li>Einzigartige Richtlinie: Internationaler Exporthandel</li><li>Einzigartige Richtlinie: Perle des Orients</li><li>Das Großhandelszentrum benötigt zum Freischalten nur 4 Ressourcen</li><li>Beginnen Sie mit 100 Millionen Bargeld</li>",
    TaiChi10xCultureDescV2:
        "Kostenloser Transport von Kung-Fu und Tai-Chi. Filmstudios haben eine doppelte Kapazität, verbrauchen aber 50% mehr Strom",
    SettingsFullScreen: "Vollbild",
    SettingsFullScreenDesc: "Führen Sie das Spiel im Vollbildmodus aus. Nur für die Steam-Version verfügbar",
    LeaderboardByAllPrestigeCurrency: "Summe verdienter Schweizer Franken",
    LeaderboardByCash: "Aktuelles Bargeld",
    LeaderboardBySwissPerBuilding: "Aktuelle Schweizer Franken pro Gebäude",
    LeaderboardTotalValuation: "Gesamtwert",
    LeaderboardDescV2: "Sehen Sie, wo die Top-Spieler sind",
    LastUpdatedAt: "Zuletzt aktualisiert um",
    DetroitBonusV3:
        "<li>Motorenfabriken sind entsperrt</li><li>Motorenfabriken haben 2x Produktivität</li><li>Autofabriken haben 2x Kapazität</li><li>Autofabriken verwenden Gas anstelle von Benzin</li><li>Kostenloser Autotransport</li><li>Nikola Tesla Richtlinie ist kostenlos</li><li>Zugfabriken haben 2x Kapazität</li>",
    SaveAndExit: "Spiel speichern und beenden",
    SaveAndExitDesc:
        "Spiel speichern und beenden. Dies ist nur in der Steam-Version verfügbar und entspricht der Schaltfläche zum Schließen in der Fensterleiste",
    AutoSellResourceWarningShortLabel: "💡Auto Verkauf",
    AutoSellResourceWarningDesc:
        "Sie verkaufen diese Ressource automatisch. Der im Handelszentrum verfügbare Betrag kann hier nicht verwendet werden",
    PlayerTradeLocalPrice: "Lokaler Preis: %{price}",
    ChatForceScroll: "Scrollen erzwingen",
    ChatForceScrollDesc:
        "Wenn das Scrollen erzwingen aktiviert ist, wird der Chat immer dann gescrollt, wenn eine neue Nachricht eingeht. Andernfalls wird nur gescrollt, wenn Sie sich bereits unten befinden",
    ResourceExplorer2: "Ressourcen-Finder 2.0",
    ResourceExplorer2Desc: "Ressourcen-Finder erzeugen 2x Austrag, verbrauchen aber 2x Strom",
    ConstructionCancel: "Bau abbrechen",
    ConstructionPause: "Pause",
    ConstructionResume: "Fortsetzen",
    PolicyBlueprint: "Blaupause",
    PolicyBlueprintDesc:
        "Der Bau eines Gebäudes beginnt nicht automatisch - er muss manuell gestartet werden (KOSTENLOSE RICHTLINIE)",
    HighlightUnderConstruction: "... wurde noch nicht gebaut",
    HighlightUnderLevel10: "...sind unter Level 10",
    HighlightUnderLevel20: "...sind unter Level 20",
    HighlightUnderLevel30: "...sind unter Level 30",
    Logout: "Sie sind abgemeldet",
    ConstructionStatusQueueingV2: "Anstehend",
    ConstructionStatusPausedV2: "pausiert",
    ConstructionStatusBuildingV2: "Gebäude",
    ConstructionStatusUnpaidV2: "Unbezahlt",
    ConstructionStatus: "Baustatus",
    ConstructionStart: "Start",
    CostFree: "kostenlos",
    PlaceBlueprint: "Platzieren einer Gebäude Blaupause ist kostenlos",
    PlayerTradePriceNotValidV2: "Der Handelspreis muss zwischen %{min} und %{max} liegen",
    MarketNews: "Marktneuigkeiten",
    MarketNewsApplyToYou: "Nur für dich",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 hervorheben",
    MarketNewsFilterInput: "Alle %{res} Verbraucher",
    MarketNewsFilterOutput: "Alle %{res} Erzeuger",
    MarketNewsFilterBoth: "Alle %{res} Verbraucher und Erzeuger",
    MarketNewsIncrease: " erhöht um %{percent}",
    MarketNewsDecrease: " verringert um %{percent}",
    MarketNewsBuilding: "Dieses Gebäude wird betroffen von %{num} Neuigkeiten",
    StockholmBonusV2:
        "<li>Einzigartiges Gebäude: Musikproduzent</li><li>Forstbetriebe haben 2x Absatz</li><li>Papierfabriken sind entsperrt</li><li>Schaltungsgießereien haben 2x Produktivität</li><li>Die Politik der Wissenschaft Richtlinie ist kostenlos</li>",
    OsloBonusV2:
        "<li>Ölraffinerien sind freigeschaltet</li><li>Ölraffinerien haben 2x Kapazität</li><li>Die Richtlinie Elektronischer Öltransport ist kostenlos</li><li>Gasaufbereitungsanlagen haben 2x Kapazität</li><li>Kostenlose Windkraftanlage der Stufe 4 x1</li><li>Kostenlose Ölquelle der Stufe 4 x1</li><li>Kostenlose Ölraffinerie der Stufe 2 x1</li><li>Kostenlose Erdgaspumpe der Stufe 2 x1</li>",
    FreeOilTransportV2: "Elektronischer Öltransport",
    Tutorial4P1:
        "Der Transport von Ressourcen kostet Kraftstoff. Es gibt verschiedene Kraftstoffarten, momentan verwenden Sie <em>petrol⛽</em> als Kraftstoff. Sie haben eine <em>Ölraffinerie</em> welche das Öl auf der Ölquelle verbraucht und Benzin herstellt.<br><br>Die kleinen bewegenden <em>Punkte</em> stellen den Transport der Ressourcen dar. Sie sollten Ihre Gebäudestandorte optimieren, um die Distanz zu minimieren.<br><br><em>Aufwerten</em> deiner Gebäude erhöht deren Produktion, aber erhöht ebenfalls deren Stromverbrauch, sowie die benötigten Ressourcen.",
    Tutorial4P2:
        "Sie können Ihren Kraftstofftyp im <em>Logitik Institut🚦</em> ändern- auf dieser Karte, können Sie auch <em>Erdgas</em> als Kraftstoff verwenden.<br><br>Das Logitik Institut zeigt auch Ihre Transportwege an, auf denen der meiste Kraftstoff verbraucht wird - Sie sollten es im Auge behalten.<br><br>Denken Sie daran, <em> sicherzustellen, dass Ihre Kraftstoffproduktion über dem Verbrauch liegt </em>, da sonst Ihre Produktion stoppt, wenn Ihnen der Kraftstoff ausgeht.<br><br>Machen Sie sich in diesem Fall keine Sorgen, Sie können notfalls Kraftstoff im Handelszentrum oder bei anderen Spielern kaufen",
    Tutorial5P2:
        "<em>Die Statistik Agentur📊</em> bietet einen guten Überblick deiner Produktion. Sie können eine detaillierte Aufschlüsselung Ihrer Ressourcenein- und -ausgabe sehen.<br><br>Es gibt auch viele nützliche Diagramme📈 - Sie sollten sich auf diese beziehen, wenn Sie Ihre Produktion ausbalancieren.<br></br>Dein <em>Geld💰, Stromüberschuss⚡ und Kraftstoffüberschuss⛽</em> -zahlen werden auch in der oberen linken Ecke angezeigt. Wenn eine davon rot wird, sollten Sie untersuchen, was los ist.",
    MusicProducer: "Musikproduzent",
    PlasticFiber: "Kunststofffaser",
    PlasticFiberDesc: "Glasfaserfabriken verwenden 50% mehr Kunststoff, aber 50% weniger Glas",
    NewsEffectx2: "Pressekonferenz",
    NewsEffectx2Desc: "Der Effekt von Marktnachrichten verdoppelt sich sowohl positiv als auch negativ",
    SellRefundPercentage: "Rückerstattung verkaufen / herabstufen",
    SellRefundPercentageDesc:
        "Wenn Sie ein Gebäude verkaufen oder herabstufen, ist dies der Prozentsatz an Bargeld und Ressourcen, den Sie erstattet bekommen",
    SellBuildingDescV2:
        "Durch den Verkauf eines Gebäudes erhalten Sie %{percent} Ihrer Investition zurück und %{percent} der Ressourcen werden zum Handelszentrum transportiert",
    BuilderMoveSpeed: "Bauherren Bewegungsgeschwindigkeit",
    BuilderMoveSpeedDesc: "Die Geschwindigkeit, mit der sich Bauherren bewegen, um Gebäude zu bauen",
    EBookInc: "eBook Inc.",
    ResourceBooster: "Ressourcen-Verstärker",
    BuildWarningTitle: "Gebäude funktioniert möglicherweise nicht",
    BuildWarningTitleDesc: "%{reason}. Sind Sie sicher, dass Sie auf dieser Zelle zu bauen wollen?",
    BuildWarningBuildAnyway: "Trotzdem bauen",
    ResourceBoosterNotWorking: "⛔ Ressourcen-Verstärker funktionieren nur in der Nähe von Lagerstätten",
    ResourceBoosterPercentage:
        "💡 Dieses Gebäude bekommt %{percent} Austragserhörhung von benachbarten Ressourcen-Verstärkern",
    ResourceBoosterBuildings: "Gebäude werden verstärkt",
    BuildingResourceConversion: "%{resource} Umwandlung",
    AllTimeSwissMoneyEarned: "Gesamstmenge Schweizer Franken: %{number}",
    BuildingUpgradeCostDivider: "Gebäude-Upgrade-Kostenteiler",
    AchievementSoftwareGiant: "Software Gigant",
    AchievementSoftwareGiantDesc:
        "Erstellen Sie auf derselben Karte ein Softwareunternehmen der Stufe 10, ein Betriebssystemunternehmen der Stufe 10, ein Datenbankunternehmen der Stufe 10 und einen Webbrowser der Stufe 10",
    AchievementSpaceRace: "Weltraumrennen",
    AchievementSpaceRaceDesc:
        "Baue auf derselben Karte eine Raketenfabrik der Stufe 10, eine Satellitenfabrik der Stufe 10, eine Raumschifffabrik der Stufe 10 und eine Raumstationsfabrik der Stufe 10",
    AchievementToTheMoon: "Zum Mond",
    AchievementToTheMoonDesc:
        "Baue eine Bitcoin-Farm der Stufe 40 und eine Dogecoin-Farm der Stufe 40. Besitze 1B Bitcoin und 1B Dogecoin",
    ItsAllGreen: "Alles ist grün",
    ItsAllGreenDesc: "Haben Sie 50 Produktionslinien und überhaupt kein Produktionsdefizit",
    DeepInRed: "Tiefrot",
    DeepInRedDesc: "Haben Sie 50 Produktionslinien mit Produktionsdefizit",
    UseScientificNotation: "Verwenden Sie die wissenschaftliche Zahlen",
    UseScientificNotationDesc:
        "Verwenden Sie die wissenschaftliche Zahlen (e Nummernsystem) für Zahlen größer als 999,9T",
    LogoutDescV2:
        "Sie haben sich auf einem anderen Gerät angemeldet, dieses Gerät ist abgemeldet. Sie können sich wieder anmelden, aber das andere Gerät wird abgemeldet ",
    LogBackIn: "Anmelden",
    PlayerTradeNowAllowedV2:
        "Spieler-Trades sind innerhalb von %{hour} nicht verfügbar, nach of Wiederherstellen / Importieren eines Spielstandes",
    ServerDisconnected:
        "Sie sind vom Server getrennt sind, überprüfen Sie bitte Ihre Internetverbindung und starten Sie das Spiel neu",
    BuildingUpgradeCostDividerDescV2: "Teilen Sie die Kosten für die Gebäudeerweiterung durch diesen Teiler",
    ResourceBoosterBannerDesc:
        "💡 Sie haben derzeit %{number} Ressourcen-Verstärker - Der Strom- und Wissenschaftpunkteverbrauch jedes Verstärkers erhöht sich mit jedem Verstärker den die besitzen.",
    ResourceBoosterDesc: "Steigern Sie die Leistung benachbarter Minen",
    BlockUserChatTitle: "Blockiere %{user}",
    BlockUserChatAction: "Blockieren",
    BlockUserChatDesc:
        "Der Block wird während dieser Spielsitzung wirksam sein und Sie können dies nicht rückgängig machen, es sei denn, Sie starten das Spiel neu",
    ChangeNameCooldown: "Sie können Ihren Namen nur ein mal alle %{hour} ändern",
    AtomicBombFactory: "Atombombenfabrik",
    AtomicBomb: "Atombombe",
    DynamiteFactory: "Dynamit Fabrik",
    Dynamite: "Dynamit",
    NuclearMissileFactory: "Atomraketenfabrik",
    NuclearMissile: "Atomrakete",
    LiquidPropellantFactory: "Fabrik für flüssige Treibmittel",
    GasPropellantFactory: "Gas-TreibstoffFabrik",
    Propellant: "Treibstoff",
    ProjectV2: "Projekt V-2",
    ICBMFactory: "Interkontinentalraketenfabrik",
    ICBM: "Interkontinentalraketen",
    RadarFactory: "Radarfabrik",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Kommando",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Ihr letzter Fortschritt wird in Steam Cloud gespeichert und geräteübergreifend synchronisiert. Das Spiel sichert außerdem alle 10 Minuten automatisch Ihre Speicherung in Steam Cloud. Sie können jederzeit eine Sicherung erzwingen",
    SpaceColony: "Weltraumkolonie",
    SpaceColonyInc: "Weltraumkolonieagentur",
    ProjectVostok: "Projekt Wostok",
    AdjacentBonusSquare: "Angrenzendes Bonusfeld",
    AdjacentBonusSquareDesc: "Der angrenzende Bonus ist 50% effektiver, aber die Zellenmodifikatoren skalieren von -15% bis + 15%.",
    ResourceBoosterSquare: "Ressourcen-Verstärker Quadrat",
    ResourceBoosterSquareDesc:
        "Ressourcen-Verstärker sorgen für 25% mehr Boost, aber ihr Wissenschaftspunkte- und Stromverbrauch steigt um 25%",
    SteelMillx2: "Stahlofenmodernisierung",
    SteelMillx2Desc: "Stahlwerke und Edelstahlwerke haben eine doppelte Kapazität, verbrauchen jedoch die doppelte Menge Strom",
    IronSteelZone: "Eisenstahlzone",
    IronSteelZoneDesc:
        "Resourcen-Verstärker bieten benachbarten Stahlwerken oder Edelstahlwerken einen Produktionsbonus von %{percent} für jede arbeitende angrenzende Eisenmine",
    FuelDynamite: "Kraftstoff Dynamit",
    FuelDynamiteDesc: "Dynamitfabriken verwenden Ihren aktuellen Kraftstoff anstelle von Öl",
    StPetersburgBonusV2:
        "<li>Uranminen haben 2x Produktion</li><li>Urananreicherungsanlagen haben eine doppelte Kapazität</li><li>Der Urantransport kostet 50% weniger Kraftstoff</li><li>Kostenloser Waffentransport</li><li>Das Projekt Wostok hat eine Kapazität von 2x</li>",
    ToulouseBonusV2:
        "<li>Titanminen haben 2x Prdouktion</li><li>Urananreicherungsanlagen haben eine doppelte Produktivität</li><li>Triebwerksfabriken haben eine Kapazität von 2x</li><li>Flugzeugfabriken haben 2x Produktivität</li><li>Raketenfabriken haben eine Kapazität von 2x</li>",
    BuildingPermitsNeededDesc: "Dieses Gebäude funktioniert nicht, weil Sie nicht genügend Baugenehmigungen haben",
    BuildingPermitsNeeded: "Baugenehmigungen erforderlich",
    BuyMissingPermits: "Fehlende Baugenehmigungen kaufen",
    GPUIsBusy: "Ihre GPU ist ausgelastet",
    GPUIsBusyDesc:
        "Ihr Betriebssystem hat die Grafik des Spiels angehalten, da die GPU mit anderen Aufgaben beschäftigt ist. Sie können das Spiel neu laden, um fortzufahren. Wenn es nicht funktioniert, starte das Spiel neu",
    SaveAndReloadGame: "Spiel speichern und neu laden",
};
