export const ES = {
    Translator: "Traductor",
    TranslatorName: "Juan Manuel Jaén Cabrera (Leunal17), Dishito",
    Language: "Idioma",
    ThisLanguage: "Español",
    OK: "Vale",
    SteelMill: "Molino de acero",
    StainlessSteelPlant: "Planta de acero inoxidable",
    CircuitFoundry: "Fundición de circuitos",
    IntegratedCircuit: "Circuito integrado",
    OilWell: "Pozo de petróleo",
    Wood: "Madera",
    LoggingCamp: "Campamento maderero",
    LumberMill: "Serreria",
    Lumber: "Tablas de madera",
    Paper: "Papel",
    PaperMill: "Fábrica de papel",
    Book: "Libro",
    BookPublisher: "Editora de libros",
    OilRefinery: "Refinador de petróleo",
    Sell: "Vender",
    Upgrade: "Mejorar",
    Build: "Construir",
    Inspect: "Inspeccionar",
    Buildings: "Edificios",
    Iron: "Hierro",
    Actions: "Comportamiento",
    FuelType: "Elija combustible",
    FuelCost: "Coste del combustible",
    FuelConsumption: "%{fuel} Consumo",
    FuelEconomy: "Economía de combustible",
    FuelProduction: "%{fuel} Producción",
    FuelInStorage: "%{fuel} En almacen",
    Plastic: "Plastico",
    FuelSurplus: "%{fuel} Sobrante",
    Petrol: "Gasolina",
    Buy: "Comprar",
    NoLiquidity: "Sin liquidez",
    NoLiquidityTurnOffAutoSell:
        "No hay suficiente liquidez en el mercado para %{res}, la venta automática se ha desactivado",
    Multiplier: "Multiplicador",
    MultiplierDesc: "Cada 10 niveles, obtienes +1 multiplicador",
    SellBuilding: "Vender Edificio",
    PowerGrid: "Red eléctrica",
    TradeAmount: "Monto comercial",
    SortBy: "Ordenar por",
    SortByPrice: "Precio",
    SortByAmount: "Cantidad",
    NotEnoughResourcesForTrade: "No hay suficientes recurso(s) en el Trade Center para este comercio",
    NotEnoughResources: "No hay suficientes recurso(s) para esta operación",
    Transportation: "Transporte",
    Cash: "Dinero",
    Aluminum: "Aluminio",
    ResearchPoint: "Punto de investigación",
    Unlock: "Desbloqueado",
    BuildingUnlocked: "%{building} Ha sido desbloqueado",
    Science: "Ciencia",
    ScienceFromPowerDesc: "Las plantas de energía producen una pequeña cantidad de ciencia cuando generan energía",
    Culture: "Cultura",
    School: "Escuela",
    University: "Universidad",
    Polytechnic: "Politécnico",
    Colosseum: "Coliseo",
    WindTurbine: "Turbina eólica",
    Engine: "Motor",
    EngineFactory: "Fábrica de motores",
    CameraFactory: "Fábrica de cámaras",
    Camera: "Cámara",
    Gun: "Arma",
    GunFactory: "Fábrica de armas",
    Aircraft: "Aviones",
    AircraftFactory: "Fábrica de aviones",
    Zeppelin: "zepelín",
    ZeppelinFactory: "Fábrica de Zeppelin",
    Tank: "Tanque",
    TankFactory: "Fábrica de tanques",
    CoalPowerPlant: "Central eléctrica de carbón",
    PetrolPowerPlant: "Planta de energía de gasolina",
    Copper: "Cobre",
    Gas: "Gas natural",
    GasPump: "Bomba de gas natural",
    GasPowerPlant: "Planta de energía de gas",
    Missile: "Misil",
    MissileFactory: "Fábrica de misiles",
    Rocket: "Cohete",
    RocketFactory: "Fábrica de cohetes",
    BuildingPermit: "Permiso de construcción",
    BuildingPermitDesc:
        "Tienes permiso para %{amount} edificios, ya has construido %{amountBuilt} y tienes %{amountLeft} restantes",
    BuildingLocked:
        "El edificio aún no está disponible, primero debes desbloquearlo en el Laboratorio de investigación",
    BuildQueue: "Crear cola",
    BuildQueueDesc: "Número de edificios actualmente en cola",
    MaxBuilders: "Maximas Construcciones",
    MaxBuildersDesc: "Cantidad de edificios que puedes construir al mismo tiempo",
    Silicon: "Silicio",
    AluminumMine: "Mina de aluminio",
    CopperMine: "Mina de cobre",
    SiliconMine: "Mina de silicio",
    IronMine: "Mina de hierro",
    CoalMine: "Mina de carbón",
    Headquarter: "Sede",
    ResearchLab: "Laboratorio de investigación",
    TradeCenter: "Centro de Comercio",
    Resources: "Recursos",
    NotEnoughPower: "💡 No hay suficiente poder, considere aumentar el suministro de energía",
    NotEnoughFuel: "No es suficiente %{fuel} para esta operación",
    NotEnoughCash: "No hay suficiente dinero en efectivo para esta operación.",
    NotEnoughSwissMoney: "No hay suficiente dinero suizo para esta operación.",
    BuildingNotEnoughFuel: "💡 No es suficiente %{fuel}",
    AutoSell: "Vender automático",
    SellAll: "Vender todo",
    Change: "Cambio",
    StatisticsBureau: "Oficina de Estadística",
    LogisticsDepartment: "Departamento de logística",
    From: "Desde",
    Top20FuelCost: "20 principales costos de combustible",
    To: "Para",
    TransportTime: "Tiempo de transporte",
    TopN: "Cima %{n}",
    Warehouse: "Depósito",
    TradeWarehouse: "Almacén de carga",
    Coal: "Carbón",
    Video: "Video",
    ClothingFactory: "Fábrica de ropa",
    Clothes: "Ropa",
    Fashion: "Moda",
    FashionFactory: "Fábrica de moda",
    VideoFarm: "Granja de videos",
    SantaFactory: "Fábrica de Santa",
    Santa: "Papa Noel",
    Car: "Coche",
    CarFactory: "Fábrica de coches",
    Ship: "Barco",
    SolarPanel: "Panel solar",
    SolarPanelDesc:
        "💡 Los paneles solares solo funcionan 5 segundos de cada 10 segundos - todos los ciclos están alineados",
    WindTurbineDesc:
        "💡 Las turbinas eólicas solo funcionan 8 segundos de cada 10 segundos - los ciclos no están alineados",
    Movie: "Película",
    MovieStudio: "Estudio de cine",
    Sitcom: "Comedia de enredo",
    TVStudio: "Estudio de televisión",
    PC: "PC",
    GameStudio: "Estudio de juegos",
    Game: "Juego",
    ComputerFactory: "Fábrica de Ordenadores",
    Shipyard: "Astillero",
    PowerUsage: "Consumo de energía",
    PowerSupply: "Fuente de alimentación",
    PowerSurplus: "Excedente de energía",
    Level: "Nivel",
    Power: "Energía",
    CentralBank: "Banco Central",
    ResourceInput: "En",
    ResourceOutput: "Fuera",
    ResourceStorage: "Almacenamiento",
    ResourceChange: "Cambio",
    ResourceInOutDesc:
        "💡 Toque los números de entrada y salida de arriba para resaltar los edificios de entrada y salida correspondientes",
    ResourceChart: "Gráfico de recursos",
    MarketUpdateIn: "Actualización de mercado en %{time}",
    Income: "Ingreso",
    Semiconductor: "Semiconductor",
    SemiconductorFactory: "Fábrica de semiconductores",
    Steel: "Acero",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Granja de Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Granja Dogecoin",
    Guitar: "Guitarra",
    GuitarFactory: "Fábrica de guitarras",
    Drum: "Tambor",
    DrumFactory: "Fábrica de Tambores",
    RecordingStudio: "Estudio de grabación",
    OperaHouse: "Teatro de la Ópera",
    CoalGasificationPlant: "Planta de gasificación de carbón",
    GasProcessingPlant: "Planta de procesamiento de gas",
    Music: "Musica",
    Glass: "Vidrio",
    PhoneFactory: "Fábrica de teléfonos",
    Phone: "Telefono",
    GlassFactory: "Fábrica de vidrio",
    Oil: "Petróleo",
    Chromium: "Cromo",
    ChromiumMine: "Mina de cromo",
    Uranium: "Uranio",
    EnrichedUranium: "Uranio enriquecido",
    NuclearPowerPlant: "Planta de energía nuclear",
    UraniumEnrichmentPlant: "Planta de enriquecimiento de uranio",
    UraniumMine: "Mina de uranio",
    Titanium: "Titanio",
    TitaniumMine: "Titanium Mine",
    TitaniumAlloyPlant: "Mina de titanio",
    ChromiumAlloyPlant: "Planta de aleación de cromo",
    Input: "Introducir",
    PanelPosition: "Panel Position",
    PanelPositionDesc:
        "Mostrar panel lateral a la izquierda, derecha o automático (depende del mosaico seleccionado actualmente)",
    InputCapacity: "Capacidad de entrada",
    InputCapacityPerCycle: "Capacidad de entrada / Ciclo",
    Output: "Salida",
    OutputCapacity: "Capacidad de salida",
    OutputCapacityPerCycle: "Capacidad de salida / Ciclo",
    ResourceDeposit: "Depósito de recursos",
    RecommendedBuilding: "💡 Este mosaico tiene %{resource} depositar",
    AdjacentBonus: "Bono adyacente",
    AdjacentBonusDesc:
        "Usted obtiene %{bonus}% capacidad adicional para cada edificio de trabajo adyacente del mismo tipo",
    ConsiderIncreaseProduction: "💡 Consider increase %{resource} producción",
    AlwaysTransportInput: "Modo de almacenamiento",
    AlwaysTransportInputTradeCenter: "Exportar siempre",
    AlwaysTransportInputTradeCenterDesc:
        "Transporte siempre los recursos al Trade Center, incluso si la venta automática no está habilitada para ese recurso.",
    AlwaysTransportInputDesc:
        "Transporte siempre los recursos de entrada, incluso si están por encima de los requisitos mínimos de producción.",
    ProductionCycleLength: "Ciclo productivo",
    ProductionCycleLengthDesc:
        "Duración de un ciclo de producción, medido en segundos. Alargar el ciclo aumentará la entrada / salida por ciclo en consecuencia, por lo tanto, reducirá su prioridad al buscar recursos de entrada",
    MaxInputDistance: "Distancia máxima de entrada",
    MaxInputDistanceDesc:
        "La distancia máxima desde la que este edificio puede obtener recursos de entrada, medida en número de mosaicos",
    AutoSellCapacity: "Capacidad de venta automática",
    AutoSellCapacityDesc: "Cantidad máxima de recursos que la venta automática puede manejar por segundo, por recurso",
    CurrentAutoSellCapacityMultiplier: "Multiplicador actual: x%{n}",
    AutoSellConcurrency: "Simultaneidad de venta automática",
    AutoSellConcurrencyDesc: "Número máximo de recursos que la venta automática puede manejar al mismo tiempo",
    MaxAutoSellConcurrencyReached:
        "Ha alcanzado la simultaneidad máxima de venta automática, desactive otra venta automática para habilitar esta",
    CannotSellBuilding: "No se puede vender el edificio en este momento",
    WallStreet: "Mundo financiero",
    MarketCap: "Tapa del mercado",
    MarketCapDesc: "Capitalización de mercado total (i.e. valor de mercado) de tu corporación",
    BuildingValuation: "Valoración de edificios",
    BuildingValuationDesc: "Valor total de sus edificios, incluyendo permisos de construcción y mejoras",
    ResourcesValuation: "Valoración de recursos",
    ResourcesValuationDesc: "Valor total de los recursos en su inventario",
    Battery: "Batería",
    BatteryFactory: "Fábrica de baterías",
    RatingBuy: "Comprar",
    RatingSell: "Vender",
    SwissShop: "Tienda suiza",
    RatingHold: "Mantener",
    RatingOutperform: "Fuera de rendimiento",
    RatingUnderperform: "Bajo rendimiento",
    StockRating: "Calificación de acciones",
    JetEngine: "Motor a reacción",
    Helicopter: "Helicoptero",
    Lithium: "Litio",
    LithiumMine: "Mina de litio",
    LiionBatteryFactory: "Fábrica de baterías de iones de litio",
    HelicopterFactory: "Fábrica de helicópteros",
    Satellite: "Satélite",
    ToyFactory: "Fábrica de juguetes",
    Toy: "Juguete",
    SpaceStation: "Estación Espacial",
    SpaceStationFactory: "Fábrica de la estación espacial",
    OperatingSystem: "Sistema operativo",
    OperatingSystemCompany: "Sistema operativo Inc",
    LinuxDistribution: "Distribución de Linux",
    Internet: "Internet",
    WebBrowser: "Navegador web",
    Console: "Consola",
    ConsoleFactory: "Fábrica de consolas",
    Train: "Tren",
    TrainFactory: "Fábrica de trenes",
    ShoeFactory: "Fábrica de zapatos",
    Shoes: "Zapatos",
    ArtilleryFactory: "Fábrica de artillería",
    Artillery: "Artillería",
    SubmarineFactory: "Fábrica de submarinos",
    Submarine: "Submarino",
    Spaceship: "Astronave",
    RobotFactory: "Fábrica de robots",
    Robot: "Robot",
    SpaceshipFactory: "Fábrica de naves espaciales",
    SatelliteFactory: "Fábrica de satélites",
    JetEngineFactory: "Fábrica de motores a reacción",
    StockRatingDesc:
        "Consenso de calificación de acciones de analistas de Wall Street, que afecta su capitalización de mercado y se actualiza junto con el mercado",
    InterestRate: "Tasa de interés a un día",
    InterestRateDesc: "Intereses que gana sobre su capitalización de mercado mientras está desconectado",
    OfflineEarning: "Ganancia sin conexión",
    OfflineEarningDesc: "Las ganancias sin conexión dependen de su capitalización de mercado y tasa de interés",
    PerMin: "%{amount}/mínimo",
    OfflineEarningTime: "Tiempo de ganancia sin conexión",
    OfflineEarningTimeDesc: "Obtendrá ingresos fuera de línea hasta este umbral",
    BuyPermit: "Permiso de compra",
    NotEnoughBuildingPermit: "No hay suficientes permisos de construcción. Compre más para construir nuevos edificios.",
    MovingAverage: "Media móvil",
    MovingAverageDesc: "Muestra el promedio móvil del cambio de recursos en lugar del cambio en tiempo real",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Activar el soporte de zoom. Usa la rueda del mouse para hacer zoom. El zoom actual es %{zoom}",
    AllowZoomMobileDesc: "Activar el soporte de zoom. Puedes pellizcar para hacer zoom. El zoom actual es %{zoom}",
    Settings: "Ajustes",
    Sound: "Efecto de sonido",
    SoundDesc: "Activar efectos de sonido como clic o sonido de error",
    AutoHighlight: "Resaltado automático",
    AutoHighlightDesc: "Resalte automáticamente edificios del mismo tipo cuando seleccione un edificio",
    MusicDesc: "Enciende la música: It's Not Over 'Til The Bossa Nova de Shane Ivers (https://www.silvermansound.com)",
    Credits: "Creditos",
    Icons: "Iconos",
    MisplacedBuilding: "⛔ Este %{building} no se coloca encima del depósito de recursos correcto",
    Left: "Izquierda",
    Right: "Derecha",
    Auto: "Auto",
    HighlightBuildings: "Destacar edificios",
    HighlightTurnedOff: "...que están apagados",
    HighlightStockpileModeOn: "...que tienen el modo de almacenamiento activado",
    HighlightProductionCycleNotDefault: "...que tienen ciclo de producción > 1",
    HighlightMaxInputDistanceNotDefault: "...que tienen una distancia máxima de entrada < ∞",
    HighlightNotMakingProfit: "...no obtengas ganancias",
    NBuildingsAreHighlighted: "%{n} edificio(s) están resaltados",
    OnlyToWarehouse: "Solo para almacenes",
    OnlyToWarehouseDesc: "Solo los almacenes pueden transportar recursos desde este edificio",
    TurnOffProduction: "Apagar",
    TurnOffProductionDesc:
        "Apague la producción del edificio. El edificio ya no transportará recursos ni utilizará energía.",
    ApplyToAll: "Aplicar a todo %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Ilimitado",
    Transport: "Transporte",
    TileModifier: "Modificador de mosaico",
    ShowAllModifiers: "Mostrar todos los modificadores",
    HideAllModifiers: "Ocultar todos los modificadores",
    NumberOfBuildings: "Cantidad de edificios que tienes",
    ShowContent: "Contenido del show",
    HideContent: "Ocultar contenido",
    BuyExpansionPack: "Comprar por %{price}",
    Cities: "Ciudades",
    InputStrategy: "Estrategia de entrada",
    InputStrategyClose: "Cerca",
    InputStrategyCloseDesc: "Prefiera el almacén más cercano que tenga suficientes recursos",
    InputStrategyFar: "Más lejos",
    InputStrategyFarDesc: "Prefiere el almacén más lejano que tenga suficientes recursos.",
    InputStrategyAmount: "Cantidad",
    InputStrategyAmountDesc:
        "Prefiera el almacén con la mayor cantidad de recursos, independientemente de la distancia.",
    FuelCostSave: "Ahorro de costo de combustible",
    FuelCostSaveDesc:
        "Los almacenes ahorran un cierto porcentaje de combustible para transportar recursos hacia el interior en comparación con otros edificios, cuanto más alto es el nivel, más se ahorra",
    SoftwareCompany: "Compañía de software",
    Software: "Software",
    ScreenFactory: "Fábrica de pantallas",
    Screen: "Pantalla",
    JoinDiscord: "Únase a nuestro servidor de Discord para obtener las últimas actualizaciones, consejos y discusiones",
    ClaimOfflineEarning: "Reclamar ganancias sin conexión",
    OfflineTime: "Tiempo sin conexión",
    Minutes: "%{time}mínimo",
    MaxUpgrade: "Mejora máxima",
    MaxUpgradeDesc: "Has alcanzado la actualización máxima",
    ClaimAmount: "Dinero +%{amount}",
    EarningPerMinute: "Tasa de ganancia",
    EffectiveTime: "Tiempo efectivo",
    EffectiveTimeDesc: "Su tiempo efectivo de ganancia fuera de línea está limitado a %{time}mínimo.",
    BuildSearchPlaceholder: "Escriba edificio o recurso para buscar",
    MineOverlayWarning: "%{building} No se ve afectado por el modificador de mosaico",
    WholesaleCenter: "Centro al por mayor",
    OrderFrom: "Ordenar desde %{name}",
    ExpireIn: "Expira en",
    TurnOnAllProductions: "Producción activada",
    TurnOnAllProductionsDesc:
        "Activar las producciones de todos los edificios, no se puede utilizar cuando la política de ahorro de costes está activa",
    OperationSuccessful: "Esta operación se ha completado con éxito",
    TurnOn: "Encender",
    Reward: "Recompensa",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/ciclo",
    PolicyPoint: "Punto de política",
    PolicyPointPerMinute: "Generate Rate",
    PolicyPointPerMinuteDesc: "Obtienes puntos de política cada minuto en el juego.",
    YourWilLGaimPolicyPoints: "Tu ganarás %{amount} puntos de política en %{time}s",
    PolicyPointDesc: "💡 Cuantas más políticas activas, más costo tiene cada política",
    NextOrderIn: "Siguiente orden en",
    FillOrder: "Completar pedido",
    RejectOrder: "Aprobar",
    WholesaleCenterLocked:
        "Necesitas al menos %{required} diferentes recursos para desbloquear el Centro Mayorista. Tu solo tienes %{current} recuursos",
    OrderFilled: "La orden de %{from} se ha llenado con éxito!",
    PolicyCenter: "Centro de políticas",
    NewOrder: "Un nuevo pedido de %{from} ha llegado, por favor verifique en el Centro Mayorista",
    Policies: "Políticas",
    PolicyNotEnoughTime: "No tiene suficientes puntos de política para esta política",
    TimeLeft: "%{time} Izquierda",
    WholesaleCenterOrderFaster: "Feria Mundial",
    WholesaleCenterOrderFasterDesc:
        "El Centro Mayorista recibe pedidos 2 veces más rápido y el tamaño del pedido es 2 veces mayor",
    PolicyOilWellPowerx2: "Sobrecarga de pozo de petróleo",
    PolicyOilWellPowerx2Desc: "Los pozos de petróleo producen el doble de petróleo y usan el doble de energía",
    HalfTransportSpeed: "Reduzca la velocidad para ahorrar",
    HalfTransportSpeedDesc:
        "La velocidad de transporte se ralentiza en un 25% y el costo de combustible se reduce en un 25%",
    RefineryMoreOil: "Problemas de Mo Petrol Mo",
    RefineryMoreOilDesc: "Las refinerías de petróleo producen un 50% más de gasolina y un 50% menos de plástico",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Los edificios preferirán transportarse desde la fuente anterior, en lugar de buscar la mejor fuente en cada ciclo (POLÍTICA GRATUITA)",
    RefineryMorePlastic: "Mo Plásticos Mo Problemas",
    RefineryMorePlasticDesc: "Las refinerías de petróleo producen un 50% menos de gasolina y un 50% más de plástico",
    FreeOilTransportDesc:
        "El transporte de petróleo no cuesta combustible, pero los pozos de petróleo usan el doble de energía",
    SuperSteelMill: "Corazones de Hierro",
    SuperSteelMillDesc: "Las acerías utilizan un 50% menos de carbón y un 25% más de hierro y un 25% más de energía.",
    AlSemiconductor: "Al circuito",
    AlSemiconductorDesc: "Las fundiciones de circuitos utilizan aluminio en lugar de cobre",
    CostSaver: "Ahorro de costos",
    CostSaverDesc: "Si los insumos de un edificio cuestan más que su producción, cierre la producción",
    CostSaverBuildingDesc:
        "La política de ahorro de costos está activa, la producción se encenderá / apagará automáticamente en función de su rentabilidad",
    CostSaverBuildingWarning: "La política de ahorro de costos está activa, no puede cambiar la producción manualmente",
    GlassUseCoal: "Vidrio negro",
    GlassUseCoalDesc: "Las fábricas de vidrio utilizan un 50% más de carbón y un 50% menos de silicio",
    AdjacentBonusOnlyOutput: "Bono adyacente Plus",
    AdjacentBonusOnlyOutputDesc:
        "La bonificación adyacente no requiere más entrada, pero usa más energía y es solo 50% efectiva",
    IronMine2xOutput: "Hierro pesado",
    IronMine2xOutputDesc:
        "Las minas de hierro producen el doble de hierro, pero el transporte de hierro cuesta el doble de combustible",
    SolarPanelAlwaysWork: "El sol nunca se pone",
    SolarPanelAlwaysWorkDesc: "El panel solar funciona el 100% del tiempo pero produce un 60% menos de energía",
    SteelScience: "Conocimiento a través del acero",
    SteelScienceDesc: "Las acerías utilizan el doble de insumos y producen ciencia adicional",
    WholesaleCenterProducingOnly: "Socios mayoristas",
    WholesaleCenterProducingOnlyDesc:
        "Los pedidos del centro mayorista solo contienen recursos que se están produciendo actualmente (también debe producir la cantidad de recursos necesarios para desbloquear el centro mayorista)",
    ShoppingSpree: "Compra compulsiva",
    ShoppingSpreeDesc:
        "Si la capacidad de producción de un recurso es insuficiente, compre la cantidad que falte en Trade Center automáticamente (si el recurso tiene la venta automática activada, se ignorará)",
    ShoppingSpreeTradeCenterDesc:
        "💡 La política Shopping Spree está activada, Trade Center comprará automáticamente los recursos en escasez",
    ExtraPolicyPoints: "Cabildero político",
    ExtraPolicyPointsDesc: "Aumentar la capacidad de producción de pólizas en un 50%",
    CrAlloyUseFe: "Cromo",
    CrAlloyUseFeDesc: "Las plantas de aleación de cromo no usan litio, sino que usan 2x hierro en su lugar",
    DoubleTileModifier: "Poder de la naturaleza",
    DoubleTileModifierDesc: "El efecto del modificador de todas las fichas x2, tanto positivo como negativo",
    TileModifierOutputOnly: "Editar mosaico plus",
    TileModifierOutputOnlyDesc:
        "Los modificadores de mosaicos solo afectan la salida en lugar de la entrada y la salida, pero solo son efectivos en un 50%",
    GasPlantPetrol: "Licuadora de gas",
    GasPlantPetrolDesc: "Las centrales eléctricas de gas utilizan gas extra para producir gasolina",
    BuildingRecycle: "Reciclaje de edificios",
    BuildingRecycleDesc:
        "Obtenga un reembolso completo cuando venda un edificio dentro de 1 minuto después de la construcción",
    CoalPlantFuel: "Licuadora de carbón",
    CoalPlantFuelDesc: "Las centrales eléctricas de carbón utilizan carbón adicional para producir gasolina",
    Welcome: "Bienvenido",
    SeeTutorialAgain: "Rehacer tutorial",
    HelpTranslateTheGame: "Ayuda a traducir el juego🌐",
    SkipTutorial: "Saltar tutorial",
    NextTutorial: "Próximo",
    Tutorial1:
        "Industry Idle es un juego de <em>Administracion de recursos</em> un juego donde construyes fábricas🏭, para producir bienes📦 y ganar dinero💸.<br><br>Repasemos algunos conceptos básicos para que comiences; no tomará mucho tiempo, lo prometo.",
    Tutorial2:
        "Todos los edificios necesitan energía⚡, usted tiene una <em>turbina eólica</em> que genera poder. Puede ver su fuente de alimentación actual en el lado izquierdo de la barra superior.<br><br>Es posible que haya notado que las turbinas eólicas solo funcionan el <em>80%</em> del tiempo. Puede considerar la construcción de otros tipos de plantas de energía que generen energía estable.",
    Tutorial3:
        "Tienes muchos <em>depósitos de recursos</em> en el mapa. Para extraer recursos, tienes que construir minas ⛏️ <em>sobre</em> el depósito correspondiente.<br><br>Por ejemplo, tienes un <em>pozo petrolífero🛢️</em> que extrae <em>petróleo</em> de un depósito de petróleo.<br></br>Los depósitos son ilimitados - no necesitas preocuparte de quedarte sin recursos. Además de las minas, otros edificios pueden ser construidos en mosaicos vacíos.",
    Tutorial5:
        "Para ganar dinero, debe exportar sus recursos a través del centro comercial. Para hacer esto, simplemente active <em> venta automática </em> para ese recurso. <br> </br> También puede comprar recursos en el centro comercial. Recuerda <em> si compras un recurso, subirás el precio </em> y si vendes un recurso, bajarás el precio. <br> <br> El mercado es <em> volátil </ em > y el precio📈 cambia regularmente.",
    Tutorial6:
        "Para construir nuevos edificios, primero debes desbloquearlo en el <em> laboratorio de investigación🧪 </em>. El laboratorio de investigación también convierte la ciencia en puntos de investigación. <br> <br> Su turbina eólica (y otras plantas de energía) produce una pequeña cantidad de ciencia cuando está en funcionamiento. Y puede construir escuelas🏫 y otros edificios dedicados para impulsar la ciencia más adelante. <br> <br> ¡Ahora que ha aprendido todos los conceptos básicos, comience a desarrollar su economía! Aquí hay algo de <em> efectivo💸 </em> y <em> gasolina⛽ </em> para comenzar.",
    WelcomePlay: "Jugar",
    WelcomePlayMuted: "Reproducir (🔇Music)",
    Changelog: "Registro de cambios",
    ChangelogGotIt: "Entendido",
    Chat: "Chat",
    Send: "Enviar",
    Import: "Importar",
    Export: "Exportar",
    LastBackupAt: "Última copia de seguridad",
    RestoreFromBackup: "Reinstalar desde el respaldo",
    RestoreFromBackupFail:
        "No se pudo restaurar la copia de seguridad de Steam Cloud: ¿estás seguro de que hay una copia de seguridad??",
    RestoreFromBackupTitle: "Estas seguro?",
    RestoreFromBackupDesc:
        "Normalmente no es necesario restaurar desde la copia de seguridad en la nube, a menos que se pierda su guardado local. Las copias de seguridad en la nube son un poco más antiguas que su guardado local",
    ChatMessages: "Mensajes de chat",
    ChangeName: "Cambio",
    SaveName: "Ahorrar",
    NameValidationRule: "Su nombre solo debe contener letras y números y tener entre 5 y 15 caracteres",
    NameValidationRuleProfanity: "Tu nombre no debe contener blasfemias",
    ChatMessageRateLimit: "Solo puedes enviar un nuevo mensaje de chat cada 10 segundos",
    NameSaved: "Tu nombre ha sido cambiado exitosamente",
    NoMessages: "no hay mensajes nuevos",
    Leaderboard: "Tabla de clasificación",
    Name: "Nombre",
    Rank: "Rango",
    Tips1: "Las calificaciones de acciones tienen 5 niveles: compra, rendimiento superior, retención, rendimiento inferior y venta",
    Tips2: "Los edificios dejarán de transportar recursos si ya hay suficientes para la producción, a menos que active el modo de almacenamiento.",
    Tips3: "El costo de combustible para el transporte de recursos está determinado por la distancia y la cantidad de recursos.",
    Tips4: "Los edificios solo transportarán un recurso si la cantidad encontrada en el mapa excede la capacidad de entrada",
    Tips5: "Los edificios solo transportarán un recurso desde el Centro Comercial si la venta automática está desactivada para ese recurso",
    Tips6: "Puede ver el costo de combustible de un recurso en la sección de capacidad de entrada correspondiente",
    Tips7: "Si compra un recurso, aumentará el precio. Si vende un recurso, bajará el precio",
    Tips8: "Puede ver el cuadro de la cantidad de cada recurso y su cambio a lo largo del tiempo en la Oficina de estadísticas",
    Tips9: "Los puntos de investigación necesarios para un edificio están determinados por el precio de mercado de sus recursos de entrada.",
    Tips10: "Los diferentes recursos tienen un precio diferente en el mercado; siempre esté preparado para la volatilidad del mercado",
    Tips11: "Es una buena idea verificar siempre su suministro de energía y combustible antes de expandir su producción.",
    FPS30: "El ahorro de energía",
    OfflineModeDesc:
        "No se puede conectar al servidor: no se generarán ganancias sin conexión. Por favor revise su conexion a internet",
    OptOut: "Optar por no",
    OptIn: "Restablecer y habilitar",
    LeaderboardOptOut: "Exclusión de la tabla de clasificación",
    LeaderboardOptOutDesc:
        "Esto ya no enviará la puntuación de la tabla de clasificación. TENGA EN CUENTA: si desea habilitar la tabla de clasificación más adelante, sus datos deben restablecerse",
    LeaderboardOptIn: "Restablecer y habilitar la tabla de clasificación",
    LeaderboardOptInDesc:
        "Sus datos deben REINICIARSE antes de que pueda volver a habilitar la tabla de clasificación, ¿está seguro?",
    RewardAdsFailed: "El video de recompensa no se completó",
    RewardAdsNotAvailable:
        "El video de recompensa no está disponible (actualmente solo es compatible con iOS / Android)",
    OfflineEarningDoubleSuccess: "Has duplicado tus ingresos sin conexión",
    FPS30Desc:
        "Activar el modo de ahorro de energía ejecutará el juego a 30FPS en lugar de 60FPS. Esto hará que su batería dure más",
    HighlightAll: 'Destacar "%{type}"',
    HighlightInput: "🔍 Destacar %{type} Entrada",
    HighlightOutput: "🔍 Destacar %{type} Salida",
    TotalInput: "Capacidad de entrada total",
    TotalOutput: "Capacidad de salida total",
    RunOutIn: "Salir en %{time}",
    FuelRunOutWarning:
        "💡 Su consumo de combustible supera la producción. Cuando se acabe el combustible, su transporte se detendrá",
    InAmount: "en: %{number}",
    OutAmount: "Afuera: %{number}",
    SwissBank: "Banco suizo",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Si comienzas en una nueva ciudad, obtendrás %{money} 💵",
    RestorePurchases: "Restaurar las compras",
    RestorePurchasesSuccess: "Tus compras han sido restauradas",
    RestorePurchasesFailed: "Tus compras no se restauraron",
    ExpansionPacks: "Paquetes de expansión",
    ExpansionPack1: "Paquetes de expansión 1",
    ExpansionPack1Owned: "Paquete de expansión 1",
    RequireExpansionPack1: "Paquete de expansión 1",
    RequireExpansionPack1Desc: "Esto solo está disponible para Expansion Pack 1",
    RequireAnyExpansionPack: "Paquetes de expansión exclusivos",
    RequireAnyExpansionPackDesc: "Esta función requiere que tengas al menos uno de los paquetes de expansión.",
    HideRewardAd: "Ocultar anuncios recompensados",
    HideRewardAdDesc:
        "Todos los anuncios del juego son anuncios recompensados opcionales. Esto ocultará todas las opciones de anuncios recompensados del juego..",
    HideDiscordBanner: "Ocultar estandarte de discordia",
    HideDiscordBannerDesc: "Ocultar Discord y banner de escaparate en la sede",
    HideChat: "Ocultar mensaje de chat",
    SortedByDeficit: "Ordenada por déficit",
    PurchaseFailed: "La compra no se completó",
    PurchaseSteamContinue: "Termina tu compra en Steam",
    PurchaseSuccess: "La compra se ha completado, gracias por su apoyo.",
    PrestigeCurrency: "Dinero suizo 💵",
    RestartDesc: "💡 Solo quiero reiniciar? Puede tocar Comenzar en una nueva ciudad arriba y elegir su ciudad actual",
    PrestigeGoBack: "Regresar",
    PermanentUpgradeDesc: "Esta actualización se transferirá si comienzas en una nueva ciudad.",
    ProductionMultiplier: "Multiplicador de producción",
    ProductionMultiplierDesc:
        "Un impulso a la capacidad de producción de todos sus edificios (incluidas minas, fábricas, centrales eléctricas, edificios científicos y culturales)",
    FuelCostDiscount: "Descuento en el costo de combustible",
    FuelCostDiscountDesc: "Ofrece un descuento en el costo del combustible al transportar recursos.",
    AutoSellCapacityMultiplier: "Multiplicador de capacidad de venta automática",
    AutoSellCapacityMultiplierDesc:
        "Un multiplicador que se aplica a su capacidad de venta automática independientemente de la capacidad actual",
    BuildingPermitCostDivider: "Divisor de costos de permisos de construcción",
    BuildingPermitCostDividerDesc: "Divida el costo del permiso de construcción por este divisor",
    ExtraAdjacentBonus: "Bono adicional adyacente",
    ExtraAdjacentBonusDesc: "Capacidad adicional adicional para cada edificio de trabajo adyacente del mismo tipo",
    OfflineEarningMultiplier: "Multiplicador de ganancias sin conexión",
    OfflineEarningMultiplierDesc: "Un multiplicador que se aplica a los ingresos fuera de línea.",
    PrestigeAlertTitle: "Estas seguro?",
    PrestigeAlertContent:
        "Su empresa será liquidada. Cobrarás %{amount} Dinero suizo y comenzar una nueva empresa en %{city}",
    PrestigeCurrencyDesc:
        "Este es el dinero en su cuenta bancaria secreta suiza, puede llevarlo con usted cuando comience en una nueva ciudad",
    Prestige: "Dinero en",
    Cancel: "Cancelar",
    SaveFileCorrupted: "Guardar archivo dañado",
    CheatDetected:
        "Su antiguo guardado no pasó la validación del servidor y no se puede leer. Empezarás con un nuevo guardado",
    LoadGameError: "Error al cargar el juego",
    LoadGameErrorMessage: "Mensaje de error: %{message}",
    LoadGameErrorDesc: "Por favor revise su conexion a internet. Si el problema persiste, comuníquese con el soporte",
    ExpansionPackIncompatible:
        "Estás importando un guardado con paquetes de expansión, pero tu juego no tiene los paquetes de expansión requeridos.",
    SaveFileMigrated: "Una nueva era: Beta está aquí",
    SaveFileMigratedDesc:
        "Gracias por jugar las pruebas en alfa. Su mapa anterior no es compatible, pero hemos migrado sus datos y le damos una bonificación.",
    ClaimSwissMoney: "Afirmar %{amount} Dinero suizo 💵",
    SaveFileMigratedFinePrint:
        "Su capitalización de mercado se convierte en dinero suizo y su dinero suizo no gastado se traslada. Obtendrá un 50% de dinero suizo adicional para probar el juego en alfa. El dinero suizo máximo que se puede transferir tiene un límite de 200",
    CashIn: "Dinero en efectivo en",
    CurrentCity: "Ciudad actual",
    CashInDesc:
        "Recibirá esta cantidad en su cuenta bancaria suiza si comienza en una nueva ciudad. Se basa en la capitalización de mercado de su empresa y debe alcanzar %{amount} antes de que puedas ganar dinero suizo",
    MoveToNewMap: "Comience en una ciudad nueva",
    CityName: "Ciudad",
    CitySize: "Tamaño de mapa",
    GridType: "Tipo de cuadrícula",
    StartInThisCity: "Empezar en %{city}",
    CityBonus: "Bono de ciudad",
    ResourceTilePercentage: "Azulejos de recursos",
    MapSquareGrid: "Cuadrado",
    MapHexGrid: "Hex",
    Stockholm: "Estocolmo",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li> Las acerías tienen el doble de capacidad </li> <li> Las plantas de acero inoxidable tienen el doble de capacidad </li> <li> Transporte gratuito de hierro </li> <li> El transporte de acero cuesta un 50% menos de combustible </li> <li> Comience con el doble de capacidad de venta automática </li> <li> Sin modificadores de mosaicos </li> ",
    Oslo: "Oslo",
    StPetersburg: "San Petersburgo",
    Hamburg: "Hamburgo",
    HamburgBonus:
        "<li> Las fábricas de Zeppelin están desbloqueadas </li> <li> Las fábricas de semiconductores tienen el doble de productividad </li> <li> Los astilleros tienen el doble de capacidad </li> <li> Las fábricas de automóviles tienen el doble de capacidad </li> <li> Las fábricas de baterías de iones de litio están desbloqueadas </li> ",
    Toulouse: "Toulouse",
    Rome: "Roma",
    RomeBonus:
        "<li> Los coliseos están desbloqueados </li> <li> Los coliseos tienen el doble de productividad </li> <li> Comience con el centro de políticas de nivel 5 </li> <li> Los teatros de ópera tienen el doble de capacidad </li> <li> Los estudios de grabación también producen cultura </li> ",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li> Comience con el laboratorio de investigación de nivel 5 </li> <li> Las escuelas politécnicas están desbloqueadas </li> <li> Las escuelas politécnicas tienen el doble de capacidad </li> <li> Las escuelas tienen el doble de capacidad </li> <li> Universidad tener el doble de productividad </li> ",
    HideNotProducing: "Ocultar recursos que no son producidos",
    SortByStorage: "Almacenaje",
    SortByProduction: "Producción",
    SortByName: "Nombre",
    PlayerTrade: "Player Trade",
    AddTradeFail: "Failed to add your trade",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Your trade has been added successfully",
    LoadTradeFail: "Failed to load player trades, please try again later",
    ClaimTradeFail: "Failed to claim this trade, please try again later",
    CancelTradeSuccess: "Your trade has been cancelled successfully",
    CancelTradeFail: "Failed to cancel this trade, please try again later",
    AcceptTradeFail: "Failed to accept this trade, please try again later",
    PlayerTradeBanner: "Trade Resources with Other Players",
    PlayerTradeResource: "Resource",
    PlayerTradeAmount: "Amount",
    PlayerTradePrice: "Price $",
    PlayerTradeValue: "Value $",
    PlayerTradeWaiting: "Waiting...",
    UseTradeCenterPrice: "Use Trade Center Price",
    AddTrade: "Add Trade",
    ActiveTrades: "Active Trades",
    AcceptTrade: "Accept",
    CancelTrade: "Cancel",
    RefundTrade: "Refund",
    RefundTradeSuccess: "This trade has been refunded: %{resource} has been refunded to your trade center",
    RefundTradeFail: "Failed to refund this trade, please try again later",
    ClaimTrade: "Reclamar",
    RefreshTrade: "Refrescar",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    FailedToCheckActiveTrade: "Failed to check active player trades, please try again later",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeValidRange: "Rango: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Can Afford",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transport and store any resources and with lower fuel cost",
    PowerBankChargeSpeed: "Charge Speed",
    PowerBankPowerLeft: "Power Left",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ExcludeBuildingsShutdown: "Excluir edificios que están desactivados",
    ColorTheme: "Game Color Theme",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Industrial Revolution",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "This will hide resource movement (those tiny dots) by default and only show the movement when you select a building",
    PowerBankLeft: "Power Bank",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Guardar",
    ColorThemeEditorReset: "Reiniciar",
    ColorThemeEditorResetAll: "Reiniciar Todo",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "Solo puedes aceptar un intercambio cada %{time} segundos",
    DowngradeBuilding: "Degradar",
    CancelTradeConfirmDialogTitle: "Cancel This Trade?",
    CancelTradeConfirmDialogYes: "Sí",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Agregar Ruta",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Encontrar en el Mapa",
    WarehouseRemoveRoute: "Remover",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Superávit",
    Production: "Producción",
    Consumption: "Consumo",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Player Flag",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    WarehouseOutwardFuelSave: "Free Delivery",
    WarehouseOutwardFuelSaveDesc: "Warehouses provide the same fuel save on outward transportation as well",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Resources tend to spawn in clusters</li><li>Warehouse provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Terms of Service",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Manga Publisher",
    Manga: "Manga",
    AnimeStudio: "Anime Studio",
    Anime: "Anime",
    PlayerTradeAction: "Acción",
    PlayerTradeBuy: "Comprar",
    PlayerTradeSell: "Vender",
    PlayerTradeBid: "Bid",
    PlayerTradeAsk: "Ask",
    CancelTradeConfirmDialogDescV2:
        "Cancelling this trade will refund %{percent} of the resource/cash. Resources will be refunded to Trade Center warehouse",
    ClaimTradeSuccessV2: "Your trade has been claimed successfully: %{cashOrResource}",
    AcceptTradeSuccessV2: "This trade has been accepted by you: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Better Than Market Price",
    ResourceExplorer: "Resource Explorer",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explore",
    ProductionSettings: "Production Settings",
    PlayerTradeQuotaDesc: "💡 Player trade quota is %{percent} of your market cap, it resets when the market updates",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Game Guides",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ShowProfitBreakdown: "Show Profit Breakdown",
    HideProfitBreakdown: "Hide Profit Breakdown",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Fuel Cost",
    BuildingProfit: "Ganancia",
    RestoreBackup: "Restore",
    SteamLogin: "Sign In Through Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Sign In",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "International Export Trade",
    FreeTransportToTradeCenterDesc:
        "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "En Almacén: %{amount}",
    PlayerTradeFillValue: "Valor",
    FiberFactory: "Fiber Factory",
    Fiber: "Fiber",
    Achievements: "Logros",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Reward: Swiss Money +%{swiss}",
    AchievementsRewardToast: "You have claimed the reward:  Swiss Money +%{swiss}",
    AchievementsClaim: "Claim",
    AchievementsToast: "You have achieved %{name}, claim your reward in Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Force Steam Cloud Sync",
    UILoading: "Cargando...",
    UserAuthenticated: "You are authenticated",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Déficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardBySwissPerBuilding: "Current Swiss Money Per Building",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Save and Exit Game",
    SaveAndExitDesc:
        "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Force Scroll",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ResourceExplorer2Desc: "Resource explorers produce 2x output but use 2x power",
    ConstructionCancel: "Cancel Construction",
    ConstructionPause: "Pause",
    ConstructionResume: "Resume",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
    HighlightUnderConstruction: "...that haven't been constructed",
    HighlightUnderLevel10: "...por debajo del nivel 10",
    HighlightUnderLevel20: "...por debajo del nivel 20",
    HighlightUnderLevel30: "...por debajo del nivel 30",
    Logout: "You Are Logged Out",
    ConstructionStatusQueueingV2: "Encolando",
    ConstructionStatusPausedV2: "Pausado",
    ConstructionStatusBuildingV2: "Construyendo",
    ConstructionStatusUnpaidV2: "Impago",
    ConstructionStatus: "Estado de Construcción",
    ConstructionStart: "Iniciar",
    CostFree: "Gratis",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Solo tu",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "incrementado por %{percent}",
    MarketNewsDecrease: "decrementado por %{percent}",
    MarketNewsBuilding: "Este edificio es afectado por %{num} noticia(s)",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    OsloBonusV2:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Conferencia de prensa",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Resource Booster",
    BuildWarningTitle: "Building Might Not Work",
    BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
    BuildWarningBuildAnyway: "Build Anyway",
    ResourceBoosterNotWorking: "⛔ Resource boosters only work next to deposit mines",
    ResourceBoosterPercentage: "💡 This building gets %{percent} output boost from adjacent resource boosters",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
    BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "Have 50 production lines that has production deficit",
    UseScientificNotation: "Use Scientific Notation",
    UseScientificNotationDesc: "Use scientific notation (e notation) for numbers larger than 999.9T",
    LogoutDescV2:
        "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
    LogBackIn: "Log Back In",
    PlayerTradeNowAllowedV2: "Player trades are not available within %{hour} hours of restoring/importing a save",
    ServerDisconnected:
        "You are disconnected from the server, please check your internet connection and restart the game",
    BuildingUpgradeCostDividerDescV2: "Divide building upgrade cost by this divider",
    ResourceBoosterBannerDesc:
        "💡 You currently have %{number} resource boosters - the power and science input of each is scaled to the number of resource boosters you currently have",
    ResourceBoosterDesc: "Boost the output of adjacent mines",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Dynamite Factory",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Nuclear Missile Factory",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Space Colony",
    SpaceColonyInc: "Space Colony",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    IronSteelZone: "Iron Steel Zone",
    IronSteelZoneDesc:
        "Resource booster provide a %{percent} output bonus to adjacent steel mills or stainless steel plants for each working iron mine it is boosting",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
    ToulouseBonusV2:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
};
