export const FR = {
    Translator: "Traducteur",
    TranslatorName: "Picault Lucas, Gilgemann Inès",
    Language: "Langue",
    ThisLanguage: "Français",
    OK: "OK",
    SteelMill: "Aciérie",
    StainlessSteelPlant: "Usine d'acier inoxydable",
    CircuitFoundry: "Fonderie de circuits intégré",
    IntegratedCircuit: "Circuit intégré",
    OilWell: "Puits de pétrole",
    Wood: "Bois",
    LoggingCamp: "Camp de bûcherons",
    LumberMill: "Scierie",
    Lumber: "Planches",
    Paper: "Papier",
    PaperMill: "Papeterie",
    Book: "Livre",
    BookPublisher: "Éditeur de livres",
    OilRefinery: "Raffinerie de pétrole",
    Sell: "Vendre",
    Upgrade: "Améliorer",
    Build: "Construire",
    Inspect: "Inspecter",
    Buildings: "Bâtiments",
    Iron: "Fer",
    Actions: "Actions",
    FuelType: "Choisissez le carburant",
    FuelCost: "Coût du carburant",
    FuelConsumption: "%{fuel} Consommation",
    FuelEconomy: "Économie de carburant",
    FuelProduction: "%{fuel} Production",
    FuelInStorage: "%{fuel} En stock",
    Plastic: "Plastique",
    FuelSurplus: "%{fuel} Surplus",
    Petrol: "Pétrole Raffiné",
    Buy: "Acheter",
    NoLiquidity: "Plus d'argent",
    NoLiquidityTurnOffAutoSell:
        "Il n'y a pas assez de d'argent sur le marché pour %{res}, la vente automatique a été désactivée",
    Multiplier: "Multiplicateur",
    MultiplierDesc: "Tous les 10 niveaux, vous obtenez x2 multiplicateur",
    SellBuilding: "Vendre un bâtiment",
    PowerGrid: "Réseau électrique",
    TradeAmount: "Montant de la transaction",
    SortBy: "Trier par",
    SortByPrice: "Prix",
    SortByAmount: "Quantité",
    NotEnoughResourcesForTrade: "Pas assez de ressource(s) dans le centre d'échange pour ce commerce",
    NotEnoughResources: "Pas assez de ressources pour cette opération",
    Transportation: "Transport",
    Cash: "Argent",
    Aluminum: "Aluminium",
    ResearchPoint: "Point de recherche",
    Unlock: "Ouvrir",
    BuildingUnlocked: "%{building} a été déverrouillé",
    Science: "Science",
    ScienceFromPowerDesc:
        "Les centrales électriques produisent une petite quantité de science lors de la production d'électricité",
    Culture: "Culture",
    School: "École",
    University: "Université",
    Polytechnic: "Polytechnique",
    Colosseum: "Colisée",
    WindTurbine: "Éolienne",
    Engine: "Moteur",
    EngineFactory: "Usine de moteurs",
    CameraFactory: "Usine d'appareil photo",
    Camera: "Appareil photo",
    Gun: "Arme à feu",
    GunFactory: "Usine d'armes à feu",
    Aircraft: "Avion",
    AircraftFactory: "Usine aéronautique",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Usine de Zeppelin",
    Tank: "Chars de combat",
    TankFactory: "Usine de chars de combat",
    CoalPowerPlant: "Centrale électrique au charbon",
    PetrolPowerPlant: "Centrale électrique à pétrole",
    Copper: "Cuivre",
    Gas: "Gaz naturel",
    GasPump: "Pompe à gaz naturel",
    GasPowerPlant: "Centrale électrique à gaz",
    Missile: "Missile",
    MissileFactory: "Usine de missiles",
    Rocket: "Fusée",
    RocketFactory: "Usine de fusées",
    BuildingPermit: "Permis de construire",
    BuildingPermitDesc:
        "Vous avez %{amount} permis de construction, vous avez déjà construit %{amountBuilt} bâtiments et il vous en reste %{amountLeft}",
    BuildingLocked:
        "Le bâtiment n'est pas encore disponible, vous devez d'abord le déverrouiller dans le laboratoire de recherche",
    BuildQueue: "Créer une file d'attente",
    BuildQueueDesc: "Nombre de bâtiments actuellement en file d'attente",
    MaxBuilders: "Max constructeurs",
    MaxBuildersDesc: "Nombre de bâtiments que vous pouvez construire en même temps",
    Silicon: "Silicium",
    AluminumMine: "Mine d'aluminium",
    CopperMine: "Mine de cuivre",
    SiliconMine: "Mine de silicium",
    IronMine: "Mine de fer",
    CoalMine: "Mine de charbon",
    Headquarter: "Siège social",
    ResearchLab: "Laboratoire de recherche",
    TradeCenter: "Centre d'échange",
    Resources: "Ressources",
    NotEnoughPower: "💡 Pas assez de puissance, pensez à augmenter l'alimentation électrique",
    NotEnoughFuel: "Pas assez d'%{fuel} pour cette opération",
    NotEnoughCash: "Pas assez d'argent pour cette opération",
    NotEnoughSwissMoney: "Pas assez de Franc Suisse pour cette opération",
    BuildingNotEnoughFuel: "💡 Pas assez %{fuel}",
    AutoSell: "Vente automatique",
    SellAll: "Tout vendre",
    Change: "Changement",
    StatisticsBureau: "Bureau des statistiques",
    LogisticsDepartment: "Département de logistique",
    From: "De",
    Top20FuelCost: "Top 20 des coûts de carburant",
    To: "À",
    TransportTime: "Temps de transport",
    TopN: "Haut %{n}",
    Warehouse: "Entrepôt",
    TradeWarehouse: "Entrepôt de Vente",
    Coal: "Charbon",
    Video: "Vidéo",
    ClothingFactory: "Usine de vêtements",
    Clothes: "Vêtements",
    Fashion: "Mode",
    FashionFactory: "Fabrique de mode",
    VideoFarm: "Ferme a vidéo",
    SantaFactory: "Usine du Père Noël",
    Santa: "Père Noël",
    Car: "Voiture",
    CarFactory: "Usine automobile",
    Ship: "Bateau",
    SolarPanel: "Panneau solaire",
    SolarPanelDesc:
        "💡 Les panneaux solaires ne fonctionnent que 5 secondes toutes les 10 secondes - tous les cycles sont alignés",
    WindTurbineDesc:
        "💡 Les éoliennes ne fonctionnent que 8 secondes toutes les 10 secondes - les cycles ne sont pas alignés",
    Movie: "Film",
    MovieStudio: "Studio de cinéma",
    Sitcom: "Sitcom",
    TVStudio: "Studio de télévision",
    PC: "PC",
    GameStudio: "Studio de jeux vidéo",
    Game: "Jeu vidéo",
    ComputerFactory: "Usine d'ordinateurs",
    Shipyard: "Chantier naval",
    PowerUsage: "Consommation d'énergie",
    PowerSupply: "Source de courant",
    PowerSurplus: "Surplus de courant",
    Level: "Niveau",
    Power: "Energie",
    CentralBank: "Banque centrale",
    ResourceInput: "Entrée",
    ResourceOutput: "Sortie",
    ResourceStorage: "Stockage",
    ResourceChange: "Echanger",
    ResourceInOutDesc:
        "💡 Appuyez sur les numéros Entrée-Sortie ci-dessus pour mettre en évidence les bâtiments de sortie et d'entrée correspondants",
    ResourceChart: "Tableau des ressources",
    MarketUpdateIn: "Mise à jour du marché dans %{time}",
    Income: "Revenu",
    Semiconductor: "Semi-conducteur",
    SemiconductorFactory: "Usine de semi-conducteurs",
    Steel: "Acier",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Ferme à Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Ferme à Dogecoin",
    Guitar: "Guitare",
    GuitarFactory: "Usine de guitares",
    Drum: "Batterie",
    DrumFactory: "Usine de batteries",
    RecordingStudio: "Studio d'enregistrement",
    OperaHouse: "Opéra",
    CoalGasificationPlant: "Usine de gazéification du charbon",
    GasProcessingPlant: "Usine de traitement de gaz",
    Music: "Musique",
    Glass: "Verre",
    PhoneFactory: "Usine de téléphones",
    Phone: "Téléphone",
    GlassFactory: "Usine de verre",
    Oil: "Pétrole Brut",
    Chromium: "Chrome",
    ChromiumMine: "Mine de chrome",
    Uranium: "Uranium",
    EnrichedUranium: "Uranium enrichi",
    NuclearPowerPlant: "Centrale nucléaire",
    UraniumEnrichmentPlant: "Usine d'enrichissement d'uranium",
    UraniumMine: "Mine d'uranium",
    Titanium: "Titane",
    TitaniumMine: "Mine de titane",
    TitaniumAlloyPlant: "Usine d'alliage de titane",
    ChromiumAlloyPlant: "Usine d'alliage de chrome",
    Input: "Entrée",
    PanelPosition: "Position du panneau",
    PanelPositionDesc:
        "Afficher le panneau latéral à gauche, à droite ou automatique (dépend de la vignette actuellement sélectionnée)",
    InputCapacity: "Capacité d'entrée",
    InputCapacityPerCycle: "Capacité d'entrée/cycle",
    Output: "Sortie",
    OutputCapacity: "Capacité de sortie",
    OutputCapacityPerCycle: "Capacité/cycle de sortie",
    ResourceDeposit: "Dépôt de ressources",
    RecommendedBuilding: "💡 Cette tuile a %{resource} déposer",
    AdjacentBonus: "Bonus adjacent",
    AdjacentBonusDesc: "Vous obtenez %{bonus}% capacité supplémentaire pour chaque bâtiment adjacent du même type",
    ConsiderIncreaseProduction: "💡 Pensez à augmenter %{resource} production",
    AlwaysTransportInput: "Mode de stockage",
    AlwaysTransportInputTradeCenter: "Toujours exporter",
    AlwaysTransportInputTradeCenterDesc:
        "Transportez toujours les ressources vers le centre d'échange, même si la vente automatique n'est pas activée pour cette ressource",
    AlwaysTransportInputDesc:
        "Transportez toujours les ressources d'entrée, même si elles dépassent les exigences de production minimales",
    ProductionCycleLength: "Cycle de production",
    ProductionCycleLengthDesc:
        "Durée d'un cycle de production, mesurée en secondes. L'allongement du cycle augmentera les entrées / sorties par cycle, diminuant ainsi sa priorité lors de la récupération des ressources d'entrée",
    MaxInputDistance: "Distance d'entrée maximale",
    MaxInputDistanceDesc:
        "La distance maximale à partir de laquelle ce bâtiment peut récupérer les ressources d'entrée, mesurée en nombre de tuiles",
    AutoSellCapacity: "Capacité de vente automatique",
    AutoSellCapacityDesc:
        "Quantité maximale de ressources que la vente automatique peut gérer par seconde et par ressource",
    CurrentAutoSellCapacityMultiplier: "Multiplicateur actuel: x%{n}",
    AutoSellConcurrency: "Nombre de vente automatique",
    AutoSellConcurrencyDesc: "Nombre maximum de ressources que la vente automatique peut gérer en même temps",
    MaxAutoSellConcurrencyReached:
        "Vous avez atteint le nombre maximal de ventes automatiques, désactivez une autre vente automatique pour activer celle-ci",
    CannotSellBuilding: "Impossible de vendre le bâtiment pour le moment",
    WallStreet: "Wall Street",
    MarketCap: "Capital en bourse",
    MarketCapDesc: "Capital en bourse total (Valeur marchande) de votre société",
    BuildingValuation: "Évaluation du bâtiment",
    BuildingValuationDesc: "Valeur totale de vos bâtiments, y compris les permis de construire et les améliorations",
    ResourcesValuation: "Évaluation des ressources",
    ResourcesValuationDesc: "Valeur totale des ressources de votre inventaire",
    Battery: "Piles",
    BatteryFactory: "Usine de piles",
    RatingBuy: "Acheter",
    RatingSell: "Vendre",
    SwissShop: "Boutique suisse",
    RatingHold: "Prise",
    RatingOutperform: "Surpasser",
    RatingUnderperform: "Sous-performance",
    StockRating: "Évaluation du stock",
    JetEngine: "Moteur à réaction",
    Helicopter: "Hélicoptère",
    Lithium: "Lithium",
    LithiumMine: "Mine de lithium",
    LiionBatteryFactory: "Usine de batteries Li-ion",
    HelicopterFactory: "Usine d'hélicoptères",
    Satellite: "Satellite",
    ToyFactory: "Usine de jouets",
    Toy: "Jouet",
    SpaceStation: "Station spatiale",
    SpaceStationFactory: "Usine de la station spatiale",
    OperatingSystem: "Système opérateur",
    OperatingSystemCompany: "Système d'exploitation Inc",
    LinuxDistribution: "Distribution Linux",
    Internet: "Internet",
    WebBrowser: "Navigateur Web",
    Console: "Console",
    ConsoleFactory: "Usine de consoles",
    Train: "Train",
    TrainFactory: "Usine de trains",
    ShoeFactory: "Usine de chaussures",
    Shoes: "Chaussures",
    ArtilleryFactory: "Usine d'artilleries",
    Artillery: "Artillerie",
    SubmarineFactory: "Usine de sous-marins",
    Submarine: "Sous-marin",
    Spaceship: "Vaisseau spatial",
    RobotFactory: "Usine de robots",
    Robot: "Robot",
    SpaceshipFactory: "Usine de vaisseaux spatiaux",
    SatelliteFactory: "Usine de satellites",
    JetEngineFactory: "Usine de moteurs à réactions",
    StockRatingDesc:
        "Le consensus de notation des actions des analystes de Wall Street, qui affecte votre capitalisation boursière est mis à jour avec le marché",
    InterestRate: "Taux d'intérêt par jour",
    InterestRateDesc: "L'intérêt que vous gagnez sur votre capital en bourse lorsque vous êtes hors ligne",
    OfflineEarning: "Gains hors ligne",
    OfflineEarningDesc: "Les gains hors ligne dépendent de votre capital en bourse et de votre taux d'intérêt",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Temps de gain hors ligne",
    OfflineEarningTimeDesc: "Vous gagnerez des revenus hors ligne jusqu'à avoir atteind ce seuil",
    BuyPermit: "Acheter un permis",
    NotEnoughBuildingPermit:
        "Pas assez de permis de construire. Veuillez en acheter plus pour construire de nouveaux bâtiments",
    MovingAverage: "Moyenne mobile",
    MovingAverageDesc: "Afficher la moyenne mobile du changement des ressources au lieu du changement en temps réel",
    AllowZoom: "Zoom",
    AllowZoomDesc:
        "Activez la prise en charge du zoom. Utilisez la molette de votre souris pour zoomer. Le zoom actuel est %{zoom}",
    AllowZoomMobileDesc:
        "Activez la prise en charge du zoom. Vous pouvez pincer pour zoomer. Le zoom actuel est %{zoom}",
    Settings: "Paramètres",
    Sound: "Effet sonore",
    SoundDesc: "Activer les effets sonores comme le clic ou le son d'erreur",
    AutoHighlight: "Mise en évidence automatique",
    AutoHighlightDesc:
        "Mettez automatiquement en surbrillance les bâtiments du même type lorsque vous sélectionnez un bâtiment",
    MusicDesc:
        "Allumez la musique: 'It's Not Over 'Til The Bossa Nova' de Shane Ivers (https://www.silvermansound.com)",
    Credits: "Crédits",
    Icons: "Icônes",
    MisplacedBuilding: "⛔ Le %{building} n'est pas placé au-dessus du bon gisement de ressources",
    Left: "Gauche",
    Right: "Droite",
    Auto: "Auto",
    HighlightBuildings: "Mettre en évidence les bâtiments",
    HighlightTurnedOff: "...qui sont éteints",
    HighlightStockpileModeOn: "...dont le mode de stockage est activé",
    HighlightProductionCycleNotDefault: "...qui ont un cycle de production > 1",
    HighlightMaxInputDistanceNotDefault: "...qui ont une distance d'entrée maximale < ∞",
    HighlightNotMakingProfit: "...ne fais pas de profit",
    NBuildingsAreHighlighted: "%{n} bâtiment(s) sont mis en évidence",
    OnlyToWarehouse: "Uniquement pour les entrepôts",
    OnlyToWarehouseDesc: "Seuls les entrepôts peuvent transporter des ressources depuis ce bâtiment",
    TurnOffProduction: "Désactiver",
    TurnOffProductionDesc:
        "Arrêtez la production du bâtiment. Le bâtiment ne transportera plus de ressources et n'utilisera plus d'électricité",
    ApplyToAll: "S'applique à tous %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Illimité",
    Transport: "Transport",
    TileModifier: "Modificateur de tuile",
    ShowAllModifiers: "Afficher tous les modificateurs",
    HideAllModifiers: "Masquer tous les modificateurs",
    NumberOfBuildings: "Nombre de bâtiments dont vous disposez",
    ShowContent: "Montrer le contenu",
    HideContent: "Masquer le contenu",
    BuyExpansionPack: "Acheter pour %{price}",
    Cities: "Villes",
    InputStrategy: "Stratégie d'entrée",
    InputStrategyClose: "Le plus proche",
    InputStrategyCloseDesc: "Préférez l'entrepôt le plus proche qui dispose de suffisamment de ressources",
    InputStrategyFar: "Le plus loin",
    InputStrategyFarDesc: "Préférez l'entrepôt le plus éloigné qui dispose de suffisamment de ressources",
    InputStrategyAmount: "La quantité",
    InputStrategyAmountDesc:
        "Préférez l'entrepôt avec la plus grande quantité de ressources, quelle que soit la distance",
    FuelCostSave: "Économisez sur le coût du carburant",
    FuelCostSaveDesc:
        "Les entrepôts économisent un certain pourcentage de carburant pour le transport des ressources vers l'intérieur par rapport aux autres bâtiments, plus le niveau est élevé, plus l'économie est importante",
    SoftwareCompany: "Société de logiciels",
    Software: "Logiciel",
    ScreenFactory: "Usine d'écrans",
    Screen: "Écran",
    JoinDiscord: "Rejoignez notre serveur Discord pour les dernières mises à jour, conseils et discussions",
    ClaimOfflineEarning: "Réclamer des gains hors ligne",
    OfflineTime: "Temps hors ligne",
    Minutes: "%{time}min",
    MaxUpgrade: "Mise à niveau maximale",
    MaxUpgradeDesc: "Vous améliorez au niveau maximum",
    ClaimAmount: "Espèces +%{amount}",
    EarningPerMinute: "Taux de gain",
    EffectiveTime: "Temps effectif",
    EffectiveTimeDesc: "La durée effective de vos gains hors connexion est plafonnée à %{time}min.",
    BuildSearchPlaceholder: "Sélectionner le bâtiment ou la rechercher",
    MineOverlayWarning: "%{building} n'est pas affecté par le modificateur de tuile",
    WholesaleCenter: "Centre de vente en gros",
    OrderFrom: "Commande de %{name}",
    ExpireIn: "Expire dans",
    TurnOnAllProductions: "Production active",
    TurnOnAllProductionsDesc:
        "Activer les productions de tous les bâtiments, ne peut pas être utilisé lorsque la politique d'économie de coûts est active",
    OperationSuccessful: "Cette opération a été effectuée avec succès",
    TurnOn: "Allumer",
    Reward: "Récompense",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cycle",
    PolicyPoint: "Point de stratégie",
    PolicyPointPerMinute: "Taux de génération",
    PolicyPointPerMinuteDesc: "Vous gagnez des points de stratégie à chaque minute du jeu",
    YourWilLGaimPolicyPoints: "Vous gagnerez %{amount} points de stratégie dans %{time}s",
    PolicyPointDesc: "💡 Plus les stratégies sont actives, plus le coût de chaque stratégie est élevé",
    NextOrderIn: "Prochaine commande dans",
    FillOrder: "Remplir la commande",
    RejectOrder: "Passer",
    WholesaleCenterLocked:
        "Vous avez besoin d'au moins %{required} différentes ressources pour débloquer le centre de vente. Vous avez seulement %{current} resources",
    OrderFilled: "La commande de %{from} a été remplie avec succès!",
    PolicyCenter: "Centre de stratégie",
    NewOrder: "Une nouvelle commande de %{from} est arrivée, veuillez vous enregistrer dans ",
    Policies: "Stratégies",
    PolicyNotEnoughTime: "Vous ne disposez pas de suffisamment de points de stratégie pour cette stratégie",
    TimeLeft: "%{time} restant",
    WholesaleCenterOrderFaster: "Exposition mondiale",
    WholesaleCenterOrderFasterDesc:
        "Le centre de vente reçoit les commandes 2 fois plus rapidement et la taille de la commande est 2 fois plus grande",
    PolicyOilWellPowerx2: "Puits de pétrole suralimenté",
    PolicyOilWellPowerx2Desc: "Les puits de pétrole produisent 2x de pétrole et utilisent 2x de courant",
    HalfTransportSpeed: "Ralentissez pour économiser",
    HalfTransportSpeedDesc: "La vitesse de transport est ralentie de 25% et le coût du carburant est réduit de 25%",
    RefineryMoreOil: "Plus d'essence, moins de problèmes",
    RefineryMoreOilDesc: "Les raffineries de pétrole produisent 50% plus d'essence et 50% moins de plastique",
    StickyInput: "Entrée collante",
    StickyInputDesc:
        "Les bâtiments préféreront transporter à partir de la source précédente, au lieu de rechercher la meilleure source à chaque cycle (STRATEGIE GRATUITE)",
    RefineryMorePlastic: "Plus de plastique, moins de problèmes",
    RefineryMorePlasticDesc: "Les raffineries de pétrole produisent 50% moins d'essence et 50% plus de plastique",
    FreeOilTransportDesc:
        "Le transport de pétrole ne coûte pas de carburant mais les puits de pétrole consomment 2 fois plus de puissance",
    SuperSteelMill: "Coeurs de fer",
    SuperSteelMillDesc: "Les aciéries utilisent 50% moins de charbon et 25% plus de fer et 25% plus d'énergie",
    AlSemiconductor: "Circuit AI",
    AlSemiconductorDesc: "Les fonderies de circuits utilisent de l'aluminium au lieu du cuivre",
    CostSaver: "Économiseur de coûts",
    CostSaverDesc: "Si les intrants d'un bâtiment coûtent plus cher que sa production, arrêtez la production",
    CostSaverBuildingDesc:
        "La politique d'économie de coûts est active, la production s'activera / s'éteindra automatiquement en fonction de sa rentabilité",
    CostSaverBuildingWarning:
        "La politique d'économie de coûts est active, vous ne pouvez pas modifier manuellement la production",
    GlassUseCoal: "Verre noir",
    GlassUseCoalDesc: "Les usines de verre utilisent 50% plus de charbon et 50% moins de silicium",
    AdjacentBonusOnlyOutput: "Plus de bonus adjacent",
    AdjacentBonusOnlyOutputDesc:
        "Le bonus adjacent ne nécessite pas plus d'entrée mais utilise plus de puissance et n'est efficace qu'à 50%",
    IronMine2xOutput: "Fer lourd",
    IronMine2xOutputDesc:
        "Les mines de fer produisent 2 fois le fer mais le transport du fer coûte 2 fois le carburant",
    SolarPanelAlwaysWork: "Le soleil ne se couche jamais",
    SolarPanelAlwaysWorkDesc: "Le panneau solaire fonctionne 100% du temps mais produit 60% moins d'énergie",
    SteelScience: "La connaissance à travers l'acier",
    SteelScienceDesc: "Les aciéries utilisent 2x intrants et produisent des données scientifiques supplémentaires",
    WholesaleCenterProducingOnly: "Partenaires du centre de vente",
    WholesaleCenterProducingOnlyDesc:
        "Les commandes des centres ne contiennent que des ressources en cours de production (vous devez également produire le nombre de ressources nécessaires pour déverrouiller le centre de vente)",
    ShoppingSpree: "Virée shopping",
    ShoppingSpreeDesc:
        "Si la capacité de sortie d'une ressource est insuffisante, achetez automatiquement le montant de la pénurie auprès du centre d'échange (si la ressource est vendue automatiquement, elle sera ignorée)",
    ShoppingSpreeTradeCenterDesc:
        "💡 La politique virée shopping est activée, Le centre d'échange achètera automatiquement les ressources en pénurie",
    ExtraPolicyPoints: "Lobbyiste stratégique",
    ExtraPolicyPointsDesc: "Augmenter de 50% la capacité de production des points stratégiques",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Les usines d'alliage de chrome n'utilisent pas de lithium mais utilisent plutôt 2x fer",
    DoubleTileModifier: "Le pouvoir de la nature",
    DoubleTileModifierDesc: "Effet du modificateur de toutes les tuiles x2 - à la fois positif et négatif",
    TileModifierOutputOnly: "Modificateur de tuile Plus",
    TileModifierOutputOnlyDesc:
        "Les modificateurs n'affectent que la sortie au lieu de l'entrée et de la sortie, mais ne sont efficaces qu'à 50%",
    GasPlantPetrol: "Liquificateur de gaz",
    GasPlantPetrolDesc: "Les centrales au gaz utilisent du gaz supplémentaire pour produire de l'essence",
    BuildingRecycle: "Recyclage du bâtiment",
    BuildingRecycleDesc:
        "Obtenez un remboursement complet lorsque vous vendez un bâtiment dans la minute qui suit la construction",
    CoalPlantFuel: "Charbon liquide",
    CoalPlantFuelDesc: "Les centrales au charbon utilisent du charbon supplémentaire pour produire de l'essence",
    Welcome: "Bienvenue",
    SeeTutorialAgain: "Refaire le didacticiel",
    HelpTranslateTheGame: "Aide pour traduire le jeu🌐",
    SkipTutorial: "Passer le tutoriel",
    NextTutorial: "Suivant",
    Tutorial1:
        "Industry Idle est un jeu <em>de gestion des ressources</em> où vous construisez des usines🏭, produire des biens📦 et gagner de l'argent💸.<br><br>Passons en revue quelques concepts de base pour vous aider à bien démarrer - cela ne prendra pas longtemps, je le promets.",
    Tutorial2:
        "Tous les bâtiments ont besoin d'électricité ⚡,you have une <em>éolienne</em> qui génère de l'énergie. Vous pouvez voir votre alimentation électrique actuelle en haut a gauche.<br><br> Vous avez peut-être remarqué que les éoliennes ne fonctionnent que <em>80%</em> du temps. Vous pouvez envisager de construire d'autres types de centrales électriques qui génèrent une énergie stable.",
    Tutorial3:
        "Vous avez beaucoup de <em>gisements de ressources</em> sur la carte. Pour extraire des ressources, ⛏️ il faut construire des mines <em>au dessus de</em> le dépôt correspondant.<br><br>Par exemple, vous avez un <em>puits de pétrole🛢️</em> qui extrait de <em>huile</em> d'un gisement de pétrole.<br></br>Les dépôts de ressources sont illimités - pas besoin de s'inquiéter de leur épuisement. En dehors des mines, d'autres bâtiments peuvent être construits sur n'importe quelle tuile vide.",
    Tutorial5:
        "Pour gagner de l'argent, vous devez exporter vos ressources via le centre d'échange. Pour ce faire, activez simplement <em>vente auto</em> pour cette ressource.<br></br>Vous pouvez également acheter des ressources au centre commercial. Se souvenir <em>si vous achetez une ressource, vous augmenterez le prix</em> et si vous vendez une ressource, vous réduirez le prix.<br><br>Le marché est <em>changant</em> et le prix📈 change régulièrement.",
    Tutorial6:
        "Pour construire de nouveaux bâtiments, vous devez d'abord le déverrouiller dans le <em>Laboratoire de recherche🧪</em>. Le laboratoire de recherche convertit également la science en points de recherche. <br><br>Votre éolienne (et d'autres centrales électriques) produit une petite quantité de science lorsqu'elle fonctionne. Et tu peux construire une école🏫 et d'autres bâtiments dédiés pour stimuler la science plus tard.<br><br>Maintenant que vous avez appris toutes les bases, commencez à bâtir votre économie! Voilà de <em>l'argent💸</em> et du <em>pétrole⛽</em> to give you a jump start.",
    WelcomePlay: "Jouer",
    WelcomePlayMuted: "Jouer (🔇Music)",
    Changelog: "Journal des modifications",
    ChangelogGotIt: "J'ai compris",
    Chat: "Discussion",
    Send: "Envoyer",
    Import: "Importer",
    Export: "Exportation",
    LastBackupAt: "Dernière sauvegarde",
    RestoreFromBackup: "Restorer depuis une sauvegarde",
    RestoreFromBackupFail:
        "Échec de la restauration de la sauvegarde à partir de Steam Cloud: êtes-vous sûr qu'il y a une sauvegarde?",
    RestoreFromBackupTitle: "êtes-vous sûr?",
    RestoreFromBackupDesc:
        "Vous n'avez normalement pas besoin de restaurer à partir d'une sauvegarde cloud, sauf si votre sauvegarde locale est perdue. La sauvegarde dans le cloud est un peu plus ancienne que votre sauvegarde locale",
    ChatMessages: "Messages de chat",
    ChangeName: "Changer",
    SaveName: "Sauvegarder",
    NameValidationRule:
        "Votre nom ne doit contenir que des lettres et des chiffres et comprendre entre 5 et 15 caractères",
    NameValidationRuleProfanity: "Votre nom ne doit pas contenir de grossièretés",
    ChatMessageRateLimit: "Vous ne pouvez envoyer un nouveau message de discussion que toutes les 10 secondes",
    NameSaved: "Votre nom a été modifié avec succès",
    NoMessages: "Aucun nouveau message",
    Leaderboard: "Classement",
    Name: "Nom",
    Rank: "Rang",
    Tips1: "Les notations des actions ont 5 niveaux: acheter, sur-performer, conserver, sous-performer et vendre",
    Tips2: "Les bâtiments arrêteront de transporter des ressources s'il y en a déjà assez pour la production, à moins que vous n'activiez le mode de stockage",
    Tips3: "Le coût du carburant pour le transport des ressources est déterminé par la distance et la quantité de ressources",
    Tips4: "Les bâtiments ne transporteront une ressource que si la quantité trouvée sur la carte dépasse la capacité d'entrée",
    Tips5: "Les bâtiments ne transporteront une ressource du centre d'échange que si la vente automatique est désactivée pour cette ressource",
    Tips6: "Vous pouvez voir le coût du carburant pour une ressource dans la section de capacité d'entrée correspondante",
    Tips7: "Si vous achetez une ressource, vous augmenterez le prix. Si vous vendez une ressource, vous réduirez le prix",
    Tips8: "Vous pouvez voir le graphique pour chaque montant de ressources et son évolution au fil du temps dans le Bureau des statistiques",
    Tips9: "Les points de recherche nécessaires pour un bâtiment sont déterminés par le prix du marché de ses ressources d'entrée",
    Tips10: "Différentes ressources ont un prix différent sur le marché - soyez toujours prêt à faire face aux changements du marché",
    Tips11: "C'est une bonne idée de toujours vérifier votre alimentation en électricité et en carburant avant d'étendre votre production",
    FPS30: "Économie d'énergie",
    OfflineModeDesc:
        "Impossible de se connecter au serveur: les revenus hors ligne ne seront pas générés. S'il vous plait, vérifiez votre connexion internet",
    OptOut: "Se désengager",
    OptIn: "Réinitialiser et activer",
    LeaderboardOptOut: "Désactivation du classement",
    LeaderboardOptOutDesc:
        "Cela n'enverra plus le score du classement. VEUILLEZ NOTER: si vous souhaitez activer le classement plus tard, vos données doivent être réinitialisées",
    LeaderboardOptIn: "Réinitialiser et activer le classement",
    LeaderboardOptInDesc:
        "Vos données doivent être RÉINITIALISÉES avant de pouvoir réactiver le classement, êtes-vous sûr?",
    RewardAdsFailed: "La vidéo de récompense ne s'est pas terminée",
    RewardAdsNotAvailable:
        "La vidéo de récompense n'est pas disponible (actuellement, seul iOS / Android est pris en charge)",
    OfflineEarningDoubleSuccess: "Vous avez doublé vos gains hors ligne",
    FPS30Desc:
        "Activer le mode d'économie d'énergie exécutera le jeu à 30 FPS au lieu de 60 FPS. Cela prolongera la durée de vie de votre batterie",
    HighlightAll: 'Afficher "%{type}"',
    HighlightInput: "🔍 Afficher les entrées de %{type} ",
    HighlightOutput: "🔍 Afficher les sorties de %{type} ",
    TotalInput: "Capacité d'entrée totale",
    TotalOutput: "Capacité de sortie totale",
    RunOutIn: "Sortie dans %{time}",
    FuelRunOutWarning:
        "💡 Votre consommation de carburant dépasse la production. Lorsque le carburant sera épuisé, votre transport s'arrêtera",
    InAmount: "Dans: %{number}",
    OutAmount: "Dehors: %{number}",
    SwissBank: "Banque Suisse",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Si vous commencez dans une nouvelle ville, vous obtiendrez %{money} 💵",
    RestorePurchases: "Restaurer les achats",
    RestorePurchasesSuccess: "Vos achats ont été restaurés",
    RestorePurchasesFailed: "Vos achats n'ont pas été restaurés",
    ExpansionPacks: "Packs d'extension",
    ExpansionPack1: "Pack d'extension 1",
    ExpansionPack1Owned: "Pack d'extension 1 reçu",
    RequireExpansionPack1: "Requiert Pack d'extension 1",
    RequireExpansionPack1Desc: "Ceci n'est disponible que pour le pack d'extension 1",
    RequireAnyExpansionPack: "Packs d'extension exclusifs",
    RequireAnyExpansionPackDesc: "Cette fonctionnalité vous oblige à posséder au moins un des packs d'extension",
    HideRewardAd: "Masquer les annonces avec récompense",
    HideRewardAdDesc:
        "Toutes les publicités dans le jeu sont des publicités avec récompense facultatives. Cela masquera toutes les options publicitaires récompensées du jeu.",
    HideDiscordBanner: "Masquer la bannière Discord",
    HideDiscordBannerDesc: "Masquer Discord et la bannière de la vitrine dans le siège social",
    HideChat: "Masquer les messages du chat",
    SortedByDeficit: "Trié par déficit",
    PurchaseFailed: "L'achat n'a pas abouti",
    PurchaseSteamContinue: "Veuillez terminer votre achat sur Steam",
    PurchaseSuccess: "L'achat est terminé, merci pour votre soutien",
    PrestigeCurrency: "Argent suisse 💵",
    RestartDesc:
        "💡 Vous voulez juste redémarrer? Vous pouvez appuyer sur Démarrer dans une nouvelle ville ci-dessus et choisir votre ville actuelle",
    PrestigeGoBack: "Retourner",
    PermanentUpgradeDesc: "Cette mise à niveau sera reportée si vous commencez dans une nouvelle ville",
    ProductionMultiplier: "Multiplicateur de production",
    ProductionMultiplierDesc:
        "Une augmentation de la capacité de production de tous vos bâtiments (y compris les mines, les usines, les centrales électriques, les bâtiments scientifiques et culturels)",
    FuelCostDiscount: "Remise sur le prix du carburant",
    FuelCostDiscountDesc: "Donne une réduction sur le coût du carburant lors du transport des ressources",
    AutoSellCapacityMultiplier: "Multiplicateur de capacité de vente automatique",
    AutoSellCapacityMultiplierDesc:
        "Un multiplicateur qui est appliqué à votre capacité de vente quelle que soit la capacité actuelle",
    BuildingPermitCostDivider: "Diviseur des coûts de permis de construire",
    BuildingPermitCostDividerDesc: "Divisez le coût du permis de construire par ce diviseur",
    ExtraAdjacentBonus: "Bonus supplémentaire adjacent",
    ExtraAdjacentBonusDesc:
        "Capacité de bonus supplémentaire pour chaque bâtiment en fonctionnement adjacent du même type",
    OfflineEarningMultiplier: "Multiplicateur de gains hors ligne",
    OfflineEarningMultiplierDesc: "Un multiplicateur qui s'applique aux revenus hors connexion",
    PrestigeAlertTitle: "Etes-vous sûr?",
    PrestigeAlertContent:
        "Votre entreprise sera liquidée. Vous encaisserez %{amount} en argent suisse et créerez une nouvelle entreprise à %{city}",
    PrestigeCurrencyDesc:
        "C'est l'argent sur votre compte bancaire suisse secret, vous pouvez l'emporter avec vous lorsque vous commencez dans une nouvelle ville",
    Prestige: "Encaisser",
    Cancel: "Annuler",
    SaveFileCorrupted: "Enregistrer le fichier corrompu",
    CheatDetected:
        "Votre ancienne sauvegarde n'a pas réussi la validation du serveur et ne peut pas être lue. Vous allez commencer avec une nouvelle sauvegarde",
    LoadGameError: "Échec du chargement du jeu",
    LoadGameErrorMessage: "Message d'erreur: %{message}",
    LoadGameErrorDesc:
        "S'il vous plait, vérifiez votre connexion internet. Si le problème persiste, veuillez contacter le support",
    ExpansionPackIncompatible:
        "Vous importez une sauvegarde avec des packs d'extension mais votre jeu ne dispose pas des packs d'extension requis",
    SaveFileMigrated: "Une nouvelle ère: la bêta est arrivée",
    SaveFileMigratedDesc:
        "Merci d'avoir joué aux tests en alpha. Votre ancienne carte n'est pas compatible mais nous avons migré vos données et vous offrons un bonus",
    ClaimSwissMoney: "Réclamer %{amount} CHF 💵",
    SaveFileMigratedFinePrint:
        "Votre capital en bourse est converti en Franc suisse et est reporté si non-dépensé. Vous obtiendrez un bonus de 50% en CHF pour les tests de jeu en alpha. L'argent suisse maximal pouvant être reporté est plafonné à 200",
    CashIn: "Encaisser",
    CurrentCity: "Ville actuelle",
    CashInDesc:
        "Vous obtiendrez ce montant sur votre compte bancaire suisse si vous commencez dans une nouvelle ville. Il est basé sur le capital en bourse de votre entreprise et il doit atteindre %{amount} avant de pouvoir gagner des Franc Suisse",
    MoveToNewMap: "Commencez dans une nouvelle ville",
    CityName: "Ville",
    CitySize: "Taille de la carte",
    GridType: "Type de grille",
    StartInThisCity: "Commencer dans %{city}",
    CityBonus: "Bonus de ville",
    ResourceTilePercentage: "Tuiles de ressources",
    MapSquareGrid: "Carré",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Les aciéries ont une capacité 2x</li><li>Les usines en acier inoxydable ont une capacité 2x</li><li>Transport de fer gratuit</li><li>Le transport de l'acier coûte 50% de carburant en moins</li><li>Commencez avec une capacité de vente automatique 2x</li><li>Aucun modificateur de tuile</li>",
    Oslo: "Oslo",
    StPetersburg: "Saint-Pétersbourg",
    Hamburg: "Hambourg",
    HamburgBonus:
        "<li>Les usines Zeppelin sont déverrouillées</li><li>Les usines de semi-conducteurs ont une productivité 2x</li><li>Les chantiers navals ont une capacité 2x</li><li>Les usines automobiles ont une capacité 2x</li><li>Les usines de batteries Li-ion sont déverrouillées</li>",
    Toulouse: "Toulouse",
    Rome: "Rome",
    RomeBonus:
        "<li>Les Colisée sont déverrouillés</li><li>Les Colisée ont une productivité 2x</li><li>Commencez avec le centre de politique de niveau 5</li><li>Les opéras ont une capacité 2x</li><li>Enregistrement les studios produisent également de la culture</li>",
    Detroit: "Détroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Commencez avec un laboratoire de recherche de niveau 5</li><li>Les écoles polytechniques sont déverrouillées</li><li>Les écoles polytechniques ont une capacité 2x</li><li>Les écoles ont une capacité 2x</li><li>Les universités ont 2x productivité</li>",
    HideNotProducing: "Masquer les ressources qui ne sont pas produites",
    SortByStorage: "Stockage",
    SortByProduction: "Production",
    SortByName: "Nom",
    PlayerTrade: "Échange de Ressources En Ligne",
    AddTradeFail: "Échec de l'ajout de votre échange",
    AddTradeExceedMaximumTrade:
        "Vous ne pouvez avoir que %{number} échanges actifs au maximum, veuillez d'abord réclamer ou annuler l'un d'entre eux",
    AddTradeSuccess: "Votre échange a été ajouté avec succès",
    LoadTradeFail: "Échec du chargement des échanges avec les joueurs, veuillez réessayer plus tard",
    ClaimTradeFail: "Échec de la récupération de cet échange, veuillez réessayer plus tard",
    CancelTradeSuccess: "Votre transaction a été annulée avec succès",
    CancelTradeFail: "Échec de l'annulation de cette transaction, veuillez réessayer plus tard",
    AcceptTradeFail: "Échec de l'acceptation de cet échange, veuillez réessayer plus tard",
    PlayerTradeBanner: "Échangez des ressources avec d'autres joueurs",
    PlayerTradeResource: "Ressource",
    PlayerTradeAmount: "Quantité",
    PlayerTradePrice: "Prix $",
    PlayerTradeValue: "Valeur $",
    PlayerTradeWaiting: "En Attente...",
    UseTradeCenterPrice: "Utiliser le prix du centre d'échange",
    AddTrade: "Ajouter un échange",
    ActiveTrades: "Activer les échanges",
    AcceptTrade: "Accepter",
    CancelTrade: "Annuler",
    RefundTrade: "Remboursement",
    RefundTradeSuccess: "Cet échange a été remboursé: %{resource} a été remboursé à votre centre d'échange",
    RefundTradeFail: "Échec du remboursement de cet échange, veuillez réessayer plus tard",
    ClaimTrade: "Réclamer",
    RefreshTrade: "Recharger",
    PasteYourSave: "Veuillez coller vos données de sauvegarde",
    FailedToImportSave: "Échec de l'importation de la sauvegarde",
    FailedToImportSaveDesc: "Votre fichier de sauvegarde est incompatible ou corrompu: %{error}",
    SaveCopiedToClipboard: "Vos données de sauvegarde ont été copiées dans votre presse-papiers",
    CancelActiveTradeFirst: "Vous avez des échanges actifs, veuillez d'abord les annuler / les réclamer",
    FailedToCheckActiveTrade: "Échec de la vérification des échanges de joueurs actifs, veuillez réessayer plus tard",
    PlayerTradeQuotaExceed: "Cet échange a dépassé votre quota",
    PlayerTradeValidRange: "Entre: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Trop cher",
    PlayerTradeQuota: "Quantité d'échanges restant: %{value}",
    PlayerTradeUnavailable:
        "Vous devez avoir au moins une ressource en production et en stockage avant de pouvoir échanger avec les joueurs",
    PlayerTradeToClaim: "Vous avez %{num} nouveau(x) commerce(s) à réclamer dans le centre d'échange",
    PowerBank: "Batterie",
    PowerBankBuildDesc: "Stockez l'énergie en trop et fournissez de l'électricité en cas de pénurie",
    WarehouseBuildDesc: "le transport et le stockage de toutes les ressources coûte moins de carburant",
    PowerBankChargeSpeed: "Vitesse de charge",
    PowerBankPowerLeft: "Puissance en moins",
    PowerBankMoreCapacity: "Économie d'énergie",
    PowerBankMoreCapacityDesc: "Les batteries se chargent à une vitesse de 50% mais ont 50% de capacité en plus",
    PowerBankNotWorking: "⛔ Les batteries ne fonctionnent qu'à côté d'une centrale électrique",
    ExcludeBuildingsShutdown: "Exclure les bâtiments qui sont fermés",
    ColorTheme: "Thème de couleur du jeu",
    ColorThemeDesc:
        "Thème de couleur pour les icônes de jeu, la mise en évidence, la grille et l'arrière-plan. REQUIERT UN REDEMARAGE",
    SiliconMine2xOutput: "Mine de Silicium",
    SiliconMine2xOutputDesc:
        "Les mines de silicium produisent 2x silicium mais utilisent 50% de plus d'électricité et le transport du silicium coûte 50% de plus de carburant",
    CoalMine2xOutput: "Mine de charbon",
    CoalMine2xOutputDesc:
        "Les mines de charbon produisent 2x charbon mais utilisent 50% de plus d'électricité et le transport du charbon coûte 50% de plus de carburant",
    AlMine2xOutput: "Mine d'Aluminium",
    AlMine2xOutputDesc: "Les mines d'aluminium produisent 2x aluminium mais utilisent 2x plus d'électricité",
    LoggingCamp2xOutput: "Chantier forestier",
    LoggingCamp2xOutputDesc: "Les camps forestiers produisent 2x bois mais utilisent 2x plus de carburant",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "Cela masquera le mouvement des ressources (ces petits points) par défaut et n'affichera le mouvement que lorsque vous sélectionnez un bâtiment",
    PowerBankLeft: "Stockage d'énergie",
    ColorThemeEditor: "Editeur de la couleur du thème",
    ColorThemeEditorDesc:
        "Vous pouvez remplacer des couleurs dans le thème actuel. Vous avez actuellement %{num} changement(s).",
    ColorThemeEditorSave: "Sauvegarder",
    ColorThemeEditorReset: "Réinitialiser",
    ColorThemeEditorResetAll: "Tout réinitialiser",
    NewMessageMentions: "Un nouveau message vous mentionne : %{message}",
    HideChatMentions: "Masquer les mentions du chat",
    HideChatMentionsDesc: "Masquer la bulle de notification et rendre muet lorsqu'un message du chat me mentionne",
    PendingConstructionCannotReload: "Vous avez une construction de bâtiment en cours, le jeu ne peut pas recharger",
    AcceptTradeFailRateLimit: "Vous pouvez seulement accepter un échange toutes les %{time} secondes",
    DowngradeBuilding: "Rétrograder",
    CancelTradeConfirmDialogTitle: "Annuler cet échange?",
    CancelTradeConfirmDialogYes: "Oui",
    CancelTradeConfirmDialogNo: "Non",
    WarehouseInputRoutes: "Routes d'entrée",
    WarehouseAddInput: "Ajouter Route",
    WarehouseTapToSelect: "Cliquez sur la carte pour sélectionner...",
    WarehouseFindOnMap: "🔍 Trouver sur la carte",
    WarehouseRemoveRoute: "Enlever",
    WarehouseAddRouteFail: "Échec de l'ajout de l'itinéraire: la case sélectionnée n'est pas une source valide",
    LevelN: "Niveau %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consommation",
    WarehouseInputCapacityDescV2: "Capacité totale de transport entrant, répartie également entre tous les itinéraires",
    WarehouseInputCapacityPerRoute: "Par Route: ",
    PlayerCountryFlag: "Drapeau du joueur",
    PlayerCountryChooseFlag: "Par ordre alphabétique des indicatifs de pays",
    WindTurbineAlwaysWork: "Le vent se lève",
    WindTurbineAlwaysWorkDesc: "Les éoliennes fonctionnent 100% du temps mais produisent 30% d'énergie en moins",
    BookPublisherScience: "Littérature scientifique",
    BookPublisherScienceDesc: "Les éditeurs de livres produisent de la science au lieu de la culture",
    WarehouseOutwardFuelSave: "Livraison gratuite",
    WarehouseOutwardFuelSaveDesc:
        "Les entrepôts offrent également la même économie de carburant sur le transport aller",
    ImportSaveVersionTooNew:
        "Vous importez une sauvegarde de %{saveVersion} mais votre jeu est en %{gameVersion}. Veuillez d'abord mettre à jour votre jeu",
    BatteryFuelEconomy: "Batterie rechargeable",
    BatteryFuelEconomyDesc: "Le carburant via les batteries s'améliore de 100% (soit 50% du coût du carburant)",
    ShowTheoreticalInputOutputCapacity: "Afficher la capacité d'entrée/sortie théorique",
    SpecialTransportCost: "Ressources avec un coût de transport spécial",
    FreeTransportCost: "Ressources avec frais de transport gratuits",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Les ressources ont tendance à apparaître en groupe </li><li>L'entrepôt offre 50% d'économie de carburant en plus</li><li>Bâtiment unique: éditeur de mangas</li><li>Bâtiment unique: studio d'anime</li><li>Les usines de semi-conducteurs ont une productivité 2x</li><li>Les usines de batteries Li-ion ont une capacité 2x</li><li>Les usines de batteries sont déverrouillées</li><li>Les usines de batteries ont une capacité 2x</li><li>L'économie de carburant de la batterie s'améliore de 100%</li><li>Les usines de batteries ne nécessitent pas de charbon</li><li>Commencez avec 100K de batteries</li>",
    HideChatDescV2:
        "Masquer le message de chat dans la barre d'outils inférieure. En affichant les messages de chat, vous acceptez nos ",
    HideChatDescV2ToS: "Conditions d'utilisation",
    IntegratedCircuitFab: "Usine de Circuit intégrés",
    MangaPublisher: "Éditeur de manga",
    Manga: "Manga",
    AnimeStudio: "Studio d'animés",
    Anime: "Animé",
    PlayerTradeAction: "Action",
    PlayerTradeBuy: "Acheter",
    PlayerTradeSell: "Vendre",
    PlayerTradeBid: "Offre",
    PlayerTradeAsk: "Demander",
    CancelTradeConfirmDialogDescV2:
        "L'annulation de cet échange entraînera le remboursement de %{pourcent} des ressources/argents. Les ressources seront restituées à l'entrepôt du Trade Center.",
    ClaimTradeSuccessV2: "Votre transaction a été réalisée avec succès : %{cashOrResource}",
    AcceptTradeSuccessV2: "Cet échange a été accepté par vous : %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Meilleur que le prix du marché",
    ResourceExplorer: "Explorateur de ressources",
    ResourceExplorerDesc: "Permet d'extraire des ressources d'un carreau de carte vide.",
    ResourceExplorerDescLong:
        "💡 Les explorateurs de ressources ne bénéficient pas du bonus adjacent. L'utilisation de l'énergie diffère selon la ressource",
    ResourceExplorerSelectResource: "Explorez",
    ProductionSettings: "Paramètres de production",
    PlayerTradeQuotaDesc:
        "💡 Le quota d'échange des joueurs est de %{percent} de votre plafond de marché, il est réinitialisé lors des mises à jour du marché.",
    PlayerTradePartialFillTitle: "Choisissez le pourcentage de remplissage",
    PlayerTradeAmountNotValidV2: "Le montant minimum de transaction autorisé est de 1",
    PlayerTradeOptOut:
        "Vous avez choisi de ne pas figurer au classement, vous ne pouvez pas échanger avec d'autres joueurs",
    FirstTimeReadGuide:
        "💡 Vous avez besoin d'un peu d'aide pour savoir comment jouer ? Cliquez pour lire le guide du débutant !",
    ReadSteamGuideV2: "Guides de jeu",
    ReadSteamGuideV2Desc:
        "Vous pouvez lire les guides créés par la communauté sur Steam - et vous pouvez également créer les vôtres",
    ChatMessageTooLong: "Votre message de chat a dépassé le nombre maximal de caractères autorisé",
    ChatPlaceholderV2: "Tapez votre message: max %{length} chars",
    ShowProfitBreakdown: "Afficher l'améilloration des bénéfices",
    HideProfitBreakdown: "Masquer cassage des bénéfices",
    ProfitBreakdownOutput: "%{res} Sortie",
    ProfitBreakdownInput: "%{res} Entrée",
    ProfitBreakdownFuel: "Le coût du carburant",
    BuildingProfit: "Profit",
    RestoreBackup: "Restaurer",
    SteamLogin: "Connectez-vous via Steam",
    SteamLoginDialogDesc:
        "Votre sauvegarde locale a activé le pack d'extension, vous devez vous connecter via Steam pour continuer. Ou vous pouvez EFFACER VOTRE SAUVEGARDE LOCALE et recommencer",
    SteamLoginDesc:
        "Si vous possédez des packs d'extension sur Steam, vous pouvez jouer avec des packs d'extension sur le Web après vous être connecté",
    SteamLoginYes: "Connexion",
    SteamLoginNo: "Effacer et recommencer",
    KungFuDojo: "Dojo de Kung-Fu",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Dojo de Tai-Chi",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Commerce international d'exportation",
    FreeTransportToTradeCenterDesc:
        "Le transport vers le centre commercial ne coûte pas de carburant, mais le transport depuis le centre commercial coûte 50% de carburant en plus",
    TaiChi10xCulture: "Perle de l'Orient",
    PlayerTradeYouHave: "En stock : %{amount}",
    PlayerTradeFillValue: "Valeur",
    FiberFactory: "Usine de fibres",
    Fiber: "Fibre",
    Achievements: "Succès",
    AchievementsDesc: "Vous avez réalisé %{number} de %{total} réalisations",
    AchievementsReward: "Récompense : +%{swiss} CHF 💵",
    AchievementsRewardToast: "Vous avez réclamé la récompense : +%{swiss} CHF 💵",
    AchievementsClaim: "Réclamer",
    AchievementsToast: "Vous avez atteint %{name}, réclamez votre récompense au quartier général",
    AchievementStockholm100: "Viking débutant",
    AchievementStockholm100Desc: "Gagner 100 Franc Suisse à Stockholm en une seule partie",
    AchievementStockholm500: "Viking diplômé",
    AchievementStockholm500Desc: "Gagner 500 Franc Suisse à Stockholm en une seule partie",
    AchievementStockholm1000: "Viking expérimenté",
    AchievementStockholm1000Desc: "Gagnez 1000 Franc Suisse à Stockholm en une seule partie",
    AchievementOslo100: "Hobbyiste du pétrole norvégien",
    AchievementOslo100Desc: "Gagner 100 Franc Suisse à Oslo en une seule partie",
    AchievementOslo500: "Enthousiaste du pétrole norvégien",
    AchievementOslo500Desc: "Gagner 500 Franc Suisse à Oslo en une seule partie",
    AchievementOslo1000: "Magnat du pétrole norvégien",
    AchievementOslo1000Desc: "Gagner 1000 Franc Suisse à Oslo en une seule partie",
    AchievementRotterdam100: "Propriétaire de moulinet",
    AchievementRotterdam100Desc: "Gagner 100 Franc Suisse à Rotterdam en une seule partie",
    AchievementRotterdam500: "Propriétaire du moulin à vent",
    AchievementRotterdam500Desc: "Gagner 500 Franc Suisse à Rotterdam en une seule partie",
    AchievementRotterdam1000: "Propriétaire d'éoliennes",
    AchievementRotterdam1000Desc: "Gagner 1000 Franc Suisse à Rotterdam en une seule partie",
    AchievementDetroit100: "Concessionnaire automobile local",
    AchievementDetroit100Desc: "Gagner 100 Franc Suisse à Detroit en une seule partie",
    AchievementDetroit500: "Distributeur régional de voitures",
    AchievementDetroit500Desc: "Gagner 500 Franc Suisse à Detroit en une seule partie",
    AchievementDetroit1000: "Monopole national de l'automobile",
    AchievementDetroit1000Desc: "Gagner 1000 Franc Suisse à Detroit en une seule partie",
    AchievementBoston100: "Licence du prolétariat",
    AchievementBoston100Desc: "Gagner 100 Franc Suisse à Boston en une seule partie",
    AchievementBoston500: "Master du gain d'argent",
    AchievementBoston500Desc: "Gagner 500 Franc Suisse à Boston en une seule partie",
    AchievementBoston1000: "Doctorat en impression d'argent",
    AchievementBoston1000Desc: "Gagner 1000 Franc Suisse à Boston en une seule partie",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Gagner 100 Franc Suisse à Rome en une seule partie",
    AchievementRome500: "Constantin Ier",
    AchievementRome500Desc: "Gagner 500 Franc Suisse à Rome en une seule partie",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Gagner 1000 Franc Suisse à Rome en une seule partie",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Gagner 100 Franc Suisse à Hamburg en une seule partie",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Gagner 500 Franc Suisse à Hamburg en une seule partie",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Gagner 1000 Franc Suisse à Hamburg en une seule partie",
    AchievementToulouse100: "Avion de ligne A310",
    AchievementToulouse100Desc: "Gagner 100 Franc Suisse à Toulouse en une seule partie",
    AchievementToulouse500: "Avion de ligne A330",
    AchievementToulouse500Desc: "Gagner 500 Franc Suisse à Toulouse en une seule partie",
    AchievementToulouse1000: "Avion de ligne A380",
    AchievementToulouse1000Desc: "Gagner 1000 Franc Suisse à Toulouse en une seule partie",
    AchievementHongKong100: "Trader amateur",
    AchievementHongKong100Desc: "Gagner 100 Franc Suisse à Hong Kong en une seule partie",
    AchievementHongKong500: "Courtier professionnel",
    AchievementHongKong500Desc: "Gagner 500 Franc Suisse à Hong Kong en une seule partie",
    AchievementHongKong1000: "Gestionnaire de fonds spéculatifs",
    AchievementHongKong1000Desc: "Gagner 1000 Franc Suisse à Hong Kong en une seule partie",
    AchievementStPetersburg100: "Le Grand Duc",
    AchievementStPetersburg100Desc: "Gagner 100 Franc Suisse à St. Petersburg en une seule partie",
    AchievementStPetersburg500: "Le Tsesarevich",
    AchievementStPetersburg500Desc: "Gagner 500 Franc Suisse à St. Petersburg en une seule partie",
    AchievementStPetersburg1000: "Le Tsar de toute la Russie",
    AchievementStPetersburg1000Desc: "Gagner 1000 Franc Suisse à St. Petersburg en une seule partie",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Gagner 100 Franc Suisse à Osaka en une seule partie",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Gagner 500 Franc Suisse à Osaka en une seule partie",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Gagner 1000 Franc Suisse à Osaka en une seule partie",
    SteamAutoCloudBackup: "Sauvegarde automatique de Steam Cloud",
    SteamAutoCloudBackupFailed: "Échec de la sauvegarde automatique de Steam Cloud: %{error}",
    SteamManualBackup: "Forcer la synchronisation de Steam Cloud",
    UILoading: "Chargement...",
    UserAuthenticated: "Vous êtes authentifié",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Déficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "QG du réseau social",
    SocialNetwork: "Réseau social",
    DatabaseCompany: "Société de bases de données",
    Database: "Base de données",
    SatelinkInc: "QG de la liaison satellite",
    GameStationInc: "Siège social des consoles de jeux",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Usine de porte-avions",
    AircraftCarrier: "Porte-avions",
    MapExclusive: "Exclusif à la carte",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc:
        "Les usines de fabrication de voitures utilisent des batteries à la place de l'essence et ne nécessitent que 50 % de la quantité.",
    HongKongBonusV2:
        "<li>Algorithme unique d'évaluation du marché - les prix et la cote des actions suivent une distribution normale (courbe en cloche)</li><li>Les mises à jour du marché et les réinitialisations des quotas commerciaux sont deux fois plus fréquentes (toutes les heures).</li><li>Les recherches peuvent être débloquées via les ressources échangées</li><li>Bâtiment unique : Dojo de kung-fu</li><li>Bâtiment unique : Tai-Chi Dojo</li><li>Augmentation de 50 % du nombre maximal de transactions autorisées pour les joueurs actifs</li><li>Commencez avec une vente automatique de plus</li><li>Politique unique : Commerce international d'exportation</li><li>Politique unique : Perle de l'Orient</li><li>Le centre de vente en gros ne nécessite que 4 ressources pour être déverrouillé</li><li>Débutez avec 100M d'argent liquide.</li>",
    TaiChi10xCultureDescV2:
        "Transports gratuits pour le Kung-fu et le Tai-chi. Les studios de cinéma ont une capacité multipliée par deux mais consomment 50 % d'énergie en plus.",
    SettingsFullScreen: "Plein écran",
    SettingsFullScreenDesc: "Exécutez le jeu en mode plein écran. Disponible uniquement pour la version Steam",
    LeaderboardByAllPrestigeCurrency: "Argent suisse gagné en tout temps",
    LeaderboardByCash: "Liquidités actuelles",
    LeaderboardBySwissPerBuilding: "Argent suisse actuel par bâtiment",
    LeaderboardTotalValuation: "Valeur totale",
    LeaderboardDescV2: "Voir où se trouvent les meilleurs joueurs",
    LastUpdatedAt: "Dernière mise à jour à",
    DetroitBonusV3:
        "<li>Les usines de moteurs sont débloquées</li><li>Les usines de moteurs ont une productivité 2x</li><li>Les usines de voitures ont une capacité 2x</li><li>Les usines de voitures utilisent le gaz au lieu de l'essence</li><li>Le transport gratuit des voitures</li><li>La politique de Nikola Tesla est gratuite</li><li>Les usines de trains ont une capacité 2x</li>",
    SaveAndExit: "Sauvegarder et quitter le jeu",
    SaveAndExitDesc:
        "Sauvegarder et quitter le jeu. Cette fonction n'est disponible que sur la version Steam et fait la même chose que le bouton de fermeture de la barre des fenêtres.",
    AutoSellResourceWarningShortLabel: "💡Vente automatique",
    AutoSellResourceWarningDesc:
        "Vous vendez automatiquement cette ressource, la quantité stockée dans le Trade Center ne peut être utilisée ici.",
    PlayerTradeLocalPrice: "Prix local: %{price}",
    ChatForceScroll: "Défilement auto",
    ChatForceScrollDesc:
        "Si le défilement auto est activé, le chat défilera chaque fois qu'il y aura un nouveau message. Sinon, il ne défilera que si vous êtes déjà en bas de la page.",
    ResourceExplorer2: "Explorateur de ressources 2.0",
    ResourceExplorer2Desc:
        "Les explorateurs de ressources produisent deux fois plus mais utilisent deux fois plus d'énergie.",
    ConstructionCancel: "Annuler la construction",
    ConstructionPause: "Pause",
    ConstructionResume: "Reprendre",
    PolicyBlueprint: "Plan de construction",
    PolicyBlueprintDesc:
        "La construction d'un bâtiment ne démarre pas automatiquement - elle doit être lancée manuellement (STRATÉGIE GRATUITE)",
    HighlightUnderConstruction: "...qui n'ont pas été construits",
    HighlightUnderLevel10: "...qui sont en dessous du niveau 10",
    HighlightUnderLevel20: "...qui sont en dessous du niveau 20",
    HighlightUnderLevel30: "...qui sont en dessous du niveau 30",
    Logout: "Vous êtes déconnecté",
    ConstructionStatusQueueingV2: "Mise en attente",
    ConstructionStatusPausedV2: "En pause",
    ConstructionStatusBuildingV2: "En construction",
    ConstructionStatusUnpaidV2: "Impayé",
    ConstructionStatus: "État de la construction",
    ConstructionStart: "Démarrage",
    CostFree: "Gratuit",
    PlaceBlueprint: "Placer un plan de construction est gratuit",
    PlayerTradePriceNotValidV2: "Le prix de la transaction doit être compris entre %{min} et %{max}.",
    MarketNews: "Actualités du marché",
    MarketNewsApplyToYou: "Seulement vous",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Mettre en évidence",
    MarketNewsFilterInput: "Toutes les entrées %{res} ",
    MarketNewsFilterOutput: "Toutes les sorties %{res} ",
    MarketNewsFilterBoth: "Toutes les entrées et sorties de %{res} ",
    MarketNewsIncrease: "Augmenté de %{percent}",
    MarketNewsDecrease: "Diminué de %{percent}",
    MarketNewsBuilding: "Ce bâtiment est affecté par %{num} nouvelles",
    StockholmBonusV2:
        "<li>Bâtiment unique : producteur de musique</li><li>Les camps d'exploitation forestière ont une productivité 2x</li><li>Les papeteries sont déverrouillées</li><li>Les fonderies de circuits ont une productivité 2x</li><li>La politique de littérature scientifique est gratuite</li>",
    OsloBonusV2:
        "<li>Les raffineries de pétrole sont débloquées</li><li>Les raffineries de pétrole ont une capacité de 2x.</li><li>la statégie Transport électrique du pétrole brut est gratuit</li><li>Les usines de traitement du gaz ont une capacité de 2x</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Transport électrique du pétrole brut",
    Tutorial4P1:
        "Le transport des ressources coûte du carburant. Il existe plusieurs types de carburant et vous utilisez actuellemnt le <em>pétrole raffiné⛽</em> comme carburant. Vous avez une <em>raffinerie de pétrole</em> qui transporte le pétrole brut du puits de pétrole et produit du pétrole raffiné.<br><br>Les minuscules <em>points</em> mobiles représentent le mouvement en temps réel des ressources. Vous devez optimiser l'emplacement de vos bâtiments pour minimiser la distance de déplacement.<br><br><em>La mise à niveau</em> de vos bâtiments augmentera leur rendement, mais aussi leur consommation d'énergie et les entrées nécessaires.",
    Tutorial4P2:
        " Vous pouvez changer votre type de carburant dans le <em>Département de logistique🚦</em> - sur cette carte, vous pouvez également utiliser le <em>gaz naturel</em> comme carburant.<br><br>Le Département de logistique montre également vos routes de transport qui brûlent le plus de carburant - vous voudrez garder un œil dessus. <br><br>N'oubliez pas de <em>vous assurer que votre production de carburant est supérieure à la consommation</em>, sinon votre production s'arrêtera lorsque vous serez à court de carburant.<br><br>Si cela se produit, ne vous inquiétez pas, vous pouvez acheter du carburant d'urgence au Centre d'échange ou auprès d'autres joueurs",
    Tutorial5P2:
        "Le <em>Bureau des statistiques📊</em> fournit un bon aperçu de votre production. Vous pouvez voir une ventilation détaillée de vos entrées et sorties de ressources.<br><br>Il y a également beaucoup de graphiques utiles📈 - vous voudrez vous y référer lorsque vous équilibrez votre production.<br></br>Vos indicateurs d'<em>argent💰, de surplus d'énergie⚡ et de surplus de carburant⛽</em> sont également affichés dans le coin supérieur gauche - si l'un d'entre eux devient rouge, vous devriez chercher à savoir ce qui se passe.",
    MusicProducer: "Producteur de musique",
    PlasticFiber: "Fibre plastique",
    PlasticFiberDesc: "Les usines de fibres utilisent 50 % de plastique en plus, mais 50 % de verre en moins.",
    NewsEffectx2: "Conférence de presse",
    NewsEffectx2Desc: "L'effet des nouvelles du marché double, tant positif que négatif",
    SellRefundPercentage: "Remboursement de la vente/rétrogradation",
    SellRefundPercentageDesc:
        "Si vous vendez ou déclassez un bâtiment, voici le pourcentage d'argent et de ressources qui vous est remboursé",
    SellBuildingDescV2:
        "La vente d'un bâtiment vous remboursera %{percent} de votre investissement et %{percent} des ressources seront transportées vers le Trade Center.",
    BuilderMoveSpeed: "Vitesse de déplacement du constructeur",
    BuilderMoveSpeedDesc: "La vitesse à laquelle les constructeurs se déplacent pour construire des bâtiments",
    EBookInc: "Siège social",
    ResourceBooster: "Booster de ressources",
    BuildWarningTitle: "Le bâtiment pourrait ne pas fonctionner",
    BuildWarningTitleDesc: "%{reason}. Vous êtes sûr de vouloir construire sur cette tuile?",
    BuildWarningBuildAnyway: "Construire quand même",
    ResourceBoosterNotWorking: "⛔ Les boosters de ressources ne fonctionnent qu'à côté des mines de dépôt",
    ResourceBoosterPercentage:
        "💡 Ce bâtiment reçoit %{percent} d'augmentation de rendement des boosters de ressources adjacents.",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "Franc Suisse gagné depuis le début: %{number}",
    BuildingUpgradeCostDivider: "Diviseur de coûts pour l'amélioration des bâtiments",
    AchievementSoftwareGiant: "Géants du numérique",
    AchievementSoftwareGiantDesc:
        "Construisez une société de logiciels de niveau 10, une société de systèmes d'exploitation de niveau 10, une société de bases de données de niveau 10 et un navigateur Web de niveau 10 sur la même carte.",
    AchievementSpaceRace: "Course à l'espace",
    AchievementSpaceRaceDesc:
        "Construire une usine de fusées de niveau 10, une usine de satellites de niveau 10, une usine de vaisseaux spatiaux de niveau 10 et une usine de stations spatiales de niveau 10 sur la même carte.",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Construisez une ferme Bitcoin de niveau 40 et une ferme Dogecoin de niveau 40. Posséder 1B Bitcoin et 1B Dogecoin",
    ItsAllGreen: "C'est tout vert",
    ItsAllGreenDesc: "Disposer de 50 lignes de production et d'aucun déficit de production",
    DeepInRed: "Rouge profond",
    DeepInRedDesc: "Avoir 50 lignes de production qui ont un déficit de production",
    UseScientificNotation: "Utiliser la notation scientifique",
    UseScientificNotationDesc: "Utiliser la notation scientifique (notation e) pour les nombres supérieurs à 999,9T",
    LogoutDescV2:
        "Vous vous êtes connecté sur un autre appareil, cet appareil est déconnecté. Vous pouvez vous reconnecter mais l'autre appareil sera déconnecté.",
    LogBackIn: "Se reconnecter",
    PlayerTradeNowAllowedV2:
        "Les échanges de joueurs ne sont pas disponibles dans les %{hour} heures qui suivent la restauration/importation d'une sauvegarde.",
    ServerDisconnected:
        "Vous êtes déconnecté du serveur, veuillez vérifier votre connexion Internet et redémarrer le jeu.",
    BuildingUpgradeCostDividerDescV2: "Divisez le coût d'amélioration du bâtiment par ce diviseur",
    ResourceBoosterBannerDesc:
        "💡 Vous avez actuellement %{number} boosters de ressources - la puissance et l'apport scientifique de chacun sont mis à l'échelle du nombre de boosters de ressources dont vous disposez actuellement.",
    ResourceBoosterDesc: "Augmenter la production des mines adjacentes",
    BlockUserChatTitle: "Bloquer %{user}",
    BlockUserChatAction: "Bloquer",
    BlockUserChatDesc:
        "Le blocage sera effectif pendant cette session de jeu et vous ne pourrez pas l'annuler à moins de relancer le jeu",
    ChangeNameCooldown: "Vous ne pouvez changer votre nom qu'une fois toutes les %{hour} heures",
    AtomicBombFactory: "Usine de bombes atomiques",
    AtomicBomb: "Bombe atomique",
    DynamiteFactory: "Usine de dynamites",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Usine de missiles nucléaires",
    NuclearMissile: "Missile nucléaire",
    LiquidPropellantFactory: "Usine de propergols liquide",
    GasPropellantFactory: "Usine de propergols gazeux",
    Propellant: "Propergol",
    ProjectV2: "Projet V-2",
    ICBMFactory: "Usine de missiles intercontinentals",
    ICBM: "Missile intercontinental",
    RadarFactory: "Usine de radars",
    Radar: "Radar",
    SpaceForceCommand: "Centre des forces spatiales",
    SpaceForce: "Force spatiale",
    SteamAutoCloudBackupDescV2:
        "Votre dernière progression est enregistrée sur Steam Cloud et synchronisée sur tous les appareils. Le jeu sauvegarde également votre sauvegarde toutes les 10 minutes automatiquement sur Steam Cloud. Vous pouvez forcer une sauvegarde à tout moment",
    SpaceColony: "Colonie spatiale",
    SpaceColonyInc: "Centre de colonie spatiale",
    ProjectVostok: "Projet Vostok",
    AdjacentBonusSquare: "Bonus de tuille adjacente",
    AdjacentBonusSquareDesc:
        "Le bonus adjacent est 50 % plus efficace, mais les modificateurs de tuiles vont de -15 % à +15 %.",
    ResourceBoosterSquare: "Boosters de ressources amélioré",
    ResourceBoosterSquareDesc:
        "Les boosters de ressources fournissent 25% de boost en plus, mais leur apport scientifique et leur consommation d'énergie augmentent également de 25%.",
    SteelMillx2: "Modernisation des fours à acier",
    SteelMillx2Desc:
        "Les aciéries et les usines d'acier inoxydable ont une capacité multipliée par deux mais consomment deux fois plus d'énergie.",
    IronSteelZone: "Zone ferro-acier",
    IronSteelZoneDesc:
        "Le booster de ressources offre un bonus de production de %{percent} aux aciéries ou aux usines d'acier inoxydable adjacentes pour chaque mine de fer en activité qu'il booste.",
    FuelDynamite: "Dynamite fait en carburant",
    FuelDynamiteDesc: "Les usines de dynamite utilisent votre carburant actuel au lieu du pétrole.",
    StPetersburgBonusV2:
        "<li>Les mines d'uranium ont une production multipliée par 2</li><li>Les usines d'enrichissement de l'uranium ont une capacité multipliée par 2</li><li>Le transport de l'uranium coûte 50 % de carburant en moins</li><li>Le transport des armes gratuite</li><li>Le projet Vostok a une capacité multipliée par 2</li>",
    ToulouseBonusV2:
        "<li>Les mines de titane ont une production 2x</li><li>Les usines d'enrichissement de l'uranium ont une productivité 2x</li><li>Les usines de moteurs à réaction ont une capacité 2x</li><li>Les usines d'avions ont une productivité 2x</li><li>Les usines de fusées ont une capacité 2x</li>",
    BuildingPermitsNeededDesc: "Ce bâtiment ne fonctionne pas car vous n'avez pas assez de permis de construire.",
    BuildingPermitsNeeded: "Permis de construire nécessaires",
    BuyMissingPermits: "Acheter les permis manquants",
    GPUIsBusy: "Votre GPU est occupé",
    GPUIsBusyDesc:
        "Votre système d'exploitation a mis en pause les graphiques du jeu car le GPU est occupé à d'autres tâches. Vous pouvez recharger le jeu pour reprendre. Si cela ne fonctionne pas, essayez de redémarrer le jeu",
    SaveAndReloadGame: "Sauvegarder et recharger le jeu",
};
