export const JP = {
    Translator: "翻訳者",
    TranslatorName: "etyucat",
    Language: "言語",
    ThisLanguage: "日本語",
    OK: "OK",
    SteelMill: "製鋼所",
    StainlessSteelPlant: "クロム製鋼材プラント",
    CircuitFoundry: "半導体製IC工場",
    IntegratedCircuit: "IC",
    OilWell: "油井",
    Wood: "原木",
    LoggingCamp: "伐採所",
    LumberMill: "製材所",
    Lumber: "木材",
    Paper: "紙",
    PaperMill: "製紙工場",
    Book: "書籍",
    BookPublisher: "出版社",
    OilRefinery: "製油所",
    Sell: "売却",
    Upgrade: "アップグレード",
    Build: "建築",
    Inspect: "Inspect",
    Buildings: "施設",
    Iron: "鉄",
    Actions: "行動",
    FuelType: "燃料を選択",
    FuelCost: "燃料コスト",
    FuelConsumption: "%{fuel}収支",
    FuelEconomy: "燃費",
    FuelProduction: "%{fuel}生産",
    FuelInStorage: "%{fuel}在庫",
    Plastic: "プラスチック",
    FuelSurplus: "%{fuel}消費",
    Petrol: "ガソリン",
    Buy: "購入",
    NoLiquidity: "流動性なし",
    NoLiquidityTurnOffAutoSell: "%{res}の市場には十分な流動性がないので、自動売却がオフになっています",
    Multiplier: "倍率",
    MultiplierDesc: "10レベルごとに倍率が1上がります",
    SellBuilding: "施設を売却",
    PowerGrid: "電力網",
    TradeAmount: "取引量",
    SortBy: "並び替え",
    SortByPrice: "価格",
    SortByAmount: "数量",
    NotEnoughResourcesForTrade: "このトレードに必要な資源がトレードセンターにありません",
    NotEnoughResources: "この操作に必要な資源がありません",
    Transportation: "輸送手段",
    Cash: "現金",
    Aluminum: "アルミ",
    ResearchPoint: "リサーチポイント",
    Unlock: "ロック解除",
    BuildingUnlocked: "%{building}がアンロックされました",
    Science: "科学",
    ScienceFromPowerDesc: "発電所では発電時に少量の科学が発生する",
    Culture: "カルチャー",
    School: "学校",
    University: "大学",
    Polytechnic: "ポリテク",
    Colosseum: "コロッセオ",
    WindTurbine: "風力発電",
    Engine: "エンジン",
    EngineFactory: "エンジン工場",
    CameraFactory: "カメラ工場",
    Camera: "カメラ",
    Gun: "銃",
    GunFactory: "銃工場",
    Aircraft: "飛行機",
    AircraftFactory: "飛行機工場",
    Zeppelin: "飛行船",
    ZeppelinFactory: "飛行船工場",
    Tank: "戦車",
    TankFactory: "戦車工場",
    CoalPowerPlant: "石炭発電所",
    PetrolPowerPlant: "ガソリン発電所",
    Copper: "銅",
    Gas: "天然ガス",
    GasPump: "天然ガスポンプ",
    GasPowerPlant: "ガス発電所",
    Missile: "ミサイル",
    MissileFactory: "ミサイル工場",
    Rocket: "ロケット",
    RocketFactory: "ロケット工場",
    BuildingPermit: "建築許可証",
    BuildingPermitDesc: "建築許可証 : %{amount} / 建築済み : %{amountBuilt} / 残り : %{amountLeft}",
    BuildingLocked: "建てるにはリサーチラボでアンロックしてください",
    BuildQueue: "建築キュー",
    BuildQueueDesc: "現在キューに入っている施設の数",
    MaxBuilders: "同時建築数",
    MaxBuildersDesc: "同時に建築できる施設の数",
    Silicon: "シリコン",
    AluminumMine: "アルミ採掘場",
    CopperMine: "銅採掘場",
    SiliconMine: "シリコン採掘場",
    IronMine: "鉄採掘場",
    CoalMine: "石炭採掘場",
    Headquarter: "本部",
    ResearchLab: "リサーチラボ",
    TradeCenter: "トレードセンター",
    Resources: "資源",
    NotEnoughPower: "💡電力が足りません。電力供給量の増加を検討してください",
    NotEnoughFuel: "この操作に必要な%{fuel}が不足しています",
    NotEnoughCash: "この操作に必要な現金が不足しています",
    NotEnoughSwissMoney: "この操作に必要なスイスマネーが不足しています",
    BuildingNotEnoughFuel: "💡%{fuel}が足りません",
    AutoSell: "自動売却",
    SellAll: "すべて売却",
    Change: "変更",
    StatisticsBureau: "統計局",
    LogisticsDepartment: "物流センター",
    From: "From",
    Top20FuelCost: "燃料コストトップ20",
    To: "To",
    TransportTime: "輸送時間",
    TopN: "Top%{n}",
    Warehouse: "倉庫",
    TradeWarehouse: "貨物倉庫",
    Coal: "石炭",
    Video: "ビデオ",
    ClothingFactory: "洋服工場",
    Clothes: "洋服",
    Fashion: "ファッション",
    FashionFactory: "ファッション工場",
    VideoFarm: "ビデオファーム",
    SantaFactory: "サンタ工場",
    Santa: "サンタ",
    Car: "自動車",
    CarFactory: "自動車工場",
    Ship: "船",
    SolarPanel: "ソーラーパネル",
    SolarPanelDesc: "💡ソーラーパネルは10秒中5秒しか稼働しません。このサイクルは全施設で同じです",
    WindTurbineDesc: "💡風力発電は10秒中8秒しか稼働しません。このサイクルは各施設で異なります",
    Movie: "映画",
    MovieStudio: "映画スタジオ",
    Sitcom: "番組",
    TVStudio: "テレビスタジオ",
    PC: "PC",
    GameStudio: "ゲームスタジオ",
    Game: "ゲーム",
    ComputerFactory: "PC工場",
    Shipyard: "造船所",
    PowerUsage: "消費電力",
    PowerSupply: "発電量",
    PowerSurplus: "余剰電力",
    Level: "レベル",
    Power: "電力",
    CentralBank: "中央銀行",
    ResourceInput: "In",
    ResourceOutput: "Out",
    ResourceStorage: "ストレージ",
    ResourceChange: "変化",
    ResourceInOutDesc: "💡数字をクリックすると、対応する消費施設・生産施設がハイライトされます",
    ResourceChart: "Resource Chart",
    MarketUpdateIn: "市場価格の更新まで%{time}",
    Income: "Income",
    Semiconductor: "半導体",
    SemiconductorFactory: "半導体工場",
    Steel: "鋼材",
    Bitcoin: "ビットコイン",
    BitcoinFarm: "ビットコインファーム",
    Dogecoin: "ドージコイン",
    DogecoinFarm: "ドージコインファーム",
    Guitar: "ギター",
    GuitarFactory: "ギター工場",
    Drum: "ドラム",
    DrumFactory: "ドラム工場",
    RecordingStudio: "レコーディングスタジオ",
    OperaHouse: "オペラハウス",
    CoalGasificationPlant: "石炭→ガス化プラント",
    GasProcessingPlant: "ガス→プラ化プラント",
    Music: "音楽",
    Glass: "ガラス",
    PhoneFactory: "スマホ工場",
    Phone: "スマホ",
    GlassFactory: "ガラス工場",
    Oil: "原油",
    Chromium: "クロム",
    ChromiumMine: "クロム採掘場",
    Uranium: "ウラン",
    EnrichedUranium: "濃縮ウラン",
    NuclearPowerPlant: "原子力発電所",
    UraniumEnrichmentPlant: "ウラン濃縮プラント",
    UraniumMine: "ウラン採掘場",
    Titanium: "チタン",
    TitaniumMine: "チタン採掘場",
    TitaniumAlloyPlant: "チタン合金プラント",
    ChromiumAlloyPlant: "クロム合金プラント",
    Input: "Input",
    PanelPosition: "パネルポジション",
    PanelPositionDesc: "サイドパネルを左、右、または自動で表示する",
    InputCapacity: "Input Capacity",
    InputCapacityPerCycle: "Input Capacity / Cycle",
    Output: "Output",
    OutputCapacity: "Output Capacity",
    OutputCapacityPerCycle: "Output Capacity / Cycle",
    ResourceDeposit: "Resource Deposit",
    RecommendedBuilding: "💡このタイルには%{resource}の鉱床があります",
    AdjacentBonus: "隣接ボーナス",
    AdjacentBonusDesc: "同じ種類の施設が隣接していると、容量が%{bonus}%追加されます",
    ConsiderIncreaseProduction: "💡%{resource}の生産量を増やすことを検討してください",
    AlwaysTransportInput: "備蓄モード",
    AlwaysTransportInputTradeCenter: "常に輸入",
    AlwaysTransportInputTradeCenterDesc: "自動売却が有効になっていない資源もトレードセンターに輸入します",
    AlwaysTransportInputDesc: "材料を必要量を超えて輸入し、この施設に備蓄します",
    ProductionCycleLength: "生産サイクル",
    ProductionCycleLengthDesc: "サイクルを大きくすると1度にまとめて生産を行います。資源取得の優先順位が下がります",
    MaxInputDistance: "最大入力距離",
    MaxInputDistanceDesc: "この施設が入力資源を取得できる最大の距離（タイル数）",
    AutoSellCapacity: "自動売却量",
    AutoSellCapacityDesc: "自動売却では、資源ごとに1秒あたりの最大処理量が設定されています",
    CurrentAutoSellCapacityMultiplier: "現在倍率 : x%{n}",
    AutoSellConcurrency: "自動売却枠",
    AutoSellConcurrencyDesc: "自動売却で同時に売れる資源の種類",
    MaxAutoSellConcurrencyReached: "自動売却枠が最大に達しています",
    CannotSellBuilding: "現在施設を売却することはできません",
    WallStreet: "ウォールストリート",
    MarketCap: "時価総額",
    MarketCapDesc: "(資源評価+建物評価)x株式評価",
    BuildingValuation: "建物評価",
    BuildingValuationDesc: "建築許可証やアップグレードを含む、建築済み施設の総価値",
    ResourcesValuation: "資源評価",
    ResourcesValuationDesc: "手持ち資源の合計価値",
    Battery: "バッテリー",
    BatteryFactory: "バッテリー工場",
    RatingBuy: "買い",
    RatingSell: "売り",
    SwissShop: "スイスショップ",
    RatingHold: "ホールド",
    RatingOutperform: "買い推奨",
    RatingUnderperform: "売り推奨",
    StockRating: "株式評価",
    JetEngine: "ジェットエンジン",
    Helicopter: "ヘリコプター",
    Lithium: "リチウム",
    LithiumMine: "リチウム採掘場",
    LiionBatteryFactory: "リチウムイオンバッテリー工場",
    HelicopterFactory: "ヘリコプター工場",
    Satellite: "人工衛星",
    ToyFactory: "おもちゃ工場",
    Toy: "おもちゃ",
    SpaceStation: "宇宙ステーション",
    SpaceStationFactory: "宇宙ステーション工場",
    OperatingSystem: "OS",
    OperatingSystemCompany: "OSメーカー",
    LinuxDistribution: "Linuxディストリビューション",
    Internet: "Webコンテンツ",
    WebBrowser: "Web企業",
    Console: "ゲームハード",
    ConsoleFactory: "ゲームハードメーカー",
    Train: "電車",
    TrainFactory: "電車工場",
    ShoeFactory: "靴工場",
    Shoes: "靴",
    ArtilleryFactory: "大砲工場",
    Artillery: "大砲",
    SubmarineFactory: "潜水艦工場",
    Submarine: "潜水艦",
    Spaceship: "スペースシップ",
    RobotFactory: "ロボット工場",
    Robot: "ロボット",
    SpaceshipFactory: "スペースシップ工場",
    SatelliteFactory: "人工衛星工場",
    JetEngineFactory: "ジェットエンジン工場",
    StockRatingDesc: "「買い」なら時価総額が高くなります。市場価格とともに更新されます",
    InterestRate: "金利",
    InterestRateDesc: "オフラインの間、時価総額に応じて得られる利息",
    OfflineEarning: "オフライン収入",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "オフライン収益時間",
    OfflineEarningTimeDesc: "この時間までオフライン収入が得られます",
    BuyPermit: "建築許可証の購入",
    NotEnoughBuildingPermit: "建築許可証が不足しています。新しい建物を建てるためにもっと買ってください",
    MovingAverage: "移動平均",
    MovingAverageDesc: "資源の変化をリアルタイムではなく移動平均で表示します",
    AllowZoom: "ズーム",
    AllowZoomDesc: "ズームサポートをオンにします。マウスホイールでズームします。現在のズームは%{zoom}です",
    AllowZoomMobileDesc: "ズームサポートをオンにします。ピンチ操作でズームできます。現在のズームは%{zoom}です",
    Settings: "設定",
    Sound: "効果音",
    SoundDesc: "クリック音やエラー音などの効果音をオンにする",
    AutoHighlight: "自動ハイライト",
    AutoHighlightDesc: "施設を選択すると、同じ種類の施設が自動的にハイライトされます",
    MusicDesc:
        "BGMをオンにする。曲名 : It's Not Over 'Til The Bossa Nova アーティスト : Shane Ivers (https://www.silvermansound.com)",
    Credits: "クレジット",
    Icons: "アイコンの表示",
    MisplacedBuilding: "⛔この%{building}は、正しい資源タイルに置かれていません",
    HighlightBuildings: "建物のハイライト",
    HighlightTurnedOff: "停止している施設",
    HighlightStockpileModeOn: "備蓄モードがオンになっている施設",
    HighlightProductionCycleNotDefault: "生産サイクルが1でない施設",
    HighlightMaxInputDistanceNotDefault: "最大入力距離が∞でない施設",
    HighlightNotMakingProfit: "利益が出ていない施設",
    NBuildingsAreHighlighted: "%{n}個の施設がハイライトされます",
    OnlyToWarehouse: "倉庫のみ",
    OnlyToWarehouseDesc: "この施設から資源を輸送できるのは倉庫だけです",
    TurnOffProduction: "一時停止",
    TurnOffProductionDesc: "施設を一時停止します。施設は、生産・輸送を停止し、消費電力が0になります",
    ApplyToAll: "すべての%{building}に適用",
    FuelCostNumber: "%{cost}%{fuel}",
    Unlimited: "無制限",
    Transport: "輸送",
    TileModifier: "タイル補正",
    ShowAllModifiers: "すべての補正を表示",
    HideAllModifiers: "すべての補正を隠す",
    NumberOfBuildings: "持っている建物の数",
    ShowContent: "コンテンツの表示",
    HideContent: "コンテンツを隠す",
    BuyExpansionPack: "%{price}で購入",
    Cities: "Cities",
    InputStrategy: "輸入方針",
    InputStrategyClose: "近くから",
    InputStrategyCloseDesc: "資源が十分にある最も近い施設から輸入する",
    InputStrategyFar: "遠くから",
    InputStrategyFarDesc: "資源が十分にある最も遠い施設から輸入する",
    InputStrategyAmount: "多い所から",
    InputStrategyAmountDesc: "距離に関係なく資源の量が多い施設から輸入する",
    FuelCostSave: "燃料節約率",
    FuelCostSaveDesc: "倉庫は他の施設より安く資源を輸入できます。節約率はレベルが高くなるほど上がります",
    SoftwareCompany: "ソフトウェアメーカー",
    Software: "ソフトウェア",
    ScreenFactory: "液晶パネル工場",
    Screen: "液晶パネル",
    JoinDiscord: "Discordサーバーに参加して、最新情報やヒント、ディスカッションをお楽しみください",
    ClaimOfflineEarning: "オフライン収入を受け取る",
    OfflineTime: "オフライン時間",
    Minutes: "%{time}min",
    MaxUpgrade: "最大アップグレード",
    MaxUpgradeDesc: "最大アップグレード数に達しています",
    ClaimAmount: "現金+%{amount}",
    EffectiveTime: "有効時間",
    EffectiveTimeDesc: "オフライン収入が獲得できるのは%{time}分までです",
    BuildSearchPlaceholder: "検索する建物またはリソースを入力してください",
    MineOverlayWarning: "%{building}はタイル補正の影響を受けません",
    WholesaleCenter: "卸売センター",
    OrderFrom: "%{name}からの注文",
    ExpireIn: "有効期限",
    TurnOnAllProductions: "Production On",
    TurnOnAllProductionsDesc: "すべての施設の生産をオンにしますが、コスト削減ポリシーが有効な場合は使用できません",
    OperationSuccessful: "この操作は正常に完了しました",
    TurnOn: "Turn On",
    Reward: "報酬",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/サイクル",
    PolicyPoint: "ポリシーポイント",
    PolicyPointPerMinute: "生産レート",
    PolicyPointPerMinuteDesc: "ゲーム中、1分ごとにポリシーポイントを獲得できます",
    YourWilLGaimPolicyPoints: "%{time}で、%{amount}のポリシーポイントを獲得できます",
    PolicyPointDesc: "💡アクティブなポリシーが多ければ多いほど、各ポリシーにかかるコストは大きくなります",
    NextOrderIn: "次の注文まで",
    FillOrder: "納品",
    RejectOrder: "パス",
    WholesaleCenterLocked:
        "卸売センターのロックを解除するには、最低でも%{required}種類の資源が必要です。現在の資源は%{current}しかありません。",
    OrderFilled: "%{from}のオーダーが正常に処理されました",
    PolicyCenter: "ポリシーセンター",
    NewOrder: "%{from}から新しい注文が届きました",
    Policies: "ポリシー",
    PolicyNotEnoughTime: "このポリシーに対する十分なポリシーポイントがありません",
    TimeLeft: "残り%{time}",
    WholesaleCenterOrderFasterDesc: "卸売センターの発注間隔が2倍早くなり、2倍の発注が入ります",
    PolicyOilWellPowerx2: "油井スーパーチャージ",
    PolicyOilWellPowerx2Desc: "油井の生産量が2倍になり、消費電力が2倍になります",
    HalfTransportSpeed: "省エネ輸送",
    HalfTransportSpeedDesc: "物流速度と物流燃料費が-25%になります",
    RefineryMoreOil: "もっとガソリンを",
    RefineryMoreOilDesc: "製油所のガソリン生産量が50%増え、プラスチック生産量が50%減ります",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "施設がサイクルごとにより最適な供給元を探す機能を止めて、最後に供給を受けたところから供給を受け続けるようになります(無料)",
    RefineryMorePlastic: "もっとプラスチックを",
    RefineryMorePlasticDesc: "製油所のプラスチック生産量が50%増え、ガソリン生産量が50%減ります",
    FreeOilTransportDesc: "原油の輸送が無料になり、油井の消費電力が2倍になります",
    SuperSteelMill: "鉄のハート",
    SuperSteelMillDesc: "製鋼所の石炭消費が50%減り、鉄と電力の消費が25%増えます",
    AlSemiconductor: "Al半導体",
    AlSemiconductorDesc:
        "半導体製IC工場が銅の代わりにアルミを使用するようになります。また、銅が出ないマップでこの施設がリサーチ可能になります",
    CostSaver: "コストセーバー",
    CostSaverDesc: "施設が赤字生産を行っている場合、自動で生産を停止します",
    CostSaverBuildingDesc: "ポリシー「コストセーバー」が有効なため、収益性に応じて生産が自動的にオン/オフされます",
    CostSaverBuildingWarning: "ポリシー「コストセーバー」が有効なため、手動で生産を変更することはできません",
    GlassUseCoal: "黒いガラス",
    GlassUseCoalDesc: "ガラス工場の石炭消費量が50%増え、シリコンの消費量が50%減ります",
    AdjacentBonusOnlyOutput: "隣接ボーナス・プラス",
    AdjacentBonusOnlyOutputDesc:
        "隣接ボーナスが発生してる施設で、材料の消費量は増やさず消費電力だけを増やし、50%効率化します",
    IronMine2xOutput: "重い鉄",
    IronMine2xOutputDesc: "鉄採掘場の生産量が2倍になり、鉄の輸送コストが2倍になります",
    SolarPanelAlwaysWork: "太陽は沈まない",
    SolarPanelAlwaysWorkDesc: "ソーラーパネルが発電量を60%減らして常時稼働します",
    SteelScience: "鋼の知識",
    SteelScienceDesc: "製鋼所が材料を2倍消費して、科学も生産するようになります",
    ShoppingSpree: "買い物三昧",
    ShoppingSpreeDesc:
        "資源の生産量が不足している場合、トレードセンターから不足分を自動的に購入します（資源が自動売却されている場合は無効）",
    ShoppingSpreeTradeCenterDesc:
        "💡ポリシーの「買い物三昧」が有効なのでトレードセンターは不足している資源を自動的に購入します",
    ExtraPolicyPoints: "ロビー活動",
    CrAlloyUseFe: "クロム鉄",
    CrAlloyUseFeDesc:
        "クロム合金工場が、鉄x2+アルミx1を素材にクロムを生産します。また、リチウムが出ないマップでこの施設がリサーチ可能になります",
    DoubleTileModifier: "自然の力",
    TileModifierOutputOnly: "タイル補正プラス",
    GasPlantPetrol: "ガス液化",
    GasPlantPetrolDesc: "ガス発電所が、追加のガスを消費してガソリンも生産します",
    BuildingRecycle: "建築リサイクル",
    BuildingRecycleDesc: "施設を建てたたあと1分以内に売ると全額返金されます",
    CoalPlantFuel: "石炭液化",
    CoalPlantFuelDesc: "石炭発電所が、追加の石炭を消費してガソリンも生産します",
    Welcome: "Welcome",
    SeeTutorialAgain: "もう一度チュートリアルを見る",
    HelpTranslateTheGame: "翻訳改善にご協力お願いします(by初代翻訳者)",
    SkipTutorial: "チュートリアルをスキップ",
    NextTutorial: "次のページ",
    Tutorial1:
        "Industry Idleは、工場🏭を建てて、製品📦を生産し、資産を増やす<em>資源管理</em>ゲームです。 <br><br>まず、基本的なコンセプトを紹介しましょう",
    Tutorial2:
        "すべての施設には電力⚡が必要ですあなたは<em>風力発電</em>で発電しています。<br><br>風力発電は10秒中8秒しか動きません",
    Tutorial3:
        "地図上にはたくさんの<em>資源の鉱脈</em>があります。<br><br>例えば、原油の鉱脈から<em>原油</em>を取り出す<em>油井</em>があります。<br></br>資源の鉱脈は無制限なので、なくなる心配はありません。採掘場以外の施設は、どのタイルにも建てることができます",
    Tutorial5:
        "また、トレードセンターから資源を購入することもできます。<br><br>市場は<em>流動的</em>で、価格📈は定期的に変化します",
    Tutorial6:
        "新しい施設を建てるには、まず<em>リサーチラボ🧪</em>でアンロックする必要があります。リサーチラボでは、科学をリサーチポイントに変換することもできます。<br><br>風力発電（およびその他の発電所）は、稼働すると少量の科学を生み出します。<br><br>風力発電(やその他の発電所)は、運転中に少量の科学を生成します。ここでは、<em>現金💸</em>と<em>ガソリン⛽</em>を使って、スタートダッシュを決めましょう",
    WelcomePlay: "ゲーム開始",
    WelcomePlayMuted: "ゲーム開始(🔇BGM OFF)",
    Chat: "チャット",
    Send: "送信",
    Import: "インポート",
    Export: "エクスポート",
    LastBackupAt: "最後のバックアップ",
    RestoreFromBackup: "バックアップから復元",
    RestoreFromBackupFail: "Steam Cloudからのバックアップの復元に失敗しました : 本当にバックアップがありますか？",
    RestoreFromBackupTitle: "よろしいですか？",
    RestoreFromBackupDesc:
        "通常、ローカルでの保存が失われない限り、クラウドバックアップからの復元は必要ありません。クラウドバックアップはローカルセーブより少し古いです",
    ChatMessages: "チャットメッセージ",
    ChangeName: "変更",
    SaveName: "保存方法",
    NameValidationRule: "名前はアルファベットと数字のみで、5～15文字以内です",
    NameValidationRuleProfanity: "冒涜的な言葉は使用しないでください",
    ChatMessageRateLimit: "新しいチャットメッセージは、10秒ごとに送信できます",
    NameSaved: "名前の変更が完了しました",
    NoMessages: "新しいメッセージはありません",
    Leaderboard: "リーダーボード",
    Name: "名前",
    Rank: "順位",
    Tips1: "株式の格付けは5段階。買い・買い推奨・ホールド・売り推奨・売りの5段階です",
    Tips2: "生産に必要な資源がすでにある場合、備蓄モードをオンにしない限り、施設は資源の輸送を停止します",
    Tips3: "資源の輸送にかかる燃料費は、距離と資源の量によって決まります",
    Tips4: "施設は資源の輸送を停止しますが、地図上の資源量が投入量を超える場合は輸送しません",
    Tips5: "施設は資源の自動売却がオフになっている場合、トレードセンターから資源を輸送します",
    Tips6: "資源の燃料費は「投入量」の項目で確認できます",
    Tips7: "資源を購入すると、価格が上昇します。資源を売却すると、価格が下がります",
    Tips8: "各資源の量とその経年変化のグラフは、統計局で見ることができます",
    Tips9: "施設のアンロックに必要なリサーチポイントは、資源の市場価格によって決まります",
    Tips10: "資源の種類によって市場での価格は異なります。常に市場の変動に備えましょう",
    Tips11: "生産を拡大する前に、電力や燃料の供給状況を常に確認することをお勧めします",
    FPS30: "省エネモード",
    OfflineModeDesc: "サーバー接続エラー : オフラインの収益は生成されません。インターネット接続を確認してください",
    OptOut: "Opt Out",
    OptIn: "リセットして有効にする",
    LeaderboardOptOut: "リーダーボードのオプトアウト",
    LeaderboardOptOutDesc:
        "これにより、リーダーボードのスコアが送信されなくなります。注意 : 後でリーダーボードを有効にしたい場合は、データをリセットする必要があります",
    LeaderboardOptIn: "リーダーボードのリセットと有効化",
    LeaderboardOptInDesc: "リーダーボードを有効にするには、データをリセットする必要がありますが、間違いありませんか？",
    RewardAdsFailed: "特典映像の再生が完了しない",
    RewardAdsNotAvailable: "特典映像が配信されていません（現在、iOS/Androidのみ対応しています）",
    OfflineEarningDoubleSuccess: "オフラインでの稼ぎが2倍になりました",
    FPS30Desc:
        "省エネモードをオンにすると、60FPSではなく30FPSでゲームが動作します。これにより、バッテリーが長持ちします",
    HighlightAll: "🔍%{type}をハイライト",
    HighlightInput: "🔍%{type}を要求する施設をハイライト",
    HighlightOutput: "🔍%{type}を生産する施設をハイライト",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Out in %{time}",
    FuelRunOutWarning: "💡燃料の消費量が生産量を上回っています。燃料がなくなると、輸送が停止します",
    InAmount: "In : %{number}",
    OutAmount: "Out : %{number}",
    SwissBank: "スイス銀行",
    SwissMoney: "%{money}💵",
    PrestigeDesc: "新しい都市で始めると、%{money}がもらえます💵",
    RestorePurchases: "購入品の復元",
    RestorePurchasesSuccess: "購入品が復元されました",
    RestorePurchasesFailed: "購入品が復元されませんでした",
    ExpansionPacks: "拡張パック",
    ExpansionPack1: "拡張パック1",
    ExpansionPack1Owned: "拡張パック1",
    RequireExpansionPack1: "拡張パック1",
    RequireExpansionPack1Desc: "この機能は拡張パック1でのみ利用可能です",
    RequireAnyExpansionPack: "拡張パック専用",
    RequireAnyExpansionPackDesc: "この機能を利用するには、少なくとも1つの拡張パックを所有している必要があります",
    HideRewardAd: "リワード広告を隠す",
    HideRewardAdDesc:
        "ゲーム内の広告はすべてオプションのリワード広告です。これにより、ゲーム内のリワード広告オプションがすべて非表示になります",
    HideDiscordBanner: "ディスコードバナーを隠す",
    HideDiscordBannerDesc: "本部でDiscordとストアフロントのバナーを隠す",
    HideChat: "チャットメッセージを隠す",
    SortedByDeficit: "赤字でソート",
    PurchaseFailed: "購入が完了しませんでした",
    PurchaseSteamContinue: "Steamで購入を完了してください",
    PurchaseSuccess: "購入が完了しました、ご協力ありがとうございました",
    PrestigeCurrency: "スイスマネー💵",
    RestartDesc: "💡現在の都市を選択すると続きから再開できます",
    PrestigeGoBack: "戻る",
    ProductionMultiplier: "生産能力",
    ProductionMultiplierDesc: "すべての施設の生産能力が向上します",
    FuelCostDiscount: "燃料 割引率",
    FuelCostDiscountDesc: "資源を輸送する際の燃料費が割引になる",
    AutoSellCapacityMultiplier: "自動売却倍率",
    AutoSellCapacityMultiplierDesc: "現在の容量に関係なく、自動売却容量に適用される倍率",
    BuildingPermitCostDivider: "建築許可証 割引率",
    BuildingPermitCostDividerDesc: "建築許可証の代金がこの数値で割られます",
    ExtraAdjacentBonus: "隣接ボーナス",
    ExtraAdjacentBonusDesc: "同じ種類の施設が隣接していると、ボーナス容量が追加されます",
    OfflineEarningMultiplier: "オフライン収益倍率",
    OfflineEarningMultiplierDesc: "オフライン収益に適用される倍率",
    PrestigeAlertTitle: "よろしいですか？",
    PrestigeAlertContent: "会社を売却し、%{city}に新会社を設立します。%{amount}のスイスマネーを獲得します",
    PrestigeCurrencyDesc: "これはスイス銀行の口座にあるお金で、新しい都市で始めるときに持っていくことができます",
    Prestige: "Cash In",
    Cancel: "キャンセル",
    SaveFileCorrupted: "保存ファイルが壊れています",
    CheatDetected: "セーブファイルが古いため読み取ることができません。新しいセーブファイルで開始してください",
    LoadGameError: "ゲームの読み込みに失敗しました",
    LoadGameErrorMessage: "Error message : %{message}",
    LoadGameErrorDesc:
        "インターネット接続環境をご確認ください。それでも問題が解決しない場合は、サポートにお問い合わせください",
    ExpansionPackIncompatible: "拡張パックを含むセーブをインポートしていますが、ゲームに必要な拡張パックがありません",
    SaveFileMigrated: "新しい時代へ。ベータ版が登場",
    SaveFileMigratedDesc:
        "アルファ版でのプレイテストにご協力いただきありがとうございました。あなたの古いマップは互換性がありませんが、あなたのデータを移行し、いくつかのボーナスを提供しています",
    ClaimSwissMoney: "%{amount}のスイスマネーを受け取る",
    SaveFileMigratedFinePrint:
        "時価総額がスイスマネーに変換され、未使用のスイスマネーが繰り越されます。アルファ版でプレイすると、50%のボーナススイスマネーがもらえます。繰り越し可能なスイスマネーの上限は200です",
    CashIn: "Cash In",
    CurrentCity: "現在の都市",
    CashInDesc:
        "新しい都市でスタートした場合、スイス銀行の口座にこの金額が振り込まれます。スイスマネーを獲得するには、時価総額が%{amount}に達する必要があります",
    MoveToNewMap: "新しい都市で始める",
    CityName: "都市名",
    CitySize: "マップサイズ",
    GridType: "グリッドタイプ",
    StartInThisCity: "%{city}でスタート",
    CityBonus: "シティボーナス",
    ResourceTilePercentage: "リソースタイル",
    MapSquareGrid: "正方形",
    MapHexGrid: "ヘクス",
    Stockholm: "ストックホルム",
    Rotterdam: "ロッテルダム",
    Oslo: "オスロ",
    StPetersburg: "サンクトペテルブルク",
    Hamburg: "ハンブルグ",
    HamburgBonus:
        "<li>アンロック済み施設 : 飛行船工場</li><li>出力2倍 : 半導体工場</li><li>入出力2倍 : 造船所</li><li>入出力2倍 : 自動車工場</li><li>アンロック済み施設 : リチウムイオンバッテリー工場</li>",
    Toulouse: "トゥールーズ",
    Rome: "ローマ",
    RomeBonus:
        "<li>アンロック済み施設 : コロッセオ</li><li>出力2倍 : コロッセオ</li><li>開始時にポリシーセンターがLv5</li><li>入出力2倍 : オペラハウス</li><li>レコーディングスタジオがカルチャーも生産</li>",
    Detroit: "デトロイト",
    Boston: "ボストン",
    BostonBonus:
        "<li>開始時にリサーチラボがLv5</li><li>アンロック済み施設 : ポリテク</li><li>入出力2倍 : ポリテク</li><li>入出力2倍 : 学校</li><li>出力2倍 : 大学</li>",
    HideNotProducing: "生産されていない資源を隠す",
    SortByStorage: "ストレージ",
    SortByProduction: "製作",
    SortByName: "名前",
    PlayerTrade: "プレイヤー間トレード",
    AddTradeFail: "トレードの追加に失敗しました",
    AddTradeExceedMaximumTrade: "有効な取引は最大%{num}までです。先にいずれかの取引を要求またはキャンセルしてください",
    AddTradeSuccess: "このトレードは正常に追加されました",
    LoadTradeFail: "プレイヤー間トレードのロードに失敗しました。後でもう一度試してください",
    ClaimTradeFail: "トレードに失敗しました。後でもう一度試してください",
    CancelTradeSuccess: "トレードは正常にキャンセルされました",
    CancelTradeFail: "このトレードをキャンセルできませんでした、後でもう一度試してください",
    AcceptTradeFail: "トレードに失敗しました。後でもう一度試してください",
    PlayerTradeBanner: "他のプレイヤーと資源をトレードする",
    PlayerTradeResource: "リソース",
    PlayerTradeAmount: "数量",
    PlayerTradePrice: "単価",
    PlayerTradeValue: "総額",
    PlayerTradeWaiting: "待機中...",
    UseTradeCenterPrice: "手数料",
    AddTrade: "トレードの追加",
    ActiveTrades: "アクティブなトレード",
    AcceptTrade: "了承",
    CancelTrade: "キャンセル",
    RefundTrade: "払い戻し",
    RefundTradeSuccess: "このトレードはキャンセルされました。%{resource} が返還されます",
    RefundTradeFail: "このトレードの払い戻しに失敗しました。後でもう一度試してください",
    ClaimTrade: "受け取る",
    RefreshTrade: "リフレッシュ",
    PasteYourSave: "保存データを貼り付けてください",
    FailedToImportSave: "保存データのインポートに失敗しました",
    FailedToImportSaveDesc: "セーブファイルに互換性がないか破損しています : %{error}",
    SaveCopiedToClipboard: "セーブデータがクリップボードにコピーされました",
    CancelActiveTradeFirst: "アクティブなプレイヤー間トレードがあります。先にキャンセル/受取してください",
    FailedToCheckActiveTrade: "アクティブなトレードの確認に失敗しました。後ほどもう一度お試しください",
    PlayerTradeQuotaExceed: "このトレードはあなたの取引枠を超えています",
    PlayerTradeValidRange: "Range : %{min}~%{max}",
    PlayerTradeFilterCanAfford: "お金がない",
    PlayerTradeQuota: "取引枠残り : %{value}",
    PlayerTradeUnavailable:
        "プレイヤー間トレードを行うには、少なくとも1つのリソースが生産され、保管されている必要があります",
    PlayerTradeToClaim: "あと%{num}回プレイヤー間トレードが可能です",
    PowerBank: "パワーバンク",
    PowerBankBuildDesc: "余剰電力を蓄え、電力不足の際に電力を供給する",
    WarehouseBuildDesc: "選択した施設から資源をこの施設に輸送できます。この施設への輸送コストは通常より安上がりです",
    PowerBankChargeSpeed: "充電速度",
    PowerBankPowerLeft: "パワー残量",
    PowerBankMoreCapacity: "バッテリー保護",
    PowerBankMoreCapacityDesc: "パワーバンクの容量が50%増え、充電速度が50%減ります",
    PowerBankNotWorking: "⛔パワーバンクは発電所の隣でしか稼働しない",
    ExcludeBuildingsShutdown: "停止している建物を除く",
    ColorTheme: "カラーテーマ",
    ColorThemeDesc: "ゲームアイコン、ハイライト、グリッド、背景のカラーテーマ。リロードが必要",
    SiliconMine2xOutput: "シリコンバレー",
    SiliconMine2xOutputDesc:
        "シリコン採掘場の生産量が2倍になり、消費電力が1.5倍に、シリコンの輸送コストが1.5倍になります",
    CoalMine2xOutput: "産業革命",
    CoalMine2xOutputDesc: "石炭採掘場の生産量が2倍になり、消費電力が1.5倍に、石炭の輸送コストが1.5倍になります",
    AlMine2xOutput: "アルミの製錬",
    AlMine2xOutputDesc: "アルミ採掘場の生産量が2倍になり、消費電力が2倍になります",
    LoggingCamp2xOutput: "森林破壊",
    LoggingCamp2xOutputDesc: "伐採場の生産量が2倍になり、木材の輸送コストが2倍になります",
    PowerBankLeft: "パワーバンク",
    ColorThemeEditor: "カラーテーマエディター",
    ColorThemeEditorDesc: "現在のカラーテーマの色を上書きできます。現在のオーバーライド数は%{num}です",
    ColorThemeEditorSave: "保存",
    ColorThemeEditorReset: "リセット",
    ColorThemeEditorResetAll: "オールリセット",
    NewMessageMentions: "新規メッセージ : %{message}",
    HideChatMentions: "チャットのメンションを隠す",
    HideChatMentionsDesc: "チャットメッセージで私のことが話題になったとき、音声とトーストの通知を非表示にします",
    PendingConstructionCannotReload: "建設中の建物があると、ゲームを再読み込みできません",
    AcceptTradeFailRateLimit: "トレードは%{time}秒ごとに1回しか行えません",
    DowngradeBuilding: "ダウングレード",
    CancelTradeConfirmDialogTitle: "このトレードをキャンセルしますか？",
    CancelTradeConfirmDialogYes: "Yes",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "供給元の追加",
    WarehouseAddInput: "供給元の追加",
    WarehouseTapToSelect: "地図をタップして選択...",
    WarehouseFindOnMap: "🔍地図から探す",
    WarehouseRemoveRoute: "削除",
    WarehouseAddRouteFail: "選択されたタイルは有効な供給元ではありません",
    LevelN: "レベル%{level}",
    Surplus: "余剰",
    Production: "生産",
    Consumption: "消費",
    WarehouseInputCapacityDescV2: "この倉庫の輸入速度。すべてのルートで均等になります",
    WarehouseInputCapacityPerRoute: "各ルート : ",
    PlayerCountryFlag: "プレイヤーフラグ",
    PlayerCountryChooseFlag: "国名コードのアルファベット順",
    WindTurbineAlwaysWork: "風立ちぬ",
    WindTurbineAlwaysWorkDesc: "風力発電が発電量を30%減らして常時稼働します",
    BookPublisherScience: "科学文献",
    BookPublisherScienceDesc: "出版社がカルチャーの代わりに科学を生産するようになります",
    WarehouseOutwardFuelSave: "無料宅配",
    WarehouseOutwardFuelSaveDesc: "倉庫からの輸送でも燃料を節約できる",
    ImportSaveVersionTooNew:
        "お使いのゲームは%{gameVersion}ですが、%{saveVersion}のセーブをインポートしています。まずゲームをアップグレードしてください",
    BatteryFuelEconomy: "充電バッテリー",
    BatteryFuelEconomyDesc: "バッテリーの燃料効率が100%向上します（燃料消費が50%になります）",
    ShowTheoreticalInputOutputCapacity: "理論上の入出力容量を表示する",
    SpecialTransportCost: "輸送コストが特別な資源",
    FreeTransportCost: "無料で輸送できる資源",
    Osaka: "大阪",
    OsakaBonus:
        "<li>資源タイルが塊になりやすい</li><li>倉庫で50%の燃料節約が可能</li><li>ユニーク施設 : 漫画出版社</li><li>ユニーク施設 : アニメスタジオ</li><li>出力2倍 : 半導体工場</li><li>入出力2倍 : リチウムイオンバッテリー工場</li><li>アンロック済み施設 : バッテリー工場</li><li>入出力2倍 : バッテリー工場</li><li>バッテリーの燃料効率が100％向上</li><li>バッテリー工場が石炭を要求しない</li><li>開始時に100Kのバッテリーを持っている</li>",
    HideChatDescV2:
        "下のツールバーからチャットメッセージを隠すことができます。チャットメッセージを表示することで、私たちのサービスに同意したことになります",
    HideChatDescV2ToS: "サービス規約",
    IntegratedCircuitFab: "シリコン製IC工場",
    MangaPublisher: "漫画出版社",
    Manga: "漫画",
    AnimeStudio: "アニメスタジオ",
    Anime: "アニメ",
    PlayerTradeAction: "アクション",
    PlayerTradeBuy: "購入",
    PlayerTradeSell: "売却",
    PlayerTradeBid: "要求",
    PlayerTradeAsk: "提供",
    CancelTradeConfirmDialogDescV2:
        "このトレードをキャンセルすると、資源/キャッシュの%{percent}が返金されます。資源はトレードセンターの倉庫に返還されます",
    ClaimTradeSuccessV2: "%{cashOrResource}のトレードが成立しました",
    AcceptTradeSuccessV2: "%{cashOrResource}のトレードを行いました",
    PlayerTradeFilterPriceV2: "市場価格より有利な取引だけ表示",
    ResourceExplorer: "リソースエクスプローラー",
    ResourceExplorerDesc: "何もないタイルから資源を採掘できるようになります",
    ResourceExplorerDescLong: "💡リソースエクスプローラには隣接ボーナスがありません。消費電力は資源ごとに異なります",
    ResourceExplorerSelectResource: "採掘資源",
    ProductionSettings: "プロダクション設定",
    PlayerTradeQuotaDesc: "💡プレイヤーのトレード枠は時価総額の%{percent}で、市場が更新されるとリセットされます",
    PlayerTradePartialFillTitle: "フィル・パーセンテージを選択",
    PlayerTradeAmountNotValidV2: "最小取引量は1です",
    PlayerTradeOptOut: "リーダーボードに参加していないため、他のプレイヤーとトレードできません",
    FirstTimeReadGuide: "💡遊び方についてちょっとしたヘルプが必要ですか？タップしてビギナーズガイドを読んでみましょう",
    ReadSteamGuideV2: "ゲームガイド",
    ReadSteamGuideV2Desc: "Steamでコミュニティが作成したガイドを読むことができ、自分でも作成できます",
    ChatMessageTooLong: "チャットメッセージが最大文字数を超えています",
    ChatPlaceholderV2: "メッセージを入力 : 最大%{length}文字",
    ShowProfitBreakdown: "利益の内訳を表示する",
    HideProfitBreakdown: "利益の内訳を隠す",
    ProfitBreakdownOutput: "%{res}出力",
    ProfitBreakdownInput: "%{res}入力",
    ProfitBreakdownFuel: "燃料コスト",
    BuildingProfit: "利益",
    RestoreBackup: "リストア",
    SteamLogin: "Steamによるサインイン",
    SteamLoginDialogDesc:
        "ローカルセーブで拡張パックが有効になっているため、続行するにはSteamでサインインする必要があります。または、ローカルセーブを消去して最初からやり直してください",
    SteamLoginDesc: "Steamで拡張パックを所有している場合、サインイン後にウェブ上で拡張パックを使って遊ぶことができます",
    SteamLoginYes: "サインイン",
    SteamLoginNo: "消去してやり直す",
    KungFuDojo: "カンフー道場",
    KungFu: "カンフー",
    TaiChi: "太極拳",
    TaiChiDojo: "太極拳道場",
    HongKong: "香港",
    FreeTransportToTradeCenter: "国際輸出貿易",
    FreeTransportToTradeCenterDesc: "トレードセンターへの輸送が無料。トレードセンターからの輸送コストが+50%",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "InStorage : %{amount}",
    PlayerTradeFillValue: "価値",
    FiberFactory: "光ファイバー工場",
    Fiber: "光ファイバー",
    Achievements: "Achievements",
    AchievementsDesc: "%{total}個中%{number}個の実績を解除しました",
    AchievementsReward: "報酬 : スイスマネー+%{swiss}",
    AchievementsRewardToast: "報酬を獲得 : スイスマネー+%{swiss}",
    AchievementsClaim: "受け取る",
    AchievementsToast: "実績「%{name}」を解除しました。本部で報酬が受け取れます",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "1回のプレイでストックホルムで100スイスマネーを獲得",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "1回のプレイでストックホルムで500スイスマネーを獲得",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "1回のプレイでストックホルムで1000スイスマネーを獲得",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "1回のプレイでオスロで100スイスマネーを獲得",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "1回のプレイでオスロで500スイスマネーを獲得",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "1回のプレイでオスロで1000スイスマネーを獲得",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "1回のプレイでロッテルダムで100スイスマネーを獲得",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "1回のプレイでロッテルダムで500スイスマネーを獲得",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "1回のプレイでロッテルダムで1000スイスマネーを獲得",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "1回のプレイでデトロイトで100スイスマネーを獲得",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "1回のプレイでデトロイトで500スイスマネーを獲得",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "1回のプレイでデトロイトで1000スイスマネーを獲得",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "1回のプレイでボストンで100スイスマネーを獲得",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "1回のプレイでボストンで500スイスマネーを獲得",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "1回のプレイでボストンで1000スイスマネーを獲得",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "1回のプレイでローマで100スイスマネーを獲得",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "1回のプレイでローマで500スイスマネーを獲得",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "1回のプレイでローマで1000スイスマネーを獲得",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "1回のプレイでハンブルグで100スイスマネーを獲得",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "1回のプレイでハンブルグで500スイスマネーを獲得",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "1回のプレイでハンブルグで1000スイスマネーを獲得",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "1回のプレイでトゥールーズで100スイスマネーを獲得",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "1回のプレイでトゥールーズで500スイスマネーを獲得",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "1回のプレイでトゥールーズで1000スイスマネーを獲得",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "1回のプレイで香港で100スイスマネーを獲得",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "1回のプレイで香港で500スイスマネーを獲得",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "1回のプレイで香港で1000スイスマネーを獲得",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "1回のプレイでサンクトペテルブルクで100スイスマネーを獲得",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "1回のプレイでサンクトペテルブルクで500スイスマネーを獲得",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "1回のプレイでサンクトペテルブルクで1000スイスマネーを獲得",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "1回のプレイで大阪で100スイスマネーを獲得",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "1回のプレイで大阪で500スイスマネーを獲得",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "1回のプレイで大阪で1000スイスマネーを獲得",
    SteamAutoCloudBackup: "スチームクラウド自動バックアップ",
    SteamAutoCloudBackupFailed: "Steam Cloudの自動バックアップに失敗 : %{error}",
    SteamManualBackup: "Steam Cloudの強制バックアップ",
    UILoading: "読み込み中...",
    UserAuthenticated: "あなたは認証されています",
    BuildingResourceBreakdown: "アイドル金額内訳",
    SortByDeficit: "赤字",
    SortByRunOut: "ランアウト",
    SocialNetworkInc: "SNS運営",
    SocialNetwork: "SNS",
    DatabaseCompany: "データベースメーカー",
    Database: "データベース",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "空母工場",
    AircraftCarrier: "空母",
    MapExclusive: "このマップ専用",
    ElectricCar: "ニコラ・テスラ",
    ElectricCarDesc: "自動車工場がガソリンの代わりにバッテリーを消費します。バッテリーの消費量はガソリンの半分です",
    HongKongBonusV2:
        "<li>独自の市場価格 : 市場価格と株価は正規分布に従う</li><li>市場の更新と取引枠のリセットが2倍の頻度で行われる（1時間ごと）</li><li>リサーチは取引資源量が増えるとアンロックされる</li><li>ユニーク施設 : カンフー道場</li><li>ユニーク施設 : 太極拳道場</li><li>アクティブプレイヤーの最大トレード数を50％増加</li><li>自動売却枠が+1</li><li>ユニークポリシー : 国際輸出貿易</li><li>ユニークポリシー : Pearl of the Orient</li><li>卸売センターが4種のリソースでアンロック</li><li>開始時に100Mの現金を持っている</li>",
    TaiChi10xCultureDescV2: "カンフーと太極拳の輸送が無料。映画スタジオの入出力が2倍。映画スタジオの消費電力が+50%",
    SettingsFullScreen: "フルスクリーン",
    SettingsFullScreenDesc: "フルスクリーンモードでゲームを実行します。Steamバージョンでのみ利用可能",
    LeaderboardByAllPrestigeCurrency: "総獲得スイスマネー",
    LeaderboardByCash: "現在の手元資金",
    LeaderboardTotalValuation: "評価額",
    LeaderboardDescV2: "トッププレイヤーの位置を確認",
    LastUpdatedAt: "最終更新日",
    DetroitBonusV3:
        "<li>アンロック済み施設 : エンジン工場</li><li>出力2倍 : エンジン工場</li><li>入出力2倍 : 自動車工場</li><li>自動車工場がガソリンの代わりに天然ガスを使用</li><li>輸送無料 : 自動車</li><li>ポリシー無料化 : ニコラ・テスラ</li><li>入出力2倍 : 電車工場</li>",
    SaveAndExit: "ゲームの保存と終了",
    SaveAndExitDesc:
        "ゲームの保存と終了。これはSteam版でのみ可能で、ウィンドウバーの閉じるボタンと同じ役割を果たします",
    AutoSellResourceWarningShortLabel: "💡自動売却",
    AutoSellResourceWarningDesc:
        "このリソースは自動売却されます。トレードセンターに保管されている分はここでは使用できません",
    PlayerTradeLocalPrice: "LocalPrice : %{price}",
    ChatForceScroll: "強制スクロール",
    ChatForceScrollDesc:
        "強制スクロールがオンになっていると、新しいメッセージがあるたびにチャットがスクロールします。それ以外の場合は、すでに下にいるときにのみスクロールします",
    ResourceExplorer2: "リソースエクスプローラー2.0",
    ConstructionCancel: "キャンセル",
    ConstructionPause: "一時停止",
    ConstructionResume: "レジューム",
    PolicyBlueprint: "ブループリント",
    PolicyBlueprintDesc: "施設の建築が自動的に開始されなくなり、ブループリントが配置されます(無料)",
    HighlightUnderConstruction: "建築されていない施設",
    HighlightUnderLevel10: "レベル10未満の施設",
    HighlightUnderLevel20: "レベル20未満の施設",
    HighlightUnderLevel30: "レベル30未満の施設",
    Logout: "あなたはログアウトしています",
    ConstructionStatusQueueingV2: "キューイング",
    ConstructionStatusPausedV2: "一時停止",
    ConstructionStatusBuildingV2: "建物",
    ConstructionStatusUnpaidV2: "未払い",
    ConstructionStatus: "工事状況",
    ConstructionStart: "スタート",
    CostFree: "無料",
    PlaceBlueprint: "ブループリント配置は無料",
    PlayerTradePriceNotValidV2: "取引価格は、%{min}と%{max}の間でなければなりません",
    MarketNews: "市場ニュース",
    MarketNewsApplyToYou: "あなただけ",
    MarketNewsApplyToGlobal: "グローバル",
    MarketNewsHighlightAffected: "🔍ハイライト",
    MarketNewsFilterInput: "すべての%{res}入力",
    MarketNewsFilterOutput: "すべての%{res}出力",
    MarketNewsFilterBoth: "すべての%{res}入力および出力",
    MarketNewsIncrease: "%{percent}増加",
    MarketNewsDecrease: "%{percent}減少",
    MarketNewsBuilding: "この建物は%{num}ニュースの影響を受けます",
    StockholmBonusV2:
        "<li>ユニーク施設 : 音楽プロデューサー</li><li>アンロック済み施設 : 製紙工場</li><li>ポリシー無料化 : 科学出版</li><li>入出力2倍 : 製紙工場</li><li>出力2倍 : 伐採場</li><li>出力2倍 : IC工場</li>",
    FreeOilTransportV2: "電気で原油輸送",
    Tutorial4P1:
        "資源の輸送には燃料が必要です。燃料は数種類から好きなものを選べます。現在あなたは燃料として<em>ガソリン⛽</em>を使用しています。<br><br>小さな動く<em>点</em>は、資源のリアルタイムの動きを表しています",
    Tutorial4P2:
        "物流センターでは、燃料の種類を変更することができます。このマップでは、燃料として<em>天然ガス</em>を使用することもできます。<br><br>物流センターでは、最も燃料を消費する輸送ルートも表示されますので、参考にするといいでしょう。<br><br>燃料の生産量が消費量を上回っていないと、燃料切れで生産が止まってしまいます。<br><br>もしそうなっても、トレードセンターや他のプレイヤーから燃料を購入することができますのでご安心を",
    Tutorial5P2:
        "<em>統計局📊</em>では、この都市の生産状況を知ることができます。<br><br>資源の入力と出力の詳細な内訳を見ることができます。<br><br>また、便利なチャート📈もたくさんあるので、生産のバランスを取るときに参考にするといいでしょう。<br></br>左上には<em>現金💰、余剰電力⚡、余剰燃料⛽</em>の数字も表示されているので、どれかが赤くなっていたら、何が起きているのか調べてみるといいでしょう",
    MusicProducer: "音楽プロデューサー",
    PlasticFiber: "安価な光ファイバー",
    PlasticFiberDesc: "光ファイバー工場がプラスチックの使用量を50%増やし、ガラスの使用量を50%減らします",
    NewsEffectx2: "記者会見",
    NewsEffectx2Desc: "市場ニュースの効果が良いものも悪いものも2倍になります",
    SellRefundPercentage: "売却返金率",
    SellRefundPercentageDesc: "施設を売却/ダウングレードした際に、戻ってくる現金と資源の割合です",
    SellBuildingDescV2:
        "施設を売却すると、投資額の%{percent}が返金され、貯蔵資源の%{percent}がトレードセンターに輸送されます",
    BuilderMoveSpeed: "ビルダー移動速度",
    BuilderMoveSpeedDesc: "施設を建てるビルダーが移動する速度",
    EBookInc: "科学出版社",
    ResourceBooster: "リソースブースター",
    BuildWarningTitle: "設置は失敗することがあります",
    BuildWarningTitleDesc: "%{reason}をこのタイルに設置しますか？",
    BuildWarningBuildAnyway: "設置する",
    ResourceBoosterNotWorking: "⛔リソースブースターは、資源採掘場の隣でのみ稼働する",
    ResourceBoosterBuildings: "ブーストされる施設",
    BuildingResourceConversion: "%{resource}変換",
    AllTimeSwissMoneyEarned: "総獲得スイスマネー : %{number}",
    BuildingUpgradeCostDivider: "建物のアップグレードコスト割引",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "同じマップにレベル10のソフトウェアメーカー、OSメーカー、データベースメーカー、Web企業を建てる",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "同じマップにレベル10のロケット工場、人工衛星工場、スペースシップ工場、宇宙ステーション工場を建てる",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "レベル40のビットコインファームとドージコインファームを建てて、1Bのビットコインとドージコインを所有する",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "生産ラインが50本あり、赤字生産がまったくない",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "生産ラインが50本あり、赤字生産が含まれる",
    UseScientificNotation: "科学的記数法の使用",
    UseScientificNotationDesc: "999.9T以上の数値にはe表記法を使用",
    LogoutDescV2:
        "他の端末でログインしたところ、その端末がログアウトしてしまいました。再度ログインすることはできますが、他の端末はログアウトされてしまいます",
    LogBackIn: "ログインし直す",
    PlayerTradeNowAllowedV2: "セーブを復元/インポートしてから%{hour}時間以内は、プレイヤー間トレードができません",
    ServerDisconnected: "サーバーから切断されています。インターネット接続を確認して、ゲームを再起動してください",
    BuildingUpgradeCostDividerDescV2: "施設のアップグレード費用がこの数値で割られます",
    ResourceBoosterDesc: "隣接する採掘場の出力を上げる",
    BlockUserChatTitle: "%{user}をブロック",
    BlockUserChatAction: "ブロック",
    BlockUserChatDesc: "ブロックはこのゲームセッション中に有効になり、ゲームを再起動しない限り元に戻すことはできません",
    ChangeNameCooldown: "名前の変更は%{hour}時間ごとに1回のみ可能です",
    AtomicBombFactory: "原子爆弾工場",
    AtomicBomb: "原子爆弾",
    DynamiteFactory: "ダイナマイト工場",
    Dynamite: "ダイナマイト",
    NuclearMissileFactory: "核ミサイル工場",
    NuclearMissile: "核ミサイル",
    LiquidPropellantFactory: "ガソリン製推進剤工場",
    GasPropellantFactory: "ガス製推進剤工場",
    Propellant: "推進剤",
    ProjectV2: "V-2計画",
    ICBMFactory: "ICBM工場",
    ICBM: "ICBM",
    RadarFactory: "レーダー工場",
    Radar: "レーダー",
    SpaceForceCommand: "宇宙軍司令部",
    SpaceForce: "宇宙軍",
    SteamAutoCloudBackupDescV2:
        "ゲームの進行状況はSteamCloudに保存され、デバイス間で同期されます。また、ゲーム内のセーブデータは10分ごとにSteamCloudに自動的にバックアップされます。バックアップはいつでも強制的に行うことができます",
    SpaceColony: "スペースコロニー",
    SpaceColonyInc: "スペースコロニー社",
    ProjectVostok: "ボストーク計画",
    AdjacentBonusSquare: "隣接ボーナス・スクエア",
    AdjacentBonusSquareDesc: "隣接ボーナスの効果が50%増えます。タイル補正は-15%から+15%になります",
    ResourceBoosterSquare: "リソースブースタースクエア",
    ResourceBoosterSquareDesc: "リソースブースターのブースト量が25%増加します。ただし科学と電力の消費も25%増加します",
    SteelMillx2: "鉄鋼炉の近代化",
    SteelMillx2Desc: "製鋼所とクロム製鋼材プラントの入出力と消費電力が2倍になります",
    FuelDynamite: "燃料ダイナマイト",
    FuelDynamiteDesc:
        "ダイナマイト工場が原油の代わりに現在の物流燃料を消費します。また、原油が出ないマップでこの施設がリサーチ可能になります",
    StPetersburgBonusV2:
        "<li>出力2倍 : ウラン採掘場</li><li>入出力2倍 : ウラン濃縮プラント</li><li>ウランの輸送コストが-50%</li><li>輸送無料 : 銃</li><li>入出力2倍 : ボストーク計画</li>",
    ToulouseBonusV2:
        "<li>出力2倍 : チタン採掘場</li><li>出力2倍 : ウラン濃縮プラント</li><li>入出力2倍 : ジェットエンジン工場</li><li>出力2倍 : 飛行機工場</li><li>入出力2倍 : ロケット工場</li>",
    BuildingPermitsNeededDesc: "建築許可証が不足しているため、この施設は使用できません",
    BuildingPermitsNeeded: "建築許可証が必要",
    BuyMissingPermits: "不足している許可証を購入する",
    GPUIsBusy: "GPUがビジー状態です",
    GPUIsBusyDesc:
        "GPUが他のタスクで忙しくなっているため、OSがゲームのグラフィックを一時停止しています。ゲームを再読み込みすると再開できます。うまくいかない場合は、ゲームを再起動してみてください",
    SaveAndReloadGame: "セーブ＆リロード",
    ResearchLabCultureInput: "ルネッサンス",
    ResearchLabCultureInputDesc: "リサーチラボがカルチャーも要求するようになり、リサーチポイントの出力が2倍になります",
    GasPumpx2Output: "高圧ガスポンプ",
    GasPumpx2OutputDesc: "天然ガスポンプの生産量が2倍になり、消費電力が2倍になります",
    LeaderboardValuationPerHour: "1時間あたりの評価額",
    LeaderboardValuationPerHourPerSwiss: "1時間あたりの評価額(1スイスマネーあたり)",
    LeaderboardValuationPerHourNewPlayers: "1時間あたりの評価額(1000スイスマネー未満)",
    LeaderboardValuationPerBuilding: "建物ごとの評価額",
    BuildingCustomColor: "建物の色",
    BuildingCustomColorReset: "リセット",
    Vancouver: "バンクーバー",
    VancouverBonus:
        "<li>4種類の建物を建てるごとに、建築許可証を1個無料で獲得</li><li>ユニークポリシー : 生産の多様性</li><li>ユニーク施設 : メープルシロップ工場</li><li>輸送無料 : メープルシロップ</li><li>ユニーク燃料 : メープルシロップ</li><li>プレイヤー間トレードでウランと濃縮ウランを2倍多く取引できる</li><li>ユニークポリシー : メープルプラスチック(無料)</li><li>出力2倍 : おもちゃ工場</li><li>入出力2倍 : ゲームスタジオ</li>",
    MapExtraPermitDesc: "マップのユニークボーナスで、建築許可証を%{number}個、無料入手しました",
    OsloBonusV3:
        "<li>アンロック済み施設 : 製油所</li><li>入出力2倍 : 製油所</li><li>ポリシー無料化 : 電気で原油輸送</li><li>入出力2倍 : ガス処理プラント</li><li>Lv4の風力発電が1個設置済み</li><li>Lv8の油井が1個設置済み</li><li>Lv2の製油所が1個設置済み</li><li>Lv2の天然ガスポンプが1個設置済み</li>",
    ResourceBoosterPercentageV2: "💡この量には、隣接するリソースブースターからの%{percent}のブーストが含まれています",
    MapleSyrup: "メープルシロップ",
    MapleSyrupFactory: "メープルシロップ工場",
    SyrupPlastic: "メープルプラスチック",
    SyrupPlasticDesc: "全工場がプラスチックの代わりにメープルシロップを消費します",
    ResourceBoosterSupplyChain: "サプライチェーンブースター",
    ResourceBoosterSupplyChainDesc:
        "リソースブースターの効果が、採掘場のサプライチェーンにも付与されます。リソースブースターの科学と電力消費が2倍になります",
    ProductionDiversification: "生産の多様化",
    ProductionDiversificationDesc: "施設の種類が増えるごとに、すべての施設に1%の容量が追加されます",
    ExtraPolicyPointsDescV2: "ポリシーセンターのポリシーポイント変換能力が2倍になります",
    PowerRequired: "必要な電力",
    AchievementVancouver100: "Sap Seller",
    AchievementVancouver100Desc: "1回のプレイでバンクーバーで100スイスマネーを獲得",
    AchievementVancouver500: "Syrup Savant",
    AchievementVancouver500Desc: "1回のプレイでバンクーバーで500スイスマネーを獲得",
    AchievementVancouver1000: "Canuck Conqueror",
    AchievementVancouver1000Desc: "1回のプレイでバンクーバーで1000スイスマネーを獲得",
    BarbariansAtTheGate: "Barbarians At The Gate",
    BarbariansAtTheGateDesc: "プレイヤー間トレードで1Tを取引",
    DiversifiedProductions: "Diversified Productions",
    DiversifiedProductionsDesc: "1つのマップで100種類の施設を建てる",
    RealEstateTycoon: "RealEstateTycoon",
    RealEstateTycoonDesc: "1つのマップで400個の施設を建てる",
    ResourceExplorer2DescV2:
        "リソースエクスプローラの生産量と消費電力が2倍になります。ポリシー「サプライチェーンブースター」が有効な場合はそちらの効果が優先されます",
    NoTileModifier: "地球は平ら",
    NoTileModifierDesc:
        "すべてのタイル補正が0になります。このポリシーにより、「自然の力」と「タイル補正プラス」のポリシーが無効になります",
    DoubleTileModifierDescV2:
        "すべてのタイル補正をプラスもマイナスも2倍にします。このポリシーは「地球は平ら」のポリシーを無効にします",
    TileModifierOutputOnlyDescV2:
        "タイル補正が出力のみに影響を与えるようになります(最大50%)このポリシーは「地球は平ら」のポリシーを無効にします",
    RotterdamBonusV2:
        "<li>入出力2倍 : 製鋼所</li><li>入出力2倍 : クロム製鋼材プラント</li><li>輸送無料 : 鉄</li><li>輸送半額 : 鋼材</li><li>自動売却量が2倍</li><li>ポリシー無料化 : 地球は平ら</li>",
    QuickLinks: "クイックリンク",
    GetHelp: "ヘルプ",
    GetHelpBeginnerGuides: "ビギナーズガイド",
    GetHelpSteamGuides: "その他のSteamガイド",
    GetHelpInGameChat: "ゲーム内チャットで聞く",
    GetHelpDiscord: "Discordサーバーに参加する",
    GetHelpWiki: "コミュニティWiki",
    SelectATile: "タイルの選択",
    PledgeAmount: "資源提供 : %{amount}",
    PledgeValue: "支援額+$%{amount}",
    TotalPledgedValue: "あなたの支援額合計",
    TotalPledgedValueDesc:
        "最初の支援は、全体の支援物資量にカウントされます。その後の支援は、「あなたの支援額合計」だけを増やします",
    ReturnOnPledge: "リターン",
    ReturnOnPledgeDesc:
        "このクラウドファンディングが成功した場合のリターンです。「あなたの支援額合計」に%を上乗せした現金が得られます。%は提供した資源の種類が増えると上がります",
    CrowdfundingEndIn: "終了-%{time}",
    ClaimCrowdfundingReward: "%{amount}の報酬を受け取る",
    ClaimCrowdfundingRefund: "%{amount}の払い戻しを受け取る",
    CrowdfundingUnsuccessful: "このクラウドファンディングは成功しませんでした。あなたの支援は返却されます。",
    PledgeSuccessful: "このクラウドファンディングに %{amount} を支援しました。",
    CrowdfundingClaimSuccessful: "%{amount} の現金を受け取りました",
    CrowdfundingAlreadyPledged: "すでに支援をしています",
    CrowdfundingAlreadyPledgedDesc:
        "さらに支援を提供することができます。その場合、「あなたの支援額合計」とリターンは増加しますが、全体の支援物資目標は増えません",
    WholesaleCenterProducingOnly: "卸売パートナー",
    WholesaleCenterProducingOnlyDesc: "卸売センターの注文が、アンロック済みの高級な製品になります",
    SoftwareCompiler: "ソフトウェアコンパイラ",
    SearchEngine: "検索エンジン",
    SearchEngineCompany: "検索エンジン会社",
    Navy: "海軍",
    NavyCommand: "海軍司令部",
    Battleship: "戦艦",
    BattleshipFactory: "戦艦工場",
    ResourceMovementHide: "すべて非表示",
    ResourceMovementShow: "すべて表示",
    ResourceMovementHighlight: "ハイライトのみ",
    ResourceMovementLine: "線だけ表示",
    ResourceMovement: "資源移動の表示",
    ResourceMovementDesc: "資源が移動する様子の表示方法を選択できます。非表示にするとパフォーマンスが向上します",
    CrowdfundingCashInWarning: "⚠新しい都市に移ると終了前のクラウドファンディングへの投資は没収されます",
    ResourceBoosterBannerDescV2:
        "💡 %{number}個のリソースブースターを持っています。それぞれの科学消費は、現在持っているリソースブースターの数に比例します",
    CrowdfundingId: "Crowdfunding %{id}",
    PatchNotes: "更新履歴",
    PatchNotesDesc: "Read what's new in this update",
    PanelPositionLeft: "左(ドック)",
    PanelPositionLeftFloat: "左(フロート)",
    PanelPositionRight: "右(ドック)",
    PanelPositionRightFloat: "右(フロート)",
    PanelPositionAuto: "自動",
    TimePlayed: "プレイ時間",
    ValuationPerHour: "1時間あたりの評価額",
    HighPowerPriority: "優先施設",
    HighPowerPriorityDesc: "オンにすると、他の施設よりも優先的に電力が供給されます",
    IndustryZone: "産業ゾーン",
    IndustryZoneDesc: "サプライチェーンを形成する施設群をまとめ、建築許可証を節約します",
    IndustryZoneMaxBuildingLevel: "最大施設Lv",
    IndustryZoneNotWorkingDesc:
        "隣接するすべての建物がサプライチェーンを形成し、他の産業ゾーンに属していない必要があります",
    IndustryZoneNoAdjacentBonus: "この施設は産業ゾーンの一部のため、隣接ボーナスはありません",
    PlayerTradeAutoClaim: "完了トレードの自動受け取り",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "クラウドストリーミング",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "スパコンラボ",
    SuperComputer: "スパコン",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "スカイネット",
    RobocarFactory: "ロボカー工場",
    Robocar: "ロボカー",
    WarehouseBuildingPermitSave: "倉庫優遇制度",
    WarehouseBuildingPermitSaveDesc: "倉庫を2つ建てる度に、建築許可証を無料で入手できます",
    PolicySearchPlaceholder: "ポリシー検索",
    SwissUpgrade: "スイスアップグレード",
    SwissUpgradeDesc: "スイスアップグレードの効果は永続的なもので、新しい都市にも引き継がれます",
    SwissBoost: "スイスブースト",
    SwissBoostDesc: "スイスブーストの効果は現在プレイ中の都市でのみ有効で、新しい都市には引き継がれません",
    ProductionMultipliers: "生産倍率",
    MultiplierMapUniqueBonus: "マップユニークボーナス",
    MultiplierSwissUpgrade: "スイスアップグレード(永続)",
    MultiplierSwissBoost: "スイスブースト(今回限り)",
    SwissBoostCostDivider: "スイスブーストコスト割引",
    SwissBoostCostDividerDesc: "スイスブーストのコストをこの値で割ります",
    AirForceCommand: "空軍司令部",
    AirForce: "空軍",
    StealthFighterFactory: "ステルス戦闘機工場",
    StealthFighter: "ステルス戦闘機",
    ArmyCommand: "陸軍司令部",
    Army: "陸軍",
    GreenPeacekeeper: "Green Peacekeeper",
    GreenPeacekeeperDesc: "風力か太陽光だけで陸軍、海軍、空軍、宇宙軍を建てる",
    DotComTycoon: "DotCom Tycoon",
    DotComTycoonDesc: "同じマップにレベル10のSNS運営、検索エンジン会社、SkyNet Inc、Musify Incを建てる",
    ConstructionNotResearched: "Not Researched",
    OfflineEarningDescV2: "オフライン収入額は、研究・生産量・自動売却に依存します",
    HighSpeedWarehouse: "特急便",
    HighSpeedWarehouseDesc: "倉庫の物流量が2倍になり、輸送速度が1.5倍になります。消費電力が2倍になります",
    IndustryZoneMultiplierDesc: "産業ゾーンボーナス",
    IndustryZoneMultiplierSwissBoost: "産業ゾーン容量ブースター",
    IndustryZoneMultiplierSwissBoostDesc: "同じ産業ゾーン内の全施設がブースト効果を受けます",
    EarningPerMinuteV2: "Offline Earning Rate",
    OfflineResearchPoint: "Offline Research Point",
    WholesaleCenterOrderFasterV2: "Bigger Faster Wholesale",
    OfflineResearchSwissBoost: "Offline Research",
    OfflineResearchSwissBoostDesc:
        "Research points are generated while you are offline (according to your Research Lab level, Science in your warehouse and offline earning time)",
};
