export const KR = {
    Translator: "번역자",
    TranslatorName: "zed",
    Language: "언어",
    ThisLanguage: "한국어",
    OK: "OK",
    SteelMill: "제철소",
    StainlessSteelPlant: "스테인리스 공장",
    CircuitFoundry: "파운드리",
    IntegratedCircuit: "집적 회로",
    OilWell: "유정",
    Wood: "나무",
    LoggingCamp: "벌목소",
    LumberMill: "제재소",
    Lumber: "목재",
    Paper: "종이",
    PaperMill: "제지 공장",
    Book: "책",
    BookPublisher: "출판사",
    OilRefinery: "정유소",
    Sell: "판매",
    Upgrade: "업그레이드",
    Build: "건설",
    Inspect: "검사",
    Buildings: "건물",
    Iron: "철",
    Actions: "작업",
    FuelType: "연료 선택",
    FuelCost: "연료 가격",
    FuelConsumption: "%{fuel} 소비",
    FuelEconomy: "연비",
    FuelProduction: "%{fuel} 생산",
    FuelInStorage: "%{fuel} 재고",
    Plastic: "플라스틱",
    FuelSurplus: "%{fuel} 과잉",
    Petrol: "가솔린",
    Buy: "구매",
    NoLiquidity: "유동성 없음",
    NoLiquidityTurnOffAutoSell: "시장에 %{res}에 대한 유동성이 충분하지 않습니다. 자동 판매가 꺼졌습니다.",
    Multiplier: "승수",
    MultiplierDesc: "10 레벨마다 +1 승수를 얻습니다.",
    SellBuilding: "건물 판매",
    PowerGrid: "전력망",
    TradeAmount: "거래 금액",
    SortBy: "정렬",
    SortByPrice: "가격",
    SortByAmount: "재고",
    NotEnoughResourcesForTrade: "거래를 위한 무역 센터의 자원이 충분하지 않습니다.",
    NotEnoughResources: "작업에 대한 자원이 충분하지 않습니다.",
    Transportation: "수송",
    Cash: "자금",
    Aluminum: "알루미늄",
    ResearchPoint: "연구 점수",
    Unlock: "해제",
    BuildingUnlocked: "%{building} 이/가 해제되었습니다.",
    Science: "과학",
    ScienceFromPowerDesc: "발전소는 전력을 생산할 때 소량의 과학을 생산합니다.",
    Culture: "문화",
    School: "학교",
    University: "대학교",
    Polytechnic: "과학기술 전문학교",
    Colosseum: "콜로세움",
    WindTurbine: "풍력발전기",
    Engine: "엔진",
    EngineFactory: "엔진 공장",
    CameraFactory: "카메라 공장",
    Camera: "카메라",
    Gun: "총기",
    GunFactory: "총기 공장",
    Aircraft: "항공기",
    AircraftFactory: "항공기 공장",
    Zeppelin: "비행선",
    ZeppelinFactory: "비행선 공장",
    Tank: "탱크",
    TankFactory: "탱크 공장",
    CoalPowerPlant: "석탄 발전소",
    PetrolPowerPlant: "가솔린 발전소",
    Copper: "구리",
    Gas: "천연가스",
    GasPump: "천연가스 펌프",
    GasPowerPlant: "가스 발전소",
    Missile: "미사일",
    MissileFactory: "미사일 공장",
    Rocket: "로켓",
    RocketFactory: "로켓 공장",
    BuildingPermit: "건축 허가",
    BuildingPermitDesc:
        "당신은 %{amount} 개의 건축 허가를 받았으며, %{amountBuilt} 개를 지었고 %{amountLeft} 개가 남았습니다.",
    BuildingLocked: "건물은 아직 사용할 수 없습니다. 먼저 연구소에서 잠금을 해제해야 합니다.",
    BuildQueue: "건설 대기열",
    BuildQueueDesc: "현재 대기열의 건물 수",
    MaxBuilders: "건축업자 수",
    MaxBuildersDesc: "동시에 건설할 수 있는 건물 수",
    Silicon: "규소",
    AluminumMine: "알루미늄 광산",
    CopperMine: "구리 광산",
    SiliconMine: "규소 광산",
    IronMine: "철 광산",
    CoalMine: "석탄 광산",
    Headquarter: "본사",
    ResearchLab: "연구소",
    TradeCenter: "무역센터",
    Resources: "자원",
    NotEnoughPower: "💡 전력이 충분하지 않습니다, 전력 공급을 늘리는 것을 고려하십시오",
    NotEnoughFuel: "이 작업을 하기 위한 %{fuel} 이 부족합니다",
    NotEnoughCash: "이 작업에 충분한 자금이 없습니다",
    NotEnoughSwissMoney: "스위스 돈이 충분하지 않습니다",
    BuildingNotEnoughFuel: "💡 %{fuel} 부족",
    AutoSell: "자동 판매",
    SellAll: "모두 판매",
    Change: "변경",
    StatisticsBureau: "통계국",
    LogisticsDepartment: "물류 부서",
    From: "발송",
    Top20FuelCost: "상위 20 연료 비용",
    To: "도착",
    TransportTime: "운송 시간",
    TopN: "상위 %{n}",
    Warehouse: "창고",
    TradeWarehouse: "화물 창고",
    Coal: "석탄",
    Video: "비디오",
    ClothingFactory: "의류 공장",
    Clothes: "옷",
    Fashion: "패션",
    FashionFactory: "패션 회사",
    VideoFarm: "비디오 팜",
    SantaFactory: "산타 공장",
    Santa: "산타",
    Car: "자동차",
    CarFactory: "자동차 공장",
    Ship: "선박",
    SolarPanel: "태양광 패널",
    SolarPanelDesc: "💡 태양광 패널은 10초 중 5초만 작동합니다 - 모든 동작 주기가 동일합니다",
    WindTurbineDesc: "💡 풍력 터빈은 10초 중 8초만 작동합니다 - 동작 주기가 제각각입니다",
    Movie: "영화",
    MovieStudio: "영화 스튜디오",
    Sitcom: "시트콤",
    TVStudio: "TV 스튜디오",
    PC: "PC",
    GameStudio: "게임 회사",
    Game: "게임",
    ComputerFactory: "컴퓨터 공장",
    Shipyard: "조선소",
    PowerUsage: "전력 사용량",
    PowerSupply: "전력 공급량",
    PowerSurplus: "남는 전력",
    Level: "레벨",
    Power: "전력",
    CentralBank: "중앙 은행",
    ResourceInput: "입력",
    ResourceOutput: "출력",
    ResourceStorage: "저장량",
    ResourceChange: "변동",
    ResourceInOutDesc: "💡 해당 출력 및 입력 건물을 강조 표시하려면 위의 출력-입력 번호를 누르세요",
    ResourceChart: "자원 차트",
    MarketUpdateIn: "%{time} 후 시장 업데이트",
    Income: "수입",
    Semiconductor: "반도체",
    SemiconductorFactory: "반도체 공장",
    Steel: "강철",
    Bitcoin: "비트코인",
    BitcoinFarm: "비트코인 채굴장",
    Dogecoin: "도지코인",
    DogecoinFarm: "도지코인 채굴장",
    Guitar: "기타",
    GuitarFactory: "기타 공장",
    Drum: "드럼",
    DrumFactory: "드럼 공장",
    RecordingStudio: "녹음 스튜디오",
    OperaHouse: "오페라 하우스",
    CoalGasificationPlant: "석탄 기화 공장",
    GasProcessingPlant: "가스 처리 공장",
    Music: "음악",
    Glass: "유리",
    PhoneFactory: "스마트폰 공장",
    Phone: "스마트폰",
    GlassFactory: "유리 공장",
    Oil: "원유",
    Chromium: "크롬",
    ChromiumMine: "크롬 광산",
    Uranium: "우라늄",
    EnrichedUranium: "농축 우라늄",
    NuclearPowerPlant: "핵발전소",
    UraniumEnrichmentPlant: "우라늄 농축 시설",
    UraniumMine: "우라늄 광산",
    Titanium: "티타늄",
    TitaniumMine: "티타늄 광산",
    TitaniumAlloyPlant: "티타늄 합금 공장",
    ChromiumAlloyPlant: "크롬 합금 공장",
    Input: "입력",
    PanelPosition: "패널 위치",
    PanelPositionDesc: "왼쪽, 오른쪽 또는 자동에 측면 패널 표시 (현재 선택한 타일에 따라 다름)",
    InputCapacity: "입력 용량",
    InputCapacityPerCycle: "입력 용량 / 사이클",
    Output: "출력",
    OutputCapacity: "출력 용량",
    OutputCapacityPerCycle: "출력 용량 / 사이클",
    ResourceDeposit: "자원 매장층",
    RecommendedBuilding: "💡 이 타일에는 %{resource} 매장층이 있습니다",
    AdjacentBonus: "인접 보너스",
    AdjacentBonusDesc: "같은 유형의 인접한 모든 작업 건물에 대해 %{bonus}% 추가 용량을 얻습니다",
    ConsiderIncreaseProduction: "💡 %{resource} 생산량 증가 고려",
    AlwaysTransportInput: "비축 모드",
    AlwaysTransportInputTradeCenter: "항상 내보내기",
    AlwaysTransportInputTradeCenterDesc:
        "해당 자원에 대해 자동 판매가 활성화되지 않은 경우에도 항상 자원을 무역센터로 전송",
    AlwaysTransportInputDesc: "생산에 필요한 최소량을 초과하더라도 항상 입력 자원을 전송합니다",
    ProductionCycleLength: "생산주기",
    ProductionCycleLengthDesc:
        "생산주기의 기간(초). 주기를 연장하면 주기 당 입/출력이 증가하므로 입력 자원을 가져올 때 우선 순위가 낮아집니다",
    MaxInputDistance: "최대 입력 거리",
    MaxInputDistanceDesc: "건물에서 입력 리소스를 가져올 수 있는 최대 거리(타일 수)",
    AutoSellCapacity: "자동 판매 용량",
    AutoSellCapacityDesc: "자동 판매가 처리할 수 있는 초당 자원량",
    CurrentAutoSellCapacityMultiplier: "현재 승수: x%{n}",
    AutoSellConcurrency: "자동 판매 종류",
    AutoSellConcurrencyDesc: "자동 판매가 동시에 처리 할 수 있는 최대 자원 종류",
    MaxAutoSellConcurrencyReached:
        "자동 판매를 할 수 있는 최대치입니다. 이 기능을 사용하려면 다른 자동 판매를 끄십시오",
    CannotSellBuilding: "현재 건물을 팔 수 없습니다",
    WallStreet: "월 스트리트",
    MarketCap: "시가 총액",
    MarketCapDesc: "당신 회사의 시가 총액(시장 가치)",
    BuildingValuation: "건물 평가",
    BuildingValuationDesc: "건물 허가 및 업그레이드를 포함한 건물의 총 가치",
    ResourcesValuation: "자원 평가",
    ResourcesValuationDesc: "재고에 있는 자원의 총 가치",
    Battery: "배터리",
    BatteryFactory: "배터리 공장",
    RatingBuy: "구매",
    RatingSell: "판매",
    SwissShop: "스위스 상점",
    RatingHold: "보류",
    RatingOutperform: "능가",
    RatingUnderperform: "부진",
    StockRating: "주식 등급",
    JetEngine: "제트 엔진",
    Helicopter: "헬리콥터",
    Lithium: "리튬",
    LithiumMine: "리튬 광산",
    LiionBatteryFactory: "리튬-이온 배터리 공장",
    HelicopterFactory: "헬리콥터 공장",
    Satellite: "인공위성",
    ToyFactory: "장난감 공장",
    Toy: "장난감",
    SpaceStation: "우주 정거장",
    SpaceStationFactory: "우주 정거장 공장",
    OperatingSystem: "운영 체제",
    OperatingSystemCompany: "운영 체제 개발사",
    LinuxDistribution: "리눅스 배포",
    Internet: "인터넷",
    WebBrowser: "웹 브라우저",
    Console: "콘솔",
    ConsoleFactory: "콘솔 회사",
    Train: "기차",
    TrainFactory: "기차 공장",
    ShoeFactory: "신발 공장",
    Shoes: "신발",
    ArtilleryFactory: "대포 공장",
    Artillery: "대포",
    SubmarineFactory: "잠수함 조선소",
    Submarine: "잠수함",
    Spaceship: "우주선",
    RobotFactory: "로봇 공장",
    Robot: "로봇",
    SpaceshipFactory: "우주선 공장",
    SatelliteFactory: "인공위성 공장",
    JetEngineFactory: "제트 엔진 공장",
    StockRatingDesc: "월스트리트 분석가의 주식 평가 합의는 시가 총액에 영향을 미치며 시장과 함께 새로 고침됩니다",
    InterestRate: "야간 이자율",
    InterestRateDesc: "오프라인 상태에서 시가 총액에 대한 이자",
    OfflineEarning: "오프라인 수입",
    OfflineEarningDesc: "오프라인 수입은 시가 총액과 이자율에 따라 다릅니다",
    PerMin: "%{amount}/분",
    OfflineEarningTime: "오프라인 수입 시간",
    OfflineEarningTimeDesc: "이 시간까지 오프라인 수입을 얻을 수 있습니다",
    BuyPermit: "건축 허가 구매",
    NotEnoughBuildingPermit: "건축 허가가 충분하지 않습니다. 새 건물을 짓기 위해 더 구입하십시오",
    MovingAverage: "이동 평균",
    MovingAverageDesc: "실시간 변경 대신 자원 변경의 이동 평균 표시",
    AllowZoom: "확대",
    AllowZoomDesc: "확대 지원을 켜십시오. 확대하려면 마우스 휠을 사용하십시오. 현재 확대 배율은 %{zoom} 입니다",
    AllowZoomMobileDesc: "확대 지원을 켜십시오. 손가락을 모아 확대할 수 있습니다. 현재 확대 배율은 %{zoom} 입니다",
    Settings: "설정",
    Sound: "사운드 효과",
    SoundDesc: "클릭 또는 오류 같은 사운드 효과 켜기",
    AutoHighlight: "자동 강조",
    AutoHighlightDesc: "건물을 선택할 때 동일한 유형의 건물을 자동으로 강조 표시",
    MusicDesc: "음악 켜기: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "제작 참여",
    Icons: "아이콘",
    MisplacedBuilding: "⛔ 이 %{building} 은 올바른 자원 매장층 위에 배치되지 않았습니다",
    Left: "왼쪽",
    Right: "오른쪽",
    Auto: "자동",
    HighlightBuildings: "건물 하이라이트",
    HighlightTurnedOff: "...꺼진 건물",
    HighlightStockpileModeOn: "...비축 모드가 켜져있는 경우",
    HighlightProductionCycleNotDefault: "...생산주기 > 1",
    HighlightMaxInputDistanceNotDefault: "...최대 입력 거리 < ∞",
    HighlightNotMakingProfit: "...이익을 내지 못 함 ",
    NBuildingsAreHighlighted: "%{n} 개의 건물이 강조 표시되었습니다",
    OnlyToWarehouse: "창고 전용",
    OnlyToWarehouseDesc: "창고로만 자원을 보냅니다",
    TurnOffProduction: "꺼짐",
    TurnOffProductionDesc: "건물의 생산을 중단합니다. 건물은 더 이상 자원을 수송하거나 전력을 사용하지 않을 것입니다",
    ApplyToAll: "모든 %{building}에 적용",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "무제한",
    Transport: "수송",
    TileModifier: "타일 보정",
    ShowAllModifiers: "모든 보정 보기",
    HideAllModifiers: "모든 보정 숨기기",
    NumberOfBuildings: "소유한 건물 수",
    ShowContent: "컨텐츠 보기",
    HideContent: "컨텐츠 숨기기",
    BuyExpansionPack: "%{price}에 구매",
    Cities: "도시",
    InputStrategy: "입력 전략",
    InputStrategyClose: "가까운 것 우선",
    InputStrategyCloseDesc: "충분한 자원이 있는 가장 가까운 창고를 선호합니다",
    InputStrategyFar: "먼 것 우선",
    InputStrategyFarDesc: "충분한 자원이 있는 가장 먼 창고를 선호합니다",
    InputStrategyAmount: "많은 양 우선",
    InputStrategyAmountDesc: "거리에 관계 없이 자원이 가장 많은 창고를 선호합니다",
    FuelCostSave: "연료 비용 절약",
    FuelCostSaveDesc:
        "창고는 내부로 자원을 운반할 때 다른 건물에 비해 일정 비율의 연료를 절약합니다. 레벨이 높을수록 절약 효과가 높습니다",
    SoftwareCompany: "소프트웨어 회사",
    Software: "소프트웨어",
    ScreenFactory: "디스플레이 공장",
    Screen: "디스플레이",
    JoinDiscord: "최신 업데이트, 팁 및 토론을 위해 Discord 서버에 가입하세요",
    ClaimOfflineEarning: "오프라인 수입 청구",
    OfflineTime: "오프라인 시간",
    Minutes: "%{time}분",
    MaxUpgrade: "최대 업그레이드",
    MaxUpgradeDesc: "최대 업그레이드에 도달했습니다",
    ClaimAmount: "현금 +%{amount}",
    EarningPerMinute: "수익률",
    EffectiveTime: "유효 시간",
    EffectiveTimeDesc: "유효 오프라인 수입 시간은 %{time}분으로 제한됩니다.",
    BuildSearchPlaceholder: "검색할 건물 또는 자원 입력",
    MineOverlayWarning: "%{building} 은 타일 보정을 받지 않습니다",
    WholesaleCenter: "도매 센터",
    OrderFrom: "%{name} 에서 주문",
    ExpireIn: "만료",
    TurnOnAllProductions: "생산 켜기",
    TurnOnAllProductionsDesc: "모든 건물의 생산을 켭니다. 비용 절약 정책이 활성화되면 사용할 수 없습니다",
    OperationSuccessful: "작업이 성공적으로 완료되었습니다",
    TurnOn: "켜기",
    Reward: "보상",
    PerSecond: "%{time}/초",
    PerCycle: "%{amount}/사이클",
    PolicyPoint: "정책 점수",
    PolicyPointPerMinute: "분당 정책점수",
    PolicyPointPerMinuteDesc: "게임에서 매 분마다 정책 점수를 획득합니다",
    YourWilLGaimPolicyPoints: "%{time}초 후에 %{amount} 정책 점수를 얻을 수 있습니다",
    PolicyPointDesc: "💡 정책이 더 활성화 될수록 각 정책에 더 많은 비용이 듭니다",
    NextOrderIn: "다음 주문",
    FillOrder: "주문 채우기",
    RejectOrder: "거절",
    WholesaleCenterLocked:
        "도매 센터를 잠금 해제하려면 최소 %{required} 개의 다른 자원이 필요합니다. %{current} 개의 자원만 있습니다",
    OrderFilled: "%{from} 의 주문이 성공적으로 완료되었습니다!",
    PolicyCenter: "정책 센터",
    NewOrder: "%{from} 의 새 주문이 도착했습니다, 도메 센터에서 확인하십시오",
    Policies: "정책",
    PolicyNotEnoughTime: "이 정책에 대한 정책 점수가 충분하지 않습니다",
    TimeLeft: "%{time} 남음",
    WholesaleCenterOrderFaster: "세계 박람회",
    WholesaleCenterOrderFasterDesc: "도매 센터는 주문을 2배 더 빨리 받고 주문량이 2배 더 많습니다",
    PolicyOilWellPowerx2: "과급 유정",
    PolicyOilWellPowerx2Desc: "유정은 2배의 원유를 생산하고 2배의 전력을 사용합니다",
    HalfTransportSpeed: "절약을 위해 천천히",
    HalfTransportSpeedDesc: "운송 속도가 25% 감소하고 연료비가 25% 감소합니다",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "정유 공장은 가솔린을 50% 더 생산하고 플라스틱을 50% 더 적게 생산합니다",
    StickyInput: "고정 입력",
    StickyInputDesc:
        "건물은 매 주기마다 최상의 입력을 검색하는 대신 이전 입력에서 전송하는 것을 선호합니다 (무료 정책)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "정유 공장은 가솔린을 50% 덜 생산하고 플라스틱을 50% 더 생산합니다",
    FreeOilTransportDesc: "원유 운송은 비용이 들지 않지만 유정은 2배의 전력을 사용합니다",
    SuperSteelMill: "철의 심장",
    SuperSteelMillDesc: "제철소는 석탄을 50% 적게 사용하고 철은 25% 더 많이 사용하며 전력은 25% 더 많이 사용합니다",
    AlSemiconductor: "Al 회로",
    AlSemiconductorDesc: "파운드리는 구리 대신 알루미늄을 사용합니다",
    CostSaver: "비용 절약",
    CostSaverDesc: "건물의 투입물이 산출물보다 더 비싸면 생산을 중단합니다",
    CostSaverBuildingDesc: "C비용 절약 정책이 활성화되어 있으며 수익성에 따라 생산이 자동으로 켜지거나 꺼집니다",
    CostSaverBuildingWarning: "비용 절약 정책이 활성화되어 있으며 생산을 수동으로 변경할 수 없습니다",
    GlassUseCoal: "검은 유리",
    GlassUseCoalDesc: "유리 공장은 석탄을 50% 더 많이 사용하고 규소를 50% 더 적게 사용합니다",
    AdjacentBonusOnlyOutput: "인접 보너스 플러스",
    AdjacentBonusOnlyOutputDesc:
        "인접 보너스는 더 많은 입력이 필요하지 않지만 더 많은 전력을 사용하고 50% 만 효과적입니다",
    IronMine2xOutput: "중철",
    IronMine2xOutputDesc: "철 광산은 2배의 철을 생산하지만 철 수송에 드는 연료는 2배가 됩니다",
    SolarPanelAlwaysWork: "태양은 결코 지지 않는다",
    SolarPanelAlwaysWorkDesc: "태양 전지판은 항상 작동하지만 전력을 60% 적게 생산합니다",
    SteelScience: "강철을 통한 지식",
    SteelScienceDesc: "제철소는 2배의 입력을 사용하고 추가 과학을 생산합니다",
    WholesaleCenterProducingOnly: "도매 파트너",
    WholesaleCenterProducingOnlyDesc:
        "도매 센터 주문에는 현재 생산중인 자원만 포함됩니다 (도매 센터를 잠금 해제하려면 필요한 자원을 생산해야 함)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "자원의 생산 능력이 부족하면 무역 센터에서 자동으로 부족량을 구매합니다. (자원이 자동 판매가 되면 무시됩니다)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree 정책이 켜져 있습니다. 무역 센터는 부족한 자원을 자동으로 구매합니다",
    ExtraPolicyPoints: "정치 로비스트",
    ExtraPolicyPointsDesc: "정책 포인트 생산 능력을 50% 증가",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "크롬 합금 공장은 리튬을 사용하지 않고 대신 철을 2배로 사용합니다",
    DoubleTileModifier: "자연의 힘",
    DoubleTileModifierDesc: "모든 타일 보정 효과를 2배로 합니다 - 양수 및 음수 모두",
    TileModifierOutputOnly: "타일 보정 플러스",
    TileModifierOutputOnlyDesc: "타일 보정은 입력과 출력이 아닌 출력에만 영향을 주지만 50% 만 효과적입니다",
    GasPlantPetrol: "가스 액화기",
    GasPlantPetrolDesc: "가스 발전소는 추가 가스를 사용하여 휘발유를 생산합니다",
    BuildingRecycle: "건물 재활용",
    BuildingRecycleDesc: "건축 후 1분 이내에 건물을 판매했다면 전액 환불을 받으세요",
    CoalPlantFuel: "석탄 액화기",
    CoalPlantFuelDesc: "석탄 발전소는 추가 석탄을 사용하여 휘발유를 생산합니다",
    Welcome: "환영합니다",
    SeeTutorialAgain: "튜토리얼 재실행",
    HelpTranslateTheGame: "게임 번역을 도와주세요🌐",
    SkipTutorial: "튜토리얼 건너 뛰기",
    NextTutorial: "다음",
    Tutorial1:
        "Industry Idle은 공장🏭을 짓고, 상품📦을 생산하고 돈💸을 벌 수 있는 <em>자원 관리</em> 게임입니다.<br><br> 시작하기 위해 몇 가지 기본 개념을 살펴 보겠습니다. 오래 걸리지 않아요, 약속해요.",
    Tutorial2:
        "모든 건물에는 전력⚡이 필요합니다. 전력을 생성하는 <em>풍력 터빈</em>이 있습니다. 상단 막대의 왼쪽에서 현재 전력 공급을 확인할 수 있습니다.<br><br>풍력 터빈은 시간의 <em>80%</em>만 동작합니다. 안정적인 전력을 생성하는 다른 유형의 발전소를 건설하는 것을 고려할 수 있습니다.",
    Tutorial3:
        "지도에 많은 <em>자원 매장지</em>가 있습니다. 자원을 추출하려면 해당 매장지 <em>위에</em> 광산⛏️을 건설해야합니다. <br><br> 예를 들어, 석유 매장지에서 <em> 석유</em>를 추출하는 <em> 유정🛢️</em>이 있습니다. <br></br> 자원 매장량은 무제한이므로 고갈에 대해 걱정할 필요가 없습니다. 광산을 제외하고는 빈 타일에 다른 건물을 지을 수 있습니다.",
    Tutorial5:
        "돈을 벌려면 무역 센터를 통해 자원을 내보내야 합니다. 이렇게 하려면 해당 리소스에 대해 <em>자동 판매</em>를 설정하기만 하면 됩니다. <br></br> 또한 무역 센터도 마찬가지입니다. <em>자원을 구입하면 가격이 상승</em>하고 자원을 판매하면 가격이 하락합니다. <br> <br> 시장은 <em>변덕스럽고</em> 가격📈은 정기적으로 변경됩니다.",
    Tutorial6:
        "새 건물을 건설하려면 먼저 <em>연구실🧪</em>에서 잠금을 해제해야 합니다. 연구실은 과학을 연구 점수로 전환합니다. <br><br>풍력 터빈(및 기타 발전소)은 동작 중일 때 소량의 과학을 생산합니다. 그리고 나중에 과학을 늘리기 위해 학교🏫 및 기타 전용 건물을 지을 수 있습니다. <br><br> 이제 모든 기본 사항을 배웠고 경제를 구축하기 시작하세요! 여기 약간의 <em>돈💸 </em>과 <em>휘발유⛽</em>로 시작해보세요.",
    WelcomePlay: "재생",
    WelcomePlayMuted: "재생 (🔇음악)",
    Changelog: "변경 내역",
    ChangelogGotIt: "알았다",
    Chat: "채팅",
    Send: "보내기",
    Import: "가져오기",
    Export: "내보내기",
    LastBackupAt: "마지막 백업",
    RestoreFromBackup: "백업에서 복원",
    RestoreFromBackupFail: "Steam 클라우드에서 백업을 복원하지 못했습니다 : 백업이 있습니까?",
    RestoreFromBackupTitle: "계속 하시겠습니까?",
    RestoreFromBackupDesc:
        "로컬 저장이 손실되지 않는 한 일반적으로 클라우드 백업에서 복원할 필요가 없습니다. 클라우드 백업은 로컬 저장보다 약간 오래되었습니다.",
    ChatMessages: "채팅 메시지",
    ChangeName: "변경",
    SaveName: "저장",
    NameValidationRule: "이름은 문자와 숫자만 포함해야하며 5-15자 사이여야 합니다",
    NameValidationRuleProfanity: "이름에 욕설을 포함해서는 안 됩니다",
    ChatMessageRateLimit: "10초마다 새 채팅 메시지를 보낼 수 있습니다",
    NameSaved: "이름이 성공적으로 변경되었습니다",
    NoMessages: "새 메시지 없음",
    Leaderboard: "리더 보드",
    Name: "이름",
    Rank: "순위",
    Tips1: "주식 등급은 매수, 과잉, 보류, 저조 및 매도의 5 단계로 나뉩니다.",
    Tips2: "비축 모드를 설정하지 않는 한, 이미 생산에 충분한 자원이 있는 경우 건물은 자원 운송을 중지합니다",
    Tips3: "자원 수송을 위한 연료비는 거리와 자원의 양에 의해 결정됩니다",
    Tips4: "건물은 지도에서 찾은 양이 입력 용량을 초과하는 경우에만 자원을 수송합니다",
    Tips5: "건물은 해당 자원에 대해 자동 판매가 꺼진 경우에만 무역 센터에서 자원을 운송합니다",
    Tips6: "해당 입력 용량 섹션에서 자원에 대한 연료 비용을 볼 수 있습니다",
    Tips7: "자원을 구매하면 가격이 올라갑니다. 자원을 판매하면 가격이 내려갑니다",
    Tips8: "통계국에서 각 자원의 양과 시간에 따른 변화에 대한 차트를 볼 수 있습니다",
    Tips9: "건물에 필요한 연구 포인트는 입력 자원의 시장 가격에 의해 결정됩니다",
    Tips10: "다른 자원은 시장에서 다르게 가격이 책정됩니다 - 항상 시장 변동성에 대비하십시오",
    Tips11: "생산을 확장하기 전에 항상 전력과 연료 공급을 확인하는 것이 좋습니다",
    FPS30: "에너지 절약",
    OfflineModeDesc: "서버에 연결할 수 없습니다 : 오프라인 수입이 생성되지 않습니다. 인터넷 연결을 확인하십시오",
    OptOut: "옵트 아웃",
    OptIn: "재설정 및 활성화",
    LeaderboardOptOut: "리더 보드 옵트 아웃",
    LeaderboardOptOutDesc:
        "더 이상 리더 보드 점수를 전송하지 않습니다. 참고 : 나중에 리더 보드를 사용하려면 데이터를 재설정해야 합니다.",
    LeaderboardOptIn: "리더 보드 재설정 및 활성화",
    LeaderboardOptInDesc: "리더 보드를 다시 활성화하기 전에 데이터를 재설정해야합니다. 계속 하시겠습니까?",
    RewardAdsFailed: "보상 동영상이 완료되지 않았습니다",
    RewardAdsNotAvailable: "보상 동영상을 사용할 수 없습니다 (현재 iOS/Android 만 지원됨)",
    OfflineEarningDoubleSuccess: "오프라인 수입이 두 배가되었습니다",
    FPS30Desc: "에너지 절약 모드를 켜면 60FPS 대신 30FPS로 게임이 실행됩니다. 배터리가 더 오래 지속됩니다",
    HighlightAll: '강조 표시 "%{type}"',
    HighlightInput: "🔍 %{type} 입력 강조",
    HighlightOutput: "🔍 %{type} 출력 강조",
    TotalInput: "총 입력 용량",
    TotalOutput: "총 출력 용량",
    RunOutIn: "%{time}후 종료",
    FuelRunOutWarning: "💡 연료 소비량이 생산량을 초과합니다. 연료가 떨어지면 운송이 중단됩니다",
    InAmount: "입력: %{number}",
    OutAmount: "출력: %{number}",
    SwissBank: "스위스 은행",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "새로운 도시에서 시작하면, %{money} 💵을 받습니다",
    RestorePurchases: "구매 복원",
    RestorePurchasesSuccess: "구매 내역이 복원되었습니다",
    RestorePurchasesFailed: "구매 내역이 복원되지 않았습니다",
    ExpansionPacks: "확장팩",
    ExpansionPack1: "확장팩1",
    ExpansionPack1Owned: "확장팩1",
    RequireExpansionPack1: "확장팩1",
    RequireExpansionPack1Desc: "확장팩 1에서만 사용할 수 있습니다",
    RequireAnyExpansionPack: "확장팩 전용",
    RequireAnyExpansionPackDesc: "이 기능을 사용하려면 확장팩 중 하나 이상을 소유해야합니다",
    HideRewardAd: "보상형 광고 숨기기",
    HideRewardAdDesc:
        "모든 게임 내 광고는 선택적인 보상형 광고입니다. 이것은 게임에서 모든 보상형 광고 옵션을 숨깁니다.",
    HideDiscordBanner: "Discord 배너 숨기기",
    HideDiscordBannerDesc: "본부에서 Discord 배너 및 상점 배너 숨기기",
    HideChat: "채팅 메시지 숨기기",
    SortedByDeficit: "부족분 순 정렬",
    PurchaseFailed: "구매가 완료되지 않았습니다",
    PurchaseSteamContinue: "Steam에서 구매를 완료하세요",
    PurchaseSuccess: "구매가 완료되었습니다. 지원해 주셔서 감사합니다",
    PrestigeCurrency: "스위스 돈💵",
    RestartDesc: "💡 다시 시작 하시겠습니까? 위의 새로운 도시에서 시작을 누르고 현재 도시를 선택할 수 있습니다",
    PrestigeGoBack: "돌아가기",
    PermanentUpgradeDesc: "이 업그레이드는 새로운 도시에서 시작해도 이어집니다",
    ProductionMultiplier: "생산 승수",
    ProductionMultiplierDesc: "모든 건물의 생산 능력 향상 (광산, 공장, 발전소, 과학 및 문화 건물 포함)",
    FuelCostDiscount: "연료비 절약",
    FuelCostDiscountDesc: "자원을 운송할 때 연료비를 할인합니다",
    AutoSellCapacityMultiplier: "자동 판매 용량 승수",
    AutoSellCapacityMultiplierDesc: "현재 용량에 관계없이 자동 판매 용량에 적용되는 승수",
    BuildingPermitCostDivider: "건물 허가 비용 나누기",
    BuildingPermitCostDividerDesc: "건물 허가 비용 나누기",
    ExtraAdjacentBonus: "추가 인접 보너스",
    ExtraAdjacentBonusDesc: "같은 유형의 인접한 모든 작업 건물에 대한 추가 보너스 용량",
    OfflineEarningMultiplier: "오프라인 수입 승수",
    OfflineEarningMultiplierDesc: "오프라인 수입에 적용되는 승수",
    PrestigeAlertTitle: "확실합니까?",
    PrestigeAlertContent:
        "귀하의 회사는 청산될 것입니다. %{amount}의 스위스 돈을 챙기고 %{city}에서 새로운 회사를 시작합니다",
    PrestigeCurrencyDesc:
        "이것은 당신의 비밀 스위스 은행 계좌에 있는 돈입니다. 새로운 도시에서 시작할 때 가지고 다닐 수 있습니다",
    Prestige: "청산한다",
    Cancel: "취소",
    SaveFileCorrupted: "파일 저장이 손상됨",
    CheatDetected: "이전 저장이 서버 유효성 검사를 통과하지 못했고 읽을 수 없습니다. 새 저장으로 시작됩니다",
    LoadGameError: "게임로드 실패",
    LoadGameErrorMessage: "오류 메시지: %{message}",
    LoadGameErrorDesc: "인터넷 연결을 확인하십시오. 문제가 지속되면 지원팀에 문의하십시오",
    ExpansionPackIncompatible: "확장팩이 있는 저장 파일을 가져오지만, 게임에 필요한 확장팩이 없습니다",
    SaveFileMigrated: "새로운 시대 : 베타가 여기에 있습니다",
    SaveFileMigratedDesc:
        "알파 테스터로 플레이 해 주셔서 감사합니다. 귀하의 이전 맵은 호환되지 않지만 귀하의 데이터를 마이그레이션하여 몇 가지 보너스를 드립니다",
    ClaimSwissMoney: "%{amount} 스위스 돈💵 청구",
    SaveFileMigratedFinePrint:
        "귀하의 시가 총액은 스위스 돈으로 전환되고 사용하지 않은 스위스 돈은 이월됩니다. 알파 플레이 테스트를 위해 50% 보너스 스위스 돈을 받게 됩니다. 이월할 수 있는 최대 스위스 돈은 200으로 제한됩니다.",
    CashIn: "청산한다",
    CurrentCity: "현재 도시",
    CashInDesc:
        "새로운 도시에서 시작하면 이 금액을 스위스 은행 계좌로 받게됩니다. 이 금액은 회사의 시가 총액을 기반으로 하며 스위스 돈을 벌려면 %{amount}에 도달해야 합니다",
    MoveToNewMap: "새로운 도시에서 시작",
    CityName: "도시",
    CitySize: "지도 크기",
    GridType: "그리드 유형",
    StartInThisCity: "%{city}에서 시작",
    CityBonus: "도시 보너스",
    ResourceTilePercentage: "자원 타일",
    MapSquareGrid: "정사각형",
    MapHexGrid: "6각형",
    Stockholm: "스톡홀름",
    Rotterdam: "로테르담",
    RotterdamBonus:
        "<li>제철소 용량 2배</li><li>스테인리스 공장 용량 2배</li><li>무료 철 수송</li><li>강철 수송 연료비 50% 절감</li><li>자동 판매 용량 2배로 시작</li><li>타일 보정 없음</li>",
    Oslo: "오슬로",
    StPetersburg: "상트 페테르부르크",
    Hamburg: "함부르크",
    HamburgBonus:
        "<li>비행선 공장 잠금 해제</li><li>반도체 공장 생산성 2배</li><li>조선소 용량 2배</li><li>자동차 공장 용량 2배</li><li>리튬 이온 배터리 공장 잠금 해제</li>",
    Toulouse: "툴루즈",
    Rome: "로마",
    RomeBonus:
        "<li>콜로세움 잠금 해제</li><li>콜로세움 생산성 2배</li><li>레벨5 정책 센터에서 시작</li><li>오페라 하우스 용량 2배</li><li>녹음 스튜디오도 문화를 만들어냅니다</li>",
    Detroit: "디트로이트",
    Boston: "보스턴",
    BostonBonus:
        "<li>레벨5 연구실에서 시작</li><li>과학기술 전문학교 잠금 해제</li><li>과학기술 전문학교 용량 2배</li><li>학교 용량 2배</li><li>대학 생산성 2배</li>",
    HideNotProducing: "생산되지 않는 자원 숨기기",
    SortByStorage: "저장소",
    SortByProduction: "생산",
    SortByName: "이름",
    PlayerTrade: "사용자 간 거래",
    AddTradeFail: "거래 추가 실패",
    AddTradeExceedMaximumTrade: "최대 %{number}개의 거래만 활성화 할 수 있습니다. 먼저 하나를 청구하거나 취소하십시오",
    AddTradeSuccess: "당신의 거래가 성공적으로 추가되었습니다",
    LoadTradeFail: "플레이어 거래를 불러오지 못했습니다. 나중에 다시 시도하십시오",
    ClaimTradeFail: "이 거래를 청구하지 못했습니다. 나중에 다시 시도하십시오",
    CancelTradeSuccess: "거래가 성공적으로 취소되었습니다",
    CancelTradeFail: "거래를 취소하지 못했습니다. 나중에 다시 시도하십시오",
    AcceptTradeFail: "거래를 수락하지 못했습니다. 나중에 다시 시도하십시오",
    PlayerTradeBanner: "다른 플레이어와 자원 거래",
    PlayerTradeResource: "자원",
    PlayerTradeAmount: "거래량",
    PlayerTradePrice: "가격 $",
    PlayerTradeValue: "가치 $",
    PlayerTradeWaiting: "대기중...",
    UseTradeCenterPrice: "거래 센터 가격 사용",
    AddTrade: "거래 추가",
    ActiveTrades: "활성 거래",
    AcceptTrade: "수락",
    CancelTrade: "취소",
    RefundTrade: "환불",
    RefundTradeSuccess: "이 거래는 환불되었습니다: %{resource}가 거래 센터로 환불되었습니다",
    RefundTradeFail: "거래를 환불하지 못했습니다. 나중에 다시 시도하십시오",
    ClaimTrade: "청구",
    RefreshTrade: "새로 고침",
    PasteYourSave: "저장 데이터를 붙여 넣으십시오",
    FailedToImportSave: "저장 가져 오기 실패",
    FailedToImportSaveDesc: "저장 파일이 호환되지 않거나 손상되었습니다: %{error}",
    SaveCopiedToClipboard: "저장 데이터가 클립 보드에 복사되었습니다",
    CancelActiveTradeFirst: "활성중인 사용자 간 거래가 있습니다. 먼저 취소/청구하십시오",
    FailedToCheckActiveTrade: "활성중인 사용자 간 거래를 확인하지 못했습니다. 나중에 다시 시도하십시오",
    PlayerTradeQuotaExceed: "이 거래는 한도를 초과했습니다",
    PlayerTradeValidRange: "범위: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "감당할 수 있는",
    PlayerTradeQuota: "남은 한도: %{value}",
    PlayerTradeUnavailable: "사용자와 거래하기 전에 생산 및 보관에 최소한 하나의 자원이 있어야 합니다",
    PlayerTradeToClaim: "사용자 간 거래에서 청구할 새로운 거래가 %{num}개 있습니다",
    PowerBank: "보조 배터리",
    PowerBankBuildDesc: "잉여 전력을 저장하고 부족시 전원 공급",
    WarehouseBuildDesc: "더 낮은 연료비로 모든 자원을 운송 및 저장",
    PowerBankChargeSpeed: "충전 속도",
    PowerBankPowerLeft: "남은 전력",
    PowerBankMoreCapacity: "배터리 절약",
    PowerBankMoreCapacityDesc: "보조 배터리는 50% 속도로 충전되지만 용량은 50% 더 많습니다",
    PowerBankNotWorking: "⛔ 보조 배터리는 발전소 옆에서만 작동합니다",
    ExcludeBuildingsShutdown: "폐쇄된 건물 제외",
    ColorTheme: "게임 색상 테마",
    ColorThemeDesc: "게임 아이콘, 하이라이트, 그리드 및 배경에 대한 색상 테마. 다시 로드해야 합니다.",
    SiliconMine2xOutput: "실리콘 밸리",
    SiliconMine2xOutputDesc:
        "규소 광산은 2배의 규소를 생산하지만 50% 더 많은 전력을 사용하고 규소 운송에 50% 더 많은 연료를 소비합니다",
    CoalMine2xOutput: "산업 혁명",
    CoalMine2xOutputDesc:
        "석탄 광산은 2배의 석탄을 생산하지만 전력을 50% 더 사용하고 석탄 운송에 50% 더 많은 연료를 소비합니다",
    AlMine2xOutput: "알루미늄 제련",
    AlMine2xOutputDesc: "알루미늄 광산은 2배의 알루미늄을 생산하고 2배 더 많은 전력을 사용합니다",
    LoggingCamp2xOutput: "삼림 벌채",
    LoggingCamp2xOutputDesc: "벌목소는 2배의 나무를 생산하고 나무 운송 비용이 2배가 됩니다",
    HideResourceMovement: "자원 이동 숨기기",
    HideResourceMovementDesc: "기본적으로 자원 이동(작은 점)을 숨기고 건물을 선택할 때만 이동을 표시합니다",
    PowerBankLeft: "보조 배터리",
    ColorThemeEditor: "색상 테마 편집기",
    ColorThemeEditorDesc: "현재 테마의 색상을 재정의 할 수 있습니다. 현재 %{num}개의 재정의가 있습니다",
    ColorThemeEditorSave: "저장",
    ColorThemeEditorReset: "재설정",
    ColorThemeEditorResetAll: "모두 재설정",
    NewMessageMentions: "당신을 언급한 새 메시지가 있습니다: %{message}",
    HideChatMentions: "채팅 멘션 숨기기",
    HideChatMentionsDesc: "채팅 메시지에서 나를 언급할 때 소리 및 토스트 알림 숨기기,",
    PendingConstructionCannotReload: "건물 건설이 진행 중입니다. 게임을 다시 로드할 수 없습니다",
    AcceptTradeFailRateLimit: "%{time}초마다 하나의 거래만 수락 할 수 있습니다",
    DowngradeBuilding: "다운 그레이드",
    CancelTradeConfirmDialogTitle: "이 거래를 취소 하시겠습니까?",
    CancelTradeConfirmDialogYes: "예",
    CancelTradeConfirmDialogNo: "아니요",
    WarehouseInputRoutes: "입력 경로",
    WarehouseAddInput: "경로 추가",
    WarehouseTapToSelect: "고를 지도를 누르세요...",
    WarehouseFindOnMap: "🔍 지도에서 찾기",
    WarehouseRemoveRoute: "제거",
    WarehouseAddRouteFail: "경로 추가 실패: 선택한 타일이 유효한 입력이 아닙니다",
    LevelN: "레벨 %{level}",
    Surplus: "잉여",
    Production: "생산",
    Consumption: "소비",
    WarehouseInputCapacityDescV2: "모든 경로에 균등하게 나눠진, 내부 운송의 총 용량",
    WarehouseInputCapacityPerRoute: "경로별: ",
    PlayerCountryFlag: "플레이어 국기",
    PlayerCountryChooseFlag: "국가 코드의 알파벳 순서",
    WindTurbineAlwaysWork: "바람이 분다",
    WindTurbineAlwaysWorkDesc: "풍력 터빈은 100% 동작하지만 30% 적은 전력을 생산합니다",
    BookPublisherScience: "과학 문학",
    BookPublisherScienceDesc: "출판사가 문화 대신 과학을 생산합니다",
    WarehouseOutwardFuelSave: "무료 배송",
    WarehouseOutwardFuelSaveDesc: "창고는 외부 운송시에도 동일하게 연료를 절약합니다",
    ImportSaveVersionTooNew:
        "%{saveVersion}에서 저장 파일을 가져 오지만 게임은 %{gameVersion}입니다. 먼저 게임을 업그레이드하세요",
    BatteryFuelEconomy: "충전식 배터리",
    BatteryFuelEconomyDesc: "배터리 연비가 100% 향상됩니다 (즉, 연료비 50%)",
    ShowTheoreticalInputOutputCapacity: "이론적 입력/출력 용량 표시",
    SpecialTransportCost: "특별 운송 비용이 있는 자원",
    FreeTransportCost: "무료 운송이 되는 자원",
    Osaka: "오사카",
    OsakaBonus:
        "<li>자원이 무리지어 나오는 경향이 있습니다</li><li>창고는 연료를 50% 더 절약합니다</li><li>고유 건물: 만화 출판사</li><li>고유 건물: 애니메이션 스튜디오</li><li>반도체 공장 생산성 2배</li><li>Li-ion 배터리 공장 용량 2배</li><li>배터리 공장 잠금 해제</li><li>배터리 공장 용량 2배</li><li>배터리 연비 100% 향상</li><li>배터리 공장에 석탄이 필요하지 않습니다</li><li>100K 배터리를 가지고 시작</li>",
    HideChatDescV2: "하단 툴바에서 채팅 메시지를 숨깁니다. 채팅 메시지를 표시함으로써 동의합니다",
    HideChatDescV2ToS: "서비스 약관",
    IntegratedCircuitFab: "집적회로 팹",
    MangaPublisher: "만화 출판사",
    Manga: "만화",
    AnimeStudio: "애니메이션 스튜디오",
    Anime: "애니메이션",
    PlayerTradeAction: "행동",
    PlayerTradeBuy: "구매",
    PlayerTradeSell: "판매",
    PlayerTradeBid: "호가",
    PlayerTradeAsk: "요청",
    CancelTradeConfirmDialogDescV2:
        "이 거래를 취소하면 자원/현금의 %{percent}가 환불됩니다. 자원은 무역 센터 창고로 환불됩니다.",
    ClaimTradeSuccessV2: "거래가 성공적으로 청구되었습니다: %{cashOrResource}",
    AcceptTradeSuccessV2: "거래를 수락했습니다: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "시장 가격보다 좋음",
    ResourceExplorer: "자원 탐색가",
    ResourceExplorerDesc: "빈 타일에서 자원을 추출할 수 있습니다",
    ResourceExplorerDescLong: "💡 자원 탐색가는 인접 보너스가 없습니다. 전력 사용량은 자원마다 다릅니다.",
    ResourceExplorerSelectResource: "탐색",
    ProductionSettings: "생산 설정",
    PlayerTradeQuotaDesc: "💡 플레이어 거래 할당량은 시가 총액의 %{percent}이며, 시장이 업데이트되면 재설정됩니다.",
    PlayerTradePartialFillTitle: "채우기 백분율 선택",
    PlayerTradeAmountNotValidV2: "허용되는 최소 거래 금액은 1입니다",
    PlayerTradeOptOut: "리더 보드를 탈퇴했습니다. 다른 플레이어와 거래할 수 없습니다",
    FirstTimeReadGuide: "💡 게임 방법에 대해 약간의 도움이 필요하십니까? 눌러서 초보자 가이드를 읽어보세요!",
    ReadSteamGuideV2: "게임 가이드",
    ReadSteamGuideV2Desc: "Steam에서 커뮤니티가 만든 가이드를 읽을 수 있으며 자신만의 가이드를 만들 수도 있습니다.",
    ChatMessageTooLong: "채팅 메시지가 허용되는 최대 문자 수를 초과했습니다",
    ChatPlaceholderV2: "메시지 입력: 최대 %{length}자",
    ShowProfitBreakdown: "이익 분석 표시",
    HideProfitBreakdown: "이익 분석 숨기기",
    ProfitBreakdownOutput: "%{res} 출력",
    ProfitBreakdownInput: "%{res} 입력",
    ProfitBreakdownFuel: "연료 비용",
    BuildingProfit: "이익",
    RestoreBackup: "복원",
    SteamLogin: "Steam을 통해 로그인",
    SteamLoginDialogDesc:
        "로컬 저장에 확장팩이 활성화되어 있습니다. 계속하려면 Steam을 통해 로그인해야 합니다. 또는 로컬 저장을 지우고 다시 시작할 수 있습니다",
    SteamLoginDesc: "Steam에서 확장팩을 소유하고 있다면 로그인 후 웹에서 확장팩으로 플레이할 수 있습니다",
    SteamLoginYes: "로그인",
    SteamLoginNo: "지우기 및 다시 시작",
    KungFuDojo: "쿵푸 도장",
    KungFu: "쿵푸",
    TaiChi: "태극권",
    TaiChiDojo: "태극권 도장",
    HongKong: "홍콩",
    FreeTransportToTradeCenter: "국제 수출 무역",
    FreeTransportToTradeCenterDesc:
        "무역 센터로의 운송에는 연료 비용이 들지 않지만, 무역 센터에서 나가는 운송은 연료 비용이 50% 더 많이 든다",
    TaiChi10xCulture: "동양의 진주",
    PlayerTradeYouHave: "저장량: %{amount}",
    PlayerTradeFillValue: "가치",
    FiberFactory: "섬유 공장",
    Fiber: "섬유",
    Achievements: "업적",
    AchievementsDesc: "%{total} 개의 업적 중 %{number} 개를 달성했습니다",
    AchievementsReward: "보상: 스위스 돈 +%{swiss}",
    AchievementsRewardToast: "보상을 요청하셨습니다: 스위스 돈 +%{swiss}",
    AchievementsClaim: "청구",
    AchievementsToast: "%{name}을 달성했습니다. 본사에서 보상을 받으십시오",
    AchievementStockholm100: "바이킹 신입생",
    AchievementStockholm100Desc: "스톡홀름에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementStockholm500: "바이킹 졸업생",
    AchievementStockholm500Desc: "스톡홀름에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementStockholm1000: "경험 있는 바이킹",
    AchievementStockholm1000Desc: "스톡홀름에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementOslo100: "노르웨이 석유 애호가",
    AchievementOslo100Desc: "오슬로에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementOslo500: "노르웨이 석유 열성지지자",
    AchievementOslo500Desc: "오슬로에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementOslo1000: "노르웨이 석유 거물",
    AchievementOslo1000Desc: "오슬로에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementRotterdam100: "바람개비 주인",
    AchievementRotterdam100Desc: "로테르담에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementRotterdam500: "풍차 주인",
    AchievementRotterdam500Desc: "로테르담에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementRotterdam1000: "풍력 터빈 주인",
    AchievementRotterdam1000Desc: "로테르담에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementDetroit100: "동네 자동차 판매점",
    AchievementDetroit100Desc: "디트로이트에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementDetroit500: "지역 자동차 유통 업체",
    AchievementDetroit500Desc: "디트로이트에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementDetroit1000: "국가 자동차 독점",
    AchievementDetroit1000Desc: "디트로이트에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementBoston100: "돈 버는 학사",
    AchievementBoston100Desc: "보스턴에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementBoston500: "돈 긁어모으기의 석사",
    AchievementBoston500Desc: "보스턴에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementBoston1000: "돈 복사의 박사",
    AchievementBoston1000Desc: "보스턴에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementRome100: "디오클레티아누스",
    AchievementRome100Desc: "로마에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementRome500: "콘스탄티누스 1세",
    AchievementRome500Desc: "로마에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementRome1000: "카이사르 아우구스투스",
    AchievementRome1000Desc: "로마에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "함부르크에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "함부르크에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "함부르크에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "툴루즈에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "툴루즈에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "툴루즈에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementHongKong100: "취미로 거래하는 사람",
    AchievementHongKong100Desc: "홍콩에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementHongKong500: "프로 중개인",
    AchievementHongKong500Desc: "홍콩에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementHongKong1000: "헤지펀드 매니저",
    AchievementHongKong1000Desc: "홍콩에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementStPetersburg100: "대공",
    AchievementStPetersburg100Desc: "상트 페테르부르크에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementStPetersburg500: "체사레비치",
    AchievementStPetersburg500Desc: "상트 페테르부르크에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementStPetersburg1000: "모든 러시아의 차르",
    AchievementStPetersburg1000Desc: "상트 페테르부르크에서 한 번의 실행으로 1000 스위스 돈 벌기",
    AchievementOsaka100: "단 샤쿠",
    AchievementOsaka100Desc: "오사카에서 한 번의 실행으로 100 스위스 돈 벌기",
    AchievementOsaka500: "하쿠 샤쿠",
    AchievementOsaka500Desc: "오사카에서 한 번의 실행으로 500 스위스 돈 벌기",
    AchievementOsaka1000: "고 샤쿠",
    AchievementOsaka1000Desc: "오사카에서 한 번의 실행으로 1000 스위스 돈 벌기",
    SteamAutoCloudBackup: "Steam 클라우드 자동 백업",
    SteamAutoCloudBackupFailed: "Steam 클라우드 자동 백업 실패: %{error}",
    SteamManualBackup: "강제 Steam 클라우드 동기화",
    UILoading: "로드 중...",
    UserAuthenticated: "인증되었습니다",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardBySwissPerBuilding: "Current Swiss Money Per Building",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Save and Exit Game",
    SaveAndExitDesc:
        "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Force Scroll",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ResourceExplorer2Desc: "Resource explorers produce 2x output but use 2x power",
    ConstructionCancel: "Cancel Construction",
    ConstructionPause: "Pause",
    ConstructionResume: "Resume",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
    HighlightUnderConstruction: "...that haven't been constructed",
    HighlightUnderLevel10: "...that are under level 10",
    HighlightUnderLevel20: "...that are under level 20",
    HighlightUnderLevel30: "...that are under level 30",
    Logout: "You Are Logged Out",
    ConstructionStatusQueueingV2: "Queueing",
    ConstructionStatusPausedV2: "Paused",
    ConstructionStatusBuildingV2: "Building",
    ConstructionStatusUnpaidV2: "Unpaid",
    ConstructionStatus: "Construction Status",
    ConstructionStart: "Start",
    CostFree: "Free",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Only you",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "increased by %{percent}",
    MarketNewsDecrease: "decreased by %{percent}",
    MarketNewsBuilding: "This building is affected by %{num} news",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    OsloBonusV2:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Resource Booster",
    BuildWarningTitle: "Building Might Not Work",
    BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
    BuildWarningBuildAnyway: "Build Anyway",
    ResourceBoosterNotWorking: "⛔ Resource boosters only work next to deposit mines",
    ResourceBoosterPercentage: "💡 This building gets %{percent} output boost from adjacent resource boosters",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
    BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "Have 50 production lines that has production deficit",
    UseScientificNotation: "Use Scientific Notation",
    UseScientificNotationDesc: "Use scientific notation (e notation) for numbers larger than 999.9T",
    LogoutDescV2:
        "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
    LogBackIn: "Log Back In",
    PlayerTradeNowAllowedV2: "Player trades are not available within %{hour} hours of restoring/importing a save",
    ServerDisconnected:
        "You are disconnected from the server, please check your internet connection and restart the game",
    BuildingUpgradeCostDividerDescV2: "Divide building upgrade cost by this divider",
    ResourceBoosterBannerDesc:
        "💡 You currently have %{number} resource boosters - the power and science input of each is scaled to the number of resource boosters you currently have",
    ResourceBoosterDesc: "Boost the output of adjacent mines",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Dynamite Factory",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Nuclear Missile Factory",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Space Colony",
    SpaceColonyInc: "Space Colony",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    IronSteelZone: "Iron Steel Zone",
    IronSteelZoneDesc:
        "Resource booster provide a %{percent} output bonus to adjacent steel mills or stainless steel plants for each working iron mine it is boosting",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
    ToulouseBonusV2:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
};
