export const KR = {
    Translator: "번역자",
    TranslatorName: "zed",
    Language: "언어",
    ThisLanguage: "한국어",
    OK: "OK",
    SteelMill: "제철소",
    StainlessSteelPlant: "스테인리스 공장",
    CircuitFoundry: "파운드리",
    IntegratedCircuit: "집적 회로",
    OilWell: "유정",
    Wood: "나무",
    LoggingCamp: "벌목소",
    LumberMill: "제재소",
    Lumber: "목재",
    Paper: "종이",
    PaperMill: "제지 공장",
    Book: "책",
    BookPublisher: "출판사",
    OilRefinery: "정유소",
    Sell: "판매",
    Upgrade: "업그레이드",
    Build: "건설",
    Inspect: "검사",
    Buildings: "건물",
    Iron: "철",
    Actions: "작업",
    FuelType: "연료 선택",
    FuelCost: "연료 가격",
    FuelConsumption: "%{fuel} 소비",
    FuelEconomy: "연비",
    FuelProduction: "%{fuel} 생산",
    FuelInStorage: "%{fuel} 재고",
    Plastic: "플라스틱",
    FuelSurplus: "%{fuel} 과잉",
    Petrol: "가솔린",
    Buy: "구매",
    NoLiquidity: "유동성 없음",
    NoLiquidityTurnOffAutoSell: "시장에 %{res}에 대한 유동성이 충분하지 않습니다. 자동 판매가 꺼졌습니다.",
    Multiplier: "승수",
    MultiplierDesc: "10 레벨마다 +1 승수를 얻습니다.",
    SellBuilding: "건물 판매",
    PowerGrid: "전력망",
    TradeAmount: "거래 금액",
    SortBy: "정렬",
    SortByPrice: "가격",
    SortByAmount: "재고",
    NotEnoughResourcesForTrade: "거래를 위한 무역 센터의 자원이 충분하지 않습니다.",
    NotEnoughResources: "작업에 대한 자원이 충분하지 않습니다.",
    Transportation: "수송",
    Cash: "자금",
    Aluminum: "알루미늄",
    ResearchPoint: "연구 점수",
    Unlock: "해제",
    BuildingUnlocked: "%{building} 이/가 해제되었습니다.",
    Science: "과학",
    ScienceFromPowerDesc: "발전소는 전력을 생산할 때 소량의 과학을 생산합니다.",
    Culture: "문화",
    School: "학교",
    University: "대학교",
    Polytechnic: "과학기술 전문학교",
    Colosseum: "콜로세움",
    WindTurbine: "풍력발전기",
    Engine: "엔진",
    EngineFactory: "엔진 공장",
    CameraFactory: "카메라 공장",
    Camera: "카메라",
    Gun: "총기",
    GunFactory: "총기 공장",
    Aircraft: "항공기",
    AircraftFactory: "항공기 공장",
    Zeppelin: "비행선",
    ZeppelinFactory: "비행선 공장",
    Tank: "탱크",
    TankFactory: "탱크 공장",
    MinimumTradingAmount: "최소량 미만으로 거래할 수 없습니다.",
    CoalPowerPlant: "석탄 발전소",
    PetrolPowerPlant: "가솔린 발전소",
    Copper: "구리",
    Gas: "천연가스",
    GasPump: "천연가스 펌프",
    GasPowerPlant: "가스 발전소",
    Missile: "미사일",
    MissileFactory: "미사일 공장",
    Rocket: "로켓",
    RocketFactory: "로켓 공장",
    BuildingPermit: "건축 허가",
    BuildingPermitDesc:
        "당신은 %{amount} 개의 건축 허가를 받았으며, %{amountBuilt} 개를 지었고 %{amountLeft} 개가 남았습니다.",
    BuildingLocked: "건물은 아직 사용할 수 없습니다. 먼저 연구소에서 잠금을 해제해야 합니다.",
    BuildQueue: "건설 대기열",
    BuildQueueDesc: "현재 대기열의 건물 수",
    MaxBuilders: "건축업자 수",
    MaxBuildersDesc: "동시에 건설할 수 있는 건물 수",
    Silicon: "규소",
    AluminumMine: "알루미늄 광산",
    CopperMine: "구리 광산",
    SiliconMine: "규소 광산",
    IronMine: "철 광산",
    CoalMine: "석탄 광산",
    Headquarter: "본사",
    ResearchLab: "연구소",
    TradeCenter: "무역센터",
    Resources: "자원",
    NotEnoughPower: "💡 전력이 충분하지 않습니다, 전력 공급을 늘리는 것을 고려하십시오",
    NotEnoughFuel: "이 작업을 하기 위한 %{fuel} 이 부족합니다",
    NotEnoughCash: "이 작업에 충분한 자금이 없습니다",
    NotEnoughSwissMoney: "스위스 돈이 충분하지 않습니다",
    BuildingNotEnoughFuel: "💡 %{fuel} 부족",
    AutoSell: "자동 판매",
    SellAll: "모두 판매",
    Change: "변경",
    StatisticsBureau: "통계국",
    LogisticsDepartment: "물류 부서",
    From: "발송",
    Top20FuelCost: "상위 20 연료 비용",
    To: "도착",
    TransportTime: "운송 시간",
    TopN: "상위 %{n}",
    Warehouse: "창고",
    TradeWarehouse: "화물 창고",
    Coal: "석탄",
    Video: "비디오",
    ClothingFactory: "의류 공장",
    Clothes: "옷",
    Fashion: "패션",
    FashionFactory: "패션 회사",
    VideoFarm: "비디오 팜",
    SantaFactory: "산타 공장",
    Santa: "산타",
    Car: "자동차",
    CarFactory: "자동차 공장",
    Ship: "선박",
    SolarPanel: "태양광 패널",
    SolarPanelDesc: "💡 태양광 패널은 10초 중 5초만 작동합니다 - 모든 동작 주기가 동일합니다",
    WindTurbineDesc: "💡 풍력 터빈은 10초 중 8초만 작동합니다 - 동작 주기가 제각각입니다",
    Movie: "영화",
    MovieStudio: "영화 스튜디오",
    Sitcom: "시트콤",
    TVStudio: "TV 스튜디오",
    PC: "PC",
    GameStudio: "게임 회사",
    Game: "게임",
    ComputerFactory: "컴퓨터 공장",
    Shipyard: "조선소",
    PowerUsage: "전력 사용량",
    PowerSupply: "전력 공급량",
    PowerSurplus: "남는 전력",
    Level: "레벨",
    Power: "전력",
    CentralBank: "중앙 은행",
    ResourceInput: "입력",
    ResourceOutput: "출력",
    ResourceStorage: "저장소",
    ResourceChange: "변경",
    ResourceInOutDesc: "💡 해당 출력 및 입력 건물을 강조 표시하려면 위의 출력-입력 번호를 누르세요",
    ResourceChart: "자원 차트",
    MarketUpdateIn: "%{time} 후 시장 업데이트",
    Income: "수입",
    Semiconductor: "반도체",
    SemiconductorFactory: "반도체 공장",
    SemiconductorFab: "반도체 팹",
    Steel: "강철",
    Bitcoin: "비트코인",
    BitcoinFarm: "비트코인 채굴장",
    Dogecoin: "도지코인",
    DogecoinFarm: "도지코인 채굴장",
    Guitar: "기타",
    GuitarFactory: "기타 공장",
    Drum: "드럼",
    DrumFactory: "드럼 공장",
    RecordingStudio: "녹음 스튜디오",
    OperaHouse: "오페라 하우스",
    CoalGasificationPlant: "석탄 기화 공장",
    GasProcessingPlant: "가스 처리 공장",
    Music: "음악",
    Glass: "유리",
    PhoneFactory: "스마트폰 공장",
    Phone: "스마트폰",
    GlassFactory: "유리 공장",
    Oil: "원유",
    Chromium: "크롬",
    ChromiumMine: "크롬 광산",
    Uranium: "우라늄",
    EnrichedUranium: "농축 우라늄",
    NuclearPowerPlant: "핵발전소",
    UraniumEnrichmentPlant: "우라늄 농축 시설",
    UraniumMine: "우라늄 광산",
    Titanium: "티타늄",
    TitaniumMine: "티타늄 광산",
    TitaniumAlloyPlant: "티타늄 합금 공장",
    ChromiumAlloyPlant: "크롬 합금 공장",
    Input: "입력",
    PanelPosition: "패널 위치",
    PanelPositionDesc: "왼쪽, 오른쪽 또는 자동에 측면 패널 표시 (현재 선택한 타일에 따라 다름)",
    InputCapacity: "입력 용량",
    InputCapacityPerCycle: "입력 용량 / 사이클",
    Output: "출력",
    OutputCapacity: "출력 용량",
    OutputCapacityPerCycle: "출력 용량 / 사이클",
    ResourceDeposit: "자원 매장층",
    RecommendedBuilding: "💡 이 타일에는 %{resource} 매장층이 있습니다",
    AdjacentBonus: "인접 보너스",
    AdjacentBonusDesc: "같은 유형의 인접한 모든 작업 건물에 대해 %{bonus}% 추가 용량을 얻습니다",
    ConsiderIncreaseProduction: "💡 %{resource} 생산량 증가 고려",
    AlwaysTransportInput: "비축 모드",
    AlwaysTransportInputTradeCenter: "항상 내보내기",
    AlwaysTransportInputTradeCenterDesc:
        "해당 자원에 대해 자동 판매가 활성화되지 않은 경우에도 항상 자원을 무역센터로 전송",
    AlwaysTransportInputDesc: "생산에 필요한 최소량을 초과하더라도 항상 입력 자원을 전송합니다",
    ProductionCycleLength: "생산주기",
    ProductionCycleLengthDesc:
        "생산주기의 기간(초). 주기를 연장하면 주기 당 입/출력이 증가하므로 입력 자원을 가져올 때 우선 순위가 낮아집니다",
    MaxInputDistance: "최대 입력 거리",
    MaxInputDistanceDesc:
        "건물에서 입력 리소스를 가져올 수 있는 최대 거리(타일 수)",
    AutoSellCapacity: "자동 판매 용량",
    AutoSellCapacityDesc: "자동 판매가 처리할 수 있는 초당 자원량",
    CurrentAutoSellCapacityMultiplier: "현재 승수: x%{n}",
    AutoSellConcurrency: "자동 판매 종류",
    AutoSellConcurrencyDesc: "자동 판매가 동시에 처리 할 수 있는 최대 자원 종류",
    MaxAutoSellConcurrencyReached:
        "자동 판매를 할 수 있는 최대치입니다. 이 기능을 사용하려면 다른 자동 판매를 끄십시오",
    CannotSellBuilding: "현재 건물을 팔 수 없습니다",
    WallStreet: "월 스트리트",
    MarketCap: "시가 총액",
    MarketCapDesc: "당신 회사의 시가 총액(시장 가치)",
    BuildingValuation: "건물 평가",
    BuildingValuationDesc: "건물 허가 및 업그레이드를 포함한 건물의 총 가치",
    ResourcesValuation: "자원 평가",
    ResourcesValuationDesc: "재고에 있는 자원의 총 가치",
    Battery: "배터리",
    BatteryFactory: "배터리 공장",
    RatingBuy: "구매",
    RatingSell: "판매",
    SwissShop: "스위스 상점",
    RatingHold: "보류",
    RatingOutperform: "능가",
    RatingUnderperform: "부진",
    StockRating: "주식 등급",
    JetEngine: "제트 엔진",
    Helicopter: "헬리콥터",
    Lithium: "리튬",
    LithiumMine: "리튬 광산",
    LiionBatteryFactory: "리튬-이온 배터리 공장",
    HelicopterFactory: "헬리콥터 공장",
    Satellite: "인공위성",
    ToyFactory: "장난감 공장",
    Toy: "장난감",
    SpaceStation: "우주 정거장",
    SpaceStationFactory: "우주 정거장 공장",
    OperatingSystem: "운영 체제",
    OperatingSystemCompany: "운영 체제 개발사",
    LinuxDistribution: "리눅스 배포",
    Internet: "인터넷",
    WebBrowser: "웹 브라우저",
    Console: "콘솔",
    ConsoleFactory: "콘솔 회사",
    Train: "기차",
    TrainFactory: "기차 공장",
    ShoeFactory: "신발 공장",
    Shoes: "신발",
    ArtilleryFactory: "대포 공장",
    Artillery: "대포",
    SubmarineFactory: "잠수함 조선소",
    Submarine: "잠수함",
    Spaceship: "우주선",
    RobotFactory: "로봇 공장",
    Robot: "로봇",
    SpaceshipFactory: "우주선 공장",
    SatelliteFactory: "인공위성 공장",
    JetEngineFactory: "제트 엔진 공장",
    StockRatingDesc:
        "월스트리트 분석가의 주식 평가 합의는 시가 총액에 영향을 미치며 시장과 함께 새로 고침됩니다",
    InterestRate: "야간 이자율",
    InterestRateDesc: "오프라인 상태에서 시가 총액에 대한 이자",
    OfflineEarning: "오프라인 수입",
    OfflineEarningDesc: "오프라인 수입은 시가 총액과 이자율에 따라 다릅니다",
    PerMin: "%{amount}/분",
    OfflineEarningTime: "오프라인 수입 시간",
    OfflineEarningTimeDesc: "이 시간까지 오프라인 수입을 얻을 수 있습니다",
    BuyPermit: "건축 허가 구매",
    NotEnoughBuildingPermit: "건축 허가가 충분하지 않습니다. 새 건물을 짓기 위해 더 구입하십시오",
    MovingAverage: "이동 평균",
    MovingAverageDesc: "실시간 변경 대신 자원 변경의 이동 평균 표시",
    AllowZoom: "확대",
    AllowZoomDesc: "확대 지원을 켜십시오. 확대하려면 마우스 휠을 사용하십시오. 현재 확대 배율은 %{zoom} 입니다",
    AllowZoomMobileDesc: "확대 지원을 켜십시오. 손가락을 모아 확대할 수 있습니다. 현재 확대 배율은 %{zoom} 입니다",
    Settings: "설정",
    SellBuildingDesc:
        "건물을 팔면 투자금의 50%가 환불되고 자원의 50%는 무역 센터로 보내집니다",
    SellBuildingFullRefundDesc:
        "건물 재활용 정책이 활성화되어 있습니다. 건물을 판매하면 %{time}까지 전액 환불 해드립니다",
    Sound: "사운드 효과",
    SoundDesc: "클릭 또는 오류 같은 사운드 효과 켜기",
    AutoHighlight: "자동 강조",
    AutoHighlightDesc: "건물을 선택할 때 동일한 유형의 건물을 자동으로 강조 표시",
    MusicDesc: "음악 켜기: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "제작 참여",
    Icons: "아이콘",
    MisplacedBuilding: "⛔ 이 %{building} 은 올바른 자원 매장층 위에 배치되지 않았습니다",
    UnderConstruction: "%{building} 공사중",
    Left: "왼쪽",
    Right: "오른쪽",
    Auto: "자동",
    HighlightBuildings: "건물 하이라이트",
    HighlightTurnedOff: "...꺼진 건물",
    HighlightStockpileModeOn: "...비축 모드가 켜져있는 경우",
    HighlightWarehouseOnly: "...창고 전용",
    HighlightProductionCycleNotDefault: "...생산주기 > 1",
    HighlightMaxInputDistanceNotDefault: "...최대 입력 거리 < ∞",
    HighlightNotMakingProfit: "...이익을 내지 못 함 ",
    NBuildingsAreHighlighted: "%{n} 개의 건물이 강조 표시되었습니다",
    OnlyToWarehouse: "창고 전용",
    OnlyToWarehouseDesc: "창고로만 자원을 보냅니다",
    TurnOffProduction: "꺼짐",
    TurnOffProductionDesc:
        "건물의 생산을 중단합니다. 건물은 더 이상 자원을 수송하거나 전력을 사용하지 않을 것입니다",
    ApplyToAll: "모든 %{building}에 적용",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "무제한",
    Transport: "수송",
    TileModifier: "타일 보정",
    ShowAllModifiers: "모든 보정 보기",
    HideAllModifiers: "모든 보정 숨기기",
    NumberOfBuildings: "소유한 건물 수",
    ShowContent: "컨텐츠 보기",
    HideContent: "컨텐츠 숨기기",
    BuyExpansionPack: "%{price}에 구매",
    Cities: "도시",
    WarehouseInputCapacityDesc: "창고가 초당 내부로 전송할 수 있는 자원의 양",
    InputStrategy: "입력 전략",
    InputStrategyClose: "가까운 것 우선",
    InputStrategyCloseDesc: "충분한 자원이 있는 가장 가까운 창고를 선호합니다",
    InputStrategyFar: "먼 것 우선",
    InputStrategyFarDesc: "충분한 자원이 있는 가장 먼 창고를 선호합니다",
    InputStrategyAmount: "많은 양 우선",
    InputStrategyAmountDesc: "거리에 관계 없이 자원이 가장 많은 창고를 선호합니다",
    FuelCostSave: "연료 비용 절약",
    FuelCostSaveDesc:
        "창고는 내부로 자원을 운반할 때 다른 건물에 비해 일정 비율의 연료를 절약합니다. 레벨이 높을수록 절약 효과가 높습니다",
    SoftwareCompany: "소프트웨어 회사",
    Software: "소프트웨어",
    ScreenFactory: "디스플레이 공장",
    Screen: "디스플레이",
    JoinDiscord: "최신 업데이트, 팁 및 토론을 위해 Discord 서버에 가입하세요",
    ClaimOfflineEarning: "오프라인 수입 청구",
    OfflineTime: "오프라인 시간",
    Minutes: "%{time}분",
    MaxUpgrade: "최대 업그레이드",
    MaxUpgradeDesc: "최대 업그레이드에 도달했습니다",
    ClaimAmount: "현금 +%{amount}",
    EarningPerMinute: "수익률",
    EffectiveTime: "유효 시간",
    EffectiveTimeDesc: "유효 오프라인 수입 시간은 %{time}분으로 제한됩니다.",
    BuildSearchPlaceholder: "검색할 건물 또는 자원 입력",
    MineOverlayWarning: "%{building} 은 타일 보정을 받지 않습니다",
    WholesaleCenter: "도매 센터",
    OrderFrom: "%{name} 에서 주문",
    ExpireIn: "만료",
    ProfitMargin: "이익 마진",
    NotMakingProfitWarning: "💡 생산에 수익성이 없습니다. 끄는 것을 고려하십시오",
    TurnOnAllProductions: "생산 켜기",
    TurnOnAllProductionsDesc: "모든 건물의 생산을 켭니다. 비용 절약 정책이 활성화되면 사용할 수 없습니다",
    OperationSuccessful: "작업이 성공적으로 완료되었습니다",
    TurnOn: "켜기",
    Reward: "보상",
    PerSecond: "%{time}/초",
    PerCycle: "%{amount}/사이클",
    PolicyPoint: "정책 점수",
    PolicyPointPerMinute: "분당 정책점수",
    PolicyPointPerMinuteDesc: "게임에서 매 분마다 정책 점수를 획득합니다",
    YourWilLGaimPolicyPoints: "%{time}초 후에 %{amount} 정책 점수를 얻을 수 있습니다",
    PolicyPointDesc: "💡 정책이 더 활성화 될수록 각 정책에 더 많은 비용이 듭니다",
    NextOrderIn: "다음 주문",
    FillOrder: "주문 채우기",
    RejectOrder: "거절",
    YouHave: "보유량 %{amount}",
    WholesaleCenterLocked:
        "도매 센터를 잠금 해제하려면 최소 %{required} 개의 다른 자원이 필요합니다. %{current} 개의 자원만 있습니다",
    OrderFilled: "%{from} 의 주문이 성공적으로 완료되었습니다!",
    PolicyCenter: "정책 센터",
    NewOrder: "%{from} 의 새 주문이 도착했습니다, 도메 센터에서 확인하십시오",
    Policies: "정책",
    PolicyNotEnoughTime: "이 정책에 대한 정책 점수가 충분하지 않습니다",
    TimeLeft: "%{time} 남음",
    WholesaleCenterOrderFaster: "세계 박람회",
    WholesaleCenterOrderFasterDesc: "도매 센터는 주문을 2배 더 빨리 받고 주문량이 2배 더 많습니다",
    PolicyOilWellPowerx2: "과급 유정",
    PolicyOilWellPowerx2Desc: "유정은 2배의 원유를 생산하고 2배의 전력을 사용합니다",
    HalfTransportSpeed: "절약을 위해 천천히",
    HalfTransportSpeedDesc: "운송 속도가 25% 감소하고 연료비가 25% 감소합니다",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "정유 공장은 가솔린을 50% 더 생산하고 플라스틱을 50% 더 적게 생산합니다",
    StickyInput: "고정 입력",
    StickyInputDesc:
        "건물은 매 주기마다 최상의 입력을 검색하는 대신 이전 입력에서 전송하는 것을 선호합니다 (무료 정책)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "정유 공장은 가솔린을 50% 덜 생산하고 플라스틱을 50% 더 생산합니다",
    FreeOilTransport: "무료 원유 운송",
    FreeOilTransportDesc: "원유 운송은 비용이 들지 않지만 유정은 2배의 전력을 사용합니다",
    SuperSteelMill: "철의 심장",
    SuperSteelMillDesc: "제철소는 석탄을 50% 적게 사용하고 철은 25% 더 많이 사용하며 전력은 25% 더 많이 사용합니다",
    AlSemiconductor: "Al 회로",
    AlSemiconductorDesc: "파운드리는 구리 대신 알루미늄을 사용합니다",
    CostSaver: "비용 절약",
    CostSaverDesc: "건물의 투입물이 산출물보다 더 비싸면 생산을 중단합니다",
    CostSaverBuildingDesc:
        "C비용 절약 정책이 활성화되어 있으며 수익성에 따라 생산이 자동으로 켜지거나 꺼집니다",
    CostSaverBuildingWarning: "비용 절약 정책이 활성화되어 있으며 생산을 수동으로 변경할 수 없습니다",
    GlassUseCoal: "검은 유리",
    GlassUseCoalDesc: "유리 공장은 석탄을 50% 더 많이 사용하고 규소를 50% 더 적게 사용합니다",
    AdjacentBonusOnlyOutput: "인접 보너스 플러스",
    AdjacentBonusOnlyOutputDesc:
        "인접 보너스는 더 많은 입력이 필요하지 않지만 더 많은 전력을 사용하고 50% 만 효과적입니다",
    IronMine2xOutput: "중철",
    IronMine2xOutputDesc: "철 광산은 2배의 철을 생산하지만 철 수송에 드는 연료는 2배가 됩니다",
    SolarPanelAlwaysWork: "태양은 결코 지지 않는다",
    SolarPanelAlwaysWorkDesc: "태양 전지판은 항상 작동하지만 전력을 60% 적게 생산합니다",
    SteelScience: "강철을 통한 지식",
    SteelScienceDesc: "제철소는 2배의 입력을 사용하고 추가 과학을 생산합니다",
    ShowWarehouse: "창고 잠금 해제",
    ShowWarehouseDesc:
        "창고는 자원을 운송하고 저장하는 특수 건물이며 연료를 절약할 수 있습니다 (무료 정책)",
    WholesaleCenterProducingOnly: "도매 파트너",
    WholesaleCenterProducingOnlyDesc:
        "도매 센터 주문에는 현재 생산중인 자원만 포함됩니다 (도매 센터를 잠금 해제하려면 필요한 자원을 생산해야 함)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "If a resource's output capacity falls short, buy the shortage amount from Trade Center automatically (If the resource has auto sell on, it will be ignored)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree policy is on, Trade Center will automatically buy resources in shortage",
    ExtraPolicyPoints: "Political Lobbyist",
    ExtraPolicyPointsDesc: "Increase policy point production capacity by 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromium alloy plants do not use Lithium but use 2x Iron instead",
    DoubleTileModifier: "Nature's Power",
    DoubleTileModifierDesc: "All tiles' modifier's effect x2 - both positive and negative",
    TileModifierOutputOnly: "Tile Modifier Plus",
    TileModifierOutputOnlyDesc:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective",
    GasPlantPetrol: "Gas Liquidizer",
    GasPlantPetrolDesc: "Gas power plants use extra gas to produce petrol",
    BuildingRecycle: "Building Recycle",
    BuildingRecycleDesc: "Get full refund when you sell a building within 1 min after construction",
    CoalPlantFuel: "Coal Liquidizer",
    CoalPlantFuelDesc: "Coal power plants use extra coal to produce petrol",
    Welcome: "Welcome",
    SeeTutorialAgain: "Redo Tutorial",
    ReadSteamGuide: "Official Guide on Steam",
    HelpTranslateTheGame: "Help Translate the Game🌐",
    SkipTutorial: "Skip Tutorial",
    NextTutorial: "Next",
    Tutorial1:
        "Industry Idle is a <em>resource management</em> game where you build factories🏭, produce goods📦 and make money💸.<br><br>Let's go through some basic concepts to get you started - it won't take long, I pinky promise.",
    Tutorial2:
        "All buildings need power⚡, you have a <em>wind turbine</em> that generates power. You can see your current power supply on the left side of the top bar.<br><br>You might have noticed that wind turbines only work <em>80%</em> of the time. You can consider building other types of power plants that generate stable power.",
    Tutorial3:
        "You have a lot of <em>resource deposits</em> on the map. To extract resources, you have to build mines⛏️ <em>on top of</em> the corresponding deposit.<br><br>For example, you have an <em>oil well🛢️</em> that extracts <em>oil</em> from an oil deposit.<br></br>Resource deposits are unlimited - no need to worry about them running out. Apart from mines, other buildings can be built on any empty tile.",
    Tutorial4:
        "Resource transportation costs fuel. On this map, you can use <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.<br><br>You can change your fuel type in the transportation center🚦. Remember to make sure your fuel production is above consumption otherwise your production will halt when you run out of fuel.",
    Tutorial5:
        "To make money, you need to export your resources via the trade center. To do this, simply turn on <em>auto sell</em> for that resource.<br></br>You can also buy resources from the trade center as well. Remember <em>if you buy a resource, you will drive up the price</em> and if you sell a resource, you will drive down the price.<br><br>The market is <em>volatile</em> and the price📈 changes regularly.",
    Tutorial6:
        "To build new buildings, you need to unlock it first in the <em>research lab🧪</em>. The research lab also converts science to research points.<br><br>Your wind turbine (and other power plants) produces a small amount of science when running. And you can build school🏫 and other dedicated buildings to boost science later.<br><br>Now you have learned all the basics, start to build up your economy! Here are some <em>cash💸</em> and <em>petrol⛽</em> to give you a jump start.",
    WelcomePlay: "Play",
    WelcomePlayMuted: "Play (🔇Music)",
    Changelog: "Changelog",
    ChangelogGotIt: "Got It",
    Chat: "Chat",
    Send: "Send",
    Import: "Import",
    Export: "Export",
    SteamCloudBackup: "Steam Cloud Backup",
    LastBackupAt: "Last Backup",
    RestoreFromBackup: "Restore from Backup",
    RestoreFromBackupFail: "Failed to restore backup from Steam Cloud: are you sure there's a backup?",
    RestoreFromBackupTitle: "Are you sure?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChatMessages: "Chat Messages",
    ChatPlaceholder: "Type your message: max 100 chars",
    ChangeName: "Change",
    SaveName: "Save",
    NameValidationRule: "Your name should only contain letters and numbers and be between 5-15 chars",
    NameValidationRuleProfanity: "Your name should not contain profanity",
    ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
    NameSaved: "Your name has been changed successfully",
    NoMessages: "No new messages",
    Leaderboard: "Leaderboard",
    LeaderboardDesc: "The leaderboard score is all the Swiss money you've ever earned",
    Name: "Name",
    Rank: "Rank",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2:
        "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building is determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Energy Saving",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptOutDesc:
        "This will no longer send leaderboard score. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Reward video did not complete",
    RewardAdsNotAvailable: "Reward video is not available (currently only iOS/Android is supported)",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Highlight "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Out in %{time}",
    FuelRunOutWarning: "💡 Your fuel consumption exceeds production. When fuel runs out, your transportation will halt",
    InAmount: "In: %{number}",
    OutAmount: "Out: %{number}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Expansion Packs",
    ExpansionPack1: "Expansion Pack 1",
    ExpansionPack1Owned: "Expansion Pack 1",
    RequireExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Hide Discord Banner",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Hide Chat Message",
    HideChatDesc: "Hide chat message from the bottom toolbar",
    SortedByDeficit: "Sorted By Deficit",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Swiss Money 💵",
    RestartDesc: "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
    PrestigeGoBack: "Go Back",
    PermanentUpgradeDesc: "This upgrade will carry over if you start in a new city",
    ProductionMultiplier: "Production Multiplier",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    OfflineEarningMultiplier: "Offline Earning Multiplier",
    OfflineEarningMultiplierDesc: "A multiplier that applies to offline earnings",
    PrestigeAlertTitle: "Are you sure?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Cash In",
    Cancel: "Cancel",
    SaveFileCorrupted: "Save File Corrupted",
    CheatDetected: "Your old save did not pass server validation and cannot be read. You will start with a new save",
    LoadGameError: "Failed to Load Game",
    LoadGameErrorMessage: "Error message: %{message}",
    LoadGameErrorDesc: "Please check your Internet connection. If the problem persists, please contact support",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    SaveFileMigrated: "A New Era: Beta Is Here",
    SaveFileMigratedDesc:
        "Thank you for play testing in alpha. Your old map is not compatible but we have migrated your data and give you some bonus",
    ClaimSwissMoney: "Claim %{amount} Swiss Money 💵",
    SaveFileMigratedFinePrint:
        "Your market cap is converted to Swiss Money and your unspent Swiss money is carried forward. You will get 50% bonus Swiss money for play testing in alpha. Max Swiss money that can be carried forward is capped at 200",
    CashIn: "Cash In",
    CurrentCity: "Current City",
    CashInDesc:
        "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
    MoveToNewMap: "Start In A New City",
    CityName: "City",
    CitySize: "Map Size",
    GridType: "Grid Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "City Bonus",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    StockholmBonus:
        "<li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Paper mills are unlocked</li><li>Logging camps have 2x output</li>",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>No tile modifiers</li>",
    Oslo: "Oslo",
    OsloBonus:
        "<li>Oil refineries have 2x capacity</li><li>Gas processing plants have 2x capacity</li><li>Petrol power plants have 2x capacity</li><li>Steel mills use natural gas instead of coal</li><li>Free oil transportation</li>",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Missile factories use enriched uranium instead of titanium and uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories use uranium instead of enriched uranium</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    DetroitBonus:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories do not need batteries</li><li>Train factories have 2x capacity</li>",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>University have 2x productivity</li>",
    HideNotProducing: "Hide resources that are not being produced",
    SortByStorage: "Storage",
    SortByProduction: "Production",
    SortByName: "Name",
    BuildingInProgressCannotPrestige:
        "You have building construction in progress, you cannot start in a new city until they are finished",
    PlayerTrade: "Player Trade",
    AddTradeFail: "Failed to add your trade",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Your trade has been added successfully",
    LoadTradeFail: "Failed to load player trades, please try again later",
    ClaimTradeFail: "Failed to claim this trade, please try again later",
    ClaimTradeSuccess: "Your trade has been claimed successfully: $%{cash} has been added to your account",
    CancelTradeSuccess: "Your trade has been cancelled successfully",
    CancelTradeFail: "Failed to cancel this trade, please try again later",
    AcceptTradeSuccess: "This trade has been accepted by you: %{resource} has been added to your trade center",
    AcceptTradeFail: "Failed to accept this trade, please try again later",
    PlayerTradeBanner: "Trade Resources with Other Players",
    PlayerTradeResource: "Resource",
    PlayerTradeAmount: "Amount",
    PlayerTradePrice: "Price $",
    PlayerTradeValue: "Value $",
    PlayerTradeWaiting: "Waiting...",
    UseTradeCenterPrice: "Use Trade Center Price",
    AddTrade: "Add Trade",
    ActiveTrades: "Active Trades",
    AcceptTrade: "Accept",
    CancelTrade: "Cancel",
    RefundTrade: "Refund",
    RefundTradeSuccess: "This trade has been refunded: %{resource} has been refunded to your trade center",
    RefundTradeFail: "Failed to refund this trade, please try again later",
    ClaimTrade: "Claim",
    RefreshTrade: "Refresh",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    FailedToCheckActiveTrade: "Failed to check active player trades, please try again later",
    PlayerTradePriceNotValid: "Trade price must be between %{min} and %{max} (2 x Last Market Update Price)",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeAmountNotValid: "Trade amount must be greater than 0",
    PlayerTradeValidRange: "Range: %{min} ~ %{max}",
    PlayerTradeFilterPrice: "Below Market Price",
    PlayerTradeFilterCanAfford: "Can Afford",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transport and store any resources and with lower fuel cost",
    PowerBankChargeSpeed: "Charge Speed",
    PowerBankPowerLeft: "Power Left",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ExcludeBuildingsShutdown: "Exclude buildings that are shut down",
    ColorTheme: "Game Color Theme",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Industrial Revolution",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "This will hide resource movement (those tiny dots) by default and only show the movement when you select a building",
    PowerBankLeft: "Power Bank",
};
