export const NL = {
    Translator: "Vertaler",
    TranslatorName: "Maccie, Arlene",
    Language: "Taal",
    ThisLanguage: "Nederlands",
    OK: "OK",
    SteelMill: "Staalfabriek",
    StainlessSteelPlant: "Roestvrij Staalfabriek",
    CircuitFoundry: "Printplaatfabriek",
    IntegratedCircuit: "Printplaat",
    OilWell: "Oliebron",
    Wood: "Hout",
    LoggingCamp: "Houthakkers kamp",
    LumberMill: "Houtzagerij",
    Lumber: "Planken",
    Paper: "Papier",
    PaperMill: "Papierfabriek",
    Book: "Boek",
    BookPublisher: "Boeken Uitgeverij",
    OilRefinery: "Olie Raffinaderij",
    Sell: "Verkopen",
    Upgrade: "Opwaarderen",
    Build: "Bouwen",
    Inspect: "Inspecteren",
    Buildings: "Gebouwen",
    Iron: "Ijzer",
    Actions: "Acties",
    FuelType: "Kies Brandstof",
    FuelCost: "Brandstof Kosten",
    FuelConsumption: "%{fuel} Consumptie",
    FuelEconomy: "Brandstof Economie",
    FuelProduction: "%{fuel} Productie",
    FuelInStorage: "%{fuel} In Opslag",
    Plastic: "Plastic",
    FuelSurplus: "%{fuel} Overschot",
    Petrol: "Petroleum",
    Buy: "Kopen",
    NoLiquidity: "Geen Liquiditeit",
    NoLiquidityTurnOffAutoSell: "Er is niet genoeg liquiditeit in de markt voor %{res}, auto verkopen is stil gezet",
    Multiplier: "Vermenigvuldiger",
    MultiplierDesc: "Elke 10 levels, krijg je +1 vermenigvuldiger",
    SellBuilding: "Verkoop Gebouw",
    PowerGrid: "Stroomnet",
    TradeAmount: "Handel Bedrag",
    SortBy: "Sorteren op",
    SortByPrice: "Prijs",
    SortByAmount: "Aantal",
    NotEnoughResourcesForTrade: "Niet genoeg goederen in het handelscentrum  voor deze verhandeling",
    NotEnoughResources: "Niet genoeg goederen voor deze operatie",
    Transportation: "Transport",
    Cash: "Geld",
    Aluminum: "Aluminium",
    ResearchPoint: "Onderzoekspunten",
    Unlock: "Ontgrendel",
    BuildingUnlocked: "%{building} is ontgrendeld",
    Science: "Wetenschap",
    ScienceFromPowerDesc: "Energiecentrale produceert een klein aantal wetenschap bij het aanmaken van energie",
    Culture: "Cultuur",
    School: "School",
    University: "Universiteit",
    Polytechnic: "Polytechnisch",
    Colosseum: "Colosseum",
    WindTurbine: "Wind Turbine",
    Engine: "Motor",
    EngineFactory: "Motor Fabriek",
    CameraFactory: "Camera Fabriek",
    Camera: "Camera",
    Gun: "Wapen",
    GunFactory: "Wapen Fabriek",
    Aircraft: "Vliegtuig",
    AircraftFactory: "Vliegtuigen Fabriek",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Zeppelin Fabriek",
    Tank: "Tank",
    TankFactory: "Tank Fabriek",
    CoalPowerPlant: "Kolencentrale",
    PetrolPowerPlant: "Petroleumcentrale",
    Copper: "Koper",
    Gas: "Aardgas",
    GasPump: "Aardgas Pomp",
    GasPowerPlant: "Gascentrale",
    Missile: "Ballistische Raket",
    MissileFactory: "Ballistische Raket Fabriek",
    Rocket: "Raket",
    RocketFactory: "Raket Fabriek",
    BuildingPermit: "Bouw Vergunning",
    BuildingPermitDesc:
        "Je hebt een vergunning voor %{amount} gebouwen, je hebt er al %{amountBuilt} gebouwd en hebt er  %{amountLeft} over",
    BuildingLocked: "Bouwen is nog niet beschikbaar, Je moet dit eerst vrijspelen in het Onderzoekslaboratorium",
    BuildQueue: "Gebouwen Wachtrij",
    BuildQueueDesc: "Aantal gebouwen momenteel in de wachtrij",
    MaxBuilders: "Maximum Bouwers",
    MaxBuildersDesc: "Aantal gebouwen dat je tegelijk kan bouwen",
    Silicon: "Silicium",
    AluminumMine: "Aluminium Mijn",
    CopperMine: "Kopermijn",
    SiliconMine: "Silicium mijn",
    IronMine: "Ijzermijn",
    CoalMine: "Kolenmijn",
    Headquarter: "Hoofdkwartier",
    ResearchLab: "Onderzoekslaboratorium",
    TradeCenter: "Handelscentrum",
    Resources: "Goederen",
    NotEnoughPower: "💡 Niet genoeg energie, overweeg energie productie te verhogen",
    NotEnoughFuel: "Niet genoeg %{fuel} voor deze handeling",
    NotEnoughCash: "Niet genoeg cash voor deze handeling",
    NotEnoughSwissMoney: "Niet genoeg Zwitsers geld voor deze handeling",
    BuildingNotEnoughFuel: "💡 Niet genoeg %{fuel}",
    AutoSell: "Automatisch Verkopen",
    SellAll: "Verkoop Alles",
    Change: "Aanpassen",
    StatisticsBureau: "Statistiek Bureau",
    LogisticsDepartment: "Logistiek Bureau",
    From: "Van",
    Top20FuelCost: "Top 20 Brandstof Kosten",
    To: "Tot",
    TransportTime: "Transport Tijd",
    TopN: "Top %{n}",
    Warehouse: "Opslagplaats",
    TradeWarehouse: "Verhandel Opslagplaats",
    Coal: "Kolen",
    Video: "Video",
    ClothingFactory: "Kleding Fabriek",
    Clothes: "Kleding",
    Fashion: "Mode",
    FashionFactory: "Mode Fabriek",
    VideoFarm: "Video Studio",
    SantaFactory: "Kerstman Fabriek",
    Santa: "Kerstman",
    Car: "Auto",
    CarFactory: "Auto Fabriek",
    Ship: "Schip",
    SolarPanel: "Zonnepaneel",
    SolarPanelDesc: "💡 Zonnepanelen werken maar 5 van elke 10 seconden - alle cyclussen zijn synchroon",
    WindTurbineDesc: "💡 Wind turbines werken maar 8 van elke 10 seconden - cyclussen zijn niet synchroon",
    Movie: "Film",
    MovieStudio: "Film Studio",
    Sitcom: "Sitcom",
    TVStudio: "TV Studio",
    PC: "PC",
    GameStudio: "Game Studio",
    Game: "Game",
    ComputerFactory: "Computer Fabriek",
    Shipyard: "Scheepswerf",
    PowerUsage: "Stroom verbruik",
    PowerSupply: "Stroom toevoer",
    PowerSurplus: "Stroom overschot",
    Level: "Level",
    Power: "Stroom",
    CentralBank: "Centrale Bank",
    ResourceInput: "In",
    ResourceOutput: "Uit",
    ResourceStorage: "Opslag",
    ResourceChange: "Aanpassing",
    ResourceInOutDesc:
        "💡 klik op bovenliggende Uit-In nummers om de bijbehorende uitgaande en inkomende gebouwen te markeren",
    ResourceChart: "Goederen Grafiek",
    MarketUpdateIn: "Markt bijwerken In %{time}",
    Income: "Inkomsten",
    Semiconductor: "Halfgeleiders",
    SemiconductorFactory: "Halfgeleiders Fabriek",
    Steel: "Staal",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Server",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Server",
    Guitar: "Gitaar",
    GuitarFactory: "Gitaren Fabriek",
    Drum: "Trommel",
    DrumFactory: "Trommel Fabriek",
    RecordingStudio: "Opname Studio",
    OperaHouse: "Opera",
    CoalGasificationPlant: "Kolen Vergassingscentrale",
    GasProcessingPlant: "Aardgas verwerkingscentrale",
    Music: "Muziek",
    Glass: "Glas",
    PhoneFactory: "Telefoon Fabriek",
    Phone: "Telefoon",
    GlassFactory: "Glas Fabriek",
    Oil: "Olie",
    Chromium: "Chroom",
    ChromiumMine: "Chroom Mijn",
    Uranium: "Uranium",
    EnrichedUranium: "Verrijkt Uranium",
    NuclearPowerPlant: "Nucleare Energiecentrale",
    UraniumEnrichmentPlant: "Uranium VerrijkingsCentrale",
    UraniumMine: "Uranium Mijn",
    Titanium: "Titanium",
    TitaniumMine: "Titanium Mijn",
    TitaniumAlloyPlant: "Titanium Legering Fabriek",
    ChromiumAlloyPlant: "Chroom Legering Fabriek",
    Input: "Invoer",
    PanelPosition: "Paneel Positie",
    PanelPositionDesc:
        "Toon zijpaneel aan de linkerkant, rechterkant of automatisch (afhankelijk van de geselecteerde tegel)",
    InputCapacity: "Invoer Capaciteit",
    InputCapacityPerCycle: "Invoer Capaciteit per Cyclus",
    Output: "Productie",
    OutputCapacity: "Productie Capaciteit",
    OutputCapacityPerCycle: "Productie Capaciteit per Cyclus",
    ResourceDeposit: "Grondstoffen Bron",
    RecommendedBuilding: "💡 Deze tegel heeft %{resource} bron",
    AdjacentBonus: "Aangrenzings Bonus",
    AdjacentBonusDesc: "Je krijgt %{bonus}% extra capaciteit voor elk aangrenzend werkend gebouw van hetzelfde type",
    ConsiderIncreaseProduction: "💡 Overweeg %{resource} productie te verhogen",
    AlwaysTransportInput: "Stapel Modus",
    AlwaysTransportInputTradeCenter: "Altijd Exporteren",
    AlwaysTransportInputTradeCenterDesc:
        "Altijd transporteren naar het handelscentrum, ook al is de automatische verkoop niet geactiveerd voor dit product",
    AlwaysTransportInputDesc:
        "Altijd invoer goederen transporteren, zelfs als deze boven de minimale productie vereisten liggen",
    ProductionCycleLength: "Productie Cyclus",
    ProductionCycleLengthDesc:
        "De duur van één productie cyclus, gemeten in seconden. De cyclus verlengen zal de invoer/uitvoer per cyclus verhogen, dus als bijgevolg de prioriteit verlagen bij het ophalen van invoergoederen",
    MaxInputDistance: "Maximale Invoer Afstand",
    MaxInputDistanceDesc:
        "De maximale afstand van waar dit gebouw invoer van goederen kan krijgen, gemeten in aantal tegels",
    AutoSellCapacity: "Automatische Verkoop Capaciteit",
    AutoSellCapacityDesc: "Max aantal goederen die de automatische verkoop kan verwerken per seconde, per goed",
    CurrentAutoSellCapacityMultiplier: "Huidige vermenigvuldiger: x%{n}",
    AutoSellConcurrency: "Automatische Verkoop Gelijktijdigheid",
    AutoSellConcurrencyDesc: "Max aantal goederen die je tegelijk kan verkopen",
    MaxAutoSellConcurrencyReached:
        "Je hebt het maximum automatische verkopen gelijktijdig bereikt, deactiveer een andere automatische verkoop om deze te activeren",
    CannotSellBuilding: "Je kan dit gebouw momenteel niet verkopen",
    WallStreet: "Wall Street",
    MarketCap: "Markt Kapitalisatie",
    MarketCapDesc: "Totale markt kapitalisatie (i.e. markt waarde) van je bedrijf",
    BuildingValuation: "Gebouw waarde",
    BuildingValuationDesc: "Totale waarde van je gebouwen, inclusief gebouwvergunningen en uitbreidingen",
    ResourcesValuation: "Goederen waardering",
    ResourcesValuationDesc: "Totale waarde van je goederen in je inhoud",
    Battery: "Batterij",
    BatteryFactory: "Batterijen Fabriek",
    RatingBuy: "Kopen",
    RatingSell: "Verkopen",
    SwissShop: "Zwitserse Winkel",
    RatingHold: "Stagnatie",
    RatingOutperform: "Overprestatie",
    RatingUnderperform: "Onderprestatie",
    StockRating: "Aandeel Beoordeling",
    JetEngine: "Straalmotor",
    Helicopter: "Helikopter",
    Lithium: "Lithium",
    LithiumMine: "Lithium Mijn",
    LiionBatteryFactory: "Li-ion Batterijen Fabriek",
    HelicopterFactory: "Helikopter Fabriek",
    Satellite: "Satelliet",
    ToyFactory: "Speelgoed Fabriek",
    Toy: "Speelgoed",
    SpaceStation: "Ruimte Station",
    SpaceStationFactory: "Ruimte Station Fabriek",
    OperatingSystem: "Besturingssysteem",
    OperatingSystemCompany: "Besturingssysteem Inc",
    LinuxDistribution: "Linux Distributie",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Console",
    ConsoleFactory: "Console Fabriek",
    Train: "Trein",
    TrainFactory: "Treinen Fabriek",
    ShoeFactory: "Schoenen Fabriek",
    Shoes: "Schoenen",
    ArtilleryFactory: "Artillerie Fabriek",
    Artillery: "Artillerie",
    SubmarineFactory: "Duikbooten Fabriek",
    Submarine: "Duikboot",
    Spaceship: "Ruimteschip",
    RobotFactory: "Robot Fabriek",
    Robot: "Robot",
    SpaceshipFactory: "Ruimteschepen Fabriek",
    SatelliteFactory: "Satellieten Fabriek",
    JetEngineFactory: "Straalmotoren Fabriek",
    StockRatingDesc:
        "Aandeel beoordeling van Wall Street analysten, die je markt kapitalisatie beïnvloeden en wordt geüpdate samen met de markt",
    InterestRate: "Nachtelijke Rente",
    InterestRateDesc: "Rente die je verdient op je markt kapitalisatie terwijl je offline bent",
    OfflineEarning: "Offline inkomsten",
    OfflineEarningDesc: "Offline inkomsten zijn afhankelijk van je markt kapitalisatie en rente",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline inkomsten Tijdsduratie",
    OfflineEarningTimeDesc: "Gedurende deze tijd kan je inkomsten verdienen terwijl je offline bent",
    BuyPermit: "Bouwvergunning",
    NotEnoughBuildingPermit: "Niet genoeg bouwvergunningen. Koop er meer om nieuwe gebouwen te kunnen bouwen",
    MovingAverage: "Voortschrijdend Gemiddelde",
    MovingAverageDesc: "Toon voortschrijdende gemiddeldes in plaats van directe veranderingen",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Zet zoom support aan. Gebruik je muiswiel om in te zoomen. Huidige zoom is %{zoom}",
    AllowZoomMobileDesc: "Zet zoom support aan. Je kan pinchen om te zoomen. Huidige zoom is %{zoom}",
    Settings: "Instellingen",
    Sound: "Geluidseffecten",
    SoundDesc: "Zet geluidseffecten aan, zoals klikken en foutmeldingen",
    AutoHighlight: "Automatisch markeren",
    AutoHighlightDesc: "Automatisch gebouwen markeren van hetzelfde type, wanneer je een gebouw selecteert",
    MusicDesc: "Zet muziek aan: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Icoontjes",
    MisplacedBuilding: "⛔ Dit %{building} gebouw is niet op een correcte goederen opslag gebouwd",
    Left: "Links",
    Right: "Rechts",
    Auto: "Automatisch",
    HighlightBuildings: "Markeer gebouwen",
    HighlightTurnedOff: "...die uitgeschakeld zijn",
    HighlightStockpileModeOn: "...die opslags modus aan hebben",
    HighlightProductionCycleNotDefault: "...die een productie cyclus hebben > 1",
    HighlightMaxInputDistanceNotDefault: "...die een max invoer afstand hebben < ∞",
    HighlightNotMakingProfit: "...die geen winst maken",
    NBuildingsAreHighlighted: "%{n} gebouw(en) is/zijn gemarkeerd",
    OnlyToWarehouse: "Enkel voor opslagplaatsen",
    OnlyToWarehouseDesc: "Enkel opslagplaatsen kunnen goederen transporteren van dit gebouw",
    TurnOffProduction: "Uitschakelen",
    TurnOffProductionDesc:
        "Schakel het gebouw uit. Het gebouw zal niet langer goederen ontvangen en energie verbruiken",
    ApplyToAll: "Pas toe voor alle %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Ongelimiteerd",
    Transport: "Transport",
    TileModifier: "Tegel Modificator",
    ShowAllModifiers: "Toon Alle Modificatoren",
    HideAllModifiers: "Verberg Alle Modificatoren",
    NumberOfBuildings: "Aantal gebouwen dat je bezit",
    ShowContent: "Toon Inhoud",
    HideContent: "Verberg Inhoud",
    BuyExpansionPack: "Kopen voor %{price}",
    Cities: "Steden",
    InputStrategy: "Invoer Strategie",
    InputStrategyClose: "Dichter",
    InputStrategyCloseDesc: "Prefereer de dichtste opslagplaats die genoeg goederen heeft",
    InputStrategyFar: "Verder",
    InputStrategyFarDesc: "Prefereer de verste opslagplaats die genoeg goederen heeft",
    InputStrategyAmount: "Hoeveelheid",
    InputStrategyAmountDesc: "Prefereer de opslagplaats met grootste aantal goederen, ongeacht de afstand",
    FuelCostSave: "Brandstof kosten besparing",
    FuelCostSaveDesc:
        "Opslagplaatsen besparen een bepaald percentage van de brandstof voor binnekomende goederen ten opzichte van andere gebouwen. Hoe hoger het niveau, hoe meer je bespaart",
    SoftwareCompany: "Software Bedrijf",
    Software: "Software",
    ScreenFactory: "Schermen Fabriek",
    Screen: "Scherm",
    JoinDiscord: "Bezoek onze Discord server voor de laatste updates, tips en discussies",
    ClaimOfflineEarning: "Haal de Offline Verdiensten Op",
    OfflineTime: "Offline Tijd",
    Minutes: "%{time}minuten",
    MaxUpgrade: "Maximale uitbreiding",
    MaxUpgradeDesc: "Je hebt het maximaal uitgebreid",
    ClaimAmount: "Geld +%{amount}",
    EarningPerMinute: "Verdienste Ratio",
    EffectiveTime: "Effectieve Tijd",
    EffectiveTimeDesc: "Je effectieve offline verdienste tijd is gelimiteerd tot %{time}min.",
    BuildSearchPlaceholder: "Type gebouw of goederen om te zoeken",
    MineOverlayWarning: "%{building} is niet onder invloed van de tegel modificator",
    WholesaleCenter: "Groothandel",
    OrderFrom: "Bestelling van %{name}",
    ExpireIn: "Vervalt in",
    TurnOnAllProductions: "Productie Aan",
    TurnOnAllProductionsDesc:
        "Zet productie aan van alle gebouwen, kan niet gebruikt worden wanneer Kosten besparingsbeleid actief is",
    OperationSuccessful: "Deze handeling is succesvol afgewerkt",
    TurnOn: "Aanzetten",
    Reward: "Beloning",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cyclus",
    PolicyPoint: "Beleidspunten",
    PolicyPointPerMinute: "Generatie Ratio",
    PolicyPointPerMinuteDesc: "Je ontvangt beleidspunten, elke minuut in het spel",
    YourWilLGaimPolicyPoints: "Je verdient %{amount} beleidspunten in %{time}s",
    PolicyPointDesc: "💡 Hoe meer actieve beleiden, des te hoger de kost per beleid",
    NextOrderIn: "Volgende Bestelling In",
    FillOrder: "Vervul",
    RejectOrder: "Afslaan",
    WholesaleCenterLocked:
        "Je hebt minstens %{required} verschillende goederen nodig om de groothandel te ontgrendelen. Je hebt slechts %{current} goederen",
    OrderFilled: "De bestelling van %{from} is succesvol vervult!",
    PolicyCenter: "Beleidscentrum",
    NewOrder: "Een nieuwe bestelling van %{from} is toegekomen, controleer dit aub in je groothandel",
    Policies: "Beleid",
    PolicyNotEnoughTime: "Je hebt niet genoeg beleidspunten voor dit beleid",
    TimeLeft: "%{time} over",
    WholesaleCenterOrderFaster: "Wereldtentoonstelling",
    WholesaleCenterOrderFasterDesc:
        "Groothandel ontvangt bestellingen 2x sneller en de bestellingsgrootte is 2x groter",
    PolicyOilWellPowerx2: "Supercharge Oliebronnen",
    PolicyOilWellPowerx2Desc: "Oliebronnen produceren 2x olie and gebruiken 2x energie",
    HalfTransportSpeed: "Vertraag om te sparen",
    HalfTransportSpeedDesc: "transport snelheid is vertraagd met 25% en de brandstof prijs is gereduceerd met 25%",
    RefineryMoreOil: "Meer brandstof, meer problemen",
    RefineryMoreOilDesc: "Olie raffinaderijen produceren 50% meer brandstof en 50% minder plastic",
    StickyInput: "Plakkende Invoer",
    StickyInputDesc:
        "Gebouwen zullen transport van voorgaande bron prefereren, in plaats van te zoeken naar de beste bron elke cyclus (GRATIS BELEID)",
    RefineryMorePlastic: "Meer Plastic Meer Problemen",
    RefineryMorePlasticDesc: "Olie Raffinaderijen produceren 50% minder brandstof and 50% meer plastic",
    FreeOilTransportDesc: "Olie transport kost geen brandstof meer maar oliebronnen verbruiken 2x meer energie",
    SuperSteelMill: "Harten van Ijzer",
    SuperSteelMillDesc: "Staalfabrieken verbruiken 50% minder steenkool en 25% meer ijzer en 25% meer energie",
    AlSemiconductor: "Al geleiders",
    AlSemiconductorDesc: "Halfgeleidersfabrieken gebruiken aluminium in plaats van koper",
    CostSaver: "Kosten bespaarder",
    CostSaverDesc: "Als een gebouw zijn invoer meer kost dan z'n eindproduct, schakel dan de productie uit",
    CostSaverBuildingDesc:
        "Kosten bespaarder beleid is actief, productie zal automatisch aan/uit gezet worden naargelang z'n winstgevendheid",
    CostSaverBuildingWarning: "Kosten bespaarder beleid is actief, je kan de productie niet manueel aanpassen",
    GlassUseCoal: "Zwart glas",
    GlassUseCoalDesc: "Glasfabrieken verbruiken 50% meer kolen en 50% minder silicium",
    AdjacentBonusOnlyOutput: "Aanliggend Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Aangrenzingsbonus vereist geen invoer meer, maar verbruikt meer energie en is maar 50% effectief",
    IronMine2xOutput: "Zwaar Ijzer",
    IronMine2xOutputDesc: "Ijzermijnen produceren 2x meer ijzer maar ijzer transport kost 2x meer brandstof",
    SolarPanelAlwaysWork: "De Zon Gaat Nooit Onder",
    SolarPanelAlwaysWorkDesc: "Zonnepanelen werken 100% van de tijd, maar produceren maar 60% energie",
    SteelScience: "Kennis Door Staal",
    SteelScienceDesc: "Staalfabrieken gebruiken 2x invoer en produceren extra wetenschap",
    WholesaleCenterProducingOnly: "Groothandelspartners",
    WholesaleCenterProducingOnlyDesc:
        "Groothandelsbestellingen bevatten enkel goederen die momenteel geproduceert worden ( Je moet ook het aantal vereiste goederen produceren om de groothandel vrij te spelen)",
    ShoppingSpree: "Volop Shoppen",
    ShoppingSpreeDesc:
        "Als product zijn capaciteit tekort komt, pas het tekort dan automatisch bij door aankopen in het handelscentrum (Als de goederen een auto verkoop op hebben staan, zal het dit negeren)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Volop Shoppen Beleid is geactiveerd, handelscentrum zal automatisch het tekort aan goederen kopen",
    ExtraPolicyPoints: "Politieke Lobbyist",
    ExtraPolicyPointsDesc: "Verhoog beleidspunten productie capaciteit met 50%",
    CrAlloyUseFe: "Chromijzer",
    CrAlloyUseFeDesc: "Chroom legeringsfabrieken gebruiken geen Lithium maar 2 ijzer ter vervanging",
    DoubleTileModifier: "Kracht Van De Natuur",
    DoubleTileModifierDesc: "Alle tegel modificatoren effect x2 - zowel de positieve als de negatieve",
    TileModifierOutputOnly: "Tegel Modificator Plus",
    TileModifierOutputOnlyDesc:
        "Tegel modificatoren hebben enkel effect op de opbrengst in plaats van invoer en opbrengst, maar zijn maar 50% effectief",
    GasPlantPetrol: "Gas Liquisatie",
    GasPlantPetrolDesc: "Aardgas energiecentrales gebruiken extra aardgas om petroleum te produceren",
    BuildingRecycle: "Gebouw Recyclage",
    BuildingRecycleDesc:
        "Ontvang een volledige terugbetaling wanneer je een gebouw verkoopt binnen 1 minuut na constructie",
    CoalPlantFuel: "Kolen Liquisatie",
    CoalPlantFuelDesc: "Steenkool energiecentrales verbruiken extra steenkool om brandstof te produceren",
    Welcome: "Welkom",
    SeeTutorialAgain: "Doe de Tutorial opnieuw",
    HelpTranslateTheGame: "Help het spel vertalen🌐",
    SkipTutorial: "Tutorial Overslaan",
    NextTutorial: "Volgende",
    Tutorial1:
        "Industry Idle is een <em>goederen management</em> spel waar je fabrieken bouwt🏭, goederen produceert📦 en geld verdient💸.<br><br>Laat ons door wat basic concepten gaan om je op weg te helpen - Dit gaat niet lang duren, beloofd!",
    Tutorial2:
        "Alle gebouwen hebben energie nodig⚡, je hebt een <em>wind turbine</em> die energie genereert. Je kan je huidige energie toevoer bekijken links in de bovenbalk.<br><br>Het zal je opvallen dat wind turbines maar <em>80%</em> van de tijd werken. Je kan overwegen andere gebouwen van het type energiecentrale te bouwen, die meer stabiele energie leveren.",
    Tutorial3:
        "Je hebt een heel aantal <em>bronnen</em> op de kaart. Om de bronnen te ontmijnen, moeten je mijnen bouwen⛏️ <em>bovenop</em> de bijbehorende bron.<br><br>Bijvoorbeeld, je hebt een <em>oliepomp🛢️</em> die <em>olie</em> op pompt van een oliebron.<br></br>Bronnen zijn onuitputtelijk - geen zorgen dat je zonder zal zitten. Apart van mijnen heb je andere gebouwen die je kan bouwen op lege tegels.",
    Tutorial5:
        "Om geld te verdienen, moet je je goederen exporteren via het handelscentrum. Om dit te doen, activeer je gewoon de <em>automatische verkoop</em> voor deze goederen.<br></br>Je kan ook goederen kopen van het handelscentrum. Onthoud <em>Als je goederen koopt, drijf je de prijs omhoog</em> en als je goederen verkoopt, drijf je de prijs naar beneden.<br><br>De markt is <em>grillig</em> en de prijs veranderd geregeld.",
    Tutorial6:
        "Om nieuwe gebouwen te bouwen, moet je deze eerst vrijspelen in het <em>onderzoeks laboratorium🧪</em>. Het onderzoeks laboratorium converteert ook wetenschapspunten naar onderzoekspunten.<br><br>Je wind turbine (en andere energie centrales) produceren een klein aantal wetenschap wanneer ze aan staan. En je kan een school bouwen🏫 en andere toegewijde gebouwen om je wetenschap later te verhogen.<br><br>Nu dat je al de basics hebt geleerd, start je met je economie op te bouwen.! Hier is wat <em>cash💸</em> en <em>petroleum⛽</em> om je een goede start te geven.",
    WelcomePlay: "Afspelen",
    WelcomePlayMuted: "Afspelen (🔇Muziek)",
    Changelog: "Changelog",
    ChangelogGotIt: "Ik snap het",
    Chat: "Chat",
    Send: "Versturen",
    Import: "Importeren",
    Export: "Exporteren",
    LastBackupAt: "Laatste Backup",
    RestoreFromBackup: "Backup Herstellen",
    RestoreFromBackupFail: "Backup herstel gefaald uit de Steam Cloud. Ben je zeker dat er een backup is?",
    RestoreFromBackupTitle: "Ben je zeker?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChatMessages: "Chat Berichten",
    ChangeName: "Aanpassen",
    SaveName: "Opslaan",
    NameValidationRule: "Je naam mag enkel letters en nummers bevatten en moet tussen 5 en 15 karakters lang zijn",
    NameValidationRuleProfanity: "Je naam mag niet aanstootgevend zijn",
    ChatMessageRateLimit: "Je mag maar om de 10 seconden een bericht versturen",
    NameSaved: "Je naam is succesvol aangepast",
    NoMessages: "Geen nieuwe berichten",
    Leaderboard: "Scorebord",
    Name: "Naam",
    Rank: "Rang",
    Tips1: "Aandelen beoordelingen hebben 5 niveau's: Kopen, Over Presteren, Stagnatie, Onder Presteren en Verkopen",
    Tips2: "Gebouwen zullen stoppen met transporteren van grondstoffen als er al genoeg zijn voor productie, tenzij je opslagmodus aan hebt staan.",
    Tips3: "Brandstof kosten voor goederen transport worden bepaald door afstand en hoeveelheid goederen",
    Tips4: "Gebouwen zullen goederen enkel transporteren als de gevonden hoeveelheid op de kaart de invoer capaciteit overschrijdt",
    Tips5: "Gebouwen zullen goederen enkel transporteren van het handelscentrum als de automatisch verkoop voor dit goed is afgezet",
    Tips6: "Je kan de brandstofkosten voor goederen bekijken onder de bijbehorende invoer capaciteits sectie",
    Tips7: "Als je goederen aankoopt, zal de prijs stijgen. Als je goederen verkoopt zal de prijs dalen",
    Tips8: "Je kan de grafiek voor een goed's aantal en het aanpassen over tijd in het Statistieken Bureau",
    Tips9: "Onderzoekspunten voor een gebouw worden bepaald door de marktprijs en door zijn invoersgoederen",
    Tips10: "Verschillende goederen hebben een verschillende prijs in de markt - wees altijd bereid voor de grillen van de markt",
    Tips11: "Het is een goed idee om altijd je energie en brandstof voorraad te controleren voordat je de productie gaat uitbreiden",
    FPS30: "Energie Besparing",
    OfflineModeDesc:
        "Kan niet met de server connecteren: Offline verdiensten worden niet gegenereerd. Gelieve je internet connectie na te kijken",
    OptOut: "Deactiveer",
    OptIn: "Reset en activeer",
    LeaderboardOptOut: "Scorebord Deactiveren",
    LeaderboardOptOutDesc:
        "Dit zal niet langer je score naar het scorebord versturen. LET OP: als je het scorebord later wil activeren, moet je data een reset ondergaan",
    LeaderboardOptIn: "Reset en activeer scorebord",
    LeaderboardOptInDesc: "Je data moet een RESET ondergaan voor je het scorebord terug kan activeren, ben je zeker?",
    RewardAdsFailed: "Beloningsvideo is niet beëindigd",
    RewardAdsNotAvailable: "Beloningsvideo niet beschikbaar (momenteel enkel iOS/Android ondersteund)",
    OfflineEarningDoubleSuccess: "Je hebt  je offline verdiensten verdubbelt",
    FPS30Desc:
        "De energie besparingsmode activeren zal het spel laten draaien op 30 FPS in plaats van 60 FPS. Dit laat je batterij langer meegaan",
    HighlightAll: 'Markeer "%{type}"',
    HighlightInput: "🔍 Markeer %{type} Invoer",
    HighlightOutput: "🔍 Markeer %{type} Opbrengst",
    TotalInput: "Totale Invoer Capaciteit",
    TotalOutput: "Totale Opbrengst Capaciteit",
    RunOutIn: "Uit in %{time}",
    FuelRunOutWarning:
        "💡 Je brandstof consumptie is groter dan je productie. Wanneer brandstof op is, valt je transport stil",
    InAmount: "In: %{number}",
    OutAmount: "Uit: %{number}",
    SwissBank: "Zwitserse Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Als je in een nieuwe stad start, ontvang je %{money} 💵",
    RestorePurchases: "Aankopen herstellen",
    RestorePurchasesSuccess: "Je aankopen zijn hersteld",
    RestorePurchasesFailed: "Je aankopen zijn niet hersteld",
    ExpansionPacks: "Uitbreidingspakketten",
    ExpansionPack1: "Uitbreidingspakket 1",
    ExpansionPack1Owned: "Uitbreidingspakket 1",
    RequireExpansionPack1: "Uitbreidingspakket 1",
    RequireExpansionPack1Desc: "Dit is enkel beschikbaar voor Uitbreidings Pakket 1",
    RequireAnyExpansionPack: "Uitbreidingspakket Exclusief",
    RequireAnyExpansionPackDesc: "Om dit te gebruiken heb je minstens 1 uitbreidingspakket nodig",
    HideRewardAd: "Verberg toegewezen advertenties",
    HideRewardAdDesc:
        "Alle advertenties in het spel zijn optionele belonings advertenties. Dit verbergt alle beloningsopties in het spel.",
    HideDiscordBanner: "Verberg Discord Banner",
    HideDiscordBannerDesc: "Verberg Discord en de winkelbanner in het hoofdkwartier",
    HideChat: "Verberg Chat Bericht",
    SortedByDeficit: "Gesorteerd op tekorten",
    PurchaseFailed: "De aankoop is niet doorgegaan",
    PurchaseSteamContinue: "Beëindig je aankoop aub op Steam",
    PurchaseSuccess: "Je aankoop is afgerond, bedankt voor je steun",
    PrestigeCurrency: "Zwitsers Geld 💵",
    RestartDesc:
        "💡 Wil je enkel herstarten? Je kan op start klikken in Start In Een Nieuwe Stad en je huidige stad kiezen",
    PrestigeGoBack: "Ga Terug",
    PermanentUpgradeDesc: "Deze opwaardering wordt overgedragen naar de volgende stad",
    ProductionMultiplier: "Productie Vermedigvuldiger",
    ProductionMultiplierDesc:
        "Een boost aan al je gebouwen productie capaciteiten (inclusief mijnen, fabrieken, energie centrales, wetenschap en cultuur gebouwen)",
    FuelCostDiscount: "Brandstof Kosten Korting",
    FuelCostDiscountDesc: "Geeft een korting op de brandstof kosten wanneer je goederen transporteert",
    AutoSellCapacityMultiplier: "Automatische Verkoopscapaciteit vermedigvuldiger",
    AutoSellCapacityMultiplierDesc:
        "Een vermedigvuldiger die toegepast wordt op je automatische verkoopscapaciteit, ongacht de huidige capaciteit",
    BuildingPermitCostDivider: "Bouwvergunning Kosten Deler",
    BuildingPermitCostDividerDesc: "Deel de prijs van Bouwvergunningen door deze factor",
    ExtraAdjacentBonus: "Extra Aangrenzingsbonus",
    ExtraAdjacentBonusDesc: "Extra bonus capaciteit voor elke aanliggend gebouw van hetzelfde type",
    OfflineEarningMultiplier: "Offline Verdienste Vermedigvuldiger",
    OfflineEarningMultiplierDesc: "Een vermedigvuldiger die je offline verdiensten verhoogt",
    PrestigeAlertTitle: "Ben je zeker?",
    PrestigeAlertContent:
        "Je bedrijf zal geliquideerd worden. Je ontvangt %{amount} Zwitsers geld en start een nieuw bedrijf in %{city}",
    PrestigeCurrencyDesc:
        "Dit is het geld in je geheime Zwitserse bankrekening, Je kan dit meedragen als je in een nieuwe stad start",
    Prestige: "Uitbetalen",
    Cancel: "Annuleren",
    SaveFileCorrupted: "Opslagbestand Gecorrupteerd",
    CheatDetected:
        "Je oude opslag bestand heeft de server validatie niet doorstaan en kan niet gelezen worden. Je zal starten met een nieuwe opslag bestand",
    LoadGameError: "Spel laden gefaald",
    LoadGameErrorMessage: "Foutmelding: %{message}",
    LoadGameErrorDesc:
        "Controleer aub je internet connectie. Als het probleem aanhoudt, gelieve support te contacteren",
    ExpansionPackIncompatible:
        "Je probeert een save file te importeren met uitbreidingspakketten, maar je spel heeft niet de nodige uitbreindingspakketten",
    SaveFileMigrated: "Een nieuwe Era: De Beta Is Hier",
    SaveFileMigratedDesc:
        "Bedankt om mee te testen in de alpha. Je oude map is niet compatibel, maar we hebben je data gemigreerd en je een bonus gegeven",
    ClaimSwissMoney: "%{amount} Zwitsers geld opeisen 💵",
    SaveFileMigratedFinePrint:
        "Je markt Kapitalisatie is geconverteerd naar Zwitsers geld en je niet uitgegeven Zwitsers geld wordt mee overgebracht. Je zal 50% bonus Zwitsers geld ontvangen om mee te speltesten in de alpha. Max Zwitsers geld dat mee overgebracht kan worden is gelimiteerd tot 200",
    CashIn: "Uitbetalen",
    CurrentCity: "Huidige Stad",
    CashInDesc:
        "Je zal dit bedrag in je Zwitserse bankrekening ontvangen als je in een nieuwe stad start. Het is gebaseerd op markt capaciteit van je bedrijf en het moet %{amount} bereiken voordat je Zwitsers geld kan verdienen",
    MoveToNewMap: "Start In Een Nieuwe Stad",
    CityName: "Stad",
    CitySize: "Stads Grootte",
    GridType: "Rooster Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "Stadsbonus",
    ResourceTilePercentage: "Grondstof Tegels",
    MapSquareGrid: "Vierkant",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Staalfabrieken hebben 2x capaciteit</li><li>Roestvrij Staalfabrieken hebben 2x capaciteit</li><li>Gratis ijzertransport</li><li>Staal transport kost 50% minder brandstof</li><li>Start met 2x auto verkoop capaciteit</li><li>Geen tegel modificators</li>",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin fabrieken zijn vrijgespeeld</li><li>Halfgeleiderfabrieken hebben 2x productiviteit</li><li>Scheepswerven hebben 2x capaciteit</li><li>Autofabrieken hebben 2x capaciteit</li><li>Li-ion batterijfabrieken zijn vrijgespeeld</li>",
    Toulouse: "Toulouse",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums zijn vrijgespeeld</li><li>Colosseums hebben 2x productiviteit</li><li>Start met een niveau 5 beleidscentrum</li><li>Opera huizen hebben 2x capaciteit</li><li>Opnamestudios produceren ook cultuur</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Start met niveau 5 Onderzoeks Laboratorium</li><li>Technische school is vrijgespeeld</li><li>Universiteient hebben 2x capaciteit</li><li>Scholen hebben 2x capaciteit</li><li>Universiteiten hebben 2x productiviteit</li>",
    HideNotProducing: "Verberg goederen die niet geproduceerd worden",
    SortByStorage: "Opslag",
    SortByProduction: "Productie",
    SortByName: "Naam",
    PlayerTrade: "Speler Handel",
    AddTradeFail: "Handelsoffer toevoegen gefaald",
    AddTradeExceedMaximumTrade:
        "Je kan maximum %{number} actieve handelsoffers hebben, claim ze op of annuleer ze eerst",
    AddTradeSuccess: "Je handelsoffer is succesvol toegevoegd",
    LoadTradeFail: "Spelers handel laden is gefaald, probeer later opnieuw",
    ClaimTradeFail: "Handelsoffer claimen is gefaald, probeer later opnieuw",
    CancelTradeSuccess: "Jou handelsoffer is succesvol geannuleerd",
    CancelTradeFail: "Handelsoffer annuleren is gefaald, probeer later opnieuw",
    AcceptTradeFail: "Handelsoffer accepteren is gefaald, probeer later opnieuw",
    PlayerTradeBanner: "Handel goederen met andere spelers",
    PlayerTradeResource: "Goederen",
    PlayerTradeAmount: "Aantal",
    PlayerTradePrice: "Prijs $",
    PlayerTradeValue: "Waarde $",
    PlayerTradeWaiting: "Wachten...",
    UseTradeCenterPrice: "Gebruik Handelscentrum Prijs",
    AddTrade: "Handelsoffer toevoegen",
    ActiveTrades: "Actieve handelingen",
    AcceptTrade: "Accepteer",
    CancelTrade: "Annuleer",
    RefundTrade: "Refund",
    RefundTradeSuccess: "Deze transactie werd terugbetaald: %{resource} is terugbetaald aan je handelscentrum",
    RefundTradeFail: "Transactie terugbetalen is gefaald, probeer aub later opnieuw",
    ClaimTrade: "Claim",
    RefreshTrade: "Ververs",
    PasteYourSave: "Plak uw opslag data aub",
    FailedToImportSave: "opgeslagen data importeren gefaald",
    FailedToImportSaveDesc: "je opgeslagen bestand is incompatibel or gecorrumpteerd: %{error}",
    SaveCopiedToClipboard: "Je opgeslagen data is gekopieerd naar je klembord",
    CancelActiveTradeFirst: "Je hebt actieve speler transacties, annuleer of eis ze aub eerst op",
    FailedToCheckActiveTrade: "Controleren van actieve speler transacties gefaald, probeer aub later opnieuw",
    PlayerTradeQuotaExceed: "Deze transactie heeft uw quota overschreden",
    PlayerTradeValidRange: "Bereik: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Kan Betalen",
    PlayerTradeQuota: "Resterend quota: %{value}",
    PlayerTradeUnavailable:
        "Je hebt minstens één product in productie en in opslag nodig voor je kan handelen met spelers",
    PlayerTradeToClaim: "Je hebt %{num} nieuwe transactie(s) om te claimen in Speler transacties",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transporteer en sla mijn goederen op en met lagere brandstof kosten",
    PowerBankChargeSpeed: "Oplaadsnelheid",
    PowerBankPowerLeft: "Resterende Energie",
    PowerBankMoreCapacity: "Batterij Besparing",
    PowerBankMoreCapacityDesc: "Power banks laden op met 50% snelheid maar hebben 50% meer capaciteit",
    PowerBankNotWorking: "⛔ Power banks werken enkel naast een energiecentrale",
    ExcludeBuildingsShutdown: "Sluit gebouwen uit die gesloten zijn",
    ColorTheme: "Spel kleurenthema",
    ColorThemeDesc: "Kleurenthema voor spelicoontjes, markeringen, grid en achtergrond. VEREIST HERSTART",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Industrial Revolution",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "This will hide resource movement (those tiny dots) by default and only show the movement when you select a building",
    PowerBankLeft: "Power Bank",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Cancel This Trade?",
    CancelTradeConfirmDialogYes: "Yes",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Add Route",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Find on Map",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consumption",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Player Flag",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    WarehouseOutwardFuelSave: "Free Delivery",
    WarehouseOutwardFuelSaveDesc: "Warehouses provide the same fuel save on outward transportation as well",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Resources tend to spawn in clusters</li><li>Warehouse provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Terms of Service",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Manga Publisher",
    Manga: "Manga",
    AnimeStudio: "Anime Studio",
    Anime: "Anime",
    PlayerTradeAction: "Action",
    PlayerTradeBuy: "Buy",
    PlayerTradeSell: "Sell",
    PlayerTradeBid: "Bid",
    PlayerTradeAsk: "Ask",
    CancelTradeConfirmDialogDescV2:
        "Cancelling this trade will refund %{percent} of the resource/cash. Resources will be refunded to Trade Center warehouse",
    ClaimTradeSuccessV2: "Your trade has been claimed successfully: %{cashOrResource}",
    AcceptTradeSuccessV2: "This trade has been accepted by you: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Better Than Market Price",
    ResourceExplorer: "Resource Explorer",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explore",
    ProductionSettings: "Production Settings",
    PlayerTradeQuotaDesc: "💡 Player trade quota is %{percent} of your market cap, it resets when the market updates",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Game Guides",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ShowProfitBreakdown: "Show Profit Breakdown",
    HideProfitBreakdown: "Hide Profit Breakdown",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Fuel Cost",
    BuildingProfit: "Profit",
    RestoreBackup: "Restore",
    SteamLogin: "Sign In Through Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Sign In",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "International Export Trade",
    FreeTransportToTradeCenterDesc:
        "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "In Storage: %{amount}",
    PlayerTradeFillValue: "Value",
    FiberFactory: "Fiber Factory",
    Fiber: "Fiber",
    Achievements: "Achievements",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Reward: Swiss Money +%{swiss}",
    AchievementsRewardToast: "You have claimed the reward:  Swiss Money +%{swiss}",
    AchievementsClaim: "Claim",
    AchievementsToast: "You have achieved %{name}, claim your reward in Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Force Steam Cloud Sync",
    UILoading: "Loading...",
    UserAuthenticated: "You are authenticated",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardBySwissPerBuilding: "Current Swiss Money Per Building",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Save and Exit Game",
    SaveAndExitDesc:
        "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Force Scroll",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ResourceExplorer2Desc: "Resource explorers produce 2x output but use 2x power",
    ConstructionCancel: "Cancel Construction",
    ConstructionPause: "Pause",
    ConstructionResume: "Resume",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
    HighlightUnderConstruction: "...that haven't been constructed",
    HighlightUnderLevel10: "...that are under level 10",
    HighlightUnderLevel20: "...that are under level 20",
    HighlightUnderLevel30: "...that are under level 30",
    Logout: "You Are Logged Out",
    ConstructionStatusQueueingV2: "Queueing",
    ConstructionStatusPausedV2: "Paused",
    ConstructionStatusBuildingV2: "Building",
    ConstructionStatusUnpaidV2: "Unpaid",
    ConstructionStatus: "Construction Status",
    ConstructionStart: "Start",
    CostFree: "Free",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Only you",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "increased by %{percent}",
    MarketNewsDecrease: "decreased by %{percent}",
    MarketNewsBuilding: "This building is affected by %{num} news",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    OsloBonusV2:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Resource Booster",
    BuildWarningTitle: "Building Might Not Work",
    BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
    BuildWarningBuildAnyway: "Build Anyway",
    ResourceBoosterNotWorking: "⛔ Resource boosters only work next to deposit mines",
    ResourceBoosterPercentage: "💡 This building gets %{percent} output boost from adjacent resource boosters",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
    BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "Have 50 production lines that has production deficit",
    UseScientificNotation: "Use Scientific Notation",
    UseScientificNotationDesc: "Use scientific notation (e notation) for numbers larger than 999.9T",
    LogoutDescV2:
        "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
    LogBackIn: "Log Back In",
    PlayerTradeNowAllowedV2: "Player trades are not available within %{hour} hours of restoring/importing a save",
    ServerDisconnected:
        "You are disconnected from the server, please check your internet connection and restart the game",
    BuildingUpgradeCostDividerDescV2: "Divide building upgrade cost by this divider",
    ResourceBoosterBannerDesc:
        "💡 You currently have %{number} resource boosters - the power and science input of each is scaled to the number of resource boosters you currently have",
    ResourceBoosterDesc: "Boost the output of adjacent mines",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Dynamite Factory",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Nuclear Missile Factory",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Space Colony",
    SpaceColonyInc: "Space Colony",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    IronSteelZone: "Iron Steel Zone",
    IronSteelZoneDesc:
        "Resource booster provide a %{percent} output bonus to adjacent steel mills or stainless steel plants for each working iron mine it is boosting",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
    ToulouseBonusV2:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
};
