export const NL = {
    OK: "OK",
    SteelMill: "Staalfabriek",
    StainlessSteelPlant: "Roestvrij Staalfabriek",
    CircuitFoundry: "Geintegreerde Schakelingenfabriek",
    IntegratedCircuit: "Geintegreerde schakeling",
    OilWell: "Oliebron",
    Wood: "Hout",
    LoggingCamp: "Houthakkers kamp",
    LumberMill: "Houtzagerij",
    Lumber: "Timmerhout",
    Paper: "Papier",
    PaperMill: "Papierfabriek",
    Book: "Boek",
    BookPublisher: "Boek Uitgeverij",
    OilRefinery: "Olie Raffinaderij",
    Sell: "Verkopen",
    Upgrade: "Opwaarderen",
    Build: "Bouwen",
    Inspect: "Inspecteren",
    Buildings: "Gebouwen",
    Iron: "Ijzer",
    Actions: "Acties",
    FuelType: "Kies Brandstof",
    FuelCost: "Brandstof Kosten",
    FuelConsumption: "%{fuel} Consumptie",
    FuelEconomy: "Brandstof Economie",
    FuelProduction: "%{fuel} Productie",
    FuelInStorage: "%{fuel} In Opslag",
    Plastic: "Plastic",
    FuelSurplus: "%{fuel} Overschot",
    Petrol: "Petroleum",
    Buy: "Kopen",
    NoLiquidity: "Geen Liquiditeit",
    NoLiquidityTurnOffAutoSell: "er is niet genoeg liquiditeit in de markt voor %{res}, auto verkopen is stil gezet",
    Multiplier: "Vermenigvuldiger",
    MultiplierDesc: "Elke 10 levels, krijg je +1 vermenigvuldiger",
    SellBuilding: "Verkoop Gebouw",
    PowerGrid: "Stroomnet",
    TradeAmount: "Handel Bedrag",
    SortBy: "Sorteren door",
    SortByPrice: "Prijs",
    SortByAmount: "Aantal",
    NotEnoughResourcesForTrade: "niet genoeg goederen in het handelscentrum  voor deze verhandeling",
    NotEnoughResources: "niet genoeg goederen voor deze operatie",
    Transportation: "Transport",
    Cash: "Cash",
    Aluminum: "Aluminium",
    ResearchPoint: "OnderzoeksPunt",
    Unlock: "Ontgrendelen",
    BuildingUnlocked: "%{building} is ontgrendeld",
    Science: "Wetenschap",
    ScienceFromPowerDesc: "Energiecentrale produceert een klein aantal wetenschap bij het aanmaken van energie",
    Culture: "Kultuur",
    School: "School",
    University: "Universiteit",
    Polytechnic: "Hoger Beroepsonderwijs",
    Colosseum: "Colosseum",
    WindTurbine: "Wind Turbine",
    Engine: "Motor",
    EngineFactory: "Motor Fabriek",
    CameraFactory: "Camera Fabriek",
    Camera: "Camera",
    Gun: "Wapen",
    GunFactory: "Wapen Fabriek",
    Aircraft: "Vliegtuig",
    AircraftFactory: "Vliegtuig Fabriek",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Zeppelin Fabriek",
    Tank: "Tank",
    TankFactory: "Tank Fabriek",
    MinimumTradingAmount: "Je kan niet handelen onder het minimum aantal",
    CoalPowerPlant: "Kolen Centrale",
    PetrolPowerPlant: "Petroleum Centrale",
    Copper: "Kopen",
    Gas: "Natuurlijk Gas",
    GasPump: "Natuurlijke Gas Pomp",
    GasPowerPlant: "Gas Centrale",
    Missile: "Missile",
    MissileFactory: "Missile Fabriek",
    Rocket: "Raket",
    RocketFactory: "Raket Fabriek",
    BuildingPermit: "Bouw Toelating",
    BuildingPermitDesc:
        "Je hebt de toelating voor %{amount} gebouwen, je hebt er al %{amountBuilt} gebouwd en hebt er  %{amountLeft} over",
    BuildingLocked: "Bouwen is nog niet beschikbaar, Je moet dit eerst ontgrendelen in het Onderzoekslaboratorium",
    BuildQueue: "Gebouwen Rij",
    BuildQueueDesc: "Aantal gebouwen momenteel in de rij",
    MaxBuilders: "Max Bouwers",
    MaxBuildersDesc: "Aantal gebouwen dit je tegelijk kan bouwen",
    Silicon: "Silicium",
    AluminumMine: "Aluminium Mijn",
    CopperMine: "Kopermijn",
    SiliconMine: "Silicium mijn",
    IronMine: "Ijzermijn",
    CoalMine: "Kolenmijn",
    Headquarter: "Hoofdkwartier",
    ResearchLab: "Onderzoekslaboratorium",
    TradeCenter: "Handelscentrum",
    Resources: "Goederen",
    NotEnoughPower: "💡 Niet genoeg stroom, overweeg energie productie te verhogen",
    NotEnoughFuel: "Niet genoeg %{fuel} voor deze operatie",
    NotEnoughCash: "Niet genoeg cash voor deze operatie",
    NotEnoughSwissMoney: "Niet genoeg Zwitsers geld voor deze operatie",
    BuildingNotEnoughFuel: "💡 Niet genoeg %{fuel}",
    AutoSell: "Automatisch Verkopen",
    SellAll: "Verkoop Alles",
    Change: "Aanpassen",
    StatisticsBureau: "Statistiek Bureau",
    LogisticsDepartment: "Logistiek Departement",
    From: "Van",
    Top20FuelCost: "Top 20 Brandstof Kost",
    To: "Tot",
    TransportTime: "Transport Tijd",
    TopN: "Top %{n}",
    Warehouse: "Opslagplaats",
    TradeWarehouse: "Verhandel Opslagplaats",
    Coal: "Kolen",
    Video: "Video",
    ClothingFactory: "Kleding Fabriek",
    Clothes: "Kleding",
    Fashion: "Mode",
    FashionFactory: "Mode Fabriek",
    VideoFarm: "Video Studio",
    SantaFactory: "Kerstman Fabriek",
    Santa: "Kerstman",
    Car: "Auto",
    CarFactory: "Auto Fabriek",
    Ship: "Schip",
    SolarPanel: "Zonnepaneel",
    SolarPanelDesc: "💡 Zonnepalenen werken maar 5 van elke 10 seconden - alle cyclussen zijn uitgelijnd",
    WindTurbineDesc: "💡 Wind turbines werken maar 8 van elke 10 seconden - cyclussen zijn niet uitgelijnd",
    Movie: "Film",
    MovieStudio: "Film Studio",
    Sitcom: "Sitcom",
    TVStudio: "TV Studio",
    PC: "PC",
    GameStudio: "Game Studio",
    Game: "Game",
    ComputerFactory: "Computer Fabriek",
    Shipyard: "Scheepswerf",
    PowerUsage: "Stroom verbruik",
    PowerSupply: "Stroom toevoer",
    PowerSurplus: "Stroom overschot",
    Level: "Level",
    Power: "Stroom",
    CentralBank: "Centrale Bank",
    ResourceInput: "In",
    ResourceOutput: "Uit",
    ResourceStorage: "Opslag",
    ResourceChange: "Aanpassing",
    ResourceInOutDesc: "💡 Tik op bovenliggende Uit-In nummers om de bijbehorende uitgaande en inkomende gebouwen te markeren",
    ResourceChart: "Goederen Grafiek",
    MarketUpdateIn: "Markt opwaardering In %{time}",
    Income: "Inkomen",
    Semiconductor: "Halfgeleiders",
    SemiconductorFactory: "Halfgeleiders Fabriek",
    SemiconductorFab: "Halfgeleiders Fab",
    Steel: "Staal",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Boerderij",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Boerderij",
    Guitar: "Guitaar",
    GuitarFactory: "Guitaar Fabriek",
    Drum: "Drum",
    DrumFactory: "Drum Fabriek",
    RecordingStudio: "Opname Studio",
    OperaHouse: "Opera Huis",
    CoalGasificationPlant: "Kolen Gasificatie Centrale",
    GasProcessingPlant: "Gas verwerkingscentrale",
    Music: "Muziek",
    Glass: "Glas",
    PhoneFactory: "Telefoon Fabriek",
    Phone: "Telefoon",
    GlassFactory: "Glas Fabriek",
    Oil: "Olie",
    Chromium: "Chroom",
    ChromiumMine: "Chroom Mijn",
    Uranium: "Uranium",
    EnrichedUranium: "Verrijkt Uranium",
    NuclearPowerPlant: "Nucleare Energiecentrale",
    UraniumEnrichmentPlant: "Uranium VerrijkingsCentrale",
    UraniumMine: "Uranium Mijn",
    Titanium: "Titanium",
    TitaniumMine: "Titanium Mijn",
    TitaniumAlloyPlant: "Titanium Legering Fabriek",
    ChromiumAlloyPlant: "Chroom Legering Fabriek",
    Input: "Invoer",
    PanelPosition: "Paneel Positie",
    PanelPositionDesc: "Toon zijpaneel aan de linkerkant, rechterkant of auto (afhankelijk van de geselecteerde tegel)",
    InputCapacity: "Invoer Capaciteit",
    InputCapacityPerCycle: "Invoer Capaciteit / Cyclus",
    Output: "Opbrengst",
    OutputCapacity: "Opbrengst Capaciteit",
    OutputCapacityPerCycle: "Opbrengst Capaciteit / Cyclus",
    ResourceDeposit: "Goederen Opslag",
    RecommendedBuilding: "💡 Deze tegel heeft %{resource} opslag",
    AdjacentBonus: "Aangrenzend Bonus",
    AdjacentBonusDesc: "Je krijgt %{bonus}% extra capaciteit voor elke aangrenzend werkend gebouw van hetzelfde type",
    ConsiderIncreaseProduction: "💡 Overweeg %{resource} productie te verhogen",
    AlwaysTransportInput: "Stapel Mode",
    AlwaysTransportInputTradeCenter: "Altijd Exporteren",
    AlwaysTransportInputTradeCenterDesc:
        "Altijd transporteren naar het handelscentrum, ook al is de automatische verkoop niet geactiveerd voor dit goed",
    AlwaysTransportInputDesc: "Altijd invoer goederen transporteren, zelfs als deze boven de minimale productie vereisten liggen",
    ProductionCycleLength: "Productie Cyclus",
    ProductionCycleLengthDesc:
        "Langte van één productie cyclus, gemeten in seconden. De cyclus verlengen zal de invoer/uitvoer per cyclus verhogen, dus bijgevolg de prioriteit verlagen bij het ophalen van invoergoederen",
    MaxInputDistance: "Max Invoer Afstand",
    MaxInputDistanceDesc:
        "De maximum afstand dat dit gebouw invoer van goederen kan doen, gemeten in aantal tegels",
    AutoSellCapacity: "Auto Verkoop Capaciteit",
    AutoSellCapacityDesc: "Max aantal goederen die de auto verkoop kan verwerken per seconde, per goed",
    CurrentAutoSellCapacityMultiplier: "Huidige vermenigvuldiger: x%{n}",
    AutoSellConcurrency: "Auto Verkoop Gelijktijdigheid",
    AutoSellConcurrencyDesc: "Max aantal goederen die je tegelijk kan verkopen",
    MaxAutoSellConcurrencyReached:
        "Je hebt het maximum automatische verkopen gelijktijdig bereikt, deactiveer een andere auto verkoop om deze te activeren",
    CannotSellBuilding: "Je kan dit gebouw momenteel niet verkopen",
    WallStreet: "Wall Street",
    MarketCap: "Markt Cap",
    MarketCapDesc: "Totale markt capitalisatie (i.e. markt waarde) van je bedrijf",
    BuildingValuation: "Gebouw waarde",
    BuildingValuationDesc: "Totale waarde van je gebouwen, inclusief gebouwtoelatingen en opwaarderingen",
    ResourcesValuation: "Goederen waardering",
    ResourcesValuationDesc: "Totale waarde van je goederen in je inhoud",
    Battery: "Batterij",
    BatteryFactory: "Batterij Fabriek",
    RatingBuy: "Kopen",
    RatingSell: "Verkopen",
    SwissShop: "Zwitserse Winkel",
    RatingHold: "Bijhouden",
    RatingOutperform: "Over Presteren",
    RatingUnderperform: "Onder Presteren",
    StockRating: "Aandeel Beoordeling",
    JetEngine: "Straalmotor",
    Helicopter: "Helicopter",
    Lithium: "Lithium",
    LithiumMine: "Lithium Mijn",
    LiionBatteryFactory: "Li-ion Batterij Fabriek",
    HelicopterFactory: "Helicopter Fabriek",
    Satellite: "Satelliet",
    ToyFactory: "Speelgoed Fabriek",
    Toy: "Speelgoed",
    SpaceStation: "Space Station",
    SpaceStationFactory: "Space Station Fabriek",
    OperatingSystem: "Besturingssysteem",
    OperatingSystemCompany: "Besturingssysteem Inc",
    LinuxDistribution: "Linux Distributie",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Console",
    ConsoleFactory: "Console Fabriek",
    Train: "Trein",
    TrainFactory: "Trein Fabriek",
    ShoeFactory: "Schoen Fabriek",
    Shoes: "Schoen",
    ArtilleryFactory: "Artillerie Fabriek",
    Artillery: "Artillerie",
    SubmarineFactory: "Duikboot Fabriek",
    Submarine: "Duikboot",
    Spaceship: "Ruimteschip",
    RobotFactory: "Robot Fabriek",
    Robot: "Robot",
    SpaceshipFactory: "Ruimteschip Fabriek",
    SatelliteFactory: "Satellite Fabriek",
    JetEngineFactory: "Straalmotor Fabriek",
    StockRatingDesc:
        "Aandeel beoordeling consensus van Wall Street analysten, die je markt cap beïnvloeden en wordt geüpdate met de markt",
    InterestRate: "Overnacht Interesten Ratio",
    InterestRateDesc: "Interesten die je verdient op je markt capitalisatie terwijl je offline bent",
    OfflineEarning: "Offline Verdiensten",
    OfflineEarningDesc: "Offline verdiensten zijn afhankelijk van je markt cap en interest ratio",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline Verdiensten Tijd",
    OfflineEarningTimeDesc: "Je zal tot deze limiet verdienen terwijl je offline bent",
    BuyPermit: "Koop Toelating",
    NotEnoughBuildingPermit: "Niet genoeg gebouw toelatingen. Koop er AUB meer om gebouwen te kunnen kopen",
    MovingAverage: "Lopend Gemiddelde",
    MovingAverageDesc: "Toon lopende gemiddeldes van de goederen veranderingen, in plaats van realtime veranderingen",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Zet zoom support aan. Gebruik je muiswiel om in te zoomen. Huidige zoom is %{zoom}",
    AllowZoomMobileDesc: "Turn on zoom support. You can pinch to zoom. Current zoom is %{zoom}",
    Settings: "Instellingen",
    SellBuildingDesc:
        "Een gebouwe verkopen geeft je 50% van de investering terug en 50% van de goederen worden naar het Handelscentrum getransporteerd",
    SellBuildingFullRefundDesc:
        "Gebouw recyclage toelating is actief, een gebouw verkopen zal je nu volledig terugbetalen tot %{time}",
    Sound: "Geluidseffect",
    SoundDesc: "Zet geluidseffecten aan, zoals klikken en foutmeldingen",
    AutoHighlight: "Auto Markeren",
    AutoHighlightDesc: "Automatisch gebouwen markeren van hetzelfde type, wanneer je een gebouw selecteert",
    MusicDesc: "Zet muziek aan: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Icoontjes",
    MisplacedBuilding: "⛔ Dit %{building} gebouw is niet op een correcte goederen opslag gebouwd",
    UnderConstruction: "%{building} is onder constructie",
    Left: "Links",
    Right: "Rechts",
    Auto: "Auto",
    HighlightBuildings: "Markeer gebouwen",
    HighlightTurnedOff: "...die gesloten zijn",
    HighlightStockpileModeOn: "...die opslage mode aan hebben",
    HighlightWarehouseOnly: "...die enkel voor opslagplaatsen zijn",
    HighlightProductionCycleNotDefault: "...Die een productie cyclus hebben > 1",
    HighlightMaxInputDistanceNotDefault: "...die een max invoer afstand hebben < ∞",
    HighlightNotMakingProfit: "...die geen winst maken",
    NBuildingsAreHighlighted: "%{n} gebouw(en) is/zijn gemarkeerd",
    OnlyToWarehouse: "Enkel voor opslagplaatsen",
    OnlyToWarehouseDesc: "Enkel opslagplaatsen kunnen goederen transporteren naar dit gebouw",
    TurnOffProduction: "Afsluiten",
    TurnOffProductionDesc:
        "Sluit de productie van het gebouw af. Het gebouw zal niet langer goederen transporteren en stroom verbruiken",
    ApplyToAll: "Geld voor alle %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Ongelimiteerd",
    Transport: "Transport",
    TileModifier: "Tegel Modificator",
    ShowAllModifiers: "Toon Alle Modificatoren",
    HideAllModifiers: "Verberg Alle Modificatoren",
    NumberOfBuildings: "Number of buildings you have",
    ShowContent: "Toon Inhoud",
    HideContent: "Verberg Inhoud",
    BuyExpansionPack: "Koop voor %{price}",
    Cities: "Steden",
    WarehouseInputCapacityDesc: "Aantal goederen die het opslagplaats kan inwaards kan transporteren, per seconde, per goed.",
    WarehouseBuildDesc: "Opslagplaatsen kunnen eender welke goederen transporteren en opslaan",
    InputStrategy: "Invoer Strategie",
    InputStrategyClose: "Dichter",
    InputStrategyCloseDesc: "Prefereer de dichtste opslagplaats die genoeg goederen heeft",
    InputStrategyFar: "Verder",
    InputStrategyFarDesc: "Prefereer de verste opslagplaats die genoeg goederen heeft",
    InputStrategyAmount: "Aantal",
    InputStrategyAmountDesc: "Prefereer de opslagplaats met grootste aantal goederen, ongeacht de afstand",
    FuelCostSave: "Brandstof kosten besparing",
    FuelCostSaveDesc:
        "Opslagplaatsen besparen een bepaald percentage van de brandstof voor binnekomende goederen in tegenoverstelling tot andere gebouwen. Hoe hoger het niveau, te meer je bespaart",
    SoftwareCompany: "Software Bedrijf",
    Software: "Software",
    ScreenFactory: "Scherm Fabriek",
    Screen: "Scherm",
    JoinDiscord: "Bezoek onze Discord server voor de laatste updates, tips en discussies",
    ClaimOfflineEarning: "Eis Offline Verdienste Op",
    OfflineTime: "Offline Tijd",
    Minutes: "%{time}min",
    MaxUpgrade: "Max opwaardering",
    MaxUpgradeDesc: "Je hebt het maximum opgewaardeerd",
    ClaimAmount: "Cash +%{amount}",
    EarningPerMinute: "Verdienste Ratio",
    EffectiveTime: "Effectieve Tijd",
    EffectiveTimeDesc: "Je effectieve offline verdienste tijd is gelimiteerd tot %{time}min.",
    BuildSearchPlaceholder: "Type gebouw of goederen om te zoeken",
    MineOverlayWarning: "%{building} is niet onder invloed van de tegel modificator",
    WholesaleCenter: "Groothandel",
    OrderFrom: "Bestelling van %{name}",
    ExpireIn: "Vervalt op",
    ProfitMargin: "Winstmarge",
    NotMakingProfitWarning: "💡 Productie niet winstmakend, overweeg om het te sluiten",
    TurnOnAllProductions: "Productie Aan",
    TurnOnAllProductionsDesc: "Zet productie aan van alle gebouwen, kan niet gebruikt worden wanneer Kosten besparingsbeleid actief is",
    OperationSuccessful: "Deze operatie is succesvol afgewerkt",
    TurnOn: "Aanzetten",
    Reward: "Beloning",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cyclus",
    PolicyPoint: "Beleidspunt",
    PolicyPointPerMinute: "Genereer Ratio",
    PolicyPointPerMinuteDesc: "Je ontvangt beleidspunten, elke minuut in het spel",
    YourWilLGaimPolicyPoints: "Je verdient %{amount} beleidspunten in %{time}s",
    PolicyPointDesc: "💡 Te meer actieve beleid, des te hoger de kost per beleid",
    NextOrderIn: "Volgende Bestelling In",
    FillOrder: "Vul Bestelling In",
    RejectOrder: "Overslaan",
    YouHave: "Je hebt %{amount}",
    WholesaleCenterLocked:
        "Je hebt minstens %{required} verschillende goederen nodig om de groothandel te ontgrendelen. Je hebt enkel %{current} goederen",
    OrderFilled: "De bestelling van %{from} is succesvol opgeleverd!",
    PolicyCenter: "Beleidscentrum",
    NewOrder: "Een nieuwe bestelling van %{from} is toegekomen, controleer dit aub in je groothandel",
    Policies: "Beleid",
    PolicyNotEnoughTime: "Je hebt niet genoeg beleidspunten voor dit beleid",
    TimeLeft: "%{time} over",
    WholesaleCenterOrderFaster: "Wereldtentoonstelling",
    WholesaleCenterOrderFasterDesc: "Groothandel ontvangt bestellingen 2x sneller en de bestellingsgrootte is 2x groter",
    PolicyOilWellPowerx2: "Supercharge Oliebronnen",
    PolicyOilWellPowerx2Desc: "Oliebronnen produceren 2x olie and gebruiken 2x energie",
    HalfTransportSpeed: "Vertraag om te sparen",
    HalfTransportSpeedDesc: "transport snelheid is vertraagd met 25% en de brandstof prijs is gereduceerd met 25%",
    RefineryMoreOil: "Meer brandstof, meer problemen",
    RefineryMoreOilDesc: "Olie raffinaderijen produceren 50% meer brandstof en 50% minder plastic",
    StickyInput: "Plakkende Invoer",
    StickyInputDesc:
        "Gebouwen zullen transport van voorgaande bron prefereren, in plaats van te zoeken naar de beste bron elke cyclus (GRATIS BELEID)",
    RefineryMorePlastic: "Meer Plastic Meer Problemen",
    RefineryMorePlasticDesc: "Olie Raffinaderijen produceren 50% minder brandstof and 50% meer plastic",
    FreeOilTransport: "Gratis Olie Transport",
    FreeOilTransportDesc: "Olie transport kost geen brandstof meer maar oliebronnen verbruiken 2x meer energie",
    SuperSteelMill: "Harten van Ijzer",
    SuperSteelMillDesc: "Staalfabrieken verbruiken50% minder kolen en 25% meer ijzer en 25% meer energie",
    AlSemiconductor: "AI geleiders",
    AlSemiconductorDesc: "Geleidersfabrieken gebruiken aluminium in plaats van koper",
    CostSaver: "Kosten bespaarder",
    CostSaverDesc: "Als een gebouw meer invoer kost dan z'n opbrengst, sluit dan de productie",
    CostSaverBuildingDesc:
        "Kosten bespaarder beleid is actief, producxtie zal automatisch aan/uit gezet worden naargelang z'n winstgevendheid",
    CostSaverBuildingWarning: "Kosten bespaarder beleid is actief, je kan de productie niet manueel aanpassen",
    GlassUseCoal: "Zwart glas",
    GlassUseCoalDesc: "Glasfabrieken verbruiken 50% meer kolen en 50% minder silicium",
    AdjacentBonusOnlyOutput: "Aanliggend Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Aanliggend bonus vereist geen invoer meer, maar verbruikt meer energie en is maar 50% effectief",
    IronMine2xOutput: "Zwaar Ijzer",
    IronMine2xOutputDesc: "Ijzermijnen produceren 2x meer ijzer maar ijzer transport kost 2x meer brandstof",
    SolarPanelAlwaysWork: "De Zon Gaat Nooit Onder",
    SolarPanelAlwaysWorkDesc: "Zonnepanelen werken 100% van de tijd, maar produceren maar 60% energie",
    SteelScience: "Kennis Door Staal",
    SteelScienceDesc: "Staalfabrieken gebruiken 2x invoer en produceren extra wetenschap",
    ShowWarehouse: "Ontgrendel Opslagplaats",
    ShowWarehouseDesc:
        "Een opslagplaats is een speciaal gebouw dat enkel goederen transporteert en stockeert en brandstof kan besparen (GRATIS BELEID)",
    WholesaleCenterProducingOnly: "Groothandelspartners",
    WholesaleCenterProducingOnlyDesc:
        "Groothandelsbestellingen bevatten enkel goederen die momenteel geproduceert worden ( Je moet ook het aantal vereiste goederen produceren om de groothandel te ontgrendelen)",
    ShoppingSpree: "Volop Shoppen",
    ShoppingSpreeDesc:
        "Als een goederen opbrengst capaciteit tekort komt, koop de tekort komende aantallen automatisch van het handelscentrum (Als de goederen een auto verkoop op hebben staan, zal het dit negeren)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Volop Shoppen Beleid is geactiveerd, handelscentrum zal automatisch het tekort aan goederen kopen",
    ExtraPolicyPoints: "Politieke Lobbyist",
    ExtraPolicyPointsDesc: "Verhoog beleidspunten productie met 50%",
    CrAlloyUseFe: "Chromijzer",
    CrAlloyUseFeDesc: "Chroom legeringsfabrieken gebruiken geen Lithium maar 2 ijzer ter vervanging",
    DoubleTileModifier: "Kracht Van De Natuur",
    DoubleTileModifierDesc: "Alle tegels modificatoren effect x2 - zowel de positieve als de negatieve",
    TileModifierOutputOnly: "Tegel Modificator Plus",
    TileModifierOutputOnlyDesc:
        "Tegel modificatoren hebben enkel effect op de opbrengst in plaats van invoer en opbrengst, maar zijn maar 50% effectief",
    GasPlantPetrol: "Gas Liquideerder",
    GasPlantPetrolDesc: "Gas energiecentrales gebruiken extra gas om petroleum te produceren",
    BuildingRecycle: "Gebouwen Recycle",
    BuildingRecycleDesc: "Ontvang een volledige terugstorting wanneer je een gebouw verkoopt binnen 1 minuut na constructie",
    CoalPlantFuel: "kolen Liquideerder",
    CoalPlantFuelDesc: "Kolen energiecentrales verbruiken extra kolen om brandstof te produceren",
    Welcome: "Welkom",
    SeeTutorialAgain: "Doe de Tutorial opnieuw",
    ReadSteamGuide: "Officiele Gids op Steam",
    HelpTranslateTheGame: "Help het spel vertalen🌐",
    SkipTutorial: "Tutorial Overslaan",
    NextTutorial: "Volgende",
    Tutorial1:
        "Industry Idle is een <em>goederen management</em> spel waar je fabrieken bouwt🏭, goederen produceert📦 en geld maakt💸.<br><br>Laat ons door wat basic cancepten gaan om je te starten - Dit gaat niet lang duren, pinkie belofte",
    Tutorial2:
        "Alle gebouwen hebben energie nodig⚡, je hebt een <em>wind turbine</em> die energie genereert. Je kan je huidige energie toevoer bekijken in de bovenaan links in de balk.<br><br>Het zal je opvallen dat wind turbines maar <em>80%</em> van de tijd werken. Je kan overwegen andere gebouwen van het type energiecentrale te bouwen, die meer stabiele energie leveren.",
    Tutorial3:
        "Je hebt een hele boel <em>bronnen</em> op de kaart. Om de bronnen te ontmijnen, moeten je mijnen bouwen⛏️ <em>bovenop</em> de bijbehorende bron.<br><br>Bijvoorbeeld, je hebt een <em>oliepomp🛢️</em> die <em>olie</em> op pompt van een oliebron.<br></br>Bronnen zijn onuitputtelijk - geen zorgen dat je zonder zal zitten. Apart van mijnen heb je andere gebouwen die je kan bouwen op lege tegels.",
    Tutorial4:
        "Goederen transport kost brandstof. Op deze kaart, kan je <em>petroleum⛽</em> gebruiken als brandstof. Je hebt een <em>olieraffinaderij</em> die olie transporteert van de oliebron en petroleum produceert.<br><br>De kleine bewegende <em>stipjes</em> geven de realtime beweging van je goederen weer. Je moet je gebouw locaties optimaliseren om reisafstand te minimalizeren.<br><br>Je gebouwen <em>opwaarderen</em> zal hun opbrengst verhogen, maar verhoogt ook hun stroomverbruik en de vereiste invoer.<br><br>Je kan je brandstof type aanpassen in het transport centrum🚦. Vergeet niet je brandstofverbruik voen je brandstof productie te houden, anders zal je productie stilvallen wanneer je zonder brandstof zit.",
    Tutorial5:
        "Om geld te verdienen, moet je je goederen exporteren via het handelscentrum. Om dit te doen, activeer je gewoon de <em>auto verkoop</em> voor deze goederen.<br></br>Je kan ook goederen kopen van het handelscentrum. Onthoud <em>Als je een goed koopt, drijf je de prijs omhoog</em> en als je een goed verkoopt, drijf je de prijs naar beneden.<br><br>De markt is <em>volatiel</em> en de prijs veranderd geregeld.",
    Tutorial6:
        "Om nieuwe gebouwen te bouwen, moet je deze eerst ontgrendelen in het <em>Onderzoeks Laboratorium🧪</em>. Het onderzoekscentrum converteert ook wetenschapspunten naar onderzoekspunten.<br><br>Je wind turbine (en andere energie centrales) produceren een klein aantal wetenscap wanneer ze werken. En je kan een school bouwen🏫 en andere toegewijde gebouwen om je wetenschap later te boosten.<br><br>Nu dat je al de basics hebt geleerd, start je met je economy op te bouwen.! Hier is wat <em>cash💸</em> en <em>petroleum⛽</em> om je een goede start te geven.",
    WelcomePlay: "Afspelen",
    WelcomePlayMuted: "Afspelen (🔇Muziek)",
    Changelog: "Changelog",
    ChangelogGotIt: "Ik snap het",
    Chat: "Chat",
    Send: "Verzenden",
    Import: "Importeren",
    Export: "Exporteren",
    SteamCloudBackup: "Steam Cloud Backup",
    LastBackupAt: "Laatste Backup",
    RestoreFromBackup: "Herstellen van Backup",
    RestoreFromBackupFail: "Backup herstel gefaald uit de Steam Cloud. Ben je zeker dat er een backup is?",
    RestoreFromBackupTitle: "Ben je zeker?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChatMessages: "Chat Berichten",
    ChatPlaceholder: "Typ je bericht: max 100 karakters",
    ChangeName: "Aanpassen",
    SaveName: "Opslaan",
    NameValidationRule: "Je naam mag enkel letters en nummers bevatten en moet tussen 5 en 15 karakters lang zijn",
    NameValidationRuleProfanity: "Je naam mag geen godslastering bevatten",
    ChatMessageRateLimit: "Je mag maar om de 10 seconden een bericht versturen",
    NameSaved: "Je naam is succesvol aangepast",
    NoMessages: "Geen nieuwe berichten",
    Leaderboard: "Leiderbord",
    LeaderboardDesc: "Het leiderbord score is al het Zwitsers geld dat je ooit verdient hebt",
    Name: "Naam",
    Rank: "Rang",
    Tips1: "Aandelen beoordelingen hebben 5 niveau's: Kopen, Over Presteren, Bijhouden, Onder Presteren en Verkopen",
    Tips2:
        "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Brandstof kosten voor goederen transport worden bepaald door afstand en hoeveelheid goederen",
    Tips4: "Gebouwen zullen goederen enkel transporteren als het aantal gevonden op de kaart de invoer capaciteit overschrijdt",
    Tips5: "Gebouwen zullen goederen enkel transporteren van het handelscentrum als de automatisch verkoop voor dit goed is afgezet",
    Tips6: "Je kan de brandstofkosten voor goederen bekijken onder de bijbehorende invoer capaciteits sectie",
    Tips7: "Als je een goed aankoopt, zal je de prijs opdrijven. Als je een goed verkoopt zal je de prijs drukken",
    Tips8: "Je kan de grafiek voor een goed's aantal en het aanpassen over tijd in het Statistieken Bureau",
    Tips9: "Onderzoekspunten voor een gebouw worden bepaald door de marktprijs en door zijn invoersgoederen",
    Tips10: "Verschillende goederen hebben een verschillende prijs in de markt - wees altijd bereid voor de volatiliteit van de markt",
    Tips11: "Het is een goed idee om altijd je energie en brandstof voorraad te controleren vooraleer je je productie gaat uitbreiden",
    FPS30: "Energie Besparing",
    OfflineModeDesc:
        "Kan niet met de server connecteren: Offline verdiensten worden niet gegenereerd. Gelieve je internet connectie na te kijken",
    OptOut: "Deactiveer",
    OptIn: "Reset en activeer",
    LeaderboardOptOut: "Leiderbord Deactiveren",
    LeaderboardOptOutDesc:
        "Dit zal niet langer leiderbord scores versturen. LET OP: als je het leiderbord later wil activeren, moet je data een reset ondergaan",
    LeaderboardOptIn: "Reset en activeer Leiderbord",
    LeaderboardOptInDesc: "Je data moet een RESET ondergaan voor je het leiderbord terug kan activeren, ben je zeker?",
    RewardAdsFailed: "Beloningsvideo is niet beëindigt",
    RewardAdsNotAvailable: "Beloningsvideo niet beschikbaar (momenteel enkel iOS/Android ondersteund)",
    OfflineEarningDoubleSuccess: "Je hebt  je offline verdiensten verdubbelt",
    FPS30Desc:
        "De energie besparingsmode activeren zal het spel doen draaien op 30 FPS in plaats van 60FPS. Dit laat je batterij langer meegaan",
    HighlightAll: 'Markeer "%{type}"',
    HighlightInput: "🔍 Markeer %{type} Invoer",
    HighlightOutput: "🔍 Markeer %{type} Opbrengst",
    TotalInput: "Totale Invoer Capaciteit",
    TotalOutput: "Totale Opbrengst Capaciteit",
    RunOutIn: "Uit in %{time}",
    FuelRunOutWarning: "💡 Je brandstof consumptie overtreft productie. Wanneer brandstof op is, valt je transport stil",
    InAmount: "In: %{number}",
    OutAmount: "Uit: %{number}",
    SwissBank: "Zwitserse Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Als je in een nieuwe stad start, ontvang je %{money} 💵",
    RestorePurchases: "Aankopen herstellen",
    RestorePurchasesSuccess: "Je aankopen zijn hersteld",
    RestorePurchasesFailed: "Je aankopen zijn niet hersteld",
    ExpansionPacks: "Uitbreidings Pakketten",
    ExpansionPack1: "Uitbreidings Pakket 1",
    ExpansionPack1Owned: "Uitbreidings Pakket 1",
    RequireExpansionPack1: "Uitbreidings Pakket 1",
    RequireExpansionPack1Desc: "Dit is enkel beschikbaar voor Uitbreidings Pakket 1",
    RequireAnyExpansionPack: "Uitbreidings Pakket Exclusief",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Verberg toegewezen advertenties",
    HideRewardAdDesc:
        "Alle in het spel zijnde advertenties zijn optionele belonings advertenties. Dit verbergt alle beloningsopties in het spel.",
    HideDiscordBanner: "Verberg Discord Banier",
    HideDiscordBannerDesc: "Verberg Discord en de winkelbanier in het hoofdkwartier",
    HideChat: "Verberg Chat Bericht",
    HideChatDesc: "verberg de berichten van de onderste toolbar",
    SortedByDeficit: "Gesorteerd op tekort",
    PurchaseFailed: "De aankoop is niet doorgegaan",
    PurchaseSteamContinue: "Beëindig je aankoop aub op Steam",
    PurchaseSuccess: "Je aankoop is afgerond, bedankt voor je steun",
    PrestigeCurrency: "Zwitsers Geld 💵",
    RestartDesc: "💡 Wil je enkel herstarten? Je kan op start tikken in Start In Een Nieuwe Stad en je huidige stad kiezen",
    PrestigeGoBack: "Ga Terug",
    PermanentUpgradeDesc: "Deze opwaardering wordt overgedragen naar de volgende stad",
    ProductionMultiplier: "Productie Multiplicator",
    ProductionMultiplierDesc:
        "Een boost aan al je gebouwen productie capaciteiten (inclusief mijnen, fabrieken, energie centrales, wetenschap en cultuur gebouwen)",
    FuelCostDiscount: "Brandstof Kosten Korting",
    FuelCostDiscountDesc: "Geeft een korting op de brandstof kosten wanneer je goederen transporteert",
    AutoSellCapacityMultiplier: "Auto Verkoopscapaciteit Multiplicator",
    AutoSellCapacityMultiplierDesc:
        "Een multiplicator die toegepast wordt op je automatische verkoopscapaciteit, ongacht de huidige capaciteit",
    BuildingPermitCostDivider: "Gebouwtoelatings Kosten Deler",
    BuildingPermitCostDividerDesc: "Deel de gebouw toelating door deze factor",
    ExtraAdjacentBonus: "Extra Aanliggende Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capaciteit voor elke aanliggend werkend gebouw van hetzelfde typoe",
    OfflineEarningMultiplier: "Offline Verdienste Multiplicator",
    OfflineEarningMultiplierDesc: "Een multiplicator die slaat op je offline verdiensten",
    PrestigeAlertTitle: "Ben je zeker?",
    PrestigeAlertContent:
        "Je bedrijf zal geliquideert worden. Je ontvangt %{amount} Zwitsers geld en start een nieuw bedrijf in %{city}",
    PrestigeCurrencyDesc:
        "Dit is het geld in je geheime Zwitserse bankrekening, Je kan dit meedragen als je in een nieuwe stad start",
    Prestige: "Cash In",
    Cancel: "Annuleren",
    SaveFileCorrupted: "Opslagbestand Gecorrupteerd",
    CheatDetected: "Je oude opslag bestand heeft de server validatie niet doorstaan en kan niet gelezen worden. Je zal starten met een nieuwe opslag bestand",
    LoadGameError: "Spel laden gefaald",
    LoadGameErrorMessage: "Foutmelding: %{message}",
    LoadGameErrorDesc: "Controleer aub je internet connectie. Als een probleem aanhoud, gelieve support te contacteren",
    ExpansionPackIncompatible:
        "Je bent een save file aan 't importeren met uitbreidingspakketten, maar je spel heeft niet de nodige uitbreindingspakketten",
    SaveFileMigrated: "Een nieuwe Era: De Beta Is Hier",
    SaveFileMigratedDesc:
        "Bedankt om mee te testen in de alpha. Je oude map is niet compatibel, maar we hebben je data gemigreerd en je een bonus gegeven",
    ClaimSwissMoney: "%{amount} Zwitsers geld opeisen 💵",
    SaveFileMigratedFinePrint:
        "Je markt Cap is geconverteerd naar Zwitsers geld en je niet uitgegeven Zwitsers geld wordt mee overgebracht. Je zal 50% bonus Zwitsers geld ontvangen om mee te speltesten in de alpha. Max Zwitsers geld dat mee overgebracht kan worden is gelimiteerd tot 200",
    CashIn: "Cash In",
    CurrentCity: "Huidige Stad",
    CashInDesc:
        "Je zal dit bedrag in je Zwitserse bankrekening ontvangen als je in een nieuwe stad start. Het is gebaseerd op je bedrijfs markt cap en het moet %{amount} bereiken vooraleer je Zwitsers geld kan verdienen",
    MoveToNewMap: "Start In Een Nieuwe Stad",
    CityName: "Stad",
    CitySize: "Map Grootte",
    GridType: "Rooster Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "Stadsbonus",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Vierkant",
    MapHexGrid: "Hex",
    Translator: "Vertaler",
    TranslatorName: "Maccie",
    Language: "Taal",
    ThisLanguage: "Nederlands",
    Stockholm: "Stockholm",
    StockholmBonus:
        "<li>Gratis niveau 4 wind turbines x1</li><li>gratis niveau 4 oliebronnen x1</li><li>gratis niveau 2 oil raffinaderijen x1</li><li>Papiermolens zijn ontgrendelt</li><li>Houthakkers kampen hebben 2x uitvoer</li>",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Staalfabrieken hebben 2x capaciteit</li><li>Roestvrij Staalfabrieken hebben 2x capaciteit</li><li>Gratis ijzertransport</li><li>Staal transport kost 50% minder brandstof</li><li>Start met 2x auto verkoop capaciteit</li><li>Geen tegel modificators</li>",
    Oslo: "Oslo",
    OsloBonus:
        "<li>Olie raffinaderijen hebben 2x capaciteit</li><li>Gas producerende fabrieken hebben 2x capaciteit</li><li>Brandstof energiecentrales hebben 2x capaciteit</li><li>Staalfabrieken gebruiken natuurlijk gas instead in de plaats van kolen</li><li>gratis olie transport</li>",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Uranium mijnen hebben 2x uitvoer</li><li>Uranium verrijkingscentrales hebben 2x capaciteit</li><li>Uranium transport kost 50% minder brandstof</li><li>Gratis wapen transport</li><li>Missile fabrieken gebruiken verrijkt uranium in de plaats van titanium en uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin fabrieken zijn ontgrendelt</li><li>Halfgeleiderfabrieken hebben 2x productiviteit</li><li>Scheepswerven hebben 2x capaciteit</li><li>Autofabrieken hebben 2x capaciteit</li><li>Li-ion batterijfabrieken zijn ontgrendelt</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Titanium mijnen hebben 2x opbrengst</li><li>Uranium verrijkingscentrales hebben 2x productiviteit</li><li>Straalmotorenfabrieken hebben 2x capaciteit</li><li>Vliegtuigfabrieken hebben 2x productiviteit</li><li>Raketfabrieken gebruiken uranium in plaats van verrijkt uranium</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums zijn ontgrendelt</li><li>Colosseums hebben 2x productiviteit</li><li>Start met een niveau 5 beleidscentrum</li><li>Opera huizen hebben 2x capaciteit</li><li>Opnamestudios produceren ook cultuur</li>",
    Detroit: "Detroit",
    DetroitBonus:
        "<li>Motor fabrieken zijn ontgrendelt</li><li>Motor fabrieken hebben 2x productiviteit</li><li>Auto fabrieken hebben 2x capaciteit</li><li>Auto fabrieken hebben geen batterijen nodig</li><li>Trein fabrieken hebben 2x capaciteit</li>",
    Boston: "Boston",
    BostonBonus:
        "<li>Start met niveau 5 Onderzoeks Laboratorium</li><li>Hogescholen zijn ontgrendelt</li><li>hogescholen hebben 2x capaciteit</li><li>Scholen benne 2x capaciteit</li><li>Universiteiten hebben 2x productiviteit</li>",
    HideNotProducing: "Verberg goederen die niet geproduceerd worden",
    SortByStorage: "Opslag",
    SortByProduction: "Productie",
    SortByName: "Naam",
    BuildingInProgressCannotPrestige:
        "Je hebt gebouwenconstructie onderweg; je kan niet starten in een nieuwe stad totdat dit afgewerkt is",
    PlayerTrade: "Speler Handel",
    AddTradeFail: "Handel toevoegen gefaald",
    AddTradeValidationFail: "Handelsbedrag en prijs moeten groter zijn dan 0",
    AddTradeExceedMaximumTrade:
        "Je kan maximum %{number} actieve handels hebben, Eis ze op of annuleer ze eerst",
    AddTradeSuccess: "Je handel is succesvol toegevoegd",
    LoadTradeFail: "Spelers handel laden is gefaald, probeer later opnieuw",
    ClaimTradeFail: "Handel opeisen is gefaald, probeer later opnieuw",
    ClaimTradeSuccess: "Jou handel is succesvol opgeeist: $%{cash} is toegevoegd aan je account",
    CancelTradeSuccess: "Jou handel is succesvol geannuleerd",
    CancelTradeFail: "Handel annuleren is gefaald, probeer later opnieuw",
    AcceptTradeSuccess: "Deze handel is geaccepteert door jou: %{resource} is toegevoegd aan je handelscentrum",
    AcceptTradeFail: "Handel accepteren is gefaald, probeer later opnieuw",
    PlayerTradeBanner: "Handel goederen met andere spelers",
    PlayerTradeResource: "Goederen",
    PlayerTradeAmount: "Aantal",
    PlayerTradePrice: "Prijs $",
    PlayerTradeValue: "Waarde $",
    PlayerTradeWaiting: "Wachten...",
    UseTradeCenterPrice: "Gebruik handelscentruml Prijs",
    AddTrade: "Handel toevoegen",
    ActiveTrades: "Actieve handelingen",
    AcceptTrade: "Accepteer",
    CancelTrade: "Annuleer",
    ClaimTrade: "Eis op",
    RefreshTrade: "Ververs",
    PasteYourSave: "Plak uw opslag data aub",
    FailedToImportSave: "opgeslagen data importeren gefaald",
    FailedToImportSaveDesc: "je opgeslagen bestand is incompatibel or gecorrumpteerd: %{error}",
    SaveCopiedToClipboard: "Je opgeslagen data is gekopieerd naar je klembord",
};
