export const PL = {
    Translator: "Translator",
    TranslatorName: "Tutaj wpisz swoje imię!",
    Language: "Język",
    ThisLanguage: "Polski",
    OK: "OK",
    SteelMill: "Huta stali",
    StainlessSteelPlant: "Fabryka stali nierdzewnej",
    CircuitFoundry: "Odlewnia obwodów",
    IntegratedCircuit: "Układ scalony",
    OilWell: "Szyb naftowy",
    Wood: "Drewno",
    LoggingCamp: "Obóz wyrębu drzew",
    LumberMill: "Tartak",
    Lumber: "Kłody",
    Paper: "Papier",
    PaperMill: "Papiernia",
    Book: "Książki",
    BookPublisher: "Wydawca książek",
    OilRefinery: "Rafineria ropy naftowej",
    Sell: "Sprzedaj",
    Upgrade: "Ulepsz",
    Build: "Wybuduj",
    Buildings: "Budynki",
    Iron: "Żelazo",
    FuelType: "Wybierz paliwo",
    FuelCost: "Koszt paliwa",
    FuelEconomy: "Ekonomia paliwowa",
    FuelInStorage: "%{fuel} na stanie",
    Plastic: "Plastik",
    Petrol: "Benzyna",
    Buy: "Kup",
    NoLiquidity: "Brak płynności",
    NoLiquidityTurnOffAutoSell:
        "Nie ma wystarczającej ilości produktów na rynku dla %{res}, automatyczna sprzedaż została wyłączona",
    Multiplier: "Mnożnik",
    MultiplierDesc: "Każde 10 poziomów, zwieksza mnożnik o 1",
    SellBuilding: "Sprzedaj budynek",
    PowerGrid: "Sieć energetyczna",
    TradeAmount: "Ilość towaru",
    SortBy: "Sortuj po",
    SortByPrice: "Cena",
    SortByAmount: "Ilość",
    NotEnoughResources: "Niewystarczająca ilość produktów, by wykonać tę akcję",
    Transportation: "Transport",
    Cash: "Gotówka",
    Aluminum: "Aluminium",
    ResearchPoint: "Punkt Badawczy",
    Unlock: "Odblokuj",
    BuildingUnlocked: "%{building} został odblokowany",
    Science: "Nauka",
    ScienceFromPowerDesc: "Elektrownie wytwarzają niewielką ilość Nauki podczas wytwarzania energii",
    Culture: "Kultura",
    School: "Szkoła",
    University: "Uniwersytet",
    Polytechnic: "Politechnika",
    Colosseum: "Koloseum",
    WindTurbine: "Turbina wiatrowa",
    Engine: "Silnik",
    EngineFactory: "Fabryka silników",
    CameraFactory: "Fabryka aparatów",
    Camera: "Aparat fotograficzny",
    Gun: "Pistolet",
    GunFactory: "Fabryka broni",
    Aircraft: "Samolot",
    AircraftFactory: "Fabryka samolotów",
    Zeppelin: "Sterowiec",
    ZeppelinFactory: "Fabryka sterowców",
    Tank: "Czołg",
    TankFactory: "Fabryka czołgów",
    CoalPowerPlant: "Elektrownia węglowa",
    PetrolPowerPlant: "Elektrownia benzynowa",
    Copper: "Miedź",
    Gas: "Gaz ziemny",
    GasPump: "Pompa gazu ziemnego",
    GasPowerPlant: "Elektrownia gazowa",
    Missile: "Pocisk rakietowy",
    MissileFactory: "Fabryka pocisków rakietowych",
    Rocket: "Rakieta",
    RocketFactory: "Fabryka rakiet",
    BuildingPermit: "Pozwolenie na budowę",
    BuildingPermitDesc:
        "Masz pozwolenia na budowę %{amount} budynków, zbudowałeś już %{amountBuilt} i pozostało Ci %{amountLeft}",
    BuildingLocked: "Budynek nie jest jeszcze dostępny, musisz go najpierw odblokować w Laboratorium Badawczym",
    MaxBuilders: "Limit budujących",
    MaxBuildersDesc: "Liczba budynków, które możesz zbudować jednocześnie",
    Silicon: "Krzem",
    AluminumMine: "Kopalnia aluminium",
    CopperMine: "Kopalnia miedzi",
    SiliconMine: "Kopalnia Krzemu",
    IronMine: "Kopalnia żelaza",
    CoalMine: "Kopalnia Węgla",
    Headquarter: "Centrala",
    ResearchLab: "Laboratorium Badawcze",
    TradeCenter: "Rynek",
    Resources: "Surowce",
    NotEnoughCash: "Niewystarczająca ilość gotówki do wykonanie tej akcji",
    NotEnoughSwissMoney: "Niewystarczająca ilość Swiss Money do wykonanie tej akcji",
    BuildingNotEnoughFuel: "💡 Niewystarczająca ilość %{fuel}",
    AutoSell: "Automatyczna sprzedaż",
    Change: "Zmień",
    StatisticsBureau: "Biuro Statystyczne",
    LogisticsDepartment: "Dział logistyki",
    From: "Z",
    Top20FuelCost: "Top 20 kosztów paliwa",
    To: "Do",
    TransportTime: "Czas transportu",
    Warehouse: "Magazyn",
    TradeWarehouse: "Główny magazyn towarowy",
    Coal: "Węgiel",
    Video: "Wideo",
    ClothingFactory: "Fabryka odzieży",
    Clothes: "Odzież",
    Fashion: "Moda",
    FashionFactory: "Fabryka mody",
    VideoFarm: "Video blogi",
    SantaFactory: "Fabryka Świętych Mikołajów",
    Santa: "Świety Mikołaj",
    Car: "Samochód",
    CarFactory: "Fabryka Samochodów",
    Ship: "Statek",
    SolarPanel: "Panel słoneczny",
    SolarPanelDesc: "💡 Panele słoneczne działają tylko 5 sekund na każde 10 sekund - wszystkie cykle są wyrównane",
    WindTurbineDesc: "💡 Turbiny wiatrowe działają tylko 8 sekund na każde 10 sekund - cykle nie są równane",
    Movie: "Film",
    MovieStudio: "Studio filmowe",
    Sitcom: "Sitcom",
    TVStudio: "Studio telewizyjne",
    PC: "Komputer",
    GameStudio: "Developer gier",
    Game: "Gry",
    ComputerFactory: "Fabryka komputerów",
    Shipyard: "Stocznia",
    PowerUsage: "Zużycie energii",
    PowerSupply: "Zasilanie",
    Level: "Poziom",
    Power: "Moc/Zasilanie",
    CentralBank: "Bank centralny",
    ResourceInput: "Pobiera",
    ResourceOutput: "Produkuje",
    ResourceStorage: "Magazyn",
    ResourceChange: "Zmiana",
    ResourceInOutDesc:
        "💡 Stuknij w liczby Pobiera/Produkuje powyżej, aby podświetlić odpowiednie budynki produkujące i pobierajace.",
    MarketUpdateIn: "Aktualizacja rynku za %{time}",
    Semiconductor: "Półprzewodnik",
    SemiconductorFactory: "Fabryka półprzewodników",
    Steel: "Stal",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Farma Bitcoina",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Farma Dogecoina",
    Guitar: "Gitara",
    GuitarFactory: "Fabryka Gitar",
    Drum: "Perkusja",
    DrumFactory: "Fabryka Perkusji",
    RecordingStudio: "Studio nagrań",
    OperaHouse: "Opera",
    CoalGasificationPlant: "Zakład zgazowania węgla",
    GasProcessingPlant: "Zakład przetwórstwa gazu",
    Music: "Muzyka",
    Glass: "Szkło",
    PhoneFactory: "Fabryka telefonów komórkowych",
    Phone: "Komórka",
    GlassFactory: "Fabryka szkła",
    Oil: "Ropa",
    Chromium: "Chrom",
    ChromiumMine: "Kopalnia chromu",
    Uranium: "Uran",
    EnrichedUranium: "Wzbogacony uran",
    NuclearPowerPlant: "Elektrownia jądrowa",
    UraniumEnrichmentPlant: "Zakład wzbogacania uranu",
    UraniumMine: "Kopalnia uranu",
    Titanium: "Tytan",
    TitaniumMine: "Kopalnia tytanu",
    TitaniumAlloyPlant: "Fabryka stopów tytanu",
    ChromiumAlloyPlant: "Fabryka stopów chromu",
    Input: "Potrzebuje",
    PanelPosition: "Pozycja wyświetlacza",
    PanelPositionDesc: "Pokaż panel boczny z lewej, prawej lub automatycznie (zależne od zaznaczonego pola)",
    InputCapacity: "Pojemność wejściowa",
    Output: "Produkuje",
    OutputCapacity: "Pojemność wyjściowa",
    ResourceDeposit: "Depozyt zasobów",
    AdjacentBonus: "Premia za sąsiedztwo",
    AdjacentBonusDesc:
        "Otrzymujesz %{bonus}% dodatkową premię za każdy sąsiadujacy i pracujacy budynek tego samego typu",
    ConsiderIncreaseProduction: "💡 Rozważ zwiekszenie produkcji %{resource} ",
    AlwaysTransportInput: "Nadwyżka magazynowa",
    AlwaysTransportInputTradeCenter: "Zawsze eksportuj",
    AlwaysTransportInputTradeCenterDesc:
        "Zawsze transportuj surowce do Rynku, nawet jeżeli autosprzedaż nie jest katywna dla danego surowca",
    AlwaysTransportInputDesc:
        "Zawsze transportuj surowce produkcyjne, nawet jeżeli spełnione zostały minimalne wymogi produkcji",
    ProductionCycleLength: "Cykl produkcyjny",
    ProductionCycleLengthDesc:
        "Długość cyklu produkcji mierzona jest w sekundach. Wydłużenie cyklu zwiększy zapotrzeobwanie surowców i produkcje, tym samym redukując priorytet dostarczania surowców",
    MaxInputDistance: "Maksymalna odległość zaopatrzenia",
    MaxInputDistanceDesc:
        "Maksymalna odległość z jakiej budynek jest w stanie pobierać surowce do produkcji, liczone w polach.",
    AutoSellCapacity: "Przepustowość automatycznej sprzedaży",
    AutoSellCapacityDesc: "Maksymalna ilość produktu jaki może być sprzedawany automatycznie w sekundach/ilość",
    CurrentAutoSellCapacityMultiplier: "Bieżacy mnożnik: x%{n}",
    AutoSellConcurrency: "Limit rodzajów sprzedawanych towarów",
    AutoSellConcurrencyDesc: "Maksymalna liczba rodzajów produktów jakie można sprzedawać w tym samamy czasie",
    MaxAutoSellConcurrencyReached:
        "Osiągnąłeś maksymalna liczbę rodzajów sprzedawanych produktów, zaprzestań sprzedawania innego produktu by zacząć sprzedawać wybrany.",
    WallStreet: "Giełda Wall Street",
    MarketCap: "Kapitalizacja rynku",
    MarketCapDesc: "Total market capitalization (i.e. market value) of your corporation",
    BuildingValuation: "Wartość twoich budynków",
    BuildingValuationDesc: "Łączna wartość twoich budynków, włącznie ze zgodami na budowe i ulepszeniami",
    ResourcesValuation: "Wartość surowców",
    ResourcesValuationDesc: "Łączna wartość surowców w twoim ekwipunku",
    Battery: "Bateria",
    BatteryFactory: "Fabryka baterii",
    RatingBuy: "Kup",
    RatingSell: "Sprzedaj",
    SwissShop: "Swiss Shop",
    RatingHold: "Wstrzymaj się",
    RatingOutperform: "Wyśmienicie",
    RatingUnderperform: "Poniżej normy",
    StockRating: "Wartość akcji",
    JetEngine: "Silnik odrzutowy",
    Helicopter: "Helikopter",
    Lithium: "Lit",
    LithiumMine: "Kopalnia litu",
    LiionBatteryFactory: "Fabryka baterii litowych",
    HelicopterFactory: "Fabryka helikopterów",
    Satellite: "Satelita",
    ToyFactory: "Fabryka zabawek",
    Toy: "Zabawka",
    SpaceStation: "Stacja kosmiczna",
    SpaceStationFactory: "Fabryka stacji kosmicznych",
    OperatingSystem: "System operacyjny",
    OperatingSystemCompany: "Developer systemów operacyjnych",
    LinuxDistribution: "Dystrybucja systemu Linux",
    Internet: "Internet",
    WebBrowser: "Przeglądarka internetowa",
    Console: "Konsola",
    ConsoleFactory: "Fabryka konsol",
    Train: "Pociąg",
    TrainFactory: "Fabryka pociągów",
    ShoeFactory: "Fabryka butów",
    Shoes: "Buty",
    ArtilleryFactory: "Fabryka dział",
    Artillery: "Działo",
    SubmarineFactory: "Fabryka łodzi podwodnych",
    Submarine: "Łódź podwodna",
    Spaceship: "Statek kosmiczny",
    RobotFactory: "Fabryka robotów",
    Robot: "Robot",
    SpaceshipFactory: "Fabryka statków kosmicznych",
    SatelliteFactory: "Fabryka satelit",
    JetEngineFactory: "fabryka silników odrzutowych",
    StockRatingDesc:
        "Ocena wartości akcji od analityków z Wall Street, która wpływa na kapitalizację rynkową i jest aktualizowana wraz z rynkiem",
    OfflineEarning: "Dochód offline",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Czas dochodu offline",
    OfflineEarningTimeDesc: "Zarabiasz w trybie offline do tego progu",
    BuyPermit: "Kup pozwolenie",
    Settings: "Ustawienia",
    Sound: "Efekt dźwiękowy",
    SoundDesc: "Włącz efekt dźwiękowy, taki jak dźwięk kliknięcia lub dźwięk błędu",
    AutoHighlight: "Automatyczne podświetlanie",
    AutoHighlightDesc: "Automatycznie podświetlaj budynki tego samego typu po wybraniu budynku",
    MusicDesc: "Włącz muzykę: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Ikony",
    MisplacedBuilding: "⛔ Ten %{building} nie jest umieszczany na odpowiednim depozycie zasobów",
    HighlightBuildings: "Budynki podświetlone",
    HighlightTurnedOff: "...wyłączone budynki",
    HighlightStockpileModeOn: "...z włączonym trybem magazynowania zasobów",
    HighlightProductionCycleNotDefault: "...z cyklem produkcyjnym > 1",
    HighlightMaxInputDistanceNotDefault: "...z maksymalnym zasięgiem poboru surowców < ∞",
    HighlightNotMakingProfit: "...które nie zarabiają",
    NBuildingsAreHighlighted: "%{n} budynków zostało podświetlonych",
    TurnOffProduction: "Wyłącz",
    TurnOffProductionDesc: "Wyłącz produkcję budynku. Budynek nie będzie już transportował surowców i zużywał energii",
    ApplyToAll: "Zastosuj dla wszystkich %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Nielimitowany",
    Transport: "Transport",
    TileModifier: "Modyfikator pól",
    ShowAllModifiers: "Pokaż wszystkie modyfikatory",
    HideAllModifiers: "Ukryj wszystkie modyfikatory",
    NumberOfBuildings: "Liczba budynków które posiadasz",
    ShowContent: "Pokaż obiekt",
    HideContent: "ukryj obiekt",
    BuyExpansionPack: "Kup za %{price}",
    Cities: "Miasta",
    InputStrategy: "Strategia poboru materiałów",
    InputStrategyClose: "Bliskie",
    InputStrategyCloseDesc: "Wybieraj magazyny znajdujące sie najbliżej i posiadające wystarczającą ilość surowców",
    InputStrategyFar: "Najdalsze",
    InputStrategyFarDesc: "Wybieraj magazyny znajdujące sie najdalej i posiadające wystarczającą ilość surowców",
    InputStrategyAmount: "Ilość",
    InputStrategyAmountDesc: "Wybieraj magazyny posiadające największość ilość zasobów, niezależnie od dystansu",
    FuelCostSave: "Oszczędność kosztów transportu",
    FuelCostSaveDescV2:
        "Warehouses save a certain percentage of fuel for transporting resources compared to other buildings, the higher the level, the more the save",
    SoftwareCompany: "Hurtownia oprogramowania",
    Software: "Oprogramowanie",
    ScreenFactory: "Fabryka wyświetlaczy",
    Screen: "Wyświetlacz",
    JoinDiscord: "Dołącz do naszego serwera Discord, aby otrzymywać najnowsze aktualizacje, wskazówki i dyskusje",
    ClaimOfflineEarning: "Odbierz zarobki offline",
    OfflineTime: "Czas bycia nieobecnym",
    Minutes: "%{time}min",
    MaxUpgrade: "Maksymalny poziom ulepszenia",
    MaxUpgradeDesc: "Osiągnołeś maksymalny poziom ulepszeń",
    ClaimAmount: "Pieniądze +%{amount}",
    EffectiveTime: "Efektywny czas",
    EffectiveTimeDesc: "Twój efektywny czas zarabiania offline jest ograniczony do %{time}min.",
    BuildSearchPlaceholder: "Wpisz budynek lub zasób do przeszukania",
    MineOverlayWarning: "%{building} nie podlega modyfikatorowi pól",
    WholesaleCenter: "Centrum hurtowe",
    OrderFrom: "Zamów z %{name}",
    ExpireIn: "Wygasa za",
    Reward: "Nagroda",
    PerSecond: "%{time}/s",
    PolicyPoint: "Punkty patentowe",
    PolicyPointDesc: "💡 Im więcej aktywnych patentów, tym więcej punktów patentowych zostaje zużytych",
    NextOrderIn: "Następne zamówienie w",
    FillOrder: "Wypełnij zamówienie",
    RejectOrder: "Zrezygnuj",
    WholesaleCenterLocked:
        "You need at least %{required} different resources to unlock Wholesale Center. You only have %{current} resources",
    OrderFilled: "The order from %{from} has been successfully filled!",
    PolicyCenter: "Policy Center",
    NewOrder: "A new order from %{from} has arrived, please check in Wholesale Center",
    Policies: "Policies",
    PolicyNotEnoughTime: "You don't have enough policy points for this policy",
    WholesaleCenterOrderFasterDesc: "Wholesale Center receives orders 2x faster and the order size is 2x bigger",
    PolicyOilWellPowerx2: "Supercharge Oil Well",
    PolicyOilWellPowerx2Desc: "Oil wells produce 2x oil and use 2x power",
    HalfTransportSpeed: "Slow Down To Save Up",
    HalfTransportSpeedDesc: "Transportation speed is slowed down by 25% and fuel cost is reduced by 25%",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "Oil Refineries produce 50% more petrol and 50% less plastic",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Buildings will prefer to transport from previous source, instead of searching for the best source every cycle (FREE POLICY)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "Oil Refineries produce 50% less petrol and 50% more plastic",
    FreeOilTransportDesc: "Oil transport doesn't cost fuel but oil wells use 2x power",
    SuperSteelMill: "Hearts of Iron",
    SuperSteelMillDesc: "Steel mills use 50% less coal and 25% more iron and 25% more power",
    AlSemiconductor: "Al Circuit",
    AlSemiconductorDesc: "Circuit foundries use aluminum instead of copper",
    CostSaver: "Cost Saver",
    CostSaverDesc: "If a building's input cost more than its output, shut down the production",
    CostSaverBuildingDesc:
        "Cost Saver policy is active, production will turn on/off automatically based on its profitability",
    CostSaverBuildingWarning: "Cost Saver policy is active, you cannot manually change production",
    GlassUseCoal: "Black Glass",
    GlassUseCoalDesc: "Glass factories use 50% more coal and 50% less silicon",
    AdjacentBonusOnlyOutput: "Adjacent Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Adjacent bonus does not require more input but uses more power and is only 50% as effective",
    IronMine2xOutput: "Heavy Iron",
    IronMine2xOutputDesc: "Iron mines produce 2x iron but iron transport costs 2x fuel",
    SolarPanelAlwaysWork: "The Sun Never Sets",
    SolarPanelAlwaysWorkDesc: "Solar panels work 100% of the time but produce 60% less power",
    SteelScience: "Knowledge Through Steel",
    SteelScienceDesc: "Steel mills use 2x input and produce extra science",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "If a resource's output capacity falls short, buy the shortage amount from Trade Center automatically (If the resource has auto sell on, it will be ignored)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree policy is on, Trade Center will automatically buy resources in shortage",
    ExtraPolicyPoints: "Political Lobbyist",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromium alloy plants do not use Lithium but use 2x Iron instead",
    DoubleTileModifier: "Nature's Power",
    TileModifierOutputOnly: "Tile Modifier Plus",
    GasPlantPetrol: "Gas Liquidizer",
    GasPlantPetrolDesc: "Gas power plants use extra gas to produce petrol",
    CoalPlantFuel: "Coal Liquidizer",
    CoalPlantFuelDesc: "Coal power plants use extra coal to produce petrol",
    Welcome: "Welcome",
    SeeTutorialAgain: "Redo Tutorial",
    HelpTranslateTheGame: "Help Translate the Game🌐",
    NextTutorial: "Next",
    Tutorial1:
        "Industry Idle is a <em>resource management</em> game where you build factories🏭, produce goods📦 and make money💸.<br><br>Let's go through some basic concepts to get you started - it won't take long, I pinky promise.",
    Tutorial2:
        "All buildings need power⚡, you have a <em>wind turbine</em> that generates power. You can see your current power supply on the left side of the top bar.<br><br>You might have noticed that wind turbines only work <em>80%</em> of the time. You can consider building other types of power plants that generate stable power.",
    Tutorial3:
        "You have a lot of <em>resource deposits</em> on the map. To extract resources, you have to build mines⛏️ <em>on top of</em> the corresponding deposit.<br><br>For example, you have an <em>oil well🛢️</em> that extracts <em>oil</em> from an oil deposit.<br></br>Resource deposits are unlimited - no need to worry about them running out. Apart from mines, other buildings can be built on any empty tile.",
    Tutorial5:
        "To make money, you need to export your resources via the trade center. To do this, simply turn on <em>auto sell</em> for that resource.<br></br>You can also buy resources from the trade center as well. Remember <em>if you buy a resource, you will drive up the price</em> and if you sell a resource, you will drive down the price.<br><br>The market is <em>volatile</em> and the price📈 changes regularly.",
    Tutorial6:
        "To build new buildings, you need to unlock it first in the <em>research lab🧪</em>. The research lab also converts science to research points.<br><br>Your wind turbine (and other power plants) produces a small amount of science when running. And you can build school🏫 and other dedicated buildings to boost science later.<br><br>Now you have learned all the basics, start to build up your economy! Here are some <em>cash💸</em> and <em>petrol⛽</em> to give you a jump start.",
    WelcomePlay: "Play",
    WelcomePlayMuted: "Play (🔇Music)",
    Chat: "Chat",
    Import: "Import",
    Export: "Export",
    RestoreFromBackup: "Restore from Backup",
    RestoreFromBackupFail: "Failed to restore backup from Steam Cloud: are you sure there's a backup?",
    RestoreFromBackupTitle: "Are you sure?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChangeName: "Change",
    SaveName: "Save",
    NameValidationRule: "Your name should only contain letters and numbers and be between 5-15 chars",
    NameValidationRuleProfanity: "Your name should not contain profanity",
    ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
    NameSaved: "Your name has been changed successfully",
    NoMessages: "No new messages",
    Leaderboard: "Leaderboard",
    Name: "Name",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2: "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from the Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building are determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Energy Saving",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Reward video did not complete",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turning on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Highlight "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    RunOutIn: "Out in %{time}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Expansion Packs",
    ExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Hide Discord Banner",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Hide Chat Message",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Swiss Money 💵",
    RestartDesc: "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
    PrestigeGoBack: "Go Back",
    ProductionMultiplier: "Production Multiplier",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    PrestigeAlertTitle: "Are you sure?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss Money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Cash In",
    Cancel: "Cancel",
    SaveFileCorrupted: "Save File Corrupted",
    LoadGameError: "Failed to Load Game",
    LoadGameErrorMessage: "Error message: %{message}",
    LoadGameErrorDesc: "Please check your internet connection. If the problem persists, please contact support",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    CashIn: "Cash In",
    CurrentCity: "Current City",
    CashInDesc:
        "You will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss Money",
    CitySize: "Map Size",
    GridType: "Grid Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "City Bonus",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>Universities have 2x productivity</li>",
    HideNotProducing: "Hide resources that are not being produced",
    SortByStorage: "Storage",
    SortByName: "Name",
    PlayerTrade: "Player Trade",
    AddTradeFail: "Failed to add your trade",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Your trade has been added successfully",
    ClaimTradeFail: "Failed to claim this trade, please try again later",
    CancelTradeSuccess: "Your trade has been cancelled successfully",
    CancelTradeFail: "Failed to cancel this trade, please try again later",
    AcceptTradeFail: "Failed to accept this trade, please try again later",
    PlayerTradeBanner: "Trade Resources with Other Players",
    PlayerTradeResource: "Resource",
    PlayerTradeAmount: "Amount",
    PlayerTradePrice: "Price $",
    PlayerTradeValue: "Value $",
    PlayerTradeWaiting: "Waiting...",
    AddTrade: "Add Trade",
    AcceptTrade: "Accept",
    CancelTrade: "Cancel",
    ClaimTrade: "Claim",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeValidRange: "Range: %{min} ~ %{max}",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "You have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transport and store any resources and with lower fuel cost",
    PowerBankChargeSpeed: "Charge Speed",
    PowerBankPowerLeft: "Power Left",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ColorTheme: "Color Theme",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Industrial Revolution",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    PowerBankLeft: "Power Bank",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Add Route",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Find on Map",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consumption",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Player Flag",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produce 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Resources tend to spawn in clusters</li><li>Warehouses provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Terms of Service",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Manga Publisher",
    Manga: "Manga",
    AnimeStudio: "Anime Studio",
    Anime: "Anime",
    PlayerTradeAction: "Action",
    PlayerTradeBuy: "Buy",
    PlayerTradeSell: "Sell",
    PlayerTradeBid: "Bid",
    PlayerTradeAsk: "Ask",
    ClaimTradeSuccessV2: "Your trade has been claimed successfully: %{cashOrResource}",
    AcceptTradeSuccessV2: "This trade has been accepted by you: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Better Than Market Price",
    ResourceExplorer: "Resource Explorer",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explore",
    ProductionSettings: "Production Settings",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Game Guides",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeds the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Fuel Cost",
    BuildingProfit: "Profit",
    RestoreBackup: "Restore",
    SteamLogin: "Sign In Through Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Sign In",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "International Export Trade",
    FreeTransportToTradeCenterDesc:
        "Transportation to the Trade Center does not cost fuel but transportation from the Trade Center cost 50% more fuel",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "In Storage: %{amount}",
    PlayerTradeFillValue: "Value",
    FiberFactory: "Fiber Factory",
    Fiber: "Fiber",
    Achievements: "Achievements",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Reward: Swiss Money +%{swiss}",
    AchievementsRewardToast: "You have claimed the reward:  Swiss Money +%{swiss}",
    AchievementsClaim: "Claim",
    AchievementsToast: "You have achieved %{name}, claim your reward in the Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Force Steam Cloud Backup",
    UILoading: "Loading...",
    UserAuthenticated: "You are authenticated",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max number of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but use 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Save and Exit Game",
    SaveAndExitDesc:
        "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in the Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Force Scroll",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ConstructionCancel: "Cancel",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
    HighlightUnderConstruction: "...that haven't been constructed",
    HighlightUnderLevel10: "...that are under level 10",
    HighlightUnderLevel20: "...that are under level 20",
    HighlightUnderLevel30: "...that are under level 30",
    Logout: "You Are Logged Out",
    ConstructionStatusQueueingV2: "Queueing",
    ConstructionStatusPausedV2: "Paused",
    ConstructionStatusBuildingV2: "Building",
    ConstructionStatusUnpaidV2: "Unpaid",
    ConstructionStatus: "Construction Status",
    ConstructionStart: "Start",
    CostFree: "Free",
    PlaceBlueprint: "Placing a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Only you",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "increased by %{percent}",
    MarketNewsDecrease: "decreased by %{percent}",
    MarketNewsBuilding: "This building is affected by %{num} news",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and currently you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burn most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turn red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles - both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to the Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Resource Booster",
    BuildWarningTitle: "Building Might Not Work",
    BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
    BuildWarningBuildAnyway: "Build Anyway",
    ResourceBoosterNotWorking: "⛔ Resource boosters only work next to deposit mines",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
    BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "Have 50 production lines that has production deficit",
    UseScientificNotation: "Use Scientific Notation",
    UseScientificNotationDesc: "Use scientific notation (e notation) for numbers larger than 999.9T",
    LogoutDescV2:
        "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
    LogBackIn: "Log Back In",
    PlayerTradeNowAllowedV2: "Player trades are not available within %{hour} hours of restoring/importing a save",
    ServerDisconnected:
        "You are disconnected from the server, please check your internet connection and restart the game",
    BuildingUpgradeCostDividerDescV2: "Divide building upgrade cost by this divider",
    ResourceBoosterDesc: "Boost the output of adjacent mines",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Dynamite Factory",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Nuclear Missile Factory",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Space Colony",
    SpaceColonyInc: "Space Colony Inc",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
    ToulouseBonusV2:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
    ResearchLabCultureInput: "The Renaissance",
    ResearchLabCultureInputDesc: "Research Lab has 2x capacity but takes culture as the extra input",
    GasPumpx2Output: "High Pressure Gas Pump",
    GasPumpx2OutputDesc: "Natural gas pumps have 2x output but use 2x power",
    LeaderboardValuationPerHour: "Total Valuation Per Hour",
    LeaderboardValuationPerHourPerSwiss: "Total Valuation Per Hour Per Swiss",
    LeaderboardValuationPerHourNewPlayers: "Total Valuation Per Hour (< 1000 Swiss)",
    LeaderboardValuationPerBuilding: "Building Valuation Per Building",
    BuildingCustomColor: "Building Color",
    BuildingCustomColorReset: "Reset",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Every 4 different types of buildings give 1 free building permit</li><li>Unique policy: Production Diversification</li><li>Unique building: Maple Syrup Factory</li><li>Free maple syrup transport</li><li>Unique fuel type: Maple Syrup</li><li>2x player trade quota when trading Uranium and Enriched Uranium</li><li>Unique free policy: Syrup Plastic</li><li>Toy factories have 2x productivity</li><li>Game studios have 2x capacity</li>",
    MapExtraPermitDesc: "You get %{number} free building permits from the map's unique bonus",
    OsloBonusV3:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 8 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    ResourceBoosterPercentageV2: "💡 This amount includes %{percent} boost from adjacent resource boosters",
    MapleSyrup: "Maple Syrup",
    MapleSyrupFactory: "Maple Syrup Factory",
    SyrupPlastic: "Syrup Plastic",
    SyrupPlasticDesc: "All buildings that input plastic use maple syrup instead",
    ResourceBoosterSupplyChain: "Supply Chain Booster",
    ResourceBoosterSupplyChainDesc:
        "Resource boosters use 2x power and science, but for each working mine a resource booster is boosting, it also provides capacity boost to adjacent factories that consume the mine's output (the factory should only consume deposits)",
    ProductionDiversification: "Production Diversification",
    ProductionDiversificationDesc: "Each different type of building gives 1% extra capacity to all buildings",
    ExtraPolicyPointsDescV2: "Policy center has 2x policy points conversion capacity",
    PowerRequired: "Power Required",
    AchievementVancouver100: "Sap Seller",
    AchievementVancouver100Desc: "Earn 100 Swiss Money in Vancouver in a single run",
    AchievementVancouver500: "Syrup Savant",
    AchievementVancouver500Desc: "Earn 500 Swiss Money in Vancouver in a single run",
    AchievementVancouver1000: "Canuck Conqueror",
    AchievementVancouver1000Desc: "Earn 1000 Swiss Money in Vancouver in a single run",
    BarbariansAtTheGate: "Barbarians At The Gate",
    BarbariansAtTheGateDesc: "Use 1 trillion worth of player trade quota between market updates",
    DiversifiedProductions: "Diversified Productions",
    DiversifiedProductionsDesc: "Build 100 different types of buildings on a single map",
    RealEstateTycoon: "Real Estate Tycoon",
    RealEstateTycoonDesc: "Have 400 buildings on a single map",
    ResourceExplorer2DescV2:
        "Resource explorers produce 2x output but use 2x power. Resource explorers can be boosted by resource boosters if Supply Chain Booster policy is active and the booster has an adjacent mine of the same output",
    NoTileModifier: "Earth Is Flat",
    NoTileModifierDesc:
        "All tile modifiers are zero. This policy will deactivate Nature's Power and Tile Modifier Plus policies",
    DoubleTileModifierDescV2:
        "All tile modifiers' effect x2 - both positive and negative. This policy will deactivate Earth Is Flat policy",
    TileModifierOutputOnlyDescV2:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective. This policy will deactivate Earth Is Flat policy",
    QuickLinks: "Quick Links",
    GetHelp: "Get Help",
    GetHelpBeginnerGuides: "Beginner's Guide",
    GetHelpSteamGuides: "Other Steam Guides",
    GetHelpInGameChat: "Ask In-Game Chat",
    GetHelpDiscord: "Join Our Discord Server",
    GetHelpWiki: "Community Wiki",
    SelectATile: "Select a Tile",
    PledgeAmount: "Pledge %{amount}",
    PledgeValue: "Value $%{amount}",
    TotalPledgedValue: "Total Pledged Value",
    TotalPledgedValueDesc:
        "Your first pledge counts towards the crowdfunding goal. Subsequent pledges increase total pledged value but do not count towards the goal",
    ReturnOnPledge: "Return On Pledge",
    CrowdfundingEndIn: "End in %{time}",
    ClaimCrowdfundingReward: "Claim Reward %{amount}",
    PledgeSuccessful: "You have pledged %{amount} to this crowdfunding",
    CrowdfundingClaimSuccessful: "You have claimed %{amount} cash",
    CrowdfundingAlreadyPledged: "You've Already Pledged",
    CrowdfundingAlreadyPledgedDesc:
        "You can pledge more resources, which will increase your total pledged value (and potential return), but won't count towards crowdfunding goal",
    WholesaleCenterProducingOnly: "Wholesale Partners",
    WholesaleCenterProducingOnlyDesc:
        "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
    SoftwareCompiler: "Software Compiler",
    SearchEngine: "Search Engine",
    SearchEngineCompany: "Search Engine Company",
    Navy: "Navy",
    NavyCommand: "Navy Command",
    Battleship: "Battleship",
    BattleshipFactory: "Battleship Factory",
    ResourceMovementHide: "Always Hide",
    ResourceMovementShow: "Always Show",
    ResourceMovementHighlight: "On Highlight",
    ResourceMovementLine: "Line Only",
    ResourceMovement: "Resource Movement",
    ResourceMovementDesc:
        "You can choose when to show the resource movement (dots). Hiding it can improvement performance",
    CrowdfundingCashInWarning: "You have pending crowdfunding pledges - starting in a new city will forfeit them",
    ResourceBoosterBannerDescV2:
        "💡 You currently have %{number} resource boosters - the science input of each is scaled to the number of resource boosters you currently have",
    CrowdfundingId: "Crowdfunding %{id}",
    PatchNotes: "Patch Notes",
    PatchNotesDesc: "Read what's new in this update",
    PanelPositionLeft: "Left (Docked)",
    PanelPositionLeftFloat: "Left (Float)",
    PanelPositionRight: "Right (Docked)",
    PanelPositionRightFloat: "Right (Float)",
    PanelPositionAuto: "Auto",
    TimePlayed: "Time Played",
    ValuationPerHour: "Valuation Per Hour",
    HighPowerPriority: "High Power Priority",
    HighPowerPriorityDesc: "Switching this on will make the building draw power before other buildings",
    IndustryZone: "Industry Zone",
    IndustryZoneDesc: "Combine adjacent buildings that forms a supply chain and save building permits",
    IndustryZoneMaxBuildingLevel: "Max Building Level",
    IndustryZoneNotWorkingDesc:
        "All of its adjacent buildings should form a supply chain and are not part of other industry zones",
    IndustryZoneNoAdjacentBonus: "This building is part of an industry zone and does not have adjacent bonus",
    PlayerTradeAutoClaim: "Automatycznie odbieraj oferty",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "Cloud Steaming",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "Labolatorium super komputerów",
    SuperComputer: "Super Komputer",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "SkyNet",
    RobocarFactory: "Fabryka Roboaut",
    Robocar: "Roboauto",
    WarehouseBuildingPermitSave: "Warehouse Permit Act",
    WarehouseBuildingPermitSaveDesc: "Every two warehouses provide one free building permit",
    PolicySearchPlaceholder: "Type a policy name to search",
    SwissUpgrade: "Swiss Ulepszenia",
    SwissUpgradeDesc: "Swiss upgrades are permanent and will carry over if you start in a new city",
    SwissBoost: "Swiss Bonus",
    SwissBoostDesc: "Swiss boosts only affect your current run - and will reset if you start in a new city",
    ProductionMultipliers: "Production Multipliers",
    MultiplierMapUniqueBonus: "Map Unique Bonus",
    MultiplierSwissUpgrade: "Swiss Upgrade (Permanent)",
    MultiplierSwissBoost: "Swiss Boost (This Run)",
    SwissBoostCostDivider: "Swiss Boost Cost Divider",
    SwissBoostCostDividerDesc: "Divide Swiss boost cost by this divider - only applies to multiplier/divider upgrades",
    AirForceCommand: "Siedziba sił powietrznych",
    AirForce: "Siły powietrzne",
    StealthFighterFactory: "Fabryka myśliwców",
    StealthFighter: "Myśliwiec",
    ArmyCommand: "Army Command",
    Army: "Armia",
    GreenPeacekeeper: "Zielony Strażnik Pokoju",
    GreenPeacekeeperDesc:
        "Twórz armie, marynarkę wojenna, siły potwietrzne czy drużyny kosmiczne korzystajac tylko z odnawialnych źródeł energii (turbina, panel solarny)",
    DotComTycoon: "Bańka internetowa",
    DotComTycoonDesc:
        "Build a level 10 Social Network Inc, level 10 Search Engine Company, level 10 SkyNet Inc and level 10 Musify Inc on the same map",
    ConstructionNotResearched: "Nie zbadano",
    OfflineEarningDescV2: "Offline earning depends on your current research, production and auto sell",
    HighSpeedWarehouse: "High Speed Warehouse",
    HighSpeedWarehouseDesc:
        "Warehouses have 2x capacity and 50% faster inward and outward transport speed, but use 2x power",
    IndustryZoneMultiplierDesc: "Industry Zone Bonus",
    IndustryZoneMultiplierSwissBoost: "Industry Zone Capacity Booster",
    EarningPerMinuteV2: "Zarobki offline",
    OfflineResearchPoint: "Punkty badań offline",
    WholesaleCenterOrderFasterV2: "Szybki rynek zbytu",
    OfflineResearchSwissBoost: "Badania offline",
    OfflineResearchSwissBoostDesc:
        "Research points are generated while you are offline (according to your Research Lab level, Science in your warehouse and offline earning time)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Unique building: chip manufacturer</li><li>Unique building: FaceApp Inc</li><li>Unique building: Bitcoin Miner</li><li>All buildings that consume silicon have max tile modifier</li><li>Solar panels generate 2x power</li><li>Silicon mines have 2x output</li>",
    RotterdamBonusV2:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>Earth Is Flat policy is free</li>",
    ChipManufacturer: "Chip Manufacturer",
    SnapTokInc: "SnapTok Inc",
    FaceAppInc: "FaceApp Inc",
    BitcoinMiner: "Bitcoin Miner",
    GalvanicBatteryFactory: "Galvanic Battery Factory",
    BaseProductionMultiplier: "Base Production",
    ShowBreakdown: "Show Breakdown",
    HideBreakdown: "Hide Breakdown",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Each tier of production chain inside an industry zone provides this capacity boost to all the buildings in the same zone",
    IndustryZoneBuildingPermitDesc:
        "If an industry zone has N tiers of productions, it will provide N-2 building permits for free",
    CrowdfundingBackersReturn: "Backers: %{backers}, Current Return: %{return}",
    CrowdfundingBackersNeeded: "%{backers} More Backer(s)",
    CrowdfundingReturnBonus: "+%{return} Return",
    ReturnOnPledgeDescV2:
        "Your total return equals to total pledged value multiplied by return rates from all resources. More backers of a resource will improve its return",
    PlayerTradeQuotaDescV2:
        "💡 Quota is the amount of the resource you can trade. The monetary value equals to %{percent} of your market cap and it resets when the market updates. The more your trade's price deviates from your trade center price, the more quota you need",
    AchievementSanJose100: "Venture Hobbyist",
    AchievementSanJose100Desc: "Earn 100 Swiss Money in San Jose in a single run",
    AchievementSanJose500: "Venture Enthusiast",
    AchievementSanJose500Desc: "Earn 500 Swiss Money in San Jose in a single run",
    AchievementSanJose1000: "Venture Capitalist",
    AchievementSanJose1000Desc: "Earn 1000 Swiss Money in San Jose in a single run",
    AchievementCrowdfundingTycoon: "Crowdfunding Tycoon",
    AchievementCrowdfundingTycoonDesc: "Pledge 1Qa worth of resources in a single crowdfunding",
    AchievementCashIsKing: "Cash Is King",
    AchievementCashIsKingDesc: "Have 1Qa cash at hand in a single run",
    AchievementPowerTycoon: "Power Tycoon",
    AchievementPowerTycoonDesc: "Generate 1GW power in a single run",
    PlayerTradeFilteringNResources: "Filtering %{n} Resource(s)",
    PlayerTradeFilterResources: "Filter Resources",
    PlayerTradeFilterClear: "Clear Filters",
    ResourceExplorerAll: "Explore All Resources",
    ResourceExplorerAllDesc:
        "Resource explorers can produce all resources, including the ones that are not on the map (this DOES NOT unlock the relevant technologies)",
    ShowResourceInTopBar: "Show In Top Bar",
    LeaderboardOptOutDescV2:
        "You will no longer appear in the leaderboard. This will also disable player trade. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    PolicyPointNoCopperDesc:
        "💡 This map doesn't have copper deposits, you can activate Al Circuit policy to unlock further technologies",
    Pumpkin: "Pumpkin",
    PumpkinBattery: "Pumpkin Battery",
    PumpkinBatteryDesc: "All buildings that consume battery use pumpkin instead (FREE POLICY)",
    PumpkinSteel: "Pumpkin Steel",
    PumpkinSteelDesc: "All buildings that consume steel use pumpkin instead (FREE POLICY)",
    RequireExpansionPack2: "Expansion Pack 2",
    ExpansionPack2: "Expansion Pack 2",
    RequireExpansionPack2Desc: "This is only available for Expansion Pack 2",
    Reindeer: "Reindeer",
    ReindeerSilicon: "Reindeer Silicon",
    ReindeerSiliconDesc: "All buildings that consume silicon use reindeer instead (FREE POLICY)",
    ReindeerAluminum: "Reindeer Aluminum",
    ReindeerAluminumDesc: "All buildings that consume aluminum use reindeer instead (FREE POLICY)",
    SantaClauseIsComing: "Santa Clause is Coming",
    SantaClauseIsComingDesc:
        "Santa factories consume reindeer and toy and produce santa, science and culture. Santa factories have max tile modifier. Toy factories produce reindeer in addition to toy (FREE POLICY)",
    MetaRebranding: "Meta Rebranding",
    MetaRebrandingDesc:
        "Social Network Inc is renamed to Meta Inc and consumes internet, game, super computer, bitcoin and dogecoin instead",
    MetaInc: "Meta Inc",
};
