export const PL = {
    Translator: "Translator",
    TranslatorName: "Tutaj Wpisz Swoje Imię!",
    Language: "Język",
    ThisLanguage: "Polski",
    OK: "OK",
    SteelMill: "Huta stali",
    StainlessSteelPlant: "Fabryka stali nierdzewnej",
    CircuitFoundry: "Odlewnia obwodów",
    IntegratedCircuit: "Układ scalony",
    OilWell: "Szyb naftowy",
    Wood: "Drewno",
    LoggingCamp: "Obóz wyrębu drzew",
    LumberMill: "Tartak",
    Lumber: "Kłody",
    Paper: "Papier",
    PaperMill: "Papiernia",
    Book: "Książki",
    BookPublisher: "Wydawca książek",
    OilRefinery: "Rafineria ropy naftowej",
    Sell: "Sprzedaj",
    Upgrade: "Ulepsz",
    Build: "Wybuduj",
    Buildings: "Budynki",
    Iron: "Żelazo",
    FuelType: "Wybierz paliwo",
    FuelCost: "Koszt paliwa",
    FuelEconomy: "Ekonomia paliwowa",
    FuelInStorage: "%{fuel} na stanie",
    Plastic: "Plastik",
    Petrol: "Benzyna",
    Buy: "Kup",
    NoLiquidity: "Brak płynności",
    NoLiquidityTurnOffAutoSell:
        "Nie ma wystarczającej ilości produktów na rynku dla %{res}, automatyczna sprzedaż została wyłączona",
    Multiplier: "Mnożnik",
    MultiplierDesc: "Każde 10 poziomów, zwieksza mnożnik o 1",
    SellBuilding: "Sprzedaj budynek",
    PowerGrid: "Sieć energetyczna",
    TradeAmount: "Ilość towaru",
    SortBy: "Sortuj po",
    SortByPrice: "Cena",
    SortByAmount: "Ilość",
    NotEnoughResources: "Niewystarczająca ilość produktów, by wykonać tę akcję",
    Transportation: "Transport",
    Cash: "Gotówka",
    Aluminum: "Aluminium",
    ResearchPoint: "Punkt Badawczy",
    Unlock: "Odblokuj",
    BuildingUnlocked: "%{building} został odblokowany",
    Science: "Nauka",
    ScienceFromPowerDesc: "Elektrownie wytwarzają niewielką ilość Nauki podczas wytwarzania energii",
    Culture: "Kultura",
    School: "Szkoła",
    University: "Uniwersytet",
    Polytechnic: "Politechnika",
    Colosseum: "Koloseum",
    WindTurbine: "Turbina wiatrowa",
    Engine: "Silnik",
    EngineFactory: "Fabryka silników",
    CameraFactory: "Fabryka aparatów",
    Camera: "Aparat fotograficzny",
    Gun: "Pistolet",
    GunFactory: "Fabryka broni",
    Aircraft: "Samolot",
    AircraftFactory: "Fabryka samolotów",
    Zeppelin: "Sterowiec",
    ZeppelinFactory: "Fabryka sterowców",
    Tank: "Czołg",
    TankFactory: "Fabryka czołgów",
    CoalPowerPlant: "Elektrownia węglowa",
    PetrolPowerPlant: "Elektrownia benzynowa",
    Copper: "Miedź",
    Gas: "Gaz ziemny",
    GasPump: "Pompa gazu ziemnego",
    GasPowerPlant: "Elektrownia gazowa",
    Missile: "Pocisk rakietowy",
    MissileFactory: "Fabryka pocisków rakietowych",
    Rocket: "Rakieta",
    RocketFactory: "Fabryka rakiet",
    BuildingPermit: "Pozwolenie na budowę",
    BuildingPermitDesc:
        "Masz pozwolenia na budowę %{amount} budynków, zbudowałeś już %{amountBuilt} i pozostało Ci %{amountLeft}",
    BuildingLocked: "Budynek nie jest jeszcze dostępny, musisz go najpierw odblokować w Laboratorium Badawczym",
    MaxBuilders: "Limit budujących",
    MaxBuildersDesc: "Liczba budynków, które możesz zbudować jednocześnie",
    Silicon: "Krzem",
    AluminumMine: "Kopalnia aluminium",
    CopperMine: "Kopalnia miedzi",
    SiliconMine: "Kopalnia Krzemu",
    IronMine: "Kopalnia żelaza",
    CoalMine: "Kopalnia Węgla",
    Headquarter: "Centrala",
    ResearchLab: "Laboratorium Badawcze",
    TradeCenter: "Rynek",
    Resources: "Surowce",
    NotEnoughCash: "Niewystarczająca ilość gotówki do wykonanie tej akcji",
    NotEnoughSwissMoney: "Niewystarczająca ilość Swiss Money do wykonanie tej akcji",
    BuildingNotEnoughFuel: "💡 Niewystarczająca ilość %{fuel}",
    AutoSell: "Automatyczna sprzedaż",
    Change: "Zmień",
    StatisticsBureau: "Biuro Statystyczne",
    LogisticsDepartment: "Dział logistyki",
    From: "Z",
    Top20FuelCost: "Top 20 kosztów paliwa",
    To: "Do",
    TransportTime: "Czas transportu",
    Warehouse: "Magazyn",
    TradeWarehouse: "Główny magazyn towarowy",
    Coal: "Węgiel",
    Video: "Wideo",
    ClothingFactory: "Fabryka odzieży",
    Clothes: "Odzież",
    Fashion: "Moda",
    FashionFactory: "Fabryka mody",
    VideoFarm: "Video blogi",
    SantaFactory: "Fabryka Świętych Mikołajów",
    Santa: "Świety Mikołaj",
    Car: "Samochód",
    CarFactory: "Fabryka Samochodów",
    Ship: "Statek",
    SolarPanel: "Panel słoneczny",
    SolarPanelDesc: "💡 Panele słoneczne działają tylko 5 sekund na każde 10 sekund - wszystkie cykle są wyrównane",
    WindTurbineDesc: "💡 Turbiny wiatrowe działają tylko 8 sekund na każde 10 sekund - cykle nie są równane",
    Movie: "Film",
    MovieStudio: "Studio filmowe",
    Sitcom: "Sitcom",
    TVStudio: "Studio telewizyjne",
    PC: "Komputer",
    GameStudio: "Developer gier",
    Game: "Gry",
    ComputerFactory: "Fabryka komputerów",
    Shipyard: "Stocznia",
    PowerUsage: "Zużycie energii",
    PowerSupply: "Zasilanie",
    Level: "Poziom",
    Power: "Moc/Zasilanie",
    CentralBank: "Bank centralny",
    ResourceInput: "Pobiera",
    ResourceOutput: "Produkuje",
    ResourceStorage: "Magazyn",
    ResourceChange: "Zmiana",
    ResourceInOutDesc:
        "💡 Stuknij w liczby Pobiera/Produkuje powyżej, aby podświetlić odpowiednie budynki produkujące i pobierajace.",
    MarketUpdateIn: "Aktualizacja rynku za %{time}",
    Semiconductor: "Półprzewodnik",
    SemiconductorFactory: "Fabryka półprzewodników",
    Steel: "Stal",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Farma Bitcoina",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Farma Dogecoina",
    Guitar: "Gitara",
    GuitarFactory: "Fabryka Gitar",
    Drum: "Perkusja",
    DrumFactory: "Fabryka Perkusji",
    RecordingStudio: "Studio nagrań",
    OperaHouse: "Opera",
    CoalGasificationPlant: "Zakład zgazowania węgla",
    GasProcessingPlant: "Zakład przetwórstwa gazu",
    Music: "Muzyka",
    Glass: "Szkło",
    PhoneFactory: "Fabryka telefonów komórkowych",
    Phone: "Komórka",
    GlassFactory: "Fabryka szkła",
    Oil: "Ropa",
    Chromium: "Chrom",
    ChromiumMine: "Kopalnia chromu",
    Uranium: "Uran",
    EnrichedUranium: "Wzbogacony uran",
    NuclearPowerPlant: "Elektrownia jądrowa",
    UraniumEnrichmentPlant: "Zakład wzbogacania uranu",
    UraniumMine: "Kopalnia uranu",
    Titanium: "Tytan",
    TitaniumMine: "Kopalnia tytanu",
    TitaniumAlloyPlant: "Fabryka stopów tytanu",
    ChromiumAlloyPlant: "Fabryka stopów chromu",
    Input: "Potrzebuje",
    PanelPosition: "Pozycja wyświetlacza",
    PanelPositionDesc: "Pokaż panel boczny z lewej, prawej lub automatycznie (zależne od zaznaczonego pola)",
    InputCapacity: "Pojemność wejściowa",
    Output: "Produkuje",
    OutputCapacity: "Pojemność wyjściowa",
    ResourceDeposit: "Depozyt zasobów",
    AdjacentBonus: "Premia za sąsiedztwo",
    AdjacentBonusDesc:
        "Otrzymujesz %{bonus}% dodatkową premię za każdy sąsiadujacy i pracujacy budynek tego samego typu",
    ConsiderIncreaseProduction: "💡 Rozważ zwiekszenie produkcji %{resource} ",
    AlwaysTransportInput: "Nadwyżka magazynowa",
    AlwaysTransportInputTradeCenter: "Zawsze eksportuj",
    AlwaysTransportInputTradeCenterDesc:
        "Zawsze transportuj surowce do Rynku, nawet jeżeli autosprzedaż nie jest katywna dla danego surowca",
    AlwaysTransportInputDesc:
        "Zawsze transportuj surowce produkcyjne, nawet jeżeli spełnione zostały minimalne wymogi produkcji",
    ProductionCycleLength: "Cykl produkcyjny",
    ProductionCycleLengthDesc:
        "Długość cyklu produkcji mierzona jest w sekundach. Wydłużenie cyklu zwiększy zapotrzeobwanie surowców i produkcje, tym samym redukując priorytet dostarczania surowców",
    MaxInputDistance: "Maksymalna odległość zaopatrzenia",
    MaxInputDistanceDesc:
        "Maksymalna odległość z jakiej budynek jest w stanie pobierać surowce do produkcji, liczone w polach.",
    AutoSellCapacity: "Przepustowość automatycznej sprzedaży",
    AutoSellCapacityDesc: "Maksymalna ilość produktu jaki może być sprzedawany automatycznie w sekundach/ilość",
    CurrentAutoSellCapacityMultiplier: "Bieżacy mnożnik: x%{n}",
    AutoSellConcurrency: "Limit rodzajów sprzedawanych towarów",
    AutoSellConcurrencyDesc: "Maksymalna liczba rodzajów produktów jakie można sprzedawać w tym samamy czasie",
    MaxAutoSellConcurrencyReached:
        "Osiągnąłeś maksymalna liczbę rodzajów sprzedawanych produktów, zaprzestań sprzedawania innego produktu by zacząć sprzedawać wybrany.",
    WallStreet: "Giełda Wall Street",
    MarketCap: "Kapitalizacja rynku",
    MarketCapDesc: "Total market capitalization (i.e. market value) of your corporation",
    BuildingValuation: "Wartość twoich budynków",
    BuildingValuationDesc: "Łączna wartość twoich budynków, włącznie ze zgodami na budowe i ulepszeniami",
    ResourcesValuation: "Wartość surowców",
    ResourcesValuationDesc: "Łączna wartość surowców w twoim ekwipunku",
    Battery: "Bateria",
    BatteryFactory: "Fabryka baterii",
    RatingBuy: "Kup",
    RatingSell: "Sprzedaj",
    SwissShop: "Swiss Shop",
    RatingHold: "Wstrzymaj się",
    RatingOutperform: "Wyśmienicie",
    RatingUnderperform: "Poniżej normy",
    StockRating: "Wartość akcji",
    JetEngine: "Silnik odrzutowy",
    Helicopter: "Helikopter",
    Lithium: "Lit",
    LithiumMine: "Kopalnia litu",
    LiionBatteryFactory: "Fabryka baterii litowych",
    HelicopterFactory: "Fabryka helikopterów",
    Satellite: "Satelita",
    ToyFactory: "Fabryka zabawek",
    Toy: "Zabawka",
    SpaceStation: "Stacja kosmiczna",
    SpaceStationFactory: "Fabryka stacji kosmicznych",
    OperatingSystem: "System operacyjny",
    OperatingSystemCompany: "Developer systemów operacyjnych",
    LinuxDistribution: "Dystrybucja systemu Linux",
    Internet: "Internet",
    WebBrowser: "Przeglądarka internetowa",
    Console: "Konsola",
    ConsoleFactory: "Fabryka konsol",
    Train: "Pociąg",
    TrainFactory: "Fabryka pociągów",
    ShoeFactory: "Fabryka butów",
    Shoes: "Buty",
    ArtilleryFactory: "Fabryka dział",
    Artillery: "Działo",
    SubmarineFactory: "Fabryka łodzi podwodnych",
    Submarine: "Łódź podwodna",
    Spaceship: "Statek kosmiczny",
    RobotFactory: "Fabryka robotów",
    Robot: "Robot",
    SpaceshipFactory: "Fabryka statków kosmicznych",
    SatelliteFactory: "Fabryka satelit",
    JetEngineFactory: "fabryka silników odrzutowych",
    StockRatingDesc:
        "Ocena wartości akcji od analityków z Wall Street, która wpływa na kapitalizację rynkową i jest aktualizowana wraz z rynkiem",
    OfflineEarning: "Dochód offline",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Czas dochodu offline",
    OfflineEarningTimeDesc: "Zarabiasz w trybie offline do tego progu",
    BuyPermit: "Kup pozwolenie",
    Settings: "Ustawienia",
    Sound: "Efekt dźwiękowy",
    SoundDesc: "Włącz efekt dźwiękowy, taki jak dźwięk kliknięcia lub dźwięk błędu",
    AutoHighlight: "Automatyczne podświetlanie",
    AutoHighlightDesc: "Automatycznie podświetlaj budynki tego samego typu po wybraniu budynku",
    MusicDesc: "Włącz muzykę: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Ikony",
    MisplacedBuilding: "⛔ Ten %{building} nie jest umieszczany na odpowiednim depozycie zasobów",
    HighlightBuildings: "Budynki podświetlone",
    HighlightTurnedOff: "...wyłączone budynki",
    HighlightStockpileModeOn: "...z włączonym trybem magazynowania zasobów",
    HighlightProductionCycleNotDefault: "...z cyklem produkcyjnym > 1",
    HighlightMaxInputDistanceNotDefault: "...z maksymalnym zasięgiem poboru surowców < ∞",
    HighlightNotMakingProfit: "...które nie zarabiają",
    NBuildingsAreHighlighted: "%{n} budynków zostało podświetlonych",
    TurnOffProduction: "Wyłącz",
    TurnOffProductionDesc: "Wyłącz produkcję budynku. Budynek nie będzie już transportował surowców i zużywał energii",
    ApplyToAll: "Zastosuj dla wszystkich %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Nielimitowany",
    Transport: "Transport",
    TileModifier: "Modyfikator pól",
    ShowAllModifiers: "Pokaż wszystkie modyfikatory",
    HideAllModifiers: "Ukryj wszystkie modyfikatory",
    NumberOfBuildings: "Liczba budynków które posiadasz",
    ShowContent: "Pokaż obiekt",
    HideContent: "ukryj obiekt",
    BuyExpansionPack: "Kup za %{price}",
    Cities: "Miasta",
    InputStrategy: "Strategia poboru materiałów",
    InputStrategyClose: "Bliskie",
    InputStrategyCloseDesc: "Wybieraj magazyny znajdujące sie najbliżej i posiadające wystarczającą ilość surowców",
    InputStrategyFar: "Najdalsze",
    InputStrategyFarDesc: "Wybieraj magazyny znajdujące sie najdalej i posiadające wystarczającą ilość surowców",
    InputStrategyAmount: "Ilość",
    InputStrategyAmountDesc: "Wybieraj magazyny posiadające największość ilość zasobów, niezależnie od dystansu",
    FuelCostSave: "Oszczędność kosztów transportu",
    FuelCostSaveDescV2:
        "Magazyny oszczędzają pewien procent paliwa do transportu surowców w porównaniu z innymi budynkami, im wyższy poziom, tym więcej oszczędności",
    SoftwareCompany: "Hurtownia oprogramowania",
    Software: "Oprogramowanie",
    ScreenFactory: "Fabryka wyświetlaczy",
    Screen: "Wyświetlacz",
    JoinDiscord: "Dołącz do naszego serwera Discord, aby otrzymywać najnowsze aktualizacje, wskazówki i móc prowadzić dyskusje",
    ClaimOfflineEarning: "Odbierz zarobki offline",
    OfflineTime: "Czas bycia nieobecnym",
    Minutes: "%{time}min",
    MaxUpgrade: "Maksymalny poziom ulepszenia",
    MaxUpgradeDesc: "Osiągnołeś maksymalny poziom ulepszeń",
    ClaimAmount: "Pieniądze +%{amount}",
    EffectiveTime: "Efektywny czas",
    EffectiveTimeDesc: "Twój efektywny czas zarabiania offline jest ograniczony do %{time}min.",
    BuildSearchPlaceholder: "Wpisz budynek lub zasób do przeszukania",
    MineOverlayWarning: "%{building} nie podlega modyfikatorowi pól",
    WholesaleCenter: "Centrum hurtowe",
    OrderFrom: "Zamów z %{name}",
    ExpireIn: "Wygasa za",
    Reward: "Nagroda",
    PerSecond: "%{time}/s",
    PolicyPoint: "Punkty patentowe",
    PolicyPointDesc: "💡 Im więcej aktywnych patentów, tym więcej punktów patentowych zostaje zużytych",
    NextOrderIn: "Następne zamówienie w",
    FillOrder: "Wypełnij zamówienie",
    RejectOrder: "Zrezygnuj",
    WholesaleCenterLocked:
        "Potrzebujesz przynajmniej %{required} różnych zasobów, aby odblokować Centrum Hurtowe. Masz tylko  %{current} Surowców",
    OrderFilled: "Zamówienie od %{from} zostało pomyślnie wypełnione!",
    PolicyCenter: "Centrum Polityki",
    NewOrder: "Nowe zamówienie od %{from} dotarło, sprawdź w centrum hurtowym!",
    Policies: "Polityka",
    PolicyNotEnoughTime: "Nie masz wystarczającej liczby punktów za tę politykę",
    WholesaleCenterOrderFasterDesc: "Centrum Hurtowe otrzymuje zamówienia 2x szybciej, a wielkość zamówienia jest 2x większa",
    PolicyOilWellPowerx2: "Doładowanie szybu naftowego",
    PolicyOilWellPowerx2Desc: "Szyby naftowe produkują 2x więcej ropy i zużywają 2x więcej moc",
    HalfTransportSpeed: "Zwolnij, aby zaoszczędzić",
    HalfTransportSpeedDesc: "Prędkość transportu zostaje zmniejszona o 25%, a koszt paliwa zmniejszony o 25%",
    RefineryMoreOil: "Rafineria Potrzebuje Więcej ropy",
    RefineryMoreOilDesc: "Rafinerie ropy naftowej produkują o 50% więcej benzyny i 50% mniej plastiku",
    StickyInput: "Dane wejściowe",
    StickyInputDesc:
        "Budynki wolą transportować z poprzedniego źródła, zamiast szukać najlepszego źródła w każdym cyklu",
    RefineryMorePlastic: "Rafineria Potrzebuje Więcej plastiku",
    RefineryMorePlasticDesc: "Rafinerie ropy naftowej produkują o 50% mniej benzyny i 50% więcej plastiku",
    FreeOilTransportDesc: "Transport ropy nie zużywa paliwa, ale szyby naftowe zużywają 2x moc",
    SuperSteelMill: "Serca z żelaza",
    SuperSteelMillDesc: "Huty zużywają o 50% mniej węgla, a 25% więcej żelaza i 25% więcej mocy",
    AlSemiconductor: "Obwód Al",
    AlSemiconductorDesc: "Po Odlaniu obwodów używają aluminium zamiast miedzi",
    CostSaver: "Oszczędność kosztów",
    CostSaverDesc: "Jeśli nakłady finansowe  na budynek kosztują więcej niż jego produkcja, zamknij produkcję",
    CostSaverBuildingDesc:
        "Polityki oszczędność  jest aktywna, produkcja będzie się włączać/wyłączać automatycznie w oparciu o jej rentowność",
    CostSaverBuildingWarning: "Polityki oszczędności kosztów jest aktywna, nie można ręcznie zmienić produkcji",
    GlassUseCoal: "Czarne szkło",
    GlassUseCoalDesc: "Fabryki szkła zużywają o 50% więcej węgla i 50% mniej krzemu",
    AdjacentBonusOnlyOutput: "Sąsiadujący bonus dodatkowy",
    AdjacentBonusOnlyOutputDesc:
        "Sąsiadująca premia nie wymagają większego wkładu, ale zużywa więcej mocy i jest skuteczniejsza tylko o 50%",
    IronMine2xOutput: "Ciężkie żelazo",
    IronMine2xOutputDesc: "Kopalnie żelaza produkują 2x więcej żelaza, ale transport żelaza kosztuje 2x wiecej  paliwa",
    SolarPanelAlwaysWork: "Słońce nigdy nie zachodzi",
    SolarPanelAlwaysWorkDesc: "Panele słoneczne działają przez 100% czasu, ale wytwarzają o 60% mniej energii",
    SteelScience: "Wiedza przez stal",
    SteelScienceDesc: "Huty zużywają 2x więcej wkład i produkują dodatkową naukę",
    ShoppingSpree: "Szał zakupów",
    ShoppingSpreeDesc:
        "Jeśli wydajność zasobu jest niewystarczająca, kup ilość brakującą w Centrum Handlowym automatycznie (jeśli zasób ma automatyczną sprzedaż, zostanie zignorowany)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Zasady dotyczące zakupów są włączone, Trade Center automatycznie kupi brakujące zasoby",
    ExtraPolicyPoints: "Lobbysta polityczny",
    CrAlloyUseFe: "chrom",
    CrAlloyUseFeDesc: "Zakłady produkujące stopy chromu nie używają litu, ale zamiast tego używają 2x więcej żelaza",
    DoubleTileModifier: "Siła Natury",
    TileModifierOutputOnly: "Modyfikatory płytek Dodatkowych",
    GasPlantPetrol: "Likwidator gazu",
    GasPlantPetrolDesc: "Elektrownie gazowe zużywają dodatkowy gaz do produkcji benzyny",
    CoalPlantFuel: "Zmiękczacz węgla",
    CoalPlantFuelDesc: "Elektrownie węglowe wykorzystują dodatkowy węgiel do produkcji benzyny",
    Welcome: "Witamy!",
    SeeTutorialAgain: "Ponów samouczek",
    HelpTranslateTheGame: "Pomóż przetłumaczyć grę🌐",
    NextTutorial: "Następny",
    Tutorial1:
        "Przemysł w którym <em>zarządzasz zasobami</em> gra, w której budujesz fabryki 🏭, produkujesz towary 📦 i zarabiasz pieniądze 💸.<br><br>Przejdźmy przez kilka podstawowych pojęć, aby zacząć – to nie potrwa długo, obiecuję⏲.",
    Tutorial2:
        "Wszystkie fabryki Potrzebują energi elektrycznej ⚡, masz <em>turbine wiatrową</em> która generuje moc. Możesz zobaczyć swój aktualny stan prądu po lewej stronie górnego paska.<br><br>Być może zauważyłeś, że turbiny wiatrowe działają tylko? <em>80%</em> czasu. Możesz rozważyć budowę innych typów elektrowni, które generują stabilną moc.",
    Tutorial3:
        "Masz dużo <em>depozytów surowców</em> na mapie. Aby wydobywać surowce, musisz budować kopalnie⛏️ <em>na powierzchni za </em> odpowiedni depozyt.<br><br>Na przykład masz <em>szyb naftowy🛢️</em> to wyciągi <em>oil</em> ze złoża ropy.<br></br>Depozyty surowców są nieograniczone- nie musisz się martwić, że się skończą. Oprócz kopalń na każdym pustym kafelku można budować inne budynki.",
    Tutorial5:
        "Aby zarabiać pieniądze, musisz wyeksportować swoje zasoby za pośrednictwem centrum handlowego. Aby to zrobić, po prostu włącz <em>automatyczną Sprzedaż</em> dla tego zasobu.<br></br>Surowce można również kupić w centrum handlowym. Pamiętaj <em>jeśli kupisz zasoby, podniesiesz cenę</em>a jeśli sprzedasz zasoby, obniżysz cenę.<br><br>Rynek jest <em>zmienny</em> jak i cena📈zmienia się regularnie.",
    Tutorial6:
        "Aby budować nowe budynki, musisz je najpierw odblokować w <em>laboratorium badawczym🧪</em>. Laboratorium badawcze przekształca również naukę w punkty badawcze.<br><br>Twoja turbina wiatrowa (i inne elektrownie) wytwarzają niewielką ilość nauki podczas pracy. Możesz zbudować szkołę🏫 i inne dedykowane budynki, aby później wzmocnić naukę.<br><br>Teraz nauczyłeś się wszystkich podstaw, zacznij budować swoją gospodarkę! Oto kilka drobnych <em>złotych💸</em> oraz <em>kilka litrów benzyny⛽</em> aby dać ci szybki start.",
    WelcomePlay: "Graj",
    WelcomePlayMuted: "Włącz/Wyłącz (🔇muzykę)",
    Chat: "Czat",
    RestoreFromBackup: "Przywróć z kopii zapasowej",
    RestoreFromBackupFail: "Nie udało się przywrócić kopii zapasowej ze Steam Cloud: czy na pewno istnieje kopia zapasowa?",
    RestoreFromBackupTitle: "Jesteś pewny?",
    RestoreFromBackupDesc:
        "Zwykle nie musisz przywracać danych z kopii zapasowej w chmurze, chyba że utracisz lokalny zapis. Kopie zapasowe w chmurze są nieco starsze niż lokalne zapisy",
    ChangeName: "Zmień",
    SaveName: "Zapisz",
    NameValidationRule: "Twoja nazwa powinno zawierać tylko litery i cyfry oraz mieć od 5 do 15 znaków",
    NameValidationRuleProfanity: "Twoja nazwa  nie powinno zawierać wulgaryzmów",
    ChatMessageRateLimit: "Możesz wysłać nową wiadomość dla czatu tylko co 10 sekund",
    NameSaved: "Twoja nazwa zostało pomyślnie zmienione",
    NoMessages: "Brak nowych wiadomości",
    Leaderboard: "Tablica wyników",
    Name: "Nazwa",
    Tips1: "Oceny akcji mają 5 poziomów: kup, przewyższaj, trzymaj, poniżej wyników i sprzedawaj",
    Tips2: "Budynki przestaną transportować zasoby, jeśli jest ich już wystarczająco do produkcji, chyba że włączysz tryb gromadzenia zasobów",
    Tips3: "Koszt paliwa do transportu zasobów zależy od odległości i ilości zasobów",
    Tips4: "Budynki będą transportować zasób tylko wtedy, gdy ilość znaleziona na mapie przekracza pojemność wejściową",
    Tips5: "Budynki będą transportować zasoby z Centrum Handlowego tylko wtedy, gdy automatyczna sprzedaż jest wyłączona dla tego zasobu",
    Tips6: "Możesz zobaczyć koszt paliwa dla zasobu w odpowiedniej sekcji pojemności wejściowej",
    Tips7: "Jeśli kupisz zasób, podniesiesz cenę. Jeśli sprzedasz zasób, obniżysz cenę",
    Tips8: "Możesz zobaczyć wykres dla ilości każdego zasobu i jego zmiany w czasie w Biurze Statystycznym",
    Tips9: "Punkty badań potrzebne do budowy budynków są określane przez cenę rynkową jego zasobów wejściowych",
    Tips10: "Różne zasoby są różnie wyceniane na rynku - zawsze bądź przygotowany na zmienność rynku",
    Tips11: "Przed rozszerzeniem produkcji warto zawsze sprawdzić stan zasilania i paliwa",
    FPS30: "Oszczędzanie energii",
    OfflineModeDesc:
        "Nie można połączyć się z serwerem: zarobki offline nie będą generowane. Proszę sprawdzić swoje połączenie z internetem",
    OptOut: "Zrezygnuj",
    OptIn: "Zresetuj i włącz ponownie",
    LeaderboardOptOut: "Rezygnacja z tabeli wyników",
    LeaderboardOptIn: "Zresetuj i włącz tablicę wyników",
    LeaderboardOptInDesc: "Twoje dane muszą zostać zresetowane, zanim będzie można ponownie włączyć tabelę wyników, czy na pewno?",
    RewardAdsFailed: "Film z nagrodą nie został ukończony",
    OfflineEarningDoubleSuccess: "Podwoiłeś swoje zarobki offline",
    FPS30Desc:
        "Włączenie trybu oszczędzania energii uruchomi grę przy 30 FPS zamiast 60 FPS. Dzięki temu bateria będzie działać dłużej",
    HighlightAll: 'Atrakcja "%{type}"',
    HighlightInput: "🔍 Atrakcja %{type} Wejście",
    HighlightOutput: "🔍 Atrakcja %{type} Wyjście",
    RunOutIn: "na zewnątrz %{time}",
    SwissBank: "Szwajcarski Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Jeśli zaczniesz w nowym mieście, dostaniesz %{money} 💵",
    RestorePurchases: "Przywróć zakupy",
    RestorePurchasesSuccess: "Twoje zakupy zostały przywrócone",
    RestorePurchasesFailed: "Twoje zakupy nie zostały przywrócone",
    ExpansionPacks: "Pakiety rozszerzeń",
    ExpansionPack1: "Dodatek 1",
    RequireExpansionPack1: "Dodatek 1",
    RequireExpansionPack1Desc: "Jest to dostępne tylko dla dodatku Expansion Pack 1",
    RequireAnyExpansionPack: "Ekskluzywne pakiety rozszerzeń",
    RequireAnyExpansionPackDesc: "Ta funkcja wymaga posiadania co najmniej jednego z dodatków",
    HideRewardAd: "Ukryj reklamy z nagrodą",
    HideRewardAdDesc:
        "Wszystkie reklamy w grze są opcjonalnymi reklamami z nagrodą. Spowoduje to ukrycie wszystkich opcji reklam z nagrodą w grze.",
    HideDiscordBanner: "Ukryj baner z Discorda",
    HideDiscordBannerDesc: "Ukryj Discord i baner sklepu w centrali",
    HideChat: "Ukryj wiadomość czatu",
    PurchaseFailed: "Zakup nie został ukończony",
    PurchaseSteamContinue: "Dokończ zakup na Steam",
    PurchaseSuccess: "Zakup został zakończony, dziękujemy za wsparcie",
    PrestigeCurrency: "Szwajcarskie pieniądze 💵",
    RestartDesc: "💡 Chcesz tylko zrestartować? Możesz dotknąć opcji Zacznij w nowym mieście powyżej i wybrać swoje obecne miasto",
    PrestigeGoBack: "Wróć",
    ProductionMultiplier: "Mnożnik produkcji",
    ProductionMultiplierDesc:
        "Zwiększenie zdolności produkcyjnej wszystkich budynków (w tym kopalń, fabryk, elektrowni, budynków naukowych i kulturalnych)",
    FuelCostDiscount: "Zniżka na koszty paliwa",
    FuelCostDiscountDesc: "Daje zniżkę na koszt paliwa przy transporcie surowców",
    AutoSellCapacityMultiplier: "Mnożnik zdolności sprzedaży automatycznej",
    AutoSellCapacityMultiplierDesc:
        "Mnożnik stosowany do zdolności automatycznej sprzedaży niezależnie od aktualnej zdolności",
    BuildingPermitCostDivider: "Dzielnik kosztów pozwoleń  na budowę",
    BuildingPermitCostDividerDesc: "Podziel koszt pozwoleń na budowę przez ten dzielnik",
    ExtraAdjacentBonus: "Dodatkowe sąsiednie bonusy",
    ExtraAdjacentBonusDesc: "Dodatkowa pojemność dla każdego sąsiedniego, działającego budynku tego samego typu",
    PrestigeAlertTitle: "Jesteś pewny?",
    PrestigeAlertContent:
        "Twoja firma zostanie zlikwidowana. Zarobisz %{amount} Szwajcarskich pieniędzy i możesz założyć nową firme w %{city}",
    PrestigeCurrencyDesc:
        "To są pieniądze na Twoim tajnym szwajcarskim koncie bankowym, możesz je nosić przy sobie, gdy zaczynasz w nowym mieście",
    Prestige: "środki pieniężne w",
    Cancel: "Anuluj",
    SaveFileCorrupted: "Zapisz plik uszkodzony",
    LoadGameError: "Nie udało się załadować gry",
    LoadGameErrorMessage: "Komunikat o błędzie: %{message}",
    LoadGameErrorDesc: "Proszę sprawdzić swoje połączenie z internetem. Jeśli problem będzie się powtarzał, skontaktuj się z pomocą techniczną",
    ExpansionPackIncompatible:
        "Importujesz zapis z dodatkami, ale twoja gra nie ma wymaganych dodatków",
    CashIn: "Środki pieniężne w",
    CurrentCity: "Obecne miasto",
    CashInDesc:
        "Kwotę tę otrzymasz na swoje szwajcarskie konto bankowe, jeśli zaczniesz w nowym mieście. Opiera się na kapitalizacji rynkowej Twojej firmy i musi osiągnąć %{amount} zanim będziesz mógł zarobić szwajcarskie pieniądze",
    CitySize: "Rozmiar mapy",
    GridType: "Typ siatki",
    StartInThisCity: "Zacząć w %{city}",
    CityBonus: "Bonus miejski",
    ResourceTilePercentage: "Płytki zasobów",
    MapSquareGrid: "Square ",
    MapHexGrid: "Hex",
    Stockholm: "Sztokholm",
    Rotterdam: "Rotterdam",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Fabryki Zeppelin są odblokowane</li><li>Fabryki półprzewodników mają 2x więcej produktywność</li><li>Stocznie mają 2x więcej pojemność</li><li>Fabryki samochodów mają 2x więcej pojemnośćy</li><li>Fabryki akumulatorów litowo-jonowych są odblokowane</li>",
    Toulouse: "Toulouse",
    Rome: "Rzym",
    RomeBonus:
        "<li>Kolosea są odblokowane</li><li>Kolosea mają 2x więcej produktywność</li><li>Zacznij od centrum polityki poziomu 5</li><li>Opery mają 2x więcej pojemnośćy</li><li>Studia nagraniowe również produkują kulturę</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Zacznij od laboratorium badawczego poziomu 5</li><li>Politechniki są odblokowane</li><li>Politechniki mają 2x więcej pojemność</li><li>Szkoły mają 2x więcej pojemność</li><li>Uczelnie mają 2x więcej produktywność </li>",
    HideNotProducing: "Ukryj zasoby, które nie są produkowane",
    SortByStorage: "Magazyn",
    SortByName: "Nazwa",
    PlayerTrade: "Handel z graczami",
    AddTradeFail: "Nie udało się dodać Twojej transakcji",
    AddTradeExceedMaximumTrade:
        "Możesz mieć tylko maksimum %{number} aktywne transakcje,najpierw odbierz lub anuluj jedną z nich",
    AddTradeSuccess: "Twoja transakcja została pomyślnie dodana",
    ClaimTradeFail: "Nie udało się odebrać  tej transakcji, spróbuj ponownie później",
    CancelTradeSuccess: "Twoja transakcja została pomyślnie anulowana",
    CancelTradeFail: "Nie udało się anulować tej transakcji, spróbuj ponownie później",
    AcceptTradeFail: "Nie udało się zaakceptować tej transakcji, spróbuj ponownie później",
    PlayerTradeBanner: "Handluj zasobami z innymi graczami",
    PlayerTradeResource: "Surowce",
    PlayerTradeAmount: "Kwota",
    PlayerTradePrice: "Cena $",
    PlayerTradeValue: "Wartość $",
    PlayerTradeWaiting: "Czekanie...",
    AddTrade: "Dodaj handel",
    AcceptTrade: "Zaakceptować",
    CancelTrade: "Anuluj",
    ClaimTrade: "Odbierz",
    PasteYourSave: "Proszę wkleić zapisane dane",
    FailedToImportSave: "Nie udało się zaimportować Zapisz",
    FailedToImportSaveDesc: "Twój plik zapisu jest niezgodny lub uszkodzony: %{error}",
    SaveCopiedToClipboard: "Twoje dane zapisu zostały skopiowane do schowka",
    CancelActiveTradeFirst: "Masz aktywne transakcje gracza, najpierw je anuluj lub odbierz",
    PlayerTradeQuotaExceed: "Ta transakcja przekroczyła Twój limit",
    PlayerTradeValidRange: "Zakres: %{min} ~ %{max}",
    PlayerTradeQuota: "Pozostały limit: %{value}",
    PlayerTradeUnavailable:
        "Musisz mieć co najmniej jeden surowiec w produkcji i magazynie, zanim będziesz mógł handlować z graczami",
    PlayerTradeToClaim: "Ty masz %{num} nowych transakcj ubieganych  się o wymianę z graczami",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Przechowuj nadwyżkę mocy i zapewnij zasilanie podczas niedoboru",
    WarehouseBuildDesc: "Transportuj i przechowuj dowolne zasoby przy niższych kosztach zużycia  paliwa",
    PowerBankChargeSpeed: "Szybkość ładowania",
    PowerBankPowerLeft: "Pozostało mocy",
    PowerBankMoreCapacity: "Oszczędzanie Bateri",
    PowerBankMoreCapacityDesc: "Power banki ładują się z 50% szybkości, ale mają o 50% większą pojemność",
    PowerBankNotWorking: "⛔ Power banki działają tylko obok elektrowni",
    ColorTheme: "Motywy kolorystyczne",
    ColorThemeDesc: "Motyw kolorystyczny dla ikon gry, podświetlenia, siatki i tła. WYMAGA PONOWNEGO ZAŁADOWANIA",
    SiliconMine2xOutput: "Dolina Krzemowa",
    SiliconMine2xOutputDesc:
        "Kopalnie krzemu produkują 2x więcej  krzemu, ale zużywają o 50% więcej energii, a transport krzemu kosztuje 50% więcej paliwa",
    CoalMine2xOutput: "Rewolucja przemysłowa",
    CoalMine2xOutputDesc: "Kopalnie węgla produkują 2x więcej węgla, ale zużywają o 50% więcej energii, a transport węgla kosztuje o 50% więcej paliwa",
    AlMine2xOutput: "Wytop aluminium",
    AlMine2xOutputDesc: "Kopalnie aluminium produkują 2x więcej aluminium i zużywają 2x więcej mocy",
    LoggingCamp2xOutput: "Wylesianie",
    LoggingCamp2xOutputDesc: "Obozy drwali produkują 2x więcej drewna, a transport drewna kosztuje 2x więcej paliwa",
    PowerBankLeft: "Power Bank",
    ColorThemeEditor: "Edytor motywów kolorystycznych",
    ColorThemeEditorDesc: "Możesz zastąpić kolory w bieżącym motywie kolorystycznym. Obecnie masz %{num} nadpisuje",
    ColorThemeEditorSave: "Zapisać",
    ColorThemeEditorReset: "Resetowanie",
    ColorThemeEditorResetAll: "Zresetować wszystko",
    NewMessageMentions: "Nowa wiadomość wspomina o Tobie: %{message}",
    HideChatMentions: "Ukryj wzmianki na czacie",
    HideChatMentionsDesc: "Ukryj powiadomienie dźwiękowe i toastowe, gdy w czacie pojawia się wzmianka o mnie,",
    AcceptTradeFailRateLimit: "Możesz zaakceptować tylko jedną transakcję co %{time} sekund",
    DowngradeBuilding: "Obniżenie poziomu",
    WarehouseInputRoutes: "Trasy wejściowe",
    WarehouseAddInput: "Dodaj trasę",
    WarehouseTapToSelect: "Stuknij w wybraną mapę...",
    WarehouseFindOnMap: "🔍 Znajdź na mapie",
    WarehouseRemoveRoute: "Usunąć",
    WarehouseAddRouteFail: "Nie udało się dodać trasy: wybrany kafelek nie jest prawidłowym źródłem",
    LevelN: "Poziom %{level}",
    Surplus: "Nadwyżka",
    Production: "Produkcja",
    Consumption: "Konsumpcja",
    WarehouseInputCapacityDescV2: "Całkowita pojemność transportu wewnętrznego, podzielona równo na wszystkie trasy",
    WarehouseInputCapacityPerRoute: "Na trasę: ",
    PlayerCountryFlag: "Flaga gracza",
    PlayerCountryChooseFlag: "Ułożone W porządku alfabetycznym kodu kraju",
    WindTurbineAlwaysWork: "Wiatr się wzmaga",
    WindTurbineAlwaysWorkDesc: "Turbiny wiatrowe pracują przez 100% czasu, ale wytwarzają o 30% mniej energii",
    BookPublisherScience: "Literatura naukowa",
    BookPublisherScienceDesc: "Wydawcy książek produkują naukę zamiast kultury",
    ImportSaveVersionTooNew:
        "Importujesz zapis z %{saveVersion} ale twoja gra jest %{gameVersion}. Najpierw uaktualnij swoją grę",
    BatteryFuelEconomy: "Bateria do ponownego ładowania",
    BatteryFuelEconomyDesc: "Zużycie paliwa w akumulatorze poprawia się o 100% (50% kosztów paliwa)",
    ShowTheoreticalInputOutputCapacity: "Pokaż teoretyczną pojemność wejściową/wyjściową",
    SpecialTransportCost: "Zasoby ze specjalnym kosztem transportu",
    FreeTransportCost: "Zasoby z bezpłatnym kosztem transportu",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Zasoby zwykle pojawiają się w klastrach</li><li>Magazyny zapewniają 50% więcej oszczędności paliwa</li><li>Unikalny budynek: wydawca mangi</li><li>Unikalny budynek: studio anime</li><li>Fabryki półprzewodników mają 2x więcej produktywność</li><li>Fabryki akumulatorów litowo-jonowych mają 2x więcej pojemność</li><li>Fabryki baterii są odblokowane</li><li>Fabryki akumulatorów mają 2x więcej pojemność</li><li>Zużycie paliwa w akumulatorze poprawia się o 100%</li><li>Fabryki akumulatorów nie wymagają węgla</li><li>Zacznij od baterii 100K</li>",
    HideChatDescV2: "Ukryj wiadomość czatu na dolnym pasku narzędzi. Wyświetlając wiadomości na czacie, zgadzasz się na nasze ",
    HideChatDescV2ToS: "Warunki usługi",
    IntegratedCircuitFab: "Układ scalony Fab",
    MangaPublisher: "Wydawca mangi",
    Manga: "Manga",
    AnimeStudio: "Studio anime",
    Anime: "Anime",
    PlayerTradeAction: "Akcja",
    PlayerTradeBuy: "Kup",
    PlayerTradeSell: "Sprzedać",
    PlayerTradeBid: "Oferta",
    PlayerTradeAsk: "Zapytać się",
    ClaimTradeSuccessV2: "Twoja transakcja została pomyślnie potwierdzona: %{cashOrResource}",
    AcceptTradeSuccessV2: "Ten handel został przez Ciebie zaakceptowany: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Lepsza niż cena rynkowa",
    ResourceExplorer: "Eksplorator zasobów",
    ResourceExplorerDesc: "Pozwalają wydobywać zasoby z pustego kafelka mapy",
    ResourceExplorerDescLong: "💡 Odkrywcy zasobów nie mają sąsiedniego bonusu. Zużycie energii różni się w zależności od zasobu",
    ResourceExplorerSelectResource: "Badać",
    ProductionSettings: "Ustawienia produkcji",
    PlayerTradePartialFillTitle: "Wybierz procent wypełnienia",
    PlayerTradeAmountNotValidV2: "Minimalna dozwolona kwota transakcji to 1",
    PlayerTradeOptOut: "Zrezygnowałeś z tabeli liderów, nie możesz handlować z innymi graczami",
    FirstTimeReadGuide: "💡 Potrzebujesz trochę pomocy, jak grać? Dotknij, aby przeczytać przewodnik dla początkujących!",
    ReadSteamGuideV2: "Przewodnik Gry",
    ReadSteamGuideV2Desc: "Możesz czytać poradniki stworzone przez społeczność na Steamie - możesz też tworzyć własne",
    ChatMessageTooLong: "Twoja wiadomość na czacie przekracza maksymalną dozwoloną liczbę znaków",
    ChatPlaceholderV2: "Wpisz swoją wiadomość: max %{length} znaki",
    ProfitBreakdownOutput: "%{res} Wyjście",
    ProfitBreakdownInput: "%{res} Wejście",
    ProfitBreakdownFuel: "Koszt paliwa",
    BuildingProfit: "Zysk",
    RestoreBackup: "Przywrócić",
    SteamLogin: "Zaloguj się przez Steam",
    SteamLoginDialogDesc:
       "Twój lokalny zapis ma włączony Expansion Pack, musisz zalogować się przez Steam, aby kontynuować. Możesz też USUNĄĆ LOKALNY ZAPIS i zacząć od nowa",
    SteamLoginDesc: "Jeśli posiadasz dodatki na Steam, możesz grać z dodatkami w sieci po zalogowaniu",
    SteamLoginYes: "Zaloguj",
    SteamLoginNo: "Wymaż i zacznij od nowa",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Międzynarodowy handel eksportowy",
    FreeTransportToTradeCenterDesc:
        "Transport do Centrum Handlowego nie kosztuje paliwa, ale transport z Centrum Handlowego kosztuje 50% więcej paliwa",
    TaiChi10xCulture: "Perła Orientu",
    PlayerTradeYouHave: "W magazynie: %{amount}",
    PlayerTradeFillValue: "Wartość",
    FiberFactory: "Fabryka włókien",
    Fiber: "włókno",
    Achievements: "Osiągnięcia",
    AchievementsDesc: "Osiągnąłeś %{number} z %{total} osiągnięć",
    AchievementsReward: "Nagroda: szwajcarskie pieniądze +%{swiss}",
    AchievementsRewardToast: "Odebrałeś nagrodę: Szwajcarskie pieniądze +%{swiss}",
    AchievementsClaim: "Odbierz",
    AchievementsToast: "Osiągnąłeś %{name}, odbierz nagrodę w Kwaterze Głównej",
    AchievementStockholm100: "Nowicjusz Wiking",
    AchievementStockholm100Desc: "Zarób 100 szwajcarskich pieniędzy w Sztokholmie w jednym biegu",
    AchievementStockholm500: "Absolwent Wikingów",
    AchievementStockholm500Desc: "Zarób 500 szwajcarskich pieniędzy w Sztokholmie w jednym biegu",
    AchievementStockholm1000: "Doświadczony wiking",
    AchievementStockholm1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Sztokholmie w jednym biegu",
    AchievementOslo100: "Norweski hobbysta olejowy",
    AchievementOslo100Desc: "Zarób 100 szwajcarskich pieniędzy w Oslo w jednym biegu",
    AchievementOslo500: "Norweski entuzjasta ropy",
    AchievementOslo500Desc: "Zarób 500 szwajcarskich pieniędzy w Oslo w jednym biegu",
    AchievementOslo1000: "Norweski potentat naftowy",
    AchievementOslo1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Oslo w jednym biegu",
    AchievementRotterdam100: "Właściciel Wiatraczka",
    AchievementRotterdam100Desc: "Zarób 100 szwajcarskich pieniędzy w Rotterdamie w jednym biegu",
    AchievementRotterdam500: "Właściciel wiatraka",
    AchievementRotterdam500Desc: "Zarób 500 szwajcarskich pieniędzy w Rotterdamie w jednym biegu",
    AchievementRotterdam1000: "Właściciel turbiny wiatrowej",
    AchievementRotterdam1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Rotterdamie w jednym biegu",
    AchievementDetroit100: "Lokalny dealer samochodowy",
    AchievementDetroit100Desc: "Zarób 100 szwajcarskich pieniędzy w Detroit w jednym biegu",
    AchievementDetroit500: "Regionalny Dystrybutor Samochodów",
    AchievementDetroit500Desc: "Zarób 500 szwajcarskich pieniędzy w Detroit w jednym biegu",
    AchievementDetroit1000: "Narodowy monopol samochodowy",
    AchievementDetroit1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Detroit w jednym biegu",
    AchievementBoston100: "Licencjat Zarabiania Pieniędzy",
    AchievementBoston100Desc: "Zarób 100 szwajcarskich pieniędzy w Bostonie w jednym biegu",
    AchievementBoston500: "Mistrz zdobywania pieniędzy",
    AchievementBoston500Desc: "Zarób 500 szwajcarskich pieniędzy w Bostonie w jednym biegu",
    AchievementBoston1000: "Doktorat z drukowania pieniędzy",
    AchievementBoston1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Bostonie w jednym biegu",
    AchievementRome100: "Dioklecjan",
    AchievementRome100Desc: "Zarób 100 szwajcarskich pieniędzy w Rzymie w jednym biegu",
    AchievementRome500: "Konstantyn Wielki",
    AchievementRome500Desc: "Zarób 500 szwajcarskich pieniędzy w Rzymie w jednym biegu",
    AchievementRome1000: "Cezar August",
    AchievementRome1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Rzymie w jednym biegu",
    AchievementHamburg100: "Niemcy",
    AchievementHamburg100Desc: "Zarób 100 szwajcarskich pieniędzy w Hamburgu w jednym biegu",
    AchievementHamburg500: "Ojczyzna",
    AchievementHamburg500Desc: "Zarób 500 szwajcarskich pieniędzy w Hamburgu w jednym biegu",
    AchievementHamburg1000: "Hrabia Zeppelin",
    AchievementHamburg1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Hamburgu w jednym biegu",
    AchievementToulouse100: "Odrzutowiec A310",
    AchievementToulouse100Desc: "Zarób 100 szwajcarskich pieniędzy w Tuluzie w jednym biegu",
    AchievementToulouse500: "Odrzutowiec A330",
    AchievementToulouse500Desc: "Zarób 500 szwajcarskich pieniędzy w Tuluzie w jednym biegu",
    AchievementToulouse1000: "Odrzutowiec A380",
    AchievementToulouse1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Tuluzie w jednym biegu",
    AchievementHongKong100: "Hobbysta handlarz",
    AchievementHongKong100Desc: "Zarób 100 szwajcarskich pieniędzy w Hongkongu w jednym biegu",
    AchievementHongKong500: "Profesjonalny Broker",
    AchievementHongKong500Desc: "Zarób 500 szwajcarskich pieniędzy w Hongkongu w jednym biegu",
    AchievementHongKong1000: "Zarządzający funduszem hedgingowym",
    AchievementHongKong1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Hongkongu w jednym biegu",
    AchievementStPetersburg100: "Wielki Książę",
    AchievementStPetersburg100Desc: "Zarób 100 szwajcarskich pieniędzy w Petersburgu w jednym biegu",
    AchievementStPetersburg500: "Carewicze",
    AchievementStPetersburg500Desc: "Zarób 500 szwajcarskich pieniędzy w Petersburgu w jednym biegu",
    AchievementStPetersburg1000: "Car Wszechrusi",
    AchievementStPetersburg1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Petersburgu w jednym biegu",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Zarób 100 szwajcarskich pieniędzy w Osace w jednym biegu",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Zarób 500 szwajcarskich pieniędzy w Osace w jednym biegu",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Osace w jednym biegu",
    SteamAutoCloudBackup: "Automatyczna kopia zapasowa Steam Cloud",
    SteamAutoCloudBackupFailed: "Automatyczna kopia zapasowa Steam Cloud nie powiodła się: %{error}",
    SteamManualBackup: "Wymuś kopię zapasową Steam Cloud",
    UILoading: "Ładowanie...",
    UserAuthenticated: "Jesteś uwierzytelniony",
    BuildingResourceBreakdown: "Podział ilości bezczynności",
    SortByDeficit: "Deficyt",
    SortByRunOut: "Skończyć się",
    SocialNetworkInc: "Sieć społecznościowa Inc",
    SocialNetwork: "Sieć społeczna",
    DatabaseCompany: "Firma bazy danych",
    Database: "Baza danych",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Fabryka lotniskowców",
    AircraftCarrier: "Lotniskowiec",
    MapExclusive: "Ekskluzywna mapa",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Fabryki samochodów używają baterii zamiast benzyny i wymagają tylko 50% kwoty",
    HongKongBonusV2:
        "<li>Unikalny algorytm wyceny rynkowej - ceny i notowania akcji podążają za normalnym rozkładem (krzywa dzwonowa)</li><li>Aktualizacje rynku i resety kwot handlowych są dwa razy częstsze (co godzinę)</li><li>Badania można odblokować za pośrednictwem wymienianych zasobów</li><li>Unikalny budynek: Kung-Fu Dojo</li><li>Unikalny budynek: Tai-Chi Dojo</li><li>50% wzrost maksymalnej liczby dozwolonych transakcji aktywnych graczy</li><li>Zacznij od 1 dodatkowej współbieżności sprzedaży samochodów</li><li>Unikalna polityka: Międzynarodowy handel eksportowy</li><li>Unikalna polityka: Perła Orientu</li><li>Centrum Hurtowe potrzebuje tylko 4 zasobów do odblokowania</li><li>Zacznij od 100 mln gotówki</li>",
    TaiChi10xCultureDescV2:
        "Bezpłatny transport Kung-fu i Tai-chi. Studia filmowe mają 2x więcej  pojemność, ale zużywają o 50% więcej mocy",
    SettingsFullScreen: "Pełny ekran",
    SettingsFullScreenDesc: "Uruchom grę w trybie pełnoekranowym. Dostępne tylko dla wersji Steam",
    LeaderboardByAllPrestigeCurrency: "Zarobione szwajcarskie pieniądze przez cały czas",
    LeaderboardByCash: "Aktualna gotówka pod ręką",
    LeaderboardTotalValuation: "Całkowita wycena",
    LeaderboardDescV2: "Zobacz, gdzie są najlepsi gracze",
    LastUpdatedAt: "Ostatnia aktualizacja w",
    DetroitBonusV3:
        "<li>Fabryki silników są odblokowane</li><li>Fabryki silników mają 2x więcej wydajność</li><li>Fabryki samochodów mają 2x więcej pojemność</li><li>Fabryki samochodów używają gazu zamiast benzyny</li><li>Bezpłatny transport samochodowy</li><li>Polityka Nikoli Tesli jest bezpłatna</li><li>Fabryki pociągów mają 2x więcej  pojemność</li>",
    SaveAndExit: "Zapisz i wyjdź z gry",
    SaveAndExitDesc:
        "Zapisz i wyjdź z gry. Jest to dostępne tylko w wersji Steam i działa tak samo jak przycisk zamykania na pasku okna",
    AutoSellResourceWarningShortLabel: "💡Sprzedaż samochodów",
    AutoSellResourceWarningDesc:
        "Automatycznie sprzedajesz ten surowiec, nie możesz tutaj wykorzystać kwoty przechowywanej w Trade Center",
    PlayerTradeLocalPrice: "Cena lokalna: %{price}",
    ChatForceScroll: "Wymuś przewijanie",
    ChatForceScrollDesc:
        "Jeśli wymuszone przewijanie jest włączone, czat będzie przewijany po pojawieniu się nowej wiadomości. W przeciwnym razie będzie się przewijać tylko wtedy, gdy jesteś już na dole",
    ResourceExplorer2: "Eksplorator zasobów 2.0",
    ConstructionCancel: "Anuluj",
    PolicyBlueprint: "Projekt",
    PolicyBlueprintDesc:
        "Budowa budynku nie rozpocznie się automatycznie - trzeba ją uruchomić ręcznie",
    HighlightUnderConstruction: "...które nie zostały skonstruowane",
    HighlightUnderLevel10: "...które są poniżej poziomu 10",
    HighlightUnderLevel20: "...które są poniżej poziomu 20",
    HighlightUnderLevel30: "...które są poniżej poziomu 30",
    Logout: "Jesteś wylogowany",
    ConstructionStatusQueueingV2: "Kolejkowanie",
    ConstructionStatusPausedV2: "Wstrzymane",
    ConstructionStatusBuildingV2: "Budynek",
    ConstructionStatusUnpaidV2: "Nie zapłacony",
    ConstructionStatus: "Stan budowy",
    ConstructionStart: "Rozpoczęcie",
    CostFree: "Bezpłatny",
    PlaceBlueprint: "Umieszczenie planu budynku jest bezpłatne",
    PlayerTradePriceNotValidV2: "Cena handlowa musi być pomiędzy %{min} oraz %{max}",
    MarketNews: "Wiadomości rynkowe",
    MarketNewsApplyToYou: "Tylko ty",
    MarketNewsApplyToGlobal: "Światowy",
    MarketNewsHighlightAffected: "🔍 Atrakcja",
    MarketNewsFilterInput: "Wszystkie %{res} Wejście ",
    MarketNewsFilterOutput: "Wszystkie %{res} wyjście ",
    MarketNewsFilterBoth: "Wszystkie %{res} wejście i wyjście ",
    MarketNewsIncrease: "zwiększona o %{percent}",
    MarketNewsDecrease: "zmniejszyła się o %{percent}",
    MarketNewsBuilding: "Na ten budynek ma wpływ %{num} Aktualności",
    StockholmBonusV2:
        "<li>Unikalny budynek: producent muzyczny</li><li>Obozy drwali mają 2x więcej wyjścia</li><li>Papiernie są odblokowane</li><li>Odlewnie obiegowe mają 2x więcej wydajność</li><li>Polityka dotycząca literatury naukowej jest bezpłatna</li>",
    FreeOilTransportV2: "Elektryczny transport oleju",
    Tutorial4P1:
        "Transport surowców kosztuje paliwo. Istnieje kilka rodzajów paliwa, z których obecnie korzystasz <em>benzyna⛽</em> jako paliwo. Masz <em>Rafinerie ropy</em> która transportuje ropę z szybu naftowego i produkuje benzynę.<br><br>Malutki ruch <em>dots</em> reprezentują przepływ zasobów w czasie rzeczywistym.Powinieneś zoptymalizować lokalizacje swoich budynków, aby zminimalizować odległość podróży.<br><br><em>Ulepszenie</em> Twoich budynków zwiększa swoją wydajność , ale także zwiększa zużycie energi i wymagane nakłady.",
    Tutorial4P2:
        "Możesz zmienić rodzaj paliwa w <em>dziale logistyki🚦</em> - na tej mapie możesz również użyć <em>gazu ziemnego</em> jako paliwa.<br><br>Dział logistyki pokazuje również Twoje trasy transportowe, które spalają najwięcej paliwa - będziesz chciał mieć na to oko.<br><br>Pamiętaj by <em>upewnić się, że produkcja paliwa jest wyższa niż zużycie</em> w przeciwnym razie Twoja produkcja zostanie wstrzymana, gdy skończy Ci się paliwo.<br><br>Jeśli tak się stanie, nie martw się, możesz kupić paliwo awaryjne w centrum handlowym lub od innych graczy.",
    Tutorial5P2:
        "<em>Biuro Statystyczne📊</em> zapewnia dobry przegląd Twojej produkcji. Możesz zobaczyć szczegółowy podział danych wejściowych i wyjściowych zasobów.<br><br>Istnieje również wiele przydatnych wykresów📈 -będziesz chciał się do nich odnieść, gdy równoważysz swoją produkcję.<br></br>Twoja<em>gotówka💰, nadwyżka mocy ⚡i nadwyżka paliwa⛽</em> Liczby które również są wyświetlane w lewym górnym rogu - jeśli któryś z nich zmieni kolor na czerwony, należy sprawdzić, co się dzieje.",
    MusicProducer: "Producent muzyczny",
    PlasticFiber: "Plastikowe włókno",
    PlasticFiberDesc: "Fabryki włókien zużywają o 50% więcej tworzyw sztucznych, ale o 50% mniej szkła",
    NewsEffectx2: "Konferencja prasowa",
    NewsEffectx2Desc: "Podwaja się efekt wiadomości rynkowych – zarówno pozytywnych, jak i negatywnych",
    SellRefundPercentage: "Zwrot kosztów sprzedaży/obniżenia ulepszenia",
    SellRefundPercentageDesc:
        "Jeśli sprzedasz lub obniżysz poziom budynku, jest to procent pieniędzy i zasobów, który otrzymujesz z powrotem",
    SellBuildingDescV2:
        "Sprzedaż budynku zwróci Ci pieniądze %{percent} Twojej inwestycji i %{percent} surowców zostanie przetransportowanych do Centrum Handlowego",
    BuilderMoveSpeed: "Szybkość ruchu budowniczego",
    BuilderMoveSpeedDesc: "Szybkość, jaką poruszają się budowniczowie, aby wznosić budynki",
    EBookInc: "eBook Inc",
    ResourceBooster: "Wzmacniacz zasobów",
    BuildWarningTitle: "Budynek może nie działać",
    BuildWarningTitleDesc: "%{reason}. Czy na pewno będziesz budować na tym kafelku??",
    BuildWarningBuildAnyway: "Buduj mimo to",
    ResourceBoosterNotWorking: "⛔ Wzmacniacze surowców działają tylko obok kopalni złóż",
    ResourceBoosterBuildings: "Wzmacnianie budynków",
    BuildingResourceConversion: "%{resource} Konwersja",
    AllTimeSwissMoneyEarned: "Zarobione szwajcarskie pieniądze przez cały czas: %{number}",
    BuildingUpgradeCostDivider: "Dzielnik kosztów modernizacji budynku",
    AchievementSoftwareGiant: "Gigant oprogramowania",
    AchievementSoftwareGiantDesc:
        "Zbuduj na tej samej mapie firmę programistyczną poziomu 10, firmę zajmującą się systemami operacyjnymi poziomu 10, firmę z bazą danych  poziomu 10 i przeglądarkę internetową poziomu 10",
    AchievementSpaceRace: "Kosmiczny wyścig",
    AchievementSpaceRaceDesc:
        "Zbuduj fabrykę rakiet poziomu 10, fabrykę satelitów poziomu 10, fabrykę statków kosmicznych poziomu 10 i fabrykę stacji kosmicznych poziomu 10 na tej samej mapie",
    AchievementToTheMoon: "Na Księżyc",
    AchievementToTheMoonDesc:
        "Zbuduj farmę bitcoinów na poziomie 40 i farmę Dogecoin na poziomie 40. Posiadaj 1B Bitcoin i 1B Dogecoin",
    ItsAllGreen: "Wszystko jest zielone",
    ItsAllGreenDesc: "Posiadaj 50 linii produkcyjnych i żadnego deficytu produkcyjnego",
    DeepInRed: "Głęboko w czerwieni",
    DeepInRedDesc: "Posiadaj 50 linii produkcyjnych, które mają deficyt produkcji",
    UseScientificNotation: "Użyj notacji naukowej",
    UseScientificNotationDesc: "Użyj notacji naukowej (notacji e) dla liczb większych niż 999,9T",
    LogoutDescV2:
        "Zalogowałeś się na innym urządzeniu, to urządzenie jest wylogowane. Możesz się ponownie zalogować, ale drugie urządzenie zostanie wylogowane",
    LogBackIn: "Zaloguj się ponownie",
    PlayerTradeNowAllowedV2: "Transakcje graczy nie są dostępne w ciągu %{hour} godzin od przywrócenia/zaimportowania zapisu",
    ServerDisconnected:
        "Nie masz połączenia z serwerem, sprawdź połączenie z internetem i spróbój ponownie",
    BuildingUpgradeCostDividerDescV2: "Podziel koszt ulepszenia budynku przez ten dzielnik",
    ResourceBoosterDesc: "Zwiększ wydajność sąsiednich kopalń",
    BlockUserChatTitle: "Blok %{user}",
    BlockUserChatAction: "Blok",
    BlockUserChatDesc:
        "Blokada będzie obowiązywać podczas tej sesji gry i nie można tego cofnąć, chyba że ponownie uruchomisz grę",
    ChangeNameCooldown: "Możesz zmienić swoje imię tylko raz na raz %{hour} godzin",
    AtomicBombFactory: "Fabryka bomb atomowych",
    AtomicBomb: "Bomba atomowa",
    DynamiteFactory: "Fabryka dynamitu",
    Dynamite: "Dynamit",
    NuclearMissileFactory: "Fabryka rakiet jądrowych",
    NuclearMissile: "Pocisk jądrowy",
    LiquidPropellantFactory: "Fabryka ciekłych paliw",
    GasPropellantFactory: "Fabryka Propelentów Gazowych",
    Propellant: "Gaz pędny",
    ProjectV2: "Projekt V-2",
    ICBMFactory: "Fabryka ICBM",
    ICBM: "ICBM",
    RadarFactory: "Fabryka radarów",
    Radar: "Radar",
    SpaceForceCommand: "Dowództwo Sił Kosmicznych",
    SpaceForce: "Siła Kosmicznae",
    SteamAutoCloudBackupDescV2:
        "Twoje najnowsze postępy są zapisywane w Steam Cloud i synchronizowane na różnych urządzeniach. Gra automatycznie tworzy kopię zapasową zapisanych stanów gry co 10 minut w Steam Cloud. W każdej chwili możesz wymusić wykonanie kopii zapasowej",
    SpaceColony: "Kosmiczna Kolonia",
    SpaceColonyInc: "Kosmiczna Kolonia Inc",
    ProjectVostok: "Projekt Wostok",
    AdjacentBonusSquare: "Przyległy plac bonusowy",
    AdjacentBonusSquareDesc: "Sąsiednia premia jest o 50% skuteczniejsza, ale modyfikatory płytek skalują się od -15% do +15%",
    ResourceBoosterSquare: "Plac Wzmacniacza Zasobów",
    ResourceBoosterSquareDesc:
        "Wzmacniacze zasobów zapewniają 25% więcej wzmocnienia, ale ich wkład naukowy i zużycie energii również wzrastają o 25%",
    SteelMillx2: "Modernizacja Pieca Stalowego",
    SteelMillx2Desc: "Stalownie i zakłady ze stali nierdzewnej mają 2x lepszą wydajność, ale zużywają 2x więcej  mocy",
    FuelDynamite: "Dynamitowego Paliwa",
    FuelDynamiteDesc: "Fabryki dynamitu wykorzystują twoje obecne paliwo zamiast oleju",
    StPetersburgBonusV2:
        "<li>Kopalnie uranu mają 2x lepszą  wydajność</li><li>Instalacje wzbogacania uranu mają 2x lepszą  wydajność</li><li>Transport uranu kosztuje 50% mniej paliwa</li><li>Darmowy transport broni</li><li>Projekt Vostok ma 2x większą pojemność</li>",
    ToulouseBonusV2:
        "<li>Kopalnie tytanu mają 2x lepszą  wydajność</li><li>Zakłady wzbogacania uranu mają 2x lepszą  wydajność</li><li>Fabryki silników odrzutowych mają 2x lepszą wydajność</li><li>Fabryki samolotów mają 2x lepszą wydajność</li><li> Fabryki rakiet mają 2x większą pojemność</li>",
    BuildingPermitsNeededDesc: "Ten budynek nie działa, ponieważ nie masz wystarczających pozwoleń na budowę",
    BuildingPermitsNeeded: "Potrzebne pozwolenia na budowę",
    BuyMissingPermits: "Kup brakujące pozwolenia",
    GPUIsBusy: "Twój procesor graficzny jest zajęty",
    GPUIsBusyDesc:
        "Twój system operacyjny wstrzymał grafikę gry, ponieważ GPU jest zajęty innymi zadaniami. Możesz ponownie załadować grę, aby wznowić. Jeśli to nie zadziała, spróbuj ponownie uruchomić grę",
    SaveAndReloadGame: "Zapisz i odśwież grę",
    ResearchLabCultureInput: "Renesans",
    ResearchLabCultureInputDesc: "Laboratorium Badawcze ma dwukrotnie większą pojemność, ale wykorzystuje kulturę jako dodatkowy wkład",
    GasPumpx2Output: "Pompa gazowa wysokiego ciśnienia",
    GasPumpx2OutputDesc: "Pompy gazu ziemnego mają 2x więcej  mocy, ale zużywają 2x więcej mocy",
    LeaderboardValuationPerHour: "Całkowita wycena na godzinę",
    LeaderboardValuationPerHourPerSwiss: "Całkowita wycena na godzinę na szwajcary",
    LeaderboardValuationPerHourNewPlayers: "Całkowita wycena na godzinę (< 1000 szwajcarski)",
    LeaderboardValuationPerBuilding: "Wycena budynku na budynek",
    BuildingCustomColor: "Kolor budynku",
    BuildingCustomColorReset: "Resetowanie",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Każde 4 różne typy budynków dają 1 bezpłatne pozwolenie na budowę</li> <li>Unikalna polityka: Dywersyfikacja produkcji</li><li>Unikalny budynek: Fabryka syropu klonowego</li><li>Bezpłatny transport syropu klonowego</li ><li>Unikalny rodzaj paliwa: syrop klonowy</li><li>2x limit handlu dla graczy podczas handlu uranem i uranem wzbogaconym</li><li>Unikalna darmowa polityka: syrop z tworzywa sztucznego</li> <li>Fabryki zabawek 2x lepsza wydajność</li><li>Studia gier mają 2x większą  pojemność</li>",
    MapExtraPermitDesc: "Otrzymasz %{number} darmowych pozwoleń na budowę z unikalnego bonusu mapy",
    OsloBonusV3:
        "<li>Rafinerie ropy naftowej są odblokowane </li><li>Rafinerie ropy naftowej mają 2x lepszą  wydajność</li><li>Polityka transportu energii elektrycznej jest bezpłatna</li><li>Zakłady przetwarzania gazu mają 2x lepszą  wydajność</li> <li>Bezpłatny poziom 4 turbina wiatrowa x1</li><li>Bezpłatny poziom 8 szyb naftowego x1</li><li>Bezpłatny poziom 2 rafineria ropy naftowej x1</li><li>Bezpłatny poziom 2 pompa gazu ziemnego x1</li>",
    ResourceBoosterPercentageV2: "💡 Ta kwota obejmuje %{percent} doładowania z sąsiednich wzmacniaczy zasobów",
    MapleSyrup: "Syrop klonowy",
    MapleSyrupFactory: "Fabryka syropu klonowego",
    SyrupPlastic: "Syrop z tworzywa sztucznego",
    SyrupPlasticDesc: "Wszystkie budynki, do których trafiają tworzywa sztuczne, używają zamiast tego syropu klonowego",
    ResourceBoosterSupplyChain: "Wzmacniacz łańcucha dostaw",
    ResourceBoosterSupplyChainDesc:
        "Wzmacniacze surowców zużywają 2 razy więcej mocy i nauki, ale każda działająca kopalnia zwiększa wydajność, zapewnia również zwiększenie wydajności sąsiednim fabrykom, które zużywają produkcję kopalni (fabryka powinna zużywać tylko złoża)",
    ProductionDiversification: "Dywersyfikacja produkcji",
    ProductionDiversificationDesc: "Każdy inny typ budynku daje 1% dodatkowej pojemności wszystkim budynkom",
    ExtraPolicyPointsDescV2: "Centrum polis ma 2x więcej  zdolność konwersji punktów polisy",
    PowerRequired: "Wymagana moc",
    AchievementVancouver100: "Sprzedawca soków",
    AchievementVancouver100Desc: "Zarób 100 szwajcarskich pieniędzy w Vancouver w jednym biegu",
    AchievementVancouver500: "Syrop Savant",
    AchievementVancouver500Desc: "Zarób 500 szwajcarskich pieniędzy w Vancouver w jednym biegu",
    AchievementVancouver1000: "Zdobywca Canuck",
    AchievementVancouver1000Desc: "Zarób 1000 szwajcarskich pieniędzy w Vancouver w jednym biegu",
    BarbariansAtTheGate: "Barbarzyńcy przy bramie",
    BarbariansAtTheGateDesc: "Wykorzystaj limit handlowy gracza o wartości 1 biliona między aktualizacjami rynku",
    DiversifiedProductions: "Zróżnicowane produkcje",
    DiversifiedProductionsDesc: "Zbuduj 100 różnych typów budynków na jednej mapie",
    RealEstateTycoon: "Potentat nieruchomości",
    RealEstateTycoonDesc: "Posiadaj 400 budynków na jednej mapie",
    ResourceExplorer2DescV2:
        "Odkrywcy zasobów produkują 2x lepszą wydajność, ale zużywają 2x więcej  mocy. Eksploratorzy zasobów mogą zostać wzmocnieni przez wzmacniacze zasobów, jeśli polityka Wspomagania Łańcucha Dostaw jest aktywna, a wzmacniacz ma sąsiednią kopalnię o tej samej wydajności",
    NoTileModifier: "Ziemia jest płaska",
    NoTileModifierDesc:
        "Wszystkie modyfikatory płytek mają zero. Ta zasada dezaktywuje zasady Nature's Power i Tile Modifier Plus",
    DoubleTileModifierDescV2:
        "Efekt wszystkich modyfikatorów płytek x2 - zarówno pozytywny, jak i negatywny. Ta zasada dezaktywuje zasadę Earth Is Flat",
    TileModifierOutputOnlyDescV2:
        "Modyfikatory kafelków wpływają tylko na wyjście, a nie na wejście i wyjście, ale są skuteczne tylko w 50%. Ta zasada dezaktywuje zasadę Earth Is Flat",
    QuickLinks: "Szybkie linki",
    GetHelp: "Uzyskać pomoc",
    GetHelpBeginnerGuides: "Przewodnik dla początkujących",
    GetHelpSteamGuides: "Inne poradniki Steam",
    GetHelpInGameChat: "Zapytaj czat w grze",
    GetHelpDiscord: "Dołącz do naszego serwera Discord",
    GetHelpWiki: "Wiki społeczności",
    SelectATile: "Wybierz kafelek",
    PledgeAmount: "Zastaw %{amount}",
    PledgeValue: "Wartość $%{amount}",
    TotalPledgedValue: "Całkowita zadeklarowana wartość",
    TotalPledgedValueDesc:
        "Twoja pierwsza deklaracja wlicza się do celu finansowania społecznościowego. Kolejne przyrzeczenia zwiększają całkowitą wartość przyrzeczenia, ale nie wliczają się do celu",
    ReturnOnPledge: "Zwrot przy zastawie",
    CrowdfundingEndIn: "Koniec za %{time}",
    ClaimCrowdfundingReward: "Odbierz nagrodę %{amount}",
    PledgeSuccessful: "Zobowiązałeś się do %{amount} finansowania społecznościowego",
    CrowdfundingClaimSuccessful: "Odebrałeś %{amount} gotówki",
    CrowdfundingAlreadyPledged: "Już obiecałeś",
    CrowdfundingAlreadyPledgedDesc:
        "Możesz zadeklarować więcej zasobów, co zwiększy Twoją całkowitą zadeklarowaną wartość (i potencjalny zwrot), ale nie będzie liczyć się do celu crowdfundingowego",
    WholesaleCenterProducingOnly: "Partnerzy hurtowi",
    WholesaleCenterProducingOnlyDesc:
        "Zamówienia centrum hurtowego zawierają tylko zasoby, które są aktualnie produkowane (musisz również wyprodukować wymaganą liczbę zasobów, aby odblokować centrum hurtowe)",
    SoftwareCompiler: "Kompilacja oprogramowaniar",
    SearchEngine: "Wyszukiwarka",
    SearchEngineCompany: "Wyszukiwarka firmy",
    Navy: "Marynarka wojenna",
    NavyCommand: "Dowództwo marynarki wojennej",
    Battleship: "Okręt wojenny",
    BattleshipFactory: "Fabryka pancerników",
    ResourceMovementHide: "Zawsze ukrywać",
    ResourceMovementShow: "Zawsze pokazuj",
    ResourceMovementHighlight: "Na wyróżnienie",
    ResourceMovementLine: "Tylko linia",
    ResourceMovement: "Ruch surowców",
    ResourceMovementDesc:
        "Możesz wybrać, kiedy pokazać ruch zasobów (kropki). Ukrycie go może poprawić wydajność",
    CrowdfundingCashInWarning: "Masz oczekujące zobowiązania dotyczące finansowania społecznościowego – rozpoczęcie w nowym mieście spowoduje ich utratę",
    ResourceBoosterBannerDescV2:
        "💡 Masz obecnie %{number} wzmacniaczy zasobów - wkład naukowy każdego z nich jest skalowany do liczby wzmacniaczy zasobów, które aktualnie posiadasz",
    CrowdfundingId: "Finansowanie społecznościowe %{id}",
    PatchNotes: "Opis zmian",
    PatchNotesDesc: "Przeczytaj, co nowego w tej aktualizacji",
    PanelPositionLeft: "Lewy (zadokowany)",
    PanelPositionLeftFloat: "Lewy (pływający)",
    PanelPositionRight: "Prawo (Zadokowane",
    PanelPositionRightFloat: "Prawo (pływak)",
    PanelPositionAuto: "Automatyczny",
    TimePlayed: "Czas gry",
    ValuationPerHour: "Wycena na godzinę",
    HighPowerPriority: "Priorytet wysokiej mocy",
    HighPowerPriorityDesc: "Włączenie tego spowoduje, że budynek będzie pobierał energię przed innymi budynkami",
    IndustryZone: "Strefa Przemysłu",
    IndustryZoneDesc: "Połącz sąsiednie budynki, które tworzą łańcuch dostaw i oszczędzaj pozwolenia na budowę",
    IndustryZoneMaxBuildingLevel: "Maksymalny poziom budynku",
    IndustryZoneNotWorkingDesc:
        "Wszystkie sąsiadujące z nim budynki powinny tworzyć łańcuch dostaw i nie należeć do innych stref przemysłowych",
    IndustryZoneNoAdjacentBonus: "Ten budynek jest częścią strefy przemysłowej i nie ma przyległego bonusu",
    PlayerTradeAutoClaim: "Automatycznie odbieraj oferty",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "Cloud Steaming",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "Labolatorium super komputerów",
    SuperComputer: "Super Komputer",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "SkyNet",
    RobocarFactory: "Fabryka Roboaut",
    Robocar: "Roboauto",
    WarehouseBuildingPermitSave: "Ustawa o zezwoleniu na składowanie",
    WarehouseBuildingPermitSaveDesc: "Każde dwa magazyny dają jedno bezpłatne pozwolenie na budowę",
    PolicySearchPlaceholder: "Wpisz nazwę polityki do wyszukania",
    SwissUpgrade: "Szwajcarskie Ulepszenia",
    SwissUpgradeDesc: "Szwajcarskie aktualizacje są stałe i zostaną przeniesione, jeśli zaczniesz w nowym mieście",
    SwissBoost: "Szwajcarska premia",
    SwissBoostDesc: "Szwajcarskie doładowania mają wpływ tylko na bieżący bieg – i zostaną zresetowane, jeśli zaczniesz w nowym mieście",
    ProductionMultipliers: "Mnożniki produkcji",
    MultiplierMapUniqueBonus: "Unikalna premia za mapę",
    MultiplierSwissUpgrade: "Szwajcarska aktualizacja (stała)",
    MultiplierSwissBoost: "Szwajcarski dopalacz (ten bieg)",
    SwissBoostCostDivider: "Szwajcarski dzielnik kosztów doładowania",
    SwissBoostCostDividerDesc: "Podziel szwajcarski koszt doładowania przez ten dzielnik - dotyczy tylko ulepszeń mnożnika/dzielnika",
    AirForceCommand: "Siedziba sił powietrznych",
    AirForce: "Siły powietrzne",
    StealthFighterFactory: "Fabryka myśliwców",
    StealthFighter: "Myśliwiec",
    ArmyCommand: "Dowództwo armii",
    Army: "Armia",
    GreenPeacekeeper: "Zielony Strażnik Pokoju",
    GreenPeacekeeperDesc:
        "Twórz armie, marynarkę wojenna, siły potwietrzne czy drużyny kosmiczne korzystajac tylko z odnawialnych źródeł energii (turbina, panel solarny)",
    DotComTycoon: "Bańka internetowa",
    DotComTycoonDesc:
        "Zbuduj na tej samej mapie sieć społecznościową na poziomie 10, firmę zajmującą się wyszukiwarką na poziomie 10, spółkę SkyNet Inc na poziomie 10 i spółkę Musify Inc na poziomie 10",
    ConstructionNotResearched: "Nie zbadano",
    OfflineEarningDescV2: "Zarabianie offline zależy od Twoich aktualnych badań, produkcji i sprzedaży samochodów",
    HighSpeedWarehouse: "Magazyn dużych prędkości",
    HighSpeedWarehouseDesc:
        "Magazyny mają 2x więcej  pojemność i 50% większą prędkość transportu do wewnątrz i na zewnątrz, ale zużywają 2x więcej mocy",
    IndustryZoneMultiplierDesc: "Premia za strefę przemysłową",
    IndustryZoneMultiplierSwissBoost: "Wzmacniacz pojemności strefy przemysłowej",
    EarningPerMinuteV2: "Zarobki offline",
    OfflineResearchPoint: "Punkty badań offline",
    WholesaleCenterOrderFasterV2: "Szybki rynek zbytu",
    OfflineResearchSwissBoost: "Badania offline",
    OfflineResearchSwissBoostDesc:
        "Punkty badawcze są generowane, gdy jesteś offline (zgodnie z twoim poziomem laboratorium badawczego, nauką w magazynie i czasem zarabiania offline)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Unikalny budynek: producent chipów</li><li>Unikalny budynek: FaceApp Inc</li><li>Unikalny budynek: Bitcoin Miner</li><li>Wszystkie budynki, które zużywają krzem, mają maksymalny modyfikator płytek</li>li><li>Panele słoneczne generują 2x więcej mocy</li><li>Kopalnie krzemu mają 2x więcej  mocy</li>",
    RotterdamBonusV2:
        "<li>Stalownie mają 2x lepszą  wydajność</li><li>Wytwórnie stali nierdzewnej mają 2x lepszą  wydajność</li><li>Bezpłatny transport żelaza</li><li>Transport stali kosztuje 50% mniej paliwa</li><li>Rozpocznij z 2x większymi możliwościami sprzedaży samochodów</li><li>Polisa Earth Is Flat jest bezpłatna</li>",
    ChipManufacturer: "Producent chipów",
    SnapTokInc: "SnapTok Inc",
    FaceAppInc: "FaceApp Inc",
    BitcoinMiner: "Koparka bitcoinów",
    GalvanicBatteryFactory: "Fabryka baterii galwanicznych",
    BaseProductionMultiplier: "Produkcja podstawowa",
    ShowBreakdown: "Pokaż podział",
    HideBreakdown: "Ukryj podział",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Każdy poziom łańcucha produkcyjnego w strefie przemysłowej zapewnia ten wzrost wydajności we wszystkich budynkach w tej samej strefie",
    IndustryZoneBuildingPermitDesc:
        "Jeśli strefa przemysłowa ma N poziomów produkcji, wyda N-2 pozwoleń na budowę za darmo",
    CrowdfundingBackersReturn: "Wspierający: %{backers}, Bieżący zwrot: %{return}",
    CrowdfundingBackersNeeded: "%{backers} Więcej sponsorów",
    CrowdfundingReturnBonus: "+%{return} Powrót",
    ReturnOnPledgeDescV2:
        "Twój całkowity zwrot jest równy całkowitej zastawionej wartości pomnożonej przez stopy zwrotu ze wszystkich zasobów. Więcej zwolenników zasobu poprawi jego zwrot",
    PlayerTradeQuotaDescV2:
        "💡 Limit to ilość surowca, którym możesz handlować. Wartość pieniężna wynosi %{percent} kapitalizacji rynkowej i resetuje się, gdy rynek się aktualizuje. Im bardziej cena Twojej transakcji odbiega od ceny Twojego centrum handlowego, tym więcej potrzebujesz kwoty",
    AchievementSanJose100: "Hobbystka przedsięwzięć",
    AchievementSanJose100Desc: "Zarób 100 szwajcarskich pieniędzy w San Jose w jednym biegu",
    AchievementSanJose500: "Entuzjasta przedsięwzięć",
    AchievementSanJose500Desc: "Zarób 500 szwajcarskich pieniędzy w San Jose w jednym biegu",
    AchievementSanJose1000: "Venture Capitalist",
    AchievementSanJose1000Desc: "Zarób 1000 szwajcarskich pieniędzy w San Jose w jednym biegu",
    AchievementCrowdfundingTycoon: "Potentat crowdfundingowy",
    AchievementCrowdfundingTycoonDesc: "Zastaw zasobów o wartości 1Qa w ramach jednego finansowania społecznościowego",
    AchievementCashIsKing: "Kasa jest wszystkim",
    AchievementCashIsKingDesc: "Miej 1Q gotówki pod ręką w jednym biegu",
    AchievementPowerTycoon: "Fabryka mocy",
    AchievementPowerTycoonDesc: "Generuj moc 1 GW w jednym przebiegu",
    PlayerTradeFilteringNResources: "Filtracja %{n}Zasobów",
    PlayerTradeFilterResources: "Filtruj zasoby",
    PlayerTradeFilterClear: "Wyczyść filtry",
    ResourceExplorerAll: "Przeglądaj wszystkie zasoby",
    ResourceExplorerAllDesc:
        "Eksploratorzy zasobów mogą produkować wszystkie zasoby, w tym te, których nie ma na mapie (NIE ODblokowuje to odpowiednich technologii)",
    ShowResourceInTopBar: "Pokaż na górnym pasku",
    LeaderboardOptOutDescV2:
        "Nie będziesz już pojawiać się na tablicy wyników. Spowoduje to również wyłączenie handlu gracza. UWAGA: jeśli chcesz później włączyć tabelę wyników, Twoje dane muszą zostać zresetowane",
    PolicyPointNoCopperDesc:
        "💡 Ta mapa nie zawiera złóż miedzi, możesz aktywować polisę Al Circuit, aby odblokować kolejne technologie",
    Pumpkin: "Dynia",
    PumpkinBattery: "Bateria dyniowa",
    PumpkinBatteryDesc: "Wszystkie budynki, które zużywają baterię, używają zamiast tego dyni",
    PumpkinSteel: "Stal dyniowa",
    PumpkinSteelDesc: "Wszystkie budynki, które zużywają stal, używają zamiast tego dyni",
    RequireExpansionPack2: "Dodatek 2",
    ExpansionPack2: "Dodatek 2",
    RequireExpansionPack2Desc: "Jest to dostępne tylko dla dodatku Expansion Pack 2",
    Reindeer: "Renifer",
    ReindeerSilicon: "Renifer Krzem",
    ReindeerSiliconDesc: "Wszystkie budynki, które zużywają krzem, wykorzystują zamiast tego renifery",
    ReindeerAluminum: "Renifer Aluminium",
    ReindeerAluminumDesc: "Wszystkie budynki, które zużywają aluminium, wykorzystują zamiast tego renifery",
    SantaClauseIsComing: "Święty Mikołaj nadchodzi",
    SantaClauseIsComingDesc:
        "Fabryki Świętego Mikołaja konsumują renifery i zabawki oraz produkują Świętego Mikołaja, naukę i kulturę. Fabryki Mikołaja mają maksymalny modyfikator kafelków. Fabryka zabawek oprócz zabawek produkuje renifery",
    MetaRebranding: "Meta Rebranding",
    MetaRebrandingDesc:
        "Social Network Inc zmienia nazwę na Meta Inc i zamiast tego zużywa internet, grę, superkomputer, bitcoiny i dogecoiny",
    MetaInc: "Meta Inc",
    ImportSave: "Importuj Zapis",
    ExportSave: "Eksportuj Zapis",
    ClearMyTrades: "Wyczyść Moje Transakcje",
};
