export const PT_BR = {
    Translator: "Tradutor",
    TranslatorName: "Altruista",
    Language: "Idioma",
    ThisLanguage: "Português (BR)",
    OK: "OK",
    SteelMill: "Fábrica de aço",
    StainlessSteelPlant: "Fábrica de aço inoxidável",
    CircuitFoundry: "Fundição de circuito",
    IntegratedCircuit: "Circuito integrado",
    OilWell: "Poço Petrolífero",
    Wood: "Madeira",
    LoggingCamp: "Madeireira",
    LumberMill: "Serraria",
    Lumber: "Madeira Serrada",
    Paper: "Papel",
    PaperMill: "Fábrica de papel",
    Book: "Livro",
    BookPublisher: "Editora de Livros",
    OilRefinery: "Refinaria de Petróleo",
    Sell: "Vender",
    Upgrade: "Melhorar",
    Build: "Construir",
    Inspect: "Inspecionar",
    Buildings: "Construções",
    Iron: "Ferro",
    Actions: "Ações",
    FuelType: "Tipo de combustível",
    FuelCost: "Custo de combustível",
    FuelConsumption: "%{fuel} Consumo",
    FuelEconomy: "Economia de combustível",
    FuelProduction: "%{fuel} produção",
    FuelInStorage: "%{fuel} armazenado",
    Plastic: "Plástico",
    FuelSurplus: "%{fuel} sobrando",
    Petrol: "Petróleo",
    Buy: "Comprar",
    NoLiquidity: "Sem liquidez",
    NoLiquidityTurnOffAutoSell: "Não há liquidez no mercado suficiente por %{res}, venda automática desativada",
    Multiplier: "Multiplicador",
    MultiplierDesc: "A cada 10 níveis, você ganha +1 multiplicador",
    SellBuilding: "Vender Construção",
    PowerGrid: "Malha energética",
    TradeAmount: "Quantidade da negociação",
    SortBy: "Classificar por",
    SortByPrice: "Preço",
    SortByAmount: "Quantidade",
    NotEnoughResourcesForTrade: "Sem recurso(s) suficiente(s) no Centro Comercial para esta troca",
    NotEnoughResources: "Não há recurso suficiente para essa ação",
    Transportation: "Transporte",
    Cash: "Dinheiro",
    Aluminum: "Alumínio",
    ResearchPoint: "Ponto de pesquisa",
    Unlock: "Desbloquear",
    BuildingUnlocked: "%{building} foi desbloqueado",
    Science: "Ciência",
    ScienceFromPowerDesc: "Usinas Elétricas geram uma pequena quantidade de Ciência quando estão gerando energia",
    Culture: "Cultura",
    School: "Escola",
    University: "Universidade",
    Polytechnic: "Escola politécnica",
    Colosseum: "Coliseu",
    WindTurbine: "Turbina eólica",
    Engine: "Motor",
    EngineFactory: "Fábrica de motores",
    CameraFactory: "Fábrica de câmeras",
    Camera: "Câmera",
    Gun: "Arma",
    GunFactory: "Fábrica de Armas",
    Aircraft: "Aeronave",
    AircraftFactory: "Fábrica de Aeronaves",
    Zeppelin: "Zepelim",
    ZeppelinFactory: "Fábrica de Zepelins",
    Tank: "Tanque",
    TankFactory: "Fábrica de Tanques",
    CoalPowerPlant: "Usina Elétrica à Carvão",
    PetrolPowerPlant: "Usina Elétrica à Petróleo",
    Copper: "Cobre",
    Gas: "Gás Natural",
    GasPump: "Bomba de Gás Natural",
    GasPowerPlant: "Usina Elétrica à Gás",
    Missile: "Míssil",
    MissileFactory: "Fábrica de Mísseis",
    Rocket: "Foguete",
    RocketFactory: "Fábrica de foguetes",
    BuildingPermit: "Permissão para construir",
    BuildingPermitDesc:
        "Você tem permissão para %{amount} construções, você já construiu %{amountBuilt} e tem %{amountLeft} sobrando",
    BuildingLocked: "Construção ainda não disponível, você precisa desbloquear no Centro de Pesquisa primeiro",
    BuildQueue: "Fila de Construção",
    BuildQueueDesc: "Número de construções atualmente na fila",
    MaxBuilders: "Máximo de Construtores",
    MaxBuildersDesc: "Número de edifícios que você pode construir ao mesmo tempo",
    Silicon: "Silício",
    AluminumMine: "Mina de Alumínio",
    CopperMine: "Mina de Cobre",
    SiliconMine: "Mina de Silício",
    IronMine: "Mina de Ferro",
    CoalMine: "Mina de Carvão",
    Headquarter: "Quartel General",
    ResearchLab: "Laboratório de Pesquisa",
    TradeCenter: "Centro Comercial",
    Resources: "Recursos",
    NotEnoughPower: "💡 Energia insuficiente, considere aumentar sua produção de energia",
    NotEnoughFuel: "%{fuel} insuficiente para esta operação",
    NotEnoughCash: "Dinheiro insuficiente para esta operação",
    NotEnoughSwissMoney: "Não há dinheiro Suiço suficiente para essa operação",
    BuildingNotEnoughFuel: "💡 %{fuel} insuficiente",
    AutoSell: "Venda automática",
    SellAll: "Vender tudo",
    Change: "Trocar",
    StatisticsBureau: "Departamento de estatística",
    LogisticsDepartment: "Departamento de Logística",
    From: "De",
    Top20FuelCost: "Top 20 custos de combustível",
    To: "Para",
    TransportTime: "Tempo de transporte",
    TopN: "Top %{n}",
    Warehouse: "Armazém",
    TradeWarehouse: "Armazém comercial",
    Coal: "Carvão",
    Video: "Video",
    ClothingFactory: "Fábrica de Roupas",
    Clothes: "Roupas",
    Fashion: "Moda",
    FashionFactory: "Fábrica de Moda",
    VideoFarm: "Fazenda de vídeo",
    SantaFactory: "Fábrica de Papai Noel",
    Santa: "Papai Noel",
    Car: "Carro",
    CarFactory: "Fábrica de Carros",
    Ship: "Navio",
    SolarPanel: "Painel Solar",
    SolarPanelDesc:
        "💡 Painéis Solares trabalham apenas 5 segundos em cada 10 segundos - todos os ciclos estão alinhados",
    WindTurbineDesc: "💡 Turbinas eólicas trabalham apenas 8 segundos em cada 10 segundos - ciclos não estão alinhados",
    Movie: "Filme",
    MovieStudio: "Estúdio de filmagem",
    Sitcom: "Sitcom",
    TVStudio: "Estúdio de Televisão",
    PC: "Computador",
    GameStudio: "Estúdio de Jogos",
    Game: "Jogo",
    ComputerFactory: "Fábrica de Computadores",
    Shipyard: "Estaleiro",
    PowerUsage: "Energia Usada",
    PowerSupply: "Energia Gerada",
    PowerSurplus: "Energia Sobrando",
    Level: "Nível",
    Power: "Energia",
    CentralBank: "Banco Central",
    ResourceInput: "Entrada",
    ResourceOutput: "Saída",
    ResourceStorage: "Armazém",
    ResourceChange: "Alterar",
    ResourceInOutDesc:
        "💡 Clique nos números de Entrada-Saída acima para realçar as correspondentes construções de saída e entrada",
    ResourceChart: "Gráfico de Recursos",
    MarketUpdateIn: "Atualização de mercado em %{time}",
    Income: "Receita",
    Semiconductor: "Semicondutor",
    SemiconductorFactory: "Fábrica de Semicondutor",
    Steel: "Aço",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Fazenda de Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Fazenda de Dogecoin",
    Guitar: "Guitarra",
    GuitarFactory: "Fábrica de guitarras",
    Drum: "Tambor",
    DrumFactory: "Fábrica de tambores",
    RecordingStudio: "Estúdio de Gravação",
    OperaHouse: "Casa de Ópera",
    CoalGasificationPlant: "Planta de Gaseificação de Carvão",
    GasProcessingPlant: "Planta de Processamento de Gás",
    Music: "Música",
    Glass: "Vidro",
    PhoneFactory: "Fábrica de Celular",
    Phone: "Celular",
    GlassFactory: "Fábrica de Vidro",
    Oil: "Petróleo Bruto",
    Chromium: "Cromo",
    ChromiumMine: "Mina de Cromo",
    Uranium: "Urânio",
    EnrichedUranium: "Urânio Enriquecido",
    NuclearPowerPlant: "Usina Nuclear",
    UraniumEnrichmentPlant: "Planta de Enriquecimento de Urânio",
    UraniumMine: "Mina de Urânio",
    Titanium: "Titânio",
    TitaniumMine: "Mina de Titânio",
    TitaniumAlloyPlant: "Planta de Liga de Titânio",
    ChromiumAlloyPlant: "Planta de Liga de Cromo",
    Input: "Entrada",
    PanelPosition: "Posição do painel",
    PanelPositionDesc:
        "Mostrar painel lateral à esquerda, direita ou automático (depende do bloco selecionado atualmente)",
    InputCapacity: "Capacidade de entrada",
    InputCapacityPerCycle: "Capacidade de entrada por Ciclo",
    Output: "Saída",
    OutputCapacity: "Capacidade de saída",
    OutputCapacityPerCycle: "Capacidade de saída por ciclo",
    ResourceDeposit: "Depósito de recursos",
    RecommendedBuilding: "💡 Este bloco tem %{resource} depositado",
    AdjacentBonus: "Bônus adjacente",
    AdjacentBonusDesc: "Você ganha %{bonus}% de capacidade extra para cada construção adjacente de mesmo tipo operando",
    ConsiderIncreaseProduction: "💡 Considere aumentar a produção de %{resource}",
    AlwaysTransportInput: "Modo de Estoque",
    AlwaysTransportInputTradeCenter: "Sempre exportar",
    AlwaysTransportInputTradeCenterDesc:
        "Sempre transportar recursos ao centro comercial, mesmo se a venda automática estiver desabiltada para este recurso",
    AlwaysTransportInputDesc:
        "Sempre transporte recursos de entrada, mesmo se eles estiverem acima do requisito mínimo de produção",
    ProductionCycleLength: "Ciclo de produção",
    ProductionCycleLengthDesc:
        "Duração de um ciclo de produção, mensurado em segundos. Prolongar o clico irá aumentar a entrada/saída por ciclo consequentemente diminuindo sua prioridade ao buscar recursos de entrada",
    MaxInputDistance: "Max Input Distance",
    MaxInputDistanceDesc:
        "A distância máxima a partir da qual este edifício pode buscar recursos de entrada, medida em número de blocos",
    AutoSellCapacity: "Capacidade de Venda Automática",
    AutoSellCapacityDesc:
        "Quantidade máxima de recursos que a venda automática pode manipular por segundo, por recurso",
    CurrentAutoSellCapacityMultiplier: "Multiplicador atual: x%{n}",
    AutoSellConcurrency: "Simultaneidade de venda automática",
    AutoSellConcurrencyDesc: "Número máximo de recursos que a venda automática pode gerenciar ao mesmo tempo",
    MaxAutoSellConcurrencyReached:
        "Você atingiu o máximo de vendas automáticas simultâneas, desativa uma venda automática para habilitar esta",
    CannotSellBuilding: "Não é possível vender construção no momento",
    WallStreet: "Wall Street",
    MarketCap: "Valor de mercado",
    MarketCapDesc: "Capitalização total (i.e. valor de mercado) de sua corporação",
    BuildingValuation: "Estimativa da construção",
    BuildingValuationDesc: "Valor total de suas construções, incluindo licenças de construção e atualizações",
    ResourcesValuation: "Estimativa de recursos",
    ResourcesValuationDesc: "Valor total de recursos no seu inventário",
    Battery: "Bateria",
    BatteryFactory: "Fábrica de baterias",
    RatingBuy: "Comprar",
    RatingSell: "Vender",
    SwissShop: "Loja Suíça",
    RatingHold: "Segurar",
    RatingOutperform: "Exceder",
    RatingUnderperform: "Underperform",
    StockRating: "Avaliação de ações",
    JetEngine: "Motor de jato",
    Helicopter: "Helicóptero",
    Lithium: "Lítio",
    LithiumMine: "Mina de Lítio",
    LiionBatteryFactory: "Fábrica de bateria Li-ion",
    HelicopterFactory: "Fábrica de helicóptero",
    Satellite: "Satélite",
    ToyFactory: "Fábrica de brinquedo",
    Toy: "Brinquedo",
    SpaceStation: "Estação Espacial",
    SpaceStationFactory: "Fábrica de estações espaciais",
    OperatingSystem: "Sistema operacional",
    OperatingSystemCompany: "Incorporação Sistema Computacional",
    LinuxDistribution: "Distribuição Linux",
    Internet: "Internet",
    WebBrowser: "Navegador de internet",
    Console: "Console",
    ConsoleFactory: "Fábrica de consoles",
    Train: "Trem",
    TrainFactory: "Fábrica de trens",
    ShoeFactory: "Fábrica de sapatos",
    Shoes: "Sapatos",
    ArtilleryFactory: "Fábrica de artilharia",
    Artillery: "Artilharia",
    SubmarineFactory: "Fábrica de submarinos",
    Submarine: "Submarino",
    Spaceship: "Nave espacial",
    RobotFactory: "Fábrica de robôs",
    Robot: "Robô",
    SpaceshipFactory: "Fábrica de nave espacial",
    SatelliteFactory: "Fábrica de satélites",
    JetEngineFactory: "Fábrica de motor de jatos",
    StockRatingDesc:
        "Consenso de classificação de ações de analistas de Wall Street, que afeta sua capitalização de mercado e é atualizado junto com o mercado",
    InterestRate: "Taxa de juros noturna",
    InterestRateDesc: "Juros que você ganha sobre sua capitalização de mercado enquanto está offline",
    OfflineEarning: "Ganhos offline",
    OfflineEarningDesc: "Os ganhos off-line dependem de sua capitalização de mercado e taxa de juros",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Tempo de ganho offline",
    OfflineEarningTimeDesc: "Você ganhará ganhos off-line por até esse limite",
    BuyPermit: "Comprar permissão",
    NotEnoughBuildingPermit:
        "Não há licenças de construção suficientes. Por favor, compre mais para construir novos edifícios",
    MovingAverage: "Média Móvel",
    MovingAverageDesc: "Mostra a média móvel de mudança de recursos em vez de mudança em tempo real",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Ative o suporte para zoom. Use a roda do mouse para dar zoom. O zoom atual é %{zoom}",
    AllowZoomMobileDesc: "Ative o suporte para zoom. Você pode apertar para ampliar. O zoom atual é %{zoom}",
    Settings: "Configurações",
    Sound: "Efeito sonoro",
    SoundDesc: "Ative o efeito de som como o clique ou som de erro",
    AutoHighlight: "Destaque automático",
    AutoHighlightDesc: "Destacar edifícios do mesmo tipo automaticamente ao selecionar um edifício",
    MusicDesc: "Ligue a música: It's Not Over 'Til The Bossa Nova de Shane Ivers (https://www.silvermansound.com)",
    Credits: "Créditos",
    Icons: "Ícones",
    MisplacedBuilding: "⛔ Esta %{building} não está colocada em cima do depósito de recursos correto",
    Left: "Esquerda",
    Right: "Direita",
    Auto: "Auto",
    HighlightBuildings: "Destacar construções",
    HighlightTurnedOff: "... que estão desativadas",
    HighlightStockpileModeOn: "...que têm o modo de estoque ativado",
    HighlightProductionCycleNotDefault: "...quem têm o clico de prodição > 1",
    HighlightMaxInputDistanceNotDefault: "...que têm distância máxima de entrada < ∞",
    HighlightNotMakingProfit: "... que não geram lucro",
    NBuildingsAreHighlighted: "%{n} construção(ões) são destacadas",
    OnlyToWarehouse: "Apenas para armazéns",
    OnlyToWarehouseDesc: "Apenas armazéns podem transportar recursos deste edifício",
    TurnOffProduction: "Desativar",
    TurnOffProductionDesc:
        "Desligue a produção da construção. A construção não transportará mais recursos nem usará energia",
    ApplyToAll: "Aplicar para todos %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Ilimitado",
    Transport: "Transporte",
    TileModifier: "Tile Modifier",
    ShowAllModifiers: "Mostrar todos modificadores",
    HideAllModifiers: "Esconder todos modificadores",
    NumberOfBuildings: "Numero de construções que você tem",
    ShowContent: "Mostrar conteúdo",
    HideContent: "Esconder conteúdo",
    BuyExpansionPack: "Comprar por %{price}",
    Cities: "Cidades",
    InputStrategy: "Estratégia de Entrada",
    InputStrategyClose: "Mais próximo",
    InputStrategyCloseDesc: "Prefira o armazém mais próximo que tenha recursos suficientes",
    InputStrategyFar: "Mais distante",
    InputStrategyFarDesc: "Prefira o armazém mais distante que tenha recursos suficientes",
    InputStrategyAmount: "Quantidade",
    InputStrategyAmountDesc: "Prefira o armazém com maior quantidade de recursos, independente da distância",
    FuelCostSave: "Economia de combustível",
    FuelCostSaveDesc:
        "Os armazéns economizam uma certa porcentagem de combustível para o transporte de recursos para dentro em comparação com outros edifícios, quanto mais alto o nível, mais economia",
    SoftwareCompany: "Empresa de programas",
    Software: "Programa",
    ScreenFactory: "Fábrica de telas",
    Screen: "Tela",
    JoinDiscord: "Junte-se ao nosso servidor Discord para novidades, dicas e discussões",
    ClaimOfflineEarning: "Reivindicar ganhos offline",
    OfflineTime: "Tempo desligado",
    Minutes: "%{time}min",
    MaxUpgrade: "Melhoria máxima",
    MaxUpgradeDesc: "Você chegou na melhoria máxima. Parabéns!",
    ClaimAmount: "Dinheiro +%{amount}",
    EarningPerMinute: "Taxa de ganho",
    EffectiveTime: "Tempo Efetivo",
    EffectiveTimeDesc: "Seu tempo efetivo de ganho offline é limitado a %{time}min.",
    BuildSearchPlaceholder: "Digite construção ou recurso para pesquisar",
    MineOverlayWarning: "%{building} não é afetado pelo modificador de bloco",
    WholesaleCenter: "Centro de atacado",
    OrderFrom: "Ordem de %{name}",
    ExpireIn: "Expira em",
    TurnOnAllProductions: "Produção Ligada",
    TurnOnAllProductionsDesc:
        "Ligue as produções de todos os edifícios, não pode ser usado quando a política de economia de custos está ativa",
    OperationSuccessful: "Essa operação foi concluída com sucesso",
    TurnOn: "Ligar",
    Reward: "Recompensa",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/ciclo",
    PolicyPoint: "Ponto de Política",
    PolicyPointPerMinute: "Taxa de geração",
    PolicyPointPerMinuteDesc: "Você adquire pontos de política a cada minuto no jogo",
    YourWilLGaimPolicyPoints: "Você ganhará %{amount} pontos de política em %{time}s",
    PolicyPointDesc: "💡 Quanto mais políticas ativas, mais custo para cada política",
    NextOrderIn: "Próximo pedido em",
    FillOrder: "Preencher pedido",
    RejectOrder: "Passar",
    WholesaleCenterLocked:
        "Você precisa de pelo menos %{required} recursos diferentes para desbloquear o Centro de atacado. Você tem apenas %{current} recursos",
    OrderFilled: "O pedido de %{from} foi preenchido com sucesso!",
    PolicyCenter: "Centro Político",
    NewOrder: "Um novo pedido de %{from} chegou, por favor, verifique no Centro de atacado",
    Policies: "Políticas",
    PolicyNotEnoughTime: "Você não tem pontos de política suficientes para esta política",
    TimeLeft: "%{time} Restante",
    WholesaleCenterOrderFaster: "Feira mundial",
    WholesaleCenterOrderFasterDesc:
        "A Central de atacado recebe pedidos 2x mais rápido e o tamanho do pedido é 2x maior",
    PolicyOilWellPowerx2: "Sobrecarregar Poço de Petróleo",
    PolicyOilWellPowerx2Desc: "Poços de petróleo produzem 2x mais óleo e usam 2x mais energia",
    HalfTransportSpeed: "Diminua A Velocidade Para Economizar",
    HalfTransportSpeedDesc: "A velocidade de transporte é reduzida em 25% e o custo do combustível é reduzido em 25%",
    RefineryMoreOil: "Mais Petróleo Mais Problemas",
    RefineryMoreOilDesc: "Refinarias de petróleo produzem 50% mais gasolina e 50% menos plástico",
    StickyInput: "Entrada Pegajosa",
    StickyInputDesc:
        "Os edifícios irão preferir o transporte da fonte anterior, em vez de procurar a melhor fonte a cada ciclo (POLÍTICA GRATUITA)",
    RefineryMorePlastic: "Mais Plásticos Mais Problemas",
    RefineryMorePlasticDesc: "Refinarias de petróleo produzem 50% menos gasolina e 50% mais plástico",
    FreeOilTransportDesc: "O transporte de petróleo não custa combustível, mas os poços de petróleo usam 2x a potência",
    SuperSteelMill: "Corações de Ferro",
    SuperSteelMillDesc: "As siderúrgicas usam 50% menos carvão e 25% mais ferro e 25% mais energia",
    AlSemiconductor: "Circuito de IA",
    AlSemiconductorDesc: "As fundições de circuito usam alumínio em vez de cobre",
    CostSaver: "Economia de Custos",
    CostSaverDesc: "Se a entrada de um edifício custar mais do que sua produção, desligue a produção",
    CostSaverBuildingDesc:
        "A política de redução de custos está ativa, a produção será ligada / desligada automaticamente com base em sua lucratividade",
    CostSaverBuildingWarning:
        "A política de redução de custos está ativa, você não pode alterar manualmente a produção",
    GlassUseCoal: "Vidro Negro",
    GlassUseCoalDesc: "As fábricas de vidro usam 50% mais carvão e 50% menos silício",
    AdjacentBonusOnlyOutput: "Bônus Adjacente Plus",
    AdjacentBonusOnlyOutputDesc:
        "O bônus adjacente não requer mais entrada, mas usa mais energia e é apenas 50% eficaz",
    IronMine2xOutput: "Ferro Pesado",
    IronMine2xOutputDesc: "As minas de ferro produzem 2x o ferro, mas o transporte de ferro custa 2x o combustível",
    SolarPanelAlwaysWork: "O Sol Nunca Se Põe",
    SolarPanelAlwaysWorkDesc: "Os painéis solares funcionam 100% do tempo, mas produzem 60% menos energia",
    SteelScience: "Conhecimento através do aço",
    SteelScienceDesc: "As usinas siderúrgicas usam 2x mais insumos e produzem ciência extra",
    WholesaleCenterProducingOnly: "Parceiros de Atacado",
    WholesaleCenterProducingOnlyDesc:
        "Os pedidos do centro de atacado contêm apenas recursos que estão sendo produzidos no momento (você também precisa estar produzindo o número de recursos necessários para desbloquear o centro de atacado)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "Se a capacidade de produção de um recurso for insuficiente, compre a quantidade em falta do Centro Comercial automaticamente (se o recurso tiver venda automática, ele será ignorado)",
    ShoppingSpreeTradeCenterDesc:
        "💡 A política da Maratona de Compras está ativada, o Centro Comercial comprará automaticamente os recursos em falta",
    ExtraPolicyPoints: "Lobista Político",
    ExtraPolicyPointsDesc: "Aumenta a capacidade de produção de pontos de política em 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "As fábricas de liga de cromo não usam lítio, mas usam 2x ferro em vez disso",
    DoubleTileModifier: "Poder da Natureza",
    DoubleTileModifierDesc: "Todos os modificadores de blocos afetam x2 - tanto positivo quanto negativo",
    TileModifierOutputOnly: "Modificador de Bloco Plus",
    TileModifierOutputOnlyDesc:
        "Os modificadores de bloco afetam apenas a saída, em vez de entrada e saída, mas são apenas 50% eficazes",
    GasPlantPetrol: "Liquidificador de Gás",
    GasPlantPetrolDesc: "Usinas a gás usam gás extra para produzir gasolina",
    BuildingRecycle: "Reciclagem de Edifícios",
    BuildingRecycleDesc: "Obtenha o reembolso total ao vender um edifício dentro de 1 minuto após a construção",
    CoalPlantFuel: "Liquidificador de carvão",
    CoalPlantFuelDesc: "Usinas de carvão usam carvão extra para produzir gasolina",
    Welcome: "Bem-vindo",
    SeeTutorialAgain: "Refazer Tutorial",
    HelpTranslateTheGame: "Ajude a traduzir o jogo 🌐",
    SkipTutorial: "Pular tutorial",
    NextTutorial: "Próximo",
    Tutorial1:
        "Industry Idle é um <em> jogo </em> de gestão de recursos em que você constrói fábricas🏭, produz bens📦 e faz dinheiro💸.<br><br>Vamos repassar alguns conceitos básicos para você começar - não vai demorar muito, eu prometo.",
    Tutorial2:
        "Todas as construções precisão de energia⚡, você tem a <em>turbina eólica</em> que gera energia. Você pode ver sua produção de energia atual no lado esquerdo da barra superior.<br><br>Você deve ter notado que as turbinas eólicas só funcionam <em>80%</em> do tempo. Você pode considerar a construção de outros tipos de usinas de energia que geram energia estável.",
    Tutorial3:
        "Vo~e tem um monte de <em>depositos de recursos</em> no mapa. Para extrair recursos, você deve construir minas⛏️ <em>em cima</em> do depósito correspondente.<br><br>por exemplo, você tem um <em>poço de petróleo🛢️</em> que extrái <em>petróleo</em> De um depósito.<br></br>Os depósitos de recursos são ilimitados - não há necessidade de se preocupar com o esgotamento. Além das minas, outros edifícios podem ser construídos em qualquer blco vazio.",
    Tutorial5:
        "Para ganhar dinheiro, você precisa exportar seus recursos através do centro de comércio. Para fazer isso, basta ligar <em>Venda Automática</em> para este recurso.<br></br>Você também pode comprar recursos do centro comercial. Lembre-se, <em>se você compra um recurso, você vai aumentar o preço</em> e se você vender um recurso, você vai baixar o preço.<br><br>O mercado é <em>volátil</em> e o preço📈 muda regularmente.",
    Tutorial6:
        "Para construir novos edifícios, você precisa primeiro de desbloquear ele no <em>centro de pesquisa🧪</em>. O laboratório de pesquisa também converte ciência em pontos de pesquisa.<br><br>Sua turbina eólica (e outras plantas de energia) produzem uma pequena quantidade de ciência enquanto funcionam. E você também pode construir escolas🏫 e outros edifícios dedicados para impulsionar a ciência mais tarde.<br><br>Agora que você aprendeu o básico, comece a construir sua economia! Aqui está um pouco de <em>dinheiro💸</em> e <em>petróleo⛽</em> para te dar um salto inicial.",
    WelcomePlay: "Tocar",
    WelcomePlayMuted: "Tocar (🔇Música)",
    Changelog: "Lista de mudanças",
    ChangelogGotIt: "Entendi",
    Chat: "Chat",
    Send: "Enviar",
    Import: "Importar",
    Export: "Exportar",
    LastBackupAt: "Último backup",
    RestoreFromBackup: "Restaurar do backup",
    RestoreFromBackupFail: "Falha ao restaurar o backup do Steam Cloud: você tem certeza que há um backup?",
    RestoreFromBackupTitle: "Certeza?",
    RestoreFromBackupDesc:
        "Normalmente, você não precisa restaurar do backup em nuvem, a menos que seu salvamento local seja perdido. O backup na nuvem é um pouco mais antigo que o seu save local",
    ChatMessages: "Mensagens de bate-papo",
    ChangeName: "Trocar",
    SaveName: "Salvar",
    NameValidationRule: "Seu nome só pode conter letras e números e ter entre 5-15 caracteres",
    NameValidationRuleProfanity: "Seu nome não deve conter profanidade",
    ChatMessageRateLimit: "Você só pode enviar uma nova mensagem de bate-papo a cada 10 segundos",
    NameSaved: "Seu nome foi alterado com sucesso",
    NoMessages: "Sem mensagens novas",
    Leaderboard: "Leaderboard",
    Name: "Nome",
    Rank: "Rank",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2: "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building is determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Modo economia de energia",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptOutDesc:
        "This will no longer send leaderboard score. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Reward video did not complete",
    RewardAdsNotAvailable: "Reward video is not available (currently only iOS/Android is supported)",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Realçar "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Acaba em %{time}",
    FuelRunOutWarning: "💡 Your fuel consumption exceeds production. When fuel runs out, your transportation will halt",
    InAmount: "In: %{number}",
    OutAmount: "Out: %{number}",
    SwissBank: "Banco na Suíça",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Se você começar em uma nova cidade, você receberá %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Pacotes de expansão",
    ExpansionPack1: "Pacote de expansão 1",
    ExpansionPack1Owned: "Pacote de expansão 1",
    RequireExpansionPack1: "Pacote de expansão 1",
    RequireExpansionPack1Desc: "Somente disponível pelo pacote de expansão 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Esconder banner do Discord",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Esconder bate-papo",
    SortedByDeficit: "Sorted By Deficit",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Dinheiro Suíço 💵",
    RestartDesc: "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
    PrestigeGoBack: "Voltar",
    PermanentUpgradeDesc: "This upgrade will carry over if you start in a new city",
    ProductionMultiplier: "Multiplicador de Produção",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    OfflineEarningMultiplier: "Offline Earning Multiplier",
    OfflineEarningMultiplierDesc: "A multiplier that applies to offline earnings",
    PrestigeAlertTitle: "Você tem certeza?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Receber",
    Cancel: "Cancelar",
    SaveFileCorrupted: "Save File Corrupted",
    CheatDetected: "Your old save did not pass server validation and cannot be read. You will start with a new save",
    LoadGameError: "Falha em carregar jogo",
    LoadGameErrorMessage: "Mensagem de erro: %{message}",
    LoadGameErrorDesc: "Por favor, verifique sua conexão com a internet. Se o problema persistir, contate o suporte",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    SaveFileMigrated: "A New Era: Beta Is Here",
    SaveFileMigratedDesc:
        "Thank you for play testing in alpha. Your old map is not compatible but we have migrated your data and give you some bonus",
    ClaimSwissMoney: "Receber %{amount} Swiss Money 💵",
    SaveFileMigratedFinePrint:
        "Your market cap is converted to Swiss Money and your unspent Swiss money is carried forward. You will get 50% bonus Swiss money for play testing in alpha. Max Swiss money that can be carried forward is capped at 200",
    CashIn: "Cash In",
    CurrentCity: "Cidade atual",
    CashInDesc:
        "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
    MoveToNewMap: "Comece em uma nova cidade",
    CityName: "Cidade",
    CitySize: "Tamanho do mapa",
    GridType: "Tipo de Grade",
    StartInThisCity: "Começar em %{city}",
    CityBonus: "Bônus da Cidade",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hexagonal",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>No tile modifiers</li>",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>Universities have 2x productivity</li>",
    HideNotProducing: "Esconder recursos que não estão sendo produzidos",
    SortByStorage: "Armazenamento",
    SortByProduction: "Produção",
    SortByName: "Nome",
    PlayerTrade: "Troca entre jogadores",
    AddTradeFail: "Falha em adicionar sua oferta",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Sua oferta foi adicionada com sucesso",
    LoadTradeFail: "Falha em carregar as ofertas dos jogadores, por favor, tente novamente mais tarde",
    ClaimTradeFail: "Falha em reinvindicar essa oferta, por favor, tente novamente mais tarde",
    CancelTradeSuccess: "Sua oferta foi cancelada com sucesso",
    CancelTradeFail: "Falha em cancelar essa oferta, por favor, tente novamente mais tarde",
    AcceptTradeFail: "Falha em aceitar essa oferta, por favor, tente novamente mais tarde",
    PlayerTradeBanner: "Troque recursos com outros jogadores",
    PlayerTradeResource: "Recurso",
    PlayerTradeAmount: "Quantidade",
    PlayerTradePrice: "Preço $",
    PlayerTradeValue: "Valor $",
    PlayerTradeWaiting: "Aguardando...",
    UseTradeCenterPrice: "Use Trade Center Price",
    AddTrade: "Adicionar proposta",
    ActiveTrades: "Ofertas ativas",
    AcceptTrade: "Aceitar",
    CancelTrade: "Cancelar",
    RefundTrade: "Reembolsar",
    RefundTradeSuccess: "This trade has been refunded: %{resource} has been refunded to your trade center",
    RefundTradeFail: "Failed to refund this trade, please try again later",
    ClaimTrade: "Reivindicar",
    RefreshTrade: "Atualizar",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    FailedToCheckActiveTrade: "Failed to check active player trades, please try again later",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeValidRange: "Alcance: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Can Afford",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transport and store any resources and with lower fuel cost",
    PowerBankChargeSpeed: "Velocidade de recarga",
    PowerBankPowerLeft: "Energia restante",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ExcludeBuildingsShutdown: "Exclude buildings that are shut down",
    ColorTheme: "Tema de cor",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Vale do Silício",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Revolução industrial",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Desmatamento",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "This will hide resource movement (those tiny dots) by default and only show the movement when you select a building",
    PowerBankLeft: "Armazenamento de energia restante",
    ColorThemeEditor: "Editor de Esquema de Cor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Salvar",
    ColorThemeEditorReset: "Restaurar",
    ColorThemeEditorResetAll: "Restaurar tudo",
    NewMessageMentions: "Uma nova mensagem menciona você: %{message}",
    HideChatMentions: "Esconder menções no bate-papo",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "Você só pode aceitar um acordo a cada %{time} segundos",
    DowngradeBuilding: "Rebaixar",
    CancelTradeConfirmDialogTitle: "Cancelar essa troca?",
    CancelTradeConfirmDialogYes: "Sim",
    CancelTradeConfirmDialogNo: "Não",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Adicionar rota",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Mostrar no Mapa",
    WarehouseRemoveRoute: "Remover",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Nível %{level}",
    Surplus: "Surplus",
    Production: "Produção",
    Consumption: "Consumo",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Bandeira do Jogador",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    WarehouseOutwardFuelSave: "Free Delivery",
    WarehouseOutwardFuelSaveDesc: "Warehouses provide the same fuel save on outward transportation as well",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Resources tend to spawn in clusters</li><li>Warehouse provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Termos de serviço",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Editora de mangá",
    Manga: "Mangá",
    AnimeStudio: "Estúdio de anime",
    Anime: "Anime",
    PlayerTradeAction: "Ação",
    PlayerTradeBuy: "Comprar",
    PlayerTradeSell: "Vender",
    PlayerTradeBid: "Bid",
    PlayerTradeAsk: "Ask",
    CancelTradeConfirmDialogDescV2:
        "Cancelling this trade will refund %{percent} of the resource/cash. Resources will be refunded to Trade Center warehouse",
    ClaimTradeSuccessV2: "Your trade has been claimed successfully: %{cashOrResource}",
    AcceptTradeSuccessV2: "Esse acordo foi aceito por você: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Melhor que o preço de mercado",
    ResourceExplorer: "Explorador de recursos",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explorar",
    ProductionSettings: "Production Settings",
    PlayerTradeQuotaDesc: "💡 Player trade quota is %{percent} of your market cap, it resets when the market updates",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Game Guides",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ShowProfitBreakdown: "Show Profit Breakdown",
    HideProfitBreakdown: "Hide Profit Breakdown",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Custo de combustível",
    BuildingProfit: "Lucro",
    RestoreBackup: "Restaurar",
    SteamLogin: "Entrar pela Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Entrar",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "International Export Trade",
    FreeTransportToTradeCenterDesc:
        "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "Armazenado: %{amount}",
    PlayerTradeFillValue: "Valor",
    FiberFactory: "Fábrica de fibra",
    Fiber: "Fibra",
    Achievements: "Achievements",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Reward: Swiss Money +%{swiss}",
    AchievementsRewardToast: "You have claimed the reward:  Swiss Money +%{swiss}",
    AchievementsClaim: "Claim",
    AchievementsToast: "You have achieved %{name}, claim your reward in Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Forçar sincronização na nuvem do Steam",
    UILoading: "Carregando...",
    UserAuthenticated: "Você está autenticado",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardBySwissPerBuilding: "Current Swiss Money Per Building",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Salvar e Sair do Jogo",
    SaveAndExitDesc:
        "Salvar e Sair do Jogo. Só está disponível na versão da Steam and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Forçar Rolagem",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ResourceExplorer2Desc: "Resource explorers produce 2x output but use 2x power",
    ConstructionCancel: "Cancelar",
    ConstructionPause: "Parar",
    ConstructionResume: "Retomar",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "A construção de um edifício não começará automaticamente - terá que ser iniciada manualmente (Política Gratuita)",
    HighlightUnderConstruction: "...que ainda não foram construídos",
    HighlightUnderLevel10: "...que estão abaixo do nível 10",
    HighlightUnderLevel20: "...que estão abaixo do nível 20",
    HighlightUnderLevel30: "...que estão abaixo do nível 30",
    Logout: "Você está desconectado",
    ConstructionStatusQueueingV2: "Na fila",
    ConstructionStatusPausedV2: "Pausado",
    ConstructionStatusBuildingV2: "Construindo",
    ConstructionStatusUnpaidV2: "Não Pago",
    ConstructionStatus: "Status da Construção",
    ConstructionStart: "Começar",
    CostFree: "Grátis",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Only you",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "increased by %{percent}",
    MarketNewsDecrease: "decreased by %{percent}",
    MarketNewsBuilding: "This building is affected by %{num} news",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    OsloBonusV2:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Impulsionador de recuros",
    BuildWarningTitle: "Construção pode não funcionar",
    BuildWarningTitleDesc: "%{reason}. Tem certeza que deseja construir nesse bloco?",
    BuildWarningBuildAnyway: "Construir de qualquer maneira",
    ResourceBoosterNotWorking: "⛔ Impulsionadores de recursos apenas funcionam próximos a minas",
    ResourceBoosterPercentage:
        "💡 Esta construção recebe %{percent} de impulso de saída de melhorias de recursos adjacentes",
    ResourceBoosterBuildings: "Construções sendo impulsionadas",
    BuildingResourceConversion: "%{resource} Conversão",
    AllTimeSwissMoneyEarned: "Total de Dinheiro Suíço ganho: %{number}",
    BuildingUpgradeCostDivider: "Divisor de custo de melhoria de construção",
    AchievementSoftwareGiant: "Gigante de Software",
    AchievementSoftwareGiantDesc:
        "Construa uma Compania de Software nível 10, Indústria de Sistemas Operacionais nível 10, Compania de Banco de Dados nível 10 e um Navegado de Internet nível 10 no mesmo mapa",
    AchievementSpaceRace: "Corrida espacial",
    AchievementSpaceRaceDesc:
        "Construa uma fábrica de foguetes nível 10, fábrica de satélite nível 10, fábrica de nave estelar nível 10 e uma fábrica de Estação Espacial nível 10 no mesmo mapa",
    AchievementToTheMoon: "Para a Lua",
    AchievementToTheMoonDesc:
        "Construa uma Fazenda de Bitcoin nível 40 e uma Fazenda de Dogecoin nível 40. Tenha 1B em Bitcoin e 1B em Dogecoin",
    ItsAllGreen: "Tudo verde",
    ItsAllGreenDesc: "Tenha 50 linha de produção sem nenhum déficit",
    DeepInRed: "Afundado em dívidas",
    DeepInRedDesc: "Tenha 50 linhas de produção em déficit",
    UseScientificNotation: "Usar notação científica",
    UseScientificNotationDesc: "Use notação científica para números maiores que 999.9T",
    LogoutDescV2:
        "Você entrou em outro dispositivo, este dispositivo está desconectado. Você pode entrar novamente, mas o outro dispositivo será desconectado",
    LogBackIn: "Entrar novamente",
    PlayerTradeNowAllowedV2:
        "Trocas com jogadores não estão disponíveis por  %{hour} horas após restaurar/importar o jogo",
    ServerDisconnected:
        "Você está desconectado do servidor, por favor, verifique sua conexão com a internet e reinicie o jogo",
    BuildingUpgradeCostDividerDescV2: "Divide o custo da melhoria de construção por este divisor",
    ResourceBoosterBannerDesc:
        "💡 Atualmente você possui %{number} impulsionadores de recursos - a energia e ciência de cada entrada é escalada junto ao número de impulsionadores de recursos que você possui atualmente",
    ResourceBoosterDesc: "Impulsiona a saída de minas adjacentes",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Dynamite Factory",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Nuclear Missile Factory",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Space Colony",
    SpaceColonyInc: "Space Colony",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    IronSteelZone: "Iron Steel Zone",
    IronSteelZoneDesc:
        "Resource booster provide a %{percent} output bonus to adjacent steel mills or stainless steel plants for each working iron mine it is boosting",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
    ToulouseBonusV2:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
};
