export const PT_BR = {
    Translator: "Tradutor",
    TranslatorName: "Altruista & Bertei",
    Language: "Idioma",
    ThisLanguage: "Português (BR)",
    OK: "OK",
    SteelMill: "Fábrica de aço",
    StainlessSteelPlant: "Fábrica de aço inoxidável",
    CircuitFoundry: "Fundição de circuito",
    IntegratedCircuit: "Circuito integrado",
    OilWell: "Poço Petrolífero",
    Wood: "Madeira",
    LoggingCamp: "Madeireira",
    LumberMill: "Serraria",
    Lumber: "Madeira Serrada",
    Paper: "Papel",
    PaperMill: "Fábrica de papel",
    Book: "Livro",
    BookPublisher: "Editora de Livros",
    OilRefinery: "Refinaria de Petróleo",
    Sell: "Vender",
    Upgrade: "Melhorar",
    Build: "Construir",
    Buildings: "Construções",
    Iron: "Ferro",
    FuelType: "Tipo de combustível",
    FuelCost: "Custo de combustível",
    FuelEconomy: "Economia de combustível",
    FuelInStorage: "%{fuel} armazenado",
    Plastic: "Plástico",
    Petrol: "Petróleo",
    Buy: "Comprar",
    NoLiquidity: "Sem liquidez",
    NoLiquidityTurnOffAutoSell: "Não há liquidez no mercado suficiente por %{res}, venda automática desativada",
    Multiplier: "Multiplicador",
    MultiplierDesc: "A cada 10 níveis, você ganha +1 multiplicador",
    SellBuilding: "Vender Construção",
    PowerGrid: "Malha energética",
    TradeAmount: "Quantidade da negociação",
    SortBy: "Classificar por",
    SortByPrice: "Preço",
    SortByAmount: "Quantidade",
    NotEnoughResources: "Não há recurso suficiente para essa ação",
    Transportation: "Transporte",
    Cash: "Dinheiro",
    Aluminum: "Alumínio",
    ResearchPoint: "Ponto de pesquisa",
    Unlock: "Desbloquear",
    BuildingUnlocked: "%{building} foi desbloqueado",
    Science: "Ciência",
    ScienceFromPowerDesc: "Usinas Elétricas geram uma pequena quantidade de Ciência quando estão gerando energia",
    Culture: "Cultura",
    School: "Escola",
    University: "Universidade",
    Polytechnic: "Escola politécnica",
    Colosseum: "Coliseu",
    WindTurbine: "Turbina eólica",
    Engine: "Motor",
    EngineFactory: "Fábrica de motores",
    CameraFactory: "Fábrica de câmeras",
    Camera: "Câmera",
    Gun: "Arma",
    GunFactory: "Fábrica de Armas",
    Aircraft: "Aeronave",
    AircraftFactory: "Fábrica de Aeronaves",
    Zeppelin: "Zepelim",
    ZeppelinFactory: "Fábrica de Zepelins",
    Tank: "Tanque",
    TankFactory: "Fábrica de Tanques",
    CoalPowerPlant: "Usina Elétrica à Carvão",
    PetrolPowerPlant: "Usina Elétrica à Petróleo",
    Copper: "Cobre",
    Gas: "Gás Natural",
    GasPump: "Bomba de Gás Natural",
    GasPowerPlant: "Usina Elétrica à Gás",
    Missile: "Míssil",
    MissileFactory: "Fábrica de Mísseis",
    Rocket: "Foguete",
    RocketFactory: "Fábrica de foguetes",
    BuildingPermit: "Permissão para construir",
    BuildingPermitDesc:
        "Você tem permissão para %{amount} construções, você já construiu %{amountBuilt} e tem %{amountLeft} sobrando",
    BuildingLocked: "Construção ainda não disponível, você precisa desbloquear no Centro de Pesquisa primeiro",
    MaxBuilders: "Máximo de Construtores",
    MaxBuildersDesc: "Número de edifícios que você pode construir ao mesmo tempo",
    Silicon: "Silício",
    AluminumMine: "Mina de Alumínio",
    CopperMine: "Mina de Cobre",
    SiliconMine: "Mina de Silício",
    IronMine: "Mina de Ferro",
    CoalMine: "Mina de Carvão",
    Headquarter: "Quartel General",
    ResearchLab: "Laboratório de Pesquisa",
    TradeCenter: "Centro Comercial",
    Resources: "Recursos",
    NotEnoughCash: "Dinheiro insuficiente para esta operação",
    NotEnoughSwissMoney: "Não há dinheiro Suiço suficiente para essa operação",
    BuildingNotEnoughFuel: "💡 %{fuel} insuficiente",
    AutoSell: "Venda automática",
    Change: "Trocar",
    StatisticsBureau: "Departamento de estatística",
    LogisticsDepartment: "Departamento de Logística",
    From: "De",
    Top20FuelCost: "Top 20 custos de combustível",
    To: "Para",
    TransportTime: "Tempo de transporte",
    Warehouse: "Armazém",
    TradeWarehouse: "Armazém comercial",
    Coal: "Carvão",
    Video: "Video",
    ClothingFactory: "Fábrica de Roupas",
    Clothes: "Roupas",
    Fashion: "Moda",
    FashionFactory: "Fábrica de Moda",
    VideoFarm: "Fazenda de vídeo",
    SantaFactory: "Fábrica de Papai Noel",
    Santa: "Papai Noel",
    Car: "Carro",
    CarFactory: "Fábrica de Carros",
    Ship: "Navio",
    SolarPanel: "Painel Solar",
    SolarPanelDesc:
        "💡 Painéis Solares trabalham apenas 5 segundos em cada 10 segundos - todos os ciclos estão alinhados",
    WindTurbineDesc: "💡 Turbinas eólicas trabalham apenas 8 segundos em cada 10 segundos - ciclos não estão alinhados",
    Movie: "Filme",
    MovieStudio: "Estúdio de filmagem",
    Sitcom: "Sitcom",
    TVStudio: "Estúdio de Televisão",
    PC: "Computador",
    GameStudio: "Estúdio de Jogos",
    Game: "Jogo",
    ComputerFactory: "Fábrica de Computadores",
    Shipyard: "Estaleiro",
    PowerUsage: "Energia Usada",
    PowerSupply: "Energia Gerada",
    Level: "Nível",
    Power: "Energia",
    CentralBank: "Banco Central",
    ResourceInput: "Entrada",
    ResourceOutput: "Saída",
    ResourceStorage: "Armazém",
    ResourceChange: "Alterar",
    ResourceInOutDesc:
        "💡 Clique nos números de Entrada-Saída acima para realçar as correspondentes construções de saída e entrada",
    MarketUpdateIn: "Atualização de mercado em %{time}",
    Semiconductor: "Semicondutor",
    SemiconductorFactory: "Fábrica de Semicondutor",
    Steel: "Aço",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Fazenda de Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Fazenda de Dogecoin",
    Guitar: "Guitarra",
    GuitarFactory: "Fábrica de guitarras",
    Drum: "Tambor",
    DrumFactory: "Fábrica de tambores",
    RecordingStudio: "Estúdio de Gravação",
    OperaHouse: "Casa de Ópera",
    CoalGasificationPlant: "Planta de Gaseificação de Carvão",
    GasProcessingPlant: "Planta de Processamento de Gás",
    Music: "Música",
    Glass: "Vidro",
    PhoneFactory: "Fábrica de Celular",
    Phone: "Celular",
    GlassFactory: "Fábrica de Vidro",
    Oil: "Petróleo Bruto",
    Chromium: "Cromo",
    ChromiumMine: "Mina de Cromo",
    Uranium: "Urânio",
    EnrichedUranium: "Urânio Enriquecido",
    NuclearPowerPlant: "Usina Nuclear",
    UraniumEnrichmentPlant: "Planta de Enriquecimento de Urânio",
    UraniumMine: "Mina de Urânio",
    Titanium: "Titânio",
    TitaniumMine: "Mina de Titânio",
    TitaniumAlloyPlant: "Planta de Liga de Titânio",
    ChromiumAlloyPlant: "Planta de Liga de Cromo",
    Input: "Entrada",
    PanelPosition: "Posição do painel",
    PanelPositionDesc:
        "Mostrar painel lateral à esquerda, direita ou automático (depende do bloco selecionado atualmente)",
    Output: "Saída",
    OutputCapacity: "Capacidade de saída",
    ResourceDeposit: "Depósito de recursos",
    AdjacentBonus: "Bônus adjacente",
    AdjacentBonusDesc: "Você ganha %{bonus}% de capacidade extra para cada construção adjacente de mesmo tipo operando",
    ConsiderIncreaseProduction: "💡 Considere aumentar a produção de %{resource}",
    AlwaysTransportInput: "Modo de Estoque",
    AlwaysTransportInputTradeCenter: "Sempre exportar",
    AlwaysTransportInputTradeCenterDesc:
        "Sempre transportar recursos ao centro comercial, mesmo se a venda automática estiver desabiltada para este recurso",
    AlwaysTransportInputDesc:
        "Sempre transporte recursos de entrada, mesmo se eles estiverem acima do requisito mínimo de produção",
    ProductionCycleLength: "Ciclo de produção",
    ProductionCycleLengthDesc:
        "Duração de um ciclo de produção, mensurado em segundos. Prolongar o clico irá aumentar a entrada/saída por ciclo consequentemente diminuindo sua prioridade ao buscar recursos de entrada",
    MaxInputDistance: "Distância máxima de entrada",
    MaxInputDistanceDesc:
        "A distância máxima a partir da qual este edifício pode buscar recursos de entrada, medida em número de blocos",
    AutoSellCapacity: "Capacidade de Venda Automática",
    AutoSellCapacityDesc:
        "Quantidade máxima de recursos que a venda automática pode manipular por segundo, por recurso",
    CurrentAutoSellCapacityMultiplier: "Multiplicador atual: x%{n}",
    AutoSellConcurrency: "Simultaneidade de venda automática",
    AutoSellConcurrencyDesc: "Número máximo de recursos que a venda automática pode gerenciar ao mesmo tempo",
    MaxAutoSellConcurrencyReached:
        "Você atingiu o máximo de vendas automáticas simultâneas, desativa uma venda automática para habilitar esta",
    WallStreet: "Wall Street",
    MarketCap: "Valor de mercado",
    MarketCapDesc: "Capitalização total (i.e. valor de mercado) de sua corporação",
    BuildingValuation: "Estimativa da construção",
    BuildingValuationDesc: "Valor total de suas construções, incluindo licenças de construção e atualizações",
    ResourcesValuation: "Estimativa de recursos",
    ResourcesValuationDesc: "Valor total de recursos no seu inventário",
    Battery: "Bateria",
    BatteryFactory: "Fábrica de baterias",
    RatingBuy: "Comprar",
    RatingSell: "Vender",
    SwissShop: "Loja Suíça",
    RatingHold: "Segurar",
    RatingOutperform: "Exceder",
    RatingUnderperform: "Underperform",
    StockRating: "Avaliação de ações",
    JetEngine: "Motor de jato",
    Helicopter: "Helicóptero",
    Lithium: "Lítio",
    LithiumMine: "Mina de Lítio",
    LiionBatteryFactory: "Fábrica de bateria Li-ion",
    HelicopterFactory: "Fábrica de helicóptero",
    Satellite: "Satélite",
    ToyFactory: "Fábrica de brinquedo",
    Toy: "Brinquedo",
    SpaceStation: "Estação Espacial",
    SpaceStationFactory: "Fábrica de estações espaciais",
    OperatingSystem: "Sistema operacional",
    OperatingSystemCompany: "Incorporação Sistema Computacional",
    LinuxDistribution: "Distribuição Linux",
    Internet: "Internet",
    WebBrowser: "Navegador de internet",
    Console: "Console",
    ConsoleFactory: "Fábrica de consoles",
    Train: "Trem",
    TrainFactory: "Fábrica de trens",
    ShoeFactory: "Fábrica de sapatos",
    Shoes: "Sapatos",
    ArtilleryFactory: "Fábrica de artilharia",
    Artillery: "Artilharia",
    SubmarineFactory: "Fábrica de submarinos",
    Submarine: "Submarino",
    Spaceship: "Nave espacial",
    RobotFactory: "Fábrica de robôs",
    Robot: "Robô",
    SpaceshipFactory: "Fábrica de nave espacial",
    SatelliteFactory: "Fábrica de satélites",
    JetEngineFactory: "Fábrica de motor de jatos",
    StockRatingDesc:
        "Consenso de classificação de ações de analistas de Wall Street, que afeta sua capitalização de mercado e é atualizado junto com o mercado",
    OfflineEarning: "Ganhos offline",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Tempo de ganho offline",
    OfflineEarningTimeDesc: "Você ganhará ganhos off-line por até esse limite",
    BuyPermit: "Comprar permissão",
    Settings: "Configurações",
    Sound: "Efeito sonoro",
    SoundDesc: "Ative o efeito de som como o clique ou som de erro",
    MusicDesc: "Ligue a música: It's Not Over 'Til The Bossa Nova de Shane Ivers (https://www.silvermansound.com)",
    Credits: "Créditos",
    Icons: "Ícones",
    MisplacedBuilding: "⛔ Esta %{building} não está colocada em cima do depósito de recursos correto",
    HighlightBuildings: "Destacar construções",
    HighlightTurnedOff: "... que estão desativadas",
    HighlightStockpileModeOn: "...que têm o modo de estoque ativado",
    HighlightProductionCycleNotDefault: "...quem têm o clico de prodição > 1",
    HighlightMaxInputDistanceNotDefault: "...que têm distância máxima de entrada < ∞",
    HighlightNotMakingProfit: "... que não geram lucro",
    NBuildingsAreHighlighted: "%{n} construção(ões) são destacadas",
    TurnOffProduction: "Desativar",
    TurnOffProductionDesc:
        "Desligue a produção da construção. A construção não transportará mais recursos nem usará energia",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Ilimitado",
    Transport: "Transporte",
    TileModifier: "Tile Modifier",
    ShowAllModifiers: "Mostrar todos modificadores",
    HideAllModifiers: "Esconder todos modificadores",
    NumberOfBuildings: "Numero de construções que você tem",
    ShowContent: "Mostrar conteúdo",
    HideContent: "Esconder conteúdo",
    BuyExpansionPack: "Comprar por %{price}",
    Cities: "Cidades",
    InputStrategy: "Estratégia de Entrada",
    InputStrategyClose: "Mais próximo",
    InputStrategyCloseDesc: "Prefira o armazém mais próximo que tenha recursos suficientes",
    InputStrategyFar: "Mais distante",
    InputStrategyFarDesc: "Prefira o armazém mais distante que tenha recursos suficientes",
    InputStrategyAmount: "Quantidade",
    InputStrategyAmountDesc: "Prefira o armazém com maior quantidade de recursos, independente da distância",
    FuelCostSave: "Economia de combustível",
    FuelCostSaveDescV2:
        "Warehouses save a certain percentage of fuel for transporting resources compared to other buildings, the higher the level, the more the save",
    SoftwareCompany: "Empresa de programas",
    Software: "Programa",
    ScreenFactory: "Fábrica de telas",
    Screen: "Tela",
    JoinDiscord: "Junte-se ao nosso servidor Discord para novidades, dicas e discussões",
    ClaimOfflineEarning: "Reivindicar ganhos offline",
    OfflineTime: "Tempo desligado",
    Minutes: "%{time}min",
    MaxUpgrade: "Melhoria máxima",
    MaxUpgradeDesc: "Você chegou na melhoria máxima. Parabéns!",
    ClaimAmount: "Dinheiro +%{amount}",
    EffectiveTime: "Tempo Efetivo",
    EffectiveTimeDesc: "Seu tempo efetivo de ganho offline é limitado a %{time}min.",
    BuildSearchPlaceholder: "Digite construção ou recurso para pesquisar",
    MineOverlayWarning: "%{building} não é afetado pelo modificador de bloco",
    WholesaleCenter: "Centro de atacado",
    OrderFrom: "Ordem de %{name}",
    ExpireIn: "Expira em",
    Reward: "Recompensa",
    PerSecond: "%{time}/s",
    PolicyPoint: "Ponto de Política",
    PolicyPointDesc: "💡 Quanto mais políticas ativas, mais custo para cada política",
    NextOrderIn: "Próximo pedido em",
    FillOrder: "Preencher pedido",
    RejectOrder: "Passar",
    WholesaleCenterLocked:
        "Você precisa de pelo menos %{required} recursos diferentes para desbloquear o Centro de atacado. Você tem apenas %{current} recursos",
    OrderFilled: "O pedido de %{from} foi preenchido com sucesso!",
    PolicyCenter: "Centro Político",
    NewOrder: "Um novo pedido de %{from} chegou, por favor, verifique no Centro de atacado",
    Policies: "Políticas",
    PolicyNotEnoughTime: "Você não tem pontos de política suficientes para esta política",
    WholesaleCenterOrderFasterDesc:
        "A Central de atacado recebe pedidos 2x mais rápido e o tamanho do pedido é 2x maior",
    PolicyOilWellPowerx2: "Sobrecarregar Poço de Petróleo",
    PolicyOilWellPowerx2Desc: "Poços de petróleo produzem 2x mais óleo e usam 2x mais energia",
    HalfTransportSpeed: "Diminua A Velocidade Para Economizar",
    HalfTransportSpeedDesc: "A velocidade de transporte é reduzida em 25% e o custo do combustível é reduzido em 25%",
    RefineryMoreOil: "Mais Petróleo Mais Problemas",
    RefineryMoreOilDesc: "Refinarias de petróleo produzem 50% mais gasolina e 50% menos plástico",
    RefineryMorePlastic: "Mais Plásticos Mais Problemas",
    RefineryMorePlasticDesc: "Refinarias de petróleo produzem 50% menos gasolina e 50% mais plástico",
    FreeOilTransportDesc:
        "O transporte de petróleo não custa combustível, mas os poços de petróleo usam 2x mais energia",
    SuperSteelMill: "Corações de Ferro",
    SuperSteelMillDesc: "As siderúrgicas usam 50% menos carvão, 25% mais ferro e 25% mais energia",
    AlSemiconductor: "Circuito de IA",
    AlSemiconductorDesc: "As fundições de circuito usam alumínio em vez de cobre",
    CostSaver: "Economia de Custos",
    CostSaverDesc: "Se a entrada de um edifício custar mais do que sua produção, desligue a produção",
    CostSaverBuildingDesc:
        "A política de redução de custos está ativa, a produção será ligada / desligada automaticamente com base em sua lucratividade",
    CostSaverBuildingWarning:
        "A política de redução de custos está ativa, você não pode alterar manualmente a produção",
    GlassUseCoal: "Vidro Negro",
    GlassUseCoalDesc: "As fábricas de vidro usam 50% mais carvão e 50% menos silício",
    AdjacentBonusOnlyOutput: "Bônus Adjacente Plus",
    AdjacentBonusOnlyOutputDesc:
        "O bônus adjacente não requer mais entrada, mas usa mais energia e é apenas 50% eficaz",
    IronMine2xOutput: "Ferro Pesado",
    IronMine2xOutputDesc: "As minas de ferro produzem 2x o ferro, mas o transporte de ferro custa 2x o combustível",
    SolarPanelAlwaysWork: "O Sol Nunca Se Põe",
    SolarPanelAlwaysWorkDesc: "Os painéis solares funcionam 100% do tempo, mas produzem 60% menos energia",
    SteelScience: "Conhecimento através do aço",
    SteelScienceDesc: "As usinas siderúrgicas usam 2x mais insumos e produzem ciência extra",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "Se a capacidade de produção de um recurso for insuficiente, compre a quantidade em falta do Centro Comercial automaticamente (se o recurso tiver venda automática, ele será ignorado)",
    ShoppingSpreeTradeCenterDesc:
        "💡 A política da Maratona de Compras está ativada, o Centro Comercial comprará automaticamente os recursos em falta",
    ExtraPolicyPoints: "Lobista Político",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "As fábricas de liga de cromo não usam lítio, mas usam 2x ferro em vez disso",
    DoubleTileModifier: "Poder da Natureza",
    TileModifierOutputOnly: "Modificador de Bloco Plus",
    GasPlantPetrol: "Liquidificador de Gás",
    GasPlantPetrolDesc: "Usinas a gás usam gás extra para produzir gasolina",
    CoalPlantFuel: "Liquidificador de carvão",
    CoalPlantFuelDesc: "Usinas de carvão usam carvão extra para produzir gasolina",
    Welcome: "Bem-vindo",
    SeeTutorialAgain: "Refazer Tutorial",
    HelpTranslateTheGame: "Ajude a traduzir o jogo 🌐",
    NextTutorial: "Próximo",
    Tutorial1:
        "Industry Idle é um <em> jogo </em> de gestão de recursos em que você constrói fábricas🏭, produz bens📦 e faz dinheiro💸.<br><br>Vamos repassar alguns conceitos básicos para você começar - não vai demorar muito, eu prometo.",
    Tutorial2:
        "Todas as construções precisam de energia⚡, você tem a <em>turbina eólica</em> que gera energia. Você pode ver sua produção de energia atual no lado esquerdo da barra superior.<br><br>Você deve ter notado que as turbinas eólicas só funcionam <em>80%</em> do tempo. Você pode considerar a construção de outros tipos de usinas de energia que geram energia estável.",
    Tutorial3:
        "Você tem um monte de <em>depósitos de recursos</em> no mapa. Para extrair recursos, você deve construir minas ⛏️ <em>em cima</em> do depósito correspondente.<br><br>Por exemplo, você tem um <em>poço de petróleo 🛢️</em> que extrai <em>petróleo</em> de um depósito.<br></br>Os depósitos de recursos são ilimitados - não há necessidade de se preocupar com o esgotamento. Além das minas, outros edifícios podem ser construídos em qualquer bloco vazio.",
    Tutorial5:
        "Para ganhar dinheiro, você precisa exportar seus recursos através do centro de comércio. Para fazer isso, basta ligar <em>Venda Automática</em> para este recurso.<br></br>Você também pode comprar recursos do centro comercial. Lembre-se, <em>se você compra um recurso, você vai aumentar o preço</em> e se você vender um recurso, você vai baixar o preço.<br><br>O mercado é <em>volátil</em> e o preço📈 muda regularmente.",
    Tutorial6:
        "Para construir novos edifícios, você precisa primeiro de desbloquear ele no <em>centro de pesquisa🧪</em>. O laboratório de pesquisa também converte ciência em pontos de pesquisa.<br><br>Sua turbina eólica (e outras plantas de energia) produzem uma pequena quantidade de ciência enquanto funcionam. E você também pode construir escolas🏫 e outros edifícios dedicados para impulsionar a ciência mais tarde.<br><br>Agora que você aprendeu o básico, comece a construir sua economia! Aqui está um pouco de <em>dinheiro💸</em> e <em>petróleo⛽</em> para te dar um salto inicial.",
    WelcomePlay: "Tocar",
    WelcomePlayMuted: "Tocar (🔇Música)",
    Chat: "Bate-Papo",
    RestoreFromBackup: "Restaurar do backup",
    RestoreFromBackupFail: "Falha ao restaurar o backup do Steam Cloud: você tem certeza que há um backup?",
    RestoreFromBackupTitle: "Certeza?",
    RestoreFromBackupDesc:
        "Normalmente, você não precisa restaurar do backup em nuvem, a menos que seu salvamento local seja perdido. O backup na nuvem é um pouco mais antigo que o seu save local",
    ChangeName: "Trocar",
    SaveName: "Salvar",
    NameValidationRule: "Seu nome só pode conter letras e números e ter entre 5-15 caracteres",
    NameValidationRuleProfanity: "Seu nome não deve conter profanidade",
    ChatMessageRateLimit: "Você só pode enviar uma nova mensagem de bate-papo a cada 10 segundos",
    NameSaved: "Seu nome foi alterado com sucesso",
    NoMessages: "Sem mensagens novas",
    Leaderboard: "Tabela de Classificação",
    Name: "Nome",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2: "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building is determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Modo economia de energia",
    OfflineModeDesc:
        "Não é possível conectar ao servidor: ganhos offline não serão gerados. Por favor, verifique sua conexão à internet",
    OptOut: "Opt Out",
    OptIn: "Resetar e habilitar",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptIn: "Resetar e ativar a tabela de classificação",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "O vídeo de recompensa não foi concluído",
    OfflineEarningDoubleSuccess: "Você dobrou seus ganhos offline",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Destacar "%{type}"',
    HighlightInput: "🔍 Destacar %{type} entradas",
    HighlightOutput: "🔍 Destacar %{type} saídas",
    RunOutIn: "Acaba em %{time}",
    SwissBank: "Banco na Suíça",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Se você começar em uma nova cidade, você receberá %{money} 💵",
    RestorePurchases: "Restaurar compras",
    RestorePurchasesSuccess: "Suas compras foram restauradas",
    RestorePurchasesFailed: "Suas compras não foram restauradas",
    ExpansionPacks: "Pacotes de expansão",
    ExpansionPack1: "Pacote de expansão 1",
    RequireExpansionPack1: "Pacote de expansão 1",
    RequireExpansionPack1Desc: "Somente disponível pelo pacote de expansão 1",
    RequireAnyExpansionPack: "Pacotes de expansão exclusivos",
    RequireAnyExpansionPackDesc: "Este recurso requer que você tenha pelo menos um dos pacotes de expansão",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Esconder banner do Discord",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Esconder bate-papo",
    PurchaseFailed: "A compra não foi concluída",
    PurchaseSteamContinue: "Conclua sua compra no Steam",
    PurchaseSuccess: "A compra foi concluída, obrigado pelo seu apoio",
    PrestigeCurrency: "Dinheiro Suíço 💵",
    RestartDesc:
        "💡 Quer apenas reiniciar? Você pode tocar em Começar em uma nova cidade acima e escolher sua cidade atual",
    PrestigeGoBack: "Voltar",
    ProductionMultiplier: "Multiplicador de Produção",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    PrestigeAlertTitle: "Você tem certeza?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Receber",
    Cancel: "Cancelar",
    SaveFileCorrupted: "Arquivo de save corrompido",
    LoadGameError: "Falha em carregar jogo",
    LoadGameErrorMessage: "Mensagem de erro: %{message}",
    LoadGameErrorDesc: "Por favor, verifique sua conexão com a internet. Se o problema persistir, contate o suporte",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    CashIn: "Cash In",
    CurrentCity: "Cidade atual",
    CashInDesc:
        "Você receberá esse valor em sua conta bancária na Suíça se começar em uma nova cidade. É baseado na capitalização de mercado da sua empresa e deve atingir %{amount} antes de você ganhar dinheiro suíço",
    CitySize: "Tamanho do mapa",
    GridType: "Tipo de Grade",
    StartInThisCity: "Começar em %{city}",
    CityBonus: "Bônus da Cidade",
    ResourceTilePercentage: "Percentual de Blocos de Recurso",
    MapSquareGrid: "Quadrada",
    MapHexGrid: "Hexagonal",
    Stockholm: "Estocolmo",
    Rotterdam: "Roterdã",
    Oslo: "Oslo",
    StPetersburg: "São Petersburgo",
    Hamburg: "Hamburgo",
    HamburgBonus:
        "<li>Fábricas de Zepelim são desbloqueadas de início</li><li>Fábricas de Semicondutor têm 2x de produtividade</li><li>Estaleiros têm 2x de capacidade</li><li>Fábrica de Carro têm 2x de capacidade</li><li>Fábrica de bateria Li-ion são desbloqueadas de início</li>",
    Toulouse: "Toulouse",
    Rome: "Roma",
    RomeBonus:
        "<li>Coliseus são desbloqueados de início</li><li>Coliseus têm 2x de produtividade</li><li>Começa com o Centro Político no nível 5</li><li>Casas de Ópera têm 2x de capacidade</li><li>Estúdios de Gravação também produzem cultura</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Começa com o Laboratório de Pesquisa no nível 5</li><li>Escolas politécnicas são desbloqueadas de início</li><li>Escolas politécnicas têm 2x de capacidade</li><li>Escolas têm 2x de capacidade</li><li>Universidade têm 2x de produtividade</li>",
    HideNotProducing: "Esconder recursos que não estão sendo produzidos",
    SortByStorage: "Armazenamento",
    SortByName: "Nome",
    PlayerTrade: "Troca entre jogadores",
    AddTradeFail: "Falha em adicionar sua oferta",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Sua oferta foi adicionada com sucesso",
    ClaimTradeFail: "Falha em reinvindicar essa oferta, por favor, tente novamente mais tarde",
    CancelTradeSuccess: "Sua oferta foi cancelada com sucesso",
    CancelTradeFail: "Falha em cancelar essa oferta, por favor, tente novamente mais tarde",
    AcceptTradeFail: "Falha em aceitar essa oferta, por favor, tente novamente mais tarde",
    PlayerTradeBanner: "Troque recursos com outros jogadores",
    PlayerTradeResource: "Recurso",
    PlayerTradeAmount: "Quantidade",
    PlayerTradePrice: "Preço $",
    PlayerTradeValue: "Valor $",
    PlayerTradeWaiting: "Aguardando...",
    AddTrade: "Adicionar proposta",
    AcceptTrade: "Aceitar",
    CancelTrade: "Cancelar",
    ClaimTrade: "Reivindicar",
    FailedToImportSave: "Falha ao importar seu carregamento",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    PlayerTradeQuotaExceed: "Este comércio excedeu sua cota",
    PlayerTradeValidRange: "Alcance: %{min} ~ %{max}",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transport and store any resources and with lower fuel cost",
    PowerBankChargeSpeed: "Velocidade de recarga",
    PowerBankPowerLeft: "Energia restante",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ColorTheme: "Tema de cor",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Vale do Silício",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Revolução industrial",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Desmatamento",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    PowerBankLeft: "Armazenamento de energia restante",
    ColorThemeEditor: "Editor de Esquema de Cor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Salvar",
    ColorThemeEditorReset: "Restaurar",
    ColorThemeEditorResetAll: "Restaurar tudo",
    NewMessageMentions: "Uma nova mensagem menciona você: %{message}",
    HideChatMentions: "Esconder menções no bate-papo",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    AcceptTradeFailRateLimit: "Você só pode aceitar um acordo a cada %{time} segundos",
    DowngradeBuilding: "Rebaixar",
    WarehouseAddInput: "Adicionar rota",
    WarehouseTapToSelect: "Toque no mapa para selecionar...",
    WarehouseFindOnMap: "🔍 Mostrar no Mapa",
    WarehouseRemoveRoute: "Remover",
    WarehouseAddRouteFail: "Falha ao adicionar rota: o bloco selecionado não é uma fonte válida",
    LevelN: "Nível %{level}",
    Surplus: "Surplus",
    Production: "Produção",
    Consumption: "Consumo",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    PlayerCountryFlag: "Bandeira do Jogador",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Literatura Científica",
    BookPublisherScienceDesc: "Editoras de livros produzem ciência em vez de cultura",
    BatteryFuelEconomy: "Bateria recarregável",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Recursos com custo especial de transporte",
    FreeTransportCost: "Recursos com Custo de Transporte Gratuito",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Recursos tendem em aparecer em grupos</li><li>Armazéns providenciam 50% mais economia de combustível</li><li>Construção única: editora de mangá</li><li>Construção única: estúdio de anime</li><li>Fábricas de Semicondutor têm 2x de produtividade</li><li>Fábrica de bateria Li-ion têm 2x de capacidade</li><li>Fábricas de bateria são desbloqueadas de início</li><li>Fábricas de bateria têm 2x de capacidade</li><li>Melhora em 100% da economia de combustível ao utilizar baterias</li><li>Fábricas de bateria não utilizam carvão</li><li>Começa com 100k de bateriass</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Termos de serviço",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Editora de mangá",
    Manga: "Mangá",
    AnimeStudio: "Estúdio de anime",
    Anime: "Anime",
    PlayerTradeAction: "Ação",
    PlayerTradeBuy: "Comprar",
    PlayerTradeSell: "Vender",
    PlayerTradeBid: "Oferta",
    PlayerTradeAsk: "Pedir",
    ClaimTradeSuccessV2: "Sua negociação foi reivindicada com sucesso: %{cashOrResource}",
    AcceptTradeSuccessV2: "Esse acordo foi aceito por você: %{cashOrResource}",
    ResourceExplorer: "Explorador de recursos",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explorar",
    ProductionSettings: "Configurações de produção",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Guia do jogo",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Custo de combustível",
    BuildingProfit: "Lucro",
    RestoreBackup: "Restaurar",
    SteamLogin: "Entrar pela Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Entrar",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Dojo de Kung-Fu",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Dojo de Tai-Chi",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Comércio Internacional de Exportação",
    FreeTransportToTradeCenterDesc:
        "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
    TaiChi10xCulture: "Pérola do Oriente",
    PlayerTradeYouHave: "Armazenado: %{amount}",
    PlayerTradeFillValue: "Valor",
    FiberFactory: "Fábrica de fibra",
    Fiber: "Fibra",
    Achievements: "Conquistas",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Recompensa: dinheiro suiço +%{swiss}",
    AchievementsRewardToast: "Você reivindicou a recompensa: dinheiro suiço +%{swiss}",
    AchievementsClaim: "Reivindicar",
    AchievementsToast: "You have achieved %{name}, claim your reward in Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Forçar sincronização na nuvem do Steam",
    UILoading: "Carregando...",
    UserAuthenticated: "Você está autenticado",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Algoritmo de preços do mercado único - preços e a avaliação das ações seguem uma distribuição normal (curva em sino)</li><li>Atualizações de mercado e redefinições de cotas comerciais são duas vezes mais frequentes (toda hora)</li><li>Pesquisas podem ser desbloqueadas via troca de recursos</li><li>Construção única: Dojo de Kung-Fu</li><li>Construção única: Dojo de Tai-Chi</li><li>Aumento de 50% no número máximo de negociações com jogadores permitidas</li><li>Começa com mais 1 simultaneidade de venda automática</li><li>Política única: Comércio Internacional de Exportação</li><li>Política única: Pérola do Oriente</li><li>O centro de atacado só precisa de 4 recursos para ser desbloqueado</li><li>Começa com 100M de dinheiro</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Tela cheia",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Ultima atualização em",
    DetroitBonusV3:
        "<li>Fábricas de motor são desbloqueadas de início</li><li>Fábricas de motor têm 2x de produtividade</li><li>Fábricas de carro têm 2x de capacidade</li><li>Fábricas de carro utilizam gás natural em vez de petróleo</li><li>Carros são transportados gratuitamente</li><li>A política Nikola Tesla é gratuita</li><li>Fábricas de trem têm 2x de capacidade</li>",
    SaveAndExit: "Salvar e Sair do Jogo",
    SaveAndExitDesc:
        "Salvar e Sair do Jogo. Só está disponível na versão da Steam and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Automatizar venda",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Preço local: %{price}",
    ChatForceScroll: "Forçar Rolagem",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Explorador de recursos 2.0",
    ConstructionCancel: "Cancelar",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "A construção de um edifício não começará automaticamente - terá que ser iniciada manualmente (Política Gratuita)",
    HighlightUnderConstruction: "...que ainda não foram construídos",
    HighlightUnderLevel10: "...que estão abaixo do nível 10",
    HighlightUnderLevel20: "...que estão abaixo do nível 20",
    HighlightUnderLevel30: "...que estão abaixo do nível 30",
    Logout: "Você está desconectado",
    ConstructionStatusQueueingV2: "Na fila",
    ConstructionStatusPausedV2: "Pausado",
    ConstructionStatusBuildingV2: "Construindo",
    ConstructionStatusUnpaidV2: "Não Pago",
    ConstructionStatus: "Status da Construção",
    ConstructionStart: "Começar",
    CostFree: "Grátis",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Novidades do mercado",
    MarketNewsApplyToYou: "Apenas você",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "aumentou em %{percent}",
    MarketNewsDecrease: "diminuiu em %{percent}",
    MarketNewsBuilding: "Este edifício é afetado por %{num} noticias",
    StockholmBonusV2:
        "<li>Construção única: Produtoras musicais</li><li>Madeireiras têm 2x de saída</li><li>Fábricas de papel são desbloqueadas de início</li><li>Fundições de circuito têm 2x de produtividade</li><li>A política Literatura Científica é gratuita</li>",
    FreeOilTransportV2: "Transporte Elétrico de Petróleo",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Produtora Musical",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Velocidade de movimento do construtor",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Impulsionador de recuros",
    BuildWarningTitle: "Construção pode não funcionar",
    BuildWarningTitleDesc: "%{reason}. Tem certeza que deseja construir nesse bloco?",
    BuildWarningBuildAnyway: "Construir de qualquer maneira",
    ResourceBoosterNotWorking: "⛔ Impulsionadores de recursos apenas funcionam próximos a minas",
    ResourceBoosterBuildings: "Construções sendo impulsionadas",
    BuildingResourceConversion: "%{resource} Conversão",
    AllTimeSwissMoneyEarned: "Total de Dinheiro Suíço ganho: %{number}",
    BuildingUpgradeCostDivider: "Divisor de custo de melhoria de construção",
    AchievementSoftwareGiant: "Gigante de Software",
    AchievementSoftwareGiantDesc:
        "Construa uma Compania de Software nível 10, Indústria de Sistemas Operacionais nível 10, Compania de Banco de Dados nível 10 e um Navegado de Internet nível 10 no mesmo mapa",
    AchievementSpaceRace: "Corrida espacial",
    AchievementSpaceRaceDesc:
        "Construa uma fábrica de foguetes nível 10, fábrica de satélite nível 10, fábrica de nave estelar nível 10 e uma fábrica de Estação Espacial nível 10 no mesmo mapa",
    AchievementToTheMoon: "Para a Lua",
    AchievementToTheMoonDesc:
        "Construa uma Fazenda de Bitcoin nível 40 e uma Fazenda de Dogecoin nível 40. Tenha 1B em Bitcoin e 1B em Dogecoin",
    ItsAllGreen: "Tudo verde",
    ItsAllGreenDesc: "Tenha 50 linha de produção sem nenhum déficit",
    DeepInRed: "Afundado em dívidas",
    DeepInRedDesc: "Tenha 50 linhas de produção em déficit",
    UseScientificNotation: "Usar notação científica",
    UseScientificNotationDesc: "Use notação científica para números maiores que 999.9T",
    LogoutDescV2:
        "Você entrou em outro dispositivo, este dispositivo está desconectado. Você pode entrar novamente, mas o outro dispositivo será desconectado",
    LogBackIn: "Entrar novamente",
    PlayerTradeNowAllowedV2:
        "Trocas com jogadores não estão disponíveis por  %{hour} horas após restaurar/importar o jogo",
    ServerDisconnected:
        "Você está desconectado do servidor, por favor, verifique sua conexão com a internet e reinicie o jogo",
    BuildingUpgradeCostDividerDescV2: "Divide o custo da melhoria de construção por este divisor",
    ResourceBoosterDesc: "Impulsiona a saída de minas adjacentes",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Fábrica de Dinamite",
    Dynamite: "Dinamite",
    NuclearMissileFactory: "Fabrica de Missil Nuclear",
    NuclearMissile: "Míssil Nucelar",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Colônia especiaL",
    SpaceColonyInc: "Space Colony",
    ProjectVostok: "Projeto Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Minas de urânio têm 2x de saída</li><li>Plantas de enriquecimento de urânio têm 2x de capacidade</li><li>Transportar urânio utiliza 50% menos combustível</li><li>Armas são transportadas gratuitamente</li><li>Projeto Vostok têm 2x de capacidade</li>",
    ToulouseBonusV2:
        "<li>Minas de titânio têm 2x de saída</li><li>Plantas de enriquecimento de urânio têm 2x de produtividade</li><li>Fábricas de motor de jato têm 2x de capacidade</li><li>Fábricas de aeronave têm 2x de produtividade</li><li>Fábricas de foguete têm 2x de capacidade</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Salvar e recarregar o jogo",
    ResearchLabCultureInput: "The Renaissance",
    ResearchLabCultureInputDesc: "Research Lab has 2x capacity but takes culture as the extra input",
    GasPumpx2Output: "High Pressure Gas Pump",
    GasPumpx2OutputDesc: "Natural gas pumps have 2x output but use 2x power",
    LeaderboardValuationPerHour: "Total Valuation Per Hour",
    LeaderboardValuationPerHourPerSwiss: "Total Valuation Per Hour Per Swiss",
    LeaderboardValuationPerHourNewPlayers: "Total Valuation Per Hour (< 1000 Swiss)",
    LeaderboardValuationPerBuilding: "Building Valuation Per Building",
    BuildingCustomColor: "Cor da construção",
    BuildingCustomColorReset: "Resetar",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Every 4 different types of buildings give 1 free building permit</li><li>Unique policy: Production Diversification</li><li>Unique building: Maple Syrup Factory</li><li>Free maple syrup transport</li><li>Unique fuel type: Maple Syrup</li><li>2x player trade quota when trading Uranium and Enriched Uranium</li><li>Unique free policy: Syrup Plastic</li><li>Toy factories have 2x productivity</li><li>Game studios have 2x capacity</li>",
    MapExtraPermitDesc: "You get %{number} free building permits from the map's unique bonus",
    OsloBonusV3:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 8 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    ResourceBoosterPercentageV2: "💡 This amount includes %{percent} boost from adjacent resource boosters",
    MapleSyrup: "Maple Syrup",
    MapleSyrupFactory: "Maple Syrup Factory",
    SyrupPlastic: "Syrup Plastic",
    SyrupPlasticDesc: "All buildings that input plastic use maple syrup instead",
    ResourceBoosterSupplyChain: "Supply Chain Booster",
    ResourceBoosterSupplyChainDesc:
        "Resource boosters use 2x power and science, but for each working mine a resource booster is boosting, it also provides capacity boost to adjacent factories that consume the mine's output (the factory should only consume deposits)",
    ProductionDiversification: "Production Diversification",
    ProductionDiversificationDesc: "Each different type of building gives 1% extra capacity to all buildings",
    ExtraPolicyPointsDescV2: "Policy center has 2x policy points conversion capacity",
    PowerRequired: "Power Required",
    AchievementVancouver100: "Sap Seller",
    AchievementVancouver100Desc: "Earn 100 Swiss Money in Vancouver in a single run",
    AchievementVancouver500: "Syrup Savant",
    AchievementVancouver500Desc: "Earn 500 Swiss Money in Vancouver in a single run",
    AchievementVancouver1000: "Canuck Conqueror",
    AchievementVancouver1000Desc: "Earn 1000 Swiss Money in Vancouver in a single run",
    BarbariansAtTheGate: "Barbarians At The Gate",
    BarbariansAtTheGateDesc: "Use 1 trillion worth of player trade quota between market updates",
    DiversifiedProductions: "Diversified Productions",
    DiversifiedProductionsDesc: "Build 100 different types of buildings on a single map",
    RealEstateTycoon: "Real Estate Tycoon",
    RealEstateTycoonDesc: "Have 400 buildings on a single map",
    ResourceExplorer2DescV2:
        "Resource explorers produce 2x output but use 2x power. Resource explorers can be boosted by resource boosters if Supply Chain Booster policy is active and the booster has an adjacent mine of the same output",
    NoTileModifier: "Earth Is Flat",
    NoTileModifierDesc:
        "All tile modifiers are zero. This policy will deactivate Nature's Power and Tile Modifier Plus policies",
    DoubleTileModifierDescV2:
        "All tile modifiers' effect x2 - both positive and negative. This policy will deactivate Earth Is Flat policy",
    TileModifierOutputOnlyDescV2:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective. This policy will deactivate Earth Is Flat policy",
    QuickLinks: "Quick Links",
    GetHelp: "Ajuda",
    GetHelpBeginnerGuides: "Guia do Iniciate",
    GetHelpSteamGuides: "Outras Guias na Steam",
    GetHelpInGameChat: "Pergunte no chat do jogo",
    GetHelpDiscord: "Junte-se ao nosso Discord",
    GetHelpWiki: "Comunidade Wiki",
    SelectATile: "Select a Tile",
    PledgeAmount: "Pledge %{amount}",
    PledgeValue: "Valor $%{amount}",
    TotalPledgedValue: "Total Pledged Value",
    TotalPledgedValueDesc:
        "Your first pledge counts towards the crowdfunding goal. Subsequent pledges increase total pledged value but do not count towards the goal",
    ReturnOnPledge: "Return On Pledge",
    CrowdfundingEndIn: "End in %{time}",
    ClaimCrowdfundingReward: "Claim Reward %{amount}",
    PledgeSuccessful: "You have pledged %{amount} to this crowdfunding",
    CrowdfundingClaimSuccessful: "You have claimed %{amount} cash",
    CrowdfundingAlreadyPledged: "You've Already Pledged",
    CrowdfundingAlreadyPledgedDesc:
        "You can pledge more resources, which will increase your total pledged value (and potential return), but won't count towards crowdfunding goal",
    WholesaleCenterProducingOnly: "Parceiros de Atacado",
    WholesaleCenterProducingOnlyDesc:
        "Os pedidos do centro de atacado contêm apenas recursos que estão sendo produzidos no momento (você também precisa estar produzindo o número de recursos necessários para desbloquear o centro de atacado)",
    SoftwareCompiler: "Software Compiler",
    SearchEngine: "Search Engine",
    SearchEngineCompany: "Search Engine Company",
    Navy: "Navy",
    NavyCommand: "Navy Command",
    Battleship: "Battleship",
    BattleshipFactory: "Battleship Factory",
    ResourceMovementHide: "Always Hide",
    ResourceMovementShow: "Always Show",
    ResourceMovementViewport: "In Viewport",
    ResourceMovementHighlight: "On Highlight",
    ResourceMovementLine: "Line Only",
    ResourceMovement: "Resource Movement",
    ResourceMovementDesc:
        "You can choose when to show the resource movement (dots). Hiding it can improvement performance",
    CrowdfundingCashInWarning: "You have pending crowdfunding pledges - starting in a new city will forfeit them",
    ResourceBoosterBannerDescV2:
        "💡 You currently have %{number} resource boosters - the science input of each is scaled to the number of resource boosters you currently have",
    CrowdfundingId: "Crowdfunding %{id}",
    PatchNotes: "Patch Notes",
    PatchNotesDesc: "Read what's new in this update",
    PanelPositionLeft: "Left (Docked)",
    PanelPositionLeftFloat: "Left (Float)",
    PanelPositionRight: "Right (Docked)",
    PanelPositionRightFloat: "Right (Float)",
    PanelPositionAuto: "Auto",
    TimePlayed: "Time Played",
    ValuationPerHour: "Valuation Per Hour",
    HighPowerPriority: "High Power Priority",
    HighPowerPriorityDesc: "Switching this on will make the building draw power before other buildings",
    IndustryZone: "Industry Zone",
    IndustryZoneDesc: "Combine adjacent buildings that forms a supply chain and save building permits",
    IndustryZoneMaxBuildingLevel: "Max Building Level",
    IndustryZoneNotWorkingDesc:
        "All of its adjacent buildings should form a supply chain and are not part of other industry zones",
    IndustryZoneNoAdjacentBonus: "This building is part of an industry zone and does not have adjacent bonus",
    PlayerTradeAutoClaim: "Automatically claim filled trades",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "Cloud Steaming",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "Super Computer Lab",
    SuperComputer: "Super Computer",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "SkyNet",
    RobocarFactory: "Robocar Factory",
    Robocar: "Robocar",
    WarehouseBuildingPermitSave: "Warehouse Permit Act",
    WarehouseBuildingPermitSaveDesc: "Every two warehouses provide one free building permit",
    PolicySearchPlaceholder: "Digite uma política para pesquisar",
    SwissUpgrade: "Upgrade suíço",
    SwissUpgradeDesc: "As atualizações suíças são permanentes e serão aplicadas se você começar em uma nova cidade",
    SwissBoost: "Boost suíço",
    SwissBoostDesc:
        "Os impulsos suíços afetam apenas sua corrida atual - e serão redefinidos se você começar em uma nova cidade",
    ProductionMultipliers: "Production Multipliers",
    MultiplierMapUniqueBonus: "Map Unique Bonus",
    MultiplierSwissUpgrade: "Swiss Upgrade (Permanent)",
    MultiplierSwissBoost: "Swiss Boost (This Run)",
    SwissBoostCostDivider: "Swiss Boost Cost Divider",
    SwissBoostCostDividerDesc: "Divide Swiss boost cost by this divider - only applies to multiplier/divider upgrades",
    AirForceCommand: "Air Force Command",
    AirForce: "Air Force",
    StealthFighterFactory: "Stealth Fighter Factory",
    StealthFighter: "Stealth Fighter",
    ArmyCommand: "Army Command",
    Army: "Army",
    GreenPeacekeeper: "Green Peacekeeper",
    GreenPeacekeeperDesc: "Make army, navy, air force or space force with only renewable power plants (wind/solar)",
    DotComTycoon: "DotCom Tycoon",
    DotComTycoonDesc:
        "Build a level 10 Social Network Inc, level 10 Search Engine Company, level 10 SkyNet Inc and level 10 Musify Inc on the same map",
    ConstructionNotResearched: "Not Researched",
    OfflineEarningDescV2: "Offline earning depends on your current research, production and auto sell",
    HighSpeedWarehouse: "High Speed Warehouse",
    HighSpeedWarehouseDesc:
        "Warehouses have 2x capacity and 50% faster inward and outward transport speed, but use 2x power",
    IndustryZoneMultiplierDesc: "Industry Zone Bonus",
    IndustryZoneMultiplierSwissBoost: "Industry Zone Capacity Booster",
    EarningPerMinuteV2: "Offline Earning Rate",
    OfflineResearchPoint: "Offline Research Point",
    WholesaleCenterOrderFasterV2: "Bigger Faster Wholesale",
    OfflineResearchSwissBoost: "Offline Research",
    OfflineResearchSwissBoostDesc:
        "Research points are generated while you are offline (according to your Research Lab level, Science in your warehouse and offline earning time)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Unique building: chip manufacturer</li><li>Unique building: FaceApp Inc</li><li>Unique building: Bitcoin Miner</li><li>All buildings that consume silicon have max tile modifier</li><li>Solar panels generate 2x power</li><li>Silicon mines have 2x output</li>",
    RotterdamBonusV2:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>Earth Is Flat policy is free</li>",
    ChipManufacturer: "Chip Manufacturer",
    SnapTokInc: "SnapTok Inc",
    FaceAppInc: "FaceApp Inc",
    BitcoinMiner: "Bitcoin Miner",
    GalvanicBatteryFactory: "Galvanic Battery Factory",
    BaseProductionMultiplier: "Base Production",
    ShowBreakdown: "Show Breakdown",
    HideBreakdown: "Hide Breakdown",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Each tier of production chain inside an industry zone provides this capacity boost to all the buildings in the same zone",
    IndustryZoneBuildingPermitDesc:
        "If an industry zone has N tiers of productions, it will provide N-2 building permits for free",
    CrowdfundingBackersReturn: "Backers: %{backers}, Current Return: %{return}",
    CrowdfundingBackersNeeded: "%{backers} More Backer(s)",
    CrowdfundingReturnBonus: "+%{return} Return",
    ReturnOnPledgeDescV2:
        "Your total return equals to total pledged value multiplied by return rates from all resources. More backers of a resource will improve its return",
    PlayerTradeQuotaDescV2:
        "💡 Quota is the amount of the resource you can trade. The monetary value equals to %{percent} of your market cap and it resets when the market updates. The more your trade's price deviates from your trade center price, the more quota you need",
    AchievementSanJose100: "Venture Hobbyist",
    AchievementSanJose100Desc: "Earn 100 Swiss Money in San Jose in a single run",
    AchievementSanJose500: "Venture Enthusiast",
    AchievementSanJose500Desc: "Earn 500 Swiss Money in San Jose in a single run",
    AchievementSanJose1000: "Venture Capitalist",
    AchievementSanJose1000Desc: "Earn 1000 Swiss Money in San Jose in a single run",
    AchievementCrowdfundingTycoon: "Crowdfunding Tycoon",
    AchievementCrowdfundingTycoonDesc: "Pledge 1Qa worth of resources in a single crowdfunding",
    AchievementCashIsKing: "Cash Is King",
    AchievementCashIsKingDesc: "Have 1Qa cash at hand in a single run",
    AchievementPowerTycoon: "Power Tycoon",
    AchievementPowerTycoonDesc: "Generate 1GW power in a single run",
    PlayerTradeFilteringNResources: "Filtering %{n} Resource(s)",
    PlayerTradeFilterResources: "Filter Resources",
    PlayerTradeFilterClear: "Clear Filters",
    ResourceExplorerAll: "Explore All Resources",
    ResourceExplorerAllDesc:
        "Resource explorers can produce all resources, including the ones that are not on the map (this DOES NOT unlock the relevant technologies)",
    ShowResourceInTopBar: "Show In Top Bar",
    LeaderboardOptOutDescV2:
        "You will no longer appear in the leaderboard. This will also disable player trade. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    PolicyPointNoCopperDesc:
        "💡 This map doesn't have copper deposits, you can activate Al Circuit policy to unlock further technologies",
    Pumpkin: "Pumpkin",
    PumpkinBattery: "Pumpkin Battery",
    PumpkinBatteryDesc: "All buildings that consume battery use pumpkin instead (FREE POLICY)",
    PumpkinSteel: "Pumpkin Steel",
    PumpkinSteelDesc: "All buildings that consume steel use pumpkin instead (FREE POLICY)",
    RequireExpansionPack2: "Expansion Pack 2",
    ExpansionPack2: "Expansion Pack 2",
    RequireExpansionPack2Desc: "This is only available for Expansion Pack 2",
    Reindeer: "Reindeer",
    ReindeerSilicon: "Reindeer Silicon",
    ReindeerSiliconDesc: "All buildings that consume silicon use reindeer instead (FREE POLICY)",
    ReindeerAluminum: "Reindeer Aluminum",
    ReindeerAluminumDesc: "All buildings that consume aluminum use reindeer instead (FREE POLICY)",
    SantaClauseIsComing: "Santa Clause is Coming",
    SantaClauseIsComingDesc:
        "Santa factories consume reindeer and toy and produce santa, science and culture. Santa factories have max tile modifier. Toy factories produce reindeer in addition to toy (FREE POLICY)",
    MetaRebranding: "Meta Rebranding",
    MetaRebrandingDesc:
        "Social Network Inc is renamed to Meta Inc and consumes internet, game, super computer, bitcoin and dogecoin instead",
    MetaInc: "Meta Inc",
    ImportSave: "Import Save",
    ExportSave: "Export Save",
    ClearMyTrades: "Clear My Trades",
    SaveVersionTooNew:
        "Your save is from %{saveVersion} but your game is %{gameVersion}. Please update your game first",
    LeaderboardByFlag: "Tabluation By Player Flag",
    LeaderboardByMap: "Tabluation By Map",
    LeaderboardByFlagPlayerFlag: "Flag",
    LeaderboardByFlagPayerCount: "#",
    LeaderboardByFlagPayerValuationPerHour: "V/H",
    LeaderboardByFlagPayerSwissMoney: "Swiss",
    PlayerTradePriceFilter: "Price Filter",
    PlayerTradeFilterBetterThanMarket: "Better than Market",
    PlayerTradeFilterAll: "All",
    PlayerTradeFilterBestPrice: "Best Price",
    CrowdfundingTotalPledgdeValueTooLarge:
        "Your Total Pledged Value for a crowdfunding cannot exceed your current Market Cap",
    BuildingSourceAuto: "Auto Source",
    BuildingSourceManual: "🔍 Manual Source",
    BuildingSourceReset: "Reset",
    BuildingSourceSelecting: "Tap On Map...",
    BuildingSourceSetOverride: "Override",
    BuildingSourceFallback: "Manual Source Fallback",
    BuildingSourceFallbackDesc:
        "How should the building transport its input if the manual source doesn't have enough? Skip - do not transport; drain - transport what's left; new - use auto source to find a new source",
    BuildingSourceFallbackSkip: "Skip",
    BuildingSourceFallbackDrain: "Drain",
    BuildingSourceFallbackAuto: "New",
    BuildingSourceFallbackMarker: "(Fallback)",
    BuildingSourceFallbackMarkerDesc: "The manual source doesn't have enough resource, fallback strategy is active",
    BuildingSourceInvalid: "Your selected source is invalid, please select a valid tile",
    RandomIsland: "Random Island",
    RandomIslandBonus:
        "<li>The map is randomized every time you start</li><li>Map size, grid type, resource deposits and unique bonuses are all randomly rolled</li><li>There is a 5-minute cool down - the reroll only happens minimum 5 minutes apart</li>",
    RandomIslandBonusDesc: "The unique bonus on Random Island is rerolled every time you start on the map",
    RandomIslandBonusCapacity: "%{building} has %{multiplier}x capacity",
    RandomIslandBonusProductivity: "%{building} has %{multiplier}x productivity",
    RandomIslandBonusResources: "Resource deposits on this map: %{deposits}",
    ValuationPerActiveMinute: "Valuation Per Active Minute",
    Perth: "Perth",
    GV: "Geothermal Vent",
    GeothermalPowerPlant: "Geothermal Power Plant",
    AdjacentExplorer: "Adjacent Explorer",
    AdjacentExplorerDesc:
        "A resource explorer produce 2x output if it's adjacent to the resource it's producing (FREE POLICY)",
    FactoryMining: "Factory Mining",
    FactoryMiningDesc:
        "A factory can mine the deposit directly from the tile if it consumes the same deposit (FREE POLICY)",
    FactoryMiningBanner: "This building is mining %{resource} directly from this tile",
    WarehouseSourceWeight: "Weight: %{weight}",
    YAxisStartsFromZero: "Y Axis From 0",
    YAxisStartsFromZeroDesc: "All graphs' Y axis will always start from 0 instead of being auto adjusted",
    OwnDLC: "Own %{number}x Expansion(s)",
    GeneralServerSuccessMessage: "Your request has completely successfully",
    GeneralServerErrorMessage: "Error from the server: %{error}",
    WarehouseInputRoutes: "Input Routes",
    WarehouseOutputRoutes: "Output Routes",
    InputCapacity: "Capacidade de entrada",
    MultipleSources: "Multiple Sources",
    MultipleSourcesDesc:
        "Allow the building to potentially transport resources from multiple sources during a production cycle",
    Water: "Water",
    KansasCity: "Kansas City",
    Dam: "Hydro Dam",
    DamDesc: "Hydro dam turns adjacent empty tiles into water tile",
    Farmland: "Farmland",
    FarmlandDesc: "Produce crops on top of a water tile",
    Storage: "Storage",
    Rice: "Rice",
    Corn: "Corn",
    Wheat: "Wheat",
    Soybean: "Soybean",
    Sugarcane: "Sugarcane",
    Vegetable: "Vegetable",
    FarmlandProduce: "Produce",
    FarmlandOfflineFarming: "Offline Farming",
    FarmlandOfflineFarmingDesc:
        "Farmland built on top of natural water source produce while you are offline. Subject to offline earning time and affected by Swiss upgrades",
    FarmlandProductionDesc: "💡 Farmlands only work 5 seconds out of every 10 seconds - all cycles are aligned",
    WaterPump: "Water Pump",
    Greenhouse: "Greenhouse",
    GreenhouseDesc: "Produce a crop of your choice",
    WaterEntityLevelTooHighDesc:
        "Your building level is higher than the adjacent hydro dam level. Please upgrade your hydro dam",
    AirLiquidizer: "Air Liquidizer",
    CapacitorFactory: "Capacitor Factory",
    Capacitor: "Capacitor",
    OfflineProduction: "Offline Production",
    OfflineProductionDesc: "Transporting capacitors to this building will allow it to run when you are offline",
    Moderator: "Moderator",
    FlourMill: "Flour Mill",
    Flour: "Flour",
    FlourMillAdjustMix: "Adjust Flour Mix",
    RiceFlour: "100% Gluten Free",
    RiceFlourDesc: "Flour mills consumes rice instead of wheat",
    Bread: "Bread",
    Bakery: "Bakery",
    Fodder: "Fodder",
    FodderFactory: "Fodder Factory",
    SugarRefinery: "Sugar Refinery",
    RefinedSugar: "Refined Sugar",
    ShowSupplyChain: "Show Supply Chain",
    ShowSupplyChainDesc:
        "When you highlight a building, show the whole supply chain from all upstream and downstream buildings",
    Cake: "Cake",
    ChooseARecipe: "Choose A Recipe",
    ChickenFarm: "Chicken Farm",
    Chicken: "Chicken",
    Egg: "Egg",
    CowFarm: "Cow Farm",
    Beef: "Beef",
    Milk: "Milk",
    DairyFactory: "Dairy Factory",
    Cheese: "Cheese",
    Cookie: "Cookie",
    Butter: "Butter",
    UnlockAtLevel: "Unlock At Level %{level}",
    FastFoodChain: "Fast Food Chain",
    Burger: "Burger",
    Sandwich: "Sandwich",
    StandbyMode: "Standby Mode",
    StandbyModeDesc:
        "The game's simulation will continue to run in the background but it will not render any graphics. This should significant reduce GPU usage and moderately reduce CPU usage as well",
    StandbyModeOn: "Standby Mode On",
    StandbyModeOnDesc: "The game is running in the background. Tap anywhere to exit standby mode",
    PigFarm: "Pig Farm",
    Pork: "Pork",
    SausageFactory: "Sausage Factory",
    Sausage: "Sausage",
    Hotdog: "Hotdog",
    BatchOperationDesc: "This will apply to %{number} buildings(s). Do you want to continue?",
    BatchOperationResult: "Your batch operation has completed for %{success} buildings(s)",
    StreamingMakeMeDiscoverable: "Make Me Discoverable",
    StreamingMakeMeDiscoverableDesc:
        "Allow other players to watch your gameplay. The connection is peer to peer and only your gameplay is streamed. Microphone or webcam will not be accessed",
    StreamAutoApprove: "Public Stream",
    StreamAutoApproveDesc: "Allows players to join your stream with needing you to approve individual request",
    StreamingWatch: "Watch",
    StreamingStop: "Stop",
    StreamingPlayerDisconnected: "%{player} has disconnected from the stream",
    StreamingPlayerRejected: "%{player} has declined your stream request",
    StreamingPlayerRequested: "%{player} has requested to watch your stream, go to Headquarter to accept or reject",
    StreamingSettings: "Steaming Settings",
    StreamingAvailableStreams: "Available Streams",
    StreamingAudience: "Viewers",
    StreamingStopStream: "Stop Streaming For This Viewer",
    StreamingAcceptStream: "Accept",
    StreamingRejectStream: "Reject",
    StreamingStopStreamDesc: "Stop Streaming For This Viewer",
    StreamingConnectionFailed:
        "Failed to establish a peer connection - it is very likely your network doesn't support P2P connection",
    Pizza: "Pizza",
    StreamingStartRecord: "Start Recording",
    StreamingRecordCamera: "Record A Directed's Cut",
    StreamingRecordCameraDesc:
        "Record a 10s pre-directed sequence - the camera will set to max zoom and slowly zoom out",
    StreamingStopRecord: "Stop Recording",
    StreamingRecordingReady: "Recording Is Ready",
    StreamingRecordingReadyDesc: "You can save your recording file and play it with a compatible video player",
    StreamingRecordingSave: "Save As",
    Lantern: "Lantern",
    LunarNewYear22: "Year of The Tiger",
    LunarNewYear22Desc:
        "All buildings that consume paper will use Lantern instead and will have 2x capacity. Paper mills become Paper Academy and produce culture instead",
    PaperAcademy: "Paper Academy",
    FriedRice: "Fried Rice",
    Highlight: "🔍 Highlight",
    BatchMode: "Batch Mode",
    BatchModeAll: "All",
    BatchModeAdjacent: "Adjacent",
    BatchModeCluster: "Cluster",
    BatchUpgradeToLevelX: "To Level %{level}",
    ApplyToBatch: "Apply To %{batch}",
    BatteryRecycler: "Battery Recycler",
    BatteryShell: "Battery Shell",
    StartInANewCity: "Start In A New City",
    StartInANewCityFinePrint: "(Or Restart Your Current City)",
    BatteryFuelDesc:
        "💡 After batteries are used as fuel, they will become battery shells. You can build Battery Recyclers to recycle or recharge them",
    FriedChicken: "Fried Chicken",
    Coffee: "Coffee",
    Cocoa: "Cocoa",
    CornSyrup: "Liquid Sugar",
    CornSyrupDesc: "Sugar refineries produce refined sugar with corn instead of sugarcane",
    Crop: "Crop",
    SaoPaulo: "São Paulo",
    FishPond: "Fish Pond",
    Fish: "Fish",
    LoadGameErrorRetry: "Retry",
    LoadGameErrorHardReset: "Hard Reset",
    ImportGameDesc: "%{import} import(s) in the last %{days} days",
    ExportSaveWarning:
        "DO NOT share your save file with others (except for the developer) - your save file contains your account identifiers and will allow others to take over your account",
    FontSizeScaling: "Font Size Scaling",
    FontSizeScalingDesc: "Change the UI font size scale. Some UI elements might look out of place. REQUIRES RELOAD",
    FrozenVegetable: "Frozen Vegetable",
    MilkPowder: "Milk Powder",
    CannedFish: "Canned Fish",
    CocoaPowder: "Cocoa Powder",
    FrozenChicken: "Frozen Chicken",
    FrozenPork: "Frozen Pork",
    CannedBeef: "Canned Beef",
    FoodProcessingPlant: "Food Processing Plant",
    KansasCityBonus:
        "<li>Farmlands and greenhouses produce 2x corn</li><li>Free corn transportation</li><li>For each level, hydro dams give a 5% boost to adjacent farmlands</li><li>Every 2 farmlands give 1 free building permit</li><li>The Sun Never Sets policy also makes farmland work 100% of the time (including offline)</li><li>2x player trade quota when trading crops</li><li>Food processing plants are unlocked</li>",
    KansasCityHydroDamBoost: "Kansas City unique bonus: this hydro dam provides %{boost} boost to adjacent farmlands",
    PerthGeothermalPowerPlantBoost:
        "Perth unique bonus: this geothermal power plant provides %{boost} boost to adjacent buildings that produce steel",
    PerthBonus:
        "<li>Building spinners rotate clockwise, which is opposite to other cities</li><li>Unique deposit: Geothermal vent</li><li>Unique building: Geothermal Power Plant</li><li>Unique policies: Adjacent Explorer (FREE), Factory Mining (FREE)</li>",
    Biofuel: "Biofuel",
    SaoPauloBonus:
        "<li>Unique fuel: Biofuel</li><li>Pig, cow and chicken farms produces extra biofuel</li><li>Unique building: Biofuel Power Plant</li><li>Unique building: Cristo Redentor</li><li>Resource boosters can boost pig, cow and chicken farms</li><li>Logging camps produce 2x wood</li><li>Lumber mills have 2x capacity</li><li>Frozen chicken, frozen pork and canned beef have 2x trading quota</li>",
    BiofuelPowerPlant: "Biofuel Power Plant",
    CristoRedentor: "Cristo Redentor",
    CristoRedentorBanner:
        "Cristo Redentor provides adjacent bonus to any building that has lower or equal level. Its culture consumption grows exponentially if you build more",
    CristoRedentorDesc: "Consumes culture and provide adjacent bonus to any building",
};
