export const TR = {
    Translator: "Translator",
    TranslatorName: "takipsizad",
    Language: "Türkçe",
    ThisLanguage: "English",
    OK: "Tamam",
    SteelMill: "Çelik fabrikası",
    StainlessSteelPlant: "Stainless Steel Plant",
    CircuitFoundry: "Devre Dökümhanesi",
    IntegratedCircuit: "Entegre Devre",
    OilWell: "Petrol Kuyusu",
    Wood: "Odun",
    LoggingCamp: "Logging Camp",
    LumberMill: "Kereste fabrikası",
    Lumber: "Kereste",
    Paper: "Kağıt",
    PaperMill: "Kağıt fabrikası",
    Book: "Book",
    BookPublisher: "Kitap yayınlayayıcısı",
    OilRefinery: "Yağ Rafinerisi",
    Sell: "Sat",
    Upgrade: "Yükselt",
    Build: "İnşa et",
    Inspect: "İncele",
    Buildings: "Yapılar",
    Iron: "Demir",
    Actions: "Eylemler",
    FuelType: "Yakıt türü seç",
    FuelCost: "Yakıt maliyeti",
    FuelConsumption: "%{fuel} Tüketiliyor",
    FuelEconomy: "Yakıt ekonomisi",
    FuelProduction: "%{fuel} Kullanımda",
    FuelInStorage: "%{fuel} Depoda",
    Plastic: "Plastik",
    FuelSurplus: "%{fuel} Fazla",
    Petrol: "Petrol",
    Buy: "Sat",
    NoLiquidity: "Likidite yok",
    NoLiquidityTurnOffAutoSell: "Pazarda %{res} için yeterli likidite yok, otomatik satış kapatıldı",
    Multiplier: "Katlayıcı",
    MultiplierDesc: "Her 10 seviyede bir +1 çarpanı alırsınız ",
    SellBuilding: "Yapıyı sat",
    PowerGrid: "Güç ızgarası",
    TradeAmount: "Ticaret miktarı",
    SortBy: "Göre sırala",
    SortByPrice: "Fiyat",
    SortByAmount: "Miktar",
    NotEnoughResourcesForTrade: "Bu ticaret için Ticaret Merkezi'nde yeterli kaynaklar yok",
    NotEnoughResources: "Bu işlem için yeterli kaynak (lar) yok",
    Transportation: "Taşıma",
    Cash: "Para",
    Aluminum: "Alüminyum",
    ResearchPoint: "Research Point",
    Unlock: "Unlock",
    BuildingUnlocked: "%{building} ın kilidi açıldı ",
    Science: "Bilim",
    ScienceFromPowerDesc: "Power plants produce a small amount of Science when generating power",
    Culture: "Kültür",
    School: "Okul",
    University: "Üniverste",
    Polytechnic: "Polytechnic",
    Colosseum: "Colosseum",
    WindTurbine: "Rüzgar türbini",
    Engine: "Motor",
    EngineFactory: "Motor Fabrikası",
    CameraFactory: "Kamera Fabrikası",
    Camera: "Kamera",
    Gun: "Silah",
    GunFactory: "Silah fabrikası",
    Aircraft: "Uçak",
    AircraftFactory: "Uçak fabrikası",
    Zeppelin: "Zeplin",
    ZeppelinFactory: "Zeplin Fabrikası",
    Tank: "Tank",
    TankFactory: "Tank Factory",
    CoalPowerPlant: "Coal Power Plant",
    PetrolPowerPlant: "Petrol Power Plant",
    Copper: "Copper",
    Gas: "Natural Gas",
    GasPump: "Natural Gas Pump",
    GasPowerPlant: "Gas Power Plant",
    Missile: "Füze",
    MissileFactory: "Füze Fabrikası",
    Rocket: "Roket",
    RocketFactory: "Roket Fabrikası",
    BuildingPermit: "Yapı izini",
    BuildingPermitDesc:
        "%{amount} binalar için izininiz var, ama %{amountBuilt} oluşturdunuz ve %{amountLeft} kaldı", 
    BuildingLocked: "Bina henüz mevcut değil, önce araştırma laboratuarında kilidini açmanız gerekir " ,
    BuildQueue: "Yapı Kuyruğu",
    BuildQueueDesc: "Number of buildings currently in queue",
    MaxBuilders: "Max Builders",
    MaxBuildersDesc: "Number of buildings you can construct at the same time",
    Silicon: "Silikon",
    AluminumMine: "Alimünyum Madeni",
    CopperMine: "Bakır Madeni",
    SiliconMine: "Silikon Madeni",
    IronMine: "Demir Madeni",
    CoalMine: "Kömür madeni",
    Headquarter: "Merkez",
    ResearchLab: "Araştırma Laboratuvarı",
    TradeCenter: "Trade Center",
    Resources: "Resources",
    NotEnoughPower: "💡 Not enough power, consider increasing power supply",
    NotEnoughFuel: "Not enough %{fuel} for this operation",
    NotEnoughCash: "Not enough cash for this operation",
    NotEnoughSwissMoney: "Not enough Swiss money for this operation",
    BuildingNotEnoughFuel: "💡 Not enough %{fuel}",
    AutoSell: "Auto Sell",
    SellAll: "Sell All",
    Change: "Change",
    StatisticsBureau: "Statistics Bureau",
    LogisticsDepartment: "Logistics Department",
    From: "From",
    Top20FuelCost: "Top 20 Fuel Cost",
    To: "To",
    TransportTime: "Transport Time",
    TopN: "Top %{n}",
    Warehouse: "Warehouse",
    TradeWarehouse: "Freight Warehouse",
    Coal: "Coal",
    Video: "Video",
    ClothingFactory: "Clothing Factory",
    Clothes: "Clothes",
    Fashion: "Fashion",
    FashionFactory: "Fashion Factory",
    VideoFarm: "Video Farm",
    SantaFactory: "Santa Factory",
    Santa: "Santa",
    Car: "Car",
    CarFactory: "Car Factory",
    Ship: "Ship",
    SolarPanel: "Solar Panel",
    SolarPanelDesc: "💡 Solar Panels only work 5 seconds out of every 10 seconds - all cycles are aligned",
    WindTurbineDesc: "💡 Wind Turbines only work 8 seconds out of every 10 seconds - cycles are not aligned",
    Movie: "Movie",
    MovieStudio: "Movie Studio",
    Sitcom: "Sitcom",
    TVStudio: "TV Studio",
    PC: "PC",
    GameStudio: "Game Studio",
    Game: "Game",
    ComputerFactory: "Computer Factory",
    Shipyard: "Shipyard",
    PowerUsage: "Power Usage",
    PowerSupply: "Power Supply",
    PowerSurplus: "Power Surplus",
    Level: "Level",
    Power: "Power",
    CentralBank: "Central Bank",
    ResourceInput: "In",
    ResourceOutput: "Out",
    ResourceStorage: "Storage",
    ResourceChange: "Change",
    ResourceInOutDesc: "💡 Tap on Out-In numbers above to highlight the corresponding output and input buildings",
    ResourceChart: "Resource Chart",
    MarketUpdateIn: "Next market price update in %{time}",
    Income: "Income",
    Semiconductor: "Semiconductor",
    SemiconductorFactory: "Semiconductor Factory",
    Steel: "Steel",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Farm",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Farm",
    Guitar: "Guitar",
    GuitarFactory: "Guitar Factory",
    Drum: "Drum",
    DrumFactory: "Drum Factory",
    RecordingStudio: "Recording Studio",
    OperaHouse: "Opera House",
    CoalGasificationPlant: "Coal Gasification Plant",
    GasProcessingPlant: "Gas Processing Plant",
    Music: "Music",
    Glass: "Glass",
    PhoneFactory: "Phone Factory",
    Phone: "Phone",
    GlassFactory: "Glass Factory",
    Oil: "Oil",
    Chromium: "Chromium",
    ChromiumMine: "Chromium Mine",
    Uranium: "Uranium",
    EnrichedUranium: "Enriched Uranium",
    NuclearPowerPlant: "Nuclear Power Plant",
    UraniumEnrichmentPlant: "Uranium Enrichment Plant",
    UraniumMine: "Uranium Mine",
    Titanium: "Titanium",
    TitaniumMine: "Titanium Mine",
    TitaniumAlloyPlant: "Titanium Alloy Plant",
    ChromiumAlloyPlant: "Chromium Alloy Plant",
    Input: "Input",
    PanelPosition: "Panel Position",
    PanelPositionDesc: "Show side panel on left, right or auto (depends on current selected tile)",
    InputCapacity: "Input Capacity",
    InputCapacityPerCycle: "Input Capacity / Cycle",
    Output: "Output",
    OutputCapacity: "Output Capacity",
    OutputCapacityPerCycle: "Output Capacity / Cycle",
    ResourceDeposit: "Resource Deposit",
    RecommendedBuilding: "💡 This tile has %{resource} deposit",
    AdjacentBonus: "Adjacent Bonus",
    AdjacentBonusDesc: "You get %{bonus}% extra capacity for every adjacent working building of the same type",
    ConsiderIncreaseProduction: "💡 Consider increase %{resource} production",
    AlwaysTransportInput: "Stockpile Mode",
    AlwaysTransportInputTradeCenter: "Always Export",
    AlwaysTransportInputTradeCenterDesc:
        "Always transport resources to Trade Center, even if auto sell is not enabled for that resource",
    AlwaysTransportInputDesc: "Always transport input resources, even if they are above minimal production requirement",
    ProductionCycleLength: "Production Cycle",
    ProductionCycleLengthDesc:
        "Duration of one production cycle, measured in seconds. Lengthening the cycle will increase the input/output per cycle accordingly thus lower its priority when fetching input resources",
    MaxInputDistance: "Max Input Distance",
    MaxInputDistanceDesc:
        "The maximum distance this building can fetch input resources from, measured in number of tiles",
    AutoSellCapacity: "Auto Sell Capacity",
    AutoSellCapacityDesc: "Max amount of resources auto sell can handle per second, per resource",
    CurrentAutoSellCapacityMultiplier: "Current multiplier: x%{n}",
    AutoSellConcurrency: "Auto Sell Concurrency",
    AutoSellConcurrencyDesc: "Max number of resources auto sell can handle at the same time",
    MaxAutoSellConcurrencyReached:
        "You have reached maximum auto sell concurrency, turn off another auto sell to enable this one",
    CannotSellBuilding: "Cannot sell building at this time",
    WallStreet: "Wall Street",
    MarketCap: "Market Cap",
    MarketCapDesc: "Total market capitalization (i.e. market value) of your corporation",
    BuildingValuation: "Building Valuation",
    BuildingValuationDesc: "Total value of your buildings, including building permits and upgrades",
    ResourcesValuation: "Resources Valuation",
    ResourcesValuationDesc: "Total value of resources in your inventory",
    Battery: "Battery",
    BatteryFactory: "Battery Factory",
    RatingBuy: "Buy",
    RatingSell: "Sell",
    SwissShop: "Swiss Shop",
    RatingHold: "Hold",
    RatingOutperform: "Outperform",
    RatingUnderperform: "Underperform",
    StockRating: "Stock Rating",
    JetEngine: "Jet Engine",
    Helicopter: "Helicopter",
    Lithium: "Lithium",
    LithiumMine: "Lithium Mine",
    LiionBatteryFactory: "Li-ion Battery Factory",
    HelicopterFactory: "Helicopter Factory",
    Satellite: "Satellite",
    ToyFactory: "Toy Factory",
    Toy: "Toy",
    SpaceStation: "Space Station",
    SpaceStationFactory: "Space Station Factory",
    OperatingSystem: "Operating System",
    OperatingSystemCompany: "Operating System Inc",
    LinuxDistribution: "Linux Distribution",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Console",
    ConsoleFactory: "Console Factory",
    Train: "Train",
    TrainFactory: "Train Factory",
    ShoeFactory: "Shoe Factory",
    Shoes: "Shoes",
    ArtilleryFactory: "Artillery Factory",
    Artillery: "Artillery",
    SubmarineFactory: "Submarine Factory",
    Submarine: "Submarine",
    Spaceship: "Spaceship",
    RobotFactory: "Robot Factory",
    Robot: "Robot",
    SpaceshipFactory: "Spaceship Factory",
    SatelliteFactory: "Satellite Factory",
    JetEngineFactory: "Jet Engine Factory",
    StockRatingDesc:
        "Stock rating consensus from Wall Street analysts, which affects your market cap and is updated together with the market",
    InterestRate: "Overnight Interest Rate",
    InterestRateDesc: "Interest you earn on your market capitalization while you are offline",
    OfflineEarning: "Offline Earning",
    OfflineEarningDesc: "Offline Earning depends on your market cap and interest rate",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline Earning Time",
    OfflineEarningTimeDesc: "You will earn offline earning for up to this threshold",
    BuyPermit: "Buy Permit",
    NotEnoughBuildingPermit: "Not enough building permits. Please buy more to build new buildings",
    MovingAverage: "Moving Average",
    MovingAverageDesc: "Show moving average of change of resources instead of real-time change",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Turn on zoom support. Use your mouse wheel to zoom. Current zoom is %{zoom}",
    AllowZoomMobileDesc: "Turn on zoom support. You can pinch to zoom. Current zoom is %{zoom}",
    Settings: "Settings",
    Sound: "Sound Effect",
    SoundDesc: "Turn on sound effect like click or error sound",
    AutoHighlight: "Auto Highlight",
    AutoHighlightDesc: "Automatically highlight buildings of the same type when you select a building",
    MusicDesc: "Turn on music: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Icons",
    MisplacedBuilding: "⛔ This %{building} is not placed on top of the correct resource deposit",
    Left: "Left",
    Right: "Right",
    Auto: "Auto",
    HighlightBuildings: "Highlight Buildings",
    HighlightTurnedOff: "...that are shut down",
    HighlightStockpileModeOn: "...that have stockpile mode on",
    HighlightProductionCycleNotDefault: "...that have production cycle > 1",
    HighlightMaxInputDistanceNotDefault: "...that have max input distance < ∞",
    HighlightNotMakingProfit: "...do not make a profit",
    NBuildingsAreHighlighted: "%{n} building(s) are highlighted",
    OnlyToWarehouse: "Only for Warehouses",
    OnlyToWarehouseDesc: "Only warehouses can transport resources from this building",
    TurnOffProduction: "Shutdown",
    TurnOffProductionDesc:
        "Turn off the building's production. The building will no longer transport resources and use power",
    ApplyToAll: "Apply To All %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Unlimited",
    Transport: "Transport",
    TileModifier: "Tile Modifier",
    ShowAllModifiers: "Show All Modifiers",
    HideAllModifiers: "Hide All Modifiers",
    NumberOfBuildings: "Number of buildings you have",
    ShowContent: "Show Content",
    HideContent: "Hide Content",
    BuyExpansionPack: "Buy For %{price}",
    Cities: "Cities",
    InputStrategy: "Input Strategy",
    InputStrategyClose: "Closer",
    InputStrategyCloseDesc: "Prefer the closest warehouse which has enough resources",
    InputStrategyFar: "Farther",
    InputStrategyFarDesc: "Prefer the farthest warehouse which has enough resources",
    InputStrategyAmount: "Amount",
    InputStrategyAmountDesc: "Prefer the warehouse with the largest amount of the resources, regardless of distance",
    FuelCostSave: "Fuel Cost Save",
    FuelCostSaveDesc:
        "Warehouses save a certain percentage of fuel for transporting resources inward compared to other buildings, the higher the level, the more the save",
    SoftwareCompany: "Software Company",
    Software: "Software",
    ScreenFactory: "Screen Factory",
    Screen: "Screen",
    JoinDiscord: "Join our Discord server for latest updates, tips and discussions",
    ClaimOfflineEarning: "Claim Offline Earning",
    OfflineTime: "Offline Time",
    Minutes: "%{time}min",
    MaxUpgrade: "Max Upgrade",
    MaxUpgradeDesc: "You have reached maximum upgrade",
    ClaimAmount: "Cash +%{amount}",
    EarningPerMinute: "Earning Rate",
    EffectiveTime: "Effective Time",
    EffectiveTimeDesc: "Your effective offline earning time is capped at %{time}min.",
    BuildSearchPlaceholder: "Type building or resource to search",
    MineOverlayWarning: "%{building} is not affected by tile modifier",
    WholesaleCenter: "Wholesale Center",
    OrderFrom: "Order from %{name}",
    ExpireIn: "Expire In",
    TurnOnAllProductions: "Production On",
    TurnOnAllProductionsDesc: "Turn on productions of all buildings, cannot be used when Cost Saver policy is active",
    OperationSuccessful: "This operation has been successfully completed",
    TurnOn: "Turn On",
    Reward: "Reward",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cycle",
    PolicyPoint: "Policy Point",
    PolicyPointPerMinute: "Generate Rate",
    PolicyPointPerMinuteDesc: "You acquire policy points every minute in the game",
    YourWilLGaimPolicyPoints: "You will gain %{amount} policy points in %{time}s",
    PolicyPointDesc: "💡 The more active policies, the more cost for each policy",
    NextOrderIn: "Next Order In",
    FillOrder: "Fill Order",
    RejectOrder: "Pass",
    WholesaleCenterLocked:
        "You need at least %{required} different resources to unlock Wholesale Center. You only have %{current} resources",
    OrderFilled: "The order from %{from} has been successfully filled!",
    PolicyCenter: "Policy Center",
    NewOrder: "A new order from %{from} has arrived, please check in Wholesale Center",
    Policies: "Policies",
    PolicyNotEnoughTime: "You don't have enough policy points for this policy",
    TimeLeft: "%{time} Left",
    WholesaleCenterOrderFaster: "World's Fair",
    WholesaleCenterOrderFasterDesc: "Wholesale Center receives orders 2x faster and the order size is 2x bigger",
    PolicyOilWellPowerx2: "Supercharge Oil Well",
    PolicyOilWellPowerx2Desc: "Oil wells produce 2x oil and use 2x power",
    HalfTransportSpeed: "Slow Down To Save Up",
    HalfTransportSpeedDesc: "Transportation speed is slowed down by 25% and fuel cost is reduced by 25%",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "Oil Refineries produce 50% more petrol and 50% less plastic",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Buildings will prefer to transport from previous source, instead of searching for the best source every cycle (FREE POLICY)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "Oil Refineries produce 50% less petrol and 50% more plastic",
    FreeOilTransportDesc: "Oil transport doesn't cost fuel but oil wells use 2x power",
    SuperSteelMill: "Hearts of Iron",
    SuperSteelMillDesc: "Steel mills use 50% less coal and 25% more iron and 25% more power",
    AlSemiconductor: "Al Circuit",
    AlSemiconductorDesc: "Circuit foundries use aluminum instead of copper",
    CostSaver: "Cost Saver",
    CostSaverDesc: "If a building's input cost more than its output, shut down the production",
    CostSaverBuildingDesc:
        "Cost Saver policy is active, production will turn on/off automatically based on its profitability",
    CostSaverBuildingWarning: "Cost Saver policy is active, you cannot manually change production",
    GlassUseCoal: "Black Glass",
    GlassUseCoalDesc: "Glass factories use 50% more coal and 50% less silicon",
    AdjacentBonusOnlyOutput: "Adjacent Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Adjacent bonus does not require more input but uses more power and is only 50% effective",
    IronMine2xOutput: "Heavy Iron",
    IronMine2xOutputDesc: "Iron mines produce 2x iron but iron transport costs 2x fuel",
    SolarPanelAlwaysWork: "The Sun Never Sets",
    SolarPanelAlwaysWorkDesc: "Solar panel works 100% of the time but produces 60% less power",
    SteelScience: "Knowledge Through Steel",
    SteelScienceDesc: "Steel mills use 2x input and produce extra science",
    WholesaleCenterProducingOnly: "Wholesale Partners",
    WholesaleCenterProducingOnlyDesc:
        "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "If a resource's output capacity falls short, buy the shortage amount from Trade Center automatically (If the resource has auto sell on, it will be ignored)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree policy is on, Trade Center will automatically buy resources in shortage",
    ExtraPolicyPoints: "Political Lobbyist",
    ExtraPolicyPointsDesc: "Increase policy point production capacity by 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromium alloy plants do not use Lithium but use 2x Iron instead",
    DoubleTileModifier: "Nature's Power",
    DoubleTileModifierDesc: "All tiles' modifier's effect x2 - both positive and negative",
    TileModifierOutputOnly: "Tile Modifier Plus",
    TileModifierOutputOnlyDesc:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective",
    GasPlantPetrol: "Gas Liquidizer",
    GasPlantPetrolDesc: "Gas power plants use extra gas to produce petrol",
    BuildingRecycle: "Building Recycle",
    BuildingRecycleDesc: "Get full refund when you sell a building within 1 min after construction",
    CoalPlantFuel: "Coal Liquidizer",
    CoalPlantFuelDesc: "Coal power plants use extra coal to produce petrol",
    Welcome: "Welcome",
    SeeTutorialAgain: "Redo Tutorial",
    HelpTranslateTheGame: "Help Translate the Game",
    SkipTutorial: "Skip Tutorial",
    NextTutorial: "Next",
    Tutorial1:
        "Industry Idle is a <em>resource management</em> game where you build factories🏭, produce goods📦 and make money💸.<br><br>Let's go through some basic concepts to get you started - it won't take long, I pinky promise.",
    Tutorial2:
        "All buildings need power⚡, you have a <em>wind turbine</em> that generates power. You can see your current power supply on the left side of the top bar.<br><br>You might have noticed that wind turbines only work <em>80%</em> of the time. You can consider building other types of power plants that generate stable power.",
    Tutorial3:
        "You have a lot of <em>resource deposits</em> on the map. To extract resources, you have to build mines⛏️ <em>on top of</em> the corresponding deposit.<br><br>For example, you have an <em>oil well🛢️</em> that extracts <em>oil</em> from an oil deposit.<br></br>Resource deposits are unlimited - no need to worry about them running out. Apart from mines, other buildings can be built on any empty tile.",
    Tutorial5:
        "To make money, you need to export your resources via the trade center. To do this, simply turn on <em>auto sell</em> for that resource.<br></br>You can also buy resources from the trade center as well. Remember <em>if you buy a resource, you will drive up the price</em> and if you sell a resource, you will drive down the price.<br><br>The market is <em>volatile</em> and the price📈 changes regularly.",
    Tutorial6:
        "To build new buildings, you need to unlock it first in the <em>research lab🧪</em>. The research lab also converts science to research points.<br><br>Your wind turbine (and other power plants) produces a small amount of science when running. And you can build school🏫 and other dedicated buildings to boost science later.<br><br>Now you have learned all the basics, start to build up your economy! Here are some <em>cash💸</em> and <em>petrol⛽</em> to give you a jump start.",
    WelcomePlay: "Play",
    WelcomePlayMuted: "Play (🔇Music)",
    Changelog: "Changelog",
    ChangelogGotIt: "Got It",
    Chat: "Chat",
    Send: "Send",
    Import: "Import",
    Export: "Export",
    LastBackupAt: "Last Backup",
    RestoreFromBackup: "Restore from Backup",
    RestoreFromBackupFail: "Failed to restore backup from Steam Cloud: are you sure there's a backup?",
    RestoreFromBackupTitle: "Are you sure?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChatMessages: "Chat Messages",
    ChangeName: "Change",
    SaveName: "Save",
    NameValidationRule: "Your name should only contain letters and numbers and be between 5-15 chars",
    NameValidationRuleProfanity: "Your name should not contain profanity",
    ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
    NameSaved: "Your name has been changed successfully",
    NoMessages: "No new messages",
    Leaderboard: "Leaderboard",
    Name: "Name",
    Rank: "Rank",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2: "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building is determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Energy Saving",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptOutDesc:
        "This will no longer send leaderboard score. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Reward video did not complete",
    RewardAdsNotAvailable: "Reward video is not available (currently only iOS/Android is supported)",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Highlight "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Out in %{time}",
    FuelRunOutWarning: "💡 Your fuel consumption exceeds production. When fuel runs out, your transportation will halt",
    InAmount: "In: %{number}",
    OutAmount: "Out: %{number}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Expansion Packs",
    ExpansionPack1: "Expansion Pack 1",
    ExpansionPack1Owned: "Expansion Pack 1",
    RequireExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Hide Discord Banner",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Hide Chat Message",
    SortedByDeficit: "Sorted By Deficit",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Swiss Money 💵",
    RestartDesc: "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
    PrestigeGoBack: "Go Back",
    PermanentUpgradeDesc: "This upgrade will carry over if you start in a new city",
    ProductionMultiplier: "Production Multiplier",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    OfflineEarningMultiplier: "Offline Earning Multiplier",
    OfflineEarningMultiplierDesc: "A multiplier that applies to offline earnings",
    PrestigeAlertTitle: "Are you sure?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Cash In",
    Cancel: "Cancel",
    SaveFileCorrupted: "Save File Corrupted",
    CheatDetected: "Your old save did not pass server validation and cannot be read. You will start with a new save",
    LoadGameError: "Failed to Load Game",
    LoadGameErrorMessage: "Error message: %{message}",
    LoadGameErrorDesc: "Please check your Internet connection. If the problem persists, please contact support",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    SaveFileMigrated: "A New Era: Beta Is Here",
    SaveFileMigratedDesc:
        "Thank you for play testing in alpha. Your old map is not compatible but we have migrated your data and give you some bonus",
    ClaimSwissMoney: "Claim %{amount} Swiss Money 💵",
    SaveFileMigratedFinePrint:
        "Your market cap is converted to Swiss Money and your unspent Swiss money is carried forward. You will get 50% bonus Swiss money for play testing in alpha. Max Swiss money that can be carried forward is capped at 200",
    CashIn: "Cash In",
    CurrentCity: "Current City",
    CashInDesc:
        "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
    MoveToNewMap: "Start In A New City",
    CityName: "City",
    CitySize: "Map Size",
    GridType: "Grid Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "City Bonus",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>No tile modifiers</li>",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Missile factories use enriched uranium instead of titanium and uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories use uranium instead of enriched uranium</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>University have 2x productivity</li>",
    HideNotProducing: "Hide resources that are not being produced",
    SortByStorage: "Storage",
    SortByProduction: "Production",
    SortByName: "Name",
    PlayerTrade: "Player Trade",
    AddTradeFail: "Failed to add your trade",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Your trade has been added successfully",
    LoadTradeFail: "Failed to load player trades, please try again later",
    ClaimTradeFail: "Failed to claim this trade, please try again later",
    CancelTradeSuccess: "Your trade has been cancelled successfully",
    CancelTradeFail: "Failed to cancel this trade, please try again later",
    AcceptTradeFail: "Failed to accept this trade, please try again later",
    PlayerTradeBanner: "Trade Resources with Other Players",
    PlayerTradeResource: "Resource",
    PlayerTradeAmount: "Amount",
    PlayerTradePrice: "Price $",
    PlayerTradeValue: "Value $",
    PlayerTradeWaiting: "Waiting...",
    UseTradeCenterPrice: "Use Trade Center Price",
    AddTrade: "Add Trade",
    ActiveTrades: "Active Trades",
    AcceptTrade: "Accept",
    CancelTrade: "Cancel",
    RefundTrade: "Refund",
    RefundTradeSuccess: "This trade has been refunded: %{resource} has been refunded to your trade center",
    RefundTradeFail: "Failed to refund this trade, please try again later",
    ClaimTrade: "Claim",
    RefreshTrade: "Refresh",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    FailedToCheckActiveTrade: "Failed to check active player trades, please try again later",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeValidRange: "Range: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Can Afford",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Warehouses can transport and store any resources",
    PowerBankChargeSpeed: "Charge Speed",
    PowerBankPowerLeft: "Power Left",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ExcludeBuildingsShutdown: "Exclude buildings that are shut down",
    ColorTheme: "Color Theme",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Industrial Revolution",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "This will hide resource movement (those tiny dots) by default and only show the movement when you select a building",
    PowerBankLeft: "Power Bank",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Cancel This Trade?",
    CancelTradeConfirmDialogYes: "Yes",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Add Route",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Find on Map",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consumption",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Player Flag",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    WarehouseOutwardFuelSave: "Free Delivery",
    WarehouseOutwardFuelSaveDesc: "Warehouses provide the same fuel save on outward transportation as well",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Resources tend to spawn in clusters</li><li>Warehouse provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Terms of Service",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Manga Publisher",
    Manga: "Manga",
    AnimeStudio: "Anime Studio",
    Anime: "Anime",
    PlayerTradeAction: "Action",
    PlayerTradeBuy: "Buy",
    PlayerTradeSell: "Sell",
    PlayerTradeBid: "Bid",
    PlayerTradeAsk: "Ask",
    CancelTradeConfirmDialogDescV2:
        "Cancelling this trade will refund %{percent} of the resource/cash. Resources will be refunded to Trade Center warehouse",
    ClaimTradeSuccessV2: "Your trade has been claimed successfully: %{cashOrResource}",
    AcceptTradeSuccessV2: "This trade has been accepted by you: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Better Than Market Price",
    ResourceExplorer: "Resource Explorer",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explore",
    ProductionSettings: "Production Settings",
    PlayerTradeQuotaDesc: "💡 Player trade quota is %{percent} of your market cap, it resets when the market updates",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Game Guides",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ShowProfitBreakdown: "Show Profit Breakdown",
    HideProfitBreakdown: "Hide Profit Breakdown",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Fuel Cost",
    BuildingProfit: "Profit",
    RestoreBackup: "Restore",
    SteamLogin: "Sign In Through Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Sign In",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "International Export Trade",
    FreeTransportToTradeCenterDesc:
        "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "In Storage: %{amount}",
    PlayerTradeFillValue: "Value",
    FiberFactory: "Fiber Factory",
    Fiber: "Fiber",
    Achievements: "Achievements",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Reward: Swiss Money +%{swiss}",
    AchievementsRewardToast: "You have claimed the reward:  Swiss Money +%{swiss}",
    AchievementsClaim: "Claim",
    AchievementsToast: "You have achieved %{name}, claim your reward in Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupDesc:
        "The game saves automatically to your local save. Your local save is synced to Steam Cloud every 10 minutes. You can force Steam cloud backup at any time.",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Force Steam Cloud Backup",
    UILoading: "Loading...",
    UserAuthenticated: "You are authenticated",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardBySwissPerBuilding: "Current Swiss Money Per Building",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Save and Exit Game",
    SaveAndExitDesc:
        "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Force Scroll",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ResourceExplorer2Desc: "Resource explorers produce 2x output but use 2x power",
    ConstructionCancel: "Cancel",
    ConstructionPause: "Pause",
    ConstructionResume: "Resume",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
    HighlightUnderConstruction: "...that haven't been constructed",
    HighlightUnderLevel10: "...that are under level 10",
    HighlightUnderLevel20: "...that are under level 20",
    HighlightUnderLevel30: "...that are under level 30",
    Logout: "You Are Logged Out",
    ConstructionStatusQueueingV2: "Queueing",
    ConstructionStatusPausedV2: "Paused",
    ConstructionStatusBuildingV2: "Building",
    ConstructionStatusUnpaidV2: "Unpaid",
    ConstructionStatus: "Construction Status",
    ConstructionStart: "Start",
    CostFree: "Free",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Only you",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "increased by %{percent}",
    MarketNewsDecrease: "decreased by %{percent}",
    MarketNewsBuilding: "This building is affected by %{num} news",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    OsloBonusV2:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
    EBookInc: "eBook Inc",
    ResourceBooster: "Resource Booster",
    BuildWarningTitle: "Building Might Not Work",
    BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
    BuildWarningBuildAnyway: "Build Anyway",
    ResourceBoosterNotWorking: "⛔ Resource boosters only work next to deposit mines",
    ResourceBoosterPercentage: "💡 This building gets %{percent} output boost from adjacent resource boosters",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
    BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "Have 50 production lines that has production deficit",
    UseScientificNotation: "Use Scientific Notation",
    UseScientificNotationDesc: "Use scientific notation (e notation) for numbers larger than 999.9T",
    LogoutDescV2:
        "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
    LogBackIn: "Log Back In",
    PlayerTradeNowAllowedV2: "Player trades are not available within %{hour} hours of restoring/importing a save",
    ServerDisconnected:
        "You are disconnected from the server, please check your internet connection and restart the game",
    BuildingUpgradeCostDividerDescV2: "Divide building upgrade cost by this divider",
    ResourceBoosterBannerDesc:
        "💡 You currently have %{number} resource boosters - the power and science input of each is scaled to the number of resource boosters you currently have",
    ResourceBoosterDesc: "Boost the output of adjacent mines",
};
