export const VN = {
    Translator: "Người dịch",
    TranslatorName: "Dương Quỳnh",
    Language: "Ngôn ngữ",
    ThisLanguage: "Tiếng Việt",
    OK: "Đồng ý",
    SteelMill: "Nhà máy thép",
    StainlessSteelPlant: "Nhà máy thép không gỉ",
    CircuitFoundry: "Xưởng vi mạch",
    IntegratedCircuit: "Chíp vi mạch",
    OilWell: "Giếng dầu thô",
    Wood: "Gỗ",
    LoggingCamp: "Xưởng đốn gỗ",
    LumberMill: "Xưởng cưa",
    Lumber: "Gỗ tấm",
    Paper: "Giấy",
    PaperMill: "Xưởng giấy",
    Book: "Sách",
    BookPublisher: "Nhà xuất bản",
    OilRefinery: "Xưởng lọc dầu",
    Sell: "Bán",
    Upgrade: "Nâng cấp",
    Build: "Xây",
    Inspect: "Tìm hiểu",
    Buildings: "Công trình",
    Iron: "Sắt",
    Actions: "Hành động",
    FuelType: "Chọn nhiên liệu",
    FuelCost: "Mức hao nhiên liệu",
    FuelConsumption: "%{fuel} sử dụng",
    FuelEconomy: "Tiết kiệm nhiên liệu",
    FuelProduction: "Sản xuất %{fuel}",
    FuelInStorage: "%{fuel} trong bể chứa",
    Plastic: "Nhựa",
    FuelSurplus: "%{fuel} thặng dư",
    Petrol: "Xăng",
    Buy: "Mua",
    NoLiquidity: "Không có giao dịch",
    NoLiquidityTurnOffAutoSell: "Không đủ lượng giao dịch cho %{res}, ngừng Tự động Bán hàng",
    Multiplier: "Bội số",
    MultiplierDesc: "Mỗi 10 cấp, bạn được thêm 1 bội số",
    SellBuilding: "Bán công trình",
    PowerGrid: "Lưới điện",
    TradeAmount: "Khối lượng giao dịch",
    SortBy: "Sắp xếp theo",
    SortByPrice: "Giá cả",
    SortByAmount: "Số lượng",
    NotEnoughResourcesForTrade: "Không đủ tài nguyên trong Trung Tâm Thương Mại để thực hiện giao dịch này",
    NotEnoughResources: "Không đủ tài nguyên để thực hiện hành động này",
    Transportation: "Vận tải",
    Cash: "Tiền mặt",
    Aluminum: "Nhôm",
    ResearchPoint: "Điểm nghiên cứu",
    Unlock: "Mở khóa",
    BuildingUnlocked: "Công trình %{building} đã được mở khóa",
    Science: "Khoa học",
    ScienceFromPowerDesc: "Nhà máy phát điện sinh ra một lượng nhỏ Khoa học trong quá trình sản xuất điện",
    Culture: "Văn hóa",
    School: "Trường học",
    University: "Đại học Tổng hợp",
    Polytechnic: "Đại học Bách khoa",
    Colosseum: "Đấu trường",
    WindTurbine: "Điện gió",
    Engine: "Động cợ",
    EngineFactory: "Xưởng sản xuất động cơ",
    CameraFactory: "Xưởng máy ảnh",
    Camera: "Máy ảnh",
    Gun: "Súng",
    GunFactory: "Xưởng súng",
    Aircraft: "Máy bay",
    AircraftFactory: "Xưởng máy bay",
    Zeppelin: "Khinh khí cầu",
    ZeppelinFactory: "Xưởng khinh khí cầu",
    Tank: "Xe tăng",
    TankFactory: "Xưởng xe tăng",
    CoalPowerPlant: "Nhà máy điện than",
    PetrolPowerPlant: "Nhà máy điện dầu",
    Copper: "Đồng",
    Gas: "Khí hóa lỏng",
    GasPump: "Mỏ khí hóa lỏng",
    GasPowerPlant: "Nhà máy điện khí",
    Missile: "Tên lửa",
    MissileFactory: "Xưởng tên lửa",
    Rocket: "Rocket",
    RocketFactory: "Xưởng rocket",
    BuildingPermit: "Giấy phép xây dựng",
    BuildingPermitDesc:
        "Bạn có tất cả %{amount} giấy phép xây dựng, bạn đã xây %{amountBuilt} công trình và còn lại %{amountLeft} giấy phép",
    BuildingLocked: "Công trình này chưa xây được, bạn cần mở khóa trong Viện Nghiên Cứu trước",
    BuildQueue: "Chuỗi xây dựng",
    BuildQueueDesc: "Số công trình trong chuỗi",
    MaxBuilders: "Số đội xây tối đa",
    MaxBuildersDesc: "Số công trình bạn có thể xây cùng lúc",
    Silicon: "Silic",
    AluminumMine: "Mỏ nhôm",
    CopperMine: "Mỏ đồng",
    SiliconMine: "Mỏ silic",
    IronMine: "Mỏ sắt",
    CoalMine: "Mỏ than",
    Headquarter: "Trụ Sở",
    ResearchLab: "Viện Nghiên Cứu",
    TradeCenter: "Trung Tâm Thương Mại",
    Resources: "Tài nguyên",
    NotEnoughPower: "💡 Không đủ điện, đề nghị nâng sản lượng điện",
    NotEnoughFuel: "Không đủ nhiên liệu %{fuel} cho hoạt động này",
    NotEnoughCash: "Không đủ tiền mặt cho hoạt động này",
    NotEnoughSwissMoney: "Không đủ tiền Thụy Sĩ cho hoạt động này",
    BuildingNotEnoughFuel: "💡 Không đủ nhiên liệu %{fuel}",
    AutoSell: "Tự động Bán hàng",
    SellAll: "Bán hết",
    Change: "Thay đổi",
    StatisticsBureau: "Cục Thống Kê",
    LogisticsDepartment: "Cục Vận Tải",
    From: "Từ",
    Top20FuelCost: "20 tuyến tốn nhiên liệu nhất",
    To: "Đến",
    TransportTime: "Thời gian vận chuyển",
    TopN: "Top %{n}",
    Warehouse: "Kho hàng",
    TradeWarehouse: "Kho giao dịch",
    Coal: "Than",
    Video: "Video",
    ClothingFactory: "Xưởng quần áo",
    Clothes: "Quần áo",
    Fashion: "Thời trang",
    FashionFactory: "Xưởng thời trang",
    VideoFarm: "Xưởng video",
    SantaFactory: "Xưởng ông già Noel",
    Santa: "Ông già Noel",
    Car: "Ô tô",
    CarFactory: "Xưởng ô tô",
    Ship: "Thuyền",
    SolarPanel: "Tấm năng lượng mặt trời",
    SolarPanelDesc: "💡 Tấm năng lượng mặt trời chỉ hoạt động 5 giây cho mỗi 10 giây, chu kỳ đồng bộ",
    WindTurbineDesc: "💡 Điện gió chỉ hoạt động 8 giây cho mỗi 10 giây, chu kỳ không đồng bộ",
    Movie: "Phim",
    MovieStudio: "Xưởng phim",
    Sitcom: "Phim truyền hình",
    TVStudio: "Đài truyền hình",
    PC: "Máy vi tính",
    GameStudio: "Xưởng game",
    Game: "Game",
    ComputerFactory: "Xưởng máy vi tính",
    Shipyard: "Xưởng đóng tàu",
    PowerUsage: "Tiêu thụ điện năng",
    PowerSupply: "Sản xuất điện năng",
    PowerSurplus: "Điện năng thặng dư",
    Level: "Cấp",
    Power: "Điện năng",
    CentralBank: "Ngân Hàng Trung Ương",
    ResourceInput: "Vào",
    ResourceOutput: "Ra",
    ResourceStorage: "Kho chứa",
    ResourceChange: "Thay đổi",
    ResourceInOutDesc: "💡 Bấm vào con số Ra/Vào ở trên để đánh dấu các công trình sản xuất hoặc tiêu thụ",
    ResourceChart: "Biểu đồ tài nguyên",
    MarketUpdateIn: "Sàn giao dịch sẽ cập nhật trong %{time}",
    Income: "Thu nhập",
    Semiconductor: "Bóng Bán dẫn",
    SemiconductorFactory: "Xưởng bán dẫn",
    Steel: "Thép",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Đào Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Đào Dogecoin",
    Guitar: "Đàn Ghi-ta",
    GuitarFactory: "Xưởng làm ghi-ta",
    Drum: "Trống",
    DrumFactory: "Xưởng làm trống",
    RecordingStudio: "Phòng thu thanh",
    OperaHouse: "Nhà hát lớn",
    CoalGasificationPlant: "Xưởng khí hóa lỏng từ Than",
    GasProcessingPlant: "Xưởng xử lý khí hóa lỏng",
    Music: "Nhạc",
    Glass: "Kính",
    PhoneFactory: "Xưởng điện thoại",
    Phone: "Điện thoại",
    GlassFactory: "Nhà máy kính",
    Oil: "Dầu thô",
    Chromium: "Crôm",
    ChromiumMine: "Mỏ Crôm",
    Uranium: "Uranium",
    EnrichedUranium: "Uranium giàu",
    NuclearPowerPlant: "Nhà máy điện nguyên tử",
    UraniumEnrichmentPlant: "Nhà máy làm giàu uranium",
    UraniumMine: "Mỏ uranium",
    Titanium: "Titan",
    TitaniumMine: "Mỏ titan",
    TitaniumAlloyPlant: "Xưởng hợp kim titan",
    ChromiumAlloyPlant: "Xưởng hợp kim Crôm",
    Input: "Nguyên liệu",
    PanelPosition: "Vị trí bảng thông tin",
    PanelPositionDesc: "Hiển thị bảng thông tin bên trái, phải hoặc tự động (tùy vào ô được chọn trên bản đồ)",
    InputCapacity: "Dung lượng nguyên liệu",
    InputCapacityPerCycle: "Dung lượng nguyên liệu mỗi chu kỳ",
    Output: "Thành phẩm",
    OutputCapacity: "Dung lượng thành phẩm",
    OutputCapacityPerCycle: "Dung lượng thành phẩm mỗi chu kỳ",
    ResourceDeposit: "Trữ lượng",
    RecommendedBuilding: "💡 Ô này có trữ lượng %{resource}",
    AdjacentBonus: "Hiệu ứng liền kề",
    AdjacentBonusDesc: "Bạn được thêm %{bonus}% sản lượng cho mỗi công trình liền kề cùng loại",
    ConsiderIncreaseProduction: "💡 Đề nghị tăng sản lượng %{resource}",
    AlwaysTransportInput: "Chế độ tích trữ",
    AlwaysTransportInputTradeCenter: "Luôn xuất hàng",
    AlwaysTransportInputTradeCenterDesc:
        "Luôn vận chuyển thành phẩm đến Trung tâm Thương mại ngay cả khi không bật chế độ Tự động Bán hàng cho tài nguyên này",
    AlwaysTransportInputDesc: "Luôn vận chuyển nguyên liệu, ngay cả khi vượt qua số lượng tối thiểu cần cho sản xuất",
    ProductionCycleLength: "Chu kỳ sản xuất",
    ProductionCycleLengthDesc:
        "Thời gian của một chu kỳ sản xuất tính bằng giây. Kéo dài chu kỳ sẽ tăng nguyên liệu và thành phẩm tương ứng, làm hạ thấp nhu cầu vận chuyển nguyên liệu",
    MaxInputDistance: "Khoảng cách tối đa vận chuyển nguyên liệu",
    MaxInputDistanceDesc: "Khoảng cách tối đa mà công trình sẽ vận chuyển nguyên liệu, tính bằng số ô",
    AutoSellCapacity: "Số lượng Tự động Bán hàng",
    AutoSellCapacityDesc: "Số lượng tối đã tài nguyên có thể bán mỗi giây cho mỗi tài nguyên",
    CurrentAutoSellCapacityMultiplier: "Bội số hiện tại: x%{n}",
    AutoSellConcurrency: "Tự động Bán hàng đồng thời",
    AutoSellConcurrencyDesc: "Số lượng tối đa loại tài nguyên có thể đồng thời Tự động Bán hàng",
    MaxAutoSellConcurrencyReached:
        "Bạn đã sử dụng hết số loại tài nguyên có thể Tự động Bán hàng, đề nghị tắt một loại khác để có thể bật cho tài nguyên này",
    CannotSellBuilding: "Không thể bán công trình vào lúc này",
    WallStreet: "Phố Wall",
    MarketCap: "Giá trị vốn hóa",
    MarketCapDesc: "Tổng giá trị vốn hóa thị trường của tập đoàn của bạn",
    BuildingValuation: "Giá trị nhà xưởng",
    BuildingValuationDesc: "Tổng giá trị các công trình, gồm cả giấy phép xây dựng và các mức nâng cấp",
    ResourcesValuation: "Giá trị tài nguyên",
    ResourcesValuationDesc: "Tổng giá trị tài nguyên trong kho bãi",
    Battery: "Pin",
    BatteryFactory: "Xưởng pin",
    RatingBuy: "Mua",
    RatingSell: "Bán",
    SwissShop: "Cửa hàng Thụy Sĩ",
    RatingHold: "Giữ",
    RatingOutperform: "Vượt bậc",
    RatingUnderperform: "Yếu",
    StockRating: "Đánh giá cổ phiếu",
    JetEngine: "Động cơ phản lực",
    Helicopter: "Trực thăng",
    Lithium: "Li-ti",
    LithiumMine: "Mỏ li-ti",
    LiionBatteryFactory: "Xưởng pin li-ti i-ông",
    HelicopterFactory: "Xưởng trực thăng",
    Satellite: "Vệ tinh",
    ToyFactory: "Xưởng đồ chơi",
    Toy: "Đồ chơi",
    SpaceStation: "Trạm vũ trụ",
    SpaceStationFactory: "Xưởng lắp trạm vũ trụ",
    OperatingSystem: "Hệ điều hành",
    OperatingSystemCompany: "Công ty sản xuất hệ điều hành",
    LinuxDistribution: "Bản phân phối Linux",
    Internet: "Internet",
    WebBrowser: "Trình duyệt",
    Console: "Máy trò chơi",
    ConsoleFactory: "Xưởng sản xuất máy trò chơi",
    Train: "Tàu hỏa",
    TrainFactory: "Xưởng tàu hỏa",
    ShoeFactory: "Xưởng giày",
    Shoes: "Giày",
    ArtilleryFactory: "Xưởng đại bác",
    Artillery: "Đại bác",
    SubmarineFactory: "Xưởng tàu ngầm",
    Submarine: "Tàu ngầm",
    Spaceship: "Tàu vũ trụ",
    RobotFactory: "Xưởng người máy",
    Robot: "Người máy",
    SpaceshipFactory: "Xưởng tàu vũ trụ",
    SatelliteFactory: "Xưởng vệ tinh",
    JetEngineFactory: "Xưởng động cơ phản lực",
    StockRatingDesc:
        "Chỉ số đánh giá cổ phiếu của các nhà phân tích phố Wall, chỉ số này sẽ ảnh hưởng đến giá trị vốn hóa và được cập nhật cùng chu kỳ với thị trường",
    InterestRate: "Lãi suất qua đêm",
    InterestRateDesc: "Lãi suất bạn nhận được dựa trên giá trị vốn hóa trong khi bạn nghỉ chơi",
    OfflineEarning: "Tiền lãi nghỉ chơi",
    OfflineEarningDesc: "Tiền lãi nghỉ chơi phụ thuộc vào giá trị vốn hóa và lãi suất",
    PerMin: "%{amount} mỗi phút",
    OfflineEarningTime: "Thời gian tính lãi nghỉ chơi",
    OfflineEarningTimeDesc: "Bạn sẽ nhận được tiền lãi nghỉ chơi cho đến thời gian này",
    BuyPermit: "Mua giấy phép",
    NotEnoughBuildingPermit: "Không đủ giấy phép xây dựng, đề nghị mua thêm để có thể tiếp tục xây",
    MovingAverage: "Thay đổi trung bình",
    MovingAverageDesc: "Thể hiện số liệu thay đổi trung bình cho tài nguyên, thay vì số liệu thời gian thực",
    AllowZoom: "Phóng to thu nhỏ",
    AllowZoomDesc:
        "Bật hỗ trợ phóng to thu nhỏ. Sử dụng con lăn của chuột để thay đổi. Mức độ phóng hiện tại là %{zoom}",
    AllowZoomMobileDesc:
        "Bật hỗ trợ phóng to thu nhỏ. Dùng động tác nhéo để thay đổi. Mức độ phóng hiện tại là %{zoom}",
    Settings: "Tùy chọn",
    Sound: "Hiệu ứng âm thanh",
    SoundDesc: "Bật hiệu ứng âm thanh cho nhấp chuột hay báo lỗi",
    AutoHighlight: "Tự động đánh dấu",
    AutoHighlightDesc: "Tự động đánh dấu các công trình cùng loại khi bạn chọn một công trình",
    MusicDesc: "Bật nhạc: It's Not Over 'Til The Bossa Nova bởi Shane Ivers (https://www.silvermansound.com)",
    Credits: "Công trạng",
    Icons: "Hình",
    MisplacedBuilding: "⛔ Công trình %{building} này xây không đúng trên vỉa tài nguyên tương ứng",
    Left: "Trái",
    Right: "Phải",
    Auto: "Tự động",
    HighlightBuildings: "Đánh dấu công trình",
    HighlightTurnedOff: "...đã bị ngưng hoạt động",
    HighlightStockpileModeOn: "...đang bật chế độ tích trữ",
    HighlightProductionCycleNotDefault: "...có chu kỳ sản xuất > 1",
    HighlightMaxInputDistanceNotDefault: "...có khoảng cách thu tài nguyên tối đa < ∞",
    HighlightNotMakingProfit: "...không có lãi",
    NBuildingsAreHighlighted: "%{n} công trình đã được đánh dấu",
    OnlyToWarehouse: "Chỉ dành cho kho bãi",
    OnlyToWarehouseDesc: "Chỉ kho bãi có thể vận chuyển thành phẩm từ công trình này",
    TurnOffProduction: "Ngừng hoạt động",
    TurnOffProductionDesc: "Ngưng sản xuất. Công trình cũng sẽ không vận chuyển tài nguyên và không sử dụng điện năng",
    ApplyToAll: "Áp dụng cho tất cả các công trình %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Không giới hạn",
    Transport: "Vận chuyển",
    TileModifier: "Hiệu ứng trên ô",
    ShowAllModifiers: "Hiển thị tất cả hiệu ứng",
    HideAllModifiers: "Che hết hiệu ứng",
    NumberOfBuildings: "Số công trình bạn có",
    ShowContent: "Hiển thị nội dung",
    HideContent: "Che nội dung",
    BuyExpansionPack: "Mua với giá %{price}",
    Cities: "Các thành phố",
    InputStrategy: "Chiến lược nhập",
    InputStrategyClose: "Gần hơn",
    InputStrategyCloseDesc: "Ưu tiên kho bãi gần nhất có đủ nguyên liệu",
    InputStrategyFar: "Xa hơn",
    InputStrategyFarDesc: "Ưu tiên kho bãi xa nhất có đủ nguyên liệu",
    InputStrategyAmount: "Số lượng",
    InputStrategyAmountDesc: "Ưu tiên kho bãi có nhiều nguyên liệu nhất, bất kể khoảng cách",
    FuelCostSave: "Tiết kiệm nhiên liệu",
    FuelCostSaveDesc:
        "Kho bãi tiết kiệm được tỉ lệ nhiên liệu nhất định khi nhập tài nguyên vào so với các công trình khác, cấp kho bãi càng cao thì càng tiết kiệm nhiều",
    SoftwareCompany: "Công ty phần mềm",
    Software: "Phần mềm",
    ScreenFactory: "Xưởng màn hình",
    Screen: "Màn hình",
    JoinDiscord:
        "Mời gia nhâp máy chủ Discord của chúng tôi để tham khảo cập nhật mới nhất, hướng dẫn cũng như trao đổi",
    ClaimOfflineEarning: "Thu tiền lãi nghỉ chơi",
    OfflineTime: "Thời gian nghỉ chơi",
    Minutes: "%{time} phút",
    MaxUpgrade: "Nâng cấp tối đa",
    MaxUpgradeDesc: "Bạn đã lên tới cấp tối đa",
    ClaimAmount: "Tiền mặt +%{amount}",
    EarningPerMinute: "Tỉ lệ lợi nhuận",
    EffectiveTime: "Thời gian tối đa",
    EffectiveTimeDesc: "Thời gian nhận lãi nghỉ chơi tối đa của bạn bằng %{time} phút.",
    BuildSearchPlaceholder: "Gõ tên công trình hoặc tài nguyên để tìm",
    MineOverlayWarning: "Công trình %{building} không bị ảnh hưởng bởi hiệu ứng trên ô",
    WholesaleCenter: "Trung tâm bán sỉ",
    OrderFrom: "Đơn đặt hàng từ %{name}",
    ExpireIn: "Hết hạn trong",
    TurnOnAllProductions: "Bật sản xuất",
    TurnOnAllProductionsDesc:
        "Bật sản xuất cho tất cả các công trình, không dùng được khi đang chạy Chính sách Tiết kiệm",
    OperationSuccessful: "Hành động này đã được thực thi",
    TurnOn: "Bật lên",
    Reward: "Phần thưởng",
    PerSecond: "%{time}/giây",
    PerCycle: "%{amount}/chu kỳ",
    PolicyPoint: "Điểm chính sách",
    PolicyPointPerMinute: "Tốc độ xử lý",
    PolicyPointPerMinuteDesc: "Bạn nhận được điểm chính sách cho mỗi phút chơi",
    YourWilLGaimPolicyPoints: "Bạn sẽ nhận được %{amount} điểm chính sách mỗi %{time} giây",
    PolicyPointDesc: "💡 Càng nhiều chính sách thì chính sách tiếp theo càng tốn nhiều điểm để duy trì",
    NextOrderIn: "Đơn đặt hàng tiếp theo trong",
    FillOrder: "Hoàn thành đơn hàng",
    RejectOrder: "Bỏ qua",
    WholesaleCenterLocked:
        "Bạn cần tối thiểu %{required} loại tài nguyên khác nhau để mở khóa Trung tâm Bán sỉ. Bạn mới có %{current} loại tài nguyên",
    OrderFilled: "Đơn hàng của %{from} đã hoàn thành!",
    PolicyCenter: "Trung tâm Shính sách",
    NewOrder: "Có đơn hàng mới từ %{from}, đề nghị kiểm tra Trung tâm Bán sỉ",
    Policies: "Chính sách",
    PolicyNotEnoughTime: "Bạn không có đủ điểm chính sách",
    TimeLeft: "Còn lại %{time}",
    WholesaleCenterOrderFaster: "Hội chợ Toàn cầu",
    WholesaleCenterOrderFasterDesc:
        "Trung tâm Bán sỉ nhận được đơn hàng nhanh gấp đôi và số lượng hàng hóa tăng gấp đôi",
    PolicyOilWellPowerx2: "Mỏ dầu siêu cấp",
    PolicyOilWellPowerx2Desc: "Mỏ dầu sản xuất 2x dầu và sử dụng x2 điện năng",
    HalfTransportSpeed: "Chạy chậm để tiết kiệm",
    HalfTransportSpeedDesc: "Tốc độ vận chuyển giảm 25% và nhiên liệu tiêu thụ giảm 25%",
    RefineryMoreOil: "Thêm xăng thêm vấn đề",
    RefineryMoreOilDesc: "Xưởng lọc dầu sản xuất thêm 50% xăng và bớt đi 50% nhựa",
    StickyInput: "Đầu vào cố định",
    StickyInputDesc:
        "Công trình sẽ ưu tiên vận chuyển từ nguồn cung cũ thay vì liên tục tìm nguồn cung tốt nhất mỗi chu kỳ (Chính sách MIỄN PHÍ)",
    RefineryMorePlastic: "Thêm nhựa thêm vấn đề",
    RefineryMorePlasticDesc: "Xưởng lọc dầu sản xuất bớt đi 50% xăng và thêm 50% nhựa",
    FreeOilTransportDesc: "Vận chuyển dầu thô không cần nhiên liệu nhưng mỏ dầu sử dụng x2 điện năng",
    SuperSteelMill: "Thiết Tâm",
    SuperSteelMillDesc: "Nhà máy thép sử dụng bớt đi 50% than nhưng tăng thêm 25% sắt và 25% điện năng",
    AlSemiconductor: "Vi mạch nhôm",
    AlSemiconductorDesc: "Xưởng vi mạch dùng Nhôm thay vì Đồng",
    CostSaver: "Tiết kiệm",
    CostSaverDesc: "Nếu nguyên liệu của một công trình đắt hơn thành phẩm, ngưng sản xuất công trình đó",
    CostSaverBuildingDesc: "Chính sách Tiết kiệm đang chạy, sản xuất sẽ tự động bật/tắt tùy theo lỗ/lãi",
    CostSaverBuildingWarning: "Chính sách Tiết kiệm đang chạy, bạn không thể can thiệp trực tiếp",
    GlassUseCoal: "Kính đen",
    GlassUseCoalDesc: "Nhà máy kính sử dụng thêm 50% than và bớt đi 50% silic",
    AdjacentBonusOnlyOutput: "Hiệu ứng liền kề cộng",
    AdjacentBonusOnlyOutputDesc:
        "Hiệu ứng liền kề không sử dụng thêm nguyên liệu nhưng sừ dụng thêm điện năng và chỉ đạt được 50% hiệu quả",
    IronMine2xOutput: "Trọng thiết",
    IronMine2xOutputDesc: "Mỏ sắt sản xuất x2 sắt nhưng vận chuyển sắt tốn x2 nhiên liệu",
    SolarPanelAlwaysWork: "Mặt trời không bao giờ lặn",
    SolarPanelAlwaysWorkDesc: "Tấm năng lượng mặt trời hoạt động 100% thời gian nhưng giảm 60% sản lượng",
    SteelScience: "Kiến thức từ Thép",
    SteelScienceDesc: "Nhà máy thép dùng x2 nguyên liệu và sản xuất thêm điểm khoa học",
    WholesaleCenterProducingOnly: "Đối tác Bán Sỉ",
    WholesaleCenterProducingOnlyDesc:
        "Đơn hàng của Trung tâm Bán sỉ chỉ bao gồm các tài nguyên mà bạn đang sản xuất (bạn vẫn cần sản xuất đủ số loại tài nguyên để mở khóa Trung tâm Bán sỉ)",
    ShoppingSpree: "Mua sắm điên cuồng",
    ShoppingSpreeDesc:
        "Nếu sản lượng tài nguyên không đủ nhu cầu, tự động mua số lượng cần thiết từ Trung tâm Thương Mại (nếu Tự động Bán hàng đang bật cho tài nguyên này thì hệ thống sẽ bỏ qua)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Mua sắm điên cuồng đang bật, Trung tâm Thương mại sẽ tự động mua tài nguyên bị thiếu hụt",
    ExtraPolicyPoints: "Vận động hành lang",
    ExtraPolicyPointsDesc: "Tăng sản lượng điểm chính sách thêm 50%",
    CrAlloyUseFe: "Crô-sắt",
    CrAlloyUseFeDesc: "Xưởng hợp kim crôm không sử dụng Li-ti nhưng thay bằng x2 Sắt",
    DoubleTileModifier: "Sức mạnh của Thiên nhiên",
    DoubleTileModifierDesc: "Hiệu ứng trên ô x2 - cả tích cực lẫn tiêu cực",
    TileModifierOutputOnly: "Hiệu ứng ô cộng",
    TileModifierOutputOnlyDesc: "Hiệu ứng trên ô chỉ tác động lên sản lượng thành phẩm, nhưng giảm 50% hiệu quả",
    GasPlantPetrol: "Khí hóa lỏng",
    GasPlantPetrolDesc: "Nhà máy điện khí sử dụng thêm khí hóa lỏng và sản xuất xăng",
    BuildingRecycle: "Tái cơ cấu công trình",
    BuildingRecycleDesc: "Được hoàn trả toàn bộ chi phí nếu bán công trình trong vòng 1 phút sau khi xây",
    CoalPlantFuel: "Than hóa lỏng",
    CoalPlantFuelDesc: "Nhà máy điện than sử dung thêm than và sản xuất xăng",
    Welcome: "Chào mừng bạn",
    SeeTutorialAgain: "Thực hiện lại hướng dẫn cách chơi",
    HelpTranslateTheGame: "Hãy giúp dịch thuật trò chơi🌐",
    SkipTutorial: "Bỏ qua hướng dẫn cách chơi",
    NextTutorial: "Tiếp theo",
    Tutorial1:
        "Industry Idle là một trò chơi <em>quản lý tài nguyên</em>, nơi bạn có thể xây nhà xưởng🏭, sản xuất hàng hóa📦 và kiếm tiền💸.<br><br>Hãy cùng tìm hiểu một vài khái niệm để giúp bạn khởi nghiệp. Sẽ không lâu đâu, ngoắc ngón tay hứa đó.",
    Tutorial2:
        "Tất cả các công trình đều cần điện năng⚡, bạn hiện có <em>Điện gió</em> sản sinh ra điện. Bạn có thể tìm thấy sản lượng cung cấp điện hiện tại ở góc trên bên trái.<br><br>Có thể bạn đã để ý thấy Điện gió chỉ sản xuất <em>80%</em> thời gian. Bạn có thể xem xét xây dựng các công trình phát điện khác để có thể phát điện ổn định.",
    Tutorial3:
        "Bạn có rất nhiều <em>vỉa tài nguyên</em> trên bản đồ. Để khai thác tài nguyên, bạn cần xây mỏ⛏️ <em>lên trên</em> các ô tài nguyên đó.<br><br>Ví dụ, bạn có thể xây <em>giếng dầu🛢️</em> để khai thác <em>dầu thô</em> từ một vỉa dầu.<br></br>Vỉa tài nguyên là vô hạn - không cần lo cạn kiệt dự trữ. Ngoài xây mỏ, các loại công trình khác có thể xây được trên bất kỳ ô trống nào.",
    Tutorial5:
        "Để kiếm tiền, bạn cần xuất khẩu tài nguyên thông qua Trung tâm Thương mại. Để làm việc này, chỉ cần bật <em>Tự động Bán hàng</em> cho tài nguyên mà bạn muốn bán.<br></br>Bạn cũng có thể mua tài nguyên từ Trung tâm Thương mại. Xin lưu ý, <em>nếu bạn mua một loại tài nguyên, bạn sẽ nâng giá thành</em> và nếu bạn bán tài nguyên, bạn sẽ hạ giá thành.<br><br>Thị trường liên tục <em>biến thiên</em> và giá cả📈 thường xuyên thay đổi.",
    Tutorial6:
        "Để xây các loại công trình mới, bạn cần mở khóa chúng trong <em>Viện nghiên cứu🧪</em>. Viện nghiên cứu cũng chuyển đổi điểm khoa học thành điểm nghiên cứu.<br><br>Điện gió của bạn (cũng như các dạng phát điện khác) liên tục sản sinh ra một lượng nhỏ điểm khoa học trong lúc vận hành. Về sau, bạn có thể xây trường học🏫 và các công trình chuyên môn khác để nâng sản lượng điểm khoa học.<br><br>Giờ bạn đã học được những điều cơ bản, hãy bắt đầu gây dựng nền kinh tế của bạn đi thôi! Đây là chút <em>tiền mặt💸</em> và <em>xăng⛽</em> để giúp bản khởi nghiệp.",
    WelcomePlay: "Chơi",
    WelcomePlayMuted: "Chơi (🔇Tắt nhạc)",
    Changelog: "Thay đổi gần đây",
    ChangelogGotIt: "Đã rõ",
    Chat: "Chat",
    Send: "Gửi",
    Import: "Nhập dữ liệu",
    Export: "Xuất dữ liệu",
    LastBackupAt: "Bảo lưu lần cuối lúc",
    RestoreFromBackup: "Sử dụng bản bảo lưu gần nhất",
    RestoreFromBackupFail: "Khôi phục dữ liệu từ Đám mây của Steam không thành công: bạn có chắc đã lưu rồi không?",
    RestoreFromBackupTitle: "Bạn có chắc không?",
    RestoreFromBackupDesc:
        "Bạn hiếm khi cần khôi phục dữ liệu từ đám mây, trừ khi bản lưu trên máy của bạn bị mất. Bản lưu trên đám mây sẽ cũ hơn một chút so với trên máy.",
    ChatMessages: "Tin nhắn",
    ChangeName: "Thay đổi",
    SaveName: "Lưu",
    NameValidationRule: "Tên của bạn chỉ được chứa chữ cái và số, từ 5 đến 15 ký tự",
    NameValidationRuleProfanity: "Tên của bạn không được chửi bậy",
    ChatMessageRateLimit: "Bạn chỉ có thể gửi tin 10 giây một lần",
    NameSaved: "Đổi tên thành công",
    NoMessages: "Không có tin nhắn mới",
    Leaderboard: "Bảng xếp hạng",
    Name: "Tên",
    Rank: "Hạng",
    Tips1: "Đánh giá cổ phiếu có 5 cấp: Mua, Vượt bậc, Giữ, Yếu and Bán",
    Tips2: "Công trình tự động ngừng vận chuyển nguyên liệu khi đã có đủ cho sản xuất, trừ khi bạn bật chế độ Tích trữ",
    Tips3: "Chi phí nhiên liệu cho vận chuyển tài nguyên được tính bằng khoảng các và số lượng cần vận chuyển",
    Tips4: "Công trình chỉ vận chuyển một loại tài nguyên nếu trên bản đồ có đủ nguồn cung",
    Tips5: "Công trình chỉ vận chuyển tài nguyên từ Trung tâm Thương mại nếu bạn đã tắt Tự động Bán hàng tài nguyên",
    Tips6: "Bạn có thể thấy chi phí nhiên liệu cho từng nguyên liệu dưới tên của chúng trong phần Nhập",
    Tips7: "Nếu bạn mua một tài nguyên, giá thành sẽ tăng lên. Nếu bạn bán một tài nguyên, giá thành sẽ hạ xuống",
    Tips8: "Bạn có thể xem biểu đồ số lượng của từng tài nguyên và thay đổi theo thời gian trong Cục thống kê",
    Tips9: "Điểm nghiên cứu để mở khóa một công trình được xác định bởi giá thành của các nguyên liệu đầu vào",
    Tips10: "Mỗi loại tài nguyên có định giá khác nhau - hãy sẵn sang cho tính biến thiên của thị trường",
    Tips11: "Một thói quen tốt trước khi mở rộng sản xuất là nên kiểm tra sản lượng điện năng và nhiên liệu",
    FPS30: "Tiết kiệm năng lượng",
    OfflineModeDesc:
        "Không kết nối được với máy chủ: bạn sẽ không được cấp Lãi nghỉ chơi. Xin hãy kiểm tra đường truyền của bạn",
    OptOut: "Không tham gia",
    OptIn: "Làm lại và tham gia",
    LeaderboardOptOut: "Không tham gia xếp hạng",
    LeaderboardOptOutDesc:
        "Nếu thực thi, sẽ không gửi điểm xếp hạng nữa. CHÚ Ý: nếu bạn muốn tham gia xếp hạng lại, bạn sẽ phải làm lại từ đầu",
    LeaderboardOptIn: "Làm lại và bật xếp hạng",
    LeaderboardOptInDesc: "Dữ liệu của bạn sẽ bị XÓA trước khi bạn có thể tái tham gia xếp hạng, bạn có chắc không?",
    RewardAdsFailed: "Chưa xem hết quảng cáo nên không có thưởng",
    RewardAdsNotAvailable: "Hiện tại không có quảng cáo (hiện chỉ được hỗ trợ trên iOS/Android)",
    OfflineEarningDoubleSuccess: "Bạn đã nhân đôi Lãi nghỉ chơi",
    FPS30Desc:
        "Bật Tiết kiệm Năng lượng sẽ chạy trò chơi ở 30 hình/giây thay vì 60 hình/giây. Điều này sẽ giúp pin của bạn dùng lâu hơn",
    HighlightAll: 'Đánh dấu "%{type}"',
    HighlightInput: "🔍 Đánh dấu nguồn cầu %{type}",
    HighlightOutput: "🔍 Đánh dấu nguồn cung %{type}",
    TotalInput: "Tổng sản lượng cầu",
    TotalOutput: "Tổng sản lượng cung",
    RunOutIn: "Hết sau %{time}",
    FuelRunOutWarning:
        "💡 Tiêu thụ nhiên liệu của bạn vượt quá sản lượng. Khi hết nhiên liệu dự trữ, vận tải của bạn sẽ bị đình đốn",
    InAmount: "Nhập: %{number}",
    OutAmount: "Xuất: %{number}",
    SwissBank: "Ngân hàng Thụy Sĩ",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Nếu bạn khởi đầu ở thành phố mới, bạn sẽ nhận được %{money} 💵",
    RestorePurchases: "Khôi phục giao dịch",
    RestorePurchasesSuccess: "Giao dịch của bạn đã được khôi phục",
    RestorePurchasesFailed: "Không khôi phục được giao dịch",
    ExpansionPacks: "Bản mở rộng",
    ExpansionPack1: "Bản mở rộng 1",
    ExpansionPack1Owned: "Bản mở rộng 1",
    RequireExpansionPack1: "Bản mở rộng 1",
    RequireExpansionPack1Desc: "Hành động này cần có Bản mở rộng 1",
    RequireAnyExpansionPack: "Dành riêng cho Bản mở rộng",
    RequireAnyExpansionPackDesc: "Tính năng này cần bạn sở hữu ít nhất một Bản mở rộng",
    HideRewardAd: "Tắt quảng cáo",
    HideRewardAdDesc:
        "Tất cả quảng cáo trong trò chơi đều không bắt buộc. Tính năng này sẽ tắt tất cả quảng cáo trong trò chơi.",
    HideDiscordBanner: "Giấu thẻ Discord",
    HideDiscordBannerDesc: "Che thẻ Discord trong trụ sở",
    HideChat: "Giấu khung chat",
    SortedByDeficit: "Sắp theo thiếu hụt",
    PurchaseFailed: "Giao dịch không thành công",
    PurchaseSteamContinue: "Xin hãy thực hiện giao dịch trên Steam",
    PurchaseSuccess: "Giao dịch thành công, cám ơn sự hỗ trợ của bạn",
    PrestigeCurrency: "Tiền Thụy Sĩ 💵",
    RestartDesc: "💡 Chỉ muốn làm lại từ đầu? Bạn có thể dùng Khởi đầu ở một Thành phố mới và chọn thành phố hiện tại",
    PrestigeGoBack: "Quay lại",
    PermanentUpgradeDesc: "Nâng cấp này sẽ đi theo bạn khi bạn Khởi đầu ở một Thành phố mới",
    ProductionMultiplier: "Bội số sản xuất",
    ProductionMultiplierDesc:
        "Nâng cấp sản lượng cho các công trình của bạn (bao gồm các công trình mỏ, nhà xưởng, nhà máy điện, khoa học và văn hóa)",
    FuelCostDiscount: "Giảm chi phí nhiên liệu",
    FuelCostDiscountDesc: "Giảm giá chi phí nhiên liệu khi vận chuyển tài nguyên",
    AutoSellCapacityMultiplier: "Bội số cho Tự động Bán hàng",
    AutoSellCapacityMultiplierDesc:
        "Bội số được áp dụng cho số lượng Tự động Bán hàng bất kể mức nâng cấp hiện tại trong Trung tâm Thương mại",
    BuildingPermitCostDivider: "Số chia giá thành Giấy phép xây dựng",
    BuildingPermitCostDividerDesc: "Lấy giá Giấy phép xây dựng chia cho số này ",
    ExtraAdjacentBonus: "Hiệu ứng Liền kề nâng cao",
    ExtraAdjacentBonusDesc: "Thêm điểm hiệu ứng liền kề cho các công trình cùng loại liền kề nhau",
    OfflineEarningMultiplier: "Bội số Lãi nghỉ chơi",
    OfflineEarningMultiplierDesc: "Bội số áp dụng cho Lãi nghỉ chơi",
    PrestigeAlertTitle: "Bạn có chắc không?",
    PrestigeAlertContent:
        "Công ty của bạn sẽ được thanh lý, bạn sẽ nhận được tiền Thụy Sĩ và khởi nghiệp một công ty mới ở %{city}",
    PrestigeCurrencyDesc:
        "Đây là tiền trong tài khoản bí mật của bạn trong ngân hàng Thụy Sĩ, bạn có thể sử dụng khi Khởi đầu ở một Thành phố mới",
    Prestige: "Xèng về",
    Cancel: "Hủy",
    SaveFileCorrupted: "Bản lưu bị lỗi",
    CheatDetected: "Bản lưu cũ của bạn không vượt qua được kiểm tra của máy chủ. Bạn sẽ bắt đầu lại từ đầu",
    LoadGameError: "Không mở được bản lưu",
    LoadGameErrorMessage: "Báo lỗi: %{message}",
    LoadGameErrorDesc: "Xin hãy kiểm tra đường truyền. Nếu vần đề vẫn lặp lại, xin hãy liên hệ hỗ trợ",
    ExpansionPackIncompatible:
        "Bạn đang mở một bản lưu có Bản mở rộng, nhưng phiên bản trò chơi của bạn không có Bản mở rộng nào",
    SaveFileMigrated: "Thời đại mới: Beta đã về",
    SaveFileMigratedDesc:
        "Cám ơn bạn đã tham gia bản thử Alpha. Bản đồ cũ của bạn không tương thích nhưng chúng tôi đã bảo lưu dữ liệu của bạn và tặng bạn ít phần thưởng",
    ClaimSwissMoney: "Nhận %{amount} tiền Thụy Sĩ 💵",
    SaveFileMigratedFinePrint:
        "Giá trị vốn hóa của bạn đã được quy đổi sang tiền Thụy Sĩ và gom vào với tiền chưa sử dụng. Bạn sẽ nhận được thêm 50% tiền Thụy Sĩ vì đã tham gia thử nghiệm Alpha. Số tiền Thụy Sĩ tối đa có thể mang theo là 200",
    CashIn: "Xèng về",
    CurrentCity: "Thành phố hiện tại",
    CashInDesc:
        "Bạn sẽ nhận được số tiền Thụy Sĩ này nếu bạn chuyển đến thành phố mới. Số tiền này được tính dựa giá trị vốn hóa trên thị trường của công ti bạn và giá trị này phải đạt được %{amount} trước khi bạn có thể được thanh toán tiền Thụy Sĩ",
    MoveToNewMap: "Khởi đầu ở một Thành phố mới",
    CityName: "Thành phố",
    CitySize: "Kích thước bản đồ",
    GridType: "Hình dạng ô",
    StartInThisCity: "Bắt đầu mới ở %{city}",
    CityBonus: "Ưu điểm của thành phố",
    ResourceTilePercentage: "Ô tài nguyên",
    MapSquareGrid: "Hình vuông",
    MapHexGrid: "Lục giác",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Nhà máy thép sản lượng x2</li><li>Nhà máy thép không gỉ sản lượng x2</li><li>Vận chuyển sắt miễn phí</li><li>Vận chuyển thép giảm 50% nhiên liệu</li><li>Số lượng Tự động Bán hàng x2</li><li>Không có hiệu suất trên ô</li>",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Xưởng khinh khí cầu đã được mở khóa</li><li>Xưởng bán dẫn sản lượng x2</li><li>Xưởng đóng tàu sản lượng x2</li><li>Xưởng ô tô sản lượng x2</li><li>Xưởng pin Li-ti i-ông đã được mở khóa</li>",
    Toulouse: "Toulouse",
    Rome: "Rome",
    RomeBonus:
        "<li>Đấu trường đã được mở khóa</li><li>Đấu trường hiệu suất x2</li><li>Khởi đầu với Trung tâm Chính sách cấp 5</li><li>Nhà hát lớn sản lượng x2</li><li>Phòng thu thanh cũng sản xuất điểm văn hóa</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Khởi đầu với Viện nghiên cứu cấp 5</li><li>Đại học Bách khoa đã được mở khóa</li><li>Đại học Bách khoa sản lượng x2</li><li>Trường học sản lượng x2</li><li>Đại học Tổng hợp hiệu suất x2</li>",
    HideNotProducing: "Giấu bớt tài nguyên đang không được sản xuất",
    SortByStorage: "Tồn kho",
    SortByProduction: "Sản lượng",
    SortByName: "Tên",
    PlayerTrade: "Giao dịch với người chơi",
    AddTradeFail: "Thêm giao dịch không thành công",
    AddTradeExceedMaximumTrade:
        "Bạn chỉ có thể có tối đa %{number} giao dịch trên thị trường, xin hãy kết toán hoặc hủy một giao dịch khác",
    AddTradeSuccess: "Giao dịch của bạn đã hoàn thành",
    LoadTradeFail: "Không tải được dữ liệu giao dịch, xin vui lòng thử lại sau",
    ClaimTradeFail: "Kết toán giao dịch không thành công, xin vui lòng thử lại sau",
    CancelTradeSuccess: "Giao dịch của bạn đã hủy thành công",
    CancelTradeFail: "Không hủy được giao dịch của bạn, xin vui lòng thử lại sau",
    AcceptTradeFail: "Chấp nhận giao dịch không thành công, xin vui lòng thử lại sau",
    PlayerTradeBanner: "Giao dịch tài nguyên với người chơi khác",
    PlayerTradeResource: "Tài nguyên",
    PlayerTradeAmount: "Số lượng",
    PlayerTradePrice: "Giá $",
    PlayerTradeValue: "Tổng $",
    PlayerTradeWaiting: "Đang chờ...",
    UseTradeCenterPrice: "Dùng giá Trung tâm Thương mại",
    AddTrade: "Thêm Giao dịch",
    ActiveTrades: "Giao dịch đang thực hiện",
    AcceptTrade: "Chấp nhận",
    CancelTrade: "Hủy",
    RefundTrade: "Hoàn lại",
    RefundTradeSuccess: "Giao dịch này đã được hoàn lại: %{resource} đã được trả về Trung tâm Thương mại",
    RefundTradeFail: "Hoàn lại không thành công, xin vui lòng thử lại sau",
    ClaimTrade: "Kết toán",
    RefreshTrade: "Cập nhật",
    PasteYourSave: "Xin vui lòng dán dữ liệu sao lưu",
    FailedToImportSave: "Đọc dữ liệu sao lưu không thành công",
    FailedToImportSaveDesc: "Bản lưu của bạn không tương thích hoặc đã bị hỏng: %{error}",
    SaveCopiedToClipboard: "Dữ liệu bản lưu của bạn đã được chép vào bộ nhớ",
    CancelActiveTradeFirst: "Bạn có giao dịch đang thực hiện với người chơi khác, xin vui lòng kết toán hoặc hủy chúng",
    FailedToCheckActiveTrade:
        "Kiểm tra giao dịch đang thực hiện với người chơi khác không thành công, xin vui lòng thử lại sau",
    PlayerTradeQuotaExceed: "Giao dịch này vượt quá hạn mức của bạn",
    PlayerTradeValidRange: "Khoảng: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Có thể thanh toán",
    PlayerTradeQuota: "Hạn mức còn lại: %{value}",
    PlayerTradeUnavailable:
        "Bạn phải sản xuất tối thiểu 1 tài nguyên và có tồn kho trước khi bạn có thể giao dịch với người chơi khác",
    PlayerTradeToClaim: "Bạn có %{num} giao dịch mới cần kết toán trong Giao dịch với Người chơi",
    PowerBank: "Trạm lưu áp",
    PowerBankBuildDesc: "Lưu trữ điện năng dư thừa và cung cấp điện năng trong trường hợp thiếu hụt điện",
    WarehouseBuildDesc: "Vận chuyển và lưu trữ bất kỳ tài nguyên nào với chi phí nhiên liệu thấp hơn",
    PowerBankChargeSpeed: "Tốc độ nạp",
    PowerBankPowerLeft: "Trữ lượng",
    PowerBankMoreCapacity: "Tiết kiệm Pin",
    PowerBankMoreCapacityDesc: "Trạm lưu áp nạp chậm hơn 50% nhưng có trữ lượng tăng 50%",
    PowerBankNotWorking: "⛔ Trạm lưu áp chỉ có thể xây cạnh nguồn phát điện",
    ExcludeBuildingsShutdown: "Loại trừ các công trình đã ngừng sản xuất",
    ColorTheme: "Bảng màu trò chơi",
    ColorThemeDesc: "Bảng màu cho hình, đánh dấu, lưới và nền của trò chơi. CẦN CHẠY LẠI",
    SiliconMine2xOutput: "Thung lũng Silicon",
    SiliconMine2xOutputDesc:
        "Mỏ silic sản xuất x2 silic nhưng sử dụng thêm 50% điện năng và vận chuyển silic tốn thêm 50% nhiên liệu",
    CoalMine2xOutput: "Cách mạng Công nghiệp",
    CoalMine2xOutputDesc:
        "Mỏ than sản xuất x2 Than nhưng sử dụng thêm 50% điện năng và vận chuyển Than tốn thêm 50% nhiên liệu",
    AlMine2xOutput: "Luyện nhôm",
    AlMine2xOutputDesc: "Mỏ nhôm sản xuất x2 Nhôm và sử dụng x2 điện năng",
    LoggingCamp2xOutput: "Phá rừng",
    LoggingCamp2xOutputDesc: "Xưởng đốn gỗ sản xuất 2x Gỗ và vận chuyển Gỗ tốn x2 nhiên liệu",
    HideResourceMovement: "Giấu vận chuyển tài nguyên",
    HideResourceMovementDesc:
        "Tính năng này sẽ giấu di chuyển tài nguyên (mấy dấu chấm nhỏ xíu) trên bản đồ và chỉ hiển thị tương ứng khi bạn chọn một công trình",
    PowerBankLeft: "Trữ lượng",
    ColorThemeEditor: "Thay đổi bảng màu",
    ColorThemeEditorDesc: "Bạn có thể chọn màu đè lên bảng màu hiện tại. Bạn đã có %{num} màu đè",
    ColorThemeEditorSave: "Lưu",
    ColorThemeEditorReset: "Trả lại",
    ColorThemeEditorResetAll: "Trả lại toàn bộ",
    NewMessageMentions: "Bạn có tin nhắn mới: %{message}",
    HideChatMentions: "Giấu tin nhắn của bạn",
    HideChatMentionsDesc: "Giấu thông báo và không chơi âm thanh nhắc nhở khi bạn có tin nhắn,",
    PendingConstructionCannotReload:
        "Bạn có công trình đang trong quá trình xây dựng, trò chơi không thể đọc lại dữ liệu",
    AcceptTradeFailRateLimit: "Bạn chỉ có thể chấp nhận một giao dịch trong mỗi %{time} giây",
    DowngradeBuilding: "Hạ cấp",
    CancelTradeConfirmDialogTitle: "Bạn muốn hủy giao dịch này?",
    CancelTradeConfirmDialogYes: "Có",
    CancelTradeConfirmDialogNo: "Không",
    WarehouseInputRoutes: "Các nguồn cung cấp",
    WarehouseAddInput: "Thêm nguồn cung cấp",
    WarehouseTapToSelect: "Nhấp vào bản đồ để chọn...",
    WarehouseFindOnMap: "🔍 Tìm trên bản đồ",
    WarehouseRemoveRoute: "Hủy bỏ",
    WarehouseAddRouteFail: "Không thêm được nguồn cung: ô bạn chọn không phù hợp",
    LevelN: "Cấp %{level}",
    Surplus: "Thặng dư",
    Production: "Sản lượng",
    Consumption: "Tiêu thụ",
    WarehouseInputCapacityDescV2: "Tổng lưu lượng nhập hàng, chia đều cho số nguồn cung",
    WarehouseInputCapacityPerRoute: "Lưu lượng cho mỗi nguồn: ",
    PlayerCountryFlag: "Quốc kỳ cho người chơi",
    PlayerCountryChooseFlag: "Theo thứ tự bảng chữ cái cho mã quốc gia",
    WindTurbineAlwaysWork: "Nổi gió",
    WindTurbineAlwaysWorkDesc: "Điện gió hoạt động 100% thời gian nhưng sản xuất ít đi 30% điện năng",
    BookPublisherScience: "Ấn phẩm khoa học",
    BookPublisherScienceDesc: "Nhà xuất bản sản xuất điểm khoa học thay vì văn hóa",
    WarehouseOutwardFuelSave: "Giao hàng miễn phí",
    WarehouseOutwardFuelSaveDesc:
        "Kho bãi cung cấp mức tiết kiệm nhiên liệu cho các tuyến xuất hàng như các tuyến nhập hàng",
    ImportSaveVersionTooNew:
        "Bạn đang đọc bản lưu từ bản %{saveVersion} nhưng trò chơi của bạn đang ở bản %{gameVersion}. Xin vui lòng nâng cấp trò chơi trước",
    BatteryFuelEconomy: "Pin sạc",
    BatteryFuelEconomyDesc: "Nhiên liệu từ pin tăng 100% hiệu suất (tức là giảm 50% chi phí nhiên liệu)",
    ShowTheoreticalInputOutputCapacity: "Hiển thị dung lượng nguyên liệu/thành phẩm trên lý thuyết",
    SpecialTransportCost: "Tài nguyên có chi phí vận chuyển đặc biệt",
    FreeTransportCost: "Tài nguyên vận chuyển miễn phí",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Tài nguyên có xu hướng gom lại với nhau</li><li>Kho bãi tăng thêm 50% tiết kiệm nhiên liệu</li><li>Công trình đặc thù: Nhà xuất bản truyện tranh</li><li>Công trình đặc thù: Xưởng làm phim hoạt hình</li><li>Xưởng bán dẫn sản lượng x2</li><li>Xưởng pin Li-ti i-ông sản lượng x2</li><li>Xưởng pin đã được mở khóa</li><li>Xưởng pin sản lượng x2</li><li>Nhiên liệu pin hiệu suất tăng 100%</li><li>Xưởng pin không cần nguyên liệu Than</li><li>Khởi đầu với 100K pin</li>",
    HideChatDescV2:
        "Giấu các mẩu chat khỏi thanh công cụ phía dưới màn hình. Nếu chọn hiển thị tin chat, bạn đồng ý với ",
    HideChatDescV2ToS: "Điều khoản sử dụng dịch vụ của chúng tôi",
    IntegratedCircuitFab: "Xưởng vi mạch",
    MangaPublisher: "Nhà xuất bản truyện tranh",
    Manga: "Truyện tranh",
    AnimeStudio: "Xưởng phim hoạt hình",
    Anime: "Phim hoạt hình",
    PlayerTradeAction: "Hành động",
    PlayerTradeBuy: "Mua",
    PlayerTradeSell: "Bán",
    PlayerTradeBid: "Đấu giá",
    PlayerTradeAsk: "Hỏi",
    CancelTradeConfirmDialogDescV2:
        "Hủy giao dịch này sẽ hoàn lại %{percent} tài nguyên/tiền mặt. Tài nguyên sẽ được trả về Trung tâm Thương Mại",
    ClaimTradeSuccessV2: "Giao dịch của bạn đã được kết toán thành công: %{cashOrResource}",
    AcceptTradeSuccessV2: "Bạn đã chấp nhận giao dịch này: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Tốt hơn giá thị trường",
    ResourceExplorer: "Khai khẩn tài nguyên",
    ResourceExplorerDesc: "Cho phép bạn khai thác tài nguyên từ ô trống trên bản đồ",
    ResourceExplorerDescLong:
        "💡 Khai khuẩn tài nguyên không được hưởng hiệu ứng liền kề. Điện năng sử dụng tùy thuộc vào loại tài nguyên",
    ResourceExplorerSelectResource: "Khai khẩn",
    ProductionSettings: "Cơ cấu sản xuất",
    PlayerTradeQuotaDesc:
        "💡 Hạn mức giao dịch người chơi chiếm %{percent} tổng giá trị vốn hóa của bạn, nó sẽ hoàn trả khi thị trường cập nhật",
    PlayerTradePartialFillTitle: "Chọn phần trăm làm đầy",
    PlayerTradeAmountNotValidV2: "Số lượng giao dịch tối thiểu là 1",
    PlayerTradeOptOut: "Bạn đã từ chối tham dự bảng xếp hạng, bạn không thể giao dịch với người chơi khác",
    FirstTimeReadGuide: "💡 Cần một chút giúp đỡ về cách chơi? Nhấp vào đây để đọc hướng dẫn tân thủ!",
    ReadSteamGuideV2: "Hướng dẫn chơi",
    ReadSteamGuideV2Desc:
        "Bạn có thể đọc các bản hướng dẫn được viết bởi cộng đồng trên Steam - và bạn cũng có thể viết hướng dẫn của chính mình",
    ChatMessageTooLong: "Tin chat của bạn vượt quá số ký tự cho phép",
    ChatPlaceholderV2: "Nhập tin chat của bạn: tối đa %{length} ký tự",
    ShowProfitBreakdown: "Hiển thị phân tích lợi nhuận",
    HideProfitBreakdown: "Giấu phân tích lợi nhuận",
    ProfitBreakdownOutput: "Giá thành %{res}",
    ProfitBreakdownInput: "Chi phí %{res}",
    ProfitBreakdownFuel: "Chi phí nhiên liệu",
    BuildingProfit: "Lợi nhuận",
    RestoreBackup: "Đọc dữ liệu",
    SteamLogin: "Đăng nhập qua Steam",
    SteamLoginDialogDesc:
        "Bản lưu trên máy của bạn có Bản mở rộng, bạn cần đăng nhập vào Steam để tiếp tục. Hoặc bạn có thể XÓA BẢN LƯU TRÊN MÁY và chơi lại từ đầu",
    SteamLoginDesc:
        "Nếu bạn đã mua Bản mở rộng trên steam, bạn có thể chơi với bản mở rộng trên trình duyệt sau khi đăng nhập vào Steam",
    SteamLoginYes: "Đăng nhập",
    SteamLoginNo: "Xóa & bắt đầu lại từ đầu",
    KungFuDojo: "Võ đường",
    KungFu: "Võ sinh",
    TaiChi: "Thái Cực quyền",
    TaiChiDojo: "Thái Cực đường",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Xuất khẩu Quốc tế",
    FreeTransportToTradeCenterDesc:
        "Vận chuyển đến kho bãi miễn phí nhưng vận chuyển từ kho bãi tốn thêm 50% nhiên liệu",
    TaiChi10xCulture: "Hòn ngọc Viễn Đông",
    PlayerTradeYouHave: "Trong kho: %{amount}",
    PlayerTradeFillValue: "Giá trị",
    FiberFactory: "Xưởng cáp quang",
    Fiber: "Cáp quang",
    Achievements: "Thành tựu",
    AchievementsDesc: "Bạn đã hoàn thành %{number} trên tổng số %{total} thành tựu",
    AchievementsReward: "Phần thưởng: Tiền Thụy Sĩ +%{swiss}",
    AchievementsRewardToast: "Bạn đã nhận phần thưởng:  Tiền Thụy Sĩ +%{swiss}",
    AchievementsClaim: "Nhận",
    AchievementsToast: "Bạn đã hoàn thành tiêu chí %{name}, xin hãy nhận phần thưởng ở Trụ Sở",
    AchievementStockholm100: "Viking lính mới",
    AchievementStockholm100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Stockholm trong một lần chơi",
    AchievementStockholm500: "Viking tốt nghiệp",
    AchievementStockholm500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Stockholm trong một lần chơi",
    AchievementStockholm1000: "Viking giày dạn",
    AchievementStockholm1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Stockholm trong một lần chơi",
    AchievementOslo100: "Người Na Uy chơi dầu thô",
    AchievementOslo100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Oslo trong một lần chơi",
    AchievementOslo500: "Người Na Uy đầu cơ dầu thô",
    AchievementOslo500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Oslo trong một lần chơi",
    AchievementOslo1000: "Tài phiệt dầu thô Na Uy",
    AchievementOslo1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Oslo trong một lần chơi",
    AchievementRotterdam100: "Chơi chong chóng",
    AchievementRotterdam100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Rotterdam trong một lần chơi",
    AchievementRotterdam500: "Cối xay gió",
    AchievementRotterdam500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Rotterdam trong một lần chơi",
    AchievementRotterdam1000: "Điện gió vũ bão",
    AchievementRotterdam1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Rotterdam trong một lần chơi",
    AchievementDetroit100: "Bán ô tô đầu phố",
    AchievementDetroit100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Detroit trong một lần chơi",
    AchievementDetroit500: "Buôn ô tô tỉnh lẻ",
    AchievementDetroit500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Detroit trong một lần chơi",
    AchievementDetroit1000: "Độc quyền phân phối toàn quốc",
    AchievementDetroit1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Detroit trong một lần chơi",
    AchievementBoston100: "Cử nhân kiếm tiền",
    AchievementBoston100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Boston trong một lần chơi",
    AchievementBoston500: "Thạc sĩ đầu tư",
    AchievementBoston500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Boston trong một lần chơi",
    AchievementBoston1000: "Tiến sĩ in tiền",
    AchievementBoston1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Boston trong một lần chơi",
    AchievementRome100: "Hoàng đế Diocles",
    AchievementRome100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Rome trong một lần chơi",
    AchievementRome500: "Đại đế Constantine",
    AchievementRome500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Rome trong một lần chơi",
    AchievementRome1000: "Đại đế Augustus",
    AchievementRome1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Rome trong một lần chơi",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Hamburg trong một lần chơi",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Hamburg trong một lần chơi",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Hamburg trong một lần chơi",
    AchievementToulouse100: "Máy bay A310",
    AchievementToulouse100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Toulouse trong một lần chơi",
    AchievementToulouse500: "Máy bay A330",
    AchievementToulouse500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Toulouse trong một lần chơi",
    AchievementToulouse1000: "Máy bay A380",
    AchievementToulouse1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Toulouse trong một lần chơi",
    AchievementHongKong100: "Chơi chứng khoán nghiệp dư",
    AchievementHongKong100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Hong Kong trong một lần chơi",
    AchievementHongKong500: "Chuyên gia giao dịch chức khoán",
    AchievementHongKong500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Hong Kong trong một lần chơi",
    AchievementHongKong1000: "Nhà quản lý quỹ đầu tư",
    AchievementHongKong1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Hong Kong trong một lần chơi",
    AchievementStPetersburg100: "Đại công quốc",
    AchievementStPetersburg100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở St. Petersburg trong một lần chơi",
    AchievementStPetersburg500: "Sa hoàng",
    AchievementStPetersburg500Desc: "Kiếm được 100 Tiền Thụy Sĩ ở St. Petersburg trong một lần chơi",
    AchievementStPetersburg1000: "Nga hoàng",
    AchievementStPetersburg1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở St. Petersburg trong một lần chơi",
    AchievementOsaka100: "Nam tước",
    AchievementOsaka100Desc: "Kiếm được 100 Tiền Thụy Sĩ ở Osaka trong một lần chơi",
    AchievementOsaka500: "Bá tước",
    AchievementOsaka500Desc: "Kiếm được 500 Tiền Thụy Sĩ ở Osaka trong một lần chơi",
    AchievementOsaka1000: "Công tước",
    AchievementOsaka1000Desc: "Kiếm được 1000 Tiền Thụy Sĩ ở Osaka trong một lần chơi",
    SteamAutoCloudBackup: "Tự động lưu lên Đám mây của Steam",
    SteamAutoCloudBackupFailed: "Tự động lưu lên Đám mây của Steam không thành công: %{error}",
    SteamManualBackup: "Ép lưu lên Đám mây của Steam",
    UILoading: "Đang đọc dữ liệu...",
    UserAuthenticated: "Bạn đã đăng nhập",
    BuildingResourceBreakdown: "Chi tiết doanh thu do nhàn rỗi",
    SortByDeficit: "Thâm hụt",
    SortByRunOut: "Kiệt quệ",
    SocialNetworkInc: "Công ty Mạng xã hội",
    SocialNetwork: "Mạng xã hội",
    DatabaseCompany: "Công ty Cơ sở dữ liệu",
    Database: "Cơ sở dữ liệu",
    SatelinkInc: "Công ty Vệ tinh",
    GameStationInc: "Công ty Máy trò chơi",
    AirShuttleInc: "Công ty Máy Bay",
    AircraftCarrierFactory: "Xưởng tàu sân bay",
    AircraftCarrier: "Tàu sân bay",
    MapExclusive: "đặc trưng của bản đồ",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Xưởng ô tô sử dụng pin thay cho xăng và nhu cầu chỉ bằng 50%",
    HongKongBonusV2:
        "<li>Thuật toán định giá đặc trưng - giá thành và đánh giá cổ phiếu đi theo phân phối đồng đều (biểu đồ hình chuông)</li><li>Thị trường cập nhật và hạn mức giao dịch được hoàn lại nhanh gấp đôi bình thường (mỗi giờ một lần)</li><li>Nghiên cứu có thể mở thông qua giao dịch tài nguyên</li><li>Công trình đặc trưng: Võ đường</li><li>Công trình đặc trưng: Thái Cực đường</li><li>Tăng 50% số lượng tối đa giao dịch với người chơi</li><li>Khởi đầu với thêm 1 danh mục Tự động Bán hàng</li><li>Chính sách đặc trưng: Xuất khẩu Quốc tế</li><li>Chính sách đặc trưng: Hòn ngọc Viễn Đông</li><li>Trung tâm Thương mại chỉ cần 4 tài nguyên là có thể mở khóa</li><li>Khởi đầu với 100M tiền mặt</li>",
    TaiChi10xCultureDescV2:
        "Vận chuyển Võ sinh và Thái Cực quyền miễn phí. Xưởng phim sản lượng x2 nhưng tiêu thụ thêm 50% điện năng",
    SettingsFullScreen: "Toàn màn hình",
    SettingsFullScreenDesc: "Chạy trò chơi trên chế độ toàn màn hình. Chỉ có trên phiên bản Steam",
    LeaderboardByAllPrestigeCurrency: "Tổng số Tiền Thụy Sĩ đã kiếm được",
    LeaderboardByCash: "Tiền mặt hiện có",
    LeaderboardBySwissPerBuilding: "Tiền Thụy Sĩ hiện có trên mỗi công trình",
    LeaderboardTotalValuation: "Tổng giá trị vốn hóa",
    LeaderboardDescV2: "Theo dõi những người chơi hàng đầu",
    LastUpdatedAt: "Cập nhật lần cuối vào lúc",
    DetroitBonusV3:
        "<li>Xưởng động cơ đã được mở khóa</li><li>Xưởng động cơ hiệu suất x2</li><li>Xưởng ô tô sản lượng x2</li><li>Xưởng ô tô sử dụng khí hóa lỏng thay cho xăng</li><li>Vận chuyển ô tô miễn phí</li><li>Chính sách Nikola Tesla miễn phí</li><li>Xưởng tàu hỏa sản lượng x2</li>",
    SaveAndExit: "Lưu lại và đóng trò chơi",
    SaveAndExitDesc:
        "Lưu lại và đóng trò chơi. Hành động này chỉ có trên phiên bản Steam và tương đương với việc nhấp nút Đóng cửa sổ.",
    AutoSellResourceWarningShortLabel: "💡Tự động Bán hàng",
    AutoSellResourceWarningDesc:
        "Bạn đang Tự động Bán hàng tài nguyên này, hàng tồn kho trong Trung tâm Thương mại không thể sử dụng ở đây",
    PlayerTradeLocalPrice: "Giá nội địa: %{price}",
    ChatForceScroll: "Ép cuộn cửa sổ",
    ChatForceScrollDesc:
        "Nếu bạn bật ép cuộn cửa sổ, cửa sổ chat sẽ tự động cuộn khi có tin mới. Ngược lại, cửa sổ sẽ chỉ cuộn khi bạn xuống đến dòng dưới cùng",
    ResourceExplorer2: "Khai khẩn tài nguyên 2.0",
    ResourceExplorer2Desc: "Các ô khai khẩn sản lượng x2 nhưng sử dụng x2 điện năng",
    ConstructionCancel: "Hủy",
    ConstructionPause: "Tạm ngưng",
    ConstructionResume: "Tiếp tục",
    PolicyBlueprint: "Bản thiết kế",
    PolicyBlueprintDesc:
        "Công trình sẽ không tự động bắt đầu xây dựng - thay vì đó chúng cần phải kích hoạt bởi người chơi (Chính sách miễn phí)",
    HighlightUnderConstruction: "...chưa được xây dựng",
    HighlightUnderLevel10: "...dưới cấp 10",
    HighlightUnderLevel20: "...dưới cấp 20",
    HighlightUnderLevel30: "...dưới cấp 30",
    Logout: "Bạn đã bị đăng xuất",
    ConstructionStatusQueueingV2: "Đang xếp hàng",
    ConstructionStatusPausedV2: "Đã tạm ngưng",
    ConstructionStatusBuildingV2: "Đang xây",
    ConstructionStatusUnpaidV2: "Chưa thanh toán",
    ConstructionStatus: "Trạng thái công trình",
    ConstructionStart: "Bắt đầu",
    CostFree: "Miễn phí",
    PlaceBlueprint: "Miễn phí đặt bản thiết kế",
    PlayerTradePriceNotValidV2: "Giá thành giao dịch phải nằm trong khoảng từ %{min} đến %{max}",
    MarketNews: "Tin thị trường",
    MarketNewsApplyToYou: "Chỉ ảnh hưởng bạn",
    MarketNewsApplyToGlobal: "Toàn cầu",
    MarketNewsHighlightAffected: "🔍 Điểm nhấn",
    MarketNewsFilterInput: "Tất cả nguyên liệu %{res} ",
    MarketNewsFilterOutput: "Tất cả thành phẩm %{res} ",
    MarketNewsFilterBoth: "Tất cả nguyên liệu và thành phẩm %{res} ",
    MarketNewsIncrease: "được tăng %{percent}",
    MarketNewsDecrease: "bị giảm %{percent}",
    MarketNewsBuilding: "Công trình này đang chịu ảnh hưởng của %{num} tin tức",
    StockholmBonusV2:
        "<li>Công trình đặc trưng: Nhà sản xuất nhạc</li><li>Xưởng đốn gỗ sản lượng x2</li><li>Xưởng giấy đã được mở khóa</li><li>Xưởng vi mạch sản lượng x2</li><li>Miễn phí chính sách Ấn phẩm khoa học</li>",
    OsloBonusV2:
        "<li>Nhà máy lọc dầu đã được mở khóa</li><li>Nhà máy lọc dầu sản lượng x2</li><li>Miễn phí chính sách Vận chuyển Dầu thô bằng điện</li><li>Xưởng xử lý khí hóa lỏng sản lượng x2</li><li>Điện gió cấp 4 miễn phí x1</li><li>Giếng dầu thô cấp 4 miễn phí x1</li><li>Nhà máy lọc dầu cấp 2 miễn phí x1</li><li>Mỏ khí hóa lỏng cấp 2 miễn phí x1</li>",
    FreeOilTransportV2: "Vận chuyển Dầu thô bằng điện",
    Tutorial4P1:
        "Vận chuyển tài nguyên cần sử dụng nhiên liệu. Có nhiều loại nhiên liệu khác nhau và hiện tại bạn đang dùng <em>xăng⛽</em> làm nhiên liệu. Bạn có <em>Nhà máy lọc dầu</em> nhập Dầu thô từ Giếng dầu và sản xuất xăng.<br><br>Những <em>chấm</em> tí hon đang di chuyển đại diện cho sự vận chuyển thời gian thực của tài nguyên. Khuyến nghị bạn tối ưu hóa vị trí các công trình để giảm thiểu quãng đường cần vận chuyển.<br><br><em>Nâng cấp</em> công trình sẽ tăng sản lượng, nhưng đồng thời cũng tăng nhu cầu sử dụng điện và nguyên liệu.",
    Tutorial4P2:
        "Bạn có thể chuyển đổi loại nhiên liệu trong <em>Cục Vận tải🚦</em> - trên bản đồ này, bạn cũng có thể sử dụng <em>khí hóa lỏng</em> làm nhiên liệu.<br><br>Cục vận tải cũng hiển thị cho bạn những tuyến vận tải tốn nhiều nhiên liệu nhất - bạn sẽ muốn theo dõi thông tin này thường xuyên.<br><br>Xin <em>đảm bảo sản lượng nhiên liệu của bạn cao hơn tiêu thụ</em> nếu không sản xuất của bạn sẽ bị đình đốn khi bạn cạn kiệt nhiên liệu.<br><br>Trong trường hợp đó, không cần quá lo lắng, bạn có thể mua một ít nhiên liệu khẩn cấp từ Trung tâm Thương mại hoặc với người chơi khác",
    Tutorial5P2:
        "<em>Cục thống kê📊</em> cung cấp bức tranh tổng thể về sản xuất của bạn. Bạn có thể xem chi tiết cung cầu các tài nguyên.<br><br>Có rất nhiều biểu đồ📈 hữu dụng - bạn có lẽ sẽ muốn tham khảo chúng để cân đối sản xuất.<br><br>Các con số <em>Tiền mặt💰, Thặng dư điện năng⚡ và Thặng dư nhiên liệu⛽</em> của bạn cũng được hiển thị ở góc trên bên trái - nếu bất kỳ con số nào hiện đỏ, bạn nên điều tra xem có vấn đề gì xảy ra.",
    MusicProducer: "Nhà sản xuất nhạc",
    PlasticFiber: "Cáp quang Nhựa",
    PlasticFiberDesc: "Xưởng cáp quang sử dụng thêm 50% Nhựa và bớt đi 50% Kính",
    NewsEffectx2: "Họp báo",
    NewsEffectx2Desc: "Hiệu ứng tin tức thị trường tăng gấp đôi, cả tích cực lẫn tiêu cực",
    SellRefundPercentage: "Tỷ lệ hoàn trả khi Bán/Hạ cấp",
    SellRefundPercentageDesc:
        "Nếu bạn bán hoặc hạ cấp một công trình, đây là phần trăm tiền mặt và tài nguyên bạn được hoàn lại",
    SellBuildingDescV2:
        "Bán một công trình sẽ hoàn lại %{percent} chi phí đầu tư và %{percent} tài nguyên sẽ được vận chuyển về Trung tâm Thương mại",
    BuilderMoveSpeed: "Tốc độ di chuyển của Đội xây dựng",
    BuilderMoveSpeedDesc: "Tốc độ mà các Đội xây dựng của bạn di chuyển đến công trường",
    EBookInc: "eBook Inc",
    ResourceBooster: "Resource Booster",
    BuildWarningTitle: "Building Might Not Work",
    BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
    BuildWarningBuildAnyway: "Build Anyway",
    ResourceBoosterNotWorking: "⛔ Resource boosters only work next to deposit mines",
    ResourceBoosterPercentage: "💡 This building gets %{percent} output boost from adjacent resource boosters",
    ResourceBoosterBuildings: "Buildings Being Boosted",
    BuildingResourceConversion: "%{resource} Conversion",
    AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
    BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
    AchievementSoftwareGiant: "Software Giant",
    AchievementSoftwareGiantDesc:
        "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
    AchievementSpaceRace: "Space Race",
    AchievementSpaceRaceDesc:
        "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
    AchievementToTheMoon: "To The Moon",
    AchievementToTheMoonDesc:
        "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
    ItsAllGreen: "It's All Green",
    ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
    DeepInRed: "Deep In Red",
    DeepInRedDesc: "Have 50 production lines that has production deficit",
    UseScientificNotation: "Use Scientific Notation",
    UseScientificNotationDesc: "Use scientific notation (e notation) for numbers larger than 999.9T",
    LogoutDescV2:
        "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
    LogBackIn: "Log Back In",
    PlayerTradeNowAllowedV2: "Player trades are not available within %{hour} hours of restoring/importing a save",
    ServerDisconnected:
        "You are disconnected from the server, please check your internet connection and restart the game",
    BuildingUpgradeCostDividerDescV2: "Divide building upgrade cost by this divider",
    ResourceBoosterBannerDesc:
        "💡 You currently have %{number} resource boosters - the power and science input of each is scaled to the number of resource boosters you currently have",
    ResourceBoosterDesc: "Boost the output of adjacent mines",
    BlockUserChatTitle: "Block %{user}",
    BlockUserChatAction: "Block",
    BlockUserChatDesc:
        "The block will be in effect during this game session and you cannot undo this unless you restart the game",
    ChangeNameCooldown: "You can only change your name once every %{hour} hours",
    AtomicBombFactory: "Atomic Bomb Factory",
    AtomicBomb: "Atomic Bomb",
    DynamiteFactory: "Dynamite Factory",
    Dynamite: "Dynamite",
    NuclearMissileFactory: "Nuclear Missile Factory",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Liquid Propellant Factory",
    GasPropellantFactory: "Gas Propellant Factory",
    Propellant: "Propellant",
    ProjectV2: "Project V-2",
    ICBMFactory: "ICBM Factory",
    ICBM: "ICBM",
    RadarFactory: "Radar Factory",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Command",
    SpaceForce: "Space Force",
    SteamAutoCloudBackupDescV2:
        "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
    SpaceColony: "Space Colony",
    SpaceColonyInc: "Space Colony",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Adjacent Bonus Square",
    AdjacentBonusSquareDesc: "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
    ResourceBoosterSquare: "Resource Booster Square",
    ResourceBoosterSquareDesc:
        "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
    SteelMillx2: "Steel Furnace Modernization",
    SteelMillx2Desc: "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
    IronSteelZone: "Iron Steel Zone",
    IronSteelZoneDesc:
        "Resource booster provide a %{percent} output bonus to adjacent steel mills or stainless steel plants for each working iron mine it is boosting",
    FuelDynamite: "Fuel Dynamite",
    FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
    StPetersburgBonusV2:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
    ToulouseBonusV2:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
};
