export const VN = {
    Translator: "Người dịch",
    TranslatorName: "Dương Quỳnh",
    Language: "Ngôn ngữ",
    ThisLanguage: "Tiếng Việt",
    OK: "Đồng ý",
    SteelMill: "Nhà máy thép",
    StainlessSteelPlant: "Nhà máy thép không gỉ",
    CircuitFoundry: "Xưởng vi mạch",
    IntegratedCircuit: "Chíp vi mạch",
    OilWell: "Giếng dầu thô",
    Wood: "Gỗ",
    LoggingCamp: "Xưởng đốn gỗ",
    LumberMill: "Xưởng cưa",
    Lumber: "Gỗ tấm",
    Paper: "Giấy",
    PaperMill: "Xưởng giấy",
    Book: "Sách",
    BookPublisher: "Nhà xuất bản",
    OilRefinery: "Xưởng lọc dầu",
    Sell: "Bán",
    Upgrade: "Nâng cấp",
    Build: "Xây",
    Inspect: "Tìm hiểu",
    Buildings: "Công trình",
    Iron: "Sắt",
    Actions: "Hành động",
    FuelType: "Chọn nhiên liệu",
    FuelCost: "Mức hao nhiên liệu",
    FuelConsumption: "%{fuel} sử dụng",
    FuelEconomy: "Tiết kiệm nhiên liệu",
    FuelProduction: "Sản xuất %{fuel}",
    FuelInStorage: "%{fuel} trong bể chứa",
    Plastic: "Nhựa",
    FuelSurplus: "%{fuel} thặng dư",
    Petrol: "Xăng",
    Buy: "Mua",
    NoLiquidity: "Không có giao dịch",
    NoLiquidityTurnOffAutoSell: "Không đủ lượng giao dịch cho %{res}, ngừng tự động bán hàng",
    Multiplier: "Bội số",
    MultiplierDesc: "Mỗi 10 cấp, bạn được thêm 1 bội số",
    SellBuilding: "Bán công trình",
    PowerGrid: "Lưới điện",
    TradeAmount: "Khối lượng giao dịch",
    SortBy: "Sắp xếp theo",
    SortByPrice: "Giá cả",
    SortByAmount: "Số lượng",
    NotEnoughResourcesForTrade: "Không đủ tài nguyên trong Trung Tâm Thương Mại để thực hiện giao dịch này",
    NotEnoughResources: "Không đủ tài nguyên để thực hiện hành động này",
    Transportation: "Vận tải",
    Cash: "Tiền mặt",
    Aluminum: "Nhôm",
    ResearchPoint: "Điểm nghiên cứu",
    Unlock: "Mở khóa",
    BuildingUnlocked: "Công trình %{building} đã được mở",
    Science: "Khoa học",
    ScienceFromPowerDesc: "Nhà máy phát điện sinh ra một lượng nhỏ Khoa học trong quá trình sản xuất điện",
    Culture: "Văn hóa",
    School: "Trường học",
    University: "Đại học Tổng hợp",
    Polytechnic: "Đại học Bách khoa",
    Colosseum: "Đấu trường",
    WindTurbine: "Điện gió",
    Engine: "Động cợ",
    EngineFactory: "Xưởng sản xuất động cơ",
    CameraFactory: "Xưởng máy ảnh",
    Camera: "Máy ảnh",
    Gun: "Súng",
    GunFactory: "Xưởng súng",
    Aircraft: "Máy bay",
    AircraftFactory: "Xưởng máy bay",
    Zeppelin: "Khinh khí cầu",
    ZeppelinFactory: "Xưởng khinh khí cầu",
    Tank: "Xe tăng",
    TankFactory: "Xưởng xe tăng",
    CoalPowerPlant: "Nhà máy điện than",
    PetrolPowerPlant: "Nhà máy điện dầu",
    Copper: "Đồng",
    Gas: "Khí đốt",
    GasPump: "Mỏ khí đốt",
    GasPowerPlant: "Nhà máy điện khí",
    Missile: "Tên lửa",
    MissileFactory: "Xưởng tên lửa",
    Rocket: "Rocket",
    RocketFactory: "Xưởng rocket",
    BuildingPermit: "Giấy phép xây dựng",
    BuildingPermitDesc:
        "Bạn có tất cả %{amount} giấy phép xây dựng, bạn đã xây %{amountBuilt} công trình và còn lại %{amountLeft} giấy phép",
    BuildingLocked: "Công trình này chưa xây được, bạn cần mở khóa trong Viện Nghiên Cứu trước",
    BuildQueue: "Chuỗi xây dựng",
    BuildQueueDesc: "Số công trình trong chuỗi",
    MaxBuilders: "Số đội xây tối đa",
    MaxBuildersDesc: "Số công trình bạn có thể xây cùng lúc",
    Silicon: "Silic",
    AluminumMine: "Mỏ nhôm",
    CopperMine: "Mỏ đồng",
    SiliconMine: "Mỏ silic",
    IronMine: "Mỏ sắt",
    CoalMine: "Mỏ than",
    Headquarter: "Trụ Sở",
    ResearchLab: "Viện Nghiên Cứu",
    TradeCenter: "Trung Tâm Thương Mại",
    Resources: "Tài nguyên",
    NotEnoughPower: "💡 Không đủ điện, đề nghị nâng sản lượng điện",
    NotEnoughFuel: "Không đủ nhiên liệu %{fuel} cho hoạt động này",
    NotEnoughCash: "Không đủ tiền mặt cho hoạt động này",
    NotEnoughSwissMoney: "Không đủ tiền Thụy Sĩ cho hoạt động này",
    BuildingNotEnoughFuel: "💡 Không đủ nhiên liệu %{fuel}",
    AutoSell: "Tự động bán",
    SellAll: "Bán hết",
    Change: "Thay đổi",
    StatisticsBureau: "Cục Thống Kê",
    LogisticsDepartment: "Cục Vận Tải",
    From: "Từ",
    Top20FuelCost: "20 tuyến tốn nhiên liệu nhất",
    To: "Đến",
    TransportTime: "Thời gian vận chuyển",
    TopN: "Top %{n}",
    Warehouse: "Kho hàng",
    TradeWarehouse: "Kho giao dịch",
    Coal: "Than",
    Video: "Video",
    ClothingFactory: "Xưởng quần áo",
    Clothes: "Quần áo",
    Fashion: "Thời trang",
    FashionFactory: "Xưởng thời trang",
    VideoFarm: "Xưởng video",
    SantaFactory: "Xưởng ông già Noel",
    Santa: "Ông già Noel",
    Car: "Ô tô",
    CarFactory: "Xưởng ô tô",
    Ship: "Thuyền",
    SolarPanel: "Tấm năng lượng mặt trời",
    SolarPanelDesc: "💡 Tấm năng lượng mặt trời chỉ hoạt động 5 giây cho mỗi 10 giây, chu kỳ đồng nhất",
    WindTurbineDesc: "💡 Điện gió chỉ hoạt động 8 giây cho mỗi 10 giây, chu kỳ không đồng đều",
    Movie: "Phim",
    MovieStudio: "Xưởng phim",
    Sitcom: "Phim truyền hình",
    TVStudio: "Đài truyền hình",
    PC: "Máy vi tính",
    GameStudio: "Xưởng game",
    Game: "Game",
    ComputerFactory: "Xưởng máy vi tính",
    Shipyard: "Xưởng đóng tàu",
    PowerUsage: "Tiêu thụ điện năng",
    PowerSupply: "Sản xuất điện năng",
    PowerSurplus: "Điện năng thặng dư",
    Level: "Cấp",
    Power: "Điện năng",
    CentralBank: "Ngân Hàng Trung Ương",
    ResourceInput: "Vào",
    ResourceOutput: "Ra",
    ResourceStorage: "Kho chứa",
    ResourceChange: "Thay đổi",
    ResourceInOutDesc: "💡 Bấm vào con số Ra/Vào ở trên để đánh dấu các công trình sản xuất hoặc tiêu thụ",
    ResourceChart: "Biểu đồ tài nguyên",
    MarketUpdateIn: "Sàn giao dịch sẽ làm mới trong %{time}",
    Income: "Thu nhập",
    Semiconductor: "Bán dẫn",
    SemiconductorFactory: "Xưởng bán dẫn",
    Steel: "Thép",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Đào Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Đào Dogecoin",
    Guitar: "Đàn Ghi-ta",
    GuitarFactory: "Xưởng làm ghi-ta",
    Drum: "Trống",
    DrumFactory: "Xưởng làm trống",
    RecordingStudio: "Phòng thu thanh",
    OperaHouse: "Nhà hát lớn",
    CoalGasificationPlant: "Xưởng Khí đốt từ Than",
    GasProcessingPlant: "Xưởng xử lý khí đốt",
    Music: "Nhạc",
    Glass: "Kính",
    PhoneFactory: "Xưởng điện thoại",
    Phone: "Điện thoại",
    GlassFactory: "Nhà máy kính",
    Oil: "Dầu thô",
    Chromium: "Crôm",
    ChromiumMine: "Mỏ Crôm",
    Uranium: "Uranium",
    EnrichedUranium: "Uranium giàu",
    NuclearPowerPlant: "Nhà máy điện nguyên tử",
    UraniumEnrichmentPlant: "Nhà máy làm giàu uranium",
    UraniumMine: "Mỏ uranium",
    Titanium: "Titan",
    TitaniumMine: "Mỏ titan",
    TitaniumAlloyPlant: "Xưởng hợp kim titan",
    ChromiumAlloyPlant: "Xưởng hợp kim Crôm",
    Input: "Nguyên liệu",
    PanelPosition: "Vị trí bảng thông tin",
    PanelPositionDesc: "Hiển thị bảng thông tin bên trái, phải hoặc tự động (tùy vào ô được chọn trên bản đồ)",
    InputCapacity: "Dung lượng nguyên liệu",
    InputCapacityPerCycle: "Dung lượng nguyên liệu mỗi chu kỳ",
    Output: "Thành phẩm",
    OutputCapacity: "Dung lượng thành phẩm",
    OutputCapacityPerCycle: "Dung lượng thành phẩm mỗi chu kỳ",
    ResourceDeposit: "Trữ lượng",
    RecommendedBuilding: "💡 Ô này có trữ lượng %{resource}",
    AdjacentBonus: "Hiệu ứng liền kề",
    AdjacentBonusDesc: "Bạn được thêm %{bonus}% sản lượng cho mỗi công trình liền kề cùng loại",
    ConsiderIncreaseProduction: "💡 Đề nghị tăng sản lượng %{resource}",
    AlwaysTransportInput: "Chế độ tích trữ",
    AlwaysTransportInputTradeCenter: "Luôn xuất hàng",
    AlwaysTransportInputTradeCenterDesc:
        "Luôn vận chuyển thành phẩm đến Trung tâm Thương mại ngay cả khi không bật chế độ tự động bán cho tài nguyên này",
    AlwaysTransportInputDesc: "Luôn vận chuyển nguyên liệu, ngay cả khi vượt qua số lượng tối thiểu cần cho sản xuất",
    ProductionCycleLength: "Chu kỳ sản xuất",
    ProductionCycleLengthDesc:
        "Thời gian của một chu kỳ sản xuất tính bằng giây. Kéo dài chu kỳ sẽ tăng nguyên liệu và thành phẩm tương ứng, làm hạ thấp nhu cầu vận chuyển nguyên liệu",
    MaxInputDistance: "Khoảng cách tối đa vận chuyển nguyên liệu",
    MaxInputDistanceDesc: "Khoảng cách tối đa mà công trình sẽ vận chuyển nguyên liệu, tính bằng số ô",
    AutoSellCapacity: "Số lượng tự động bán",
    AutoSellCapacityDesc: "Số lượng tối đã tài nguyên có thể bán mỗi giây cho mỗi tài nguyên",
    CurrentAutoSellCapacityMultiplier: "Bội số hiện tại: x%{n}",
    AutoSellConcurrency: "Tự động bán đồng thời",
    AutoSellConcurrencyDesc: "Số lượng tối đa loại tài nguyên có thể đồng thời tự động bán",
    MaxAutoSellConcurrencyReached:
        "Bạn đã sử dụng hết số loại tài nguyên có thể tự động bán, đề nghị tắt một loại khác để có thể bật cho tài nguyên này",
    CannotSellBuilding: "Không thể bán công trình vào lúc này",
    WallStreet: "Phố Wall",
    MarketCap: "Giá trị vốn hóa",
    MarketCapDesc: "Tổng giá trị vốn hóa thị trường của tập đoàn của bạn",
    BuildingValuation: "Giá trị nhà xưởng",
    BuildingValuationDesc: "Tổng giá trị các công trình, gồm cả giấy phép xây dựng và các mức nâng cấp",
    ResourcesValuation: "Giá trị tài nguyên",
    ResourcesValuationDesc: "Tổng giá trị tài nguyên trong kho bãi",
    Battery: "Pin",
    BatteryFactory: "Xưởng pin",
    RatingBuy: "Mua",
    RatingSell: "Bán",
    SwissShop: "Cửa hàng Thụy Sĩ",
    RatingHold: "Giữ",
    RatingOutperform: "Vượt bậc",
    RatingUnderperform: "Yếu",
    StockRating: "Đánh giá cổ phiếu",
    JetEngine: "Động cơ phản lực",
    Helicopter: "Trực thăng",
    Lithium: "Li-ti",
    LithiumMine: "Mỏ li-ti",
    LiionBatteryFactory: "Xưởng pin li-ti i-ông",
    HelicopterFactory: "Xưởng trực thăng",
    Satellite: "Vệ tinh",
    ToyFactory: "Xưởng đồ chơi",
    Toy: "Đồ chơi",
    SpaceStation: "Trạm vũ trụ",
    SpaceStationFactory: "Xưởng lắp trạm vũ trụ",
    OperatingSystem: "Hệ điều hành",
    OperatingSystemCompany: "Công ty sản xuất hệ điều hành",
    LinuxDistribution: "Bản phân phối Linux",
    Internet: "Internet",
    WebBrowser: "Trình duyệt",
    Console: "Máy trò chơi",
    ConsoleFactory: "Xưởng sản xuất máy trò chơi",
    Train: "Tàu hỏa",
    TrainFactory: "Xưởng tàu hỏa",
    ShoeFactory: "Xưởng giày",
    Shoes: "Giày",
    ArtilleryFactory: "Xưởng đại bác",
    Artillery: "Đại bác",
    SubmarineFactory: "Xưởng tàu ngầm",
    Submarine: "Tàu ngầm",
    Spaceship: "Tàu vũ trụ",
    RobotFactory: "Xưởng người máy",
    Robot: "Người máy",
    SpaceshipFactory: "Xưởng tàu vũ trụ",
    SatelliteFactory: "Xưởng vệ tinh",
    JetEngineFactory: "Xưởng động cơ phản lực",
    StockRatingDesc:
        "Chỉ số đánh giá cổ phiếu của các nhà phân tích phố Wall, chỉ số này sẽ ảnh hưởng đến giá trị vốn hóa và được tái lập cùng với chu kỳ thị trường",
    InterestRate: "Lãi suất qua đêm",
    InterestRateDesc: "Lãi suất bạn nhận được dựa trên giá trị vốn hóa trong khi bạn nghỉ chơi",
    OfflineEarning: "Tiền lãi nghỉ chơi",
    OfflineEarningDesc: "Tiền lãi nghỉ chơi phụ thuộc vào giá trị vốn hóa và lãi suất",
    PerMin: "%{amount} mỗi phút",
    OfflineEarningTime: "Thời gian tính lãi nghỉ chơi",
    OfflineEarningTimeDesc: "Bạn sẽ nhận được tiền lãi nghỉ chơi cho đến thời gian này",
    BuyPermit: "Mua giấy phép",
    NotEnoughBuildingPermit: "Không đủ giấy phép xây dựng, đề nghị mua thêm để có thể tiếp tục xây",
    MovingAverage: "Thay đổi trung bình",
    MovingAverageDesc: "Thể hiện số liệu thay đổi trung bình cho tài nguyên, thay vì số liệu thời gian thực",
    AllowZoom: "Phóng to thu nhỏ",
    AllowZoomDesc:
        "Bật hỗ trợ phóng to thu nhỏ. Sử dụng con lăn của chuột để thay đổi. Mức độ phóng hiện tại là %{zoom}",
    AllowZoomMobileDesc:
        "Bật hỗ trợ phóng to thu nhỏ. Dùng động tác nhéo để thay đổi. Mức độ phóng hiện tại là %{zoom}",
    Settings: "Tùy chọn",
    SellBuildingFullRefundDesc:
        "Chính sách tái cơ cấu công trình đang bật, bán một công trình sẽ hoàn lại toàn bộ giá trị trong vòng %{time} tới",
    Sound: "Hiệu ứng âm thanh",
    SoundDesc: "Bật hiệu ứng âm thanh cho nhấp chuột hay báo lỗi",
    AutoHighlight: "Tự động đánh dấu",
    AutoHighlightDesc: "Tự động đánh dấu các công trình cùng loại khi bạn chọn một công trình",
    MusicDesc: "Bật nhạc: It's Not Over 'Til The Bossa Nova bởi Shane Ivers (https://www.silvermansound.com)",
    Credits: "Công trạng",
    Icons: "Hình",
    MisplacedBuilding: "⛔ Công trình %{building} này xây không đúng trên vỉa tài nguyên tương ứng",
    Left: "Trái",
    Right: "Phải",
    Auto: "Tự động",
    HighlightBuildings: "Đánh dấu công trình",
    HighlightTurnedOff: "...đã bị ngưng hoạt động",
    HighlightStockpileModeOn: "...đang bật chế độ tích trữ",
    HighlightProductionCycleNotDefault: "...có chu kỳ sản xuất > 1",
    HighlightMaxInputDistanceNotDefault: "...có khoảng cách thu tài nguyên tối đa < ∞",
    HighlightNotMakingProfit: "...không có lãi",
    NBuildingsAreHighlighted: "%{n} công trình đã được đánh dấu",
    OnlyToWarehouse: "Chỉ dành cho kho bãi",
    OnlyToWarehouseDesc: "Chỉ kho bãi có thể vận chuyển thành phẩm từ công trình này",
    TurnOffProduction: "Ngừng hoạt động",
    TurnOffProductionDesc: "Ngưng sản xuất. Công trình cũng sẽ không vận chuyển tài nguyên và không sử dụng điện năng",
    ApplyToAll: "Áp dụng cho tất cả các công trình %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Không giới hạn",
    Transport: "Vận chuyển",
    TileModifier: "Hiệu ứng trên ô",
    ShowAllModifiers: "Hiển thị tất cả hiệu ứng",
    HideAllModifiers: "Che hết hiệu ứng",
    NumberOfBuildings: "Số công trình bạn có",
    ShowContent: "Hiển thị nội dung",
    HideContent: "Che nội dung",
    BuyExpansionPack: "Mua với giá %{price}",
    Cities: "Các thành phố",
    InputStrategy: "Chiến lược nhập",
    InputStrategyClose: "Gần hơn",
    InputStrategyCloseDesc: "Ưu tiên kho bãi gần nhất có đủ nguyên liệu",
    InputStrategyFar: "Xa hơn",
    InputStrategyFarDesc: "Ưu tiên kho bãi xa nhất có đủ nguyên liệu",
    InputStrategyAmount: "Số lượng",
    InputStrategyAmountDesc: "Ưu tiên kho bãi có nhiều nguyên liệu nhất, bất kể khoảng cách",
    FuelCostSave: "Tiết kiệm nhiên liệu",
    FuelCostSaveDesc:
        "Kho bãi tiết kiệm được tỉ lệ nhiên liệu nhất định khi nhập tài nguyên vào so với các công trình khác, cấp kho bãi càng cao thì càng tiết kiệm nhiều",
    SoftwareCompany: "Công ty phần mềm",
    Software: "Phần mềm",
    ScreenFactory: "Xưởng màn hình",
    Screen: "Màn hình",
    JoinDiscord:
        "Mời gia nhâp máy chủ Discord của chúng tôi để tham khảo thông tin mới nhất, hướng dẫn cũng như trao đổi",
    ClaimOfflineEarning: "Thu tiền lãi nghỉ chơi",
    OfflineTime: "Thời gian nghỉ chơi",
    Minutes: "%{time} phút",
    MaxUpgrade: "Nâng cấp tối đa",
    MaxUpgradeDesc: "Bạn đã lên tới cấp tối đa",
    ClaimAmount: "Tiền mặt +%{amount}",
    EarningPerMinute: "Tỉ lệ lợi nhuận",
    EffectiveTime: "Thời gian tối đa",
    EffectiveTimeDesc: "Thời gian nhận lãi nghỉ chơi tối đa của bạn bằng %{time} phút.",
    BuildSearchPlaceholder: "Gõ tên công trình hoặc tài nguyên để tìm",
    MineOverlayWarning: "Công trình %{building} không bị ảnh hưởng bởi hiệu ứng trên ô",
    WholesaleCenter: "Trung tâm bán sỉ",
    OrderFrom: "Đơn đặt hàng từ %{name}",
    ExpireIn: "Hết hạn trong",
    NotMakingProfitWarning: "💡 Sản xuất không có lãi, đề nghị ngưng vận hành",
    TurnOnAllProductions: "Bật sản xuất",
    TurnOnAllProductionsDesc:
        "Bật sản xuất cho tất cả các công trình, không dùng được khi đang chạy Chính sách Tiết kiệm",
    OperationSuccessful: "Hành động này đã được thực thi",
    TurnOn: "Bật lên",
    Reward: "Phần thưởng",
    PerSecond: "%{time}/giây",
    PerCycle: "%{amount}/chu kỳ",
    PolicyPoint: "Điểm chính sách",
    PolicyPointPerMinute: "Tốc độ xử lý",
    PolicyPointPerMinuteDesc: "Bạn nhận được điểm chính sách cho mỗi phút chơi",
    YourWilLGaimPolicyPoints: "Bạn sẽ nhận được %{amount} điểm chính sách mỗi %{time} giây",
    PolicyPointDesc: "💡 Càng nhiều chính sách thì chính sách tiếp theo càng tốn nhiều điểm để duy trì",
    NextOrderIn: "Đơn đặt hàng tiếp theo trong",
    FillOrder: "Hoàn thành đơn hàng",
    RejectOrder: "Bỏ qua",
    WholesaleCenterLocked:
        "Bạn cần tối thiểu %{required} loại tài nguyên khác nhau để mở Trung tâm Bán sỉ. Bạn mới có %{current} loại tài nguyên",
    OrderFilled: "Đơn hàng của %{from} đã hoàn thành!",
    PolicyCenter: "Trung tâm Shính sách",
    NewOrder: "Có đơn hàng mới từ %{from}, đề nghị kiểm tra Trung tâm Bán sỉ",
    Policies: "Chính sách",
    PolicyNotEnoughTime: "Bạn không có đủ điểm chính sách",
    TimeLeft: "Còn lại %{time}",
    WholesaleCenterOrderFaster: "Hội chợ Toàn cầu",
    WholesaleCenterOrderFasterDesc:
        "Trung tâm Bán sỉ nhận được đơn hàng nhanh gấp đôi và số lượng hàng hóa tăng gấp đôi",
    PolicyOilWellPowerx2: "Mỏ dầu siêu cấp",
    PolicyOilWellPowerx2Desc: "Mỏ dầu sản xuất 2x dầu và sử dụng x2 điện năng",
    HalfTransportSpeed: "Chạy chậm để tiết kiệm",
    HalfTransportSpeedDesc: "Tốc độ vận chuyển giảm 25% và nhiên liệu tiêu thụ giảm 25%",
    RefineryMoreOil: "Thêm xăng thêm vấn đề",
    RefineryMoreOilDesc: "Xưởng lọc dầu sản xuất thêm 50% xăng và bớt đi 50% nhựa",
    StickyInput: "Đầu vào cố định",
    StickyInputDesc:
        "Công trình sẽ ưu tiên vận chuyển từ nguồn cung cũ thay vì liên tục tìm nguồn cung tốt nhất mỗi chu kỳ (Chính sách MIỄN PHÍ)",
    RefineryMorePlastic: "Thêm nhựa thêm vấn đề",
    RefineryMorePlasticDesc: "Xưởng lọc dầu sản xuất bớt đi 50% xăng và thêm 50% nhựa",
    FreeOilTransportDesc: "Vận chuyển dầu thô không cần nhiên liệu nhưng mỏ dầu sử dụng x2 điện năng",
    SuperSteelMill: "Thiết Tâm",
    SuperSteelMillDesc: "Nhà máy thép sử dụng bớt đi 50% than nhưng tăng thêm 25% sắt và 25% điện năng",
    AlSemiconductor: "Vi mạch nhôm",
    AlSemiconductorDesc: "Xưởng vi mạch dùng Nhôm thay vì Đồng",
    CostSaver: "Tiết kiệm",
    CostSaverDesc: "Nếu nguyên liệu của một công trình đắt hơn thành phẩm, ngưng sản xuất công trình đó",
    CostSaverBuildingDesc: "Chính sách Tiết kiệm đang chạy, sản xuất sẽ tự động bật/tắt tùy theo lỗ/lãi",
    CostSaverBuildingWarning: "Chính sách Tiết kiệm đang chạy, bạn không thể can thiệp trực tiếp",
    GlassUseCoal: "Kính đen",
    GlassUseCoalDesc: "Nhà máy kính sử dụng thêm 50% than và bớt đi 50% silic",
    AdjacentBonusOnlyOutput: "Hiệu ứng liền kề cộng",
    AdjacentBonusOnlyOutputDesc:
        "Hiệu ứng liền kề không sử dụng thêm nguyên liệu nhưng sừ dụng thêm điện năng và chỉ đạt được 50% hiệu quả",
    IronMine2xOutput: "Trọng thiết",
    IronMine2xOutputDesc: "Mỏ sắt sản xuất x2 sắt nhưng vận chuyển sắt tốn x2 nhiên liệu",
    SolarPanelAlwaysWork: "Mặt trời không bao giờ lặn",
    SolarPanelAlwaysWorkDesc: "Tấm năng lượng mặt trời hoạt động 100% thời gian nhưng giảm 60% sản lượng",
    SteelScience: "Kiến thức từ Thép",
    SteelScienceDesc: "Nhà máy thép dùng x2 nguyên liệu và sản xuất thêm điểm khoa học",
    ShowWarehouse: "Mở khóa kho bãi",
    ShowWarehouseDesc:
        "Kho bãi là công trình đặc biệt chỉ vận chuyển và tàng trữ tài nguyên, đồng thời cũng giúp tiết kiệm nhiên liệu trong vận chuyển (chính sách MIỄN PHÍ)",
    WholesaleCenterProducingOnly: "Đối tác Bán Sỉ",
    WholesaleCenterProducingOnlyDesc:
        "Đơn hàng của Trung tâm Bán sỉ chỉ bao gồm các tài nguyên mà bạn đang sản xuất (bạn vẫn cần sản xuất đủ số loại tài nguyên để mở khóa Trung tâm Bán sỉ)",
    ShoppingSpree: "Mua sắm điên cuồng",
    ShoppingSpreeDesc:
        "Nếu sản lượng tài nguyên không đủ nhu cầu, tự động mua số lượng cần thiết từ Trung tâm Thương Mại (nếu Tự động Bán đang bật cho tài nguyên này thì hệ thống sẽ bỏ qua)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Mua sắm điên cuồng đang bật, Trung tâm Thương mại sẽ tự động mua tài nguyên bị thiếu hụt",
    ExtraPolicyPoints: "Vận động hành lang",
    ExtraPolicyPointsDesc: "Tăng sản lượng điểm chính sách thêm 50%",
    CrAlloyUseFe: "Crô-sắt",
    CrAlloyUseFeDesc: "Xưởng hợp kim crôm không sử dụng Li-ti nhưng thay bằng x2 Sắt",
    DoubleTileModifier: "Sức mạnh của Thiên nhiên",
    DoubleTileModifierDesc: "Hiệu ứng trên ô x2 - cả tích cực lẫn tiêu cực",
    TileModifierOutputOnly: "Hiệu ứng ô cộng",
    TileModifierOutputOnlyDesc: "Hiệu ứng trên ô chỉ tác động lên sản lượng thành phẩm, nhưng giảm 50% hiệu quả",
    GasPlantPetrol: "Khí hóa lỏng",
    GasPlantPetrolDesc: "Nhà máy điện khí sử dụng thêm khí đốt và sản xuất xăng",
    BuildingRecycle: "Tái cơ cấu công trình",
    BuildingRecycleDesc: "Được hoàn trả toàn bộ chi phí nếu bán công trình trong vòng 1 phút sau khi xây",
    CoalPlantFuel: "Than hóa lỏng",
    CoalPlantFuelDesc: "Nhà máy điện than sử dung thêm than và sản xuất xăng",
    Welcome: "Chào mừng bạn",
    SeeTutorialAgain: "Thực hiện lại hướng dẫn cách chơi",
    HelpTranslateTheGame: "Hãy giúp dịch thuật trò chơi🌐",
    SkipTutorial: "Bỏ qua hướng dẫn cách chơi",
    NextTutorial: "Tiếp theo",
    Tutorial1:
        "Industry Idle là một trò chơi <em>quản lý tài nguyên</em>, nơi bạn có thể xây nhà xưởng🏭, sản xuất hàng hóa📦 và kiếm tiền💸.<br><br>Hãy cùng tìm hiểu một vài khái niệm để giúp bạn khởi nghiệp. Sẽ không lâu đâu, ngoắc ngón tay hứa đó.",
    Tutorial2:
        "Tất cả các công trình đều cần điện năng⚡, bạn hiện có <em>Điện gió</em> sản sinh ra điện. Bạn có thể tìm thấy sản lượng cung cấp điện hiện tại ở góc trên bên trái.<br><br>Có thể bạn đã để ý thấy Điện gió chỉ sản xuất <em>80%</em> thời gian. Bạn có thể xem xét xây dựng các công trình phát điện khác để có thể phát điện ổn định.",
    Tutorial3:
        "Bạn có rất nhiều <em>vỉa tài nguyên</em> trên bản đồ. Để khai thác tài nguyên, bạn cần xây mỏ⛏️ <em>lên trên</em> các ô tài nguyên đó.<br><br>Ví dụ, bạn có thể xây <em>giếng dầu🛢️</em> để khai thác <em>dầu thô</em> từ một vỉa dầu.<br></br>Vỉa tài nguyên là vô hạn - không cần lo cạn kiệt dự trữ. Ngoài xây mỏ, các loại công trình khác có thể xây được trên bất kỳ ô trống nào.",
    Tutorial5:
        "Để kiếm tiền, bạn cần xuất khẩu tài nguyên thông qua Trung tâm Thương mại. Để làm việc này, chỉ cần bật <em>Tự động bán</em> cho tài nguyên mà bạn muốn bán.<br></br>Bạn cũng có thể mua tài nguyên từ Trung tâm Thương mại. Xin lưu ý, <em>nếu bạn mua một loại tài nguyên, bạn sẽ nâng giá thành</em> và nếu bạn bán tài nguyên, bạn sẽ hạ giá thành.<br><br>Thị trường liên tục <em>biến thiên</em> và giá cả📈 thường xuyên thay đổi.",
    Tutorial6:
        "Để xây các loại công trình mới, bạn cần mở khóa chúng trong <em>Viện nghiên cứu🧪</em>. Viện nghiên cứu cũng chuyển đổi điểm khoa học thành điểm nghiên cứu.<br><br>Điện gió của bạn (cũng như các dạng phát điện khác) liên tục sản sinh ra một lượng nhỏ điểm khoa học trong lúc vận hành. Về sau, bạn có thể xây trường học🏫 và các công trình chuyên môn khác để nâng sản lượng điểm khoa học.<br><br>Giờ bạn đã học được những điều cơ bản, hãy bắt đầu gây dựng nền kinh tế của bạn đi thôi! Đây là chút <em>tiền mặt💸</em> và <em>xăng⛽</em> để giúp bản khởi nghiệp.",
    WelcomePlay: "Chơi",
    WelcomePlayMuted: "Chơi (🔇Tắt nhạc)",
    Changelog: "Thay đổi gần đây",
    ChangelogGotIt: "Đã rõ",
    Chat: "Chat",
    Send: "Gửi",
    Import: "Nhập",
    Export: "Xuất",
    LastBackupAt: "Bảo lưu lần cuối lúc",
    RestoreFromBackup: "Sử dụng bản bảo lưu gần nhất",
    RestoreFromBackupFail: "Khôi phục dữ liệu từ Đám mây của Steam không thành công: bạn có chắc đã lưu rồi không?",
    RestoreFromBackupTitle: "Bạn có chắc không?",
    RestoreFromBackupDesc:
        "Bạn hiếm khi cần khôi phục dữ liệu từ đám mây, trừ khi bản lưu trên máy của bạn bị mất. Bản lưu trên đám mây sẽ cũ hơn một chút so với trên máy.",
    ChatMessages: "Tin nhắn",
    ChangeName: "Thay đổi",
    SaveName: "Lưu",
    NameValidationRule: "Tên của bạn chỉ được chứa chữ cái và số, từ 5 đến 15 ký tự",
    NameValidationRuleProfanity: "Tên của bạn không được chửi bậy",
    ChatMessageRateLimit: "Bạn chỉ có thể gửi tin 10 giây một lần",
    NameSaved: "Đổi tên thành công",
    NoMessages: "Không có tin nhắn mới",
    Leaderboard: "Bảng xếp hạng",
    Name: "Tên",
    Rank: "Hạng",
    Tips1: "Đánh giá cổ phiếu có 5 cấp: Mua, Vượt bậc, Giữ, Yếu and Bán",
    Tips2: "Công trình tự động ngừng vận chuyển nguyên liệu khi đã có đủ cho sản xuất, trừ khi bạn bật chế độ Tích trữ",
    Tips3: "Chi phí nhiên liệu cho vận chuyển tài nguyên được tính bằng khoảng các và số lượng cần vận chuyển",
    Tips4: "Công trình chỉ vận chuyển một loại tài nguyên nếu trên bản đồ có đủ nguồn cung",
    Tips5: "Công trình chỉ vận chuyển tài nguyên từ Trung tâm Thương mại nếu bạn đã tắt Tự động Bán tài nguyên",
    Tips6: "Bạn có thể thấy chi phí nhiên liệu cho từng nguyên liệu dưới tên của chúng trong phần Nhập",
    Tips7: "Nếu bạn mua một tài nguyên, giá thành sẽ tăng lên. Nếu bạn bán một tài nguyên, giá thành sẽ hạ xuống",
    Tips8: "Bạn có thể xem biểu đồ số lượng của từng tài nguyên và thay đổi theo thời gian trong Cục thống kê",
    Tips9: "Điểm nghiên cứu để mở một công trình được xác định bởi giá thành của các nguyên liệu đầu vào",
    Tips10: "Mỗi loại tài nguyên có định giá khác nhau - hãy sẵn sang cho tính biến thiên của thị trường",
    Tips11: "Một thói quen tốt trước khi mở rộng sản xuất là nên kiểm tra sản lượng điện năng và nhiên liệu",
    FPS30: "Tiết kiệm năng lượng",
    OfflineModeDesc:
        "Không kết nối được với máy chủ: bạn sẽ không được cấp Lãi nghỉ chơi. Xin hãy kiểm tra đường truyền của bạn",
    OptOut: "Không tham gia",
    OptIn: "Làm lại và tham gia",
    LeaderboardOptOut: "Không tham gia xếp hạng",
    LeaderboardOptOutDesc:
        "Nếu thực thi, sẽ không gửi điểm xếp hạng nữa. CHÚ Ý: nếu bạn muốn tham gia xếp hạng lại, bạn sẽ phải làm lại từ đầu",
    LeaderboardOptIn: "Làm lại và bật xếp hạng",
    LeaderboardOptInDesc: "Dữ liệu của bạn sẽ bị XÓA trước khi bạn có thể tái tham gia xếp hạng, bạn có chắc không?",
    RewardAdsFailed: "Chưa xem hết quảng cáo nên không có thưởng",
    RewardAdsNotAvailable: "Hiện tại không có quảng cáo (hiện chỉ được hỗ trợ trên iOS/Android)",
    OfflineEarningDoubleSuccess: "Bạn đã nhân đôi Lãi nghỉ chơi",
    FPS30Desc:
        "Bật Tiết kiệm Năng lượng sẽ chạy trò chơi ở 30 hình/giây thay vì 60 hình/giây. Điều này sẽ giúp pin của bạn dùng lâu hơn",
    HighlightAll: 'Đánh dấu "%{type}"',
    HighlightInput: "🔍 Đánh dấu nguồn cầu %{type}",
    HighlightOutput: "🔍 Đánh dấu nguồn cung %{type}",
    TotalInput: "Tổng sản lượng cầu",
    TotalOutput: "Tổng sản lượng cung",
    RunOutIn: "Hết sau %{time}",
    FuelRunOutWarning:
        "💡 Tiêu thụ nhiên liệu của bạn vượt quá sản lượng. Khi hết nhiên liệu dự trữ, vận tải của bạn sẽ bị đình đốn",
    InAmount: "Nhập: %{number}",
    OutAmount: "Xuất: %{number}",
    SwissBank: "Ngân hàng Thụy Sĩ",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Nếu bạn khởi đầu ở thành phố mới, bạn sẽ nhận được %{money} 💵",
    RestorePurchases: "Khôi phục giao dịch",
    RestorePurchasesSuccess: "Giao dịch của bạn đã được khôi phục",
    RestorePurchasesFailed: "Không khôi phục được giao dịch",
    ExpansionPacks: "Bản mở rộng",
    ExpansionPack1: "Bản mở rộng 1",
    ExpansionPack1Owned: "Bản mở rộng 1",
    RequireExpansionPack1: "Bản mở rộng 1",
    RequireExpansionPack1Desc: "Hành động này cần có Bản mở rộng 1",
    RequireAnyExpansionPack: "Dành riêng cho Bản mở rộng",
    RequireAnyExpansionPackDesc: "Tính năng này cần bạn sở hữu ít nhất một Bản mở rộng",
    HideRewardAd: "Tắt quảng cáo",
    HideRewardAdDesc:
        "Tất cả quảng cáo trong trò chơi đều không bắt buộc. Tính năng này sẽ tắt tất cả quảng cáo trong trò chơi.",
    HideDiscordBanner: "Giấu thẻ Discord",
    HideDiscordBannerDesc: "Che thẻ Discord trong trụ sở",
    HideChat: "Giấu khung chat",
    SortedByDeficit: "Sắp theo thiếu hụt",
    PurchaseFailed: "Giao dịch không thành công",
    PurchaseSteamContinue: "Xin hãy thực hiện giao dịch trên Steam",
    PurchaseSuccess: "Giao dịch thành công, cám ơn sự hỗ trợ của bạn",
    PrestigeCurrency: "Tiền Thụy Sĩ 💵",
    RestartDesc: "💡 Chỉ muốn làm lại từ đầu? Bạn có thể dùng Khởi đầu ở một Thành phố mới và chọn thành phố hiện tại",
    PrestigeGoBack: "Quay lại",
    PermanentUpgradeDesc: "Nâng cấp này sẽ đi theo bạn khi bạn Khởi đầu ở một Thành phố mới",
    ProductionMultiplier: "Bội số sản xuất",
    ProductionMultiplierDesc:
        "Nâng cấp sản lượng cho các công trình của bạn (bao gồm các công trình mỏ, nhà xưởng, nhà máy điện, khoa học và văn hóa)",
    FuelCostDiscount: "Giảm chi phí nhiên liệu",
    FuelCostDiscountDesc: "Giảm giá chi phí nhiên liệu khi vận chuyển tài nguyên",
    AutoSellCapacityMultiplier: "Bội số cho Tự động Bán",
    AutoSellCapacityMultiplierDesc:
        "Bội số được áp dụng cho số lượng Tự động Bán bất kể mức nâng cấp hiện tại trong Trung tâm Thương mại",
    BuildingPermitCostDivider: "Số chia giá thành Giấy phép xây dựng",
    BuildingPermitCostDividerDesc: "Lấy giá Giấy phép xây dựng chia cho số này ",
    ExtraAdjacentBonus: "Hiệu ứng Liền kề nâng cao",
    ExtraAdjacentBonusDesc: "Thêm điểm hiệu ứng liền kề cho các công trình cùng loại liền kề nhau",
    OfflineEarningMultiplier: "Bội số Lãi nghỉ chơi",
    OfflineEarningMultiplierDesc: "Bội số áp dụng cho Lãi nghỉ chơi",
    PrestigeAlertTitle: "Bạn có chắc không?",
    PrestigeAlertContent:
        "Công ty của bạn sẽ được thanh lý, bạn sẽ nhận được tiền Thụy Sĩ và khởi nghiệp một công ty mới ở %{city}",
    PrestigeCurrencyDesc:
        "Đây là tiền trong tài khoản bí mật của bạn trong ngân hàng Thụy Sĩ, bạn có thể sử dụng khi Khởi đầu ở một Thành phố mới",
    Prestige: "Xèng về",
    Cancel: "Hủy",
    SaveFileCorrupted: "Bản lưu bị lỗi",
    CheatDetected: "Bản lưu cũ của bạn không vượt qua được kiểm tra của máy chủ. Bạn sẽ bắt đầu lại từ đầu",
    LoadGameError: "Không mở được bản lưu",
    LoadGameErrorMessage: "Báo lỗi: %{message}",
    LoadGameErrorDesc: "Xin hãy kiểm tra đường truyền. Nếu vần đề vẫn lặp lại, xin hãy liên hệ hỗ trợ",
    ExpansionPackIncompatible:
        "Bạn đang mở một bản lưu có Bản mở rộng, nhưng phiên bản trò chơi của bạn không có Bản mở rộng nào",
    SaveFileMigrated: "Thời đại mới: Beta đã về",
    SaveFileMigratedDesc:
        "Cám ơn bạn đã tham gia bản thử Alpha. Bản đồ cũ của bạn không tương thích nhưng chúng tôi đã bảo lưu dữ liệu của bạn và tặng bạn ít phần thưởng",
    ClaimSwissMoney: "Nhận %{amount} tiền Thụy Sĩ 💵",
    SaveFileMigratedFinePrint:
        "Giá trị vốn hóa của bạn đã được quy đổi sang tiền Thụy Sĩ và gom vào với tiền chưa sử dụng. Bạn sẽ nhận được thêm 50% tiền Thụy Sĩ vì đã tham gia thử nghiệm Alpha. Số tiền Thụy Sĩ tối đa có thể mang theo là 200",
    CashIn: "Xèng về",
    CurrentCity: "Thành phố hiện tại",
    CashInDesc:
        "Bạn sẽ nhận được số tiền Thụy Sĩ này nếu bạn chuyển đến thành phố mới. Số tiền này được tính dựa giá trị vốn hóa trên thị trường của công ti bạn và giá trị này phải đạt được %{amount} trước khi bạn có thể được thanh toán tiền Thụy Sĩ",
    MoveToNewMap: "Khởi đầu ở một Thành phố mới",
    CityName: "Thành phố",
    CitySize: "Kích thước bản đồ",
    GridType: "Hình dạng ô",
    StartInThisCity: "Bắt đầu mới ở %{city}",
    CityBonus: "Ưu điểm của thành phố",
    ResourceTilePercentage: "Ô tài nguyên",
    MapSquareGrid: "Hình vuông",
    MapHexGrid: "Lục giác",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Nhà máy thép sản lượng x2</li><li>Nhà máy thép không gỉ sản lượng x2</li><li>Vận chuyển sắt miễn phí</li><li>Vận chuyển thép giảm 50% nhiên liệu</li><li>Số lượng Tự động Bán x2</li><li>Không có hiệu suất trên ô</li>",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Mỏ Uranium sản lượng x2</li><li>Nhà máy làm giàu Uranium sản lượng x2</li><li>Vận chuyển Uranium giảm 50% nhiên liệu</li><li>Vận chuyển súng miễn phí</li><li>Xưởng tên lửa sử dụng Uranium giàu thay vì Titan và Uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Xưởng khinh khí cầu đã được mở</li><li>Xưởng bán dẫn sản lượng x2</li><li>Xưởng đóng tàu sản lượng x2</li><li>Xưởng ô tô sản lượng x2</li><li>Xưởng pin Li-ti i-ông đã được mở</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Mỏ titan sản lượng x2</li><li>Nhà máy làm giàu Uranium hiệu suất x2</li><li>Xưởng động cơ phản lực sản lượng x2</li><li>Xưởng lắp ráp máy bay hiệu suất x2</li><li>Xưởng rocket sử dụng Uranium thay vì Uranium giàu</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Đấu trường đã được mở</li><li>Đấu trường hiệu suất x2</li><li>Khởi đầu với Trung tâm Chính sách cấp 5</li><li>Nhà hát lớn sản lượng x2</li><li>Phòng thu thanh cũng sản xuất điểm văn hóa</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>Khởi đầu với Viện nghiên cứu cấp 5</li><li>Đại học Bách khoa đã được mở</li><li>Đại học Bách khoa sản lượng x2</li><li>Trường học sản lượng x2</li><li>Đại học Tổng hợp hiệu suất x2</li>",
    HideNotProducing: "Giấu bớt tài nguyên đang không được sản xuất",
    SortByStorage: "Tồn kho",
    SortByProduction: "Sản lượng",
    SortByName: "Tên",
    BuildingInProgressCannotPrestige:
        "Bạn có công trình đang xây dựng dở, bạn không thể Khởi đầu ở một Thành phố mới cho đến khi xây xong",
    PlayerTrade: "Giao dịch với người chơi",
    AddTradeFail: "Thêm giao dịch không thành công",
    AddTradeExceedMaximumTrade:
        "Bạn chỉ có thể có tối đa %{number} giao dịch trên thị trường, xin hãy kết toán hoặc hủy một giao dịch khác",
    AddTradeSuccess: "Giao dịch của bạn đã hoàn thành",
    LoadTradeFail: "Không tải được dữ liệu giao dịch, xin vui lòng thử lại sau",
    ClaimTradeFail: "Kết toán giao dịch không thành công, xin vui lòng thử lại sau",
    CancelTradeSuccess: "Giao dịch của bạn đã hủy thành công",
    CancelTradeFail: "Không hủy được giao dịch của bạn, xin vui lòng thử lại sau",
    AcceptTradeFail: "Chấp nhận giao dịch không thành công, xin vui lòng thử lại sau",
    PlayerTradeBanner: "Giao dịch tài nguyên với người chơi khác",
    PlayerTradeResource: "Tài nguyên",
    PlayerTradeAmount: "Số lượng",
    PlayerTradePrice: "Giá $",
    PlayerTradeValue: "Tổng $",
    PlayerTradeWaiting: "Đang chờ...",
    UseTradeCenterPrice: "Dùng giá Trung tâm Thương mại",
    AddTrade: "Thêm Giao dịch",
    ActiveTrades: "Giao dịch đang thực hiện",
    AcceptTrade: "Chấp nhận",
    CancelTrade: "Hủy",
    RefundTrade: "Hoàn lại",
    RefundTradeSuccess: "Giao dịch này đã được hoàn lại: %{resource} đã được trả về Trung tâm Thương mại",
    RefundTradeFail: "Hoàn lại không thành công, xin vui lòng thử lại sau",
    ClaimTrade: "Kết toán",
    RefreshTrade: "Làm mới",
    PasteYourSave: "Xin vui lòng dán dữ liệu sao lưu",
    FailedToImportSave: "Đọc dữ liệu sao lưu không thành công",
    FailedToImportSaveDesc: "Bản lưu của bạn không tương thích hoặc đã bị hỏng: %{error}",
    SaveCopiedToClipboard: "Dữ liệu bản lưu của bạn đã được chép vào bộ nhớ",
    CancelActiveTradeFirst: "Bạn có giao dịch đang thực hiện với người chơi khác, xin vui lòng kết toán hoặc hủy chúng",
    FailedToCheckActiveTrade:
        "Kiểm tra giao dịch đang thực hiện với người chơi khác không thành công, xin vui lòng thử lại sau",
    PlayerTradeQuotaExceed: "Giao dịch này vượt quá hạn mức của bạn",
    PlayerTradeValidRange: "Khoảng: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "Có thể thanh toán",
    PlayerTradeQuota: "Hạn mức còn lại: %{value}",
    PlayerTradeUnavailable:
        "Bạn phải sản xuất tối thiểu 1 tài nguyên và có tồn kho trước khi bạn có thể giao dịch với người chơi khác",
    PlayerTradeToClaim: "Bạn có %{num} giao dịch mới cần kết toán trong Giao dịch với Người chơi",
    PowerBank: "Trạm lưu áp",
    PowerBankBuildDesc: "Lưu trữ điện năng dư thừa và cung cấp điện năng trong trường hợp thiếu hụt điện",
    WarehouseBuildDesc: "Vận chuyển và lưu trữ bất kỳ tài nguyên nào với chi phí nhiên liệu thấp hơn",
    PowerBankChargeSpeed: "Tốc độ nạp",
    PowerBankPowerLeft: "Trữ lượng",
    PowerBankMoreCapacity: "Tiết kiệm Pin",
    PowerBankMoreCapacityDesc: "Trạm lưu áp nạp chậm hơn 50% nhưng có trữ lượng tăng 50%",
    PowerBankNotWorking: "⛔ Trạm lưu áp chỉ có thể xây cạnh nguồn phát điện",
    ExcludeBuildingsShutdown: "Loại trừ các công trình đã ngừng sản xuất",
    ColorTheme: "Bảng màu trò chơi",
    ColorThemeDesc: "Bảng màu cho hình, đánh dấu, lưới và nền của trò chơi. CẦN CHẠY LẠI",
    SiliconMine2xOutput: "Thung lũng Silicon",
    SiliconMine2xOutputDesc:
        "Mỏ silic sản xuất x2 silic nhưng sử dụng thêm 50% điện năng và vận chuyển silic tốn thêm 50% nhiên liệu",
    CoalMine2xOutput: "Cách mạng Công nghiệp",
    CoalMine2xOutputDesc:
        "Mỏ than sản xuất x2 Than nhưng sử dụng thêm 50% điện năng và vận chuyển Than tốn thêm 50% nhiên liệu",
    AlMine2xOutput: "Luyện nhôm",
    AlMine2xOutputDesc: "Mỏ nhôm sản xuất x2 Nhôm và sử dụng x2 điện năng",
    LoggingCamp2xOutput: "Phá rừng",
    LoggingCamp2xOutputDesc: "Xưởng đốn gỗ sản xuất 2x Gỗ và vận chuyển Gỗ tốn x2 nhiên liệu",
    HideResourceMovement: "Giấu vận chuyển tài nguyên",
    HideResourceMovementDesc:
        "Tính năng này sẽ giấu di chuyển tài nguyên (mấy dấu chấm nhỏ xíu) trên bản đồ và chỉ hiển thị tương ứng khi bạn chọn một công trình",
    PowerBankLeft: "Trữ lượng",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Cancel This Trade?",
    CancelTradeConfirmDialogYes: "Yes",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Add Route",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Find on Map",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consumption",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Player Flag",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    WarehouseOutwardFuelSave: "Free Delivery",
    WarehouseOutwardFuelSaveDesc: "Warehouses provide the same fuel save on outward transportation as well",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Resources tend to spawn in clusters</li><li>Warehouse provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
    HideChatDescV2: "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
    HideChatDescV2ToS: "Terms of Service",
    IntegratedCircuitFab: "Integrated Circuit Fab",
    MangaPublisher: "Manga Publisher",
    Manga: "Manga",
    AnimeStudio: "Anime Studio",
    Anime: "Anime",
    PlayerTradeAction: "Action",
    PlayerTradeBuy: "Buy",
    PlayerTradeSell: "Sell",
    PlayerTradeBid: "Bid",
    PlayerTradeAsk: "Ask",
    CancelTradeConfirmDialogDescV2:
        "Cancelling this trade will refund %{percent} of the resource/cash. Resources will be refunded to Trade Center warehouse",
    ClaimTradeSuccessV2: "Your trade has been claimed successfully: %{cashOrResource}",
    AcceptTradeSuccessV2: "This trade has been accepted by you: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "Better Than Market Price",
    ResourceExplorer: "Resource Explorer",
    ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
    ResourceExplorerDescLong: "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
    ResourceExplorerSelectResource: "Explore",
    ProductionSettings: "Production Settings",
    PlayerTradeQuotaDesc: "💡 Player trade quota is %{percent} of your market cap, it resets when the market updates",
    PlayerTradePartialFillTitle: "Choose Fill Percentage",
    PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
    ReadSteamGuideV2: "Game Guides",
    ReadSteamGuideV2Desc: "You can read community created guides on Steam - and you can create your own as well",
    ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
    ChatPlaceholderV2: "Type your message: max %{length} chars",
    ShowProfitBreakdown: "Show Profit Breakdown",
    HideProfitBreakdown: "Hide Profit Break",
    ProfitBreakdownOutput: "%{res} Output",
    ProfitBreakdownInput: "%{res} Input",
    ProfitBreakdownFuel: "Fuel Cost",
    BuildingProfit: "Profit",
    RestoreBackup: "Restore",
    SteamLogin: "Sign In Through Steam",
    SteamLoginDialogDesc:
        "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
    SteamLoginDesc: "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
    SteamLoginYes: "Sign In",
    SteamLoginNo: "Erase & Start Over",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "International Export Trade",
    FreeTransportToTradeCenterDesc:
        "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
    TaiChi10xCulture: "Pearl of the Orient",
    PlayerTradeYouHave: "In Storage: %{amount}",
    PlayerTradeFillValue: "Value",
    FiberFactory: "Fiber Factory",
    Fiber: "Fiber",
    Achievements: "Achievements",
    AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
    AchievementsReward: "Reward: Swiss Money +%{swiss}",
    AchievementsRewardToast: "You have claimed the reward:  Swiss Money +%{swiss}",
    AchievementsClaim: "Claim",
    AchievementsToast: "You have achieved %{name}, claim your reward in Headquarter",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Earn 100 Swiss Money in Stockholm in a single run",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Earn 500 Swiss Money in Stockholm in a single run",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Earn 1000 Swiss Money in Stockholm in a single run",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Earn 100 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Earn 500 Swiss Money in Rotterdam in a single run",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Earn 1000 Swiss Money in Rotterdam in a single run",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Earn 1000 Swiss Money in Detroit in a single run",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Earn 1000 Swiss Money in Hamburg in a single run",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Earn 100 Swiss Money in Toulouse in a single run",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Earn 500 Swiss Money in Toulouse in a single run",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Earn 1000 Swiss Money in Toulouse in a single run",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Earn 100 Swiss Money in Hong Kong in a single run",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Earn 500 Swiss Money in Hong Kong in a single run",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Earn 1000 Swiss Money in Hong Kong in a single run",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Earn 100 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Earn 500 Swiss Money in St. Petersburg in a single run",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Earn 1000 Swiss Money in St. Petersburg in a single run",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
    SteamAutoCloudBackup: "Steam Cloud Auto Backup",
    SteamAutoCloudBackupDesc:
        "The game saves automatically to your local save. Your local save is synced to Steam Cloud every 10 minutes. You can force Steam cloud backup at any time.",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
    SteamManualBackup: "Force Steam Cloud Backup",
    UILoading: "Loading...",
    UserAuthenticated: "You are authenticated",
    BuildingResourceBreakdown: "Idle Amount Breakdown",
    SortByDeficit: "Deficit",
    SortByRunOut: "Run Out",
    SocialNetworkInc: "Social Network Inc",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Database Company",
    Database: "Database",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Aircraft Carrier Factory",
    AircraftCarrier: "Aircraft Carrier",
    MapExclusive: "Map Exclusive",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Car factories use batteries instead of petrol and only require 50% of the amount",
    HongKongBonusV2:
        "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
    TaiChi10xCultureDescV2:
        "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
    SettingsFullScreen: "Full Screen",
    SettingsFullScreenDesc: "Run the game in fullscreen mode. Only available for Steam version",
    LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
    LeaderboardByCash: "Current Cash At Hand",
    LeaderboardBySwissPerBuilding: "Current Swiss Money Per Building",
    LeaderboardTotalValuation: "Total Valuation",
    LeaderboardDescV2: "See the where the top players are",
    LastUpdatedAt: "Last Updated At",
    DetroitBonusV3:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
    SaveAndExit: "Save and Exit Game",
    SaveAndExitDesc:
        "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
    AutoSellResourceWarningShortLabel: "💡Auto Sell",
    AutoSellResourceWarningDesc:
        "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
    PlayerTradeLocalPrice: "Local Price: %{price}",
    ChatForceScroll: "Force Scroll",
    ChatForceScrollDesc:
        "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
    ResourceExplorer2: "Resource Explorer 2.0",
    ResourceExplorer2Desc: "Resource explorers produce 2x output but use 2x power",
    ConstructionCancel: "Cancel",
    ConstructionPause: "Pause",
    ConstructionResume: "Resume",
    PolicyBlueprint: "Blueprint",
    PolicyBlueprintDesc:
        "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
    HighlightUnderConstruction: "...that haven't been constructed",
    HighlightUnderLevel10: "...that are under level 10",
    HighlightUnderLevel20: "...that are under level 20",
    HighlightUnderLevel30: "...that are under level 30",
    Logout: "You Are Logged Out",
    LogoutDesc: "You have logged in on another device, this device are logged out",
    ConstructionStatusQueueingV2: "Queueing",
    ConstructionStatusPausedV2: "Paused",
    ConstructionStatusBuildingV2: "Building",
    ConstructionStatusUnpaidV2: "Unpaid",
    ConstructionStatus: "Construction Status",
    ConstructionStart: "Start",
    CostFree: "Free",
    PlaceBlueprint: "Place a building blueprint is free",
    PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
    PlayerTradeNowAllowed: "Player trades are not available within 24 hours after you've restored/imported a save",
    MarketNews: "Market News",
    MarketNewsApplyToYou: "Only you",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 Highlight",
    MarketNewsFilterInput: "All %{res} input ",
    MarketNewsFilterOutput: "All %{res} output ",
    MarketNewsFilterBoth: "All %{res} input and output ",
    MarketNewsIncrease: "increased by %{percent}",
    MarketNewsDecrease: "decreased by %{percent}",
    MarketNewsBuilding: "This building is affected by %{num} news",
    StockholmBonusV2:
        "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
    OsloBonusV2:
        "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
    FreeOilTransportV2: "Electric Oil Transport",
    Tutorial4P1:
        "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
    Tutorial4P2:
        "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
    Tutorial5P2:
        "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
    MusicProducer: "Music Producer",
    PlasticFiber: "Plastic Fiber",
    PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
    NewsEffectx2: "Press Conference",
    NewsEffectx2Desc: "The effect of market news doubles, both positive and negative",
    SellRefundPercentage: "Sell/Downgrade Refund",
    SellRefundPercentageDesc:
        "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
    SellBuildingDescV2:
        "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
    BuilderMoveSpeed: "Builder Move Speed",
    BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
};
