export const ZH_CN = {
    Translator: "译者",
    TranslatorName: "LazySu, snewpeap, Orange233，YinTingChow, HagridThick",
    Language: "语言",
    ThisLanguage: "简体中文",
    OK: "好的",
    SteelMill: "轧钢厂",
    StainlessSteelPlant: "不锈钢厂",
    CircuitFoundry: "电路代工厂",
    IntegratedCircuit: "集成电路",
    OilWell: "油井",
    Wood: "原木",
    LoggingCamp: "伐木场",
    LumberMill: "锯木厂",
    Lumber: "木材",
    Paper: "纸张",
    PaperMill: "造纸厂",
    Book: "书籍",
    BookPublisher: "图书出版社",
    OilRefinery: "炼油厂",
    Sell: "出售",
    Upgrade: "升级",
    Build: "建造",
    Inspect: "检查",
    Buildings: "建筑物",
    Iron: "铁",
    Actions: "行动",
    FuelType: "选择燃料",
    FuelCost: "燃料费用",
    FuelConsumption: "%{fuel}消耗",
    FuelEconomy: "燃烧效率",
    FuelProduction: "%{fuel}产量",
    FuelInStorage: "%{fuel}储备",
    Plastic: "塑料",
    FuelSurplus: "%{fuel}节余",
    Petrol: "汽油",
    Buy: "购买",
    NoLiquidity: "无流动性",
    NoLiquidityTurnOffAutoSell: "市场没有足够的流动性为 %{res}, 自动销售已被关闭",
    Multiplier: "乘数",
    MultiplierDesc: "每提升10级, 您将增加1个乘数",
    SellBuilding: "出售建筑物",
    PowerGrid: "电力系统",
    TradeAmount: "贸易数量",
    SortBy: "排序",
    SortByPrice: "价格",
    SortByAmount: "数量",
    NotEnoughResourcesForTrade: "贸易中心没有足够的资源用于此贸易",
    NotEnoughResources: "没有足够的资源进行此操作",
    Transportation: "运输系统",
    Cash: "现金",
    Aluminum: "铝",
    ResearchPoint: "研究点",
    Unlock: "解锁",
    BuildingUnlocked: "%{building}已解锁",
    Science: "科学点",
    ScienceFromPowerDesc: "发电厂发电时产生少量的科学点",
    Culture: "文化点",
    School: "学校",
    University: "大学",
    Polytechnic: "理工学院",
    Colosseum: "竞技场",
    WindTurbine: "风力发电机",
    Engine: "引擎",
    EngineFactory: "引擎工厂",
    CameraFactory: "相机工厂",
    Camera: "相机",
    Gun: "枪械",
    GunFactory: "枪械工厂",
    Aircraft: "飞机",
    AircraftFactory: "飞机工厂",
    Zeppelin: "齐柏林飞艇",
    ZeppelinFactory: "齐柏林飞艇工厂",
    Tank: "坦克",
    TankFactory: "坦克工厂",
    CoalPowerPlant: "燃煤发电厂",
    PetrolPowerPlant: "燃油发电厂",
    Copper: "铜",
    Gas: "天然气",
    GasPump: "天然气泵",
    GasPowerPlant: "天然气发电厂",
    Missile: "导弹",
    MissileFactory: "导弹工厂",
    Rocket: "火箭",
    RocketFactory: "火箭工厂",
    BuildingPermit: "建筑许可证",
    BuildingPermitDesc: "您总共可以建造 %{amount} 座建筑物，您已经建造了 %{amountBuilt} 座，还能建造 %{amountLeft} 座",
    BuildingLocked: "建筑物不可用，您需要先在研究室解锁它",
    BuildQueue: "建造队列",
    BuildQueueDesc: "当前在建造队列中的建筑数量",
    MaxBuilders: "最大工程队数量",
    MaxBuildersDesc: "您可以同时建造的建筑物数量",
    Silicon: "硅",
    AluminumMine: "铝矿场",
    CopperMine: "铜矿场",
    SiliconMine: "硅矿场",
    IronMine: "铁矿场",
    CoalMine: "煤矿场",
    Headquarter: "总部",
    ResearchLab: "研究实验室",
    TradeCenter: "贸易中心",
    Resources: "资源",
    NotEnoughPower: "💡 电力不足，考虑增加供电",
    NotEnoughFuel: "没有足够的 %{fuel} 进行此操作",
    NotEnoughCash: "没有足够的现金进行此操作",
    NotEnoughSwissMoney: "没有足够的瑞士资金进行此操作",
    BuildingNotEnoughFuel: "💡 %{fuel} 不足",
    AutoSell: "自动出售",
    SellAll: "全部出售",
    Change: "更改",
    StatisticsBureau: "统计局",
    LogisticsDepartment: "后勤部",
    From: "从",
    Top20FuelCost: "消耗燃料前20",
    To: "到",
    TransportTime: "运输时间",
    TopN: "前 %{n}",
    Warehouse: "仓库",
    TradeWarehouse: "货运仓库",
    Coal: "煤",
    Video: "视频",
    ClothingFactory: "服装工厂",
    Clothes: "服装",
    Fashion: "时装",
    FashionFactory: "时装工厂",
    VideoFarm: "视频工作室",
    SantaFactory: "圣诞老人工厂",
    Santa: "圣诞老人",
    Car: "汽车",
    CarFactory: "汽车工厂",
    Ship: "船舶",
    SolarPanel: "太阳能电池板",
    SolarPanelDesc: "💡 太阳能电池板每10秒只能工作5秒-所有的循环都是一致的",
    WindTurbineDesc: "💡 风力发电机每10秒只工作8秒-循环不一致",
    Movie: "影片",
    MovieStudio: "电影工作室",
    Sitcom: "电视剧",
    TVStudio: "电视台",
    PC: "电脑",
    GameStudio: "游戏开发商",
    Game: "游戏",
    ComputerFactory: "电脑工厂",
    Shipyard: "造船厂",
    PowerUsage: "用电功耗",
    PowerSupply: "发电功率",
    PowerSurplus: "电力节余",
    Level: "级别",
    Power: "电力",
    CentralBank: "中央银行",
    ResourceInput: "投入",
    ResourceOutput: "产出",
    ResourceStorage: "库存",
    ResourceChange: "变化",
    ResourceInOutDesc: "💡 点击上面的投入-产出数字，以显示相应的投入和产出建筑物",
    ResourceChart: "资源图",
    MarketUpdateIn: "市场在 %{time} 后更新",
    Income: "收入",
    Semiconductor: "半导体",
    SemiconductorFactory: "半导体工厂",
    Steel: "钢",
    Bitcoin: "比特币",
    BitcoinFarm: "比特币农场",
    Dogecoin: "狗狗币",
    DogecoinFarm: "狗狗币农场",
    Guitar: "吉他",
    GuitarFactory: "吉他工厂",
    Drum: "鼓",
    DrumFactory: "鼓工厂",
    RecordingStudio: "录音室",
    OperaHouse: "歌剧院",
    CoalGasificationPlant: "煤气化加工厂",
    GasProcessingPlant: "天然气加工厂",
    Music: "音乐",
    Glass: "玻璃",
    PhoneFactory: "手机工厂",
    Phone: "手机",
    GlassFactory: "玻璃工厂",
    Oil: "石油",
    Chromium: "铬",
    ChromiumMine: "铬矿场",
    Uranium: "铀",
    EnrichedUranium: "浓缩铀",
    NuclearPowerPlant: "核电站",
    UraniumEnrichmentPlant: "浓缩铀加工厂",
    UraniumMine: "铀矿场",
    Titanium: "钛",
    TitaniumMine: "钛矿场",
    TitaniumAlloyPlant: "钛合金加工厂",
    ChromiumAlloyPlant: "铬合金加工厂",
    Input: "投入",
    PanelPosition: "面板位置",
    PanelPositionDesc: "将控制面板显示在左侧，右侧或自动 (取决于当前的选定的地块)",
    InputCapacity: "投入量",
    InputCapacityPerCycle: "投入量 / 循环",
    Output: "产出",
    OutputCapacity: "产出量",
    OutputCapacityPerCycle: "产出量 / 循环",
    ResourceDeposit: "资源矿床",
    RecommendedBuilding: "💡 这个地块有 %{resource} 资源",
    AdjacentBonus: "相邻加成",
    AdjacentBonusDesc: "每栋相邻的同类型工作建筑物将带来%{bonus}%的额外产量",
    ConsiderIncreaseProduction: "💡 考虑增加 %{resource} 生产",
    AlwaysTransportInput: "库存模式",
    AlwaysTransportInputTradeCenter: "始终出口",
    AlwaysTransportInputTradeCenterDesc: "始终将资源运送到贸易中心，即使该资源无法启用自动销售",
    AlwaysTransportInputDesc: "始终运输投入资源，即使它们高于最低生产要求",
    ProductionCycleLength: "生产周期",
    ProductionCycleLengthDesc:
        "一个生产周期的持续时间，以秒为单位。延长周期将相应增加每个周期的投入/产出，从而降低获取投入资源时的优先级",
    MaxInputDistance: "最大投入距离",
    MaxInputDistanceDesc: "这栋建筑以地块数量计算的投入资源的最大距离",
    AutoSellCapacity: "自动销售数量",
    AutoSellCapacityDesc: "自动销售每秒能够处理每种资源的最大数量",
    CurrentAutoSellCapacityMultiplier: "当前乘数: x%{n}",
    AutoSellConcurrency: "自动销售并发数量",
    AutoSellConcurrencyDesc: "自动销售可以同时处理的最大资源数量",
    MaxAutoSellConcurrencyReached: "您已达到最大自动销售并发，请关闭另一个自动销售以启用此自动销售",
    CannotSellBuilding: "目前不能出售此建筑物",
    WallStreet: "华尔街",
    MarketCap: "市值",
    MarketCapDesc: "市场价值",
    BuildingValuation: "建筑估值",
    BuildingValuationDesc: "您的建筑物的总价值，包括建筑许可证和升级",
    ResourcesValuation: "资源估值",
    ResourcesValuationDesc: "库存资源总价值",
    Battery: "电池",
    BatteryFactory: "电池工厂",
    RatingBuy: "购买",
    RatingSell: "出售",
    SwissShop: "瑞士商店",
    RatingHold: "保持",
    RatingOutperform: "表现优异",
    RatingUnderperform: "表现不佳",
    StockRating: "股票评级",
    JetEngine: "喷气发动机",
    Helicopter: "直升机",
    Lithium: "锂",
    LithiumMine: "锂矿场",
    LiionBatteryFactory: "锂离子电池工厂",
    HelicopterFactory: "直升机工厂",
    Satellite: "卫星",
    ToyFactory: "玩具工厂",
    Toy: "玩具",
    SpaceStation: "空间站",
    SpaceStationFactory: "空间站工厂",
    OperatingSystem: "操作系统",
    OperatingSystemCompany: "操作系统公司",
    LinuxDistribution: "Linux发行版",
    Internet: "互联网",
    WebBrowser: "网络浏览器",
    Console: "游戏主机",
    ConsoleFactory: "游戏主机工厂",
    Train: "火车",
    TrainFactory: "火车工厂",
    ShoeFactory: "鞋工厂",
    Shoes: "鞋",
    ArtilleryFactory: "火炮工厂",
    Artillery: "火炮",
    SubmarineFactory: "潜艇工厂",
    Submarine: "潜艇",
    Spaceship: "宇宙飞船",
    RobotFactory: "机器人工厂",
    Robot: "机器人",
    SpaceshipFactory: "宇宙飞船工厂",
    SatelliteFactory: "卫星工厂",
    JetEngineFactory: "喷气发动机工厂",
    StockRatingDesc: "来自华尔街分析师的股票评级共识，它会影响你的市值，并随市场一起更新",
    InterestRate: "过夜利率",
    InterestRateDesc: "您在离线时通过市值赚取的利息",
    OfflineEarning: "离线收益",
    OfflineEarningDesc: "离线收益取决于您的市值和利率",
    PerMin: "%{amount}/分钟",
    OfflineEarningTime: "离线赚取时间",
    OfflineEarningTimeDesc: "您能够获取离线收益的时长",
    BuyPermit: "购买建筑许可证",
    NotEnoughBuildingPermit: "没有足够的建筑许可证，请购买更多来建造新的建筑物",
    MovingAverage: "滑动平均",
    MovingAverageDesc: "显示资源变化的滑动平均值，而不是实时变化量",
    AllowZoom: "缩放",
    AllowZoomDesc: "打开缩放支持。使用鼠标轮进行缩放。当前缩放为 %{zoom}",
    AllowZoomMobileDesc: "打开缩放支持。使用手指捏拉进行缩放。当前缩放为 %{zoom}",
    Settings: "设置",
    Sound: "声音效果",
    SoundDesc: "打开声音效果，如点击或错误的声音",
    AutoHighlight: "自动高亮",
    AutoHighlightDesc: "当您选择建筑物时，自动突出显示相同类型的建筑物",
    MusicDesc: "打开音乐：Shane Ivers（https://www.silvermansound.com）的《It's Not Over 'Til The Bossa Nova》",
    Credits: "鸣谢",
    Icons: "图标",
    MisplacedBuilding: "⛔ 此 %{building} 没有放在正确的资源格上",
    Left: "左",
    Right: "右",
    Auto: "自动",
    HighlightBuildings: "高亮建筑",
    HighlightTurnedOff: "被关闭的...",
    HighlightStockpileModeOn: "开启库存模式的...",
    HighlightProductionCycleNotDefault: "生产周期 > 1的...",
    HighlightMaxInputDistanceNotDefault: "最大投入距离 < ∞的...",
    HighlightNotMakingProfit: "不盈利的...",
    NBuildingsAreHighlighted: "%{n} 建筑物被突出显示",
    OnlyToWarehouse: "仓库专运",
    OnlyToWarehouseDesc: "只有仓库才能从这座建筑物里运送资源",
    TurnOffProduction: "关闭",
    TurnOffProductionDesc: "关闭建筑物的生产。该建筑将不再投入资源和使用电力",
    ApplyToAll: "应用于所有 %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "无限",
    Transport: "运输",
    TileModifier: "地块修正",
    ShowAllModifiers: "显示所有修正",
    HideAllModifiers: "隐藏所有修正",
    NumberOfBuildings: "拥有的建筑物数量",
    ShowContent: "显示内容",
    HideContent: "隐藏内容",
    BuyExpansionPack: "以 %{price}购买",
    Cities: "城市",
    InputStrategy: "投入策略",
    InputStrategyClose: "更近",
    InputStrategyCloseDesc: "选择最近的，且有足够资源的仓库",
    InputStrategyFar: "更远",
    InputStrategyFarDesc: "选择最远的，且有足够的资源的仓库",
    InputStrategyAmount: "数量",
    InputStrategyAmountDesc: "无论距离如何，都偏好资源量最大的仓库",
    FuelCostSave: "节省燃料成本",
    FuelCostSaveDesc: "与其他建筑物相比，仓库可节省一定比例的燃料以用于运输资源入内，等级越高，节省的费用就越多",
    SoftwareCompany: "软件公司",
    Software: "软件",
    ScreenFactory: "屏幕工厂",
    Screen: "屏幕",
    JoinDiscord: "加入我们的Discord服务器以获取最新更新，技巧和讨论",
    ClaimOfflineEarning: "获取离线收益",
    OfflineTime: "离线时间",
    Minutes: "%{time}分钟",
    MaxUpgrade: "最大升级",
    MaxUpgradeDesc: "您已达到最大升级",
    ClaimAmount: "现金 +%{amount}",
    EarningPerMinute: "收益率",
    EffectiveTime: "有效时间",
    EffectiveTimeDesc: "您的有效离线收入时间不超过 %{time}min.",
    BuildSearchPlaceholder: "输入要搜索的建筑物或资源的名称",
    MineOverlayWarning: "%{building} 不受地块修正的影响",
    WholesaleCenter: "批发中心",
    OrderFrom: "来自%{name}的订单",
    ExpireIn: "到期",
    TurnOnAllProductions: "生产开始",
    TurnOnAllProductionsDesc: "打开所有建筑物的生产，在“节省成本”政策开启时无法使用",
    OperationSuccessful: "此操作已成功完成",
    TurnOn: "打开",
    Reward: "奖励",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/周期",
    PolicyPoint: "政策点",
    PolicyPointPerMinute: "生产速率",
    PolicyPointPerMinuteDesc: "您在游戏中每分钟都会获得政策点",
    YourWilLGaimPolicyPoints: " 您将在%{time}s内获得%{amount}个政策点",
    PolicyPointDesc: "💡 开启越多政策，每个政策的成本就越高",
    NextOrderIn: "下一个订单还需",
    FillOrder: "成交订单",
    RejectOrder: "跳过",
    WholesaleCenterLocked: "您至少需要%{required}种不同资源解锁批发中心。您只有%{current}种资源",
    OrderFilled: "来自 %{from} 的订单已成功成交！",
    PolicyCenter: "政策中心",
    NewOrder: "来自 %{from} 的新订单已到，请在批发中心查看",
    Policies: "政策",
    PolicyNotEnoughTime: "此政策您没有足够的政策点",
    TimeLeft: "剩余 %{time}",
    WholesaleCenterOrderFaster: "世界博览会",
    WholesaleCenterOrderFasterDesc: "批发中心接收订单快2倍，订单大小大2倍",
    PolicyOilWellPowerx2: "增压油井",
    PolicyOilWellPowerx2Desc: "油井产生2倍的石油，并使用2倍的电力",
    HalfTransportSpeed: "慢下来保存",
    HalfTransportSpeedDesc: "运输速度降低25%，燃料成本降低25%",
    RefineryMoreOil: "更多汽油，更多问题",
    RefineryMoreOilDesc: "炼油厂的汽油产量增加50%，塑料的产量减少50%",
    StickyInput: "粘性输入",
    StickyInputDesc: "建筑物将倾向于从以前的来源进行运输，而不是每个周期都寻找最佳的来源（免费政策）",
    RefineryMorePlastic: "更多塑料，更多问题",
    RefineryMorePlasticDesc: "炼油厂的汽油产量减少50％，塑料的产量增加50％",
    FreeOilTransportDesc: "石油运输无需花费燃料，但油井使用的电力是原来的2倍",
    SuperSteelMill: "钢铁雄心",
    SuperSteelMillDesc: "钢铁厂的煤炭消耗量减少50％，铁消耗量增加25％，电力消耗增加25％",
    AlSemiconductor: "铝电路",
    AlSemiconductorDesc: "电路代工厂使用铝代替铜",
    CostSaver: "节约成本",
    CostSaverDesc: "如果建筑物的投入成本大于产出，则停止生产",
    CostSaverBuildingDesc: "节约成本政策已生效，生产将根据其获利能力自动打开/关闭",
    CostSaverBuildingWarning: "节约成本政策处于打开状态，您不能手动更改生产",
    GlassUseCoal: "黑玻璃",
    GlassUseCoalDesc: "玻璃工厂使用的煤炭多50％，硅减少50％",
    AdjacentBonusOnlyOutput: "相邻加成Plus",
    AdjacentBonusOnlyOutputDesc: "相邻的加成不需要更多的投入，但是会消耗更多的电力，并且只有50％的效率",
    IronMine2xOutput: "镀锌铁皮",
    IronMine2xOutputDesc: "铁矿场产出2倍的铁，但运输铁消耗2倍的燃料",
    SolarPanelAlwaysWork: "太阳永不落山",
    SolarPanelAlwaysWorkDesc: "太阳能板在100％的时间工作，但产出的电力少60％",
    SteelScience: "钢铁知识",
    SteelScienceDesc: "钢厂使用2倍的投入并产生额外的科学点",
    WholesaleCenterProducingOnly: "批发合作伙伴",
    WholesaleCenterProducingOnlyDesc:
        "批发中心订单仅包含当前正在生产的资源（您还需要提供一定数量的资源才能解锁批发中心）",
    ShoppingSpree: "疯狂购物",
    ShoppingSpreeDesc: "如果资源的产出量不足，从贸易中心自动购买短缺量（如果该资源已自动出售，则将被忽略）",
    ShoppingSpreeTradeCenterDesc: "💡 疯狂购物政策已启用，贸易中心将自动购买短缺的资源",
    ExtraPolicyPoints: "政治说客",
    ExtraPolicyPointsDesc: "将政策点的生产能力提高50%",
    CrAlloyUseFe: "铬",
    CrAlloyUseFeDesc: "铬合金工厂不使用锂，而是2倍于锂用量的铁",
    DoubleTileModifier: "自然的力量",
    DoubleTileModifierDesc: "所有地块修正的效果x2(包括正数修正和负数修正)",
    TileModifierOutputOnly: "地块修正Plus",
    TileModifierOutputOnlyDesc: "地块修正只影响产出，不影响投入，但仅有原来的50％有效",
    GasPlantPetrol: "天然气液化",
    GasPlantPetrolDesc: "天然气发电厂使用额外的天然气生产汽油",
    BuildingRecycle: "建筑回收",
    BuildingRecycleDesc: "在建造后1分钟内出售建筑物，可获得全额退款",
    CoalPlantFuel: "煤炭液化",
    CoalPlantFuelDesc: "煤炭发电厂使用额外的煤炭生产汽油",
    Welcome: "欢迎",
    SeeTutorialAgain: "恢复教程",
    HelpTranslateTheGame: "帮助翻译游戏🌐",
    SkipTutorial: "跳过教程",
    NextTutorial: "下一步",
    Tutorial1:
        "闲置工业是一款 <em>资源管理</em>建造游戏🏭在这里你可以建立工厂, 生产商品📦 并获得金钱💸.<br><br>让我们通过一些基本的概念介绍帮助你开始-我保证这不会花很长时间",
    Tutorial2:
        "所有建筑物都需要电力⚡, 您有一台<em>风力发电机</em>可以发电。您可以在左上角看到当前的电力情况.<br><br>您可能已经注意到，风力发电机仅在 <em>80%</em> 的时间内工作。 您可以考虑建造其他种类的发电厂，来产生稳定的电力。",
    Tutorial3:
        "您有很多 <em>资源点</em> 在地图上. 要提取资源, 您必须在<em>资源点上</em>建造相应的开采设备⛏️。<br><br>例如, 您有一口 <em>油井🛢️</em>  <em>从石油矿藏中开采石油</em>.<br></br>资源存量是无限的 - 无需担心它们耗尽。除了开采设备，其他建筑物可以在任何空地块上建造",
    Tutorial5:
        "为了赚钱，您需要通过贸易中心出口你的资源。为此，只需打开 <em>该资源的</em>自动销售.<br></br>您也可以从贸易中心购买资源。. 记住 <em>如果您购买某一种资源，您将推高价格</em> 如果您销售某一种资源，您将推低价格.<br><br>市场 <em>交易价格波动很大</em>📈 定期更换。",
    Tutorial6:
        "要建造新建筑物，您需要先在<em>研究实验室🧪</em>中将其解锁. 研究实验室还将科学点转换为研究点。<br><br>您的风力发电机（和其他发电厂）在运行时会产生少量科学点。 你可以建造学校🏫 和其他专用建筑物来促进科学发展.<br><br>现在您已经了解到所有基础知识，开始建立您的产业！这里有一些<em>现金💸</em>和 <em>汽油⛽</em> 满足您启动的需要。",
    WelcomePlay: "开始游戏",
    WelcomePlayMuted: "开始游戏 (🔇静音)",
    Changelog: "变更日志",
    ChangelogGotIt: "知道",
    Chat: "聊天",
    Send: "发送",
    Import: "导入",
    Export: "导出",
    LastBackupAt: "最后备份",
    RestoreFromBackup: "从备份还原",
    RestoreFromBackupFail: "无法从Steam Cloud恢复备份：您确定有备份吗？",
    RestoreFromBackupTitle: "确定吗？",
    RestoreFromBackupDesc: "通常，您不需要从云备份中进行还原，除非丢失了本地保存。云备份比本地保存要早一些",
    ChatMessages: "聊天消息",
    ChangeName: "更改",
    SaveName: "保存",
    NameValidationRule: "您的姓名只能包含字母和数字，且长度为5至15个字符",
    NameValidationRuleProfanity: "您的名字不应该包含违规字符",
    ChatMessageRateLimit: "您只能每10秒发送一次新的聊天消息",
    NameSaved: "您的名称已成功更改",
    NoMessages: "没有新消息",
    Leaderboard: "排行榜",
    Name: "名称",
    Rank: "排名",
    Tips1: "股票评级分为5个等级：买入，跑赢大盘，持有，跑输大盘和卖出",
    Tips2: "除非有足够的生产能力，否则建筑物将停止运输资源，除非您启用库存模式",
    Tips3: "资源运输的燃料成本取决于距离和资源量",
    Tips4: "只有在地图上找到的数量超过投入容量的情况下，建筑物才会运输资源",
    Tips5: "只有为该资源关闭自动销售功能，建筑物才会从贸易中心运输该资源",
    Tips6: "您可以在相应的投入容量部分下查看资源的燃料成本",
    Tips7: "如果您购买资源，则会提高价格。如果您出售资源，则会降低价格",
    Tips8: "您可以在统计局中查看每种资源的数量及其随时间变化的图表",
    Tips9: "建筑物所需的研究点取决于其投入资源的市场价格",
    Tips10: "不同的资源在市场中的定价不同-随时为市场波动做好准备",
    Tips11: "在扩大生产之前，始终检查电力和燃料供应是一个好主意",
    FPS30: "节能",
    OfflineModeDesc: "无法连接到服务器：将不会产生离线收入。请检查您的互联网连接",
    OptOut: "选择退出",
    OptIn: "重置并启用",
    LeaderboardOptOut: "退出排行榜",
    LeaderboardOptOutDesc: "这将不再发送排行榜得分。请注意：如果以后要启用排行榜，则需要重置数据",
    LeaderboardOptIn: "重置并启用排行榜",
    LeaderboardOptInDesc: "您必须先重置您的数据，然后才能重新启用排行榜，确定吗？",
    RewardAdsFailed: "奖励视频未完成",
    RewardAdsNotAvailable: "奖励视频不可用 (当前仅支持iOS/Android)",
    OfflineEarningDoubleSuccess: "您的离线收入已增加了一倍",
    FPS30Desc: "打开节能模式将使游戏以30FPS而非60FPS的帧率运行。这将延长您的电池续航时间",
    HighlightAll: '高亮显示 "%{type}"',
    HighlightInput: "🔍 高亮显示 %{type} 输入",
    HighlightOutput: "🔍 高亮显示 %{type} 输出",
    TotalInput: "总投入量",
    TotalOutput: "总产出量",
    RunOutIn: "在 %{time}内用完",
    FuelRunOutWarning: "💡 您的燃料消耗超过了生产。当燃料用完时，您的运输将停止",
    InAmount: "投入: %{number}",
    OutAmount: "产出: %{number}",
    SwissBank: "瑞士银行",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "如果您从一个新城市开始，您将获得 %{money} 💵",
    RestorePurchases: "恢复购买",
    RestorePurchasesSuccess: "您的购买已恢复",
    RestorePurchasesFailed: "您的购买未恢复",
    ExpansionPacks: "拓展包",
    ExpansionPack1: "拓展包1",
    ExpansionPack1Owned: "拓展包 1",
    RequireExpansionPack1: "拓展包 1",
    RequireExpansionPack1Desc: "这仅适用于拓展包 1",
    RequireAnyExpansionPack: "独家拓展包",
    RequireAnyExpansionPackDesc: "此功能要求您至少拥有一个扩展包",
    HideRewardAd: "隐藏奖励广告",
    HideRewardAdDesc: "所有游戏内广告都是可选的奖励广告。这将从游戏中隐藏所有奖励广告选项。",
    HideDiscordBanner: "隐藏Discord横幅",
    HideDiscordBannerDesc: "隐藏总部的Discord和商店横幅",
    HideChat: "隐藏聊天消息",
    SortedByDeficit: "按赤字排序",
    PurchaseFailed: "购买未完成",
    PurchaseSteamContinue: "请在Steam上完成购买",
    PurchaseSuccess: "购买已完成，感谢您的支持",
    PrestigeCurrency: "瑞士货币 💵",
    RestartDesc: "💡 想要重启？您可以点击上方的在新城市开始并选择您的新城市",
    PrestigeGoBack: "返回",
    PermanentUpgradeDesc: "如果您从新城市开始，此项升级将会保持",
    ProductionMultiplier: "生产乘数",
    ProductionMultiplierDesc: "提高您所有建筑物的生产能力（包括矿山，工厂，发电厂，科学和文化建筑物）",
    FuelCostDiscount: "燃料成本折扣",
    FuelCostDiscountDesc: "在运输资源时为燃料成本提供折扣",
    AutoSellCapacityMultiplier: "自动销售能力乘数",
    AutoSellCapacityMultiplierDesc: "不管当前容量如何，都将应用于您的自动销售容量的乘数",
    BuildingPermitCostDivider: "建筑许可证成本除数",
    BuildingPermitCostDividerDesc: "建筑许可成本除以该除数",
    ExtraAdjacentBonus: "额外相邻加成",
    ExtraAdjacentBonusDesc: "每个相邻的相同类型的工作中建筑物的额外加成量",
    OfflineEarningMultiplier: "离线收益乘数",
    OfflineEarningMultiplierDesc: "适用于离线收益的乘数",
    PrestigeAlertTitle: "确定吗?",
    PrestigeAlertContent: "您的公司将被清算。您将以 %{amount} 瑞士货币兑现并以 %{city}成立新公司",
    PrestigeCurrencyDesc: "这是您在秘密瑞士银行帐户的钱，您可以带上它在一个新的城市重新开始",
    Prestige: "现金到位",
    Cancel: "取消",
    SaveFileCorrupted: "存档文件损坏",
    CheatDetected: "您的旧存档未通过服务器验证，无法读取。您将以新存档开始",
    LoadGameError: "无法加载游戏",
    LoadGameErrorMessage: "错误消息: %{message}",
    LoadGameErrorDesc: "请检查您的互联网连接。如果问题仍然存在，请联系支持人员",
    ExpansionPackIncompatible: "您正在使用扩展包导入保存，但您的游戏没有所需的扩展包",
    SaveFileMigrated: "新时代：Beta测试在此",
    SaveFileMigratedDesc: "感谢您参与游戏的alpha测试。您的旧地图不兼容，但是我们已经迁移了您的数据并为您提供了一些奖励",
    ClaimSwissMoney: "获取 %{amount} 瑞士货币 💵",
    SaveFileMigratedFinePrint:
        "您的市值转换为瑞士货币，您未使用的瑞士货币将结转。您将获得额外50％的瑞士货币作为参与游戏alpha测试的奖金。可结转的瑞士货币上限为200",
    CashIn: "现金",
    CurrentCity: "当前城市",
    CashInDesc:
        "如果您在一个新的城市开始，您将把这笔款项存入您的瑞士银行帐户。这是基于您公司的市值，并且必须达到 %{amount} 才能赚取瑞士货币",
    MoveToNewMap: "重新城市开始",
    CityName: "城市",
    CitySize: "地图大小",
    GridType: "网格类型",
    StartInThisCity: "从 %{city}开始",
    CityBonus: "城市奖励",
    ResourceTilePercentage: "资源格",
    MapSquareGrid: "正方形",
    MapHexGrid: "六边形",
    Stockholm: "斯德哥尔摩",
    Rotterdam: "鹿特丹",
    RotterdamBonus:
        "<li>钢厂的生产能力是原来的2倍</li><li>不锈钢厂的生产能力是原来的2倍</li><li>铁运输免费</li><li>钢运输的燃料成本降低50％</li><li>初始自动销售量是原来的2倍</li><li>没有地块修正</li>",
    Oslo: "奥斯陆",
    StPetersburg: "圣彼得堡",
    Hamburg: "汉堡",
    HamburgBonus:
        "<li>齐柏林飞艇工厂已预先解锁</li><li>半导体工厂的产出量是原来的2倍</li><li>造船厂的生产能力是原来的2倍</li><li>汽车工厂的生产能力是原来的2倍</li><li>锂离子电池工厂已预先解锁</li>",
    Toulouse: "图卢兹",
    Rome: "罗马",
    RomeBonus:
        "<li>竞技场已预先解锁</li><li>竞技场的产出量是原来的2倍</li><li>开局即有5级政策中心</li><li>歌剧院的生产能力是原来的2倍</li><li>录音室也产生文化点</li>",
    Detroit: "底特律",
    Boston: "波士顿",
    BostonBonus:
        "<li>开局即有5级研究实验室</li><li>理工学院已预先解锁</li><li>理工学院的生产能力是原来的2倍</li><li>学校的生产能力是原来的2倍</li><li>大学的产出量是原来的2倍</li>",
    HideNotProducing: "隐藏未生产的资源",
    SortByStorage: "库存",
    SortByProduction: "产量",
    SortByName: "名称",
    PlayerTrade: "玩家交易",
    AddTradeFail: "添加交易失败",
    AddTradeExceedMaximumTrade: "您最多只能有 %{number} 个进行中交易，请先领取或者取消其中之一",
    AddTradeSuccess: "您的交易已成功添加",
    LoadTradeFail: "无法加载玩家交易，请稍后再试",
    ClaimTradeFail: "无法领取此交易，请稍后再试",
    CancelTradeSuccess: "您的交易已成功取消",
    CancelTradeFail: "无法取消此交易，请稍后再试",
    AcceptTradeFail: "无法接受此交易，请稍后再试",
    PlayerTradeBanner: "与其他玩家交易资源",
    PlayerTradeResource: "资源",
    PlayerTradeAmount: "数量",
    PlayerTradePrice: "价格 $",
    PlayerTradeValue: "价值 $",
    PlayerTradeWaiting: "正在等待...",
    UseTradeCenterPrice: "使用贸易中心价格",
    AddTrade: "添加交易",
    ActiveTrades: "进行中交易",
    AcceptTrade: "接受",
    CancelTrade: "取消",
    RefundTrade: "退款",
    RefundTradeSuccess: "该交易已退款: %{resource}已退还给您的贸易中心",
    RefundTradeFail: "未能退款此交易, 请稍后再试",
    ClaimTrade: "领取",
    RefreshTrade: "刷新",
    PasteYourSave: "请粘贴您的存档数据",
    FailedToImportSave: "无法导入存档",
    FailedToImportSaveDesc: "您的存档文件不兼容或损坏: %{error}",
    SaveCopiedToClipboard: "您的存档数据已被复制到您的剪贴板",
    CancelActiveTradeFirst: "您有进行中的玩家交易，请先取消/领取",
    FailedToCheckActiveTrade: "未能检查进行中的玩家交易, 请稍后再试",
    PlayerTradeQuotaExceed: "该交易已超过您的配额",
    PlayerTradeValidRange: "范围: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "买得起",
    PlayerTradeQuota: "剩余配额: %{value}",
    PlayerTradeUnavailable: "在与玩家进行交易之前，你需要在生产和存储中至少有一个资源",
    PlayerTradeToClaim: "您有 %{num} 宗玩家交易待领取",
    PowerBank: "电池组",
    PowerBankBuildDesc: "存储过剩的电力，在电力短缺时提供电能",
    WarehouseBuildDesc: "以更低的燃料消耗运输及存储任何资源",
    PowerBankChargeSpeed: "充电速度",
    PowerBankPowerLeft: "电量剩余",
    PowerBankMoreCapacity: "电池保护",
    PowerBankMoreCapacityDesc: "电池组的充电速度只有原来50%，但是多50%容量",
    PowerBankNotWorking: "⛔ 电池组只在紧邻发电厂时工作",
    ExcludeBuildingsShutdown: "被关闭的建筑除外",
    ColorTheme: "游戏颜色主题",
    ColorThemeDesc: "颜色主题应用于游戏图标，高亮，网格和背景。需要重启生效",
    SiliconMine2xOutput: "硅谷",
    SiliconMine2xOutputDesc: "硅矿场生产2倍的硅，但用电量增加50%，运输硅的燃料消耗增加50%",
    CoalMine2xOutput: "工业革命",
    CoalMine2xOutputDesc: "煤矿场生产2倍的煤，但用电量增加50%，运输煤的燃料消耗增加50%",
    AlMine2xOutput: "铝电解",
    AlMine2xOutputDesc: "铝矿场产生2倍的铝，但消耗2倍的电力",
    LoggingCamp2xOutput: "毁林",
    LoggingCamp2xOutputDesc: "伐木场产生2倍的原木，但运输原木消耗2倍的燃料",
    HideResourceMovement: "隐藏资源移动",
    HideResourceMovementDesc: "这将默认隐藏资源移动（那些小点），仅在选择建筑时显示相关资源移动",
    PowerBankLeft: "电池组",
    ColorThemeEditor: "颜色主题编辑器",
    ColorThemeEditorDesc: "你可以替换当前颜色主题中的颜色。你已经替换了%{num}个颜色",
    ColorThemeEditorSave: "保存",
    ColorThemeEditorReset: "重置",
    ColorThemeEditorResetAll: "全部重置",
    NewMessageMentions: "新消息提及了你: %{message}",
    HideChatMentions: "隐藏聊天提及通知",
    HideChatMentionsDesc: "隐藏聊天消息提及我时的音效和弹出通知",
    PendingConstructionCannotReload: "你有建造中的建筑，现在不能重新载入游戏",
    AcceptTradeFailRateLimit: "每%{time}秒只能接受一宗交易",
    DowngradeBuilding: "降级",
    CancelTradeConfirmDialogTitle: "要取消这宗交易吗？",
    CancelTradeConfirmDialogYes: "是",
    CancelTradeConfirmDialogNo: "否",
    WarehouseInputRoutes: "运入路线",
    WarehouseAddInput: "添加路线",
    WarehouseTapToSelect: "在地图上点选...",
    WarehouseFindOnMap: "🔍 在地图上定位",
    WarehouseRemoveRoute: "删除",
    WarehouseAddRouteFail: "添加路线失败: 选择的地块不是有效运入源",
    LevelN: "级别 %{level}",
    Surplus: "节余",
    Production: "产出",
    Consumption: "消耗",
    WarehouseInputCapacityDescV2: "运入资源总数量，会均等分摊到每条路线上",
    WarehouseInputCapacityPerRoute: "每条路线: ",
    PlayerCountryFlag: "玩家旗帜",
    PlayerCountryChooseFlag: "按照国家/地区代码字母排序",
    WindTurbineAlwaysWork: "起风了",
    WindTurbineAlwaysWorkDesc: "风力发电机全时段工作，但电力产出少30%",
    BookPublisherScience: "科技文献",
    BookPublisherScienceDesc: "图书出版社产出科学点，而非文化点",
    WarehouseOutwardFuelSave: "免费送货",
    WarehouseOutwardFuelSaveDesc: "仓库向外运输资源时也将享有燃料节省效果",
    ImportSaveVersionTooNew:
        "您正在导入游戏版本为 %{saveVersion} 的存档，但您目前的游戏版本为 %{gameVersion}。请您先更新游戏",
    BatteryFuelEconomy: "可充电电池",
    BatteryFuelEconomyDesc: "电池的燃料效率提升100% (也即只有50%的燃料消耗)",
    ShowTheoreticalInputOutputCapacity: "显示理论输入/输出量",
    SpecialTransportCost: "有特殊运输成本的资源",
    FreeTransportCost: "免费运输的资源",
    Osaka: "大阪",
    OsakaBonus:
        "<li>资源倾向于成簇地生成</li><li>仓库额外提供50%的燃料节省效果</li><li>独特建筑：漫画出版社</li><li>独特建筑：动漫工作室</li><li>半导体工厂的产出量是原来的2倍</li><li>锂离子电池工厂的生产能力是原来的2倍</li><li>电池工厂已预先解锁</li><li>电池工厂的生产能力是原来的2倍</li><li>电池的燃料效率提升100%</li><li>电池工厂不需要煤</li><li>开局即有100K电池</li>",
    HideChatDescV2: "隐藏底部工具栏中的聊天消息。显示聊天消息表明您同意我们的 ",
    HideChatDescV2ToS: "服务条款",
    IntegratedCircuitFab: "集成电路工厂",
    MangaPublisher: "漫画出版社",
    Manga: "漫画",
    AnimeStudio: "动漫工作室",
    Anime: "动漫",
    PlayerTradeAction: "操作",
    PlayerTradeBuy: "收购",
    PlayerTradeSell: "出售",
    PlayerTradeBid: "收购",
    PlayerTradeAsk: "出售",
    CancelTradeConfirmDialogDescV2: "取消这宗交易将会返还%{percent}的资源/现金。资源会退回到贸易中心仓库",
    ClaimTradeSuccessV2: "你发起的交易已成功完成: %{cashOrResource}",
    AcceptTradeSuccessV2: "你已经达成了这笔交易: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "优于市场价",
    ResourceExplorer: "资源勘探者",
    ResourceExplorerDesc: "你可以从空白地块中获取资源",
    ResourceExplorerDescLong: "💡 资源勘探者建筑没有相邻加成。其电力消耗视资源而不同",
    ResourceExplorerSelectResource: "勘探",
    ProductionSettings: "生产设置",
    PlayerTradeQuotaDesc: "💡 你的玩家交易配额是你的市值的%{percent}, 会在市场更新后重置",
    PlayerTradePartialFillTitle: "选择成交百分比",
    PlayerTradeAmountNotValidV2: "交易数量至少为1",
    PlayerTradeOptOut: "你已经选择退出排行榜, 不能和其他玩家交易",
    FirstTimeReadGuide: "💡 不知道怎么玩，需要帮助？点此阅读新手指南！",
    ReadSteamGuideV2: "游戏指南",
    ReadSteamGuideV2Desc: "你可以在Steam上浏览由游戏社区编写的指南-你也可以编写自己的指南",
    ChatMessageTooLong: "聊天消息长度超过了字符数上限",
    ChatPlaceholderV2: "在此键入消息: 最多%{length}个字符",
    ShowProfitBreakdown: "显示利润细目",
    HideProfitBreakdown: "隐藏利润细目",
    ProfitBreakdownOutput: "%{res} 产出",
    ProfitBreakdownInput: "%{res} 消耗",
    ProfitBreakdownFuel: "燃料成本",
    BuildingProfit: "利润",
    RestoreBackup: "恢复",
    SteamLogin: "用Steam账号登录",
    SteamLoginDialogDesc:
        "你的本地游戏存档中启用了扩展包, 因此你需要登录Steam账号来继续游戏。你也可以选择*删除本地存档*并重新开始",
    SteamLoginDesc: "如果你的Steam账户拥有扩展包, 登录后你就能在Web端游玩扩展包内容",
    SteamLoginYes: "登录",
    SteamLoginNo: "删除并重开",
    KungFuDojo: "功夫馆",
    KungFu: "功夫",
    TaiChi: "太极",
    TaiChiDojo: "太极馆",
    HongKong: "香港",
    FreeTransportToTradeCenter: "国际出口贸易",
    FreeTransportToTradeCenterDesc: "运输到贸易中心不消耗燃料，但从贸易中心运出资源多消耗50%燃料",
    TaiChi10xCulture: "东方之珠",
    PlayerTradeYouHave: "库存: %{amount}",
    PlayerTradeFillValue: "价值",
    FiberFactory: "光纤工厂",
    Fiber: "光纤",
    Achievements: "成就",
    AchievementsDesc: "您已获得%{total}项成就中的%{number}项",
    AchievementsReward: "奖励：瑞士货币 +%{swiss}",
    AchievementsRewardToast: "您已经领取了奖励：瑞士货币 +%{swiss}",
    AchievementsClaim: "领取",
    AchievementsToast: "您已获得成就 %{name}, 请在总部领取奖励",
    AchievementStockholm100: "新生维京人",
    AchievementStockholm100Desc: "在斯德哥尔摩一次性赚取100瑞士货币",
    AchievementStockholm500: "毕业维京人",
    AchievementStockholm500Desc: "在斯德哥尔摩一次性赚取500瑞士货币",
    AchievementStockholm1000: "有经验的维京人",
    AchievementStockholm1000Desc: "在斯德哥尔摩一次性赚取1000瑞士货币",
    AchievementOslo100: "挪威石油爱好者",
    AchievementOslo100Desc: "在奥斯陆一次性赚取100瑞士货币",
    AchievementOslo500: "挪威石油专家",
    AchievementOslo500Desc: "在奥斯陆一次性赚取500瑞士货币",
    AchievementOslo1000: "挪威石油大亨",
    AchievementOslo1000Desc: "在奥斯陆一次性赚取1000瑞士货币",
    AchievementRotterdam100: "风车物主",
    AchievementRotterdam100Desc: "在鹿特丹一次性赚取100瑞士货币",
    AchievementRotterdam500: "风力发电机物主",
    AchievementRotterdam500Desc: "在鹿特丹一次性赚取500瑞士货币",
    AchievementRotterdam1000: "风力涡轮机物主",
    AchievementRotterdam1000Desc: "在鹿特丹一次性赚取1000瑞士货币",
    AchievementDetroit100: "本地汽车经销商",
    AchievementDetroit100Desc: "在底特律一次性赚取100瑞士货币",
    AchievementDetroit500: "区域汽车经销商",
    AchievementDetroit500Desc: "在底特律一次性赚取500瑞士货币",
    AchievementDetroit1000: "全国汽车垄断",
    AchievementDetroit1000Desc: "在底特律一次性赚取1000瑞士货币",
    AchievementBoston100: "赚钱学士",
    AchievementBoston100Desc: "在波士顿一次性赚取100瑞士货币",
    AchievementBoston500: "赚钱高手",
    AchievementBoston500Desc: "在波士顿一次性赚取500瑞士货币",
    AchievementBoston1000: "印钞学博士",
    AchievementBoston1000Desc: "在波士顿一次性赚取1000瑞士货币",
    AchievementRome100: "戴克里先",
    AchievementRome100Desc: "在罗马一次性赚取100瑞士货币",
    AchievementRome500: "康斯坦丁大帝",
    AchievementRome500Desc: "在罗马一次性赚取500瑞士货币",
    AchievementRome1000: "凯撒大帝",
    AchievementRome1000Desc: "在罗马一次性赚取1000瑞士货币",
    AchievementHamburg100: "德意志兰",
    AchievementHamburg100Desc: "在汉堡一次性赚取100瑞士货币",
    AchievementHamburg500: "沃特兰",
    AchievementHamburg500Desc: "在汉堡一次性赚取500瑞士货币",
    AchievementHamburg1000: "齐柏林伯爵号",
    AchievementHamburg1000Desc: "在汉堡一次性赚取1000瑞士货币",
    AchievementToulouse100: "喷气式飞机A310",
    AchievementToulouse100Desc: "在图卢兹一次性赚取100瑞士货币",
    AchievementToulouse500: "喷气式飞机A330",
    AchievementToulouse500Desc: "在图卢兹一次性赚取500瑞士货币",
    AchievementToulouse1000: "喷气式飞机A380",
    AchievementToulouse1000Desc: "在图卢兹一次性赚取1000瑞士货币",
    AchievementHongKong100: "业余交易者",
    AchievementHongKong100Desc: "在香港一次性赚取100瑞士货币",
    AchievementHongKong500: "专业经纪人",
    AchievementHongKong500Desc: "在香港一次性赚取500瑞士货币",
    AchievementHongKong1000: "对冲基金经理",
    AchievementHongKong1000Desc: "在香港一次性赚取1000瑞士货币",
    AchievementStPetersburg100: "伟大的公爵",
    AchievementStPetersburg100Desc: "在圣彼得堡一次性赚取100瑞士货币",
    AchievementStPetersburg500: "沙俄王储",
    AchievementStPetersburg500Desc: "在圣彼得堡一次性赚取500瑞士货币",
    AchievementStPetersburg1000: "全俄罗斯的沙皇",
    AchievementStPetersburg1000Desc: "在圣彼得堡一次性赚取1000瑞士货币",
    AchievementOsaka100: "日本男爵",
    AchievementOsaka100Desc: "在大阪一次性赚取100瑞士货币",
    AchievementOsaka500: "日本伯爵",
    AchievementOsaka500Desc: "在大阪一次性赚取500瑞士货币",
    AchievementOsaka1000: "日本公爵",
    AchievementOsaka1000Desc: "在大阪一次性赚取1000瑞士货币",
    SteamAutoCloudBackup: "Steam Cloud 自动备份",
    SteamAutoCloudBackupFailed: "Steam Cloud自动备份失败: %{error}",
    SteamManualBackup: "强制Steam Cloud备份",
    UILoading: "加载...",
    UserAuthenticated: "您已通过身份验证",
    BuildingResourceBreakdown: "闲置数量明细",
    SortByDeficit: "亏损",
    SortByRunOut: "耗尽",
    SocialNetworkInc: "社交网络公司",
    SocialNetwork: "社交网络",
    DatabaseCompany: "数据库公司",
    Database: "数据库",
    SatelinkInc: "卫星联网公司",
    GameStationInc: "游戏站公司",
    AirShuttleInc: "航天飞机公司",
    AircraftCarrierFactory: "航空母舰工厂",
    AircraftCarrier: "航空母舰",
    MapExclusive: "地图独占",
    ElectricCar: "尼古拉·特斯拉",
    ElectricCarDesc: "汽车工厂用电池代替汽油，且只需要其50%的数量",
    HongKongBonusV2:
        "<li>独特的市场定价算法-价格符合正态分布(即钟形曲线)</li><li>市场更新和交易配额重置频率是原来的2倍(即每小时)</li><li>可以用已经交易的资源解锁研究</li><li>独特建筑：功夫馆</li><li>独特建筑：太极馆</li><li>允许同时进行的玩家交易数量增加50%</li><li>开局即多1个自动销售并发数</li><li>独特政策：国际出口贸易</li><li>独特政策：东方之珠</li><li>解锁批发中心只需4种资源</li><li>开局即有100M现金</li>",
    TaiChi10xCultureDescV2: "功夫和太极运输免费。电影工作室的生产能力是原来的2倍，但耗电量增加50%",
    SettingsFullScreen: "全屏",
    SettingsFullScreenDesc: "在全屏模式下运行游戏。只对Steam版本有效",
    LeaderboardByAllPrestigeCurrency: "有史以来赚取的瑞士货币",
    LeaderboardByCash: "当前持有的现金",
    LeaderboardBySwissPerBuilding: "当前每栋建筑的瑞士货币",
    LeaderboardTotalValuation: "总市值",
    LeaderboardDescV2: "看看那些顶尖玩家在哪里",
    LastUpdatedAt: "最近更新于",
    DetroitBonusV3:
        "<li>发动机工厂已预先解锁</li><li>发动机工厂的产出量是原来的2倍</li><li>汽车工厂的生产能力是原来的2倍</li><li>汽车工厂使用天然气替代汽油</li><li>汽车运输免费</li><li>尼古拉.特斯拉政策免政策点</li><li>火车工厂的生产能力是原来的2倍</li>",
    SaveAndExit: "保存并退出游戏",
    SaveAndExitDesc: "保存并退出游戏。此功能只在steam版本游戏内可用，且与直接点击窗口栏的关闭按钮作用相同。",
    AutoSellResourceWarningShortLabel: "💡自动销售",
    AutoSellResourceWarningDesc: "你正在自动销售该资源, 保存在贸易中心的该资源不能用于此处。",
    PlayerTradeLocalPrice: "本地价格: %{price}",
    ChatForceScroll: "强制滚动",
    ChatForceScrollDesc: "如果开启了强制滚动，聊天窗口每收到一条新消息都会滚动。否则其只在处于最近消息时才会滚动。",
    ResourceExplorer2: "资源勘探者 2.0",
    ResourceExplorer2Desc: "资源勘探者有2倍产出，但使用2倍电力",
    ConstructionCancel: "取消建造",
    ConstructionPause: "暂停",
    ConstructionResume: "恢复",
    PolicyBlueprint: "蓝图模式",
    PolicyBlueprintDesc: "建筑的建造不会自动开始 - 必须手动开始 (免费政策)",
    HighlightUnderConstruction: "未建造完成的...",
    HighlightUnderLevel10: "低于10级的...",
    HighlightUnderLevel20: "低于20级的...",
    HighlightUnderLevel30: "低于30级的...",
    Logout: "你已成功退出账号",
    ConstructionStatusQueueingV2: "队列中",
    ConstructionStatusPausedV2: "暂停中",
    ConstructionStatusBuildingV2: "建造中",
    ConstructionStatusUnpaidV2: "未付款",
    ConstructionStatus: "建造状态",
    ConstructionStart: "开始建造",
    CostFree: "免费",
    PlaceBlueprint: "放置建筑蓝图免费",
    PlayerTradePriceNotValidV2: "交易定价需在%{min}和%{max}之间",
    MarketNews: "市场消息",
    MarketNewsApplyToYou: "只适用于你",
    MarketNewsApplyToGlobal: "全球",
    MarketNewsHighlightAffected: "🔍 高亮",
    MarketNewsFilterInput: "所有 %{res}消耗 ",
    MarketNewsFilterOutput: "所有 %{res}产出 ",
    MarketNewsFilterBoth: "所有 %{res}消耗和产出 ",
    MarketNewsIncrease: "增加了%{percent}",
    MarketNewsDecrease: "减少了%{percent}",
    MarketNewsBuilding: "该建筑受%{num}则消息效果影响",
    StockholmBonusV2:
        "<li>独特建筑：音乐制作商</li><li>伐木场的产出量是原来的2倍</li><li>造纸厂预先解锁</li><li>电路代工厂的产出量是原来的2倍</li><li>科技文献政策免政策点</li>",
    OsloBonusV2:
        "<li>炼油厂预先解锁</li><li>炼油厂的生产能力是原来的2倍</li><li>电动车运石油政策免政策点</li><li>天然气加工厂的生产能力是原来的2倍</li><li>开局即有1台免费4级风力发电机</li><li>开局即有1座免费4级油井</li><li>开局即有1座免费2级炼油厂</li><li>开局即有1座免费2级天然气泵</li>",
    FreeOilTransportV2: "电动车运石油",
    Tutorial4P1:
        "运输资源会消耗燃料。燃料类型有好几种，而你正在使用<em>汽油⛽</em>作为燃料。你有一座<em>炼油厂</em>能够从油井运入石油并产出汽油。<br><br>飞动的<em>点</em>显示了资源的实时移动。你应当优化建筑位置使资源移动距离最小化。<br><br><em>升级</em>建筑会增加它们的产出，但也会提高电力和资源消耗需求。",
    Tutorial4P2:
        "你可以在<em>后勤部🚦</em>更改燃料类型 - 在该地图中，你也可以用<em>天然气</em>作为燃料。<br><br>后勤部还展示了消耗最多燃料的那些运输路线 - 你需要留意这点<br><br>别忘了<em>确保燃料产出大于消耗</em>，否则燃料耗尽将导致生产暂停<br><br>如果这种情况发生，不要惊慌，你可以从贸易中心或其他玩家手里买些应急燃料。",
    Tutorial5P2:
        "<em>统计局📊</em>为你的生产提供了很好的概览，你可以在此查看你的资源消耗和产出的具体细目。<br><br>那里还有不少有用的图表📈 - 在你平衡生产时可能需要参考这些图表<br></br>你的<em>现金💰，电力节余⚡和燃料节余⛽</em>数目也展示在左上角 - 如果它们中的任意一项飚红，你就需要看看发生什么事情了。",
    MusicProducer: "音乐制作商",
    PlasticFiber: "塑料光纤",
    PlasticFiberDesc: "光纤工厂多用50%塑料，少用50%玻璃",
    NewsEffectx2: "新闻发布会",
    NewsEffectx2Desc: "所有市场消息的正面和负面效果翻倍",
    SellRefundPercentage: "出售/降级退款",
    SellRefundPercentageDesc: "每当你出售或降级建筑，该数值是退还的现金和资源的比例",
    SellBuildingDescV2: "出售建筑将返还你%{percent}的投资且%{percent}的资源将会运送到贸易中心",
    BuilderMoveSpeed: "工程队移速",
    BuilderMoveSpeedDesc: "工程队前往施工建筑的速度",
    EBookInc: "电子书公司",
    ResourceBooster: "资源加速器",
    BuildWarningTitle: "建筑可能无法正常工作",
    BuildWarningTitleDesc: "%{reason}。你确定要在此地块建造？",
    BuildWarningBuildAnyway: "我就要建造",
    ResourceBoosterNotWorking: "⛔ 资源加速器只在紧邻矿藏时有效",
    ResourceBoosterPercentage: "💡 该建筑获从相邻资源加速器获得%{percent}产出提升",
    ResourceBoosterBuildings: "建筑正在加速",
    BuildingResourceConversion: "%{resource}转换",
    AllTimeSwissMoneyEarned: "总共赚取的瑞士货币%{number}",
    BuildingUpgradeCostDivider: "建筑升级成本除数",
    AchievementSoftwareGiant: "软件巨头",
    AchievementSoftwareGiantDesc:
        "在一张地图上建造了10级软件公司，10级操作系统公司，10级数据库公司和10级网络浏览器各一座",
    AchievementSpaceRace: "太空竞赛",
    AchievementSpaceRaceDesc: "在一张地图上建造了10级火箭工厂，10级卫星工厂，10级宇宙飞船工厂和10级空间站工厂各一座",
    AchievementToTheMoon: "直指月球",
    AchievementToTheMoonDesc: "建造一座40级比特币农场和一座40级狗狗币农场。持有1B比特币和1B狗狗币",
    ItsAllGreen: "全是绿色",
    ItsAllGreenDesc: "拥有50条生产线且没有任何生产赤字",
    DeepInRed: "深陷赤字",
    DeepInRedDesc: "拥有50条有生产赤字的生产线",
    UseScientificNotation: "使用科学记数法",
    UseScientificNotationDesc: "使用科学计数法(e表示法)来表示大于999.9T的数字",
    LogoutDescV2: "你已在其他设备上登录，该设备将下线。你可以重新登录但这将导致其他设备下线",
    LogBackIn: "重新登录",
    PlayerTradeNowAllowedV2: "在恢复/导入存档的%{hour}小时内不可进行玩家交易",
    ServerDisconnected: "你已断开与服务器的连接，请检查你的互联网连接或重启游戏",
    BuildingUpgradeCostDividerDescV2: "建筑升级成本将除以该除数",
    ResourceBoosterBannerDesc:
        "💡 你当前有%{number}座资源加速器-该数值也是每一座资源加速器的电力和科学点消耗的放大倍数",
    ResourceBoosterDesc: "增加相邻矿场的产出量",
    BlockUserChatTitle: "屏蔽%{user}",
    BlockUserChatAction: "屏蔽",
    BlockUserChatDesc: "屏蔽将在本次游戏运行期间生效，且除非重启游戏屏蔽无法撤销",
    ChangeNameCooldown: "你只能每隔%{hour}小时改名一次",
    AtomicBombFactory: "原子弹工厂",
    AtomicBomb: "原子弹",
    DynamiteFactory: "炸药工厂",
    Dynamite: "炸药",
    NuclearMissileFactory: "核导弹工厂",
    NuclearMissile: "核导弹",
    LiquidPropellantFactory: "液体推进剂工厂",
    GasPropellantFactory: "气体推进剂工厂",
    Propellant: "推进剂",
    ProjectV2: "V-2计划",
    ICBMFactory: "洲际弹道导弹工厂",
    ICBM: "洲际弹道导弹",
    RadarFactory: "雷达工厂",
    Radar: "雷达",
    SpaceForceCommand: "太空部队司令部",
    SpaceForce: "太空部队",
    SteamAutoCloudBackupDescV2:
        "你的最新进度已经保存到Steam Cloud并在设备间同步。同时游戏每10分钟都会自动备份到Steam Cloud。你可以随时强制备份",
    SpaceColony: "太空殖民地",
    SpaceColonyInc: "太空殖民地",
    ProjectVostok: "东方计划",
    AdjacentBonusSquare: "相邻加成方格版",
    AdjacentBonusSquareDesc: "相邻加成的效果增加50%，但地块修正的范围变为-15%到+15%",
    ResourceBoosterSquare: "资源加速器方格版",
    ResourceBoosterSquareDesc: "资源加速器多提供25%加速效果但科学点和电力消耗也增加25%",
    SteelMillx2: "炼钢炉现代化改造",
    SteelMillx2Desc: "轧钢厂和不锈钢厂的生产能力翻倍，用电量也翻倍",
    IronSteelZone: "钢铁专区",
    IronSteelZoneDesc: "资源加速器每加速一座工作中的铁矿厂，就为相邻轧钢厂和不锈钢厂提供%{percent}产出量加成",
    FuelDynamite: "燃料炸药",
    FuelDynamiteDesc: "炸药工厂消耗当前使用的燃料而非石油",
    StPetersburgBonusV2:
        "<li>铀矿场的产出量是原来的2倍</li><li>浓缩铀加工厂的生产能力是原来的2倍</li><li>铀运输的燃料成本降低50％</li><li>枪械运输免费</li><li>Vostok计划的生产能力是原来的2倍</li>",
    ToulouseBonusV2:
        "<li>钛矿场的产出量是原来的2倍</li><li>浓缩铀加工厂的产出量是原来的2倍</li><li>喷气发动机工厂的生产能力是原来的2倍</li><li>飞机工厂的产出量是原来的2倍</li><li>火箭工厂的生产能力是原来的2倍</li>",
    BuildingPermitsNeededDesc: "This building is not working because you don't have enough building permits",
    BuildingPermitsNeeded: "Building Permits Needed",
    BuyMissingPermits: "Buy Missing Permits",
    GPUIsBusy: "Your GPU is Busy",
    GPUIsBusyDesc:
        "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
    SaveAndReloadGame: "Save And Reload Game",
};
