export const ZH_HK = {
    Translator: "翻譯人員",
    TranslatorName: "Bencheung0422",
    Language: "語言",
    ThisLanguage: "粵語中文",
    OK: "確定",
    SteelMill: "煉鋼廠",
    StainlessSteelPlant: "不鏽鋼廠",
    CircuitFoundry: "電路工廠",
    IntegratedCircuit: "集成電路",
    OilWell: "油井",
    Wood: "原木",
    LoggingCamp: "伐木場",
    LumberMill: "鋸木廠",
    Lumber: "木材",
    Paper: "紙張",
    PaperMill: "造紙廠",
    Book: "書",
    BookPublisher: "圖書出版商",
    OilRefinery: "煉油廠",
    Sell: "賣出",
    Upgrade: "升級",
    Build: "建造",
    Inspect: "檢查",
    Buildings: "建築物",
    Iron: "鐵",
    Actions: "行動",
    FuelType: "燃料種類",
    FuelCost: "燃料消耗",
    FuelConsumption: "%{fuel}消耗",
    FuelEconomy: "燃料效率",
    FuelProduction: "%{fuel}產量",
    FuelInStorage: "%{fuel}儲備",
    Plastic: "塑膠",
    FuelSurplus: "%{fuel}盈餘",
    Petrol: "汽油",
    Buy: "買入",
    NoLiquidity: "無流通性",
    NoLiquidityTurnOffAutoSell: "市場流通性為 %{res}，唔夠流通性，自動銷售已經閂咗。",
    Multiplier: "倍率",
    MultiplierDesc: "每升10級, 就會+1倍嘅產能",
    SellBuilding: "出售建築物",
    PowerGrid: "電網",
    TradeAmount: "交易量",
    SortBy: "排序以",
    SortByPrice: "價格",
    SortByAmount: "數量",
    NotEnoughResourcesForTrade: "交易所冇足夠嘅資源用喺呢個交易",
    NotEnoughResources: "唔夠資源嚟做呢個操作",
    Transportation: "交通系統",
    Cash: "錢",
    Aluminum: "鋁",
    ResearchPoint: "研究點",
    Unlock: "解鎖",
    BuildingUnlocked: "已解鎖 %{building}",
    Science: "科學",
    ScienceFromPowerDesc: "發電廠喺發電嗰陣會產生少量嘅科學點",
    Culture: "文化",
    School: "學校",
    University: "大學",
    Polytechnic: "理工學院",
    Colosseum: "羅馬競技場",
    WindTurbine: "風力發電機",
    Engine: "引擎",
    EngineFactory: "引擎工廠",
    CameraFactory: "相機工廠",
    Camera: "相機",
    Gun: "槍",
    GunFactory: "槍械工廠",
    Aircraft: "飛機",
    AircraftFactory: "飛機工廠",
    Zeppelin: "齊柏林飛船",
    ZeppelinFactory: "齊柏林飛船工廠",
    Tank: "坦克",
    TankFactory: "坦克工廠",
    CoalPowerPlant: "燃煤發電廠",
    PetrolPowerPlant: "燃油發電廠",
    Copper: "銅",
    Gas: "天然氣",
    GasPump: "天然氣泵",
    GasPowerPlant: "燃氣發電廠",
    Missile: "導彈",
    MissileFactory: "導彈工廠",
    Rocket: "火箭",
    RocketFactory: "火箭工廠",
    BuildingPermit: "建築許可證",
    BuildingPermitDesc:
        "您總共有 %{amount}份許可證可以用喺建築物，您已經起咗 %{amountBuilt}座，仲可以起 %{amountLeft}座",
    BuildingLocked: "該建築仲未用得，您要喺研究實驗室度解鎖佢先",
    BuildQueue: "建造隊列",
    BuildQueueDesc: "目前喺隊列入面嘅建築數量",
    MaxBuilders: "最大工程隊數量",
    MaxBuildersDesc: "您可以同時起嘅建築物數量",
    Silicon: "矽",
    AluminumMine: "鋁礦場",
    CopperMine: "銅礦場",
    SiliconMine: "矽礦場",
    IronMine: "鐵礦場",
    CoalMine: "煤礦場",
    Headquarter: "總部",
    ResearchLab: "研究實驗室",
    TradeCenter: "交易所",
    Resources: "資源",
    NotEnoughPower: "💡 唔夠電，考慮增加電力供應",
    NotEnoughFuel: "唔夠%{fuel} 嚟做呢個操作",
    NotEnoughCash: "唔夠錢嚟做呢個操作",
    NotEnoughSwissMoney: "唔夠瑞士錢嚟做呢個操作",
    BuildingNotEnoughFuel: "💡 唔夠 %{fuel}",
    AutoSell: "自動賣出",
    SellAll: "全部賣出",
    Change: "更改",
    StatisticsBureau: "統計處",
    LogisticsDepartment: "物流部",
    From: "由",
    Top20FuelCost: "燃料消耗前廿幾",
    To: "去到",
    TransportTime: "運輸時間",
    TopN: "前 %{n}",
    Warehouse: "倉庫",
    TradeWarehouse: "貿易倉庫",
    Coal: "煤",
    Video: "影片",
    ClothingFactory: "製衣廠",
    Clothes: "衣服",
    Fashion: "時裝",
    FashionFactory: "時裝工廠",
    VideoFarm: "影片製作室",
    SantaFactory: "聖誕老人工廠",
    Santa: "聖誕老人",
    Car: "車",
    CarFactory: "車廠",
    Ship: "船",
    SolarPanel: "太陽能板",
    SolarPanelDesc: "💡 太陽能板每10秒淨係運作5秒-全部運作周期一致",
    WindTurbineDesc: "💡 風力發電機每10秒淨係運作8秒-運作周期不一致",
    Movie: "電影",
    MovieStudio: "電影工場",
    Sitcom: "電視劇",
    TVStudio: "電視節目製作室",
    PC: "電腦",
    GameStudio: "遊戲工作室",
    Game: "遊戲",
    ComputerFactory: "電腦組裝廠",
    Shipyard: "船廠",
    PowerUsage: "用電量",
    PowerSupply: "發電量",
    PowerSurplus: "電力盈餘",
    Level: "等級",
    Power: "電",
    CentralBank: "中央銀行",
    ResourceInput: "輸入",
    ResourceOutput: "輸出",
    ResourceStorage: "庫存",
    ResourceChange: "變化",
    ResourceInOutDesc: '💡 撳上面"輸出-輸入"嘅數字，嚟顯示同輸出/輸入有關嘅建築物',
    ResourceChart: "資源圖表",
    MarketUpdateIn: "市場喺 %{time}之後會更新",
    Income: "收入",
    Semiconductor: "半導體",
    SemiconductorFactory: "半導體工廠",
    Steel: "鋼材",
    Bitcoin: "比特幣",
    BitcoinFarm: "比特幣農場",
    Dogecoin: "狗狗幣",
    DogecoinFarm: "狗狗幣農場",
    Guitar: "吉他",
    GuitarFactory: "吉他工廠",
    Drum: "鼓",
    DrumFactory: "製鼓廠",
    RecordingStudio: "錄音室",
    OperaHouse: "歌劇院",
    CoalGasificationPlant: "煤氣化廠",
    GasProcessingPlant: "天然氣處理廠",
    Music: "音樂",
    Glass: "玻璃",
    PhoneFactory: "手機工廠",
    Phone: "手機",
    GlassFactory: "玻璃工廠",
    Oil: "石油",
    Chromium: "鉻",
    ChromiumMine: "鉻礦場",
    Uranium: "鈾",
    EnrichedUranium: "濃縮鈾",
    NuclearPowerPlant: "核電廠",
    UraniumEnrichmentPlant: "濃縮鈾廠",
    UraniumMine: "鈾礦場",
    Titanium: "鈦",
    TitaniumMine: "鈦礦場",
    TitaniumAlloyPlant: "鈦合金廠",
    ChromiumAlloyPlant: "鉻合金廠",
    Input: "輸入",
    PanelPosition: "面板位置",
    PanelPositionDesc: "將控制面板擺喺左邊，右邊或自動 (取決於目前揀嘅區域)",
    InputCapacity: "輸入容量",
    InputCapacityPerCycle: "輸入容量/周期",
    Output: "輸出",
    OutputCapacity: "輸出容量",
    OutputCapacityPerCycle: "輸出容量/周期",
    ResourceDeposit: "資源礦床",
    RecommendedBuilding: "💡 呢度有 %{resource}資源",
    AdjacentBonus: "相鄰加成",
    AdjacentBonusDesc: "每棟相鄰同類型嘅工作建築物將帶來%{bonus}%嘅額外產量",
    ConsiderIncreaseProduction: "💡 考慮增加 %{resource} 生產",
    AlwaysTransportInput: "儲存模式",
    AlwaysTransportInputTradeCenter: "始終集存",
    AlwaysTransportInputTradeCenterDesc: "始終將資源送到交易所，就算嗰個資源冇開自動賣出",
    AlwaysTransportInputDesc: "始終輸入資源，就算佢哋高過最低生產要求",
    ProductionCycleLength: "生產周期",
    ProductionCycleLengthDesc:
        "一個生產周期嘅時間，以秒嚟做單位。延長周期會增加每個周期嘅消耗同生產，從而降低獲取輸入資源嘅優先級",
    MaxInputDistance: "最大輸入距離",
    MaxInputDistanceDesc: "呢棟建築以區塊數量計算輸入資源嘅最大距離",
    AutoSellCapacity: "自動賣出數量",
    AutoSellCapacityDesc: "自動賣出每秒可以處理每種資源嘅最大數量",
    CurrentAutoSellCapacityMultiplier: "目前倍率: x%{n}",
    AutoSellConcurrency: "同時自動賣出數量",
    AutoSellConcurrencyDesc: "自動賣出可以同時處理嘅最大資源數量",
    MaxAutoSellConcurrencyReached: "您已經去到最大自動賣出數量，請閂咗另一個自動賣出項目嚟開呢個自動賣出",
    CannotSellBuilding: "而家唔可以賣呢個建築物",
    WallStreet: "華爾街",
    MarketCap: "市值",
    MarketCapDesc: "您公司的嘅緦市值(如市場價值)",
    BuildingValuation: "建築估值",
    BuildingValuationDesc: "您嘅所有建築物總價值，包括建築許可證同升級",
    ResourcesValuation: "資源估值",
    ResourcesValuationDesc: "庫存資源總價值",
    Battery: "電池",
    BatteryFactory: "電池工廠",
    RatingBuy: "買入",
    RatingSell: "賣出",
    SwissShop: "瑞士商店",
    RatingHold: "保持",
    RatingOutperform: "表現優異",
    RatingUnderperform: "表現唔好",
    StockRating: "股票評級",
    JetEngine: "噴射引擎",
    Helicopter: "直升機",
    Lithium: "鋰",
    LithiumMine: "鋰礦場",
    LiionBatteryFactory: "鋰電池工廠",
    HelicopterFactory: "直升機工廠",
    Satellite: "衛星",
    ToyFactory: "玩具工廠",
    Toy: "玩具",
    SpaceStation: "太空站",
    SpaceStationFactory: "太空站工廠",
    OperatingSystem: "作業系統",
    OperatingSystemCompany: "作業系統公司",
    LinuxDistribution: "Linux 發行版",
    Internet: "網際網路",
    WebBrowser: "網頁瀏覽器",
    Console: "遊戲機",
    ConsoleFactory: "遊戲機工廠",
    Train: "火車",
    TrainFactory: "火車工廠",
    ShoeFactory: "製鞋廠",
    Shoes: "鞋",
    ArtilleryFactory: "大炮工廠",
    Artillery: "大炮",
    SubmarineFactory: "潛水艇工廠",
    Submarine: "潛水艇",
    Spaceship: "太空船",
    RobotFactory: "機器人工廠",
    Robot: "機器人",
    SpaceshipFactory: "太空船工廠",
    SatelliteFactory: "衛星工廠",
    JetEngineFactory: "噴射引擎工廠",
    StockRatingDesc: "嚟自華爾街分析師嘅股票評級共識，佢會影響您嘅市值，並隨着市場一齊更新",
    InterestRate: "過夜利率",
    InterestRateDesc: "您喺離線嗰陣透過市值賺到嘅利息",
    OfflineEarning: "離線收入",
    OfflineEarningDesc: "離線收入取決於您的市值和利率",
    PerMin: "%{amount}/分鐘",
    OfflineEarningTime: "離線賺取時間",
    OfflineEarningTimeDesc: "您可以攞到離線收入嘅時間",
    BuyPermit: "買許可證",
    NotEnoughBuildingPermit: "唔夠建築許可證，請買多啲嚟起新嘅建築物",
    MovingAverage: "平均變化",
    MovingAverageDesc: "顯示資源變化嘅平均值，而唔係即時嘅變化",
    AllowZoom: "縮放",
    AllowZoomDesc: "打開縮放支援。用滑鼠滾輪嚟縮放。而家嘅縮放率係%{zoom}",
    AllowZoomMobileDesc: "打開縮放支援。用手指嚟縮放。而家嘅縮放率係%{zoom}",
    Settings: "設定",
    Sound: "音效",
    SoundDesc: "打開音效，如撳掣或者出錯嘅聲",
    AutoHighlight: "自動突顯",
    AutoHighlightDesc: "當您揀建築物個嗰陣，會自動突顯一樣建築物",
    MusicDesc: "打開音樂: Shane Ivers (https://www.silvermansound.com)嘅《It's Not Over 'Til The Bossa Nova》",
    Credits: "鳴謝",
    Icons: "圖標",
    MisplacedBuilding: "⛔ 呢個%{building} 冇擺喺啱嘅資源格上面",
    HighlightBuildings: "突顯建築",
    HighlightTurnedOff: "...被閂咗嘅",
    HighlightStockpileModeOn: "...已經開咗庫存模式嘅",
    HighlightProductionCycleNotDefault: "...生產周期 > 1嘅",
    HighlightMaxInputDistanceNotDefault: "..最大輸入距離 < ∞嘅",
    HighlightNotMakingProfit: "...唔盈利嘅",
    NBuildingsAreHighlighted: "%{n}個建築物被突顯",
    OnlyToWarehouse: "淨係送到倉庫",
    OnlyToWarehouseDesc: "得倉庫先可以由呢座建築物度送資源",
    TurnOffProduction: "閂",
    TurnOffProductionDesc: "閂咗建築物嘅生產。佢唔會再送資源同用電",
    ApplyToAll: "套用喺全部%{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "無限",
    Transport: "運送",
    TileModifier: "板塊增益",
    ShowAllModifiers: "顯示全部板塊增益",
    HideAllModifiers: "隱藏全部板塊增益",
    NumberOfBuildings: "您有嘅建築物數量",
    ShowContent: "顯示內容",
    HideContent: "隱藏內容",
    BuyExpansionPack: "用%{price}購買",
    Cities: "城市",
    InputStrategy: "輸入策略",
    InputStrategyClose: "近啲",
    InputStrategyCloseDesc: "揀最近嘅，而且夠資源嘅倉庫",
    InputStrategyFar: "遠啲",
    InputStrategyFarDesc: "揀最遠嘅，而且夠資源嘅倉庫",
    InputStrategyAmount: "多啲倉儲",
    InputStrategyAmountDesc: "就算距離係點，都係最多倉儲嘅倉庫先",
    FuelCostSave: "慳燃料",
    FuelCostSaveDesc: "同其他建築物相比，倉庫到一定比例嘅燃料嚟送資源，越高級，就會慳越多",
    SoftwareCompany: "軟件公司",
    Software: "軟件",
    ScreenFactory: "螢幕工廠",
    Screen: "螢幕",
    JoinDiscord: "加入我哋嘅Discord伺服器嚟攞到最新更新、技巧資訊同討論",
    ClaimOfflineEarning: "攞離線收入",
    OfflineTime: "離線時間",
    Minutes: "%{time}分鐘",
    MaxUpgrade: "最高級",
    MaxUpgradeDesc: "您已經去到最高級",
    ClaimAmount: "錢 +%{amount}",
    EarningPerMinute: "收益率",
    EffectiveTime: "有效時間",
    EffectiveTimeDesc: "您嘅有效離線收入時間唔超過 %{time}分鐘",
    BuildSearchPlaceholder: "打要揾嘅建築物或者資源",
    MineOverlayWarning: "%{building} 唔受板塊增益影響",
    WholesaleCenter: "批發所",
    OrderFrom: "嚟自%{name}嘅訂單",
    ExpireIn: "到期",
    TurnOnAllProductions: "生產開始",
    TurnOnAllProductionsDesc: "打開全部建築物生產，喺開緊「摼成本」政策嗰陣用唔到",
    OperationSuccessful: "呢個操作搞掂咗",
    TurnOn: "打開",
    Reward: "獎勵",
    PerSecond: "%{time}/秒",
    PerCycle: "%{amount}/周期",
    PolicyPoint: "政策點",
    PolicyPointPerMinute: "生產速率",
    PolicyPointPerMinuteDesc: "您喺遊戲入面每分鐘都會攞到政策點",
    YourWilLGaimPolicyPoints: " 您會喺{time}秒後攞到%{amount}個政策點",
    PolicyPointDesc: "💡 開越多政策，每個政策消耗就越多",
    NextOrderIn: "下一個訂單仲要",
    FillOrder: "成交",
    RejectOrder: "跳過",
    WholesaleCenterLocked: "您至少要%{required}種唔同嘅資源嚟解鎖批發所。您得%{current}種資源",
    OrderFilled: "嚟自 %{from}嘅訂單已成交！",
    PolicyCenter: "政策中心",
    NewOrder: "嚟自 %{from}嘅新訂單到咗，請喺批發所睇睇",
    Policies: "政策",
    PolicyNotEnoughTime: "您唔夠政策點嚟開呢個政策",
    TimeLeft: "得返 %{time}",
    WholesaleCenterOrderFaster: "世界博覽會",
    WholesaleCenterOrderFasterDesc: "批發所收到嘅訂單會快2倍同大2倍",
    PolicyOilWellPowerx2: "增壓油井",
    PolicyOilWellPowerx2Desc: "油井生產2倍石油，而且用2倍嘅電",
    HalfTransportSpeed: "送慢啲",
    HalfTransportSpeedDesc: "運送速度慢25%，燃料成本少25%",
    RefineryMoreOil: "多啲汽油，多啲問題",
    RefineryMoreOilDesc: "煉油廠嘅汽油產量多50%，塑膠嘅產量少50%",
    StickyInput: "舊客",
    StickyInputDesc: "建築物會傾向以前嘅來源，而唔係每個周期都揾最好嘅來源 (免費政策)",
    RefineryMorePlastic: "多啲塑膠，多啲問題",
    RefineryMorePlasticDesc: "煉油廠嘅汽油產量少50％，塑料嘅產量多50％",
    FreeOilTransportDesc: "運石油唔使用燃料，但油井用電量係原本嘅2倍",
    SuperSteelMill: "鋼鐵雄心",
    SuperSteelMillDesc: "煉鋼廠嘅煤炭消耗量少50％，鐵消耗量多25％，用多25％嘅電",
    AlSemiconductor: "鋁電路",
    AlSemiconductorDesc: "電路板工廠用鋁代替銅",
    CostSaver: "慳成本",
    CostSaverDesc: "如果建築物嘅生產成本大過產出，就停咗佢",
    CostSaverBuildingDesc: "慳成本政策開咗，生產會跟獲利能力嚟自動開閂",
    CostSaverBuildingWarning: "慳成本政策開咗，您唔可以手動改",
    GlassUseCoal: "黑玻璃",
    GlassUseCoalDesc: "玻璃工廠用煤炭多50％，矽少50％",
    AdjacentBonusOnlyOutput: "鄰近加成+",
    AdjacentBonusOnlyOutputDesc: "鄰近加成唔使多啲輸入，但係會用多啲電力，並且得50％嘅效率",
    IronMine2xOutput: "富鐵礦",
    IronMine2xOutputDesc: "鐵礦場產生2倍鐵，但送鐵會用2倍嘅燃料",
    SolarPanelAlwaysWork: "太陽唔落山",
    SolarPanelAlwaysWorkDesc: "太陽能板喺100％時間工作，但產電少60％",
    SteelScience: "鋼鐵知識",
    SteelScienceDesc: "煉鋼廠使用2倍輸入並產生額外嘅科學點",
    ShoppingSpree: "瘋狂買嘢",
    ShoppingSpreeDesc: "如果資源唔夠輸出量，就從交易所自動買入缺嘅 (如果嗰啲資源有開自動賣出，就會被忽略)",
    ShoppingSpreeTradeCenterDesc: "💡 瘋狂購物政策開咗，交易所會自動買入缺嘅資源",
    ExtraPolicyPoints: "政治說客",
    CrAlloyUseFe: "鐵鉻合金",
    CrAlloyUseFeDesc: "鉻合金工廠唔用鋰，反而係2倍鋰用量嘅鐵",
    DoubleTileModifier: "自然嘅力量",
    TileModifierOutputOnly: "板塊增益+",
    GasPlantPetrol: "天然氣液化",
    GasPlantPetrolDesc: "天然氣發電廠用額外嘅天然氣，嚟產生汽油",
    BuildingRecycle: "建築回收",
    BuildingRecycleDesc: "喺起咗之後1分鐘入面賣咗嗰座建築物，可以有全額退款",
    CoalPlantFuel: "煤液化",
    CoalPlantFuelDesc: "燃煤發電廠用額外嘅煤炭，嚟產生汽油",
    Welcome: "歡迎",
    SeeTutorialAgain: "再教學一次",
    HelpTranslateTheGame: "幫手翻譯遊戲🌐",
    SkipTutorial: "跳過教學",
    NextTutorial: "下一步",
    Tutorial1:
        "閒置工業係一隻<em>資源管理</em>遊戲，喺呢度你可以起工廠🏭，生產商品📦，同賺錢💸。<br><br>一齊嚟透過一啲基本概念嚟俾你開始 — 唔會好耐，我保證。",
    Tutorial2:
        "全部建築物都要電⚡，您有一個<em>風力發電機</em>可以發電。您可以喺左上角睇到而家嘅電力供應。<br><br>您可能已經注意到風力發電機淨係做<em>80%</em>嘅時間。 您可以考慮起其他種嘅發電廠嚟產生穩定嘅電。",
    Tutorial3:
        "您喺地圖上有好多<em>資源點</em>。要攞資源，您要喺相應嘅資源點<em>上面</em>起咗礦場⛏️先。<br><br>例如，您有一個<em>油井🛢️</em>喺石油田度開採<em>石油</em>。<br></br>資源蘊藏量係無限嘅 — 唔使擔心佢哋會用晒。除咗開採設備，其他建築都可以起喺任何一個空格上面",
    Tutorial5:
        "為咗賺錢，您要透過交易所嚟輸出你嘅資源。要咁做，淨係要打開資源嘅<em>自動賣出</em>。<br></br>您都可以好好咁喺交易所度買資源。記住<em>如果您買某種資源，就會提高佢個價格</em>同埋如果您賣某種資源，就會降低佢個價格。<br><br>市場<em>波動很大</em>而且價格📈會定期變。",
    Tutorial6:
        "要起新嘅建築物，您要先喺<em>研究實驗室🧪</em>度解鎖佢。研究實驗室仲會將科學轉成研究點。<br><br>您嘅風力發電機（同其他發電廠）喺郁嗰陣會產生少少科學。仲有，您之後可以起學校🏫同其他專用建築物嚟加速科學.<br><br>而家您已經了解咗全部基礎，開始建立您嘅經濟！呢度有啲<em>錢💸</em>同<em>汽油⛽</em>嚟俾您一個跳躍嘅開始。",
    WelcomePlay: "開始遊戲",
    WelcomePlayMuted: "開始遊戲 (🔇音樂)",
    Chat: "傾偈",
    Send: "送出",
    Import: "匯入",
    Export: "匯出",
    LastBackupAt: "最後備份",
    RestoreFromBackup: "喺備份度還原",
    RestoreFromBackupFail: "冇辧法喺Steam Cloud度還原備份：您真係有備份？",
    RestoreFromBackupTitle: "真係？",
    RestoreFromBackupDesc: "通常您都唔使喺雲端備份度嚟還原，除非唔見咗本機存檔。雲端備份時間點會早過本機存檔少少",
    ChatMessages: "傾偈訊息",
    ChangeName: "改名",
    SaveName: "儲存",
    NameValidationRule: "您嘅名淨係可以含字母同數字，而且長度係5至15個粒字",
    NameValidationRuleProfanity: "您嘅名唔應該包含違規嘅字",
    ChatMessageRateLimit: "您淨係可以每10秒發送一次新嘅訊息",
    NameSaved: "您嘅名成功改好咗",
    NoMessages: "冇新訊息",
    Leaderboard: "排行榜",
    Name: "名",
    Rank: "排名",
    Tips1: "股票評級分開5個等級：買入，表現好好，保持，表現唔好同賣出",
    Tips2: "如果夠生產能力，建築物就會停運資源，除非您開儲存模式",
    Tips3: "資源運輸嘅燃料成本取決喺距離同資源量",
    Tips4: "如果喺地圖上面揾到嘅量多過輸入容量，建築物就淨係會運資源",
    Tips5: "如果嗰啲資源閂咗自動賣出，建築物就淨係會喺交易所度運嗰啲資源",
    Tips6: "您可以喺相應嘅輸入容量部分下面睇到資源嘅燃料成本",
    Tips7: "如果您買資源，會提高佢個價格。如果您賣資源，會降低佢個價格",
    Tips8: "您可以喺統計局度睇到每種資源嘅數量同變化嘅圖表",
    Tips9: "建築物需要嘅研究點取決喺輸入資源嘅市場價格",
    Tips10: "唔同嘅資源喺市場嘅定價都唔同 — 隨時為市場波動做好準備",
    Tips11: "喺擴展生產之前，最好檢查吓電同燃料供應",
    FPS30: "慳電",
    OfflineModeDesc: "冇辧法連到伺服器：唔會產生離線收入。請檢查您嘅網路連接",
    OptOut: "揀退出",
    OptIn: "重設再開過",
    LeaderboardOptOut: "退出排行榜",
    LeaderboardOptOutDesc: "這將不再發送排行榜得分。請注意：如果以後要啟用排行榜，則需要重置數據",
    LeaderboardOptIn: "重設再開過排行榜",
    LeaderboardOptInDesc: "您要先重設您嘅數據，然後先可以再開排行榜，真係要？",
    RewardAdsFailed: "睇廣告獎勵未搞掂",
    RewardAdsNotAvailable: "睇廣告獎勵冇得用 (而家淨係支援iOS/Android)",
    OfflineEarningDoubleSuccess: "您嘅離線收入加多咗一倍",
    FPS30Desc: "打開慳電模式會令遊戲用30FPS代替60FPS嘅更新率嚟郁。會延長您嘅電池續航時間",
    HighlightAll: '突出顯示 "%{type}"',
    HighlightInput: "🔍 突出顯示 %{type}輸入",
    HighlightOutput: "🔍 突出顯示 %{type}輸出",
    TotalInput: "總輸入量",
    TotalOutput: "總輸出量",
    RunOutIn: "%{time}之後會用晒",
    FuelRunOutWarning: "💡 您嘅燃料消耗多過生產。喺燃料用晒嗰陣，您嘅運輸會停",
    InAmount: "輸入: %{number}",
    OutAmount: "輸出: %{number}",
    SwissBank: "瑞士銀行",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "如果您喺一個新城市開始，您會攞到 %{money} 💵",
    RestorePurchases: "恢復購買",
    RestorePurchasesSuccess: "您嘅購買恢復咗",
    RestorePurchasesFailed: "您嘅購買仲未恢復",
    ExpansionPacks: "擴展包",
    ExpansionPack1: "擴展包1",
    ExpansionPack1Owned: "擴展包 1",
    RequireExpansionPack1: "擴展包 1",
    RequireExpansionPack1Desc: "呢個淨係用喺擴展包1",
    RequireAnyExpansionPack: "獨家擴展包",
    RequireAnyExpansionPackDesc: "呢個功能要您至少有一個擴展包",
    HideRewardAd: "收埋獎勵廣告",
    HideRewardAdDesc: "全部喺遊戲入面嘅廣告都係有得揀嘅獎勵廣告。咁樣會喺遊戲度收埋晒佢哋嘅選項。",
    HideDiscordBanner: "收埋Discord橫幅",
    HideDiscordBannerDesc: "收埋總部嘅Discord同舖頭橫幅",
    HideChat: "收埋傾偈訊息",
    SortedByDeficit: "按損失排",
    PurchaseFailed: "未買好",
    PurchaseSteamContinue: "請喺Steam度買好",
    PurchaseSuccess: "買好咗啦，多謝您嘅支持",
    PrestigeCurrency: "瑞士錢 💵",
    RestartDesc: "💡 想重新嚟過？您可以撳上面嘅「喺新城市開始」同埋揀好您嘅新城市",
    PrestigeGoBack: "返轉頭",
    ProductionMultiplier: "生產增益",
    ProductionMultiplierDesc: "提高您全部建築物嘅生產能力 (包括礦場、工廠、發電廠、科學同文化建築物)",
    FuelCostDiscount: "燃料成本折扣",
    FuelCostDiscountDesc: "喺運資源個嗰陣俾燃料成本折扣",
    AutoSellCapacityMultiplier: "自動賣出能力倍率",
    AutoSellCapacityMultiplierDesc: "就算而家嘅銷量係點，都會乘埋您嘅自動賣出數量嘅倍率",
    BuildingPermitCostDivider: "建築許可證成本除率",
    BuildingPermitCostDividerDesc: "建築許可成本除嗰個除率",
    ExtraAdjacentBonus: "額外相鄰加成",
    ExtraAdjacentBonusDesc: "每個相鄰嘅同類型郁緊建築物嘅額外加成量",
    OfflineEarningMultiplier: "離線收入倍率",
    OfflineEarningMultiplierDesc: "用喺離線收入嘅倍率",
    PrestigeAlertTitle: "真係？",
    PrestigeAlertContent: "您嘅公司會被清算。您會喺 %{amount}瑞士錢而且喺 %{city}成立新公司",
    PrestigeCurrencyDesc: "呢個係您喺秘密瑞士銀行帳戶嘅錢，您可以帶埋佢喺一個新城市重新嚟過",
    Prestige: "過數",
    Cancel: "取消",
    SaveFileCorrupted: "存檔文件壞咗",
    CheatDetected: "您嘅舊存檔未俾伺服器驗證，用唔到。您會喺新存檔度開始",
    LoadGameError: "入唔到遊戲",
    LoadGameErrorMessage: "錯誤: %{message}",
    LoadGameErrorDesc: "請檢查您嘅網路連線。如果問題仲喺度，請聯絡客服人員",
    ExpansionPackIncompatible: "您匯入緊擴展包存檔，但您嘅遊戲冇需要嘅擴展包",
    SaveFileMigrated: "新時代：Beta測試喺度",
    SaveFileMigratedDesc: "多謝您加入遊戲嘅alpha測試。您嘅舊地圖唔相容，但係我哋已經轉移咗您嘅數據而且俾咗您一啲獎勵",
    ClaimSwissMoney: "攞 %{amount}瑞士錢 💵",
    SaveFileMigratedFinePrint:
        "您嘅市值會轉去瑞士錢，未用嘅瑞士錢會一齊轉。您會攞到額外50％嘅瑞士錢攞嚟做加入遊戲alpha測試嘅獎勵。可以轉嘅瑞士錢最多200",
    CashIn: "過數`",
    CurrentCity: "而家嘅城市",
    CashInDesc:
        "如果您喺一個新城市開始，就會將呢個存款存入您嘅瑞士銀行戶口。呢個係喺您公司嘅市值，而且要去到 %{amount} 先可以賺瑞士錢",
    MoveToNewMap: "喺新城市開始",
    CityName: "城市",
    CitySize: "地圖大細",
    GridType: "網格類型",
    StartInThisCity: "喺 %{city}開始",
    CityBonus: "城市增益",
    ResourceTilePercentage: "資源格",
    MapSquareGrid: "正方形",
    MapHexGrid: "六邊形",
    Stockholm: "斯德哥爾摩",
    Rotterdam: "鹿特丹",
    Oslo: "奧斯陸",
    StPetersburg: "聖彼得堡",
    Hamburg: "漢堡",
    HamburgBonus:
        "<li>齊柏林飛艇工廠係解鎖咗</li><li>半導體工廠有2倍嘅產量</li><li>造船廠有2倍嘅產能</li><li>車廠有2倍嘅產能</li><li>鋰電池工廠係解鎖咗</li>",
    Toulouse: "圖盧茲",
    Rome: "羅馬",
    RomeBonus:
        "<li>羅馬競技場係解鎖咗</li><li>羅馬競技場有2倍嘅產量</li><li>一開始有5級政策中心</li><li>歌劇院有2倍嘅產能</li><li>錄音室會產生文化</li>",
    Detroit: "底特律",
    Boston: "波士頓",
    BostonBonus:
        "<li>一開始有5級研究實驗室</li><li>理工學院係解鎖咗</li><li>理工學院有2倍嘅產能</li><li>學校有2倍嘅產能</li><li>大學有2倍嘅產量</li>",
    HideNotProducing: "收埋冇生產嘅資源",
    SortByStorage: "儲倉",
    SortByProduction: "產量",
    SortByName: "名",
    PlayerTrade: "玩家交易",
    AddTradeFail: "加唔到交易",
    AddTradeExceedMaximumTrade: "您最多淨係可以有 %{number}個係交易緊，攞咗或者取消其中一個",
    AddTradeSuccess: "您嘅交易成功加到",
    LoadTradeFail: "入唔到玩家交易，請等陣再試",
    ClaimTradeFail: "攞唔到呢個交易，請等陣再試",
    CancelTradeSuccess: "您嘅交易成功取消到",
    CancelTradeFail: "取消唔到呢個交易，請等陣再試",
    AcceptTradeFail: "接受唔到呢個交易，請等陣再試",
    PlayerTradeBanner: "同其他玩家交易資源",
    PlayerTradeResource: "資源",
    PlayerTradeAmount: "交易量",
    PlayerTradePrice: "價錢 $",
    PlayerTradeValue: "價值 $",
    PlayerTradeWaiting: "等緊...",
    UseTradeCenterPrice: "用交易所嘅價錢",
    AddTrade: "加交易",
    ActiveTrades: "交易緊",
    AcceptTrade: "接受",
    CancelTrade: "取消",
    RefundTrade: "退款",
    RefundTradeSuccess: "呢個交易退咗款: %{resource}退返俾您嘅交易所",
    RefundTradeFail: "退款唔到呢個交易, 請等陣再試",
    ClaimTrade: "攞",
    RefreshTrade: "更新",
    PasteYourSave: "請貼上您嘅存檔數據",
    FailedToImportSave: "匯入唔到存檔",
    FailedToImportSaveDesc: "您嘅存檔文件唔相容或者壞咗: %{error}",
    SaveCopiedToClipboard: "您嘅存檔數據複製咗落去您嘅剪貼簿",
    CancelActiveTradeFirst: "您有做緊嘅玩家交易，請取消/領取咗先",
    FailedToCheckActiveTrade: "檢查唔到做緊嘅玩家交易, 請等陣再試",
    PlayerTradeQuotaExceed: "呢個交易多過您嘅配額",
    PlayerTradeValidRange: "範圍: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "買到",
    PlayerTradeQuota: "淨低配額: %{value}",
    PlayerTradeUnavailable: "喺同玩家交易之前，你要喺生產同儲倉度至少有一個資源",
    PlayerTradeToClaim: "您有 %{num}單玩家交易仲未攞",
    PowerBank: "蓄電池",
    PowerBankBuildDesc: "儲存多出嚟嘅電，喺唔夠電嗰陣出電",
    WarehouseBuildDesc: "用少啲燃料消耗運同儲任何資源",
    PowerBankChargeSpeed: "充電速度",
    PowerBankPowerLeft: "電得返",
    PowerBankMoreCapacity: "慳電",
    PowerBankMoreCapacityDesc: "蓄電池嘅充電速度少到50%，但係多50%容量",
    PowerBankNotWorking: "⛔ 蓄電池淨係喺黐實發電廠嗰陣先會做嘢",
    ExcludeBuildingsShutdown: "除咗被閂咗嘅建築",
    ColorTheme: "遊戲顏色主題",
    ColorThemeDesc: "顏色主題用喺遊戲圖標、突出顯示、網格同背景。要重新開過先會套用",
    SiliconMine2xOutput: "矽谷",
    SiliconMine2xOutputDesc: "矽礦場生產2倍矽，但用電量多50%，運矽嘅燃料消耗多50%",
    CoalMine2xOutput: "工業革命",
    CoalMine2xOutputDesc: "煤礦場生產2倍煤，但用電量多50%，運煤嘅燃料消耗多50%",
    AlMine2xOutput: "鋁電解",
    AlMine2xOutputDesc: "鋁礦場產生2倍鋁，但用2倍嘅電",
    LoggingCamp2xOutput: "砍伐森林",
    LoggingCamp2xOutputDesc: "伐木場產生2倍木，但運木用2倍燃料",
    PowerBankLeft: "蓄電池電量",
    ColorThemeEditor: "編輯主題色彩",
    ColorThemeEditorDesc: "您可以改您嘅色彩主題。而家您有 %{num}個更動",
    ColorThemeEditorSave: "儲存",
    ColorThemeEditorReset: "重設",
    ColorThemeEditorResetAll: "全部重設哂",
    NewMessageMentions: "提到您嘅訊息: %{message}",
    HideChatMentions: "收埋訊息提醒",
    HideChatMentionsDesc: "訊息提到我嗰陣，唔播音效或者彈出提醒",
    PendingConstructionCannotReload: "您有做緊嘅建築施工，令遊戲冇得重新入過",
    AcceptTradeFailRateLimit: "每 %{time}秒先可以接受一單交易",
    DowngradeBuilding: "降級",
    CancelTradeConfirmDialogTitle: "取消呢個交易？",
    CancelTradeConfirmDialogYes: "係",
    CancelTradeConfirmDialogNo: "唔好",
    WarehouseInputRoutes: "進貨線",
    WarehouseAddInput: "加入貨點",
    WarehouseTapToSelect: "喺地圖到揀...",
    WarehouseFindOnMap: "🔍 喺地圖到搵",
    WarehouseRemoveRoute: "刪咗佢",
    WarehouseAddRouteFail: "加唔到入貨點: 揀嘅地點冇貨源",
    LevelN: "Lv. %{level}",
    Surplus: "盈餘",
    Production: "生產",
    Consumption: "消耗",
    WarehouseInputCapacityDescV2: "總入貨量: 平均分到每條進貨線",
    WarehouseInputCapacityPerRoute: "進貨配額:",
    PlayerCountryFlag: "玩家旗",
    PlayerCountryChooseFlag: "按國家代碼排",
    WindTurbineAlwaysWork: "有風啦",
    WindTurbineAlwaysWorkDesc: "風力發電機唔間斷咁郁，但發電量少30%",
    BookPublisherScience: "科學文獻",
    BookPublisherScienceDesc: "圖書出版社生產科學代替文化",
    WarehouseOutwardFuelSave: "免費出貨",
    WarehouseOutwardFuelSaveDesc: "喺倉庫度出貨，都會同樣慳油",
    ImportSaveVersionTooNew: "匯入嘅存檔版本係 %{saveVersion}，但您嘅遊戲版本係 %{gameVersion}。請更新咗您嘅遊戲先。",
    BatteryFuelEconomy: "充電電池",
    BatteryFuelEconomyDesc: "電池燃料效率好100% (例如50%燃料消耗)",
    ShowTheoreticalInputOutputCapacity: "顯示理論嘅輸入/輸出量",
    SpecialTransportCost: "有特殊運輸成本嘅資源",
    FreeTransportCost: "免費運嘅資源",
    Osaka: "大阪",
    OsakaBonus:
        "<li>資源生成集中啲</li><li>倉庫可以慳多50%燃料</li><li>獨特建築: 漫畫出版社</li><li>獨特建築: 動漫工作室</li><li>半導體工廠有2倍產量</li><li>鋰離子電池工廠有2倍產能</li><li>電池工廠係解鎖咗</li><li>電池工廠有2倍產能</li><li>電池嘅燃料效率好100%</li><li>電池工廠唔使煤</li><li>一開始就有100K電池</li>",
    HideChatDescV2: "收埋下面工具欄嘅傾偈訊息。顯示傾偈訊息，即係您同意我哋嘅",
    HideChatDescV2ToS: "服務條款",
    IntegratedCircuitFab: "集成電路工廠",
    MangaPublisher: "漫畫出版社",
    Manga: "漫畫",
    AnimeStudio: "動漫工作室",
    Anime: "動漫",
    PlayerTradeAction: "操作",
    PlayerTradeBuy: "買",
    PlayerTradeSell: "賣",
    PlayerTradeBid: "收",
    PlayerTradeAsk: "出",
    CancelTradeConfirmDialogDescV2: "取消呢個交易會退返%{percent}嘅資源/現金。資源會退到交易所倉庫",
    ClaimTradeSuccessV2: "您搞嘅交易搞掂咗: %{cashOrResource}",
    AcceptTradeSuccessV2: "您搞掂咗呢單交易: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "好過市場價格",
    ResourceExplorer: "資源探勘者",
    ResourceExplorerDesc: "你可以喺空地度攞資源",
    ResourceExplorerDescLong: "💡 資源勘探者建築冇相鄰加成。佢嘅電消耗係睇資源",
    ResourceExplorerSelectResource: "探勘",
    ProductionSettings: "生產設定",
    PlayerTradeQuotaDesc: "💡 您嘅玩家交易配額係您市值嘅%{percent}, 會喺市場更新之後重置",
    PlayerTradePartialFillTitle: "揀成交%",
    PlayerTradeAmountNotValidV2: "交易量至少有1",
    PlayerTradeOptOut: "您已經揀咗退出排行榜，唔可以同其他玩家交易",
    FirstTimeReadGuide: "💡 唔知點玩，要幫手？撳呢度讀新手指南！",
    ReadSteamGuideV2: "遊戲指南",
    ReadSteamGuideV2Desc: "您可以喺Steam度睇吓由遊戲社區寫嘅指南 — 您都可以寫自己嘅指南",
    ChatMessageTooLong: "傾偈訊息字數多過上限",
    ChatPlaceholderV2: "喺呢度打訊息: 最長%{length}隻字",
    ShowProfitBreakdown: "顯示利潤細節",
    HideProfitBreakdown: "收埋利潤細節",
    ProfitBreakdownOutput: "%{res} 生產",
    ProfitBreakdownInput: "%{res} 消耗",
    ProfitBreakdownFuel: "燃料成本",
    BuildingProfit: "利潤",
    RestoreBackup: "恢復",
    SteamLogin: "用Steam帳戶登入",
    SteamLoginDialogDesc:
        "您嘅本地遊戲存檔度開咗擴展包，咁您就要登入Steam帳戶嚟繼續。您都可以揀「*刪本地存檔*」重新嚟過",
    SteamLoginDesc: "如果您嘅Steam賬戶有擴展包，登入咗您就可以喺Web版度同擴展包玩",
    SteamLoginYes: "登入",
    SteamLoginNo: "刪完再開",
    KungFuDojo: "功夫館",
    KungFu: "功夫",
    TaiChi: "太極",
    TaiChiDojo: "太極館",
    HongKong: "香港",
    FreeTransportToTradeCenter: "國際出口貿易",
    FreeTransportToTradeCenterDesc: "運到交易所唔用燃料，但喺交易所運出資源用多50%燃料",
    TaiChi10xCulture: "東方之珠",
    PlayerTradeYouHave: "庫存: %{amount}",
    PlayerTradeFillValue: "價值",
    FiberFactory: "光纖工廠",
    Fiber: "光纖",
    Achievements: "成就",
    AchievementsDesc: "您攞咗%{total}個成就入面嘅%{number}個",
    AchievementsReward: "獎勵: 瑞士錢 +%{swiss}",
    AchievementsRewardToast: "您攞咗獎勵: 瑞士錢 +%{swiss}",
    AchievementsClaim: "攞",
    AchievementsToast: "您攞到成就 %{name}，請喺總部度攞獎勵",
    AchievementStockholm100: "新生維京人",
    AchievementStockholm100Desc: "喺斯德哥爾摩一次過賺100瑞士錢",
    AchievementStockholm500: "畢業維京人",
    AchievementStockholm500Desc: "喺斯德哥爾摩一次過賺500瑞士錢",
    AchievementStockholm1000: "有經驗嘅維京人",
    AchievementStockholm1000Desc: "喺斯德哥爾摩一次過賺1000瑞士錢",
    AchievementOslo100: "挪威石油愛好者",
    AchievementOslo100Desc: "喺奧斯陸一次過賺100瑞士錢",
    AchievementOslo500: "挪威石油專家",
    AchievementOslo500Desc: "喺奧斯陸一次過賺500瑞士錢",
    AchievementOslo1000: "挪威石油大亨",
    AchievementOslo1000Desc: "喺奧斯陸一次過賺1000瑞士錢",
    AchievementRotterdam100: "紙風車物主",
    AchievementRotterdam100Desc: "喺鹿特丹一次過賺100瑞士錢",
    AchievementRotterdam500: "風車物主",
    AchievementRotterdam500Desc: "喺鹿特丹一次過賺500瑞士錢",
    AchievementRotterdam1000: "風力發電機物主",
    AchievementRotterdam1000Desc: "喺鹿特丹一次過賺1000瑞士錢",
    AchievementDetroit100: "本地車經銷商",
    AchievementDetroit100Desc: "喺底特律一次過賺100瑞士錢",
    AchievementDetroit500: "地區汽車經銷商",
    AchievementDetroit500Desc: "喺底特律一次過賺500瑞士錢",
    AchievementDetroit1000: "全國汽車經銷商",
    AchievementDetroit1000Desc: "喺底特律一次過賺1000瑞士錢",
    AchievementBoston100: "賺錢學士",
    AchievementBoston100Desc: "喺波士頓一次過賺100瑞士錢",
    AchievementBoston500: "賺錢高手",
    AchievementBoston500Desc: "喺波士頓一次過賺500瑞士錢",
    AchievementBoston1000: "印鈔博士",
    AchievementBoston1000Desc: "喺波士頓一次過賺1000瑞士錢",
    AchievementRome100: "戴克里先",
    AchievementRome100Desc: "喺羅馬一次過賺100瑞士錢",
    AchievementRome500: "君士坦丁大帝",
    AchievementRome500Desc: "喺羅馬一次過賺500瑞士錢",
    AchievementRome1000: "凱撒奧古斯都",
    AchievementRome1000Desc: "喺羅馬一次過賺1000瑞士錢",
    AchievementHamburg100: "德國",
    AchievementHamburg100Desc: "喺漢堡一次過賺100瑞士錢",
    AchievementHamburg500: "祖國",
    AchievementHamburg500Desc: "喺漢堡一次過賺500瑞士錢",
    AchievementHamburg1000: "齊柏林伯爵",
    AchievementHamburg1000Desc: "喺漢堡一次過賺1000瑞士錢",
    AchievementToulouse100: "噴射客機 A310",
    AchievementToulouse100Desc: "喺圖盧茲一次過賺100瑞士錢",
    AchievementToulouse500: "噴射客機 A330",
    AchievementToulouse500Desc: "喺圖盧茲一次過賺500瑞士錢",
    AchievementToulouse1000: "噴射客機 A380",
    AchievementToulouse1000Desc: "喺圖盧茲一次過賺1000瑞士錢",
    AchievementHongKong100: "業餘商人",
    AchievementHongKong100Desc: "喺香港一次過賺100瑞士錢",
    AchievementHongKong500: "專業經紀人",
    AchievementHongKong500Desc: "喺香港一次過賺500瑞士錢",
    AchievementHongKong1000: "秘密基金經理",
    AchievementHongKong1000Desc: "喺香港一次過賺1000瑞士錢",
    AchievementStPetersburg100: "大公爵",
    AchievementStPetersburg100Desc: "喺聖彼得堡一次過賺100瑞士錢",
    AchievementStPetersburg500: "採薩列維奇",
    AchievementStPetersburg500Desc: "喺聖彼得堡一次過賺500瑞士錢",
    AchievementStPetersburg1000: "全俄羅斯沙皇",
    AchievementStPetersburg1000Desc: "喺聖彼得堡一次過賺1000瑞士錢",
    AchievementOsaka100: "日本男爵",
    AchievementOsaka100Desc: "喺大阪一次過賺100瑞士錢",
    AchievementOsaka500: "日本伯爵",
    AchievementOsaka500Desc: "喺大阪一次過賺500瑞士錢",
    AchievementOsaka1000: "日本侯爵",
    AchievementOsaka1000Desc: "喺大阪一次過賺1000瑞士錢",
    SteamAutoCloudBackup: "Steam雲端自動備份",
    SteamAutoCloudBackupFailed: "Steam雲端自動備份唔到: %{error}",
    SteamManualBackup: "強制Steam雲端備份",
    UILoading: "入緊...",
    UserAuthenticated: "您過咗認證",
    BuildingResourceBreakdown: "閒置金額細節",
    SortByDeficit: "虧損",
    SortByRunOut: "用哂",
    SocialNetworkInc: "社交網絡公司",
    SocialNetwork: "社交網絡",
    DatabaseCompany: "數據庫公司",
    Database: "數據庫",
    SatelinkInc: "衛星通信公司",
    GameStationInc: "遊戲站公司",
    AirShuttleInc: "航空公司",
    AircraftCarrierFactory: "航母工廠",
    AircraftCarrier: "航母",
    MapExclusive: "地圖獨有",
    ElectricCar: "尼古拉·特斯拉",
    ElectricCarDesc: "車廠用電池代替汽油而且淨係要50％嘅量",
    HongKongBonusV2:
        "<li>獨特市場定價計算 — 價格同股票評級跟正常分配 (鐘形曲線)</li><li>市場更新同交易配額重置頻率變2倍 (每小時)</li><li>可以透過交易咗資源嚟解鎖研究</li><li>獨特建築: 功夫館</li><li>獨特建築: 太極館</li><li>可以嘅有效最多玩家交易量多50%</li><li>一開始就多1個自動賣出項目</li><li>獨特政策: 國際出口貿易</li><li>獨特政策：東方之珠</li><li>淨係要4種資源嚟解鎖批發所</li><li>一開始就有100M錢</li>",
    TaiChi10xCultureDescV2: "功夫同太極免費運。電影工作室有2倍產能，但用多50%電",
    SettingsFullScreen: "全螢幕",
    SettingsFullScreenDesc: "用全螢幕模式嚟開遊戲。淨係用喺Steam版",
    LeaderboardByAllPrestigeCurrency: "賺過嘅瑞士錢",
    LeaderboardByCash: "而家有嘅錢",
    LeaderboardTotalValuation: "總估值",
    LeaderboardDescV2: "睇睇頂尖玩家喺邊",
    LastUpdatedAt: "上次更新喺",
    DetroitBonusV3:
        "<li>引擎工廠係解鎖咗</li><li>引擎工廠有2倍產量</li><li>車廠有2倍產能</li><li >車廠用天然氣代替汽油</li><li>免費運車</li><li>尼古拉.特斯拉政策係免費</li><li>火車工廠有2倍產能</li>",
    SaveAndExit: "儲存再退出",
    SaveAndExitDesc: "儲存再退出。呢個淨係用喺Steam版而且同視窗欄上面嘅閂掣一樣",
    AutoSellResourceWarningShortLabel: "💡 自動賣出",
    AutoSellResourceWarningDesc: "您自動賣出緊呢個資源，呢度用唔到喺交易所度儲存嘅",
    PlayerTradeLocalPrice: "本地價格: %{price}",
    ChatForceScroll: "強制郁",
    ChatForceScrollDesc: "如果開咗強制郁，有新訊息嗰陣聊天室都會郁。唔係嘅話淨係喺您已經喺底嗰陣，佢先會郁",
    ResourceExplorer2: "資源探勘者 2.0",
    ConstructionCancel: "取消工程",
    ConstructionPause: "暫停",
    ConstructionResume: "繼續",
    PolicyBlueprint: "藍圖",
    PolicyBlueprintDesc: "建築物唔會自己開始起 — 手動開始 (免費政策",
    HighlightUnderConstruction: "...尚未建造",
    HighlightUnderLevel10: "...低於10級",
    HighlightUnderLevel20: "...低於20級",
    HighlightUnderLevel30: "...低於30級",
    Logout: "您已登出",
    ConstructionStatusQueueingV2: "排隊",
    ConstructionStatusPausedV2: "已暫停",
    ConstructionStatusBuildingV2: "建造",
    ConstructionStatusUnpaidV2: "未付款",
    ConstructionStatus: "施工狀況",
    ConstructionStart: "開始",
    CostFree: "免費",
    PlaceBlueprint: "放置建築藍圖是免費的",
    PlayerTradePriceNotValidV2: "交易價格必須在%{min}和%{max}之間",
    MarketNews: "市場新聞",
    MarketNewsApplyToYou: "只有你",
    MarketNewsApplyToGlobal: "全球的",
    MarketNewsHighlightAffected: "🔍 突出顯示",
    MarketNewsFilterInput: "所有%{res}輸入 ",
    MarketNewsFilterOutput: "所有%{res}輸出 ",
    MarketNewsFilterBoth: "所有%{res}輸入和輸出 ",
    MarketNewsIncrease: "增加了 %{percent}",
    MarketNewsDecrease: "減少了 %{percent}",
    MarketNewsBuilding: "該建築物受到%{num}條新聞的影響",
    StockholmBonusV2:
        "<li>獨特的建築：音樂製作室</li> <li>伐木場有2倍的產量</li> <li>造紙廠已解鎖</li> <li>電路鑄造廠的生產率是2倍</li> <li> 科學文獻政策是免費的</li>",
    FreeOilTransportV2: "電動石油運輸",
    Tutorial4P1:
        "資源運輸消耗燃料。有幾種燃料類型，現在您正在使用<em>汽油⛽</em>作為燃料。 您有一個<em>煉油廠</em>，該煉油廠從油井運出石油並生產汽油。<br> <br>微小的移動點<em>點</em>表示資源的實時移動。 您應該優化建築物的位置，以最大程度地減少行進距離。<br> <br> <em>升級</em>您的建築物將增加其輸出，但同時也會增加其用電量和所需的輸入。",
    Tutorial4P2:
        "您可以在<em>物流部門🚦</em>中更改燃料類型-在此地圖上，您還可以使用<em>天然氣</em>作為燃料。<br> <br>物流部門還會顯示 您消耗最多燃料的運輸路線-您需要隨時注意。<br> <br>請記住<em>確保燃料產量高於消耗量</em>，否則運行時生產會停止 沒油了。<br> <br>如果發生這種情況，請放心，您可以從貿易中心或其他參與者那裡購買一些緊急燃料。",
    Tutorial5P2:
        "<em>統計局📊</em>為您的生產提供了很好的概覽。 您可以看到資源輸入和輸出的詳細分類。<br> <br>還有很多有用的圖表📈-在平衡生產時，您將希望參考它們。<br> </br>您的 左上角還會顯示<em>現金💰，剩餘電量和燃料剩餘⛽</em>編號-如果其中任何一個變為紅色，則應調查情況。",
    MusicProducer: "音樂製作室",
    PlasticFiber: "塑膠光纖",
    PlasticFiberDesc: "光纖工廠使用的塑膠增加50％，玻璃減少50％",
    NewsEffectx2: "新聞發布會",
    NewsEffectx2Desc: "市場新聞的影響加倍，正面和負面",
    SellRefundPercentage: "出售/降級退款",
    SellRefundPercentageDesc: "如果您出售或降級建築物，則這是您退還的現金和資源的百分比",
    SellBuildingDescV2: "出售建築物將退還您投資的%{percent}，並且%{percent}的資源將被運送到貿易中心",
    BuilderMoveSpeed: "工程隊移動速度",
    BuilderMoveSpeedDesc: "工程隊移動到建築目標的速度",
    EBookInc: "電子書公司",
    ResourceBooster: "資源加速器",
    BuildWarningTitle: "建築可能無法正常工作",
    BuildWarningTitleDesc: "%{reason}.您確定要在此地塊上進行構建嗎？",
    BuildWarningBuildAnyway: "確定要建造",
    ResourceBoosterNotWorking: "⛔ 資源加速器僅能在礦山旁邊工作",
    ResourceBoosterBuildings: "建築正在加速",
    BuildingResourceConversion: "%{resource} 轉換",
    AllTimeSwissMoneyEarned: "總體賺取的瑞士貨幣: %{number}",
    BuildingUpgradeCostDivider: "建築升級成本除數",
    AchievementSoftwareGiant: "軟體巨人",
    AchievementSoftwareGiantDesc: "在同一地圖上建立10級軟體公司，10級操作系統公司，10級數據庫公司和10級網頁瀏覽器",
    AchievementSpaceRace: "太空競賽",
    AchievementSpaceRaceDesc: "在同一地圖上建立10級火箭工廠，10級衛星工廠，10級太空船工廠和10級太空站工廠",
    AchievementToTheMoon: "去月球",
    AchievementToTheMoonDesc: "建立40級的比特幣農場和40級的狗狗幣農場。擁有1B比特幣和1B狗狗幣",
    ItsAllGreen: "全是綠色",
    ItsAllGreenDesc: "擁有50條生產線，完全沒有生產赤字",
    DeepInRed: "深陷赤字",
    DeepInRedDesc: "有50條生產線出現生產赤字",
    UseScientificNotation: "使用科學計數法",
    UseScientificNotationDesc: "對大於999.9T的數字使用科學計數法（e計數法）",
    LogoutDescV2: "您已經在另一台設備上登錄，該設備已被登出。 您可以重新登錄，但另一台設備將被登出",
    LogBackIn: "重新登錄",
    PlayerTradeNowAllowedV2: "恢復/導入保存後的％{hour}小時內無法進行玩家交易",
    ServerDisconnected: "您已與服務器斷開連接，請檢查您的網路連接並重新啟動遊戲",
    BuildingUpgradeCostDividerDescV2: "降低升級建築物所需費用",
    ResourceBoosterDesc: "增加相鄰礦場的產出量",
    BlockUserChatTitle: "封鎖 %{user}",
    BlockUserChatAction: "封鎖",
    BlockUserChatDesc: "封鎖會在本次遊戲中持續且無法解除 ,除非重啟遊戲",
    ChangeNameCooldown: "你每次更換名稱需間隔 %{hour} 小時",
    AtomicBombFactory: "原子彈工廠",
    AtomicBomb: "原子彈",
    DynamiteFactory: "炸藥工廠",
    Dynamite: "炸藥",
    NuclearMissileFactory: "核導彈工廠",
    NuclearMissile: "核導彈",
    LiquidPropellantFactory: "液體推進劑工廠",
    GasPropellantFactory: "氣體推進劑工廠",
    Propellant: "推進劑",
    ProjectV2: "V-2 計畫",
    ICBMFactory: "洲際彈道飛彈工廠",
    ICBM: "洲際彈道飛彈",
    RadarFactory: "雷達工廠",
    Radar: "雷達",
    SpaceForceCommand: "太空司令部",
    SpaceForce: "太空軍隊",
    SteamAutoCloudBackupDescV2:
        "你的進度已保存至Steam雲端存檔 並供跨裝置使用. 遊戲也會每10分鐘自動存檔至Steam雲端. 你可以隨時強制存檔",
    SpaceColony: "太空殖民地",
    SpaceColonyInc: "太空殖民局",
    ProjectVostok: "東方計畫",
    AdjacentBonusSquare: "相鄰加成園區",
    AdjacentBonusSquareDesc: "相鄰加成提升50%效能，但板塊增益幅度改為-15%到+15%之間",
    ResourceBoosterSquare: "資源加速園區",
    ResourceBoosterSquareDesc: "資源加速器提供25%額外加成，但科學點消耗量增加25%，用電量增加25%",
    SteelMillx2: "鋼爐現代化",
    SteelMillx2Desc: "煉鋼廠與不鏽鋼廠的容量提高2倍，並使用2倍電力",
    FuelDynamite: "燃料炸藥",
    FuelDynamiteDesc: "炸藥工廠不使用石油，而是選擇使用中的燃料",
    StPetersburgBonusV2:
        "<li>鈾礦場的產量是原來的2倍</li><li>濃縮鈾工廠的容量是原來的2倍</li><li>鈾運輸的燃料成本降低了50％</li><li>槍運輸免費</li><li>東方計畫的容量是原來的2倍</li>",
    ToulouseBonusV2:
        "<li>鈦礦場的產量是原來的2倍</li><li>濃縮鈾工廠的產能是原來的2倍</li><li>噴射引擎工廠的產能是原來的2倍</li><li>飛機工廠的產能是原來的2倍</li><li>火箭工廠的產能是原來的2倍</li>",
    BuildingPermitsNeededDesc: "此建築已停止運作 因您所持有的建築許可證不足",
    BuildingPermitsNeeded: "需要建築許可證",
    BuyMissingPermits: "購齊不足的許可證",
    GPUIsBusy: "您的GPU正處於忙碌中",
    GPUIsBusyDesc: "您的GPU因其他程式而處於高負載 您的作業系統已將遊戲畫面暫停. 您可重整以回到遊戲. 若無效, 請重啟遊戲",
    SaveAndReloadGame: "儲存並重整遊戲",
    ResearchLabCultureInput: "文藝復興",
    ResearchLabCultureInputDesc: "研究實驗室將有2倍的產能，但需要額外消耗文化點作為輸入",
    GasPumpx2Output: "高壓天然氣泵",
    GasPumpx2OutputDesc: "天然氣泵產出增加為原有的2倍，但消耗2倍電力",
    LeaderboardValuationPerHour: "每小時的資產總值估算",
    LeaderboardValuationPerHourPerSwiss: "瑞士幣的每小時資產總值估算",
    LeaderboardValuationPerHourNewPlayers: "每小時總值估算（< 1000 瑞士幣）",
    LeaderboardValuationPerBuilding: "每棟建築物的建築估值",
    BuildingCustomColor: "建築顏色",
    BuildingCustomColorReset: "重置",
    Vancouver: "溫哥華",
    VancouverBonus:
        "<li>每4棟不同類型的建築將額外提供1個免費的建築許可證</li><li>獨特政策：多角化經營</li><li>獨特建築：楓糖漿工廠</li><li>楓糖漿運輸免費</li><li>獨特燃料：楓糖漿</li><li>交易鈾與濃縮鈾時能有2倍的玩家交易額度</li><li>獨特政策：塑化糖漿</li><li>玩具工廠的產出是原有的2倍</li><li>遊戲工作室的產能是原有的2倍</li>",
    MapExtraPermitDesc: "由於地圖獨有的加成，你額外獲得了 %{number} 個免費的建築許可證",
    OsloBonusV3:
        "<li>煉油廠已解鎖</li><li>煉油廠的產能是原來的2倍</li><li>免費的電動石油運輸政策</li><li>天然氣加工廠的產能是原來的2倍</li><li>1座免費的風力發電機</li><li>1座免費的8級鑽油井</li><li>1座免費的2級煉油廠</li><li>1座免費的2級天然氣泵</li>",
    ResourceBoosterPercentageV2: "💡 這數量包含了來自鄰近資源加速器提供的 %{percent} 提升",
    MapleSyrup: "楓糖漿",
    MapleSyrupFactory: "楓糖漿工廠",
    SyrupPlastic: "塑化糖漿",
    SyrupPlasticDesc: "所有輸入塑膠的建築物將改為使用楓糖漿",
    ResourceBoosterSupplyChain: "供應鏈加速器",
    ResourceBoosterSupplyChainDesc:
        "資源加速器除了鄰近的礦場外 也會根據影響中的礦場數 強化鄰近工廠的產能，但工廠的輸入必須與加速中的礦場一致(只輸入庫存資源)，且加速器會消耗2倍電力與科學",
    MapProductionBonusDesc: "由於地圖獨有的加成，這座建築額外獲得 %{percent} 的產能提升",
    ProductionDiversification: "生產多樣化",
    ProductionDiversificationDesc: "每一種不同類型的建築物將使所有建築物提高1%產能",
    ExtraPolicyPointsDescV2: "政策中心的輸入及輸出是原來的2倍",
    PowerRequired: "電力需求",
    AchievementVancouver100: "樹汁賣商",
    AchievementVancouver100Desc: "在溫哥華一次性賺取100瑞士貨幣",
    AchievementVancouver500: "糖漿專家",
    AchievementVancouver500Desc: "在溫哥華一次性賺取500瑞士貨幣",
    AchievementVancouver1000: "加拿大征服者",
    AchievementVancouver1000Desc: "在溫哥華一次性賺取1000瑞士貨幣",
    BarbariansAtTheGate: "門口的野蠻人",
    BarbariansAtTheGateDesc: "在單次的市場更新期間使用了價值1T的玩家交易額度",
    DiversifiedProductions: "生產多樣化",
    DiversifiedProductionsDesc: "單張地圖內擁有100棟不同種類的建築物",
    RealEstateTycoon: "房地產龍頭",
    RealEstateTycoonDesc: "單張地圖內擁有400棟建築物",
    ResourceExplorer2DescV2:
        "資源探勘者輸出提升為2倍，但消耗2倍電力。但同時啟動供應鏈加速器政策的情況下，若是探勘者與加速器相鄰，且探勘者產出的礦產與加速器加速中的礦產是相同類型的話，每一個加速中的礦場，能額外提供一個該類型資源探勘者同樣的提升倍率。",
    NoTileModifier: "地球是平的",
    NoTileModifierDesc: "板塊加成全變為0%. 開啟此政策將關閉自然之力與板塊增益Plus政策",
    DoubleTileModifierDescV2: "所有板塊增益和減益都會變為2倍. 開啟此政策將關閉地球是平的政策",
    TileModifierOutputOnlyDescV2:
        "板塊增益只影響輸出而不增加輸入 但板塊增益降低50%效果. 開啟此政策將關閉地球是平的政策",
    RotterdamBonusV2:
        "<li>煉鋼廠的產能是原來的2倍</li><li>不鏽鋼廠的產能是原來的2倍</li><li>鐵運輸免費</li><li>鋼材運輸燃料消耗減少50%</li><li>開局的自動銷售數量是原來的兩倍</li><li>地球是平的政策免費</li>",
    QuickLinks: "快速連結",
    GetHelp: "尋求幫助",
    GetHelpBeginnerGuides: "新手指南",
    GetHelpSteamGuides: "其他的steam指南",
    GetHelpInGameChat: "在遊戲的聊天視窗中詢問",
    GetHelpDiscord: "加入我們的Discord伺服器",
    GetHelpWiki: "社群維基",
    SelectATile: "選擇一個板塊",
    PledgeAmount: "贊助 %{amount}",
    PledgeValue: "金額 $%{amount}",
    TotalPledgedValue: "總贊助金額",
    TotalPledgedValueDesc:
        "你的第一筆贊助會被算入群眾募資中。隨後額外的贊助將提升你的總贊助金額，但不會被算入群眾募資的總目標中。",
    ReturnOnPledge: "募資回饋",
    ReturnOnPledgeDesc:
        "群眾募資成功的話，這將會是你獲得的回饋。回饋金額的計算方式是依據你的總贊助金額，以及依據你贊助的種類數目所換算出的百分比。",
    CrowdfundingEndIn: "將於 %{time}結束",
    ClaimCrowdfundingReward: "領取回饋 %{amount}",
    ClaimCrowdfundingRefund: "領取退款 %{amount}",
    CrowdfundingUnsuccessful: "本次群眾募資沒有成功，而總贊助金額將會退還給你",
    PledgeSuccessful: "你在本次群眾募資中，總共贊助了 %{amount}",
    CrowdfundingClaimSuccessful: "你領取了 %{amount} 現金",
    CrowdfundingAlreadyPledged: "你已經贊助過了",
    CrowdfundingAlreadyPledgedDesc:
        "你可以贊助更多資源，這將會提升你的總贊助金額(以及潛在收益)，但不會被算入群眾募資的總目標中。",
    WholesaleCenterProducingOnly: "批發合作夥伴",
    WholesaleCenterProducingOnlyDesc:
        "批發市場訂單僅包含目前正在生產的資源（您還需要提供一定數量的資源才能解鎖批發市場）",
    SoftwareCompiler: "軟體編譯器",
    SearchEngine: "搜尋引擎",
    SearchEngineCompany: "搜尋引擎公司",
    Navy: "海軍",
    NavyCommand: "海軍司令部",
    Battleship: "戰艦",
    BattleshipFactory: "戰艦造船廠",
    ResourceMovementHide: "永遠隱藏",
    ResourceMovementShow: "永遠顯示",
    ResourceMovementHighlight: "高亮顯示",
    ResourceMovementLine: "只有線段",
    ResourceMovement: "資源移動",
    ResourceMovementDesc: "你可以選擇何時顯示資源(點)移動，隱藏起來有助於效能提升",
    CrowdfundingCashInWarning: "您尚有未結算的募資贊助 - 從新城市開始將會喪失它們",
    ResourceBoosterBannerDescV2: "💡 您目前傭有 %{number}座資源加速器 - 所費科學輸入量將隨著加速器數量逐步增加",
    CrowdfundingId: "募資計畫 %{id}",
    PatchNotes: "更新記錄",
    PatchNotesDesc: "來看看我們更新了什麼",
    PanelPositionLeft: "靠左 (滯留)",
    PanelPositionLeftFloat: "靠左 (浮動)",
    PanelPositionRight: "靠右 (滯留)",
    PanelPositionRightFloat: "靠右 (浮動)",
    PanelPositionAuto: "自動",
    TimePlayed: "本次場景的遊玩時數",
    ValuationPerHour: "每小時的平均資產增值",
    HighPowerPriority: "優先供電",
    HighPowerPriorityDesc: "開啟此項目可使此建築獲得優先供電",
    IndustryZone: "工業區",
    IndustryZoneDesc: "合併相鄰的建築物，形成供應鏈並節省建築許可證。",
    IndustryZoneMaxBuildingLevel: "最高建築等級",
    IndustryZoneNotWorkingDesc:
        "All of its adjacent buildings should form a supply chain and are not part of other industry zones",
    IndustryZoneNoAdjacentBonus: "This building is part of an industry zone and does not have adjacent bonus",
    PlayerTradeAutoClaim: "自動領取已完成的交易",
    MusifyInc: "Musify 公司",
    WebflixInc: "Webflix 公司",
    CloudStreaming: "Cloud Steaming",
    GameCloudInc: "GameCloud 公司",
    SuperComputerLab: "超級電腦實驗室",
    SuperComputer: "超級電腦",
    SkyNetInc: "天網(SkyNet) 公司",
    SkyNet: "天網(SkyNet)",
    RobocarFactory: "無人駕駛汽車工廠",
    Robocar: "無人駕駛汽車",
    WarehouseBuildingPermitSave: "Warehouse Permit Act",
    WarehouseBuildingPermitSaveDesc: "Every two warehouses provide one free building permit",
    PolicySearchPlaceholder: "Type a policy name to search",
    SwissUpgrade: "Swiss Upgrade",
    SwissUpgradeDesc: "Swiss upgrades are permanent and will carry over if you start in a new city",
    SwissBoost: "Swiss Boost",
    SwissBoostDesc: "Swiss boosts only affect your current run - and will reset if you start in a new city",
};
