export const ZH_HK = {
    Translator: "翻譯人員",
    TranslatorName: "Bencheung0422",
    Language: "語言",
    ThisLanguage: "粵語中文",
    OK: "確定",
    SteelMill: "煉鋼廠",
    StainlessSteelPlant: "不鏽鋼廠",
    CircuitFoundry: "電路工廠",
    IntegratedCircuit: "集成電路",
    OilWell: "油井",
    Wood: "原木",
    LoggingCamp: "伐木場",
    LumberMill: "鋸木廠",
    Lumber: "木材",
    Paper: "紙張",
    PaperMill: "造紙廠",
    Book: "書",
    BookPublisher: "圖書出版商",
    OilRefinery: "煉油廠",
    Sell: "賣出",
    Upgrade: "升級",
    Build: "建造",
    Inspect: "檢查",
    Buildings: "建築物",
    Iron: "鐵",
    Actions: "行動",
    FuelType: "燃料種類",
    FuelCost: "燃料成本",
    FuelConsumption: "%{fuel}消耗",
    FuelEconomy: "燃料效率",
    FuelProduction: "%{fuel}產量",
    FuelInStorage: "%{fuel}儲緊",
    Plastic: "塑膠",
    FuelSurplus: "%{fuel}盈餘",
    Petrol: "汽油",
    Buy: "買入",
    NoLiquidity: "無流通性",
    NoLiquidityTurnOffAutoSell: "唔夠市場流通性，得%{res}，閂咗自動賣出。",
    Multiplier: "倍率",
    MultiplierDesc: "每10級+1倍率",
    SellBuilding: "賣建築物",
    PowerGrid: "電網",
    TradeAmount: "交易量",
    SortBy: "排喺",
    SortByPrice: "價錢",
    SortByAmount: "數量",
    NotEnoughResourcesForTrade: "交易所唔夠資源用喺呢個交易",
    NotEnoughResources: "唔夠資源嚟做呢個操作",
    Transportation: "交通系統",
    Cash: "錢",
    Aluminum: "鋁",
    ResearchPoint: "研究點",
    Unlock: "解鎖",
    BuildingUnlocked: "解鎖咗%{building}",
    Science: "科學",
    ScienceFromPowerDesc: "發電廠發電嗰陣會產生少少科學點",
    Culture: "文化",
    School: "學校",
    University: "大學",
    Polytechnic: "理工學院",
    Colosseum: "羅馬競技場",
    WindTurbine: "風力發電機",
    Engine: "引擎",
    EngineFactory: "引擎工廠",
    CameraFactory: "相機工廠",
    Camera: "相機",
    Gun: "槍",
    GunFactory: "槍廠",
    Aircraft: "飛機",
    AircraftFactory: "飛機工廠",
    Zeppelin: "齊柏林飛船",
    ZeppelinFactory: "齊柏林飛船工廠",
    Tank: "坦克",
    TankFactory: "坦克工廠",
    CoalPowerPlant: "燃煤發電廠",
    PetrolPowerPlant: "燃油發電廠",
    Copper: "銅",
    Gas: "天然氣",
    GasPump: "天然氣泵",
    GasPowerPlant: "燃氣發電廠",
    Missile: "導彈",
    MissileFactory: "導彈工廠",
    Rocket: "火箭",
    RocketFactory: "火箭工廠",
    BuildingPermit: "建築許可證",
    BuildingPermitDesc: "您一共有 %{amount}份許可證可以用喺建築物，您已經起咗%{amountBuilt}間，仲可以起%{amountLeft}座",
    BuildingLocked: "呢個建築仲未用得，您要喺研究實驗室度解鎖先",
    BuildQueue: "建築隊",
    BuildQueueDesc: "而家排緊隊嘅建築量",
    MaxBuilders: "最大工程隊量",
    MaxBuildersDesc: "您同時起到嘅建築量",
    Silicon: "矽",
    AluminumMine: "鋁礦場",
    CopperMine: "銅礦場",
    SiliconMine: "矽礦場",
    IronMine: "鐵礦場",
    CoalMine: "煤礦場",
    Headquarter: "總部",
    ResearchLab: "研究實驗室",
    TradeCenter: "交易所",
    Resources: "資源",
    NotEnoughPower: "💡 唔夠電，考慮加多啲發電量",
    NotEnoughFuel: "唔夠%{fuel} 嚟做呢個操作",
    NotEnoughCash: "唔夠錢嚟做呢個操作",
    NotEnoughSwissMoney: "唔夠瑞士錢嚟做呢個操作",
    BuildingNotEnoughFuel: "💡 唔夠%{fuel}",
    AutoSell: "自動賣出",
    SellAll: "全部賣出",
    Change: "更改",
    StatisticsBureau: "統計處",
    LogisticsDepartment: "物流部",
    From: "喺",
    Top20FuelCost: "燃料成本前20",
    To: "去到",
    TransportTime: "運輸時間",
    TopN: "前 %{n}",
    Warehouse: "倉庫",
    TradeWarehouse: "交易倉庫",
    Coal: "煤",
    Video: "影片",
    ClothingFactory: "整衫廠",
    Clothes: "衫",
    Fashion: "時裝",
    FashionFactory: "時裝工廠",
    VideoFarm: "影片農場",
    SantaFactory: "聖誕老人工廠",
    Santa: "聖誕老人",
    Car: "車",
    CarFactory: "車廠",
    Ship: "船",
    SolarPanel: "太陽能板",
    SolarPanelDesc: "💡 太陽能板每10秒郁5秒 — 全部運作周期齊",
    WindTurbineDesc: "💡 風力發電機每10秒郁8秒 — 運作周期唔齊",
    Movie: "電影",
    MovieStudio: "電影工作室",
    Sitcom: "電視劇",
    TVStudio: "電視節目工作室",
    PC: "電腦",
    GameStudio: "遊戲工作室",
    Game: "遊戲",
    ComputerFactory: "電腦工廠",
    Shipyard: "船廠",
    PowerUsage: "用電量",
    PowerSupply: "發電量",
    PowerSurplus: "電盈餘",
    Level: "等級",
    Power: "電",
    CentralBank: "中央銀行",
    ResourceInput: "輸入",
    ResourceOutput: "輸出",
    ResourceStorage: "存庫",
    ResourceChange: "變化",
    ResourceInOutDesc: '💡 撳喺"輸出-輸入"上面嘅數字，嚟顯示同輸出輸入有關嘅建築物',
    ResourceChart: "資源圖表",
    MarketUpdateIn: "市場喺%{time}之後更新",
    Income: "收入",
    Semiconductor: "半導體",
    SemiconductorFactory: "半導體工廠",
    Steel: "鋼",
    Bitcoin: "比特幣",
    BitcoinFarm: "比特幣農場",
    Dogecoin: "狗狗幣",
    DogecoinFarm: "狗狗幣農場",
    Guitar: "吉他",
    GuitarFactory: "吉他工廠",
    Drum: "鼓",
    DrumFactory: "鼓廠",
    RecordingStudio: "音樂工作室",
    OperaHouse: "歌劇院",
    CoalGasificationPlant: "煤氣化廠",
    GasProcessingPlant: "天然氣處理廠",
    Music: "音樂",
    Glass: "玻璃",
    PhoneFactory: "手機工廠",
    Phone: "手機",
    GlassFactory: "玻璃工廠",
    Oil: "石油",
    Chromium: "鉻",
    ChromiumMine: "鉻礦場",
    Uranium: "鈾",
    EnrichedUranium: "濃縮鈾",
    NuclearPowerPlant: "核電廠",
    UraniumEnrichmentPlant: "濃縮鈾廠",
    UraniumMine: "鈾礦場",
    Titanium: "鈦",
    TitaniumMine: "鈦礦場",
    TitaniumAlloyPlant: "鈦合金廠",
    ChromiumAlloyPlant: "鉻合金廠",
    Input: "輸入",
    PanelPosition: "面板位",
    PanelPositionDesc: "將控制面板擺喺左右邊或者自動 (取決喺揀嘅位)",
    InputCapacity: "輸入量",
    InputCapacityPerCycle: "輸入量/周期",
    Output: "輸出",
    OutputCapacity: "輸出量",
    OutputCapacityPerCycle: "輸出量/周期",
    ResourceDeposit: "資源床",
    RecommendedBuilding: "💡 呢度有%{resource}蘊藏",
    AdjacentBonus: "相鄰加成",
    AdjacentBonusDesc: "每棟相鄰同類型郁緊嘅建築會有%{bonus}%額外產量",
    ConsiderIncreaseProduction: "💡 考慮加多啲%{resource}產量",
    AlwaysTransportInput: "儲存模式",
    AlwaysTransportInputTradeCenter: "一直儲",
    AlwaysTransportInputTradeCenterDesc: "一直將資源送到交易所，就算嗰個資源冇開自動賣出",
    AlwaysTransportInputDesc: "一直入資源，就算佢哋高過最低生產要求",
    ProductionCycleLength: "生產周期",
    ProductionCycleLengthDesc: "一個生產周期嘅時間，用秒計。加長周期會加每個周期嘅輸出入嚟到降低攞資源輸入嘅優先度",
    MaxInputDistance: "最長輸入距離",
    MaxInputDistanceDesc: "呢棟建築用版塊量計輸入資源嘅最長距離",
    AutoSellCapacity: "自動賣出量",
    AutoSellCapacityDesc: "自動賣出每種資源每秒處理到嘅最大資源量",
    CurrentAutoSellCapacityMultiplier: "而家倍率: x%{n}",
    AutoSellConcurrency: "同時自動賣出量",
    AutoSellConcurrencyDesc: "自動賣出同時處理到嘅最大資源量",
    MaxAutoSellConcurrencyReached: "您已經去到最大同時自動賣出量，閂咗另一個自動賣出嚟開呢個",
    CannotSellBuilding: "而家唔可以賣呢個建築物",
    WallStreet: "華爾街",
    MarketCap: "市值",
    MarketCapDesc: "您公司嘅緦市值(如市場價值)",
    BuildingValuation: "建築估值",
    BuildingValuationDesc: "您全部建築嘅總價值，包括建築許可證同升級",
    ResourcesValuation: "資源估值",
    ResourcesValuationDesc: "庫存資源總價值",
    Battery: "電池",
    BatteryFactory: "電池工廠",
    RatingBuy: "買入",
    RatingSell: "賣出",
    SwissShop: "瑞士鋪",
    RatingHold: "保住",
    RatingOutperform: "表現優異",
    RatingUnderperform: "表現唔好",
    StockRating: "股票評級",
    JetEngine: "噴射引擎",
    Helicopter: "直升機",
    Lithium: "鋰",
    LithiumMine: "鋰礦場",
    LiionBatteryFactory: "鋰電池工廠",
    HelicopterFactory: "直升機工廠",
    Satellite: "衛星",
    ToyFactory: "玩具工廠",
    Toy: "玩具",
    SpaceStation: "太空站",
    SpaceStationFactory: "太空站工廠",
    OperatingSystem: "作業系統",
    OperatingSystemCompany: "作業系統公司",
    LinuxDistribution: "Linux 發行版",
    Internet: "互聯網",
    WebBrowser: "網頁瀏覽器",
    Console: "遊戲機",
    ConsoleFactory: "遊戲機工廠",
    Train: "火車",
    TrainFactory: "火車工廠",
    ShoeFactory: "鞋廠",
    Shoes: "鞋",
    ArtilleryFactory: "大炮工廠",
    Artillery: "大炮",
    SubmarineFactory: "潛水艇工廠",
    Submarine: "潛水艇",
    Spaceship: "太空船",
    RobotFactory: "機器人工廠",
    Robot: "機器人",
    SpaceshipFactory: "太空船工廠",
    SatelliteFactory: "衛星工廠",
    JetEngineFactory: "噴射引擎工廠",
    StockRatingDesc: "嚟自華爾街分析師嘅股票評級共識，佢會影響您嘅市值而且一齊同市場更新",
    InterestRate: "過夜利率",
    InterestRateDesc: "您喺離線嗰陣用市值賺到嘅收入",
    OfflineEarning: "離線收入",
    PerMin: "%{amount}/分鐘",
    OfflineEarningTime: "離線賺錢時間",
    OfflineEarningTimeDesc: "您攞到離線收入嘅時間",
    BuyPermit: "買許可證",
    NotEnoughBuildingPermit: "唔夠建築許可證，買多啲嚟起新嘅建築",
    MovingAverage: "平均變化",
    MovingAverageDesc: "顯示資源變化嘅平均值而唔係即時變化",
    AllowZoom: "縮放",
    AllowZoomDesc: "打開縮放支援。用滑鼠滾輪嚟縮放。而家嘅縮放率係%{zoom}",
    AllowZoomMobileDesc: "打開縮放支援。用手指嚟縮放。而家嘅縮放率係%{zoom}",
    Settings: "設定",
    Sound: "音效",
    SoundDesc: "打開音效，如撳掣或者出錯嘅聲",
    AutoHighlight: "自動突顯",
    AutoHighlightDesc: "喺您揀建築嗰陣，會自動突顯一樣嘅建築",
    MusicDesc: "打開音樂: Shane Ivers (https://www.silvermansound.com)嘅《It's Not Over 'Til The Bossa Nova》",
    Credits: "鳴謝",
    Icons: "圖標",
    MisplacedBuilding: "⛔ 呢個%{building}冇擺喺啱嘅資源床度",
    HighlightBuildings: "突顯建築",
    HighlightTurnedOff: "...閂咗嘅",
    HighlightStockpileModeOn: "...開咗庫存模式嘅",
    HighlightProductionCycleNotDefault: "...生產周期 > 1嘅",
    HighlightMaxInputDistanceNotDefault: "..最長輸入距離 < ∞嘅",
    HighlightNotMakingProfit: "...唔盈利嘅",
    NBuildingsAreHighlighted: "%{n}個建築物被突顯",
    OnlyToWarehouse: "淨係送到倉庫",
    OnlyToWarehouseDesc: "得倉庫先可以喺呢座建築度送資源",
    TurnOffProduction: "閂",
    TurnOffProductionDesc: "閂建築嘅生產。佢唔會再送資源同用電",
    ApplyToAll: "套用喺全部%{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "無限",
    Transport: "運送",
    TileModifier: "板塊加成",
    ShowAllModifiers: "顯示全部板塊加成",
    HideAllModifiers: "收埋全部板塊加成",
    NumberOfBuildings: "您有嘅建築量",
    ShowContent: "顯示內容",
    HideContent: "收埋內容",
    BuyExpansionPack: "用%{price}買",
    Cities: "城市",
    InputStrategy: "輸入策略",
    InputStrategyClose: "近啲",
    InputStrategyCloseDesc: "揀最近而且夠資源嘅倉庫",
    InputStrategyFar: "遠啲",
    InputStrategyFarDesc: "揀最遠而且夠資源嘅倉庫",
    InputStrategyAmount: "量",
    InputStrategyAmountDesc: "就算距離係點，都係最多資源嘅倉庫先",
    FuelCostSave: "慳燃料",
    FuelCostSaveDesc: "同其他建築比，倉庫慳一定比例嘅燃料嚟送資源，越高級慳越多",
    SoftwareCompany: "軟件公司",
    Software: "軟件",
    ScreenFactory: "螢幕工廠",
    Screen: "螢幕",
    JoinDiscord: "加入我哋嘅Discord伺服器嚟攞到最新更新、技巧資訊同討論",
    ClaimOfflineEarning: "攞離線收入",
    OfflineTime: "離線時間",
    Minutes: "%{time}分鐘",
    MaxUpgrade: "最高級",
    MaxUpgradeDesc: "您已經去到最高級",
    ClaimAmount: "錢 +%{amount}",
    EffectiveTime: "有效時間",
    EffectiveTimeDesc: "您嘅有效離線收入時間唔超過 %{time}分鐘",
    BuildSearchPlaceholder: "打要搵嘅建築或者資源",
    MineOverlayWarning: "%{building} 唔受板塊加成影響",
    WholesaleCenter: "批發所",
    OrderFrom: "嚟自 %{name} 嘅訂單",
    ExpireIn: "到期",
    TurnOnAllProductions: "生產開始",
    TurnOnAllProductionsDesc: "打開全部建築物生產，喺開緊「摼成本」政策嗰陣用唔到",
    OperationSuccessful: "呢個操作搞掂咗",
    TurnOn: "打開",
    Reward: "獎勵",
    PerSecond: "%{time}/秒",
    PerCycle: "%{amount}/周期",
    PolicyPoint: "政策點",
    PolicyPointPerMinute: "生產速率",
    PolicyPointPerMinuteDesc: "您喺遊戲度每分鐘都會攞到政策點",
    YourWilLGaimPolicyPoints: " 您喺{time}秒之後會攞到%{amount}個政策點",
    PolicyPointDesc: "💡 開越多政策，每個政策成本就越多",
    NextOrderIn: "下一個訂單仲要",
    FillOrder: "成交",
    RejectOrder: "跳過",
    WholesaleCenterLocked: "您至少要%{required}種唔同嘅資源嚟解鎖批發所。您得%{current}種資源",
    OrderFilled: "嚟自 %{from} 嘅訂單成交咗！",
    PolicyCenter: "政策中心",
    NewOrder: "嚟自 %{from} 嘅新訂單到咗，喺批發所度睇睇",
    Policies: "政策",
    PolicyNotEnoughTime: "您唔夠政策點嚟開呢個政策",
    TimeLeft: "得返 %{time}",
    WholesaleCenterOrderFasterDesc: "批發所收訂單會快2倍同大2倍",
    PolicyOilWellPowerx2: "加壓油井",
    PolicyOilWellPowerx2Desc: "油井生產2倍石油同用2倍嘅電",
    HalfTransportSpeed: "送慢啲慳啲",
    HalfTransportSpeedDesc: "運送速度慢25%同埋燃料成本少25%",
    RefineryMoreOil: "多啲汽油多啲問題",
    RefineryMoreOilDesc: "煉油廠生產多50%汽油同少50%塑膠",
    StickyInput: "穩定輸入",
    StickyInputDesc: "建築會傾向以前嘅來源，而唔係每個周期都揾最好嘅來源 (免費政策)",
    RefineryMorePlastic: "多啲塑膠多啲問題",
    RefineryMorePlasticDesc: "煉油廠生產少50％汽油同多50％塑膠",
    FreeOilTransportDesc: "運石油唔使用燃料，但油井用電量係原本嘅2倍",
    SuperSteelMill: "鋼鐵雄心",
    SuperSteelMillDesc: "煉鋼廠用少50％煤、多25％鐵同多25％電",
    AlSemiconductor: "鋁電路",
    AlSemiconductorDesc: "電路板工廠用鋁代替銅",
    CostSaver: "慳成本器",
    CostSaverDesc: "如果建築嘅輸入成本大過輸出，就停咗佢",
    CostSaverBuildingDesc: "慳成本器政策開咗，生產會跟佢嘅獲利能力嚟自動開閂",
    CostSaverBuildingWarning: "慳成本器政策開咗，您冇得手動改",
    GlassUseCoal: "黑玻璃",
    GlassUseCoalDesc: "玻璃工廠用多50％煤同少50％矽",
    AdjacentBonusOnlyOutput: "鄰近加成+",
    AdjacentBonusOnlyOutputDesc: "鄰近加成唔使多啲輸入，但係要用多啲電而且得50％效率",
    IronMine2xOutput: "重鐵",
    IronMine2xOutputDesc: "鐵礦場產生2倍鐵，但送鐵用2倍燃料",
    SolarPanelAlwaysWork: "太陽唔落山",
    SolarPanelAlwaysWorkDesc: "太陽能板喺100％時間做，但產少60％電",
    SteelScience: "知識穿透鋼",
    SteelScienceDesc: "煉鋼廠用2倍輸入同產生額外科學",
    ShoppingSpree: "瘋狂買嘢",
    ShoppingSpreeDesc: "如果資源唔夠輸出量，就喺交易所度自動買入缺嘅 (如果嗰啲資源有開自動賣出，就會被忽略)",
    ShoppingSpreeTradeCenterDesc: "💡 瘋狂買嘢政策開咗，交易所會自動買缺嘅資源",
    ExtraPolicyPoints: "政治說客",
    CrAlloyUseFe: "鉻鐵合金",
    CrAlloyUseFeDesc: "鉻合金工廠唔用鋰，反而係用2倍鐵",
    DoubleTileModifier: "大自然嘅力量",
    TileModifierOutputOnly: "板塊加成+",
    GasPlantPetrol: "天然氣液化器",
    GasPlantPetrolDesc: "天然氣發電廠用額外天然氣嚟產生汽油",
    BuildingRecycle: "建築回收",
    BuildingRecycleDesc: "喺起咗之後1分鐘度賣咗佢就可以全數退晒",
    CoalPlantFuel: "煤液化器",
    CoalPlantFuelDesc: "燃煤發電廠用額外煤嚟生產汽油",
    Welcome: "歡迎",
    SeeTutorialAgain: "再教學",
    HelpTranslateTheGame: "幫手翻譯遊戲🌐",
    SkipTutorial: "跳過教學",
    NextTutorial: "下一個",
    Tutorial1:
        "閒置工業係一隻<em>資源管理</em>遊戲，您可以起工廠🏭、生產商品📦同賺錢💸。<br><br>一齊嚟透過一啲基本概念嚟俾您開始 — 唔會好耐，我保證。",
    Tutorial2:
        "全部建築物都要電⚡，您有一個<em>風力發電機</em>嚟發電。您可以喺上面嘅左邊睇到而家嘅電供應。<br><br>您可能注意到風力發電機淨係郁<em>80%</em>時間。您可以考慮起其他種發電廠嚟發穩定嘅電。",
    Tutorial3:
        "您喺地圖度有好多<em>資源床</em>。要攞資源，您要喺對應嘅資源床<em>上面</em>起礦場⛏️。<br><br>例如，您有座<em>油井🛢️</em>喺油田度抽<em>石油</em>。<br></br>資源蘊藏量係無限嘅 — 唔使擔心佢哋會用晒。除咗礦場，其他建築都可以起喺任何空格度",
    Tutorial5:
        "要賺錢，您要喺交易所度出口您嘅資源。要咁做，淨係要打開資源嘅<em>自動賣出</em>。<br></br>仲有您都可以喺交易所度買資源。記住<em>如果您買資源，就會提高佢個價格</em>同埋如果您賣資源，就會降低佢個價格。<br><br>市場<em>變動大</em>而且價格📈會定時變。",
    Tutorial6:
        "要起新建築，您要喺<em>研究實驗室🧪</em>度解鎖佢先。研究實驗室仲會將科學轉成研究點。<br><br>您嘅風力發電機(同其他發電廠)喺郁嗰陣會產生少少科學。而且您之後可以起學校🏫同其他專用建築嚟加速科學.<br><br>而家您了解咗全部基礎，開始建立您嘅經濟！呢度有啲<em>錢💸</em>同<em>汽油⛽</em>嚟俾您一個跳躍嘅開始。",
    WelcomePlay: "開始遊戲",
    WelcomePlayMuted: "開始遊戲 (🔇音樂)",
    Chat: "傾偈",
    Send: "送出",
    Import: "匯入",
    Export: "匯出",
    LastBackupAt: "最後備份",
    RestoreFromBackup: "喺備份度還原",
    RestoreFromBackupFail: "冇得喺Steam Cloud度還原備份: 您真係有備份？",
    RestoreFromBackupTitle: "真係？",
    RestoreFromBackupDesc: "通常您都唔使喺雲端備份度還原，除非唔見咗本機存檔。雲端備份會舊過本機存檔少少",
    ChatMessages: "傾偈訊息",
    ChangeName: "改名",
    SaveName: "儲存",
    NameValidationRule: "您嘅名淨係可以有字母同數字而且長度係喺5至15粒字",
    NameValidationRuleProfanity: "您嘅名唔應該包含違規嘅字",
    ChatMessageRateLimit: "您淨係可以每10秒送一次新訊息",
    NameSaved: "您嘅名成功改好咗",
    NoMessages: "冇新訊息",
    Leaderboard: "排行榜",
    Name: "名",
    Rank: "排名",
    Tips1: "股票評級有5級: 買入、表現好好、保持、表現唔好同賣出",
    Tips2: "如果夠生產，建築就會停運資源，除非您開咗儲存模式",
    Tips3: "資源運輸嘅燃料成本決定喺距離同資源量",
    Tips4: "如果喺地圖度搵到嘅量多過輸入量，建築就淨係會運資源",
    Tips5: "如果嗰啲資源閂咗自動賣出，建築就淨係會喺交易所度運資源",
    Tips6: "您可以喺相應輸入量部分下面睇到資源嘅燃料成本",
    Tips7: "如果您買資源，會提高佢個價格。如果您賣資源，會降低佢個價格",
    Tips8: "您可以喺統計局度睇到每種資源嘅量同變化嘅圖表",
    Tips9: "建築要嘅研究點決定喺輸入資源嘅市場價",
    Tips10: "唔同嘅資源喺市場嘅定價都唔同 — 一定要為市場波動做好準備",
    Tips11: "喺擴展生產之前，最好檢查吓電同燃料供應",
    FPS30: "慳電",
    OfflineModeDesc: "連唔到伺服器: 唔會產生離線收入。請檢查您嘅網路連接",
    OptOut: "揀退出",
    OptIn: "重設再開過",
    LeaderboardOptOut: "退出排行榜",
    LeaderboardOptOutDesc: "呢個唔會再送排行榜分。注意: 如果之後要開返排行榜，就要重設您嘅數據",
    LeaderboardOptIn: "重設再開過排行榜",
    LeaderboardOptInDesc: "您嘅數據重設咗先可以再開返排行榜，真係要？",
    RewardAdsFailed: "獎勵廣告未完",
    RewardAdsNotAvailable: "獎勵廣告冇得用 (而家淨係支援iOS/Android)",
    OfflineEarningDoubleSuccess: "您嘅離線收入多咗一倍",
    FPS30Desc: "打開慳電模式會令遊戲用30FPS代替60FPS嘅更新率嚟郁。會令您用耐啲電池",
    HighlightAll: '突出顯示 "%{type}"',
    HighlightInput: "🔍 突出顯示 %{type}輸入",
    HighlightOutput: "🔍 突出顯示 %{type}輸出",
    TotalInput: "總輸入量",
    TotalOutput: "總輸出量",
    RunOutIn: "%{time}之後會用晒",
    FuelRunOutWarning: "💡 您嘅燃料消耗多過生產。喺燃料用晒嗰陣，您嘅運輸會停",
    InAmount: "輸入: %{number}",
    OutAmount: "輸出: %{number}",
    SwissBank: "瑞士銀行",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "如果您喺新城市開始，您會攞到 %{money} 💵",
    RestorePurchases: "恢復購買",
    RestorePurchasesSuccess: "您嘅購買恢復咗",
    RestorePurchasesFailed: "您嘅購買未恢復",
    ExpansionPacks: "擴展包",
    ExpansionPack1: "擴展包1",
    ExpansionPack1Owned: "擴展包1",
    RequireExpansionPack1: "擴展包1",
    RequireExpansionPack1Desc: "呢個淨係用喺擴展包1",
    RequireAnyExpansionPack: "獨家擴展包",
    RequireAnyExpansionPackDesc: "呢個功能要您至少有一個擴展包",
    HideRewardAd: "收埋獎勵廣告",
    HideRewardAdDesc: "全部喺遊戲入面嘅廣告都係有得揀嘅獎勵廣告。呢個會喺遊戲度收埋晒佢哋嘅選項。",
    HideDiscordBanner: "收埋Discord橫幅",
    HideDiscordBannerDesc: "收埋總部嘅Discord同舖頭橫幅",
    HideChat: "收埋傾偈訊息",
    SortedByDeficit: "按損失排",
    PurchaseFailed: "未買好",
    PurchaseSteamContinue: "請喺Steam度買好",
    PurchaseSuccess: "買好咗，多謝您嘅支持",
    PrestigeCurrency: "瑞士錢 💵",
    RestartDesc: "💡 想重新嚟過？您可以撳上面嘅喺新城市開始同揀您而家嘅城市",
    PrestigeGoBack: "返轉頭",
    ProductionMultiplier: "生產倍率",
    ProductionMultiplierDesc: "提高您全部建築嘅產量 (包括礦場、工廠、發電廠、科學同文化建築)",
    FuelCostDiscount: "燃料成本折扣",
    FuelCostDiscountDesc: "喺運資源個嗰陣俾燃料成本折扣",
    AutoSellCapacityMultiplier: "自動賣出量倍率",
    AutoSellCapacityMultiplierDesc: "就算而家嘅量係點，都會用落您嘅自動賣出量嘅倍率",
    BuildingPermitCostDivider: "建築許可證成本折扣",
    BuildingPermitCostDividerDesc: "建築許可證成本被呢個折扣折",
    ExtraAdjacentBonus: "額外相鄰加成",
    ExtraAdjacentBonusDesc: "每個相鄰同類型郁緊建築嘅額外加成量",
    OfflineEarningMultiplier: "離線收入倍率",
    OfflineEarningMultiplierDesc: "用喺離線收入嘅倍率",
    PrestigeAlertTitle: "真係？",
    PrestigeAlertContent: "您嘅公司會被清算。您會有 %{amount}瑞士錢而且喺 %{city}成立新公司",
    PrestigeCurrencyDesc: "呢個係您喺秘密瑞士銀行帳戶嘅錢，您可以帶埋佢喺一個新城市重新嚟過",
    Prestige: "過數",
    Cancel: "取消",
    SaveFileCorrupted: "存檔壞咗",
    CheatDetected: "您嘅舊存檔未俾伺服器驗證，用唔到。您會喺新存檔度開始",
    LoadGameError: "入唔到遊戲",
    LoadGameErrorMessage: "錯誤: %{message}",
    LoadGameErrorDesc: "請檢查您嘅網路連線。如果問題仲喺度，請聯絡客服人員",
    ExpansionPackIncompatible: "您匯入緊擴展包存檔，但您嘅遊戲冇需要嘅擴展包",
    SaveFileMigrated: "新時代: Beta喺度",
    SaveFileMigratedDesc: "多謝您玩測試alpha。您嘅舊地圖唔相容，但係我哋搬咗您嘅數據同俾咗您一啲加成",
    ClaimSwissMoney: "攞 %{amount}瑞士錢 💵",
    SaveFileMigratedFinePrint:
        "您嘅市值轉咗去瑞士錢，未用嘅瑞士錢轉埋。您會攞多50％瑞士錢係玩測試alpha嘅。瑞士錢最多轉200",
    CashIn: "過數",
    CurrentCity: "而家嘅城市",
    CashInDesc:
        "如果您喺新城市開始，就會就會攞到呢個量喺您嘅瑞士銀行戶口。呢個係喺基於您公司嘅市值而且要有%{amount}喺您賺到瑞士錢之前",
    MoveToNewMap: "喺新城市開始",
    CityName: "城市",
    CitySize: "地圖大細",
    GridType: "網格類型",
    StartInThisCity: "喺%{city}開始",
    CityBonus: "城市加成",
    ResourceTilePercentage: "資源格",
    MapSquareGrid: "正方形",
    MapHexGrid: "六邊形",
    Stockholm: "斯德哥爾摩",
    Rotterdam: "鹿特丹",
    Oslo: "奧斯陸",
    StPetersburg: "聖彼得堡",
    Hamburg: "漢堡",
    HamburgBonus:
        "<li>齊柏林飛船工廠解鎖咗</li><li>半導體工廠有2倍產能</li><li>船廠有2倍產量</li><li>車廠有2倍產量</li><li>鋰電池工廠解鎖咗</li>",
    Toulouse: "圖盧茲",
    Rome: "羅馬",
    RomeBonus:
        "<li>羅馬競技場解鎖咗</li><li>羅馬競技場有2倍產能</li><li>一開始有5級政策中心</li><li>歌劇院有2倍產量</li><li>錄音工作室會產生文化</li>",
    Detroit: "底特律",
    Boston: "波士頓",
    BostonBonus:
        "<li>一開始有5級研究實驗室</li><li>理工學院解鎖咗</li><li>理工學院有2倍產量</li><li>學校有2倍產量</li><li>大學有2倍產能</li>",
    HideNotProducing: "收埋冇生產嘅資源",
    SortByStorage: "存量",
    SortByProduction: "產量",
    SortByName: "名",
    PlayerTrade: "玩家交易",
    AddTradeFail: "加唔到您嘅交易",
    AddTradeExceedMaximumTrade: "您最多淨係可以有 %{number}單交易緊，攞或者取消其中一個先",
    AddTradeSuccess: "您嘅交易成功加咗",
    LoadTradeFail: "入唔到玩家交易，請等陣再試",
    ClaimTradeFail: "攞唔到呢個交易，請等陣再試",
    CancelTradeSuccess: "您嘅交易成功取消咗",
    CancelTradeFail: "取消唔到呢個交易，請等陣再試",
    AcceptTradeFail: "接受唔到呢個交易，請等陣再試",
    PlayerTradeBanner: "同其他玩家交易資源",
    PlayerTradeResource: "資源",
    PlayerTradeAmount: "量",
    PlayerTradePrice: "價錢 $",
    PlayerTradeValue: "價值 $",
    PlayerTradeWaiting: "等緊...",
    UseTradeCenterPrice: "用交易所價格",
    AddTrade: "加交易",
    ActiveTrades: "交易緊",
    AcceptTrade: "接受",
    CancelTrade: "取消",
    RefundTrade: "退款",
    RefundTradeSuccess: "呢個交易退咗款: %{resource}退返俾您嘅交易所",
    RefundTradeFail: "退款唔到呢個交易，請等陣再試",
    ClaimTrade: "攞",
    RefreshTrade: "更新",
    PasteYourSave: "請貼上您嘅存檔數據",
    FailedToImportSave: "匯入唔到存檔",
    FailedToImportSaveDesc: "您嘅存檔唔相容或者壞咗: %{error}",
    SaveCopiedToClipboard: "您嘅存檔數據複製咗落您嘅剪貼簿",
    CancelActiveTradeFirst: "您有做緊嘅玩家交易，取消/攞咗佢哋先",
    FailedToCheckActiveTrade: "檢查唔到做緊嘅玩家交易，請等陣再試",
    PlayerTradeQuotaExceed: "呢個交易多過您嘅配額",
    PlayerTradeValidRange: "範圍: %{min} ~ %{max}",
    PlayerTradeFilterCanAfford: "買到",
    PlayerTradeQuota: "配額得返: %{value}",
    PlayerTradeUnavailable: "喺同玩家交易之前，你要至少有一個資源喺生產同存庫度",
    PlayerTradeToClaim: "您有 %{num}單玩家交易仲未攞",
    PowerBank: "蓄電池",
    PowerBankBuildDesc: "儲多出嚟嘅電同喺唔夠電嗰陣放電",
    WarehouseBuildDesc: "用少啲燃料成本運同儲任何資源",
    PowerBankChargeSpeed: "充電速度",
    PowerBankPowerLeft: "電得返",
    PowerBankMoreCapacity: "慳電池器",
    PowerBankMoreCapacityDesc: "蓄電池充電50%速度但有多50%量",
    PowerBankNotWorking: "⛔ 蓄電池黐實發電廠嗰陣先有用",
    ExcludeBuildingsShutdown: "除咗被閂咗嘅建築",
    ColorTheme: "顏色主題",
    ColorThemeDesc: "顏色主題用喺遊戲圖標、突出顯示、網格同背景。要重新開過",
    SiliconMine2xOutput: "矽谷",
    SiliconMine2xOutputDesc: "矽礦場生產2倍矽但用多50%電同運矽用多50%燃料",
    CoalMine2xOutput: "工業革命",
    CoalMine2xOutputDesc: "煤礦場生產2倍煤但用多50%電同運煤用多50%燃料",
    AlMine2xOutput: "鋁冶煉",
    AlMine2xOutputDesc: "鋁礦場產生2倍鋁同用多2倍電",
    LoggingCamp2xOutput: "砍伐森林",
    LoggingCamp2xOutputDesc: "伐木場產生2倍木同運木用2倍燃料",
    PowerBankLeft: "蓄電池",
    ColorThemeEditor: "主題色彩編輯器",
    ColorThemeEditorDesc: "您可以覆寫顏色喺而家嘅色彩主題。您而家有 %{num}項覆寫",
    ColorThemeEditorSave: "儲存",
    ColorThemeEditorReset: "重設",
    ColorThemeEditorResetAll: "重設全部",
    NewMessageMentions: "一個新訊息提到您: %{message}",
    HideChatMentions: "收埋傾計提及",
    HideChatMentionsDesc: "喺一個傾計訊息提到我嗰陣，收埋聲同彈出提醒",
    PendingConstructionCannotReload: "您有郁緊嘅建築地盤，遊戲冇得重新入過",
    AcceptTradeFailRateLimit: "每%{time}秒先可以接受一單交易",
    DowngradeBuilding: "降級",
    CancelTradeConfirmDialogTitle: "取消呢單交易？",
    CancelTradeConfirmDialogYes: "係",
    CancelTradeConfirmDialogNo: "唔好",
    WarehouseInputRoutes: "輸入線",
    WarehouseAddInput: "加線",
    WarehouseTapToSelect: "喺地圖度揀...",
    WarehouseFindOnMap: "🔍 喺地圖度搵",
    WarehouseRemoveRoute: "移除",
    WarehouseAddRouteFail: "加唔到線: 揀嘅版塊唔係有效來源",
    LevelN: "Lv. %{level}",
    Surplus: "盈餘",
    Production: "生產",
    Consumption: "消耗",
    WarehouseInputCapacityDescV2: "總入貨量平均分到全部線",
    WarehouseInputCapacityPerRoute: "每條線: ",
    PlayerCountryFlag: "玩家旗",
    PlayerCountryChooseFlag: "按國家代碼排",
    WindTurbineAlwaysWork: "有風啦",
    WindTurbineAlwaysWorkDesc: "風力發電機郁100%時間但發少30%電",
    BookPublisherScience: "科學文獻",
    BookPublisherScienceDesc: "圖書出版社生產科學代替文化",
    WarehouseOutwardFuelSave: "免費送貨",
    WarehouseOutwardFuelSaveDesc: "倉庫都會慳燃料輸出",
    ImportSaveVersionTooNew: "您匯入緊一個存檔喺 %{saveVersion}，但您嘅遊戲係 %{gameVersion}。更新咗您嘅遊戲先。",
    BatteryFuelEconomy: "充電電池",
    BatteryFuelEconomyDesc: "電池燃料效率好100% (即50%燃料成本)",
    ShowTheoreticalInputOutputCapacity: "顯示理論輸入/輸出量",
    SpecialTransportCost: "有特殊運輸成本嘅資源",
    FreeTransportCost: "免費運嘅資源",
    Osaka: "大阪",
    OsakaBonus:
        "<li>資源生成集中啲</li><li>倉庫可以慳多50%燃料</li><li>獨特建築: 漫畫出版社</li><li>獨特建築: 動漫工作室</li><li>半導體工廠有2倍產量</li><li>鋰離子電池工廠有2倍產能</li><li>電池工廠係解鎖咗</li><li>電池工廠有2倍產能</li><li>電池嘅燃料效率好100%</li><li>電池工廠唔使煤</li><li>一開始就有100K電池</li>",
    HideChatDescV2: "收埋下面工具欄嘅傾偈訊息。顯示傾偈訊息，即係您同意我哋嘅",
    HideChatDescV2ToS: "服務條款",
    IntegratedCircuitFab: "集成電路工廠",
    MangaPublisher: "漫畫出版社",
    Manga: "漫畫",
    AnimeStudio: "動漫工作室",
    Anime: "動漫",
    PlayerTradeAction: "操作",
    PlayerTradeBuy: "買",
    PlayerTradeSell: "賣",
    PlayerTradeBid: "收",
    PlayerTradeAsk: "出",
    CancelTradeConfirmDialogDescV2: "取消呢個交易會退返%{percent}嘅資源/現金。資源會退到交易所倉庫",
    ClaimTradeSuccessV2: "您搞嘅交易搞掂咗: %{cashOrResource}",
    AcceptTradeSuccessV2: "您搞掂咗呢單交易: %{cashOrResource}",
    PlayerTradeFilterPriceV2: "好過市場價格",
    ResourceExplorer: "資源探勘者",
    ResourceExplorerDesc: "你可以喺空地度攞資源",
    ResourceExplorerDescLong: "💡 資源勘探者建築冇相鄰加成。佢嘅電消耗係睇資源",
    ResourceExplorerSelectResource: "探勘",
    ProductionSettings: "生產設定",
    PlayerTradeQuotaDesc: "💡 您嘅玩家交易配額係您市值嘅%{percent}, 會喺市場更新之後重置",
    PlayerTradePartialFillTitle: "揀成交%",
    PlayerTradeAmountNotValidV2: "交易量至少有1",
    PlayerTradeOptOut: "您已經揀咗退出排行榜，唔可以同其他玩家交易",
    FirstTimeReadGuide: "💡 唔知點玩，要幫手？撳呢度讀新手指南！",
    ReadSteamGuideV2: "遊戲指南",
    ReadSteamGuideV2Desc: "您可以喺Steam度睇吓由遊戲社區寫嘅指南 — 您都可以寫自己嘅指南",
    ChatMessageTooLong: "傾偈訊息字數多過上限",
    ChatPlaceholderV2: "喺呢度打訊息: 最長%{length}隻字",
    ShowProfitBreakdown: "顯示利潤細節",
    HideProfitBreakdown: "收埋利潤細節",
    ProfitBreakdownOutput: "%{res} 生產",
    ProfitBreakdownInput: "%{res} 消耗",
    ProfitBreakdownFuel: "燃料成本",
    BuildingProfit: "利潤",
    RestoreBackup: "恢復",
    SteamLogin: "用Steam帳戶登入",
    SteamLoginDialogDesc:
        "您嘅本地遊戲存檔度開咗擴展包，咁您就要登入Steam帳戶嚟繼續。您都可以揀「*刪本地存檔*」重新嚟過",
    SteamLoginDesc: "如果您嘅Steam賬戶有擴展包，登入咗您就可以喺Web版度同擴展包玩",
    SteamLoginYes: "登入",
    SteamLoginNo: "刪完再開",
    KungFuDojo: "功夫館",
    KungFu: "功夫",
    TaiChi: "太極",
    TaiChiDojo: "太極館",
    HongKong: "香港",
    FreeTransportToTradeCenter: "國際出口貿易",
    FreeTransportToTradeCenterDesc: "運到交易所唔用燃料，但喺交易所運出資源用多50%燃料",
    TaiChi10xCulture: "東方之珠",
    PlayerTradeYouHave: "庫存: %{amount}",
    PlayerTradeFillValue: "價值",
    FiberFactory: "光纖工廠",
    Fiber: "光纖",
    Achievements: "成就",
    AchievementsDesc: "您攞咗%{total}個成就入面嘅%{number}個",
    AchievementsReward: "獎勵: 瑞士錢 +%{swiss}",
    AchievementsRewardToast: "您攞咗獎勵: 瑞士錢 +%{swiss}",
    AchievementsClaim: "攞",
    AchievementsToast: "您攞到成就 %{name}，請喺總部度攞獎勵",
    AchievementStockholm100: "新生維京人",
    AchievementStockholm100Desc: "喺斯德哥爾摩一次過賺100瑞士錢",
    AchievementStockholm500: "畢業維京人",
    AchievementStockholm500Desc: "喺斯德哥爾摩一次過賺500瑞士錢",
    AchievementStockholm1000: "有經驗嘅維京人",
    AchievementStockholm1000Desc: "喺斯德哥爾摩一次過賺1000瑞士錢",
    AchievementOslo100: "挪威石油愛好者",
    AchievementOslo100Desc: "喺奧斯陸一次過賺100瑞士錢",
    AchievementOslo500: "挪威石油專家",
    AchievementOslo500Desc: "喺奧斯陸一次過賺500瑞士錢",
    AchievementOslo1000: "挪威石油大亨",
    AchievementOslo1000Desc: "喺奧斯陸一次過賺1000瑞士錢",
    AchievementRotterdam100: "紙風車物主",
    AchievementRotterdam100Desc: "喺鹿特丹一次過賺100瑞士錢",
    AchievementRotterdam500: "風車物主",
    AchievementRotterdam500Desc: "喺鹿特丹一次過賺500瑞士錢",
    AchievementRotterdam1000: "風力發電機物主",
    AchievementRotterdam1000Desc: "喺鹿特丹一次過賺1000瑞士錢",
    AchievementDetroit100: "本地車經銷商",
    AchievementDetroit100Desc: "喺底特律一次過賺100瑞士錢",
    AchievementDetroit500: "地區汽車經銷商",
    AchievementDetroit500Desc: "喺底特律一次過賺500瑞士錢",
    AchievementDetroit1000: "全國汽車經銷商",
    AchievementDetroit1000Desc: "喺底特律一次過賺1000瑞士錢",
    AchievementBoston100: "賺錢學士",
    AchievementBoston100Desc: "喺波士頓一次過賺100瑞士錢",
    AchievementBoston500: "賺錢高手",
    AchievementBoston500Desc: "喺波士頓一次過賺500瑞士錢",
    AchievementBoston1000: "印鈔博士",
    AchievementBoston1000Desc: "喺波士頓一次過賺1000瑞士錢",
    AchievementRome100: "戴克里先",
    AchievementRome100Desc: "喺羅馬一次過賺100瑞士錢",
    AchievementRome500: "君士坦丁大帝",
    AchievementRome500Desc: "喺羅馬一次過賺500瑞士錢",
    AchievementRome1000: "凱撒奧古斯都",
    AchievementRome1000Desc: "喺羅馬一次過賺1000瑞士錢",
    AchievementHamburg100: "德國",
    AchievementHamburg100Desc: "喺漢堡一次過賺100瑞士錢",
    AchievementHamburg500: "祖國",
    AchievementHamburg500Desc: "喺漢堡一次過賺500瑞士錢",
    AchievementHamburg1000: "齊柏林伯爵",
    AchievementHamburg1000Desc: "喺漢堡一次過賺1000瑞士錢",
    AchievementToulouse100: "噴射客機 A310",
    AchievementToulouse100Desc: "喺圖盧茲一次過賺100瑞士錢",
    AchievementToulouse500: "噴射客機 A330",
    AchievementToulouse500Desc: "喺圖盧茲一次過賺500瑞士錢",
    AchievementToulouse1000: "噴射客機 A380",
    AchievementToulouse1000Desc: "喺圖盧茲一次過賺1000瑞士錢",
    AchievementHongKong100: "業餘商人",
    AchievementHongKong100Desc: "喺香港一次過賺100瑞士錢",
    AchievementHongKong500: "專業經紀人",
    AchievementHongKong500Desc: "喺香港一次過賺500瑞士錢",
    AchievementHongKong1000: "秘密基金經理",
    AchievementHongKong1000Desc: "喺香港一次過賺1000瑞士錢",
    AchievementStPetersburg100: "大公爵",
    AchievementStPetersburg100Desc: "喺聖彼得堡一次過賺100瑞士錢",
    AchievementStPetersburg500: "採薩列維奇",
    AchievementStPetersburg500Desc: "喺聖彼得堡一次過賺500瑞士錢",
    AchievementStPetersburg1000: "全俄羅斯沙皇",
    AchievementStPetersburg1000Desc: "喺聖彼得堡一次過賺1000瑞士錢",
    AchievementOsaka100: "日本男爵",
    AchievementOsaka100Desc: "喺大阪一次過賺100瑞士錢",
    AchievementOsaka500: "日本伯爵",
    AchievementOsaka500Desc: "喺大阪一次過賺500瑞士錢",
    AchievementOsaka1000: "日本侯爵",
    AchievementOsaka1000Desc: "喺大阪一次過賺1000瑞士錢",
    SteamAutoCloudBackup: "Steam雲端自動備份",
    SteamAutoCloudBackupFailed: "Steam雲端自動備份唔到: %{error}",
    SteamManualBackup: "強制Steam雲端備份",
    UILoading: "入緊...",
    UserAuthenticated: "您過咗認證",
    BuildingResourceBreakdown: "閒置金額細節",
    SortByDeficit: "虧損",
    SortByRunOut: "用哂",
    SocialNetworkInc: "社交網絡公司",
    SocialNetwork: "社交網絡",
    DatabaseCompany: "數據庫公司",
    Database: "數據庫",
    SatelinkInc: "衛星通信公司",
    GameStationInc: "遊戲站公司",
    AirShuttleInc: "航空公司",
    AircraftCarrierFactory: "航母工廠",
    AircraftCarrier: "航母",
    MapExclusive: "地圖獨有",
    ElectricCar: "尼古拉·特斯拉",
    ElectricCarDesc: "車廠用電池代替汽油而且淨係要50％嘅量",
    HongKongBonusV2:
        "<li>獨特市場定價計算 — 價格同股票評級跟正常分配 (鐘形曲線)</li><li>市場更新同交易配額重置頻率變2倍 (每小時)</li><li>可以透過交易咗資源嚟解鎖研究</li><li>獨特建築: 功夫館</li><li>獨特建築: 太極館</li><li>可以嘅有效最多玩家交易量多50%</li><li>一開始就多1個自動賣出項目</li><li>獨特政策: 國際出口貿易</li><li>獨特政策：東方之珠</li><li>淨係要4種資源嚟解鎖批發所</li><li>一開始就有100M錢</li>",
    TaiChi10xCultureDescV2: "功夫同太極免費運。電影工作室有2倍產能，但用多50%電",
    SettingsFullScreen: "全螢幕",
    SettingsFullScreenDesc: "用全螢幕模式嚟開遊戲。淨係用喺Steam版",
    LeaderboardByAllPrestigeCurrency: "賺過嘅瑞士錢",
    LeaderboardByCash: "而家有嘅錢",
    LeaderboardTotalValuation: "總估值",
    LeaderboardDescV2: "睇睇頂尖玩家喺邊",
    LastUpdatedAt: "上次更新喺",
    DetroitBonusV3:
        "<li>引擎工廠係解鎖咗</li><li>引擎工廠有2倍產量</li><li>車廠有2倍產能</li><li >車廠用天然氣代替汽油</li><li>免費運車</li><li>尼古拉.特斯拉政策係免費</li><li>火車工廠有2倍產能</li>",
    SaveAndExit: "儲存再退出",
    SaveAndExitDesc: "儲存再退出。呢個淨係用喺Steam版而且同視窗欄上面嘅閂掣一樣",
    AutoSellResourceWarningShortLabel: "💡 自動賣出",
    AutoSellResourceWarningDesc: "您自動賣出緊呢個資源，呢度用唔到喺交易所度儲存嘅",
    PlayerTradeLocalPrice: "本地價格: %{price}",
    ChatForceScroll: "強制郁",
    ChatForceScrollDesc: "如果開咗強制郁，有新訊息嗰陣聊天室都會郁。唔係嘅話淨係喺您已經喺底嗰陣，佢先會郁",
    ResourceExplorer2: "資源探勘者 2.0",
    ConstructionCancel: "取消工程",
    ConstructionPause: "暫停",
    ConstructionResume: "繼續",
    PolicyBlueprint: "藍圖",
    PolicyBlueprintDesc: "建築物唔會自己開始起 — 手動開始 (免費政策)",
    HighlightUnderConstruction: "...仲未起",
    HighlightUnderLevel10: "...低過10級",
    HighlightUnderLevel20: "...低過20級",
    HighlightUnderLevel30: "...低過30級",
    Logout: "您登出咗",
    ConstructionStatusQueueingV2: "等緊",
    ConstructionStatusPausedV2: "停咗",
    ConstructionStatusBuildingV2: "起緊",
    ConstructionStatusUnpaidV2: "未俾錢",
    ConstructionStatus: "工程狀態",
    ConstructionStart: "開始",
    CostFree: "免費",
    PlaceBlueprint: "擺建築藍圖係免費嘅",
    PlayerTradePriceNotValidV2: "交易價要喺%{min}同%{max}之間",
    MarketNews: "市場新聞",
    MarketNewsApplyToYou: "得您",
    MarketNewsApplyToGlobal: "人人都有",
    MarketNewsHighlightAffected: "🔍 突出顯示",
    MarketNewsFilterInput: "全部%{res}輸入 ",
    MarketNewsFilterOutput: "全部%{res}輸出 ",
    MarketNewsFilterBoth: "全部%{res}輸入同輸出 ",
    MarketNewsIncrease: "多咗%{percent}",
    MarketNewsDecrease: "少咗%{percent}",
    MarketNewsBuilding: "嗰個建築物受%{num}項新聞嘅影響",
    StockholmBonusV2:
        "<li>獨特建築: 音樂工作室</li><li>伐木場有2倍產量</li><li>造紙廠係解鎖咗</li><li>電路板工廠有2倍產量</li><li>科學文獻政策係免費</li>",
    FreeOilTransportV2: "電動石油運輸",
    Tutorial4P1:
        "資源運輸用燃料。有幾種燃料類型，您而家用緊<em>汽油⛽</em>嚟燃料做。您有一間<em>煉油廠</em>，佢會喺油井度運石油出嚟同生產汽油。<br><br>郁緊嘅細<em>點</em>代表資源嘅即時移動。您應該優化建築物嘅位置嚟縮短運輸距離。<br><br><em>升級</em>您嘅建築物會增加佢哋嘅輸出，但都會增加佢哋嘅用電量同要嘅輸入。",
    Tutorial4P2:
        "您可以喺<em>物流部🚦</em>度改燃料類型 — 喺呢個地圖，您仲可以用<em>天然氣</em>嚟做燃料。<br><br>物流部仲會顯示您用最多燃料嘅運輸線 — 您要隨時留意住。<br><br>記住<em>確保燃料生產高過消耗</em>，唔係嘅話喺冇燃料嗰陣會停產。<br><br>如果發生咗，唔使擔心，您可以喺交易所或者其他玩家度買啲緊急燃料。",
    Tutorial5P2:
        "<em>統計局📊</em>俾咗您好嘅生產概述。您可以睇到資源輸入同輸出嘅詳細資訊。<br><br>仲有好多有用嘅圖表📈 — 您喺平衡生產嗰陣會想參考佢哋。<br></br>左上角仲會顯示您嘅<em>錢💰，電盈餘同燃料盈餘⛽</em>嘅量 — 如果其中一個變咗紅色，您要去睇吓發生咩事。",
    MusicProducer: "音樂工作室",
    PlasticFiber: "塑膠光纖",
    PlasticFiberDesc: "光纖工廠用多50%塑膠但用少50%玻璃",
    NewsEffectx2: "新聞發布會",
    NewsEffectx2Desc: "市場新聞嘅影響加倍 — 正面同負面",
    SellRefundPercentage: "賣出/降級退款",
    SellRefundPercentageDesc: "如果您簤出或者降級建築物，呢個會係您退返嘅錢同資源嘅%",
    SellBuildingDescV2: "賣建築物會退返您投資嘅%{percent}，同埋%{percent}嘅資源會被送到交易所",
    BuilderMoveSpeed: "工程隊移動速度",
    BuilderMoveSpeedDesc: "工程隊行到建築地嘅速度",
    EBookInc: "電子書公司",
    ResourceBooster: "資源加速器",
    BuildWarningTitle: "建築可能做唔到嘢",
    BuildWarningTitleDesc: "%{reason}。您真係要喺呢度起？",
    BuildWarningBuildAnyway: "點都要起",
    ResourceBoosterNotWorking: "⛔ 資源加速器喺礦場隔離先會做嘢",
    ResourceBoosterBuildings: "建築被加速",
    BuildingResourceConversion: "%{resource}轉換",
    AllTimeSwissMoneyEarned: "有賺過嘅瑞士錢: %{number}",
    BuildingUpgradeCostDivider: "建築升級成本折扣",
    AchievementSoftwareGiant: "軟件巨人",
    AchievementSoftwareGiantDesc: "喺同一個地圖度起10級軟件公司、10級操作系統公司、10級數據庫公司同10級網頁瀏覽器",
    AchievementSpaceRace: "太空競賽",
    AchievementSpaceRaceDesc: "喺同一個地圖度起10級火箭工廠、10級衛星工廠、10級太空船工廠同10級太空站工廠",
    AchievementToTheMoon: "去月球",
    AchievementToTheMoonDesc: "起40級比特幣農場同40級狗狗幣農場。有1B比特幣同1B狗狗幣",
    ItsAllGreen: "都係綠色",
    ItsAllGreenDesc: "有50條生產線都冇生產虧損",
    DeepInRed: "深入紅色",
    DeepInRedDesc: "有50條生產線都有生產虧損",
    UseScientificNotation: "用科學計數法",
    UseScientificNotationDesc: "對大過999.9T嘅數字用科學計數法 (e表示)",
    LogoutDescV2: "您喺另一個設備度登入咗，呢個被登出咗。您可以重新登入，但另一個設備會被登出",
    LogBackIn: "重新登入",
    PlayerTradeNowAllowedV2: "恢復/導入保存之後嘅％{hour}個鐘用唔到玩家交易",
    ServerDisconnected: "您同伺服器斷咗連線，檢查您嘅網路連線同重新開過",
    BuildingUpgradeCostDividerDescV2: "呢個折扣會減少建築升級費用",
    ResourceBoosterDesc: "增加隔離礦場產量",
    BlockUserChatTitle: "封鎖 %{user}",
    BlockUserChatAction: "封鎖",
    BlockUserChatDesc: "封鎖會一直生效而且冇得取消除非重啟開過",
    ChangeNameCooldown: "您每隔%{hour}個鐘先可以改一次名",
    AtomicBombFactory: "原子彈工廠",
    AtomicBomb: "原子彈",
    DynamiteFactory: "炸藥工廠",
    Dynamite: "炸藥",
    NuclearMissileFactory: "核彈工廠",
    NuclearMissile: "核彈",
    LiquidPropellantFactory: "液體推進劑工廠",
    GasPropellantFactory: "氣體推進劑工廠",
    Propellant: "推進劑",
    ProjectV2: "V-2 計畫",
    ICBMFactory: "洲際彈道導彈工廠",
    ICBM: "洲際彈道導彈",
    RadarFactory: "雷達工廠",
    Radar: "雷達",
    SpaceForceCommand: "太空軍隊司令部",
    SpaceForce: "太空軍隊",
    SteamAutoCloudBackupDescV2:
        "您嘅最新進度儲存咗去Steam雲端同跨裝置同步。遊戲都會每10分鐘自動備份到Steam雲端。你隨時都可以強制備份",
    SpaceColony: "太空殖民地",
    SpaceColonyInc: "太空殖民局",
    ProjectVostok: "東方計畫",
    AdjacentBonusSquare: "相鄰加成區塊",
    AdjacentBonusSquareDesc: "相鄰加成多50%效能，但板塊增益幅度係-15%同+15%之間",
    ResourceBoosterSquare: "資源加速區塊",
    ResourceBoosterSquareDesc: "資源加速器有多25%加成，但科學同電用多25%",
    SteelMillx2: "鋼爐現代化",
    SteelMillx2Desc: "煉鋼廠同不鏽鋼廠有2倍產量但用2倍電",
    FuelDynamite: "燃料炸藥",
    FuelDynamiteDesc: "炸藥工廠用而家嘅燃料代替石油",
    StPetersburgBonusV2:
        "<li>鈾礦場有2倍輸出</li><li>濃縮鈾工廠有2倍產量</li><li>鈾運輸成本少50％燃料</li><li>槍免費運</li><li>東方計畫有2倍產量</li>",
    ToulouseBonusV2:
        "<li>鈦礦場有2倍輸出</li><li>濃縮鈾工廠有2倍產能</li><li>噴射引擎工廠有2倍產量</li><li>飛機工廠有2倍產能</li><li>火箭工廠有2倍產量</li>",
    BuildingPermitsNeededDesc: "呢個建築郁唔到因為您唔夠建築許可證",
    BuildingPermitsNeeded: "要建築許可證",
    BuyMissingPermits: "買唔夠嘅許可證",
    GPUIsBusy: "您嘅GPU忙緊",
    GPUIsBusyDesc: "您嘅操作系統停咗遊戲畫面因為您嘅GPU忙/亡喺其他程式。您可以重新入過嚟繼續。冇用就重新開過",
    SaveAndReloadGame: "儲存同重新入過",
    ResearchLabCultureInput: "文藝復興",
    ResearchLabCultureInputDesc: "研究實驗室有2倍產量，但要用多啲文化點",
    GasPumpx2Output: "高壓天然氣泵",
    GasPumpx2OutputDesc: "天然氣泵有2倍輸出，但用2倍電",
    LeaderboardValuationPerHour: "每個鐘總估值",
    LeaderboardValuationPerHourPerSwiss: "每瑞士錢嘅每個鐘總估值",
    LeaderboardValuationPerHourNewPlayers: "每個鐘總估值 (<1000 瑞士錢)",
    LeaderboardValuationPerBuilding: "每棟建築嘅建築估值",
    BuildingCustomColor: "建築顏色",
    BuildingCustomColorReset: "重設",
    Vancouver: "溫哥華",
    VancouverBonus:
        "<li>每4唔同類嘅建築有1個免費建築許可證</li><li>獨特政策: 生產多元化</li><li>獨特建築: 楓糖漿工廠</li><li>免費運楓糖漿</li><li>獨特燃料: 楓糖漿</li><li>交易鈾同濃縮鈾嗰陣有2倍玩家交易配額</li><li>獨特免費政策: 糖漿塑膠</li><li>玩具工廠有2倍產能</li><li>遊戲工作室有2倍產量</li>",
    MapExtraPermitDesc: "您喺地圖嘅獨有加成度攞到 %{number}個免費建築許可證",
    OsloBonusV3:
        "<li>煉油廠係解鎖咗</li><li>煉油廠有2倍產量</li><li>電動石油運輸政策係免費</li><li>天然氣加工廠有2倍產量</li><li>1座免費的風力發電機</li><li>1座免費8級油井</li><li>1座免費2級煉油廠</li><li>1座免費2級天然氣泵</li>",
    ResourceBoosterPercentageV2: "💡 呢個量包括嚟自附近資源加速器俾嘅%{percent}提升",
    MapleSyrup: "楓糖漿",
    MapleSyrupFactory: "楓糖漿工廠",
    SyrupPlastic: "糖漿塑膠",
    SyrupPlasticDesc: "全部入塑膠嘅建築物都改用楓糖漿",
    ResourceBoosterSupplyChain: "供應鏈加速器",
    ResourceBoosterSupplyChainDesc:
        "資源加速器用2倍電同科學，但會加速每個郁緊嘅礦場，佢都會強化用嗰啲礦場輸出嘅工廠產量 (嗰啲工廠應該淨係用庫存嘅)",
    ProductionDiversification: "生產多元化",
    ProductionDiversificationDesc: "每種唔同類型嘅建築會俾全部建築多1%產量",
    ExtraPolicyPointsDescV2: "政策中心有2倍政策點轉換產量",
    PowerRequired: "電力需求",
    AchievementVancouver100: "樹汁賣家",
    AchievementVancouver100Desc: "喺溫哥華一次過賺100瑞士錢",
    AchievementVancouver500: "糖漿專家",
    AchievementVancouver500Desc: "喺溫哥華一次過賺500瑞士錢",
    AchievementVancouver1000: "加納克征服者",
    AchievementVancouver1000Desc: "喺溫哥華一次過賺1000瑞士錢",
    BarbariansAtTheGate: "門口嘅野蠻人",
    BarbariansAtTheGateDesc: "喺一次市場更新嘅時候用咗值1T嘅玩家交易配額",
    DiversifiedProductions: "多元化生產",
    DiversifiedProductionsDesc: "喺一個地圖度有100棟唔同種嘅建築",
    RealEstateTycoon: "房地產大亨",
    RealEstateTycoonDesc: "喺一個地圖度有400棟建築",
    ResourceExplorer2DescV2:
        "資源探勘者用2倍輸出但用2倍電。如果供應鏈加速器郁緊而且加速器隔離有一樣輸出嘅礦場，探勘者就可以被資源加速器加速",
    NoTileModifier: "地球係平嘅",
    NoTileModifierDesc: "全部板塊加成都係0%。呢個政策會閂自然之力同板塊加成+政策",
    DoubleTileModifierDescV2: "全部板塊加成都係2倍 — 好同唔好都係。開呢個政策會閂地球係平嘅政策",
    TileModifierOutputOnlyDescV2: "板塊加成淨係影響輸出取代輸出入，但係得50%效果。開呢個政策會閂地球係平嘅政策",
    RotterdamBonusV2:
        "<li>煉鋼廠有2倍產量</li><li>不鏽鋼廠有2倍產量</li><li>免費運鐵</li><li>運鋼用少50%燃料</li><li>一開始有2倍自動賣出量</li><li>地球係平嘅政策係免費</li>",
    QuickLinks: "快速鏈接",
    GetHelp: "搵幫手",
    GetHelpBeginnerGuides: "新手指南",
    GetHelpSteamGuides: "其他Steam指南",
    GetHelpInGameChat: "喺遊戲嘅傾偈位度問",
    GetHelpDiscord: "加入我哋嘅Discord伺服器",
    GetHelpWiki: "社群維基",
    SelectATile: "揀一個板塊",
    PledgeAmount: "贊助 %{amount}",
    PledgeValue: "值 $%{amount}",
    TotalPledgedValue: "總贊助值",
    TotalPledgedValueDesc: "您嘅第一單贊助會計入眾籌目標。之後其他贊助會加落您嘅總贊助值，但唔會計入眾籌目標。",
    ReturnOnPledge: "募資報酬",
    ReturnOnPledgeDesc: "眾籌募資成功嘅話，呢個會係您嘅報酬。報酬額係您嘅總贊助值同您贊助嘅種類數目%計出嚟。",
    CrowdfundingEndIn: "喺%{time}完",
    ClaimCrowdfundingReward: "攞報酬 %{amount}",
    ClaimCrowdfundingRefund: "攞退款 %{amount}",
    CrowdfundingUnsuccessful: "呢次眾籌募資唔成功，總贊助值會退俾你",
    PledgeSuccessful: "您喺呢次眾籌募資度贊助咗 %{amount}",
    CrowdfundingClaimSuccessful: "您攞咗 %{amount}錢",
    CrowdfundingAlreadyPledged: "您贊助過",
    CrowdfundingAlreadyPledgedDesc: "您可以贊助多啲資源，會加落您嘅總贊助值(同潛在報酬)，但唔會計入眾籌目標。",
    WholesaleCenterProducingOnly: "批發合作拍檔",
    WholesaleCenterProducingOnlyDesc: "批發所訂單淨係包含研究過上半先進嘅資源 (而且要滿足一定量嘅資源)",
    SoftwareCompiler: "軟體編譯器",
    SearchEngine: "搜尋引擎",
    SearchEngineCompany: "搜尋引擎公司",
    Navy: "海軍",
    NavyCommand: "海軍司令部",
    Battleship: "戰艦",
    BattleshipFactory: "戰艦工廠",
    ResourceMovementHide: "一直收埋",
    ResourceMovementShow: "一直顯示",
    ResourceMovementHighlight: "突出顯示",
    ResourceMovementLine: "得線",
    ResourceMovement: "資源郁動",
    ResourceMovementDesc: "您可以揀幾時顯示資源(點)郁。收埋佢可以改善效能",
    CrowdfundingCashInWarning: "您有未計嘅募資贊助 — 喺新城市開始會冇咗佢哋",
    ResourceBoosterBannerDescV2: "💡 您而家有 %{number}座資源加速器 — 科學輸入量會因為資源加速器嘅量而變",
    CrowdfundingId: "眾籌 %{id}",
    PatchNotes: "更新記錄",
    PatchNotesDesc: "嚟睇睇更新咗啲咩",
    PanelPositionLeft: "左 (停)",
    PanelPositionLeftFloat: "左 (浮)",
    PanelPositionRight: "右 (停)",
    PanelPositionRightFloat: "右 (浮)",
    PanelPositionAuto: "自動",
    TimePlayed: "玩咗幾耐",
    ValuationPerHour: "每個鐘資產估值",
    HighPowerPriority: "優先用電",
    HighPowerPriorityDesc: "開呢樣嘢可以令呢個建築有用電優先權",
    IndustryZone: "工業區",
    IndustryZoneDesc: "合併隔離嘅建築，形成供應鏈嚟慳建築許可證。",
    IndustryZoneMaxBuildingLevel: "最高建築等級",
    IndustryZoneNotWorkingDesc: "全部喺佢隔離嘅建築都應該搞條供應鏈而且都唔喺其他工業區度",
    IndustryZoneNoAdjacentBonus: "呢個建築一個工業區度而且冇相鄰加成",
    PlayerTradeAutoClaim: "自動攞搞掂嘅交易",
    MusifyInc: "Musify 公司",
    WebflixInc: "Webflix 公司",
    CloudStreaming: "雲直播",
    GameCloudInc: "GameCloud 公司",
    SuperComputerLab: "超級電腦實驗室",
    SuperComputer: "超級電腦",
    SkyNetInc: "天網(SkyNet)公司",
    SkyNet: "天網(SkyNet)",
    RobocarFactory: "無人車工廠",
    Robocar: "無人車",
    WarehouseBuildingPermitSave: "倉庫許可證法",
    WarehouseBuildingPermitSaveDesc: "每兩間倉庫多一張免費建許可證",
    PolicySearchPlaceholder: "打政策名嚟搵",
    SwissUpgrade: "瑞士升級",
    SwissUpgradeDesc: "瑞士升級係永久性而且如果您喺新城市開始會被過數",
    SwissBoost: "瑞士加成Swiss Boost",
    SwissBoostDesc: "瑞士加成淨係影響您呢轉 — 同埋如果您喺新城市開始會被重設",
    ProductionMultipliers: "生產倍率",
    MultiplierMapUniqueBonus: "地圖獨特加成",
    MultiplierSwissUpgrade: "瑞士升級 (永久性)",
    MultiplierSwissBoost: "瑞士升級 (呢轉)",
    SwissBoostCostDivider: "瑞士加成成本折扣",
    SwissBoostCostDividerDesc: "瑞士加成成本被呢個折扣折咗 — 淨係用喺倍率/折扣升級",
    AirForceCommand: "空軍司令部",
    AirForce: "空軍",
    StealthFighterFactory: "隱形戰機工廠",
    StealthFighter: "隱形戰機",
    ArmyCommand: "陸軍司令部",
    Army: "陸軍",
    GreenPeacekeeper: "綠色維和者Green Peacekeeper",
    GreenPeacekeeperDesc: "俾陸軍、海軍、空軍或者太空軍得可再生發電廠用 (風力/太陽能)",
    DotComTycoon: "互聯網(DotCom)大亨",
    DotComTycoonDesc: "喺同一張地圖度起10級社交網絡公司、10級搜索引擎公司、10級天網(SkyNet)公司同10級 Musify 公司",
    ConstructionNotResearched: "Not Researched",
    OfflineEarningDescV2: "Offline earning depends on your current research, production and auto sell",
    HighSpeedWarehouse: "High Speed Warehouse",
    HighSpeedWarehouseDesc:
        "Warehouses have 2x capacity and 50% faster inward and outward transport speed, but use 2x power",
    IndustryZoneMultiplierDesc: "Industry Zone Bonus",
    IndustryZoneMultiplierSwissBoost: "Industry Zone Capacity Booster",
    IndustryZoneMultiplierSwissBoostDesc:
        "Each building inside an industry zone provides this capacity boost to all the buildings in the same zone",
    EarningPerMinuteV2: "Offline Earning Rate",
    OfflineResearchPoint: "Offline Research Point",
    WholesaleCenterOrderFasterV2: "Bigger Faster Wholesale",
    OfflineResearchSwissBoost: "Offline Research",
    OfflineResearchSwissBoostDesc:
        "Research points are generated while you are offline (according to your Research Lab level, Science in your warehouse and offline earning time)",
};
