export const ZH_TW = {
    Translator: "譯者",
    TranslatorName: "LazySu, snewpeap, Orange233",
    Language: "語言",
    ThisLanguage: "繁體中文",
    OK: "好的",
    SteelMill: "軋鋼廠",
    StainlessSteelPlant: "不鏽鋼廠",
    CircuitFoundry: "電路代工廠",
    IntegratedCircuit: "集成電路",
    OilWell: "油井",
    Wood: "木頭",
    LoggingCamp: "伐木場",
    LumberMill: "鋸木廠",
    Lumber: "木材",
    Paper: "紙張",
    PaperMill: "造紙廠",
    Book: "書本",
    BookPublisher: "圖書出版社",
    OilRefinery: "煉油廠",
    Sell: "出售",
    Upgrade: "升級",
    Build: "建造",
    Inspect: "檢查",
    Buildings: "建築物",
    Iron: "鐵",
    Actions: "行動",
    FuelType: "選擇燃料",
    FuelCost: "燃料費用",
    FuelConsumption: "%{fuel}消耗",
    FuelEconomy: "燃燒效率",
    FuelProduction: "%{fuel}產量",
    FuelInStorage: "%{fuel}儲備",
    Plastic: "塑料",
    FuelSurplus: "%{fuel}盈餘",
    Petrol: "汽油",
    Buy: "購買",
    NoLiquidity: "無流動性",
    NoLiquidityTurnOffAutoSell: "市場沒有足夠的流動性為 %{res}, 自動銷售已被關閉",
    Multiplier: "乘數",
    MultiplierDesc: "每提升10級, 您將增加1個乘數",
    SellBuilding: "出售建築物",
    PowerGrid: "電力系統",
    TradeAmount: "貿易數量",
    SortBy: "排序",
    SortByPrice: "價格",
    SortByAmount: "數量",
    NotEnoughResourcesForTrade: "貿易中心沒有足夠的資源用於此貿易",
    NotEnoughResources: "沒有足夠的資源進行此操作",
    Transportation: "運輸系統",
    Cash: "現金",
    Aluminum: "鋁",
    ResearchPoint: "研究點",
    Unlock: "解鎖",
    BuildingUnlocked: "%{building}已解鎖",
    Science: "科學",
    ScienceFromPowerDesc: "發電廠發電時產生少量的科學點",
    Culture: "文化",
    School: "學校",
    University: "大學",
    Polytechnic: "理工學院",
    Colosseum: "大競技場",
    WindTurbine: "風力發電機",
    Engine: "引擎",
    EngineFactory: "引擎工廠",
    CameraFactory: "照相機工廠",
    Camera: "照相機",
    Gun: "槍",
    GunFactory: "槍械工廠",
    Aircraft: "飛機",
    AircraftFactory: "飛機工廠",
    Zeppelin: "齊柏林飛艇",
    ZeppelinFactory: "齊柏林飛艇工廠",
    Tank: "坦克",
    TankFactory: "坦克工廠",
    MinimumTradingAmount: "交易金額不能低於最低金額",
    CoalPowerPlant: "燃煤發電廠",
    PetrolPowerPlant: "燃油發電廠",
    Copper: "銅",
    Gas: "天然氣",
    GasPump: "天然氣泵",
    GasPowerPlant: "天然氣發電廠",
    Missile: "導彈",
    MissileFactory: "導彈工廠",
    Rocket: "火箭",
    RocketFactory: "火箭工廠",
    BuildingPermit: "建築許可證",
    BuildingPermitDesc: "您總共可以建造 %{amount} 座建築物，您已經建造了 %{amountBuilt} 座，還能建造 %{amountLeft} 座",
    BuildingLocked: "建築物不可用，您需要先在研究室解鎖它",
    BuildQueue: "建造隊列",
    BuildQueueDesc: "當前在建造隊列中的建築數量",
    MaxBuilders: "最大工程隊數量",
    MaxBuildersDesc: "您可以同時建造的建築物數量",
    Silicon: "硅",
    AluminumMine: "鋁礦場",
    CopperMine: "銅礦場",
    SiliconMine: "硅礦場",
    IronMine: "鐵礦場",
    CoalMine: "煤礦場",
    Headquarter: "總部",
    ResearchLab: "研究實驗室",
    TradeCenter: "貿易中心",
    Resources: "資源",
    NotEnoughPower: "💡 電力不足，考慮增加發電站",
    NotEnoughFuel: "沒有足夠的 %{fuel} 進行此操作",
    NotEnoughCash: "沒有足夠的現金進行此操作",
    NotEnoughSwissMoney: "沒有足夠的瑞士資金進行此操作",
    BuildingNotEnoughFuel: "💡 %{fuel} 不足",
    AutoSell: "自動出售",
    SellAll: "全部出售",
    Change: "更改",
    StatisticsBureau: "統計機構",
    LogisticsDepartment: "後勤部",
    From: "從",
    Top20FuelCost: "消耗燃料前20",
    To: "到",
    TransportTime: "運輸時間",
    TopN: "前 %{n}",
    Warehouse: "倉庫",
    TradeWarehouse: "貨運倉庫",
    Coal: "煤",
    Video: "視頻",
    ClothingFactory: "服裝工廠",
    Clothes: "衣服",
    Fashion: "時裝",
    FashionFactory: "時裝工廠",
    VideoFarm: "視頻作坊",
    SantaFactory: "聖誕老人工廠",
    Santa: "聖誕老人",
    Car: "汽車",
    CarFactory: "汽車工廠",
    Ship: "船",
    SolarPanel: "太陽能電池板",
    SolarPanelDesc: "💡 太陽能電池板每10秒只能工作5秒-所有的循環都是一致的",
    WindTurbineDesc: "💡 風力發電機每10秒只工作8秒-循環不一致",
    Movie: "影片",
    MovieStudio: "電影工作室",
    Sitcom: "電視劇",
    TVStudio: "電視工作室",
    PC: "電腦",
    GameStudio: "遊戲工作室",
    Game: "遊戲",
    ComputerFactory: "計算機工廠",
    Shipyard: "造船廠",
    PowerUsage: "用電功耗",
    PowerSupply: "發電功率",
    PowerSurplus: "電力盈餘",
    Level: "級別",
    Power: "功率",
    CentralBank: "中央銀行",
    ResourceInput: "輸入",
    ResourceOutput: "輸出",
    ResourceStorage: "庫存",
    ResourceChange: "變化",
    ResourceInOutDesc: "💡 點擊上面的輸出-輸入數字，以顯示相應的輸出和輸入建築物",
    ResourceChart: "資源圖",
    MarketUpdateIn: "市場在 %{time} 後更新",
    Income: "收入",
    Semiconductor: "半導體",
    SemiconductorFactory: "半導體工廠",
    SemiconductorFab: "半導體晶圓廠",
    Steel: "鋼",
    Bitcoin: "比特幣",
    BitcoinFarm: "比特幣農場",
    Dogecoin: "狗狗幣",
    DogecoinFarm: "狗狗幣農場",
    Guitar: "吉他",
    GuitarFactory: "吉他工廠",
    Drum: "鼓",
    DrumFactory: "鼓工廠",
    RecordingStudio: "錄音室",
    OperaHouse: "歌劇院",
    CoalGasificationPlant: "煤氣化加工廠",
    GasProcessingPlant: "天然氣加工廠",
    Music: "音樂",
    Glass: "玻璃",
    PhoneFactory: "電話工廠",
    Phone: "電話",
    GlassFactory: "玻璃工廠",
    Oil: "石油",
    Chromium: "鉻",
    ChromiumMine: "鉻礦場",
    Uranium: "鈾",
    EnrichedUranium: "濃縮鈾",
    NuclearPowerPlant: "核電站",
    UraniumEnrichmentPlant: "濃縮鈾加工廠",
    UraniumMine: "鈾礦場",
    Titanium: "鈦",
    TitaniumMine: "鈦礦場",
    TitaniumAlloyPlant: "鈦合金加工廠",
    ChromiumAlloyPlant: "鉻合金加工廠",
    Input: "輸入",
    PanelPosition: "面板位置",
    PanelPositionDesc: "將控制面板顯示在左側，右側或自動 (取決於當前的選定的瓷磚)",
    InputCapacity: "輸入容量",
    InputCapacityPerCycle: "輸入容量 / 循環",
    Output: "輸出",
    OutputCapacity: "輸出容量",
    OutputCapacityPerCycle: "輸出容量 / 循環",
    ResourceDeposit: "資源礦床",
    RecommendedBuilding: "💡 這塊地磚有 %{resource} 資源",
    AdjacentBonus: "相鄰加成",
    AdjacentBonusDesc: "每棟相鄰的同類型工作建築物將帶來%{bonus}%的額外產量",
    ConsiderIncreaseProduction: "💡 考慮增加 %{resource} 生產",
    AlwaysTransportInput: "庫存模式",
    AlwaysTransportInputTradeCenter: "始終出口",
    AlwaysTransportInputTradeCenterDesc: "始終將資源運送到貿易中心，即使該資源無法啟用自動銷售",
    AlwaysTransportInputDesc: "始終運輸輸入資源，即使它們高於最低生產要求",
    ProductionCycleLength: "生產周期",
    ProductionCycleLengthDesc:
        "一個生產周期的持續時間，以秒為單位。延長周期將相應增加每個周期的投入/產出，從而降低獲取輸入資源時的優先級",
    MaxInputDistance: "最大輸入距離",
    MaxInputDistanceDesc: "這棟建築以瓷磚數量計算的輸入資源的最大距離",
    AutoSellCapacity: "自動銷售數量",
    AutoSellCapacityDesc: "自動銷售每秒能夠處理每種資源的最大數量",
    CurrentAutoSellCapacityMultiplier: "當前乘數: x%{n}",
    AutoSellConcurrency: "自動銷售並發數量",
    AutoSellConcurrencyDesc: "自動銷售可以同時處理的最大資源數量",
    MaxAutoSellConcurrencyReached: "您已達到最大自動銷售並發，請關閉另一個自動銷售以啟用此自動銷售",
    CannotSellBuilding: "目前不能出售此建築物",
    WallStreet: "華爾街",
    MarketCap: "市值",
    MarketCapDesc: "市場價值",
    BuildingValuation: "建築估值",
    BuildingValuationDesc: "您的建築物的總價值，包括建築許可證和升級",
    ResourcesValuation: "資源估值",
    ResourcesValuationDesc: "庫存資源總價值",
    Battery: "電池",
    BatteryFactory: "電池工廠",
    RatingBuy: "購買",
    RatingSell: "出售",
    SwissShop: "瑞士商店",
    RatingHold: "保持",
    RatingOutperform: "表現優異",
    RatingUnderperform: "表現不佳",
    StockRating: "股票評級",
    JetEngine: "噴氣發動機",
    Helicopter: "直升機",
    Lithium: "鋰",
    LithiumMine: "鋰礦場",
    LiionBatteryFactory: "鋰離子電池工廠",
    HelicopterFactory: "直升機工廠",
    Satellite: "衛星",
    ToyFactory: "玩具工廠",
    Toy: "玩具",
    SpaceStation: "空間站",
    SpaceStationFactory: "空間站工廠",
    OperatingSystem: "操作系統",
    OperatingSystemCompany: "操作系統公司",
    LinuxDistribution: "Linux 發行版",
    Internet: "互聯網",
    WebBrowser: "網絡瀏覽器",
    Console: "控制台",
    ConsoleFactory: "控制台工廠",
    Train: "火車",
    TrainFactory: "火車工廠",
    ShoeFactory: "鞋工廠",
    Shoes: "鞋",
    ArtilleryFactory: "火炮工廠",
    Artillery: "火炮",
    SubmarineFactory: "潛艇工廠",
    Submarine: "潛艇",
    Spaceship: "太空船",
    RobotFactory: "機器人工廠",
    Robot: "機器人",
    SpaceshipFactory: "太空船工廠",
    SatelliteFactory: "衛星工廠",
    JetEngineFactory: "噴氣發動機工廠",
    StockRatingDesc: "來自華爾街分析師的股票評級共識，它會影響你的市值，並隨市場一起更新",
    InterestRate: "過夜利率",
    InterestRateDesc: "您在離線時通過市值賺取的利息",
    OfflineEarning: "離線收益",
    OfflineEarningDesc: "離線收益取決於您的市值和利率",
    PerMin: "%{amount}/分鐘",
    OfflineEarningTime: "離線賺取時間",
    OfflineEarningTimeDesc: "您能夠獲取離線收益的時長",
    BuyPermit: "購買許可證",
    NotEnoughBuildingPermit: "沒有足夠的建築許可證，請購買更多來建造新的建築物",
    MovingAverage: "平均變動",
    MovingAverageDesc: "顯示資源變化的平均值，而不是實時變化量",
    AllowZoom: "縮放",
    AllowZoomDesc: "打開縮放支持。使用鼠標輪進行縮放。當前縮放為 %{zoom}",
    AllowZoomMobileDesc: "打開縮放支持。使用手指捏拉進行縮放。當前縮放為 %{zoom}",
    Settings: "設置",
    SellBuildingDesc: "出售建築物將退還您 50% 的投資，50% 的資源將運送到貿易中心",
    SellBuildingFullRefundDesc: "建築回收政策已經啟用，出售建築物將給你全額退款，直到在 %{time}",
    Sound: "聲音效果",
    SoundDesc: "打開聲音效果，如點擊或錯誤的聲音",
    AutoHighlight: "自動高亮",
    AutoHighlightDesc: "當您選擇建築物時，自動突出顯示相同類型的建築物",
    MusicDesc: "打開音樂：Shane Ivers（https://www.silvermansound.com）的《It's Not Over 'Til The Bossa Nova》",
    Credits: "鳴謝",
    Icons: "圖標",
    MisplacedBuilding: "⛔ 此 %{building} 沒有放在正確的資源格上",
    UnderConstruction: "%{building} 正在建設中",
    Left: "左",
    Right: "右",
    Auto: "自動",
    HighlightBuildings: "高亮建築",
    HighlightTurnedOff: "被關閉的...",
    HighlightStockpileModeOn: "開啟庫存模式的...",
    HighlightProductionCycleNotDefault: "生產周期 > 1的...",
    HighlightMaxInputDistanceNotDefault: "最大輸入距離 < ∞的...",
    HighlightNotMakingProfit: "...不盈利的",
    NBuildingsAreHighlighted: "%{n} 建築物被突出顯示",
    OnlyToWarehouse: "倉庫專運",
    OnlyToWarehouseDesc: "只有倉庫才能從這座建築物里運送資源",
    TurnOffProduction: "關閉",
    TurnOffProductionDesc: "關閉建築物的生產。該建築將不再運輸資源和使用電力",
    ApplyToAll: "應用於所有 %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "無限",
    Transport: "運輸",
    TileModifier: "瓷磚修飾器",
    ShowAllModifiers: "顯示所有修飾器",
    HideAllModifiers: "隱藏所有修飾器",
    NumberOfBuildings: "您擁有的建築物數量",
    ShowContent: "顯示內容",
    HideContent: "隱藏內容",
    BuyExpansionPack: "以 %{price}購買",
    Cities: "城市",
    WarehouseInputCapacityDesc: "倉庫每秒可將每種資源運輸入內的數量",
    InputStrategy: "輸入策略",
    InputStrategyClose: "更近",
    InputStrategyCloseDesc: "選擇最近的，且有足夠資源的倉庫",
    InputStrategyFar: "更遠",
    InputStrategyFarDesc: "選擇最遠的，且有足夠的資源的倉庫",
    InputStrategyAmount: "數量",
    InputStrategyAmountDesc: "無論距離如何，都偏好資源量最大的倉庫",
    FuelCostSave: "節省燃料成本",
    FuelCostSaveDesc: "與其他建築物相比，倉庫可節省一定比例的燃料以用於運輸資源入內，等級越高，節省的費用就越多",
    SoftwareCompany: "軟件公司",
    Software: "軟件",
    ScreenFactory: "屏幕工廠",
    Screen: "屏幕",
    JoinDiscord: "加入我們的Discord服務器以獲取最新更新，技巧和討論",
    ClaimOfflineEarning: "獲取離線收益",
    OfflineTime: "離線時間",
    Minutes: "%{time}分鐘",
    MaxUpgrade: "最大升級",
    MaxUpgradeDesc: "您已達到最大升級",
    ClaimAmount: "現金 +%{amount}",
    EarningPerMinute: "收益率",
    EffectiveTime: "有效時間",
    EffectiveTimeDesc: "您的有效離線收入時間不超過 %{time}min.",
    BuildSearchPlaceholder: "輸入要搜索的建築物或資源的名稱",
    MineOverlayWarning: "%{building} 不受瓷磚修飾器的影響",
    WholesaleCenter: "批發站",
    OrderFrom: "來自%{name}的訂單",
    ExpireIn: "到期",
    ProfitMargin: "利潤率",
    NotMakingProfitWarning: "💡 生產不盈利，請考慮將其關閉",
    TurnOnAllProductions: "生產開始",
    TurnOnAllProductionsDesc: "打開所有建築物的生產，在「節省成本」策略處於活動狀態時無法使用",
    OperationSuccessful: "此操作已成功完成",
    TurnOn: "打開",
    Reward: "獎勵",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/周期",
    PolicyPoint: "策略點",
    PolicyPointPerMinute: "生產速率",
    PolicyPointPerMinuteDesc: "您在遊戲中每分鐘都會獲得策略點",
    YourWilLGaimPolicyPoints: " 您將在%{time}s內獲得%{amount}個策略點",
    PolicyPointDesc: "💡 開啟越多策略，每個策略的成本就越高",
    NextOrderIn: "下一個訂單還需",
    FillOrder: "成交訂單",
    RejectOrder: "跳過",
    YouHave: "您有%{amount}",
    WholesaleCenterLocked: "您至少需要%{required}種不同資源解鎖批發中心。您只有%{current}種資源",
    OrderFilled: "來自 %{from} 的訂單已成功成交！",
    PolicyCenter: "政策中心",
    NewOrder: "來自 %{from} 的新訂單已到，請在批發站查看",
    Policies: "政策",
    PolicyNotEnoughTime: "此政策您沒有足夠的政策點",
    TimeLeft: "剩餘 %{time}",
    WholesaleCenterOrderFaster: "世界博覽會",
    WholesaleCenterOrderFasterDesc: "批發站收到的訂單快2倍，訂單大小大2倍",
    PolicyOilWellPowerx2: "增壓油井",
    PolicyOilWellPowerx2Desc: "油井產生2倍的石油，並使用2倍的電力",
    HalfTransportSpeed: "慢下來保存",
    HalfTransportSpeedDesc: "運輸速度降低25%，燃料成本降低25%",
    RefineryMoreOil: "更多汽油，更多問題",
    RefineryMoreOilDesc: "煉油廠的汽油產量增加50%，塑料的產量減少50%",
    StickyInput: "粘性輸入",
    StickyInputDesc: "建築物將傾向於從以前的來源進行運輸，而不是每個周期都尋找最佳的來源（免費政策）",
    RefineryMorePlastic: "更多塑料，更多問題",
    RefineryMorePlasticDesc: "煉油廠的汽油產量減少50％，塑料的產量增加50％",
    FreeOilTransport: "免費石油運輸",
    FreeOilTransportDesc: "石油運輸無需花費燃料，但油井使用的電力是原來的2倍",
    SuperSteelMill: "鋼鐵雄心",
    SuperSteelMillDesc: "鋼鐵廠的煤炭消耗量減少50％，鐵消耗量增加25％，電力消耗增加25％",
    AlSemiconductor: "鋁電路",
    AlSemiconductorDesc: "電路代工廠使用鋁代替銅",
    CostSaver: "節約成本",
    CostSaverDesc: "如果建築物的投入成本大於產出，則停止生產",
    CostSaverBuildingDesc: "節省費用政策已生效，生產將根據其獲利能力自動打開/關閉",
    CostSaverBuildingWarning: "成本節省程序策略處於活動狀態，您不能手動更改生產",
    GlassUseCoal: "黑玻璃",
    GlassUseCoalDesc: "玻璃工廠使用的煤炭多50％，硅減少50％",
    AdjacentBonusOnlyOutput: "相鄰加成Plus",
    AdjacentBonusOnlyOutputDesc: "相鄰的加成不需要更多的輸入，但是會消耗更多的電力，並且只有50％的效率",
    IronMine2xOutput: "鍍鋅鐵皮",
    IronMine2xOutputDesc: "鐵礦場產生2倍的鐵，但運輸鐵消耗2倍的燃料",
    SolarPanelAlwaysWork: "太陽永不落山",
    SolarPanelAlwaysWorkDesc: "太陽能板在100％的時間工作，但產生的電力少60％",
    SteelScience: "鋼鐵知識",
    SteelScienceDesc: "鋼廠使用2倍的輸入並產生額外的科學點",
    ShowWarehouse: "解鎖倉庫",
    ShowWarehouseDesc: "倉庫是一棟特殊的建築物，只運輸和存儲資源，並且可以節省燃料（免費政策）",
    WholesaleCenterProducingOnly: "批發合作夥伴",
    WholesaleCenterProducingOnlyDesc:
        "批發中心訂單僅包含當前正在生產的資源（您還需要提供一定數量的資源才能解鎖批發中心）",
    ShoppingSpree: "瘋狂購物",
    ShoppingSpreeDesc: "如果資源的輸出量不足，從貿易中心自動購買短缺量（如果該資源已自動出售，則將被忽略）",
    ShoppingSpreeTradeCenterDesc: "💡 瘋狂購物政策已啟用，貿易中心將自動購買短缺的資源",
    ExtraPolicyPoints: "政治說客",
    ExtraPolicyPointsDesc: "將政策點的生產能力提高50%",
    CrAlloyUseFe: "鉻",
    CrAlloyUseFeDesc: "鉻合金工廠不使用鋰，而是2倍於鋰用量的鐵",
    DoubleTileModifier: "自然的力量",
    DoubleTileModifierDesc: "所有圖塊的修飾器的效果x2-包括正數和負數",
    TileModifierOutputOnly: "瓷磚修飾器Plus",
    TileModifierOutputOnlyDesc: "瓷磚修飾器僅影響輸出，而非輸入和輸出，但僅有原來的50％有效",
    GasPlantPetrol: "天然氣液化",
    GasPlantPetrolDesc: "天然氣發電廠使用額外的天然氣生產汽油",
    BuildingRecycle: "建築回收",
    BuildingRecycleDesc: "在建造後1分鐘內出售建築物，可獲得全額退款",
    CoalPlantFuel: "煤炭液化",
    CoalPlantFuelDesc: "煤炭發電廠使用額外的煤炭生產汽油",
    Welcome: "歡迎",
    SeeTutorialAgain: "恢復教程",
    ReadSteamGuide: "Steam官方指南",
    HelpTranslateTheGame: "幫助翻譯遊戲🌐",
    SkipTutorial: "跳過教程",
    NextTutorial: "下一步",
    Tutorial1:
        "閒置工業是一款 <em>資源管理</em>建造遊戲🏭在這裡你可以建立工廠, 生產商品📦 並賺錢💸.<br><br>讓我們通過一些基本的概念介紹幫助讓你開始-這不會花很長時間，我保證",
    Tutorial2:
        "所有建築物都需要電力⚡, 您有一台<em>風力發電機</em>可以發電。您可以在左上角看到當前的電力情況.<br><br>您可能已經注意到，風力發電機僅在 <em>80%</em> 的時間內工作。 您可以考慮建造其他種類的發電廠，來產生穩定的電力。",
    Tutorial3:
        "您有很多 <em>資源節點</em> 在地圖上. 要提取資源, 您必須建造開採設備⛏️ <em>在相應的資源節點之上</em>。<br><br>例如, 您有一口 <em>油井🛢️</em>  <em>從石油礦藏中開採石油</em>.<br></br>資源存款是無限的 - 無需擔心它們耗盡。除了開採設備，其他建築物可以在任何空瓷磚上建造",
    Tutorial4:
        "資源運輸成本燃料。在這個地圖上， 您可以使用 <em>汽油⛽</em> 作為燃料。你有一個 <em>煉油廠</em>它將石油從油井開採並生產出汽油<br><br>微小的移動<em>點</em> 代表資源的實時運動。 您應該優化您的建築位置，以最大限度地減少資源運輸的距離.<br><br><em>升級</em>您的建築將增加其產量, 但也將增加它們的電力使用和輸入.<br><br>您可以在運輸中心🚦改變燃料種類.記得確保您的燃料生產高於消耗，否則您的生產將在燃料耗盡時停止生產",
    Tutorial5:
        "為了賺錢，您需要通過貿易中心出口你的資源。為此，只需打開 <em>該資源的</em>自動銷售.<br></br>您也可以從貿易中心購買資源。. 記住 <em>如果您購買某一種資源，您將推高價格</em> 如果您銷售某一種資源，您將推低價格.<br><br>市場 <em>波動很大</em>價格📈 定期更換。",
    Tutorial6:
        "要建造新建築物，您需要先在<em>研究實驗室🧪</em>中將其解鎖. 研究實驗室還將科學轉換為研究點。<br><br>您的風力發電機（和其他發電廠）在運行時會產生少量科學。 你可以建造學校🏫 和其他專用建築物來促進科學發展.<br><br>現在您已經了解到所有基礎知識，開始建立您的經濟！這裡有一些<em>現金💸</em>和 <em>汽油⛽</em> 給你一個啟動的開始。",
    WelcomePlay: "開始遊戲",
    WelcomePlayMuted: "開始遊戲 (🔇靜音)",
    Changelog: "變更日誌",
    ChangelogGotIt: "知道",
    Chat: "聊天",
    Send: "發送",
    Import: "導入",
    Export: "導出",
    SteamCloudBackup: "Steam雲備份",
    LastBackupAt: "最後備份",
    RestoreFromBackup: "從備份還原",
    RestoreFromBackupFail: "無法從Steam Cloud恢復備份：您確定有備份嗎？",
    RestoreFromBackupTitle: "確定嗎？",
    RestoreFromBackupDesc: "通常，您不需要從雲備份中進行還原，除非丟失了本地保存。雲備份比本地保存要早一些",
    ChatMessages: "聊天消息",
    ChatPlaceholder: "輸入您的消息：最多100個字符",
    ChangeName: "更改",
    SaveName: "保存",
    NameValidationRule: "您的姓名只能包含字母和數字，且長度為5至15個字符",
    NameValidationRuleProfanity: "您的名字不應該包含違規字符",
    ChatMessageRateLimit: "您只能每10秒發送一次新的聊天消息",
    NameSaved: "您的名稱已成功更改",
    NoMessages: "沒有新消息",
    Leaderboard: "排行榜",
    LeaderboardDesc: "排行榜得分是您所賺取的所有瑞士貨幣",
    Name: "名稱",
    Rank: "排名",
    Tips1: "股票評級分為5個等級：買入，跑贏大盤，持有，跑輸大盤和賣出",
    Tips2: "除非有足夠的生產能力，否則建築物將停止運輸資源，除非您啟用庫存模式",
    Tips3: "資源運輸的燃料成本取決於距離和資源量",
    Tips4: "只有在地圖上找到的數量超過輸入容量的情況下，建築物才會運輸資源",
    Tips5: "只有為該資源關閉自動銷售功能，建築物才會從貿易中心運輸該資源",
    Tips6: "您可以在相應的輸入容量部分下查看資源的燃料成本",
    Tips7: "如果您購買資源，則會提高價格。如果您出售資源，則會降低價格",
    Tips8: "您可以在統計局中查看每種資源的數量及其隨時間變化的圖表",
    Tips9: "建築物所需的研究點取決於其投入資源的市場價格",
    Tips10: "不同的資源在市場中的定價不同-隨時為市場波動做好準備",
    Tips11: "在擴大生產之前，始終檢查功率和燃料供應是一個好主意",
    FPS30: "節能",
    OfflineModeDesc: "無法連接到服務器：將不會產生離線收入。請檢查您的互聯網連接",
    OptOut: "選擇退出",
    OptIn: "重置並啟用",
    LeaderboardOptOut: "退出排行榜",
    LeaderboardOptOutDesc: "這將不再發送排行榜得分。請注意：如果以後要啟用排行榜，則需要重置數據",
    LeaderboardOptIn: "重置並啟用排行榜",
    LeaderboardOptInDesc: "您必須先重置您的數據，然後才能重新啟用排行榜，確定嗎？",
    RewardAdsFailed: "獎勵視頻未完成",
    RewardAdsNotAvailable: "獎勵視頻不可用 (當前僅支持iOS/Android)",
    OfflineEarningDoubleSuccess: "您的離線收入已增加了一倍",
    FPS30Desc: "打開節能模式將使遊戲以30FPS而非60FPS的幀率運行。這將延長您的電池續航時間",
    HighlightAll: '高亮顯示 "%{type}"',
    HighlightInput: "🔍 高亮顯示 %{type} 輸入",
    HighlightOutput: "🔍 高亮顯示 %{type} 輸出",
    TotalInput: "總輸入量",
    TotalOutput: "總輸出量",
    RunOutIn: "在 %{time}內用完",
    FuelRunOutWarning: "💡 您的燃料消耗超過了生產。當燃料用完時，您的運輸將停止",
    InAmount: "輸入: %{number}",
    OutAmount: "輸出: %{number}",
    SwissBank: "瑞士銀行",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "如果您從一個新城市開始，您將獲得 %{money} 💵",
    RestorePurchases: "恢復購買",
    RestorePurchasesSuccess: "您的購買已恢復",
    RestorePurchasesFailed: "您的購買未恢復",
    ExpansionPacks: "拓展包",
    ExpansionPack1: "拓展包1",
    ExpansionPack1Owned: "拓展包 1",
    RequireExpansionPack1: "拓展包 1",
    RequireExpansionPack1Desc: "這僅適用於拓展包 1",
    RequireAnyExpansionPack: "獨家拓展包",
    RequireAnyExpansionPackDesc: "此功能要求您至少擁有一個擴展包",
    HideRewardAd: "隱藏獎勵廣告",
    HideRewardAdDesc: "所有遊戲內廣告都是可選的獎勵廣告。這將從遊戲中隱藏所有獎勵廣告選項。",
    HideDiscordBanner: "隱藏Discord橫幅",
    HideDiscordBannerDesc: "隱藏總部的Discord和商店橫幅",
    HideChat: "隱藏聊天消息",
    HideChatDesc: "從底部工具欄隱藏聊天消息",
    SortedByDeficit: "按赤字排序",
    PurchaseFailed: "購買未完成",
    PurchaseSteamContinue: "請在Steam上完成購買",
    PurchaseSuccess: "購買已完成，感謝您的支持",
    PrestigeCurrency: "瑞士貨幣 💵",
    RestartDesc: "💡 想要重啟？您可以點擊上方的在新城市開始並選擇您的新城市",
    PrestigeGoBack: "返回",
    PermanentUpgradeDesc: "如果您從新城市開始，此項升級將會保持",
    ProductionMultiplier: "生產乘數",
    ProductionMultiplierDesc: "提高您所有建築物的生產能力（包括礦山，工廠，發電廠，科學和文化建築物）",
    FuelCostDiscount: "燃料成本折扣",
    FuelCostDiscountDesc: "在運輸資源時為燃料成本提供折扣",
    AutoSellCapacityMultiplier: "自動銷售能力乘數",
    AutoSellCapacityMultiplierDesc: "不管當前容量如何，都將應用於您的自動銷售容量的乘數",
    BuildingPermitCostDivider: "建築許可證成本除數",
    BuildingPermitCostDividerDesc: "建築許可成本除以該除數",
    ExtraAdjacentBonus: "額外相鄰加成",
    ExtraAdjacentBonusDesc: "每個相鄰的相同類型的工作中建築物的額外加成量",
    OfflineEarningMultiplier: "離線收益乘數",
    OfflineEarningMultiplierDesc: "適用於離線收益的乘數",
    PrestigeAlertTitle: "確定嗎?",
    PrestigeAlertContent: "您的公司將被清算。您將以 %{amount} 瑞士貨幣兌現並以 %{city}成立新公司",
    PrestigeCurrencyDesc: "這是您在秘密瑞士銀行帳戶的錢，您可以帶上它在一個新的城市重新開始",
    Prestige: "現金到位",
    Cancel: "取消",
    SaveFileCorrupted: "存檔文件損壞",
    CheatDetected: "您的舊存檔未通過服務器驗證，無法讀取。您將以新存檔開始",
    LoadGameError: "無法加載遊戲",
    LoadGameErrorMessage: "錯誤消息: %{message}",
    LoadGameErrorDesc: "請檢查您的互聯網連接。如果問題仍然存在，請聯繫支持人員",
    ExpansionPackIncompatible: "您正在使用擴展包導入保存，但您的遊戲沒有所需的擴展包",
    SaveFileMigrated: "新時代：Beta測試在此",
    SaveFileMigratedDesc: "感謝您參與遊戲的alpha測試。您的舊地圖不兼容，但是我們已經遷移了您的數據並為您提供了一些獎勵",
    ClaimSwissMoney: "獲取 %{amount} 瑞士貨幣 💵",
    SaveFileMigratedFinePrint:
        "您的市值轉換為瑞士貨幣，您未使用的瑞士貨幣將結轉。您將獲得額外50％的瑞士貨幣作為參與遊戲alpha測試的獎金。可結轉的瑞士貨幣上限為200",
    CashIn: "現金",
    CurrentCity: "當前城市",
    CashInDesc:
        "如果您在一個新的城市開始，您將把這筆款項存入您的瑞士銀行帳戶。這是基於您公司的市值，並且必須達到 %{amount} 才能賺取瑞士貨幣",
    MoveToNewMap: "重新城市開始",
    CityName: "城市",
    CitySize: "地圖大小",
    GridType: "網格類型",
    StartInThisCity: "從 %{city}開始",
    CityBonus: "城市獎勵",
    ResourceTilePercentage: "資源格",
    MapSquareGrid: "正方形",
    MapHexGrid: "六邊形",
    Stockholm: "斯德哥爾摩",
    StockholmBonus:
        "<li> 免費的4級風力發電機x1 </ li> <li> 免費的4級油井x1 </ li> <li> 免費的2級級煉油廠x1 </ li> <li>造紙廠已解鎖</ li > <li>伐木場有2倍的輸出量</ li>",
    Rotterdam: "鹿特丹",
    RotterdamBonus:
        "<li>鋼廠的產能是原來的2倍</ li> <li>不鏽鋼廠的產能是原來的2倍</ li> <li>免費鐵運輸</ li> <li>鋼運輸的燃料成本降低了50％</ li> <li>以2倍的自動銷售容量開始</ li> <li>沒有磁貼修飾符</ li>",
    Oslo: "奧斯陸",
    OsloBonus:
        "<li>煉油廠的產能是原來的2倍</ li> <li>天然氣加工廠的產能是原來的2倍 </ li> <li>汽油發電廠具有2倍產能</ li> <li>鋼廠使用天然氣而不是煤炭</ li> <li>免費石油運輸</ li>",
    StPetersburg: "聖彼得堡",
    StPetersburgBonus:
        "<li>鈾礦場的產量是2倍</ li> <li>鈾濃縮廠的能力是原來的2倍</ li> <li>鈾的運輸成本降低了50％的燃料</ li> <li>免費的槍支運輸</ li> <li>導彈工廠使用濃縮鈾代替鈦和鈾</ li>",
    Hamburg: "漢堡",
    HamburgBonus:
        "<li>齊柏林飛艇工廠解鎖</ li> <li>半導體工廠的產能是原來的2倍</ li> <li>造船廠的產能是原來的2倍</ li> <li>汽車工廠的產能是原來的2倍 </ li> <li>鋰離子電池工廠已解鎖</ li>",
    Toulouse: "圖盧茲",
    ToulouseBonus:
        "鈦礦場的產量是原來的2倍</ li> <li>鈾濃縮工廠的產量是原來的2倍</ li> <li>噴氣發動機工廠的產能是原來的2倍</ li> <li>飛機工廠的產能是原來的2倍</ li > <li>火箭工廠使用鈾代替濃縮鈾</ li>",
    Rome: "羅馬",
    RomeBonus:
        "<li>大競技場解鎖</ li> <li>大競技場的生產率是原來的2倍</ li> <li>從5級政策中心開始</ li> <li>歌劇院的能力是原來的2倍</ li> <li>錄音室也產生文化</ li>",
    Detroit: "底特律",
    DetroitBonus:
        "<li>發動機工廠已解鎖</li><li>發動機工廠的生產率是原來的2倍</li><li>汽車工廠的產能是原來的2倍</li><li>汽車工廠不需要電池</li><li>火車工廠的產能是原來的2倍</li>",
    Boston: "波士頓",
    BostonBonus:
        "<li>從5級研究實驗室開始</li><li>理工學院被解鎖</li><li>理工學院的能力是原來的2倍</li><li>學校具有2倍的容量</li><li>大學生產力提高了2倍</li>",
    HideNotProducing: "隱藏未生產的資源",
    SortByStorage: "庫存",
    SortByProduction: "產量",
    SortByName: "名稱",
    BuildingInProgressCannotPrestige: "您的建築正在建造中，在完成之前您不能在新城市開始建造",
    PlayerTrade: "玩家交易",
    AddTradeFail: "添加交易失敗",
    AddTradeValidationFail: "交易金額和價格必須大於0",
    AddTradeExceedMaximumTrade: "您最多只能有 %{number} 個進行中交易，請先領取或者取消其中之一",
    AddTradeSuccess: "您的交易已成功添加",
    LoadTradeFail: "無法加載玩家交易，請稍後再試",
    ClaimTradeFail: "無法領取此交易，請稍後再試",
    ClaimTradeSuccess: "您的交易已成功領取: $%{cash} 已添加到您的賬戶中",
    CancelTradeSuccess: "您的交易已成功取消",
    CancelTradeFail: "無法取消此交易，請稍後再試",
    AcceptTradeSuccess: "您已接受此交易: %{resource}已添加到您的交易中心",
    AcceptTradeFail: "無法接受此交易，請稍後再試",
    PlayerTradeBanner: "與其他玩家交易資源",
    PlayerTradeResource: "資源",
    PlayerTradeAmount: "金額",
    PlayerTradePrice: "價格 $",
    PlayerTradeValue: "價值 $",
    PlayerTradeWaiting: "正在等待...",
    UseTradeCenterPrice: "使用貿易中心價格",
    AddTrade: "添加交易",
    ActiveTrades: "進行中交易",
    AcceptTrade: "接受",
    CancelTrade: "取消",
    ClaimTrade: "領取",
    RefreshTrade: "刷新",
    RefundTrade: "退款",
    RefundTradeSuccess: "該交易已退款: %{resource}已退還給您的貿易中心",
    RefundTradeFail: "未能退款此交易, 請稍後再試",
    PasteYourSave: "請粘貼您的存檔數據",
    FailedToImportSave: "無法導入存檔",
    FailedToImportSaveDesc: "您的存檔文件不兼容或損壞: %{error}",
    SaveCopiedToClipboard: "您的存檔數據已被複製到您的剪貼板",
    CancelActiveTradeFirst: "您有進行中的玩家交易，請先取消/領取",
    FailedToCheckActiveTrade: "未能檢查進行中的玩家交易, 請稍後再試",
    PlayerTradePriceNotValid: "交易價格必須介於 %{min} 與 %{max} (2倍於上次市場更新價格)",
    PlayerTradeQuotaExceed: "該交易已超過您的配額",
    PlayerTradeAmountNotValid: "交易金額必須大於0",
    PlayerTradeValidRange: "範圍: %{min} ~ %{max}",
    PlayerTradeFilterPrice: "低於市場價格",
    PlayerTradeFilterCanAfford: "買得起",
    PlayerTradeQuota: "剩餘配額: %{value}",
    PlayerTradeUnavailable: "在與玩家進行交易之前，你需要在生產和存儲中至少有一個資源",
    PlayerTradeToClaim: "您有 %{num} 宗玩家交易待領取",
    PowerBank: "電池組",
    PowerBankBuildDesc: "存儲過剩的電力，在電力短缺時提供電能",
    PowerBankChargeSpeed: "充電速度",
    PowerBankPowerLeft: "電量剩餘",
    PowerBankMoreCapacity: "電池保護",
    PowerBankMoreCapacityDesc: "電池組的充電速度只有原來50%，但是多50%容量",
    PowerBankNotWorking: "⛔ 電池組只在緊鄰發電廠時工作",
    ExcludeBuildingsShutdown: "被關閉的建築除外",
    ColorTheme: "遊戲顏色主題",
    ColorThemeDesc: "顏色主題應用於遊戲圖標，高亮，網格和背景。需要重啟生效",
    WarehouseBuildDesc: "以更低的燃料消耗運輸及存儲任何資源",
    SiliconMine2xOutput: "硅谷",
    SiliconMine2xOutputDesc: "硅礦場生產2倍的硅，但用電量增加50%，運輸硅的燃料消耗增加50%",
    CoalMine2xOutput: "工業革命",
    CoalMine2xOutputDesc: "煤礦場生產2倍的煤，但用電量增加50%，運輸煤的燃料消耗增加50%",
    AlMine2xOutput: "鋁電解",
    AlMine2xOutputDesc: "鋁礦場產生2倍的鋁，但消耗2倍的電力",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "伐木場產生2倍的鐵，但運輸木頭消耗2倍的燃料",
    HideResourceMovement: "隱藏資源移動",
    HideResourceMovementDesc: "這將默認隱藏資源移動（那些小點），僅在選擇建築時顯示相關資源移動",
    PowerBankLeft: "電池組",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "A new message mentions you: %{message}",
    HideChatMentions: "Hide Chat Mentions",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Cancel This Trade?",
    CancelTradeConfirmDialogDesc:
        "Cancelling this trade will refund %{percent} of the resource to the Trade Center warehouse",
    CancelTradeConfirmDialogYes: "Yes",
    CancelTradeConfirmDialogNo: "No",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Add Route",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Find on Map",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Surplus",
    Production: "Production",
    Consumption: "Consumption",
    WarehouseInputCapacityDescV2: "Total capacity of inward transportation, divided equally among all routes",
    WarehouseInputCapacityPerRoute: "Per Route: ",
    PlayerCountryFlag: "Player Flag",
    PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
    WindTurbineAlwaysWork: "The Wind Rises",
    WindTurbineAlwaysWorkDesc: "Wind turbines work 100% of the time but produces 30% less power",
    BookPublisherScience: "Science Literature",
    BookPublisherScienceDesc: "Book publishers produce science instead of culture",
    WarehouseOutwardFuelSave: "Free Delivery",
    WarehouseOutwardFuelSaveDesc: "Warehouses provide the same fuel save on outward transportation as well",
    ImportSaveVersionTooNew:
        "You are importing a save from %{saveVersion} but your game is %{gameVersion}. Please upgrade your game first",
    BatteryFuelEconomy: "Rechargeable Battery",
    BatteryFuelEconomyDesc: "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
    ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
    SpecialTransportCost: "Resources with Special Transport Cost",
    FreeTransportCost: "Resources with Free Transport Cost",
};
