export const ZH = {
    Translator: "译者",
    TranslatorName: "LazySu",
    Language: "语言",
    ThisLanguage: "中文",
    OK: "好的",
    SteelMill: "钢厂",
    StainlessSteelPlant: "不锈钢厂",
    CircuitFoundry: "电路铸造厂",
    IntegratedCircuit: "集成电路",
    OilWell: "油井",
    Wood: "木头",
    LoggingCamp: "伐木蓬",
    LumberMill: "伐木工坊",
    Lumber: "木材",
    Paper: "纸张",
    PaperMill: "造纸厂",
    Book: "书本",
    BookPublisher: "图书出版社",
    OilRefinery: "炼油厂",
    Sell: "出售",
    Upgrade: "升级",
    Build: "建造",
    Inspect: "检查",
    Buildings: "建筑物",
    Iron: "铁",
    Actions: "行动",
    FuelType: "选择燃料",
    FuelCost: "燃料费用",
    FuelConsumption: "%{fuel} 油耗",
    FuelEconomy: "燃烧效率",
    FuelProduction: "%{fuel} 生产",
    FuelInStorage: "%{fuel} 储存",
    Plastic: "塑料",
    FuelSurplus: "%{fuel} 过剩",
    Petrol: "汽油",
    Buy: "购买",
    NoLiquidity: "无流动性",
    NoLiquidityTurnOffAutoSell: "市场没有足够的流动性为 %{res}, 自动销售已被关闭",
    Multiplier: "乘数",
    MultiplierDesc: "每升级10个级别, 你将得到+1个乘数",
    SellBuilding: "出售建筑物",
    PowerGrid: "电力系统",
    TradeAmount: "贸易额",
    SortBy: "排序",
    SortByPrice: "价格",
    SortByAmount: "数量",
    NotEnoughResourcesForTrade: "贸易中心没有足够的资源用于此贸易",
    NotEnoughResources: "没有足够的资源为这次行动",
    Transportation: "运输系统",
    Cash: "现金",
    Aluminum: "铝",
    ResearchPoint: "研究点",
    Unlock: "解锁",
    BuildingUnlocked: "%{building} 已解锁",
    Science: "科学",
    ScienceFromPowerDesc: "发电厂发电时产生少量的科学点",
    Culture: "文化",
    School: "学校",
    University: "大学",
    Polytechnic: "理工",
    Colosseum: "大竞技场",
    WindTurbine: "风力发电机",
    Engine: "引擎",
    EngineFactory: "引擎工厂",
    CameraFactory: "照相机工厂",
    Camera: "照相机",
    Gun: "枪",
    GunFactory: "枪械工厂",
    Aircraft: "飞机",
    AircraftFactory: "飞机工厂",
    Zeppelin: "齐柏林飞艇",
    ZeppelinFactory: "齐柏林飞艇工厂",
    Tank: "坦克",
    TankFactory: "坦克工厂",
    MinimumTradingAmount: "交易金额不能低于最低金额",
    CoalPowerPlant: "燃煤发电",
    PetrolPowerPlant: "燃油发电",
    Copper: "铜",
    Gas: "天然气",
    GasPump: "天然气泵",
    GasPowerPlant: "天然气发电",
    Missile: "导弹",
    MissileFactory: "导弹工厂",
    Rocket: "火箭",
    RocketFactory: "火箭工厂",
    BuildingPermit: "建筑许可证",
    BuildingPermitDesc: "您已获得 %{amount} 建筑物,您已经构建了 %{amountBuilt}并且还剩下了 %{amountLeft} 金额",
    BuildingLocked: "建筑物不可用，您需要先在研究室解锁它",
    BuildQueue: "建筑队列",
    BuildQueueDesc: "目前排队的建筑数量",
    MaxBuilders: "最大建筑者",
    MaxBuildersDesc: "您可以同时建造的建筑物数量",
    Silicon: "硅",
    AluminumMine: "铝矿",
    CopperMine: "铜矿",
    SiliconMine: "硅矿",
    IronMine: "铁矿",
    CoalMine: "煤矿",
    Headquarter: "总部",
    ResearchLab: "研究实验室",
    TradeCenter: "贸易中心",
    Resources: "资源",
    NotEnoughPower: "💡 电力不足，考虑增加电力供应",
    NotEnoughFuel: "没有足够的 %{fuel} 为这次行动",
    NotEnoughCash: "这次行动没有足够的现金",
    NotEnoughSwissMoney: "没有足够的瑞士资金用于这次行动",
    BuildingNotEnoughFuel: "💡 不够 %{fuel}",
    AutoSell: "自动出售",
    SellAll: "全部出售",
    Change: "更改",
    StatisticsBureau: "统计机构",
    LogisticsDepartment: "后勤部",
    From: "从",
    Top20FuelCost: "前20个燃料成本",
    To: "到",
    TransportTime: "运输时间",
    TopN: "顶部 %{n}",
    Warehouse: "仓库",
    TradeWarehouse: "货运仓库",
    Coal: "煤",
    Video: "录像",
    ClothingFactory: "服装工厂",
    Clothes: "衣服",
    Fashion: "塑造",
    FashionFactory: "塑造工厂",
    VideoFarm: "录像农场",
    SantaFactory: "檀香工厂",
    Santa: "檀香",
    Car: "汽车",
    CarFactory: "汽车工厂",
    Ship: "船",
    SolarPanel: "太阳能电池板",
    SolarPanelDesc: "💡 太阳能电池板每10秒只能工作5秒-所有的循环都是一致的",
    WindTurbineDesc: "💡 风力发电机每10秒只工作8秒-循环不一致",
    Movie: "影片",
    MovieStudio: "电影工作室",
    Sitcom: "剧情",
    TVStudio: "电视工作室",
    PC: "电脑",
    GameStudio: "游戏工作室",
    Game: "游戏",
    ComputerFactory: "计算机工厂",
    Shipyard: "船厂",
    PowerUsage: "电力使用",
    PowerSupply: "电源",
    PowerSurplus: "电力过剩",
    Level: "级别",
    Power: "功率",
    CentralBank: "主要银行",
    ResourceInput: "在",
    ResourceOutput: "退出",
    ResourceStorage: "存储",
    ResourceChange: "改变",
    ResourceInOutDesc: "💡 电击上面的输出数字，以显示相应的输出和输入建筑物",
    ResourceChart: "资源图",
    MarketUpdateIn: "市场更新在 %{time}",
    Income: "收入",
    Semiconductor: "半导体",
    SemiconductorFactory: "半导体工厂",
    SemiconductorFab: "绝妙的半导体",
    Steel: "钢",
    Bitcoin: "比特币",
    BitcoinFarm: "比特币农场",
    Dogecoin: "狗狗币",
    DogecoinFarm: "狗狗币农场",
    Guitar: "吉他",
    GuitarFactory: "吉他工厂",
    Drum: "鼓",
    DrumFactory: "鼓工厂",
    RecordingStudio: "录音室",
    OperaHouse: "歌剧院",
    CoalGasificationPlant: "煤气化加工厂",
    GasProcessingPlant: "天然气加工厂",
    Music: "音乐",
    Glass: "玻璃",
    PhoneFactory: "电话工厂",
    Phone: "电话",
    GlassFactory: "玻璃工厂",
    Oil: "石油",
    Chromium: "铬",
    ChromiumMine: "铬矿",
    Uranium: "铀",
    EnrichedUranium: "浓缩铀",
    NuclearPowerPlant: "核动力加工厂",
    UraniumEnrichmentPlant: "浓缩铀加工厂",
    UraniumMine: "铀矿",
    Titanium: "钛",
    TitaniumMine: "钛矿",
    TitaniumAlloyPlant: "钛合金加工厂",
    ChromiumAlloyPlant: "铬合金加工厂",
    Input: "输入",
    PanelPosition: "面板位置",
    PanelPositionDesc: "显示左,右或自动侧面板 (取决于当前的选定的瓷砖)",
    InputCapacity: "输入容量",
    InputCapacityPerCycle: "输入容量 / 循环",
    Output: "输出",
    OutputCapacity: "输出容量",
    OutputCapacityPerCycle: "输出容量 / 循环",
    ResourceDeposit: "资源矿床",
    RecommendedBuilding: "💡 这块地砖有 %{resource} 存款",
    AdjacentBonus: "相邻奖金",
    AdjacentBonusDesc: "您为同类型的每栋相邻工作建筑物获得%{bonus}%的额外容量",
    ConsiderIncreaseProduction: "💡 考虑增加 %{resource} 生产",
    AlwaysTransportInput: "库存模式",
    AlwaysTransportInputTradeCenter: "始终出口",
    AlwaysTransportInputTradeCenterDesc: "始终将资源运送到贸易中心，即使该资源无法启用自动销售",
    AlwaysTransportInputDesc: "始终运输输入资源，即使它们高于最低生产要求",
    ProductionCycleLength: "生产周期",
    ProductionCycleLengthDesc:
        "一个生产周期的持续时间，以秒为单位测量。延长周期将相应增加每个周期的投入/产出，从而降低获取输入资源时的优先级",
    MaxInputDistance: "最大输入距离",
    MaxInputDistanceDesc: "这栋建筑从瓷砖数量中获取输入资源的最大距离",
    AutoSellCapacity: "自动销售容量",
    AutoSellCapacityDesc: "自动销售的最大资源量可以处理每秒，每资源",
    CurrentAutoSellCapacityMultiplier: "当前乘数: x%{n}",
    AutoSellConcurrency: "自动销售容量",
    AutoSellConcurrencyDesc: "自动销售可以同时处理的最大资源数量",
    MaxAutoSellConcurrencyReached: "您已达到最大自动销售并发，请关闭另一个自动销售以启用此自动销售",
    CannotSellBuilding: "目前不能出售此建筑物",
    WallStreet: "围墙街道",
    MarketCap: "市值",
    MarketCapDesc: "市场价值",
    BuildingValuation: "建筑估值",
    BuildingValuationDesc: "您的建筑物的总价值，包括建筑许可证和升级",
    ResourcesValuation: "资源估值",
    ResourcesValuationDesc: "库存资源总价值",
    Battery: "电池",
    BatteryFactory: "电池工厂",
    RatingBuy: "购买",
    RatingSell: "出售",
    SwissShop: "瑞士的商店",
    RatingHold: "保持",
    RatingOutperform: "表现优异",
    RatingUnderperform: "表现不佳",
    StockRating: "股票评级",
    JetEngine: "喷气发动机",
    Helicopter: "直升机",
    Lithium: "锂",
    LithiumMine: "锂矿",
    LiionBatteryFactory: "锂离子电池工厂",
    HelicopterFactory: "直升机工厂",
    Satellite: "卫星",
    ToyFactory: "玩具工厂",
    Toy: "玩具",
    SpaceStation: "空间站",
    SpaceStationFactory: "空间站工厂",
    OperatingSystem: "操作系统",
    OperatingSystemCompany: "操作系统公司",
    LinuxDistribution: "Linux 分布",
    Internet: "互联网",
    WebBrowser: "网络浏览器",
    Console: "控制台",
    ConsoleFactory: "控制台工厂",
    Train: "火车",
    TrainFactory: "火车工厂",
    ShoeFactory: "鞋工厂",
    Shoes: "鞋",
    ArtilleryFactory: "火炮工厂",
    Artillery: "火炮",
    SubmarineFactory: "潜艇工厂",
    Submarine: "潜艇",
    Spaceship: "太空船",
    RobotFactory: "机器人工厂",
    Robot: "机器人",
    SpaceshipFactory: "太空船工厂",
    SatelliteFactory: "卫星工厂",
    JetEngineFactory: "喷气发动机工厂",
    StockRatingDesc: "来自围墙街道分析师的股票评级共识，它会影响你的市值，并随市场一起更新",
    InterestRate: "过夜利率",
    InterestRateDesc: "您在离线时通过市值赚取的利息",
    OfflineEarning: "离线收益",
    OfflineEarningDesc: "离线收益取决于您的市值和利率",
    PerMin: "%{amount}/分钟",
    OfflineEarningTime: "离线赚取时间",
    OfflineEarningTimeDesc: "您将赚取离线收益高达此阙值",
    BuyPermit: "购买许可证",
    NotEnoughBuildingPermit: "没有足够的建筑许可证，请购买更多来建造新的建筑物",
    MovingAverage: "平均移动",
    MovingAverageDesc: "显示资源变化的移动平均值，而不是实时更改",
    AllowZoom: "缩放",
    AllowZoomDesc: "打开缩放支持。使用鼠标轮进行缩放。当前变焦为 %{zoom}",
    AllowZoomMobileDesc: "打开缩放支持。你可以捏放大。当前变焦为 %{zoom}",
    Settings: "设置",
    SellBuildingDesc: "出售建筑物将退还您 50% 的投资，50% 的资源将运送到贸易中心",
    SellBuildingFullRefundDesc: "建筑回收政策是积极的，出售建筑物将给你全额退款，直到在 %{time}",
    Sound: "声音效果",
    SoundDesc: "打开声音效果，如点击或错误的声音",
    AutoHighlight: "自动点亮",
    AutoHighlightDesc: "当您选择建筑物时，自动突出显示相同类型的建筑物",
    MusicDesc: "打开音乐：Shane Ivers（https://www.silvermansound.com）的《直到The Bossa Nova》还没有结束",
    Credits: "学分",
    Icons: "图标",
    MisplacedBuilding: "⛔ 此 %{building} 不放在正确的资源存款顶部",
    UnderConstruction: "%{building} 正在建设中",
    Left: "左",
    Right: "右",
    Auto: "自动",
    HighlightBuildings: "点亮建筑",
    HighlightTurnedOff: "...被关闭",
    HighlightStockpileModeOn: "...有库存模式",
    HighlightWarehouseOnly: "...只供应仓库",
    HighlightProductionCycleNotDefault: "...生产周期 > 1",
    HighlightMaxInputDistanceNotDefault: "...具有最大输入距离 < ∞",
    HighlightNotMakingProfit: "...不盈利",
    NBuildingsAreHighlighted: "%{n} 建筑物被突出显示",
    OnlyToWarehouse: "只为仓库",
    OnlyToWarehouseDesc: "只有仓库才能从这座建筑物里运送资源",
    TurnOffProduction: "关闭",
    TurnOffProductionDesc: "关闭建筑物的生产。该建筑将不再运输资源和使用电力",
    ApplyToAll: "适用于所有 %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "无限",
    Transport: "运输",
    TileModifier: "瓷砖修饰器",
    ShowAllModifiers: "显示所有修改器",
    HideAllModifiers: "隐藏所有修改器",
    NumberOfBuildings: "您拥有的建筑物数量",
    ShowContent: "显示内容",
    HideContent: "隐藏内容",
    BuyExpansionPack: "以 %{price}购买",
    Cities: "城市",
    WarehouseInputCapacityDesc: "仓库每秒可向内运输的资源量，每种资源.",
    WarehouseBuildDesc: "仓库可以运输和存储任何资源s",
    InputStrategy: "输入策略",
    InputStrategyClose: "关闭",
    InputStrategyCloseDesc: "选择最接近的仓库，有足够的资源",
    InputStrategyFar: "更远",
    InputStrategyFarDesc: "选择最远的仓库，有足够的资源",
    InputStrategyAmount: "数量",
    InputStrategyAmountDesc: "无论距离如何，都更喜欢资源量最大的仓库",
    FuelCostSave: "节省燃料成本",
    FuelCostSaveDesc: "与其他建筑物相比，仓库可节省一定比例的燃料以用于向内运输资源，等级越高，节省的费用就越多",
    SoftwareCompany: "软件公司",
    Software: "软件",
    ScreenFactory: "屏幕工厂",
    Screen: "屏幕",
    JoinDiscord: "加入我们的Discord服务器以获取最新更新，技巧和讨论",
    ClaimOfflineEarning: "申请离线收益",
    OfflineTime: "离线时间",
    Minutes: "%{time}分钟",
    MaxUpgrade: "最大升级",
    MaxUpgradeDesc: "您已达到最大升级",
    ClaimAmount: "现金 +%{amount}",
    EarningPerMinute: "收益率",
    EffectiveTime: "有效时间",
    EffectiveTimeDesc: "您的有效离线收入时间不得超过 %{time}时间.",
    BuildSearchPlaceholder: "输入要搜索的建筑物或资源的名称",
    MineOverlayWarning: "%{building} 不受瓷砖修改器的影响",
    WholesaleCenter: "批发站",
    OrderFrom: "来自 %{name}的订单",
    ExpireIn: "到期",
    ProfitMargin: "利润率",
    NotMakingProfitWarning: "💡 生产不盈利，请考虑将其关闭",
    TurnOnAllProductions: "生产开始",
    TurnOnAllProductionsDesc: "打开所有建筑物的生产，在“节省成本”策略处于活动状态时无法使用",
    OperationSuccessful: "此操作已成功完成",
    TurnOn: "打开",
    Reward: "奖励",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/周期",
    PolicyPoint: "策略点",
    PolicyPointPerMinute: "生产速率",
    PolicyPointPerMinuteDesc: "您在游戏中每分钟都会获得策略点",
    YourWilLGaimPolicyPoints: " 您将在%{time}s内获得%{amount}个策略点",
    PolicyPointDesc: "💡 策略越活跃，每个策略的成本就越高",
    NextOrderIn: "下一个订单在",
    FillOrder: "填写订单",
    RejectOrder: "通过",
    YouHave: "您有 %{amount}",
    WholesaleCenterLocked: "您至少需要 %{required} 不同资源解锁批发中心。您只有 %{current} 资源",
    OrderFilled: "来自 %{from} 的订单已成功填写！",
    PolicyCenter: "政策中心",
    NewOrder: "来自 %{from} 的新订单已到，请在批发站检查",
    Policies: "政策",
    PolicyNotEnoughTime: "此策略您没有足够的策略点",
    TimeLeft: "%{time} 余下",
    WholesaleCenterOrderFaster: "世界博览会",
    WholesaleCenterOrderFasterDesc: "批发站收到的订单快2倍，订单大小大2倍",
    PolicyOilWellPowerx2: "增压油井",
    PolicyOilWellPowerx2Desc: "油井产生2倍的石油，并使用2倍的功率",
    HalfTransportSpeed: "慢下来保存",
    HalfTransportSpeedDesc: "运输速度降低了25%，燃料成本降低了25%",
    RefineryMoreOil: "钼汽油钼问题",
    RefineryMoreOilDesc: "炼油厂的汽油产量增加了50%，塑料的产量减少了50%",
    StickyInput: "粘贴输入",
    StickyInputDesc: "建筑物将倾向于从以前的来源进行运输，而不是每个周期都寻找最佳的来源（免费政策）",
    RefineryMorePlastic: "钼塑料钼问题",
    RefineryMorePlasticDesc: "炼油厂的汽油产量减少了50％，塑料的产量却增加了50％",
    FreeOilTransport: "免费石油运输",
    FreeOilTransportDesc: "石油运输无需花费燃料，但油井使用的电力是原来的2倍",
    SuperSteelMill: "铁心",
    SuperSteelMillDesc: "钢铁厂的煤炭消耗量减少了50％，铁消耗量增加了25％，电力消耗增加了25％",
    AlSemiconductor: "铝电路",
    AlSemiconductorDesc: "电路代工厂使用铝代替铜",
    CostSaver: "节约成本",
    CostSaverDesc: "如果建筑物的投入成本大于产出，则停止生产",
    CostSaverBuildingDesc: "节省费用政策已生效，生产将根据其获利能力自动打开/关闭",
    CostSaverBuildingWarning: "成本节省程序策略处于活动状态，您不能手动更改生产",
    GlassUseCoal: "黑玻璃",
    GlassUseCoalDesc: "玻璃工厂使用的煤炭多50％，硅减少50％",
    AdjacentBonusOnlyOutput: "相邻奖金加成",
    AdjacentBonusOnlyOutputDesc: "相邻的奖金不需要更多的输入，但是会消耗更多的能量，并且只有50％的有效",
    IronMine2xOutput: "镀锌铁皮",
    IronMine2xOutputDesc: "铁矿产生的铁量是铁的2倍，但铁运输的燃料费是铁的2倍",
    SolarPanelAlwaysWork: "太阳永不落山",
    SolarPanelAlwaysWorkDesc: "太阳能板100％的时间工作，但产生的功率却少60％",
    SteelScience: "钢铁知识",
    SteelScienceDesc: "钢厂使用2倍的输入并产生额外的科学信息",
    ShowWarehouse: "解锁仓库",
    ShowWarehouseDesc: "仓库是一栋特殊的建筑物，只运输和存储资源，并且可以节省燃料（免费政策）",
    WholesaleCenterProducingOnly: "批发合作伙伴",
    WholesaleCenterProducingOnlyDesc:
        "批发中心订单仅包含当前正在生产的资源（您还需要提供一定数量的资源才能解锁批发中心）",
    ShoppingSpree: "疯狂购物",
    ShoppingSpreeDesc: "如果资源的输出容量不足，请从贸易中心自动购买短缺量（如果该资源已自动出售，则将被忽略）",
    ShoppingSpreeTradeCenterDesc: "💡 疯狂购物政策已启用，贸易中心将自动购买短缺的资源",
    ExtraPolicyPoints: "政治说客",
    ExtraPolicyPointsDesc: "将策略点的生产能力提高50%",
    CrAlloyUseFe: "铬",
    CrAlloyUseFeDesc: "铬合金工厂不使用锂，而是使用2x铁",
    DoubleTileModifier: "自然的力量",
    DoubleTileModifierDesc: "所有图块的修改器的效果x2-包括正数和负数",
    TileModifierOutputOnly: "瓷砖编辑更多",
    TileModifierOutputOnlyDesc: "平铺修饰符仅影响输出，而不影响输入和输出，但仅有效50％",
    GasPlantPetrol: "气体清洗器",
    GasPlantPetrolDesc: "天然气发电厂使用额外的天然气生产汽油",
    BuildingRecycle: "建筑回收",
    BuildingRecycleDesc: "在建造后1分钟内出售建筑物，可获得全额退款",
    CoalPlantFuel: "煤炭清洗器",
    CoalPlantFuelDesc: "煤炭发电厂使用额外的煤炭生产汽油",
    Welcome: "欢迎",
    SeeTutorialAgain: "恢复教程",
    ReadSteamGuide: "Steam官方指南",
    HelpTranslateTheGame: "帮助翻译游戏🌐",
    SkipTutorial: "跳过教程",
    NextTutorial: "下一步",
    Tutorial1:
        "闲置工业是一款 <em>资源管理</em>建造游戏🏭, 生产商品📦 并赚钱💸.<br><br>让我们通过一些基本的概念让你开始-这不会花很长时间，我保证",
    Tutorial2:
        "所有建筑物都需要电源⚡, 您有一台<em>风力发电机</em>可以发电。您可以在顶部栏的左侧看到当前的电源.<br><br>您可能已经注意到，风力发电机仅在 <em>80%</em> 的时间内工作。 您可以考虑建造其他类型的能够产生稳定电力的发电厂.",
    Tutorial3:
        "您有很多 <em>资源节点</em> 在地图上. 要提取资源, 您必须建造矿山⛏️ <em>在相应的矿床之上</em>。<br><br>例如, 您有一个 <em>油井🛢️</em> 那个提取物 <em>oil</em>从矿床中.<br></br>资源存款是无限的 - 无需担心它们耗尽。除了矿山，其他建筑物可以在任何空瓷砖上建造",
    Tutorial4:
        "资源运输成本燃料。在这个地图上， 您可以使用 <em>汽油⛽</em> 作为燃料。你有一个 <em>炼油厂</em>将石油从油井运送并产生汽油<br><br>微小的移动<em>dots</em> 代表资源的实时运动。 您应该优化您的建筑位置，以最大限度地减少旅行的距离.<br><br><em>升级</em>您的建筑将增加其产出, 但也将增加他们的电力使用和输入.<br><br>您可以在运输中心改变燃料类型🚦.记得确保您的燃料生产高于消费，否则您的生产将停止燃料时会停止",
    Tutorial5:
        "要赚钱，您需要通过贸易中心导出资源。要这样做，只需打开 <em>自动销售</em>为了那个资源.<br></br>您还可以从贸易中心购买资源。. 记住 <em>如果您购买资源，您将推动价格</em> 如果您销售资源，您将推动价格.<br><br>市场是 <em>易挥发的</em>和价格📈 定期变化.",
    Tutorial6:
        "要建造新建筑物，您需要先在<em>研究实验室🧪</em>中将其解锁. 研究实验室还将科学转换为研究要点。<br><br>您的风力发电机（和其他发电厂）在运行时会产生少量科学。 你可以建造学校🏫 和其他专用建筑物以后提升科学.<br><br>现在您已经了解到所有基础知识，开始建立您的经济！这里有一些<em>现金💸</em>和 <em>汽油⛽</em> 给你一个跳跃的开始.",
    WelcomePlay: "播放",
    WelcomePlayMuted: "播放 (🔇音乐)",
    Changelog: "变更日志",
    ChangelogGotIt: "知道",
    Chat: "聊天",
    Send: "发送",
    Import: "导入",
    Export: "导出",
    SteamCloudBackup: "Steam云备份",
    LastBackupAt: "最后备份",
    RestoreFromBackup: "从备份还原",
    RestoreFromBackupFail: "无法从Steam Cloud恢复备份：您确定有备份吗？",
    RestoreFromBackupTitle: "确定吗？",
    RestoreFromBackupDesc: "通常，您不需要从云备份中进行还原，除非丢失了本地保存。云备份比本地保存要早一些",
    ChatMessages: "聊天消息",
    ChatPlaceholder: "输入您的消息：最多100个字符",
    ChangeName: "更改",
    SaveName: "保存",
    NameValidationRule: "您的姓名只能包含字母和数字，且不得超过5至15个字符",
    NameValidationRuleProfanity: "您的名字不应该包含违规字符",
    ChatMessageRateLimit: "您只能每10秒发送一次新的聊天消息",
    NameSaved: "您的名称已成功更改",
    NoMessages: "没有新消息",
    Leaderboard: "排行榜",
    LeaderboardDesc: "排行榜得分是您所赚取的所有瑞士货币",
    Name: "名称",
    Rank: "排名",
    Tips1: "股票评级分为5个等级：买入，跑赢大盘，持有，跑输大盘和卖出",
    Tips2: "除非有足够的生产能力，否则建筑物将停止运输资源，除非您启用库存模式",
    Tips3: "资源运输的燃料成本取决于距离和资源量",
    Tips4: "只有在地图上找到的数量超过输入容量的情况下，建筑物才会运输资源",
    Tips5: "只有为该资源关闭自动销售功能，建筑物才会从贸易中心运输该资源",
    Tips6: "您可以在相应的输入容量部分下查看资源的燃料成本",
    Tips7: "如果您购买资源，则会提高价格。如果您出售资源，则会降低价格",
    Tips8: "您可以在统计局中查看每种资源的数量及其随时间变化的图表",
    Tips9: "建筑物所需的研究点取决于其投入资源的市场价格",
    Tips10: "不同的资源在市场中的定价不同-随时为市场波动做好准备",
    Tips11: "在扩大生产之前，始终检查功率和燃料供应是一个好主意",
    FPS30: "节能",
    OfflineModeDesc: "无法连接到服务器：将不会产生离线收入。请检查您的互联网连接",
    OptOut: "选择退出",
    OptIn: "重置并启用",
    LeaderboardOptOut: "退出排行榜",
    LeaderboardOptOutDesc: "这将不再发送排行榜得分。请注意：如果以后要启用排行榜，则需要重置数据",
    LeaderboardOptIn: "重置并启用排行榜",
    LeaderboardOptInDesc: "您必须先重置您的数据，然后才能重新启用排行榜，确定吗？",
    RewardAdsFailed: "奖励视频未完成",
    RewardAdsNotAvailable: "奖励视频不可用 (当前仅支持iOS/Android)",
    OfflineEarningDoubleSuccess: "您的离线收入已增加了一倍",
    FPS30Desc: "打开节能模式将使游戏以30FPS而不是60FPS的速度运行。这将使您的电池续航时间更长",
    HighlightAll: '高亮显示 "%{type}"',
    HighlightInput: "🔍 高亮显示 %{type} 输入",
    HighlightOutput: "🔍 高亮显示 %{type} 输出",
    TotalInput: "总输入容量",
    TotalOutput: "总输出容量",
    RunOutIn: "在 %{time}内用完",
    FuelRunOutWarning: "💡 您的燃料消耗超过了生产。当燃料用完时，您的运输将停止",
    InAmount: "在: %{number}",
    OutAmount: "出: %{number}",
    SwissBank: "瑞士银行",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "如果您从一个新城市开始，您将获得 %{money} 💵",
    RestorePurchases: "恢复购买",
    RestorePurchasesSuccess: "您的购买已恢复",
    RestorePurchasesFailed: "您的购买未还原",
    ExpansionPacks: "拓展包",
    ExpansionPack1: "拓展包1",
    ExpansionPack1Owned: "拓展包 1",
    RequireExpansionPack1: "拓展包 1",
    RequireExpansionPack1Desc: "这仅适用于拓展包 1",
    RequireAnyExpansionPack: "独家拓展包",
    RequireAnyExpansionPackDesc: "此功能要求您至少拥有一个扩展包",
    HideRewardAd: "隐藏奖励广告",
    HideRewardAdDesc: "所有游戏内广告都是可选的奖励广告。这将从游戏中隐藏所有奖励广告选项。",
    HideDiscordBanner: "隐藏Discord横幅",
    HideDiscordBannerDesc: "在总部隐藏Disord和店面横幅",
    HideChat: "隐藏聊天消息",
    HideChatDesc: "从底部工具栏隐藏聊天消息",
    SortedByDeficit: "按赤字排序",
    PurchaseFailed: "购买未完成",
    PurchaseSteamContinue: "请在Steam上完成购买",
    PurchaseSuccess: "购买已完成，感谢您的支持",
    PrestigeCurrency: "瑞士货币 💵",
    RestartDesc: "💡 只想重启？您可以点击上方的在新城市开始并选择您当前的城市",
    PrestigeGoBack: "返回",
    PermanentUpgradeDesc: "如果您从新城市开始，此升级将继续进行",
    ProductionMultiplier: "生产乘数",
    ProductionMultiplierDesc: "提高您所有建筑物的生产能力（包括矿山，工厂，发电厂，科学和文化建筑物）",
    FuelCostDiscount: "燃料成本折扣",
    FuelCostDiscountDesc: "在运输资源时为燃料成本提供折扣",
    AutoSellCapacityMultiplier: "自动销售能力乘数",
    AutoSellCapacityMultiplierDesc: "不管当前容量如何，都将应用于您的自动销售容量的乘数",
    BuildingPermitCostDivider: "建筑许可证成本划分器",
    BuildingPermitCostDividerDesc: "通过此分隔线划分建筑许可成本",
    ExtraAdjacentBonus: "额外相邻奖金",
    ExtraAdjacentBonusDesc: "每个相邻的相同类型的工作建筑物的额外奖励容量",
    OfflineEarningMultiplier: "离线收益乘数",
    OfflineEarningMultiplierDesc: "适用于离线收益的乘数",
    PrestigeAlertTitle: "确定吗?",
    PrestigeAlertContent: "您的公司将被清算。您将以 %{amount} 瑞士货币兑现并以 %{city}成立新公司",
    PrestigeCurrencyDesc: "这是你的秘密瑞士银行帐户的钱，你就可以带着它，当你在一个新的城市开始",
    Prestige: "现金到位",
    Cancel: "取消",
    SaveFileCorrupted: "存档文件损坏",
    CheatDetected: "您的旧存档未通过服务器验证，无法读取。您将以新存档开始",
    LoadGameError: "无法加载游戏",
    LoadGameErrorMessage: "错误消息: %{message}",
    LoadGameErrorDesc: "请检查您的互联网连接。如果问题仍然存在，请联系支持人员",
    ExpansionPackIncompatible: "您正在使用扩展包导入保存，但您的游戏没有所需的扩展包",
    SaveFileMigrated: "一个新时代：测试来了",
    SaveFileMigratedDesc:
        "感谢您在初始中进行游戏测试。您的旧地图不兼容，但是我们已经迁移了您的数据并为您提供了一些好处",
    ClaimSwissMoney: "索赔 %{amount} 瑞士货币 💵",
    SaveFileMigratedFinePrint:
        "您的市值转换为瑞士货币，您未使用的瑞士货币将结转。您将获得50％的瑞士钱用于进行游戏测试的最初奖金。可结转的瑞士最大货币上限为200",
    CashIn: "现金",
    CurrentCity: "当前城市",
    CashInDesc:
        "如果您在一个新的城市开始，您将把这笔款项存入您的瑞士银行帐户。这是基于您公司的市值，并且必须达到 %{amount} 才能赚取瑞士的钱",
    MoveToNewMap: "重新城市开始",
    CityName: "城市",
    CitySize: "地图大小",
    GridType: "网格类型",
    StartInThisCity: "从 %{city}开始",
    CityBonus: "城市奖励",
    ResourceTilePercentage: "资源块",
    MapSquareGrid: "正方形",
    MapHexGrid: "六边形",
    Stockholm: "斯德哥尔摩",
    StockholmBonus:
        "<li> 4级自由风轮机x1 </ li> <li> 4级自由油井x1 </ li> <li> 2级自由级炼油厂x1 </ li> <li>造纸厂已解锁</ li > <li>伐木场有2倍的输出量</ li>",
    Rotterdam: "鹿特丹",
    RotterdamBonus:
        "<li>钢厂的产能是2倍</ li> <li>不锈钢厂的产能是2倍</ li> <li>免费铁运输</ li> <li>钢运输的燃料成本降低了50％</ li> <li>以2倍的自动销售容量开始</ li> <li>没有磁贴修饰符</ li>",
    Oslo: "奥斯陆",
    OsloBonus:
        "<li>炼油厂的产能是2倍</ li> <li>天然气加工厂的产能是2x </ li> <li>汽油发电厂是2x产能</ li> <li>钢厂使用天然气而不是煤炭</ li> <li>免费石油运输</ li>",
    StPetersburg: "圣彼得堡",
    StPetersburgBonus:
        "<li>铀矿的产量是2倍</ li> <li>铀浓缩厂的能力是2倍</ li> <li>铀的运输成本降低了50％的燃料</ li> <li>免费的枪支运输</ li> <li>导弹工厂使用浓缩铀代替钛和铀</ li>",
    Hamburg: "汉堡",
    HamburgBonus:
        "<li>策帕林工厂开锁</ li> <li>半导体工厂的产能是原来的2倍</ li> <li>造船厂的产能是原来的2倍</ li> <li>汽车工厂的产能是原来的2x </ li> <li>锂离子电池工厂已解锁</ li>",
    Toulouse: "图卢兹",
    ToulouseBonus:
        "钛矿的产量是原来的2倍</ li> <li>铀浓缩工厂的产量是原来的2倍</ li> <li>喷气发动机工厂的产能是原来的2倍</ li> <li>飞机工厂的生产率是2倍。</ li > <li>火箭工厂使用铀代替浓缩铀</ li>",
    Rome: "罗马",
    RomeBonus:
        "<li>斗兽场被解锁</ li> <li>斗兽场的生产率是2倍</ li> <li>从5级政策中心开始</ li> <li>歌剧院的能力是2倍</ li> <li>录音室也产生文化</ li>",
    Detroit: "底特律",
    DetroitBonus:
        "<li>发动机工厂已解锁</li><li>发动机工厂的生产率是原来的2倍</li><li>汽车工厂的产能是原来的2倍</li><li>汽车工厂不需要电池</li><li>火车工厂的产能是原来的2倍</li>",
    Boston: "波士顿",
    BostonBonus:
        "<li>从5级研究实验室开始</li><li>理工学院被解锁</li><li>理工学院的能力是2倍</li><li>学校具有2倍的能力</li><li>大学生产力提高了2倍</li>",
    HideNotProducing: "隐藏未生产的资源",
    SortByStorage: "储存",
    SortByProduction: "生产",
    SortByName: "名称",
    BuildingInProgressCannotPrestige: "您的房屋建筑正在进行中，在完成之前您不能在新城市开始建造",
    PlayerTrade: "玩家交易",
    AddTradeFail: "添加交易失败",
    AddTradeValidationFail: "交易金额和价格必须大于0",
    AddTradeExceedMaximumTrade: "您最多只能有 %{number} 个有效交易，请先领取或者取消其中之一",
    AddTradeSuccess: "您的交易已成功添加",
    LoadTradeFail: "无法加载玩家交易，请稍后再试",
    ClaimTradeFail: "无法进行此交易，请稍后再试",
    ClaimTradeSuccess: "您的交易已成功领取: $%{cash} 已添加到您的账户中",
    CancelTradeSuccess: "您的交易已成功取消",
    CancelTradeFail: "无法取消此交易，请稍后再试",
    AcceptTradeSuccess: "您已接受此交易: %{resource} 已添加到您的交易中心",
    AcceptTradeFail: "无法接受此交易，请稍后再试",
    PlayerTradeBanner: "与其他玩家交易资源",
    PlayerTradeResource: "资源",
    PlayerTradeAmount: "金额",
    PlayerTradePrice: "价格 $",
    PlayerTradeValue: "价值 $",
    PlayerTradeWaiting: "正在等待...",
    UseTradeCenterPrice: "使用贸易中心价格",
    AddTrade: "添加交易",
    ActiveTrades: "活跃交易",
    AcceptTrade: "接受",
    CancelTrade: "取消",
    ClaimTrade: "领取",
    RefreshTrade: "刷新",
    RefundTrade: "Refund",
    RefundTradeSuccess: "This trade has been refunded: %{resource} has been refunded to your trade center",
    RefundTradeFail: "Failed to refund this trade, please try again later",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    FailedToCheckActiveTrade: "Failed to check active player trades, please try again later",
    PlayerTradePriceNotValid: "Trade price must be between %{min} and %{max} (2 x Last Market Update Price)",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeAmountNotValid: "Trade amount must be greater than 0",
    PlayerTradeValidRange: "Range: %{min} ~ %{max}",
    PlayerTradeFilterPrice: "Below Market Price",
    PlayerTradeFilterCanAfford: "Can Afford",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
};
